### ISSUE TITLE
Consider changing the extension name of dump and snapshot

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1010]
**Is your feature request related to a problem? Please describe.**
For the moment when creating `dumps` or `snapshots` a file is created with a `tar.gz` extension. This leads to believe that information inside can be unzipped and used. Which they are for dumps.

This is an unwanted perk. The problem with it being a perk is that we need to maintain it. Users will get used to this perk and changes to it will have to be notified. 

> we want to be free to completely change the content or the compression without impacting users

**Describe the solution you'd like**
By changing the extension for `tar.gz` to respectively `dump` and `snapshot` user are not inclined to uncompress it and use it elsewhere as those will be MeiliSearch files.

**Describe alternatives you've considered**
Encode the content of the file.

**Comment by eskombro** [comment]
IMHO, I think it's fine as it is, if some user wants to open/uncompress or use somehow those files is totally fine, nobody is stating anywhere that this is a feature, it will be maintained, or should be reliable. But it let's indeed people find a usage to those files, and if he/she does, than that's cool, why not?

**Comment by LegendreM** [comment]
The reason is:
- we don't want to maintain alternate usages of it
- we want to be free to completely change the content or the compression
