### ISSUE TITLE
Feature Request: Document Time to Live

### ISSUE THREAD

**Issue by ShivanshVij** [meilisearch/MeiliSearch#1012]
**Is your feature request related to a problem? Please describe.**
Sometimes I have documents that I need indexed in MeiliSearch that I want to have automatically deleted after a while. Right now I'd have to add some sort of creation timestamp to the document and then run a cron-job to delete things. 

**Describe the solution you'd like**
What I'd like is a TTL (Time to Live) property that can be set on an index that will cause documents to "expire" or get deleted automatically. 

**Describe alternatives you've considered**
The only alternative solution I've been able to find is adding a creation timestamp to the document and then running a cron-job to delete things. 

**Additional context**
N/A

**Comment by LegendreM** [comment]
Hello @ShivanshVij, thanks for your feature request, we will discuss it.
A possible workaround is to add an `expiration_date` attribute in your documents, add it as a facet and create a cronjob that delete document filtering on a facet.


POST documents
```json
[
  {
    "title": "many the fish",
    "body": "To Be Liked By Many Is Awful",
    "expiration_date": "yyyymmddHH"
  },
// ... other documents
]
```


POST settings
```json
{
       // ... other settings
        "attributesForFaceting": [
            "expiration_date"
        ]
}
```

SEARCH on `/search?facetFilters=["expiration_date:yyyymmddHH"]`
```json
[
{
  "id": 5,
  // ...
},
{
  "id": 87,
  // ...
},
// ...
]
```

POST `documents/delete-batch`
```json
[
  5,
  87,
  // ...
]
```

with this example I would trigger my cronjob hourly but if you want to pass daily the expiration date would be `"expiration_date": "yyyymmdd"`.

I hope it might help!

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/68-delete-by-filters?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to update it on the roadmap.

**Comment by liesislukas** [comment]
link above is broken, here is current: 

https://roadmap.meilisearch.com/c/103-delete-documents-by-filters

**Comment by tomazz75** [comment]
This link currently returns this error

<img width="779" height="593" alt="Image" src="https://github.com/user-attachments/assets/e27b52bb-61fe-4c16-8f9f-8e8cddce494c" />
