### ISSUE TITLE
Improve Dumps

### ISSUE THREAD

**Issue by theswerd** [meilisearch/MeiliSearch#1019]
**Is your feature request related to a problem? Please describe.**
When I create Meilisearch dumps, I don't want to store them on the container/volume/computer that I am dumping from, I want to export them. I would like more tools for exporting dumps.

**Describe the solution you'd like**
1. The ability to add API Hooks to the events in the process (Dump started, Dump finished, Dump in progress)
2. The ability to set dumps to run at a set interval
3. The ability to export to an external URL rather than a local folder

**Describe alternatives you've considered**
For now I am looking into build a script that gets a dump once a day and exports it.

**Other Info**
- [How Postgres Covers Dumps](https://www.postgresql.org/docs/current/backup-dump.html)

Ps. I love using MeiliSearch!

**Comment by LegendreM** [comment]
related to #1023

**Comment by yashiroiori** [comment]
> **Is your feature request related to a problem? Please describe.**
> When I create Meilisearch dumps, I don't want to store them on the container/volume/computer that I am dumping from, I want to export them. I would like more tools for exporting dumps.
> 
> **Describe the solution you'd like**
> 
> 1. The ability to add API Hooks to the events in the process (Dump started, Dump finished, Dump in progress)
> 2. The ability to set dumps to run at a set interval
> 3. The ability to export to an external URL rather than a local folder
> 
> **Describe alternatives you've considered**
> For now I am looking into build a script that gets a dump once a day and exports it.
> 
> **Other Info**
> 
> * [How Postgres Covers Dumps](https://www.postgresql.org/docs/current/backup-dump.html)
> 
> Ps. I love using MeiliSearch!

About sort, I think make similar to Algolia make multiples index with each sort a need

Excellent, thank you

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/66-download-dumps?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to update it on the roadmap.
