### ISSUE TITLE
Cors error returned instead of authentication_error on wrong API key in browser

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1021]
**Describe the bug**
Previously when integrate MeiliSearch in a browser script and run it without API key or with a wrong API key I would receive a `authentication_error`.
Since v0.15 i receive a CORS error.

**To Reproduce**
1. Launch a MeiliSearch instance with a masterKey
2. Use the following code in a http file (notice it does not use a master key)
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
</head>
<body>
    Indexes:
    <div id="indexes"></div>
</body>
</html>
<script src="../../dist/bundles/meilisearch.umd.js"></script>
<script>
  const client = new window.MeiliSearch({
    host: 'http://127.0.0.1:7700',
  })
  client.listIndexes().then(res => {
    console.log({ res });
    res.map(index => document.querySelector('#indexes').innerHTML = `<div>${index.name}</div>`)
  })
</script>

```
3. Open the html file or run a http server using `http-server yourhtmlfile.html`
4. Open it on a browser and look at the console

**Expected behavior**
Return the `authentication_error` body instead of a CORS error as it not clear what failed.

```json
{
  "message": "You must have an authorization token",
  "errorCode": "missing_authorization_header",
  "errorType": "authentication_error",
  "errorLink": "https://docs.meilisearch.com/errors#missing_authorization_header"
}
```

**Screenshots**

v.0.15:
<img width="777" alt="Screenshot 2020-10-15 at 14 00 37" src="https://user-images.githubusercontent.com/33010418/96120519-ead89580-0eee-11eb-8ec9-1ec9026bcc9f.png">

**Comment by bidoubiwa** [comment]
After further investigation, this is how to reproduce the problem 👍 

1. Start a meilisearch server v0.15 > **with** a masterKey
2. Make call to that MeiliSearch inside your browser without adding a api key
3. CORS error instead of authentication error body.


Minimal code to reproduce : 

```html
<!DOCTYPE html>
<html>
</html>
<script>
  fetch('http://localhost:7700/indexes/movies/search?q=batman').then(res => {
    console.log({ res });
  })
</script>
```

**Comment by tristantbg** [comment]
I am facing the same problem with Nuxt/Vue while trying to fetch results from my Meilisearch instance :

1. Go on monsieurlagent-li1evd768.vercel.app
2. Click on "Explore"
3. See the 500 error and look at the console
4. Reload the page (it works because the fetch is made with SSR on server side)
5. Make a search 
6. It doesn't work because it is made with SPA

**Comment by bidoubiwa** [comment]
Hey @tristantbg could you provide a public repository with this error?

**Comment by tristantbg** [comment]
> Hey @tristantbg could you provide a public repository with this error?

Here is sandbox : https://codesandbox.io/s/meilisearch-cors-vnw77?file=/pages/index.vue

It works locally but not in a production server...
See here : https://vnw77.sse.codesandbox.io

**Comment by bidoubiwa** [comment]
The way I reproduce the error is by either adding a wrong API key or a wrong API key. Instead of returning an error telling me I have no authorization, it makes a CORS error. 
Could you check that your API key is correct on your production server?

**Comment by tristantbg** [comment]
> The way I reproduce the error is by either adding a wrong API key or a wrong API key. Instead of returning an error telling me I have no authorization, it makes a CORS error.
> Could you check that your API key is correct on your production server?

Just fixed it ! Sorry, I put the key in the private ENV variables.

**Comment by tristantbg** [comment]
Any news on this ?

**Comment by tristantbg** [comment]
It seems to work when the apiKey is not stored inside `process.env` but is exposed publicly.

**Comment by bidoubiwa** [comment]
I'm don't think you can access `process.env` when running your script in a browser. It is a [node specific](https://nodejs.org/api/process.html) API. I think that you don't send any API key. In which case you receive the CORS error because your API key is undefined. Could you console.log `process.env` where you use it?

**Comment by tristantbg** [comment]
> I'm don't think you can access `process.env` when running your script in a browser. It is a [node specific](https://nodejs.org/api/process.html) API. I think that you don't send any API key. In which case you receive the CORS error because your API key is undefined. Could you console.log `process.env` where you use it?

Yes I guess this was the error since it works as expected now !

**Comment by mdubus** [comment]
This error makes error handling in the front-end a bit crafty.

Is this bug planned to be fixed in the next releases ? Thanks 🙏

**Comment by mdubus** [comment]
in the meanwhile, here is how to get around the problem : 

```js
if (error.type === 'MeiliSearchCommunicationError') {
  const status = await searchClient.client.isHealthy()
  if (status) {
    // server is healthy, API Key error will fall here
  } else {
    // server is not healthy
  }
}
```

**Comment by curquiza** [comment]
Thanks for your workaround @mdubus!

It will not be included in the next release (v0.20.0) sorry, but we will try to include it in the v0.21.0 (new search engine release) -> https://github.com/meilisearch/transplant/issues/110
You can check all the milestones of MeiliSearch here: https://github.com/meilisearch/MeiliSearch/milestones
More precisely, here are the milestone of the v0.20.0: https://github.com/meilisearch/MeiliSearch/milestone/19?closed=1

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421

**Comment by bidoubiwa** [comment]
I just tried with v0.21 and received the same error. 

```
localhost/:1 Access to fetch at 'http://localhost:7700/indexes' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
http-requests.ts:50 GET http://localhost:7700/indexes net::ERR_FAILED
request @ http-requests.ts:50
get @ http-requests.ts:85
listIndexes @ meilisearch.ts:71
(anonymous) @ main.js:9
(anonymous) @ main.js:15
http-error-handler.ts:20 Uncaught (in promise) MeiliSearchCommunicationError: Failed to fetch
    at httpErrorHandler (http-error-handler.ts:20)
    at HttpRequests.request (http-requests.ts:64)
    at async HttpRequests.get (http-requests.ts:85)
    at async MeiliSearch.listIndexes (meilisearch.ts:71)
    at async main.js:9
```

**Comment by bidoubiwa** [comment]
Could not reproduce with latest v0.21 so all good for me
