### ISSUE TITLE
Facet price range, order asc/desc

### ISSUE THREAD

**Issue by yashiroiori** [meilisearch/MeiliSearch#1029]
Hi, meilisearch its amazing

I have some questions:
1. Into facets it's posible to get a low an hight number?? to use a range slide
2. How do to order asc/desc the hits results like a: name, brand, date, etc.

**Comment by atresnjo** [comment]
I'd be interested to know this also. I want to give meilisearch a shoot for a simple product search, thus a price filter would be nice!

**Comment by curquiza** [comment]
Hello @yashiroiori and @atresnjo
Glad to read you like MeiliSearch!! 😁

> Into facets it's posible to get a low an hight number?? to use a range slide

No, unfortunately, it's not possible for the moment, but we have an issue open for this if you want to 👍 it! https://github.com/meilisearch/MeiliSearch/issues/919

> How do to order asc/desc the hits results like a: name, brand, date, etc.

A solution might be to create a custom criterion in your ranking rules. Here is the section about the [relevancy of MeilISearch](https://docs.meilisearch.com/guides/main_concepts/relevancy.html) but this [specific paragraph to add our own rule](https://docs.meilisearch.com/guides/main_concepts/relevancy.html#adding-your-rules) might interests you.
But maybe @Kerollmops or @LegendreM might suggest a better solution or confirm what I suggest?

**Comment by yashiroiori** [comment]
> Note that the asc/desc ordering can only be done on numbers (u64, f64) not on names or brands.

Yes, I see that in documentation

To make a facets not accept numbers values?? Can't make a facet for example with year where is an integer and the year when are string it's make facet without problem

**Comment by yashiroiori** [comment]
> Hello @yashiroiori and @atresnjo
> Glad to read you like MeiliSearch!! 😁
> 
> > Into facets it's posible to get a low an hight number?? to use a range slide
> 
> No, unfortunately, it's not possible for the moment, but we have an issue open for this if you want to 👍 it! #919
> 
> > How do to order asc/desc the hits results like a: name, brand, date, etc.
> 
> A solution might be to create a custom criterion in your ranking rules. Here is the section about the [relevancy of MeilISearch](https://docs.meilisearch.com/guides/main_concepts/relevancy.html) but this [specific paragraph to add our own rule](https://docs.meilisearch.com/guides/main_concepts/relevancy.html#adding-your-rules) might interests you.
> But maybe @Kerollmops or @LegendreM might suggest a better solution or confirm what I suggest?

I thinking make similar how do Algolia make multiples index with order I need example: year_asc, year_desc, price_asc, price_desc

**Comment by inluxc** [comment]
I got the same problem with the price range and I got my client, pushing me to another solution.
This is a must for eCommerce solutions.

**Comment by qdequele** [comment]
Hello, Thanks for these feature proposals! 

I will close this issue in favor of our public roadmap. We have here 2 features:
- The [search for facet value](https://roadmap.meilisearch.com/c/64-search-for-facet-values?utm_medium=social&utm_source=portal_share).
- The [sort by](https://roadmap.meilisearch.com/c/32-sort-by?utm_medium=social&utm_source=portal_share).

I invite everyone interested in this feature to upvote it on the roadmap.
