### ISSUE TITLE
movies.json has two different fields "genre" and "genres"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1030]
Following this comment https://github.com/meilisearch/MeiliSearch/commit/d937aeac0a27ef21873b1a186ce2270968621815#commitcomment-43423208

We might check that we don't have the same issue on the other datasets 🙂

**Comment by bidoubiwa** [comment]
It should be changed to genres everywhere.

**Comment by bidoubiwa** [comment]
You can assign me on this

**Comment by curquiza** [comment]
It's fixed now, closing
