### ISSUE TITLE
dump/snapshot env variables and options

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1033]
**Is your feature request related to a problem? Please describe.**
For the moment in the dump and snapshot design we have the following `env variables`/`cli options`: 
- --schedule-snapshot
- --snapshot-dir
- --snapshot-interval-sec
- --import-snapshot
- --ignore-missing-snapshot
- --ignore-snapshot-if-db-exists
- --dumps-dir
- --import-dump
- --dump-batch-size

There are two inconsistent cases within these options: 

1. If the directory of a snapshot is given but the snapshot is not activated => `--snapshot-dir` but not `--schedule-snapshot` 
    => nothing happens. **No error is thrown**.
2. If `--ignore-snapshot-if-db-exists` and `--ignore-missing-snapshot` are given but not `--import-snapshot`
    => **Error is thrown** because those options can only be added when a snapshot is imported

### 1. Both behaviors should be consistent. 

**Option A**:  In both cases, no error is thrown but a warning is given
**Option B**. In both cases, we stop MeiliSearch and throw an error.
**Option C**. In both cases, no error is thrown and no warning is given.
**Option D**. Both behaviors should not be consistent, the way it is right now is good.

### 2. Should all options have an env variable equivalent

**Option A**: yes

**Option B**: no, in this case, all options that are **only** used on launch should never have an ENV_VAR equivalent.
This means: 
- --import-snapshot
- --import-dump
- --ignore-missing-snapshot
- --ignore-snapshot-if-db-exists

Will have NO corresponding:
- MEILI_IMPORT_SNAPSHOT
- MEILI_IMPORT_DUMP
- MEILI_IGNORE_MISSING_SNAPSHOT
- MEILI_SNAPSHOT_IF_DB_EXISTS

**Option C**: No, options that generate errors should never have an ENV_VAR equivalent 
This means: 
- --ignore-missing-snapshot
- --ignore-snapshot-if-db-exists

Will have NO corresponding:
- MEILI_IGNORE_MISSING_SNAPSHOT
- MEILI_SNAPSHOT_IF_DB_EXISTS

### 3. Should options removing error exists?
 In the case of the following errors: 
- --ignore-missing-snapshot
- --ignore-snapshot-if-db-exists

The user might use then in the following scenario: 
```bash
./meilisearch --import-snapshot bad_path/snapshot --ignore-missing-snapshot=true
``` 
In which case MeiliSearch will **not** import because he could not find a snapshot. But MeiliSearch will also **not** throw an error because of the `--ignore-missing-snapshot` option. Resulting in MeiliSearch not doing anything differently than if you had NOT given any of those two options.

Should the user not create their own manual or automatic check with another script instead of using options that remove usage obligations?

**Option A**: Yes. In which case we remove the following options and their env variable.
- --ignore-missing-snapshot
- --ignore-snapshot-if-db-exists

**Option B**: No. Nothing changes.

## How to Vote

Please state the problem number and the solution letter. Example:

- 1 - B
- 2 - A
- 3 - B

Feel free to suggest add any other solution or any other problem.

**Comment by bidoubiwa** [comment]
1 - A
2 - A or B 
3 - A

**Comment by eskombro** [comment]
1. B      (seems cleaner: invalid options, I don't run your thing)
2. C
3. _       (Didn't understand :) )

**Comment by LegendreM** [comment]
```
--import-snapshot
--import-dump
```
generate errors and take part to C

**Comment by MarinPostma** [comment]
1 - D (I makes sense for me that `snapshot-dir` exists without snapshot being made from startup)
2 - B
3 - B

**Comment by LegendreM** [comment]
team DBB.

**Comment by curquiza** [comment]
1. D : I thought we ask for the Boolean ˋ--schedule-snapshot` to to let the devops configure the snapshot but without necessarily active it. The purpose is to activate it when wanted. So for me it should not throw an error. Maybe a warning but I understand that not everyone is a big fan of warnings 😁
2. As I said in the PR I'm not aware of the env variables usage at all, so I don't know what to chose. I would say B but not really sure at all. 
3. B

**Comment by eskombro** [comment]
DBB seems to be a winning team :)

**Comment by bidoubiwa** [comment]
Let's go for DBB then!
