### ISSUE TITLE
Question: Combine facets with filter

### ISSUE THREAD

**Issue by yashiroiori** [meilisearch/MeiliSearch#1039]
Hi
When set a filter example price and select a facet filter the response about de hits it's correct but the count of facets no chance

Filter price > 15000 AND price < 160000 and brand:acura the response say have 1 but it's not true, not have any car with that price range
![image](https://user-images.githubusercontent.com/17031855/96898982-f7606f00-1455-11eb-8136-e19ca1f0f136.png)

The response say I have 3389 hits with and without filter price
![image](https://user-images.githubusercontent.com/17031855/96899238-48706300-1456-11eb-94e2-b7ddd2ffce23.png)

Without price filter it's same response
![image](https://user-images.githubusercontent.com/17031855/96899587-b61c8f00-1456-11eb-80fe-da22c6cfe078.png)

It's a bug?? or how to get correct counting into facets using filter

**Comment by MarinPostma** [comment]
Hello @yashiroiori, we are well aware of this, and there is currently an open pr trying to resolve that #849. The nbHits is an approximation that always overestimate the total number of results. In most cases it is not possible to have an exact number, but we are planning to make this approximation better and better over time
