### ISSUE TITLE
Reload certificates files without restarting meilisearch process

### ISSUE THREAD

**Issue by hadjedjvincent** [meilisearch/MeiliSearch#1041]
**Is your feature request related to a problem? Please describe.**

When using `--ssl-cert-path` & `--ssl-key-path` parameters, it looks like the certificate isn't getting updated by the meilisearch process.
For example, if you are using a LetsEncrypt certificate, and this certificate gets updated.
MeiliSearch process will not detect this change, and the certificate will get marked as expired (but is valid into filesystem).
To fix this, MeiliSearch process must be restarted.

**Describe the solution you'd like**

nginx or apache2 provide a reload function to prevent any downtime regarding the HTTP service.

Could a reload command or some kind of watcher could be added on SSL cert & keys files?
Or do we have to implement a custom process that will restart MeiliSearch when the certificate gets updated ?

**Comment by LegendreM** [comment]
Hello @hadjedjvincent,
meilisearch doesn't handle ssl certificate reloading,
it's not a priority for us for the moment,
the only workaround you have is to deactivate ssl on meilisearch and use nginx or kong to proxify the ssl management,

thanks for sharing your needs
