### ISSUE TITLE
Dynamic search by specified fields

### ISSUE THREAD

**Issue by senyast4745** [meilisearch/MeiliSearch#1042]
Kind time of the day. As far as I understand now, the search occurs in all fields that are set as search fields. I would like to know if it is possible to dynamically transfer a field or a set of fields that I would like to search. For each field, I would like to specify your request.

For example: `{" field1 ":" search text "," field2 ":" searchText "}`. It seems to me that it would speed up the search a little + simplify the filters

**Comment by Kerollmops** [comment]
Hey @senyast4745,

Unfortunately this is not possible with the current engine and will likely be impossible in the future, this is a major change in the internal engine design. Maybe you can create multiple indexes with the searchable fields combinations that fits your need as a workaround?

Would it be possible that you describe you use case in more details please?

**Comment by senyast4745** [comment]
Thank you for the answer.  My use case is to use your engine as a search engine for logs. I want to write my own adapter for fluentd and display logs like Kibana.  This idea arose from the fact that now the main system for visualizing logs is ELK, but this system takes up too much RAM.

**Comment by Kerollmops** [comment]
I wasn't aware that Elastic was able to do so, even if I know that elastic can do anything while hitting all of the RAM. Unfortunately I will close this issue as this is not something that we will work on now, or in the near future.

Thank you for your interest in the project, however :)
