### ISSUE TITLE
How to make "or" query?

### ISSUE THREAD

**Issue by jet10000** [meilisearch/MeiliSearch#1043]
query="a b or c"

**Comment by MarinPostma** [comment]
Hello! Can you elaborate a little bit on what you want to achieve?

**Comment by jet10000** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/query-dsl-bool-query.html

must, should, must_not

How to make [must, should, must_not] search.

**Comment by Kerollmops** [comment]
We doesn't plan to implement the should, must and must_not operations of ElasticSearch in MeiliSearch, we would like to keep it simple, but maybe one day we will work on a query language or a similar feature if many people request it.

However, thank you for sharing your needs with us! Cheers!
