### ISSUE TITLE
Highly available distributed indexes

### ISSUE THREAD

**Issue by rustysys-dev** [meilisearch/MeiliSearch#1049]
MeiliSearch seems to be a very interesting project, and I am thinking about promoting it for my team to use in our IoT platform.  That being said, there are a few things I would like to inquire about.

I would like to know what thoughts the MeiliSearch team has regarding highly available distributed indexes.

Essentially I would like to run three or more instances of MeiliSearch behind a load balancer that manage the same index to provide high availability and fault tolerance.  Is this something that is a goal for the project?

**Comment by MarinPostma** [comment]
Hello @rustysys-dev this is indeed something that's being worked on currently. We can't provide any ETA on when this will become available however

**Comment by rustysys-dev** [comment]
> Hello @rustysys-dev this is indeed something that's being worked on currently. We can't provide any ETA on when this will become available however

Sounds great!  I will keep an eye out for this feature.  If you have a kanban or task list that you are using to track features with maybe I can offer some support.

**Comment by MarinPostma** [comment]
There is this pr https://github.com/meilisearch/MeiliSearch/pull/931 that contains the current advancement on the subject, it is still messy and buggy, but help could be appreciated there, and there is our public roadmap: https://github.com/orgs/meilisearch/projects/2 :)

**Comment by rustysys-dev** [comment]
This is perfect! I will take a look at this now!

**Comment by genofire** [comment]
PR and Project is closed (or not available) anymore.
Are there new PRs / Issues to track?

**Comment by gmourier** [comment]
Hey @genofire 👋

It is a subject that has been stopped to focus on other more immediate ones.

We will come back, I think, in the future on it nevertheless I can't share with you a precise ETA.

Thanks

**Comment by liesislukas** [comment]
Looking how to run meilisearch cross-regions, any hints?

**Comment by curquiza** [comment]
Hello @liesislukas 

We don't handle feature requests in this repository 😊 

For people following this PR, please refer to the discussion in the [product repository](https://github.com/meilisearch/product/discussions) instead like:
- https://github.com/meilisearch/product/discussions/575
- https://github.com/meilisearch/product/discussions/215
