### ISSUE TITLE
Degraded queries

### ISSUE THREAD

**Issue by hah** [meilisearch/MeiliSearch#1051]
Hi, Any plans to introduce a similar degraded system as Algolia [has](https://www.algolia.com/doc/faq/searching/what-are-degraded-queries-and-how-do-they-work/)?

Basically in case of a request spike, not as many results are returned, but the response is still quick, and relevant

Maybe there is already a feature, but I could not find anything in the docs. thanks a lot

**Comment by Kerollmops** [comment]
Hey,

Thank you for helping us, indeed this is something we would like to add to the engine at a moment. We are currently working on improving the engine right now and will take you issue into account.

The first thing we want to work on is to keep the engine fast enough to be sure that we don't rely on degraded query even when query must be non-degraded and the engine must have answered fast enough.

Thank you anyway!
