### ISSUE TITLE
Phrase search / Exact match

### ISSUE THREAD

**Issue by ayalon** [meilisearch/MeiliSearch#1060]
**Is your feature request related to a problem? Please describe.**
I have a lot of documents with special characters like . (dots) and , (commas). THe most common use case is to search for an exact match:

"1. Title Chap. 2,3"

**Describe the solution you'd like**
Currently the tokenizer strips all . (dots) and , (commas). Using phrases with quotes is not supported as far as I see. If there is a way or a possibility to find all documents with the query above, please instruct me how to achieve that.

**Describe alternatives you've considered**
Algolia supports a phrase (query language) and also Lucene supports a query parser language.

Not having the possibility so search for an exact phrase can be a tough show stopper for a lot of scientific searches. I know, that meilisearch targets dummy users that just type a word and want a fast result.
But meilisearch could also be a successful search engine for scientific documents. 

Even more if I could define a language specific tokenizer. But this is an other topic.

**Comment by MarinPostma** [comment]
related to #902

**Comment by Kerollmops** [comment]
Hello,

The phrase/exact search feature is something we would like to support, however the complexities of being able to search in documents with words that are abreviated and chapter numbers is a little more complex but we will look into maybe a setting that will allow the user to specify settings by document attributes and therefore be able to force the engine to ignore punctuation.

The "2,3" will be supported by the new incoming tokenizer.

Thank you for this well described issue :)

**Comment by ayalon** [comment]
Great news! Thanks a lot for this Open Source effort! You are doing a great job and many (anonymous) user appreciate your hard work!

I really appreciate your help and looking forward to a possibility in meilisearch for phrase/exact search. If there is a new version or something to test, please mention it in this thread so I can test it.

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/77-phrase-query?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.

**Comment by 2567910** [comment]
is there any update on this?

**Comment by curquiza** [comment]
Hello @2567910 it's now possible
you can quote your query in the `q` parameter
