### ISSUE TITLE
Remove the Maintenance error

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1061]
Since the health route has been updated, the `Maintenance` error is not used anymore.

https://github.com/meilisearch/MeiliSearch/blob/4398f2c0234cc6c25910572a8eea59db66c3bb47/meilisearch-http/src/error.rs#L37-L58

Should we remove it?

Related discussion: https://github.com/meilisearch/documentation/pull/564#issuecomment-712812581

Not an emergency of course! 🙃

**Comment by MarinPostma** [comment]
Uhmm two options here:
- Meilisearch-error is a library and this error is just part of the exposed api
- it's dead code and we should remove it

I'm a partisan of the first former.

**Comment by bidoubiwa** [comment]
I'm not sure what the best practice is in this case, if meilisearch-error is a library it should not be dependant on MeiliSearch's behavior. But we also would like to avoid contributors seeing it and trying to incorporate them in their code, as they did in this PR: 
https://github.com/meilisearch/meilisearch-js/pull/635.

**Comment by MarinPostma** [comment]
we will remove it
