### ISSUE TITLE
Index Replicas

### ISSUE THREAD

**Issue by inluxc** [meilisearch/MeiliSearch#1067]
**Is your feature request related to a problem? Please describe.**
We need Index Replicas, like on Algolia we need to create replicas to add different sort rules.

**Describe the solution you'd like**
So we don't need to create different indexes to add different rules and always sync the differences in all of them. 
The replicas would always be synced with the index data, just the setting would change.

**Describe alternatives you've considered**
Duplicating indexes.

**Additional context**
Example:
**Product (index)**
- Product_Price_ASC (replicas)
- Product_Price_DESC (replicas)
- etc....

**Comment by MarinPostma** [comment]
this is related to #730

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/32-sort-by?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
