### ISSUE TITLE
Improve documentation and error messages when adding fields for facetting which contain unsuitable data 

### ISSUE THREAD

**Issue by bb** [meilisearch/MeiliSearch#1068]
I tried to configure some `attributes_for_faceting` on an existing index by "brute force", i.e. just taking all existing fields and configuring them and see if it raises an error.

I'm using server version 0.16 installed using brew on mac. I was using the meilisearch-ruby client 0.14.0, but I think the specific client is not relevant here.

### Case 1: Invalid attribute type mentions attribute value but not field name

Output was of `index.get_all_update_status` was
````
  ...
  "error"=>"error processing facet filter: invalid document attribute 2, accepted types: String and [String]",
  "errorType"=>"invalid_request_error",
  "errorCode"=>"invalid_facet",
  "errorLink"=>"https://docs.meilisearch.com/errors#invalid_facet",
  ...
````
Solution I'd like: Please also mention the attribute name and not only the field value which caused the error.

### Case 2: Internal error instead of specific error

```
  "error"=>"heed error; MDB_BAD_VALSIZE: Unsupported size of key/DB name/data, or wrong DUPFIXED size",
  "errorType"=>"internal_error",
  "errorCode"=>"internal",
  "errorLink"=>"https://docs.meilisearch.com/errors#internal",
```

I'm still in progress of investigating what the specific case is, but in Slack, @Kerollmops hinted at a possible limit of 512 bytes for facet values.

Solutions:
* Add limitations in value size to the facet documentation
* Raise `invalid_facet` error instead of `internal`
  * maybe solved by this: provide the invalid value
  * maybe solved by this and solution for case 1 above: provide the invalid field

**Comment by MarinPostma** [comment]
Thanks a lot @bb, for this very detailed report. You are right those points need to be addressed, I will create the relevant issues so this gets done 👍

**Comment by MarinPostma** [comment]
closing in favor of #1071 and #1072
