### ISSUE TITLE
Provide more index/document schema introspection via API

### ISSUE THREAD

**Issue by bb** [meilisearch/MeiliSearch#1069]
The stats endpoint (e.g. `http://127.0.0.1:7700/indexes/foo/stats`) provides a nice overview of the fields in `fieldsDistribution`.

To easily identify which attributes I could use for faceting, I'd like to also see, the types for each field, e.g. string, string[], int, int[], etc.

If there's more information available internally about fields, it would probably be nice to expose this as well.

Examples I can think of (without knowing too much about MeiliSearch internals yet):

* there's the [word limit](https://docs.meilisearch.com/guides/advanced_guides/known_limitations.html#maximum-words-per-attribute) which I might want to work around by splitting fields with long text into multiple to increase recall for rare case of words only being used in the last part.
* I read that the attributes are weighted by insertion order - maybe their weights could be exposed explicitly.

**Comment by MarinPostma** [comment]
Thanks for the suggestion!

For your first point, meilisearch is mostly untyped, so we don't keep information about the type of the field, not we care about it internally, except for certain case with facets, but this is done at indexing and forever forgotten about. 

The word limit is a hard limit, that is documented as you pointed out, I'm 'ot sure how this sits in index specific stats

The last part goes in favor of `attributesPosition` setting @curquiza @bidoubiwa @LegendreM. This is an ongoing discussion @bb

**Comment by qdequele** [comment]
Hello @bb, Thanks for your contribution, your interest in MeiliSearch, and your proposition of feature. Unfortunately, this proposition will not be possible. We are trying to create a schema-less and type-less search engine. In a lot of cases, we interpret the strings in numbers and vice versa. It will not be possible for us to add in the engine the ability to return the type of each field. Thank you for your contribution @bb!
