### ISSUE TITLE
Better error message for facet attributes type error

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#1071]
Originally reported in #1068 .

An error is thrown when indexing fields declared as `attributeForFaceting`, when the value is not of a supported type (`String` or `[String]`).

The curent error looks like this: 
```
"error processing facet filter: invalid document attribute <illegal value>, accepted types: String and [String]"
```

We want to introduce a bit more context to the error thrown when indexing documents, in the form of composable error message, e.g:
```
error processing facet filter: in document <docid>: in attribute <attr_name>: invalid value: <value>, only String and [String] are accepted.
```

This may require some thoughts, and maybe some design, to return relevant and consistent error message from indexing.

**Comment by skybristol** [comment]
I've just run into this issue as well in trying to push a bunch of values in array fields for faceting. It would be helpful if you included your tests for "suitable" data as something callable that could be incorporated into the various APIs for a priori testing of data being pushed to an index. I'm using the meilisearch Python client, and it would be really helpful to have some kind of test_documents method that returned meaningful information on any aspects of documents not suitable for the index.

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
