### ISSUE TITLE
Better error message for max facet value size

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#1072]
As explained in #1068, trying to use a facet that is longer that a certain size (504 bytes if i'm not mistaken) will result in an internal error to be thrown. We would like a better error message to be returned in that case, and a section in the documentation should explain this limitation.

This limitation is due to the key/value store we are using.

TBD: error message to be returned in this case.
TBD: specific error link

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
