### ISSUE TITLE
Support non-disjunktive facets

### ISSUE THREAD

**Issue by ayalon** [meilisearch/MeiliSearch#1073]
## Is your feature request related to a problem? Please describe.
 I created a search prototype with algolia and I'm now trying to get the same facet behaviour with meilisearch.

I have have a facet called author. Every document has exactly one author. 

## Facet Example
Adam (10)
Abraham (5)
Rossier (1)

If I select Adam on meilisearch the result is:
**Adam (10) (active)**
Abraham (0)
Rossier (0)

Adam is the active facet followed by some 0 count facets in alphabethical order.

## Describe the solution you'd like
If I use instant search with algolia, I get this:
**Adam (10) (active)**
Abraham (5) (remain selectable)
Rossier (1) (remain selectable)

The search result is updated with documents with author Adam. If I click on Rossier, all Documents with Author "Adam" OR "Rossier" are listed.

## Describe alternatives you've considered
It is not possible to have non diskunjtive facets with meilisearch as far as I can see.

**Comment by LegendreM** [comment]
Hello @ayalon, 
your issue seem to be related to [#945](https://github.com/meilisearch/MeiliSearch/issues/945#issuecomment-685526678).

The facet distribution listed by meilisearch is the distribution of returned documents.
Meaning that if a facet is exclusive and is selected (for exemple: it's not possible to have a document with `Adam` and `Abraham` and the facet `Adam` is chosen)
so the returned facet distribution will only have the selected field with a document count different to 0.

**Comment by ayalon** [comment]
Does that mean, that the frontend implementation of https://github.com/meilisearch/instant-meilisearch has a bug ? I'm using algolia vue-instantsearch in the frontend i just exchanged the search client.

Maybe https://github.com/meilisearch/instant-meilisearch has to send 4 request and fails to to so?

**Comment by bidoubiwa** [comment]
Doesn't it depend on which field you add to the [facetsDistribution](https://docs.meilisearch.com/references/search.html#search-in-an-index-with-post-route) and [facetFilters](https://docs.meilisearch.com/references/search.html#search-in-an-index-with-post-route) parameter of a search?  If you add only `Adam` to `facetFilters` and `["Adam", "Abraham"]` to `facetsDistribution`, then you will get `abraham: 0` in the facetsDistribution object. Which is the object used to showcase the count on the front-end. 

I'm not sure I understood your response @LegendreM. Sorry if this is what you said 😬.

> As you will see in the issue that I linked, Algolia sends multiple HTTP calls to retrieve the facet distribution that you are able to see with instant search.

Is this something we can reproduce?  Don't we need a system of document ratings?

**Comment by ayalon** [comment]
For reproduction check this example:
https://codesandbox.io/embed/github/algolia/doc-code-samples/tree/master/Vue+InstantSearch/getting-started
![image](https://user-images.githubusercontent.com/432045/98575231-35b0b780-22b9-11eb-8c21-d751d6e8b495.png)

If you click on the Facet "Smartwatches & Accessories", the result list only shows Smartwatches and no iPhone Accessories.
But the Facet "iPhone Accessories" remains clickable. And this is exaclity the behaviour I want. 

![image](https://user-images.githubusercontent.com/432045/98575265-42351000-22b9-11eb-9a20-802a53c5a912.png)

With meilisearch, as soon as you click on "Smartwatches & Accessories", this would be the only Facet with counts assuming that the products only have one category. The rest would be alphabetical ordered possible facets with count 0.


@LegendreM : I only see one request if I active a facet by the way.

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/73-keep-facet-count-on-disjunctive-filters?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
