### ISSUE TITLE
Non english character error in service logs

### ISSUE THREAD

**Issue by aysark** [meilisearch/MeiliSearch#1079]
**Describe the bug**
I'm seeing these errors in the meilisearch service logs:

```
Nov 15 18:45:41   meilisearch[21133]: [2020-11-15T18:45:41Z ERROR meilisearch_http::helpers::meilisearch] value: ['И', 'г', 'р', 'а', ' ', 'н', 'а', ' ', 'т', 'е', 'м', 'у', ' ', 'с', 'п', 'р', 'я', 'ж', 'е', 'н', 'и', 
Nov 15 18:54:23  meilisearch[21133]: [2020-11-15T18:54:23Z ERROR meilisearch_http::helpers::meilisearch] value: ['V', 'o', 'c', 'a', 'b', 'u', 'l', 'a', 'r', 'i', 'o', ' ', 'd', 'e', ' ', 'p', 'a', 'í', 's', 'e', 's'];
Nov 15 18:54:23  meilisearch[21133]: [2020-11-15T18:54:23Z ERROR meilisearch_http::helpers::meilisearch] value: ['P', 'a', 'í', 's', 'e', 's']; index: 0, match: MatchPosition { start: 0, length: 7 }
Nov 15 18:54:23  meilisearch[21133]: [2020-11-15T18:54:23Z ERROR meilisearch_http::helpers::meilisearch] value: ['p', 'a', 'í', 's', 'e', 's']; index: 0, match: MatchPosition { start: 0, length: 7 }
```

**To Reproduce**
Not sure, but i guess its due to non-english characters?

**Expected behavior**
Trying to understand that, as the error is not helpful to root cause.

**Screenshots**
N/A

**Desktop (please complete the following information):**
OS: ubuntu 18

**Comment by MarinPostma** [comment]
hello @aysark,
from what I see this is related to cropping/highlighting.

Can you observe any other effect than the error log?

**Comment by aysark** [comment]
Yeah if its just related to cropping/highlighting then its not so bad? I thought it was not indexing those docs?

**Comment by curquiza** [comment]
Hello @aysark, sorry for the delay.
We are currently working on fixing this issue, can you send us a sample of your document and the query you sent to MeiliSearch? so that we can reproduce your issue 🙂

**Comment by bmpf** [comment]
Same error : [2021-05-20T14:57:32Z ERROR meilisearch_http::helpers::meilisearch] value: "à"; index: 1, match: MatchPosition { start: 1, length: 1 }

**Comment by curquiza** [comment]
Still needs examples to be able to reproduce it.

**Comment by curquiza** [comment]
@aysark, can you send your dataset or at least the document that makes the search engine fails?
We need to be able to reproduce your step to fix the issue

**Comment by aysark** [comment]
Sorry no longer relevant to us as we moved off meili due to perf issues, i don't have the data anymore.

**Comment by curquiza** [comment]
Thanks for your answer! Closing this issue then!
