### ISSUE TITLE
Ability to rename index

### ISSUE THREAD

**Issue by aysark** [meilisearch/MeiliSearch#1080]
**Is your feature request related to a problem? Please describe.**
Renaming an index is important in production workflow where we are reimporting/reindexing all docs but do not want to suffer downtime.  So we will do the work in the background on a temporary index and then need to rename the temp index as the new main/master index.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
Algolia

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/65-swap-index?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to update it on the roadmap.
