### ISSUE TITLE
Elasticsearch-compatible API 

### ISSUE THREAD

**Issue by acc557** [meilisearch/MeiliSearch#1081]
**Is your feature request related to a problem? Please describe.**
Elasticsearch is a search engine based on the Lucene library and is most popular for full-text search. Many software is built around Elasticsearch API. MeiliSearch has a different set of Restful API than es, making it hard to get existing software working with MeiliSearch.

**Describe the solution you'd like**
Provide a middle-ware that  translates Elasticsearch Restful posts and queries  to MeiliSearch  posts and queries. The queries that is not supported by MeiliSearch can be simply ignored and returned with dummy results.

This will make Elasticsearch client work with MeiliSearch   as if it is talking to a real elasticsearch instance, and greatly accelerate the transition of existing software.

**Comment by LegendreM** [comment]
Hello @acc557, your request is interesting,
but we don't plan to implement and maintain it for now,
as you said a middle-ware seems to be a good option and could be implemented by anyone in the community,
probably based on nginx or kong.

Thanks for your proposal and your interest in our project!

**Comment by qdequele** [comment]
Hello @acc557,

Thanks for your proposition. I'm sorry but I don't think that we can put this wrapper inside the MeiliSearch repository. If we do that we will be forced to maintain it, what we don't want at the moment. What I propose is to do this project on your side. If you need advice, we will be happy to help you. Once the project is ready, we will be able to put it on our documentation as a tool made by the community. 

Don't hesitate to ping us!
