### ISSUE TITLE
Facet aggregation functions

### ISSUE THREAD

**Issue by bb** [meilisearch/MeiliSearch#1083]
The way values for `facetsDistribution` are determined is currently only counting documents.

I have some use cases where I am indexing and searching aggregate documents which act as surrogates for the actual things the user thinks of. In these cases, I do not want to count documents but sum up based on a certain field value. Besides count and sum, there are lots of other functions which might be taken into consideration and might make both implementation and usage more complex.

Extending the example from the documentation on facets, the API could look like this:

```ruby
index.search('thriller', {
  facetFilters: [['genres:Horror', 'genres:Mystery'], 'director:Jordan Peele'],
  facetAggregation: 'sum(my_amount_field)'
})
```

or as separate keys:

```ruby
index.search('thriller', {
  facetFilters: [['genres:Horror', 'genres:Mystery'], 'director:Jordan Peele'],
  facetAggregationFunction: 'sum'
  facetAggregationAttribute: 'my_amount_field'
})
```

Compare with the very extensive facet aggregation features which Solr provides: http://yonik.com/solr-facet-functions/

There might be additional use cases when combining distinct attribute and only counting/aggregating documents which would be actually returned vs the current state of returning counts not respecting distinctness. See also Algolia's [facetingAfterDistinct](https://www.algolia.com/doc/api-reference/api-parameters/facetingAfterDistinct/).

**Comment by LegendreM** [comment]
Hello @bb,

I may misunderstand your proposal,
but your need seems to be more  aggregation and analysis of your documents than instant-search,
we don't plan for now to implement advanced aggregation/analysis features.

I would be interested to have more details about your use case. 😄 

Thanks a lot for following meilisearch and suggest new features!

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! It definitively will look more like what Algolia is doing than Solr.

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/72-faceting-after-distinct?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
