### ISSUE TITLE
Introduce sortFacetValuesBy

### ISSUE THREAD

**Issue by bb** [meilisearch/MeiliSearch#1084]
Most of the time, I show facets in descending count order. However, I need to sort the values based on their counts on the client.

It would be great to introduce [sortFacetValuesBy](https://www.algolia.com/doc/api-reference/api-parameters/sortFacetValuesBy/) like Algolia has it.
It'd be even better if that could be configured per Facet (at query time plus defaults in settings) but that might be overkill.

**Comment by LegendreM** [comment]
Hey @bb,
As you said it's pretty easy to handle it on the client sides,
moreover,  meilisearch would not return trillions of facet values introducing performance issues on the client.
