### ISSUE TITLE
Sort on string fields

### ISSUE THREAD

**Issue by theo-lubert** [meilisearch/MeiliSearch#1093]
**Is your feature request related to a problem? Please describe.**

Currently it seems the Meilisearch's bucket sort is limited to numerical fields by design.
In order to streamline the use of the search engine, we would like to use it to retrieve even simple lists. Yet one of the most recurring limitation is the impossibility to sort by `String` (ex: title, slug, email, ...).

**Describe the solution you'd like**

We would like to be able to sort by string. In our case, we would be fine with a limited way to do so, like the one I describe in the alternatives section.

In the meantime:
- I'd love to have your input on how well you think our solution would hold at scale (sorting on large numbers).
- I believe sorting strings is not ideal for a search engine, but I wonder what is your opinion on this kind of features.

**Describe alternatives you've considered**

We added the feature ourselves, with a naive (naturally flawed) way to convert string fields into a numerical field to sort onto... It basically feels as unoptimised as it can get 😄, but it works on small projects, and I haven't started benchmarking the thing.

The idea is simply the convert the N first alphaNumerical characters into Hex values. It results in a (big) numerical value.
It is very-much half-baked at the time (intl, word separation, etc) and it has limitations too, but the feature is kinda there.

As you can see below, a string like  `Alice In Wonderland` gets converted to a large number `6576736769327378328779786869827665786800` (bigger than `MAX_INT`).

- The sort works fine, but do you see limitations ? at scale maybe, or in performance ?

```ts
function sortableString(str: string, maxLength: number = 20) {
    const standardString = str.trim().slice(0, 100).toLocaleUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    return standardString.split('', maxLength).reduce((res, c) => {
        if (isAlphaNumeric(c) || (c === ' ' && res[res.length - 1] !== '32')) {
            res.push(String(c.charCodeAt(0)).padStart(2, '0'));
        }
        return res;
    }, [] as string[]).join('').padEnd(2 * maxLength, '0');
}
```

Result:
```js
{
    hits: [
        {
            id: '14',
            title: 'Alice In Wonderland',
            sortable_title: '6576736769327378328779786869827665786800'
        }, {
            id: '4',
            title: 'Harry Potter and the Half-Blood Prince',
            sortable_title: '7265828289328079848469823265786832847269'
        }, {
            id: '456',
            title: 'Le Petit Prince',
            sortable_title: '7669328069847384328082737867690000000000'
        }, {
            id: '123',
            title: 'Pride and Prejudice',
            sortable_title: '8082736869326578683280826974856873676900'
        }, {
            id: '42',
            title: "The Hitchhiker's Guide to the Galaxy",
            sortable_title: '8472693272738467727273756982833271857300'
        }, {
            id: '1044',
            title: 'The Hobbit',
            sortable_title: '8472693272796666738400000000000000000000'
        }
    ],
    offset: 0,
    limit: 20,
    nbHits: 9,
    exhaustiveNbHits: false,
    processingTimeMs: 0,
    query: ''
}
```

**Comment by Kerollmops** [comment]
Hello @theo-lubert,

This is an appriate solution, a nice work around, however there is some flaws in it, the maximum value that MeiliSearch is able to handle is an u64 MAX, there also is another little point, in your example you use a string to store the generated numbers but it must be a string for meilisearch to accept it.

**Comment by MarinPostma** [comment]
As an alternative, you can also sort all of your documents before indexing and give associate to `sortable_title` the position in the sorted collection. 
**pro**: you don't have the limitations from the previous method
**cons**: you have to re-index everything every time you add documents (to preserve the order)

**Comment by qdequele** [comment]
Sorry, we decide to close this issue. We don't want to allow users to do this kind of action at the moment. Moreover, there are possible alternatives to do what you want.

**Comment by theo-lubert** [comment]
I understand.

Just to sum up the two workarounds:
1. Pre-computing the order: 
 It means re-indexing everything every time the order changes (at least every thing "after" your updated row). This is a perfect solution if the index is static, or not likely to be updated often. But not an option if you need real time updates.
2. Storing a hash that can be sorted on: 
 It has flaws (ex: sort limited to N characters), but it is the only option if your index is updated on a regular basis, since you can update one entry at a time, without the need of re-indexing
