### ISSUE TITLE
Introduce `rustfmt` in continuous integration

### ISSUE THREAD

**Issue by woshilapin** [meilisearch/MeiliSearch#1101]
**Is your feature request related to a problem? Please describe.**
`rustfmt` is a widely used formatter for Rust source code but it seems a lot of the code of `MeiliSearch` is not formatted using this formatter.

**Describe the solution you'd like**
- Format all the files with `rustfmt`
- Setup the CI to ensure any new piece of code respect this formatter

**Describe alternatives you've considered**
I am not aware of other widely used formatter for Rust, however, I believe `rustfmt` is configurable. In general, configuration of the formatter only leads to endless discussions about tabs vs spaces, using the default avoids having this kind of discussion.

**Additional context**
I can provide a PR if the team is interested. However, it is to be noted that this would produce potentially a massive PR with impact (mostly merge conflicts) on every other PR or work-in-progress. A bit of synchronization might be needed to pull out such an action.

**Comment by MarinPostma** [comment]
Hello @woshilapin, thank you for you proposal, but it is a choice not to use rustfmt 🙂

**Comment by woshilapin** [comment]
Thank you for your quick answer. Do you mind explaining the rational behind this decision? Also, I'm wondering if it worse explaining it in the documentation (since it's seems to be mostly the standard to use it). I could provide a PR to improve the documentation if you'd like.

**Comment by MarinPostma** [comment]
There was an attempt with #928, but @Kerollmops has reservations about using rustfmt, he will explain why better than me 🙂

**Comment by Kerollmops** [comment]
I am not a great fan of automatic code formatters as sometimes they will format code in a way [that will reduce the readability of it](https://twitter.com/pcwalton/status/1088159135877685248). I am more on the side of people who think that there must only be [simple and basic formatting rules](https://twitter.com/withoutboats/status/1223252816724221952).
