### ISSUE TITLE
filters: `!=` support for arrays of values

### ISSUE THREAD

**Issue by benhowes** [meilisearch/MeiliSearch#1102]
**Describe the bug**
When using filters, I was expecting `!=` to allow filtering for when a value was not in an array, given that `=` allows for filtering where an array contains. 

Having read up in #611 I thought that would be the behaviour.

**To Reproduce**
1. Create a document schema containing an array of values
2. Perform a search with a filter contain `arrayValue != "someValue"`
3. It seems that _any_ document which contains an element which is not `"someValue"` will be returned to the client.

**Additional context**
I have been able to use `NOT (arrayValue = "someValue")` to satisfy my usecase for the time being.

It may just be that you do a documentation update to make the behaviour with filters on arrays a bit more clear to meili-n00bs like me :)

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
