### ISSUE TITLE
Ability to delete specific updates or clear out the queue of updates

### ISSUE THREAD

**Issue by jwohlfert23** [meilisearch/MeiliSearch#1104]
**Is your feature request related to a problem? Please describe.**
When there is a super long backlog of updates, there is a need to clear out that backlog, rather than waiting for them all to complete. In most queue systems there is a way to do this.

**Describe the solution you'd like**
Add endpoints to:
1. Delete a specific update by ID
2. Delete all updates with status of "Enqueued"

**Describe alternatives you've considered**
There's no way from the documentation that I can see to do this.  Right now, your only option is to wait until the backlog has been churned through which could take hours or more.

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/71-abort-enqueued-updates?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
