### ISSUE TITLE
Example doens't work

### ISSUE THREAD

**Issue by DavidBernal** [meilisearch/MeiliSearch#1133]
I follow all getting start steps and search step doesn't find nothing:
https://docs.meilisearch.com/guides/introduction/quick_start_guide.html#download-and-launch

**To Reproduce**
Follow the getting start steps.

**Expected behavior**
Search should find same as example

**Comment by MarinPostma** [comment]
Hello @DavidBernal, could you provide us with a little bit more context? what are the results you are getting? what makes you think there are not right?

Thanks!

**Comment by DavidBernal** [comment]
Hi @MarinPostma, I just follow the guide.

Download binary and start server:
```bash
curl -L https://install.meilisearch.com | sh
./meilisearch
```
I created an index as example said:
```bash
curl \
  -X POST 'http://127.0.0.1:7700/indexes' \
  --data '{
  "uid" : "movies"
}'
```
I see index was been created.

I donwloaded the movies.json file from: https://github.com/meilisearch/MeiliSearch/blob/master/datasets/movies/movies.json
And I load to index:
```bash
curl \
  -X POST 'http://127.0.0.1:7700/indexes/movies/documents' \
  --data @movies.json
``` 

Theorically the indexer is ready. I do a search:
```bash
curl 'http://127.0.0.1:7700/indexes/movies/search' \
--data '{ "q": "botman" }'
```

I get:
```json
{"hits":[],"offset":0,"limit":20,"nbHits":0,"exhaustiveNbHits":false,"processingTimeMs":2,"query":"botman"}%                                                                                                        
```

Expeted:
```json
{
  "hits": [
    {
      "id": "29751",
      "title": "Batman Unmasked: The Psychology of the Dark Knight",
      "poster": "https://image.tmdb.org/t/p/w1280/jjHu128XLARc2k4cJrblAvZe0HE.jpg",
      "overview": "Delve into the world of Batman and the vigilante justice tha",
      "release_date": "2008-07-15"
    },
    {
      "id": "471474",
      "title": "Batman: Gotham by Gaslight",
      "poster": "https://image.tmdb.org/t/p/w1280/7souLi5zqQCnpZVghaXv0Wowi0y.jpg",
      "overview": "ve Victorian Age Gotham City, Batman begins his war on crime",
      "release_date": "2018-01-12"
    }
    ...
  ],
  "offset": 0,
  "limit": 20,
  "processingTimeMs": 2,
  "query": "botman"
}
```

As I said, is just the quick start guide.

**Comment by MarinPostma** [comment]
Thanks @DavidBernal, so my guess is that the indexing was not finished when you started querying, can you make sure all updates are `processed` [using this route](https://docs.meilisearch.com/references/updates.html#get-all-update-status)?

**Comment by MarinPostma** [comment]
@react-learner I think we should add this to the documentation 🙂

**Comment by DavidBernal** [comment]
Thank you @MarinPostma. After a while indexer works.
