### ISSUE TITLE
Cannot compile on macOS 11.0.1

### ISSUE THREAD

**Issue by fharper** [meilisearch/MeiliSearch#1136]
**Describe the bug**
I cannot compile MeiliSearch. Any help would be appreciated :D

**To Reproduce**
I followed the steps at https://github.com/meilisearch/MeiliSearch#compile-and-run-it-from-sources

**Expected behavior**
It should compile without error.

**Desktop (please complete the following information):**
 - OS: macOS BigSur 11.0.1
- rustc 1.48.0 (7eac88abb 2020-11-16)
 Tested on a MacBook Pro with the new M1 chip (running in the terminal with Rosetta2), but I have the same on a MacBook Pro Intel.

**Additional context**
here is the output when I run `cargo run` on the repo

```
Compiling jemalloc-sys v0.3.2
error: failed to run custom build command for `jemalloc-sys v0.3.2`
```

full output in [output.txt](https://github.com/meilisearch/MeiliSearch/files/5691656/output.txt)

**Comment by fharper** [comment]
I tried some things with @MarinPostma, like re-adding the toolchain

```
rustc 1.48.0 (7eac88abb 2020-11-16)
rustup self update
```

we also try to install `jemalloc` before compiling using homebrew.

**Comment by tpayet** [comment]
I can compile (`cargo clean && cargo build`) MeiliSearch last commit (#861c6fec06367fe) on my MacBook Pro 2019 with Intel processor. I am running Mac OS 11.0.1 aka Big Sur.

```bash
$ rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```

```bash
$ rustup --version
rustup 1.22.1 (b01adbbc3 2020-07-08)
```

let me know if you need more information ^^

**Comment by qdequele** [comment]
@fharper Is this issue could be closed?

**Comment by fharper** [comment]
No, I need to spend more time to try it again. It would be nice if someone on the core team can help as I have no idea what is going on as I'm even installing the "faulty" packages manually...

**Comment by qdequele** [comment]
does the issue come from the Apple M1 processor and not from MacOS?

**Comment by fharper** [comment]
I have the same issue on my intel.

**Comment by tpayet** [comment]
On a fresh new M1 MacBook Pro running macOS Big Sur 11.2.1
I did the following:
- install Rust toolchain using [rustup.rs installer](https://rustup.rs) (`rustc --version` returned  1.50.0)
- in the terminal, I run `git clone git@github.com:meilisearch/MeiliSearch.git`
- I got ask to install developer tools from Xcode, I accepted
- I run again the `git clone`
- `cargo build` -> Everything compiled
- I was able to run MeiliSearch.

@fharper Could you let me know If you have anything different in your environment?
How did you install rust toolchain?
How did you install git or other developers tools such as a gcc linker?

**Comment by fharper** [comment]
First, I only use the steps listed in the README. I assume it's a dependencies issue because of another app installed as I don't have JUST rust & MeiliSearch on my laptop.

> I run again the git clone

Why do you clone the same repo twice?

> Could you let me know If you have anything different in your environment?

rustc --version return `rustc 1.49.0 (e1884a8e3 2020-12-29)`

> How did you install rust toolchain?
`rustup override set stable`
`rustup update stable`
As listed in the README.

> How did you install git
homebrew, but I have no issue with cloning the repo, unless you tell me there are compiling steps needed git? I also have no issue with git, using it everyday.

> other developers tools such as a gcc linker
How do you do it yourself? Not in your steps.

I use `Xcode Command Line Tools` it's kinda the way to go on macOS. I could try to install gcc separately, but the error I have is with a library, seems that it compiled until that point, or maybe I'm wrong. Worth a try if you used another gcc version.
