### ISSUE TITLE
Payload Limit Size unit

### ISSUE THREAD

**Issue by fharper** [meilisearch/MeiliSearch#1138]
It's a detail, but we should manage payload limit size in a human readable fashion like at least MB. I don't see a scenario where someone would like to increase or decrease the limit for a byte.

**Comment by carlosb1** [comment]
I could try to work in this... but I should get a little more info.

**Comment by qdequele** [comment]
We could use this kind of [plugin](https://docs.rs/byte-unit/4.0.9/byte_unit/) to convert strings  (Mb/Kb) into bytes.

**Comment by tpayet** [comment]
Hey @carlosb1, thanks for your interest :)

The payload size is configurable using the CLI option `--http-payload-size-limit` or the env var `MEILI_HTTP_PAYLOAD_SIZE_LIMIT`. So far the value to set have to be in bytes. 

If we can use the crates @qdequele talked about, we should be able to offer a flexible way to set the valu as we could write `123 kb` or `123 kiB` or `123Gb` if I am not mistaken. This seems to offer a super nice user experience in my opinion. 

Please do not forget to update the [related documentation](https://github.com/meilisearch/documentation/blob/master/guides/advanced_guides/configuration.md).

And that would be great to also offer this update to the [UDB size](https://docs.meilisearch.com/guides/advanced_guides/configuration.html#options) and [MDB size](https://docs.meilisearch.com/guides/advanced_guides/configuration.html#max-mdb-size) configuration.

We would prefer if you could first open a pull request on the documentation so we agree on the format of the feature, and then you could implement it.

Let me know if you need any further information. I would be glad to guide you through your contributor journey, but unfortunately I won't be able to help you with code in Rust. If you have any code related question, @MarinPostma, @LegendreM or @Kerollmops will hep you :)

**Comment by MarinPostma** [comment]
happy to help out :)

**Comment by carlosb1** [comment]
No problem for coding in Rust :).  With this info, it seems enough and try to contribute as soon as possible and I will join in the slack channel. Thanks for this fast reply.

**Comment by MarinPostma** [comment]
No description provided.

**Comment by carlosb1** [comment]
sorry @MarinPostma  where? I don't get what it need ot add.

**Comment by carlosb1** [comment]
https://github.com/carlosb1/MeiliSearch/tree/1138-payload-size-unit -  Is it possible to include some tests for the `option.rs` module. It seems the easier way to test the PR.

**Comment by MarinPostma** [comment]
Hey @carlosb1, can you show me your test?

**Comment by carlosb1** [comment]
I tried different combinations
```
mod common;
#[actix_rt::test]
async fn it_works() {
    assert_eq!(2 + 2, 5);
}

#[actix_rt::test]
async fn it_works() {
    assert_eq!(2 + 2, 5);
}

#[test]
async fn it_works() {
    assert_eq!(2 + 2, 5);
}

```
the only thing that I didn t do  it is including the `#[cfg(test)]` or the `mod tests` from the tutorial, but one of them should work.

**Comment by MarinPostma** [comment]
Ok, got it.

First of all you will want to use https://docs.rs/structopt/0.3.21/structopt/trait.StructOpt.html#method.from_iter this to test the Option struct

Then, you'll want to write unit tests for Option, for that you need to create a module that condition Amy compile on test builds, at the bottom of option.rs:

```rust
#[cdg(test)]
mod test {
    use super::*;

    #[test]
    fn test_opt() { ... }
}
```

Here we don't need to use actix test runtime, since this is all synchronous

**Comment by carlosb1** [comment]
ok thanks! sorry for the spam, I didn t see any tests in the module and I figured out that you are including  in `tests`. Then, it is easy, I will do the usual practice for  unit tests in Rust.

**Comment by MarinPostma** [comment]
Yes that's great! This part of the code is no very well covered indeed

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
