### ISSUE TITLE
Logging mechanism

### ISSUE THREAD

**Issue by fharper** [meilisearch/MeiliSearch#1139]
As a user, I would like MeiliSearch to write logs about happening operations, but more important, about errors.

Having an issue right now, it would make my life easier to have logs since the return error is quite generic, and coming through Nginx.

**Comment by curquiza** [comment]
Logs are now available in production and have their own spec: https://github.com/meilisearch/specifications/blob/main/text/0033-logging.md
Fixed by the introduction of the new search engine then: https://github.com/meilisearch/MeiliSearch/pull/1421
