### ISSUE TITLE
Set the authorization token in the header

### ISSUE THREAD

**Issue by long1eu** [meilisearch/MeiliSearch#1144]
It's not always possible to set the token in the headers, can we have it also as a query param?

**Comment by tpayet** [comment]
Hey @long1eu,

Thank you for submitting this idea. Could you please show us in which environment you are not able to specify the token in the header? 

Have a nice day,

**Comment by long1eu** [comment]
My use case it very specific. I have a load balancer that has a health
check on the VM instance that runs the meilisearch. The healthcheck run the
version endpoint, but I can't specify headers in the load balancer.

**Comment by MarinPostma** [comment]
Hey @long1eu, any reason for not using the [health endpoint](https://docs.meilisearch.com/references/health.html) for this purpose?

**Comment by long1eu** [comment]
Didn't know about it. Does it require a key?

**Comment by MarinPostma** [comment]
nope

**Comment by long1eu** [comment]
thanks

**Comment by long1eu** [comment]
I'm back. Looks like this doesn't help. I can observe that a 204 is not something that the health check likes. It must be 200.

https://cloud.google.com/load-balancing/docs/health-checks#optional-flags-hc-protocol-http

**Comment by MarinPostma** [comment]
Thanks for the feedback, @LegendreM can you take it from there since you worked on this ?

**Comment by curquiza** [comment]
This will be fixed in the v0.20.0 (release next week). You can already give a try with the v0.20.0rc0 😄

**Comment by curquiza** [comment]
I forgot to close it! 😅
