### ISSUE TITLE
Fair comparison with Typesense

### ISSUE THREAD

**Issue by jasonbosco** [meilisearch/MeiliSearch#1148]
👋 MeiliSearch team, 

I'm Jason, one of the authors of [Typesense Search](https://github.com/typesense/typesense). Our projects started independently at different points in time, but we both have similar goals of being an easy-to-use yet powerful search engine and being a good open source alternative to Algolia. So here's to both of us succeeding in our goals! 🍻

It was [brought to my attention recently](https://github.com/typesense/typesense/issues/178) by a user evaluating Typesense and Meilisearch, that you had mentioned the following statements in your docs about Typesense. I'd like to provide some counter-points to your observations and gently ask that you update your documentation appropriately, so as to make the comparison with Typesense fair and balanced, and more importantly not confuse users.

I'm mostly summarizing [my response](https://github.com/typesense/typesense/issues/178#issuecomment-752752175) to the user's query below: 

---

> I was browsing on the meiliSearch resources at
> https://docs.meilisearch.com/resources/comparison_to_alternatives.html#about-meilisearch
> and came across a few comments referencing Typesense that I hope you can comment on:
> 
> > Typesense uses a default_sorting_field (opens new window)on each document, it means that before indexing your documents you need to compute a relevancy score for Typesense to be able to sort them based on your needs.
> > On the other hand, MeiliSearch uses a bucket sort, which means that there is a default relevancy algorithm based on the proximity of words in the documents, the fields in which the words are found and the number of typos. And you can still add your own custom rules if you want to alter the default search behavior.
> 
> 
> is this true?
> 
> 

**This is not true.** You could set `default_sorting_field` to a constant integer value for all records and Typesense will still pull up results based on just the keyword relevancy score it computes automatically by default, just like Algolia and Meilisearch. 

However in our experience working with search engines (not just Typesense) and large datasets, keyword-based relevancy scoring only gets you so far, especially in large enough datasets where many records might have similar/overlapping keywords and so end up having the same computed keyword-relevancy score. So you eventually end up having to set up custom ranking rules to tie-break records having the same keyword-relevancy score. 

This is where the `default_sorting_field` comes into play - _for tie-breaking_, when the keyword-relevancy score is identical for similar looking records. In Algolia and Meilisearch, you'd need to keep an eye out for when this happens as you index records over time and then define custom ranking rules separately to break ties. 

In Typesense, `default_sorting_field` is just a "custom ranking rule". We wanted to elevate the importance of defining a tie-breaking field upfront, especially if you have a good data point already (like say number of page views in the case of indexing web pages, or number of purchases in the case of indexing products, etc). We did this because most search applications eventually end up needing this tie-breaking mechanism and so we took the approach of having users think about it upfront, so search relevancy continues to stay good as you index more and more records. 

Now, if your dataset doesn't have a field that could be used for tie-breaking, that's totally fine as well - like I mentioned above, you can just set `default_sorting_field` to say `10` or any constant integer for all records and effectively turn off this feature. Typesense will then just go off of keyword-relevancy score, just like Algolia and Meilisearch.

---

>>... the most similar solutions to MeiliSearch are Algolia and Typesense. The three of them are search-as-you-type relevant search engines.
>> Typesense is a great tool but is not recommended for achieving a lot of operations with minimal configuration.
>
> Is this true?

**This is not true.** This one stung a bit, because Typesense's explicit stated goal is to make high-performance out-of-the-box search accessible to all developers with minimal configuration and minimal operational overhead. In fact, Typesense was born out of our personal frustrations with the complexities of using ElasticSearch (and on occasion even Algolia) in the past. So the last thing we want to do is to end up becoming another complicated piece of software to operate. 

We've been chipping away at this goal for just over 5 years now, we've heard about teams successfully switching from Algolia to Typesense in production, we try to be on top of any issues and questions, we've deployed 100s of production-grade clusters on Typesense Cloud, and so I'd like to think that we got something right! 

It's hard to address a broad unsubstantiated statement like that, but I'm open to any feedback you might have on why you think Typesense "is not recommended for achieving a lot of operations with minimal configuration". 

---

>>Typesense aims to be simple to set-up and focus on developer productivity and experience by providing a clean API. It is best suited for light projects.
> 
> What is meant by a light project?

This is another head-scratcher of a statement! Could you expand on what you mean by "light projects"?

In terms of dataset size, here's a showcase showing Typesense in action on a **32 Million songs** dataset: https://songs-search.typesense.org/. Most results should be returned in 50-60ms. 

Here's another showcase showing Typesense in action on a **28 Million books** dataset: https://books-search.typesense.org/

And another showcase with **2 Million recipes**: https://recipe-search.typesense.org/

In terms of concurrency, I've tested a dataset with ~3 million records (Amazon product data) that was ~13GB on disk and I was able to achieve a throughput of **250 concurrent search queries per second** on a 16GB RAM, 8-vCPU 3-node Typesense cluster.

So I'd have to strongly disagree with you on your broad statement that Typesense is "best suited for light projects", if I'm interpreting your definition of "light" correctly. Again, I'm open to any and all feedback you have. 

---

My apologies if this comes across as a rant, but having our work over the years be dinged by broad misleading statements, is a little disheartening, especially when it confuses users. I've tried my best to be factual and provide as much context as possible to support my statements. I'd appreciate giving me the benefit of the doubt, if my tone above doesn't convey my genuine intention of wanting to have a well-rounded conversation.

**Comment by tpayet** [comment]
Hey @jasonbosco, thanks for your message. I'll remove the comparison between MeiliSearch and Typesense until we give a new try to Typesense. 

I was the one writing the comparison a year ago and I did it based on my reading on Typesense documentation. Apologies from the MeiliSearch team as this was not our intention to confuse anyone.  

Have a nice day!

**Comment by jasonbosco** [comment]
@tpayet Thank you, I'd appreciate that.

**Comment by Glitchfix** [comment]
I think this is how nations should resolve things
This developer level understanding is what is required in the world!

**Comment by sandstrom** [comment]
I read Typesense comparison between your two tools (and Algolia / Elastic).

Would still be nice if Meili would re-add an updated comparison between yourself and Typesense. Right now there is nothing at [your comparison page](https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html#comparisons).

Here is typesense comparison (which I'm sure also has some bias, at least in what aspects they decide to compare/include):

https://typesense.org/typesense-vs-algolia-vs-elasticsearch-vs-meilisearch/

**Comment by tpayet** [comment]
Hey @sandstrom,

Thank you for your suggestion, I'll check with the team how we can prioritize this :)

Also, thank you for the rethinkdb inspiration!
Is there any specific area you would like to have better insight about or just a technical comparison from our POV?

**Comment by sandstrom** [comment]
Some type of feature/table comparison with ElasticSearch and Typesense would be great. 

Without it, the actual process of switching e.g. from ES is unknown. It's obvious that you'll lack things (since you're a less mature product, you'll have fewer features).

If it's easy for me to scroll through a table, see that you have most of the things that we need, and then maybe 2-3 things that are lacking, I can then focus on those and see if there are workarounds (or ping you and ask for an ETA on them), that is very helpful (plus you could get feedback on specifics that's missing).

Right now it's just hazy and I probably won't do this work myself by digging through your docs (since that takes time).

I'd also add some broad stroke details on your direction, i.e. if there are philosophical difference between you and ES/typesense (things like rust, how you're planning to make money, anti-feature (things you don't want to be) etc).

**Comment by curquiza** [comment]
Hello @sandstrom, thanks for your feedback, I opened an issue in the documentation side -> https://github.com/meilisearch/documentation/issues/1044

**Comment by stratboy** [comment]
Specifically, Typesense in their current comparison state that Meilisearch is no production ready. ???

https://typesense.org/docs/overview/comparison-with-alternatives.html#typesense-vs-algolia

> Based on the project's documented limitations, it seems to be geared for small dataset sizes, and specifically for cases where high availability is not a requirement. Since it does not have multi-node clustering or node-node replication, it is not production-ready yet.

So what?
