### ISSUE TITLE
High CPU usage (90-99%) if data is close to or larger than physical memory

### ISSUE THREAD

**Issue by iredmail** [meilisearch/MeiliSearch#1149]
**Describe the bug**

I run MySQL + MeiliSearch (0.17.0) on a 1GB RAM (Linode) VPS for evaluation for few days, Ubuntu 20.04 LTS.

At the beginning it works very well and CPU/RAM usages are very low, CPU available is 0.x-3%, RAM 300-600MB. But since last night, meilisearch uses  90-99% CPU and it never goes down. Meilisearch data under `data.ms` directory is about 600MB.

Tried to restart meilisearch service, live migrate to a 2GB RAM VPS, same result.

Eventually i removed all MeiliSearch data and restart meilisearch service, now it comes back to 0.x - 1% CPU usage.

**To Reproduce**

I don't have steps to reproduce the issue yet.

**Expected behavior**

I expect the CPU usage stay low or maybe slowly grows but reasonable.

**Comment by bhavyalatha26** [comment]
Hi @iredmail,

Do you observe something similar to this [issue](https://github.com/meilisearch/MeiliSearch/issues/1110) ?

**Comment by iredmail** [comment]
Hi @bhavyalatha26 

I checked all posts in the issue you mentioned (#1110), but I don't think it's same or similar, and I don't know how to steadily reproduce it.

Now i always remove existing data (the default "data.ms" directory) for new testing, no error so far, but this issue becomes my concern for running MeiliSearch on production server.

**Comment by MarinPostma** [comment]
@iredmail does that CPU surge occurs after indexing new documents?

**Comment by iredmail** [comment]
I lost the CPU/RAM metric data since the VPS plan doesn't keep it after 12 hours, and i forgot to take a screenshot. :(
I guess i have to close this issue since cannot offer further info. Just want you to know this issue happened and maybe someday others will experience the same.

**Comment by iredmail** [comment]
I constantly get high CPU usage (90-99%) after running MeiliSearch for one day. 15000+ small documents (email messages) were added.

**Comment by iredmail** [comment]
I think i figured out why MeiliSearch uses 90+% CPU: my testing machine has only 1GB memory, when meilisearch stores more processed data (under MEILI_DB_PATH), the cpu usage is increasing at the same time, restarting meilisearch doesn't help. No dump and snapshot yet.

So the problem MIGHT be, meilisearch doesn't work well if its data is larger than machine (physical) memory.

**Comment by eskombro** [comment]
You are right @iredmail, There is some mention to this [here in the docs](https://docs.meilisearch.com/resources/about_storage.html#memory-mapping). Is this what you mean?

**Comment by iredmail** [comment]
I guess this is the root cause. Thanks for the reference.
Then here comes the new question: if i have X GB memory, how can i handle / store X+Y GB data?

We plan to use MeiliSearch as the full-text search engine for email archiving software, it will handle a lot emails everyday, the data may go up to 10 GB, 100GB, 200GB, even 1TB, 5TB. We already have client with more than 3 TB mailboxes, how can we index these 3TB mailboxes with MeiliSearch AND only 16/32/64 GB memory?

**Comment by iredmail** [comment]
Dear @eskombro 

Any solution or improvement for this issue?

**Comment by eskombro** [comment]
Hi @iredmail 

From my POV, in its current state, MeiliSearch may not be the solution that fits your needs right now. A new version of the search engine will be released in the future, and maybe this will change the situation, but as for now, I don't think that trying to fit several hundreds of Gb of data (or even a few Tb) in a MeiliSearch instance with a few Gb of RAM is reliable in production.

**Comment by iredmail** [comment]
@eskombro Thanks for the feedback. :)
