### ISSUE TITLE
Updating settings on a new document can be overwritten when loading the first document

### ISSUE THREAD

**Issue by aidanhs** [meilisearch/MeiliSearch#1160]
(possibly related to #1159)

**Describe the bug**
Creating a new index, setting some settings and then (without waiting for that update to complete) loading a single initial document has been observed to lose the settings updates.

**To Reproduce**
Run the test script (listed at the bottom) against a fresh meilisearch instance (I'm using `RUST_BACKTRACE=1 ./MeiliSearch/target/release/meilisearch --db-path data.ms` (I'm on a05aef5c14d445139addb5e8709acaf427cec0cd).

The script logs will look like:
```
$ python3 repro2.py
Deleting index
Making index
Response:  b'{"name":"songs","uid":"songs","createdAt":"2021-01-01T15:29:15.263684857Z","updatedAt":"2021-01-01T15:29:15.263756264Z","primaryKey":null}'
Configuring index
Response:  b'{"updateId":0}'
Beginning song load
Songs loading with update id 1
Checking settings
Response:  b'{"rankingRules":["typo","words","proximity","attribute","wordsPosition","exactness"],"distinctAttribute":null,"searchableAttributes":["*"],"displayedAttributes":["*"],"stopWords":[],"synonyms":{},"attributesForFaceting":[]}'
Song indexing complete
```

This is wrong - the resulting settings are not the ones that I set in the test script (e.g. `searchableAttributes` is `["*"]`).

**Expected behavior**
I expect updates to be commutative - the end result should be the same no matter what order I apply things in (as long as all updates are compatible with each other, and relative ordering of updates that overwrite each other are the same).

In this case, there are two settings (S1, the initial settings, and S2, my custom settings) and a doc. As long as S1 happens before S2, I expect all end results to be the same *even if* I don't wait for updates of the settings to complete.

What I think is happening here is
 - S2 begins being applied
 - the document comes in, is treated as the first document, and figures it should register the fields into the settings
 - S2 finishes being applied
 - the document finishes being added, and settings are applied based on the fields of the document

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser N/A
 - Version Ubuntu 18.04

**Additional context**
Test script (this differs from the one in #1159 by not doing anything with facets, and printing settings out afterwards):
```
#!/usr/bin/env python3

import datetime
import json
from urllib import request
import time
import sys

assert sys.version_info.major == 3

def updatesearch():
    print("Deleting index")
    r = request.Request('http://localhost:7700/indexes/songs', method='DELETE')
    try:
        request.urlopen(r)
    except Exception as e:
        if e.getcode() != 404:
            raise

    songs = [{
        'song_key': '1', 'title': 'succducc - me & u', 'song_name': 'me & u', 'song_sub_name': '', 'level_author_name': 'datkami', 'description': 'Hard Only / ~330 notes / Event Lighting! / https://soundcloud.com/succducc/me-n-u', 'total_votes': 640, 'pct_upvoted': 82.65625, 'uploaded_at_tstamp': 1525786136, 'post_id': 7809, 'uploader_name': 'datkami', 'genres': ['Anime', 'EDM'], 'modes': ['Standard']
    }]

    print("Making index")
    r = request.Request('http://localhost:7700/indexes', method='POST',
            data=b'{"uid":"songs"}', headers={'Content-Type': 'application/json'})
    res = request.urlopen(r)
    print('Response: ', res.read())

    print("Configuring index")
    settings = {
        "searchableAttributes": ["title", "song_name", "song_sub_name", "level_author_name", "description", "uploader_name", "genres", "modes"],
        "displayedAttributes": ["*"]
    }
    settings = json.dumps(settings).encode('utf8')
    r = request.Request('http://localhost:7700/indexes/songs/settings', method='POST',
            data=settings, headers={'Content-Type': 'application/json'})
    res = request.urlopen(r)
    print('Response: ', res.read())

    print("Beginning song load")
    r = request.Request('http://localhost:7700/indexes/songs/documents?primaryKey=song_key', method='POST',
            data=json.dumps(songs[:1]).encode('utf8'), headers={'Content-Type': 'application/json'})
    res = request.urlopen(r)
    update_id = json.loads(res.read())['updateId']
    print('Songs loading with update id', update_id)
    while True:
        r = request.Request('http://localhost:7700/indexes/songs/updates/'+str(update_id))
        res = request.urlopen(r)
        data = json.loads(res.read())
        if data['status'] == 'enqueued':
            time.sleep(1)
        elif data['status'] == 'processed':
            break
        else:
            print(data)
            raise Exception('failed to process song load')

    time.sleep(5)
    print('Checking settings')
    r = request.Request('http://localhost:7700/indexes/songs/settings', method='GET',
            headers={'Content-Type': 'application/json'})
    res = request.urlopen(r)
    print('Response: ', res.read())

    print("Song indexing complete")

updatesearch()
```

**Comment by aidanhs** [comment]
Hi @MarinPostma. Unfortunately I don't think this is fixed. As I mentioned above, I'm building myself and:

> I'm on a05aef5

Which contains #1128, per the output of this command:
```
$ git branch $(git symbolic-ref --short HEAD) --contains 446b2e7
* master
```

**Comment by MarinPostma** [comment]
@aidanhs Found the bug! turn out this is a data race in https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/src/routes/document.rs#L189, where the schema is read and updated in two transaction. The event occurs in the following order:
- settings update is added to the queue
- document addition is received and the schema is read and updated
- the setting update is processed
- the document addition schema is written back to disk
- the addition is performed according the the latest written schema state

This happens because the document addition request is sent before the setting update request is fully processed, the quick fix right now is to synchronize the requests.

This issue is prioritized, thanks for the report :+1:

**Comment by aidanhs** [comment]
Great, thanks for getting to it so quickly!
