### ISSUE TITLE
Meilisearch get high CPU, only get down when i  terminate process by using htop command and start again

### ISSUE THREAD

**Issue by huynv86** [meilisearch/MeiliSearch#1175]
I can't reproduce this bug
it occurs several time per month
i use VPS Vultr

**Comment by Kerollmops** [comment]
Hello @huynv86,

It seems that it is probably related to #941, where a high number of words in a query can trigger this high COU usage behavior, we are fixing this in the next release (in less than 4 weeks).

Thank you for the report!

**Comment by MarinPostma** [comment]
If this is what @Kerollmops thinks, it is fixed by #1174.

**Comment by huynv86** [comment]
Hello @MarinPostma  
how i can solved this problem? update to 0.17.0 or waiting for new version of Meilisearch. My current is 0.15.0
thank u

**Comment by MarinPostma** [comment]
This will be part of the next release, you can simulate it now by limiting the number of word you send in a query

**Comment by curquiza** [comment]
Fixed by #1174
