### ISSUE TITLE
Use of blocking functions inside async functions

### ISSUE THREAD

**Issue by skerkour** [meilisearch/MeiliSearch#1177]
Hi,
While auditing meilliseach's source code, I've noticed that you use blocking functions inside actix web handlers which are `async` functions.
As we all know, blocking the event loop is a bad idea and may introduce hard to debug performance issues, especially in high-concurrency environments. The recommended time between each `.await` is 10 to 100 microseconds (https://ryhl.io/blog/async-what-is-blocking).

Here is an example of the incriminated code: https://github.com/meilisearch/MeiliSearch/blob/fa40c6e3d42ec9406828df3aa48e20f7c306bb68/meilisearch-http/src/routes/search.rs#L88

Issues that may be related: https://github.com/meilisearch/MeiliSearch/issues/900  & https://github.com/meilisearch/MeiliSearch/issues/522

The solution is to use a threadpool, either tokio's one or actix web's one.

Feel free to close if you have strong reasons to believe that it's not a problem 🌻

**Comment by MarinPostma** [comment]
This is an excellent point! The fix is straightforward, it'll be part of the next release. Many thanks

**Comment by skerkour** [comment]
Hey @LegendreM @Kerollmops I still think this issue is worth fixing because blocking the event loops may be the root cause of a lot of your performance issues (as highlighted by #1200,  #900, #925) and is basically a DOS vulnerability.

If you don't have bandwidth to fix it, I'm available this week as a freelance, it shouldn't take more than one day (half a day to audit the code and find the defects and half a day to create the PR fixing it)

**Comment by rubik** [comment]
@MarinPostma @LegendreM @Kerollmops Any update on this? It's a potential DOS vulnerability and a bit concerning. I also see it was removed from the 0.19.0 milestone.

**Comment by curquiza** [comment]
Hello @rubik!
We are working on a new search engine right now and this issue will be fixed in the new search engine release that will be the v0.21.0. I cannot give you an exact timeline for this release but be sure we are working on it. It will be part of the v0.21.0.

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
