### ISSUE TITLE
Is killing MeiliSearch safe ? Is there a loss in information?

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1179]
This is a self answering issue for future users that are curious about it. 

Killing MeiliSearch at any point is safe. 
Processes in MeiliSearch, synchronous, or asynchronous are [atomic](https://en.wikipedia.org/wiki/Atomicity_(database_systems)). This means that tasks are done in transactions. If the transaction for any reason fails or is killed in the middle of the transaction, nothing of the tasks will be committed to your database. 

>  An atomic transaction is an indivisible and irreducible series of database operations such that either all occur, or nothing occurs.

Imagine adding 100 documents in **one** batch to MeiliSearch. If you kill the process after 99 documents were correctly handled, when you restart MeiliSearch none of the 100 documents will be present in the dataset. 
Same goes if the 100th document raises an error. 

Depending on the status of each process when using the [update route](https://docs.meilisearch.com/guides/advanced_guides/asynchronous_updates.html) you can determine if a process has been committed to MeiliSearch or not.

- status: `enqueued` => If MeiliSearch is killed, when restarted the task will still have enqueued as status and will be processed eventually.
- status `processing` => If MeiliSearch is killed, when restarted, since it is atomic, there will be no consequences as none of the parts of the task has been committed to MeiliSearch, Meilisearch will retry the task same as an `enqueued` update.
- status `done` => If MeiliSearch is killed, this action is done and is permanently added to MeiliSearch. There is no data loss and your database/settings will be exactly the same as before you killed MeiliSearch.

Thus, killing MeiliSearch is **safe**!

**Comment by botsphp** [comment]
all processed or all failed.

**Comment by qdequele** [comment]
@bidoubiwa Could we close this issue?

**Comment by bidoubiwa** [comment]
Yes, this is a self answering issue!
