### ISSUE TITLE
Search doesn't work with mixed language strings

### ISSUE THREAD

**Issue by DmitriyKaraka** [meilisearch/MeiliSearch#1188]
**Describe the bug**
After update on v0.18.0 I can't find anything typing english symbols if string contains russian words.

**To Reproduce**
1. Install v0.18.0
2. Add document with searchable field contains russian and english words, for example: "ABB SafeRing CCCV Базовый с реле SEG WIC1, ТТ-W2+доп.катушка отключ 220 VAC+контакт сраб.реле 1НО+вывод слева+испытательные втулки"
3. Try to search "safering" => 0 docuemnts, then try to search "базовый" => 1 document
4. If string contains only english symbols, search work as expected

**Expected behavior**
If query contains english word, and in index there are documents with mixed strings, search must find this documents.

**Screenshots**
In both versions index contains the same documents

v0.17.0
![v0.17.0](https://user-images.githubusercontent.com/13933899/104429051-3a823800-5596-11eb-8649-4ac125d8411b.png)

v0.18.0
![v0.18.0](https://user-images.githubusercontent.com/13933899/104429090-453ccd00-5596-11eb-914f-bcf2268c1f60.png)

**Comment by LegendreM** [comment]
Hello @DmitriyKaraka,
we plan to make a first fix for the release 0.19,
for the moment multiple languages in the same attributes are not well supported,

thanks for your report!
