### ISSUE TITLE
Import suggestion, chunking?

### ISSUE THREAD

**Issue by Duoquote** [meilisearch/MeiliSearch#1189]
Importing 800k information to the engine, memory struggles a lot when you do it in one shot:
![Taskmgr_baXClMYOvm](https://user-images.githubusercontent.com/16341937/104457656-64018a80-55bb-11eb-8a34-c44c8e7668aa.png)
But when you do it in chunks like, sending 50k json array in multiple times, it stays low.
![image](https://user-images.githubusercontent.com/16341937/104457756-7ed3ff00-55bb-11eb-85ea-5575797dcb20.png)
It tries to index 50k by 50k when you upload that way.

I think it should be done on the engine side as it handles all the information it needs to index. Thanks for this brilliant engine!

**Comment by Duoquote** [comment]
![image](https://user-images.githubusercontent.com/16341937/104470978-59e78800-55cb-11eb-969b-4d3a1ed21e3e.png)
Also looks like there is no or too much less garbage collection after you insert documents, when you restart it, it goes back to normal.

**Comment by Kerollmops** [comment]
Hey @Duoquote,

You are right. The current indexing system is not that good for big datasets like yours. We are working on a new indexing system combined with a faster, better, and stronger search engine! It is currently able to index more than 115 million little documents without much memory usage.

About the high memory usage that is "garbage collected" on reboot, we are using Rust, and there is no such thing as garbage collection. I would say that the amount of memory that you see is related to [the memory mapping that LMDB does under the hood](https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/). This is the operating system that decides that there is enough RAM to memory map the whole file and no other program forces any memory reclaiming. Therefore the high memory usage you can see. This is normal and OK.

Thank you for the report!
