### ISSUE TITLE
Fuzzyness value per search 

### ISSUE THREAD

**Issue by sonic182** [meilisearch/MeiliSearch#1192]
Hi,

**Is your feature request related to a problem? Please describe.**
Would be nice to have fuzzyness value modifable per search, I have found better results in some searches when changing this value or making a custom rule

**Describe the solution you'd like**
A new search param for indicate fuzzyness value.

Maybe it worth to disable fuzzyness by param, so if someone wants to do a search with exact match, it could get it, something like searching for an id, product code, etc.

**Additional context**
ES example reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness

> Hello! Sorry for the delay in answering your questions. It's not possible to customize the number of typos allowed ATM. Don't hesitate to create an issue if you think it should be an option :)
> 
> _Originally posted by @CaroFG in https://github.com/meilisearch/MeiliSearch/discussions/1096#discussioncomment-259870_

**Comment by Kerollmops** [comment]
Hey @sonic182,

This is indeed a feature that we want to implement at some time, I am not sure if it has already been requested but you can use the [roadmap.meilisearch.com](https://roadmap.meilisearch.com/) website to request it by yourself.

Thank you very much, have a great day!

**Comment by 6543** [comment]
is not on the readmap anymore ... but i found it in https://github.com/orgs/meilisearch/discussions/377 ...

**Comment by macraig** [comment]
> is not on the roadmap anymore ... but i found it in https://github.com/orgs/meilisearch/discussions/377 ...

Re-directed to https://github.com/orgs/meilisearch/discussions/727
