### ISSUE TITLE
MeiliSearch in production

### ISSUE THREAD

**Issue by gurgeous** [meilisearch/MeiliSearch#1200]
Hi guys. Thank you so much for creating MeiliSearch. We love it and appreciate all your hard work! I wanted to supply a bit of feedback based on our experience rolling out MeiliSearch for production. 

Please don't take any of the below as criticism. We are very happy with MeiliSearch and honestly this is what we expected when we decided to adopt a relatively new project. I believe most of these issues have already been reported, but perhaps I can catalog some of the  roadblocks in one place. Maybe I can even learn Rust and help out!

1. Large indexes are not supported. We ran into this issue when trying to index ~1M documents. The solution was to shard the data set into multiple indexes. Our largest index is 250k documents, which seems to work fine. Updates are snappy. #900

1. Geo searches are not supported. We worked around this with [geohashing](https://en.wikipedia.org/wiki/Geohash). This is a crude solution, but one we are familiar with. Works great.

1. The default 1s timeout in the Ruby client is not sufficient while indexing. We were indexing documents in batches of 10,000. We raised the default timeout to 10s and all is well. `MeiliSearch::HTTPRequest.default_timeout(10)`

1. Building a robust `meilisearch.service` file for systemd was challenging. The one from the docs had to be buffed up to include User, Group, EnvironmentFile, Restart, WorkingDirectory, etc.

1. The current MeiliSearch version requires settings to be applied after indexing. This took a long time to figure out. #1160

1. MeiliSearch is not hardened against bad input. It's trivial to lock up the server with a long query. Bad queries will block legit queries from executing. We put some protections into our client code to guard against this, capping queries at 40 characters and 8 words. #925 #941

1. The snapshot/dump mechanism is a bit clunky for everyday usage. Snapshots are large, but can be created quickly. The dumps are 1/10 the size but slow to create. I haven't tried to import a snapshot yet, in part because it requires startup flags and I'm not sure how that works with brew services.

1. Some common search features are not yet implemented. For example, searching for "Burgers & Fries" will not return documents that contain "Burgers and Fries". A fix on our end would require a normalization step.

1. The typo handling is a big improvement over our previous postgres-based solution. I had to carefully explain to the team that it only kicks in on the fifth character, though. Likewise, we love that MeiliSearch will automatically concat/split queries. It can be confusing that it only kicks in on complete words, though. "Hello Worl" will return zero results but "Hello World" will match "HelloWorld".

1. I could not find a gem that integrates MeiliSearch with Rails & ActiveRecord. Rolling something custom wasn't too hard. https://github.com/sunspot/sunspot is a good starting point.

As I said at the top, thanks for all your hard work!

**Comment by curquiza** [comment]
Hello @gurgeous!

Thank you so much for your feedback, this will definitely help us to improve MeiliSearch!

I'm part of the integration team, so I will answer your Ruby/Rails feedbacks:

>     3. The default 1s timeout in the Ruby client is not sufficient while indexing. We were indexing documents in batches of 10,000. We raised the default timeout to 10s and all is well. `MeiliSearch::HTTPRequest.default_timeout(10)`

You can also change the timeout directly when declaring the client:
```ruby
MeiliSearch::Client.new($URL, $MASTER_KEY, timeout: 10)
```
Maybe should we also rise this default timeout? If you think we should, could you open an issue in the [meilisearch-ruby](https://github.com/meilisearch/meilisearch-ruby/issues) repository? 🙂

>     10. I could not find a gem that integrates MeiliSearch with Rails & ActiveRecord. Rolling something custom wasn't too hard. https://github.com/sunspot/sunspot is a good starting point.

I've just created an issue about it -> https://github.com/meilisearch/integration-guides/issues/85
This is definitely an integration we need to provide!

**Comment by gurgeous** [comment]
I think the default timeout in the Ruby client is correct. 1s is perfect for searches, and you don't want long timeouts with Rails because those requests are (usually) blocking. Definitely a longer value is required for large indexing jobs. Maybe it's a documentation issue?

**Comment by gurgeous** [comment]
Thanks @curquiza!

**Comment by francoism90** [comment]
@gurgeous What version are you using? It seems a new Tokenizer has been merged, don't know if this fixed the given 'Burgers & Fries' example, as I would be interested in getting these results as well. :)

**Comment by gurgeous** [comment]
Thanks @francoism90. I will try the new tokenizer. In the meantime, we worked around the problem by manually normalizing our text prior to document generation - `s/&/ and /`

Here is our `meilisearch.service` file for Ubuntu 20.04. I am not an expert on systemd and I crafted this based on other examples I was able to find.

```
# see https://docs.meilisearch.com/running-production/
# see https://git.archlinux.org/svntogit/community.git/tree/meilisearch/repos/community-x86_64/meilisearch.service

[Unit]
Description=MeiliSearch
After=network-online.target

[Service]
User=meilisearch
Group=meilisearch
Restart=on-failure
EnvironmentFile=/etc/environment
WorkingDirectory=/var/lib/meilisearch
ExecStart=/usr/bin/meilisearch \
  --env production \
  --http-addr 0.0.0.0:7700 \
  --master-key ${MEILI_MASTER_KEY} \
  --no-analytics true \
  --no-sentry true \
  --schedule-snapshot=true \
  --snapshot-interval-sec=3660

[Install]
WantedBy=multi-user.target
```

**Comment by francoism90** [comment]
@gurgeous Thanks for posting your config and workaround. I was browsing the documentation and it seems MeiliSearch offers configuring stop words, wouldn't it be a solution to add these to ignore `and, &, ..`?

I'm using Arch Linux, it seems they already provides a good service out-of-the-box. Do think it can't be merged as they depend on the distro settings.

**Comment by gurgeous** [comment]
I am not sure about stop words, I haven't tried that feature. Example - Is `&` considered a word, or are stop words applied after tokenization? Even if it worked we probably don't want to include `AND` as a stop word for our use case, though I'd have to discuss with the team.

**Comment by gurgeous** [comment]
Ignore bad click. I really need to invest in a mousepad... :)

**Comment by francoism90** [comment]
@gurgeous Maybe you want to use https://docs.meilisearch.com/guides/advanced_guides/synonyms.html#the-multi-way-association instead (e.g. `& => 'and', 'and' => &'`? I'm new to MeiliSearch, so my suggestions may be incorrect.

**Comment by gurgeous** [comment]
Same answer - synonyms might be applied after tokenization so `&` isn't a valid synonym. I actually may have tested that one, can't remember.
