### ISSUE TITLE
support a api to get  a sentence or phrase  the result of separates words

### ISSUE THREAD

**Issue by sixinyiyu** [meilisearch/MeiliSearch#1208]
feature request：

eg:
```
indexes/tokenizer?text=我是中国人
```
Expected  the result  is :
```
我、是、中国、中国人、国人

```

OS: CentOS Linux release 7.2.1511

Using MeiliSearch 0.18.1

**Comment by MarinPostma** [comment]
Hello @sixinyiyu, can you edit the issue and add more explanations?

**Comment by MarinPostma** [comment]
This may be supported in the future, but is not a priority

**Comment by qdequele** [comment]
Hello @sixinyiyu,

Thanks for this proposal. I added it on our possible features list. Unfortunately today it's not a feature we would like to add on MeiliSearch. We are focusing on features around searches, and improve the search experience. I don't know how you proposal could enter on this scope. That why, I would be glad to have more information about your usage, but until that, I will close this issue. This issue could be reopen by anyone that see the potential of the feature.
