### ISSUE TITLE
Atomicity of snapshot import

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1225]
**Describe the bug**

When using snapshot import using a wrong path (or maybe because it was a dir and not a file?) to the snapshot it: 
1. raises an error that is not very explicit
2. It creates a data.ms

Because of that, when relaunching meilisearch with the good path an error is raised because of existing `data.ms`.

**To Reproduce**
1. launch meilisearch with `--snapshot-import [path to a dir OR path to a wrong file]`
2. Error is raised: 
```
Error: failed to iterate over archive
```
3. Relaunch MeiliSearch with correct path
4. Error is raised
```
Error: database already exists at ".../data.ms", try to delete it or rename it
```

**Expected behavior**

`data.ms` should not have been created and error should have been more clear.

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
