### ISSUE TITLE
MeiliSearch shouldn't return 404 on `/` path when PRODUCTION environment enabled

### ISSUE THREAD

**Issue by eskombro** [meilisearch/MeiliSearch#1235]
**Is your feature request related to a problem? Please describe.**
When MeiliSearch is run in `development` environment, a GET request to `/` path will return the MeiliSearch test dashboard. When `production` environment is enabled, it returns a 404 error. Even if at first sight this makes sense, since the dashboard shouldn't be enabled in production, it is confusing for some users. I have had several situations and feedback of users moving their MeiliSearch from `dev` to `prod` and reading this 404 error as a problem in MeiliSearch configuration. (I.E. recent example: https://github.com/meilisearch/meilisearch-digitalocean/issues/115)

**Describe the solution you'd like**
MeiliSearch server could send any other type of answer when doing an HTTP request on `/` while the server is in production: `No content`, `Unathorized`, or a message to the user are a few examples of what could be returned. II would like to debate what is the best option since I don't have the perfect answer, but this behavior clearly creates confusion for our users.

**Comment by curquiza** [comment]
This fix needs to be done. Here what we decided about the implementation: when MeiliSearch is in the production environment, the `/` route needs to return a `200` with a JSON response `"MeiliSearch is running"`. The whole API returning JSON responses, this response needs to be in JSON as well.

**Comment by eskombro** [comment]
This sounds like a great solution to this problem, thanks a lot @curquiza !
