### ISSUE TITLE
Combining ANDs and ORs in ways that are prohibited by Algolia

### ISSUE THREAD

**Issue by CodeWithOz** [meilisearch/MeiliSearch#1236]
**Is your feature request related to a problem? Please describe.**
Algolia [limits](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/combining-boolean-operators/#combining-ands-and-ors) the type of AND/OR combinations that can be done when matching by filters/facets. Specifically, `A OR (B AND C)` queries are not allowed. I posted about trying to do this with Algolia [here](https://stackoverflow.com/questions/65496938/how-to-perform-an-a-or-b-and-c-filter-facet-match-in-algolia).

**Describe the solution you'd like**
I haven't gotten to far into the weeds with MeiliSearch, I'm considering it as an alternative to my current algolia setup. The documentation doesn't expressly state that this `A OR (B AND C)` type of query is prohibited so I'd like some confirmation if possible, thanks.

**Comment by MarinPostma** [comment]
No there are currently no limitations on that
