### ISSUE TITLE
No space left on device error on saving snapshot.

### ISSUE THREAD

**Issue by mzperix** [meilisearch/MeiliSearch#1237]
## What happens
When creating snapshot, meilisearch opens a temp dir which may be on a different disk than `snapshot_path` and even if enough disk space is available for the snapshot path, it fails with `No space left on device`.

## Expected behaviour
Should create temp dir inside snapshot_path.

https://github.com/meilisearch/MeiliSearch/blob/f83caa6c40a01c931ee4ccde4fb1113067fda488/meilisearch-http/src/snapshot.rs#L32

**Comment by MarinPostma** [comment]
Ah yes! Lone 32 is the faulty call to temp_dir. That is one easy fix.

**Comment by LegendreM** [comment]
Hello @mzperix, 
we use `TempDir` lib to manage automatically the directory deletion 🤔,
As you said we should create a standard directory and manually delete it at the end of the process.

**Comment by MarinPostma** [comment]
@LegendreM not necessary: https://docs.rs/tempdir/0.3.7/tempdir/struct.TempDir.html#method.new_in
