### ISSUE TITLE
[mini-dashboard] Long JSON values overlap each other

### ISSUE THREAD

**Issue by okyanusoz** [meilisearch/MeiliSearch#1240]
**Describe the bug**
In the MeiliSearch web interface, if the values are very long, they can overlap each other.

**To Reproduce**
1. Create a JSON document with a long value(see below comment for an example)
2. Create an index and add the JSON document
3. Open up the web interface
4. Scroll down a little bit 
5. See the error

**Expected behavior**
The values shouldn't be overlapping each other.

**Screenshots**
Here is a screenshot:
![Screenshot](https://user-images.githubusercontent.com/46757266/107367164-04ca6380-6af0-11eb-9bb4-cbddf8ae2c5f.png)

 - OS: macOS 10.15
 - Browser Mozilla Firefox 85.0
 - Version 0.18.1 (Commit SHA bf3f36b46ecddb6240092193d578eb221fde2a65)

**Additional context**

*Possible fix:* Truncate values that are longer than a number of characters

**Comment by okyanusoz** [comment]
Hello,
I made a sample JSON file that triggers this bug.
Here it is: https://gist.github.com/okyanusoz/740961e3fc83dc75b9e0a199014e3efd
A simple cURL will do the job. And then you need to scroll down a little bit.
Oh, and if you are curios, here is the code that I used to generate it: https://gist.github.com/okyanusoz/980834fd78380e58239f8edaff05d639

**Comment by barabulkit** [comment]
Hello, i wasn't able to reproduce this bug yet, but i agree that it probably could be usefull to show only part of the content in case if it is too long (i got tired while scrolling up to second document), and add something like "..." at the end of content, and when you click on it, full content will be at the screen. If you think that it is neccessary feature i would like to take this issue.

P.S. i think it also would be good to add some configuration, like enable/disable this, and the length of the resulting content

**Comment by okyanusoz** [comment]
I have created a PR for this. See #1258

**Comment by curquiza** [comment]
Fixed by #1240

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
