### ISSUE TITLE
Promoting certain items

### ISSUE THREAD

**Issue by szepeviktor** [meilisearch/MeiliSearch#1245]
Hello! I'm not a user yet.
MeiliSearch looks promising!

Is it possible to move some item from somewhere on the result list to the top?
#priority

**Comment by MarinPostma** [comment]
I think you can use custom ranking rules, and add a priority field to your documents that you'd use to sort.

**Comment by szepeviktor** [comment]
Thank you.
https://docs.meilisearch.com/learn/core_concepts/relevancy.html#adding-your-rules
