### ISSUE TITLE
Partial word matching?

### ISSUE THREAD

**Issue by NicTorgersen** [meilisearch/MeiliSearch#1248]
**Describe the bug**
I'm trying to get a document from Meilisearch by partially typing in a word.

**To Reproduce**
1. Add index
2. Add a document with some attribute, with the content of "Github" for example
3. Search for "hub"
4. No results

**Expected behavior**
Documents which contain the partial word should ideally be returned, right?

**Additional context**
Can't find anything about this in the documents, tried searching for "partial word matching" or similar, but so far nothing is said anywhere about this in relation to MeiliSearch.

**Comment by NicTorgersen** [comment]
Found the "Matches" option.

**Comment by CaroFG** [comment]
Hi @NicTorgersen! MeiliSearch is designed for a search-as-you-type use, therefore it is built based on [prefix search](https://docs.meilisearch.com/reference/under_the_hood/prefix.html#prefix-searchl) It's one of our primary features. Following your example, you will get results for "git" but it is not designed to provide results for "hub". It's not an issue, it's just its design :) There are users that use https://nlp.h-its.org/bpemb/ to preprocess their dataset and split words, if it can help. If you think MeiliSearch should have this feature, you can add it to the [roadmap](https://roadmap.meilisearch.com/tabs/5-ideas) :)

**Comment by veneliniliev** [comment]
is there any solution to the case?

**Comment by curquiza** [comment]
hey @veneliniliev 
No workaround at the moment

FYI @meilisearch/product-team, I ping you since it's an old issue. It does not mean we will do it of course, because as Caro said, MeiliSearch is currently designed to provide a search-as-you-type experience.

**Comment by veneliniliev** [comment]
yes, i make this for phone number... its work for now. tnx.

**Comment by ghomem** [comment]
> yes, i make this for phone number... its work for now. tnx.

Can you share how you made it work for a subtring of the phone number?

**Comment by veneliniliev** [comment]
> > yes, i make this for phone number... its work for now. tnx.
> 
> Can you share how you made it work for a subtring of the phone number?

something like this:

```
protected function wordEmbedding(int|string|null $word): string
    {
        $word = trim($word);

        if (empty($word)) {
            return '';
        }

        $return = '';
        for ($i = 0; $i < Str::length($word); $i++) {
            $return .= ' ' . Str::substr($word, $i);
        }

        return trim($return);
    }
```
