### ISSUE TITLE
Web Interface Design

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/MeiliSearch#1261]
# Web Interface Design Feedback (for eventual re-design)

It’s been a while since the web interface was designed, but it’s very important and visible—ships with MeiliSearch and is the first entry-point for most newcomers (especially those without a lot of API/command line experience). Particularly with v1.0 coming soon, we should think about redesigning it in the near future. Here are some small points of feedback for whomever ends up working on this project: 

- ~~**Problem**: The API key text box is described as “optional”, which is confusing. An API key is optional for a MeiliSearch instance; however, if you do have an API key set then the web interface will not make any search queries without the API key (in other words, it’s not optional to input the key into the web interface).~~

- ~~**Potential solution**: It would be better for the web interface to infer whether your instance has an API key and show or hide the text input box accordingly. If not possible, then there should at least be a toggle switch: API Key? YES | NO, with the text input box appearing only if “YES” is selected.~~

**FIXED** by #1265 
---
- **Problem**: Missing information: total number of documents in the index.

- **Potential solution**: Instead of only displaying “Documents: {number of returned documents}”, display “Hits: {number of returned documents}” and “Documents: {total number of documents}”
---
- **Problem**: No support for faceted search

- **Potential solution**: Left-hand facet area with text truncation (to handle overly long facet values)
---
- **Problem**: ~~Before performing any searches, the index list appears but no documents are displayed (document counter says “0 documents”). This makes it hard to tell if the interface is functioning or if documents have successfully been added to the index.~~ If your instance is protected by an API key and you open the web interface, you will not see any indexes or documents until after entering your API key. This is normal; however, it's strange that even after the API key has been verified, no documents are displayed until the first search is performed. Accessing a placeholder search requires typing, then deleting a query.

- **Potential solution**: Entering (and verifying) the API key should automatically perform a Placeholder Search on the current index; this would be more consistent with online search interfaces.

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
