### ISSUE TITLE
Unsuccessful call to Amplitude - Invalid certificate UnknownIssuer

### ISSUE THREAD

**Issue by Braunson** [meilisearch/MeiliSearch#1262]
**Describe the bug**

This is the error returned when checking the status of Meilisearch

```
[2021-02-23T00:35:51Z ERROR meilisearch::analytics] Unsuccessful call to Amplitude: https://api.amplitude.com/httpapi: Network Error: invalid certificate: UnknownIssuer
```

**To Reproduce**
Try to install Meilisearch as a service inside [Laravel Homestead](https://github.com/laravel/homestead).

**Expected behavior**
Expected no errors?

**Additional context**
I'm thinking this may be due to the fact Meilisearch cannot call outside Homestead and this is causing the issue. My goal is to create a small script to install Meilisearch and establish it as a service for Laravel Homestead (Virtual VM) with the goal of making Meilisearch a native thing installed with Laravel Homestead.

**Comment by qdequele** [comment]
Hello @Braunson, Yeah, I think it's normal even if this error should probably be a warning instead of an error. You can deactivate the analytics like explained in [the documentation](https://docs.meilisearch.com/reference/features/configuration.html#analytics).

**Comment by Braunson** [comment]
Closing as MeiliSearch is now apart of [Laravel Homestead](https://github.com/laravel/homestead/releases/tag/v12.1.0) and this error is more of a warning and less a breaking error.
