### ISSUE TITLE
API implementation for adding and updating documents with a primary key is confusing

### ISSUE THREAD

**Issue by sanders41** [meilisearch/MeiliSearch#1274]
When including a primary key with either adding or updating documents, the API implementation is a bit confusing. I have been discussing this issue with @bidoubiwa [here](https://github.com/meilisearch/meilisearch-python/issues/224) and now understand that my issue was the index was already created so it doesn't get updated, but as the end user this was confusing. I was not expecting to receive a failed status and was expecting to get the primary key back as the one I specified and when this didn't happen I didn't understand why at first.

I find the update documents part is even more confusing. I understand that the primary key is there to be sent in case the index hasn't been created yet, but I can't think of a situation where I would ever use and update in this case instead of add.

**Comment by curquiza** [comment]
Hello @sanders41,
I've answered in the meilisearch-python issue about the confusion of "update documents" https://github.com/meilisearch/meilisearch-python/issues/224#issuecomment-793026949. I think this is an issue about the SDK and not MeiliSearch itself.
About the silent error that does not inform you the primary key cannot be updated, there is already an issue -> https://github.com/meilisearch/MeiliSearch/issues/1223
Tell me if I miss-understand something 🙂

**Comment by sanders41** [comment]
Thanks @curquiza with this I'll close this one.
