### ISSUE TITLE
OpenAPI v3 / Swagger Docs

### ISSUE THREAD

**Issue by cryptoroo** [meilisearch/MeiliSearch#1277]
**Is your feature request related to a problem? Please describe.**
Swagger / OpenAPI v3 is a very useful way of documenting APIs. 

**Describe the solution you'd like**
In an ideal world the code would expose /docs path where a swagger UI would allow for testing and documentation. 

**Describe alternatives you've considered**
The current API documentation is excellent. If there isn't bandwidth to do this I am happy to create an initial spec. 
My go programming is a bit rusty but I can generate the swagger.json fairly easily.

**Comment by cryptoroo** [comment]
Yes - closing

**Comment by revskill10** [comment]
@cryptoroo It's 404.

**Comment by wassfila** [comment]
it just moved it's currently referenced here https://www.meilisearch.com/docs/reference/api/overview with direct link here
https://bump.sh/meilisearch/doc/meilisearch.yaml
but as those things might get reorganized over time, it is possible to re-navigate e.g. home>API reference>Overview>OpenAPI
