### ISSUE TITLE
SearchableAttribute order is impacted by settings added before documents

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1285]
**Describe the bug**
If you first add settings with for examples `attributesForFaceting: ["genres"]`, when you then add your first documents the "hidden" order of searchable attribute will have `genres` at the start of attributesForFaceting

Example, 
on the movie dataset with the following fields in this order: `id, title, overview, genres` the hidden searchable attribute order will be the following:  
```
genres, id, title, overview, ...
```

**To Reproduce**
1. Add settings with attributeForFaceting
2. add documents
3. search on any document
4. Genre is the first field displayed in the hits

**Expected behavior**
`Genres` should have kept its position based on the first document added

I cannot remember if there is already an issue about this.

**Comment by curquiza** [comment]
It's an already know behavior. It's because the "genres" field was known by MeiliSearch before the other fields (when pushing the first document). That's why it's at the top and is not taken into account when pushing the first documents.

**Comment by curquiza** [comment]
Duplication of #1495
