### ISSUE TITLE
Optional Words like Algolia

### ISSUE THREAD

**Issue by LucaIaconelli** [meilisearch/MeiliSearch#1288]
Hello,

I wanted to ask if there was a functionality in meilisearch similar to the optional words of Algolia.

Thank you in advance for your reply

**Comment by curquiza** [comment]
Hello @LucaIaconelli, do you mean the ranking rules "words"? Here is our docs about ranking rules: https://docs.meilisearch.com/learn/core_concepts/relevancy.html#ranking-rules

The "words" criterion is not available for the moment but will be in the next search engine we are working on right now :)

**Comment by mzperix** [comment]
Excuse me @curquiza, just to clarify: the "words" ranking rule which will result in showing results with _not_ all words matching will be released in 0.21.0? That would be great, I have been long waiting for not strictly matching on all words.

**Comment by curquiza** [comment]
@mzperix yes :)

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
