### ISSUE TITLE
ARM Docker image

### ISSUE THREAD

**Issue by fharper** [meilisearch/MeiliSearch#1290]
We should add to the release the arm (M1 chip) release for macOS now that we fixed #1136

**Comment by robsontenorio** [comment]
Docker image for m1 arm64 is missing. Any plans to release it?

**Comment by curquiza** [comment]
No precise ETA but we will work on it 🙂

**Comment by curquiza** [comment]
Until we provide it, a user provides it here: https://github.com/meilisearch/MeiliSearch/issues/1347#issuecomment-913358145 🙂

**Comment by mayel** [comment]
Any chance you're planning to support this soon? Many more people are starting to use M1...

**Comment by robsontenorio** [comment]
Here is how I build mutiarch docker images through GitHub Actions. 

https://github.com/robsontenorio/laravel-docker/blob/master/.github/workflows/docker-publish.yml

**Comment by curquiza** [comment]
Hello @mayel 
For people using MacOs M1, the `meilisearch-macos-amd64` will work thanks to Rosetta you can install on your Mac
For people using Docker, on M1 or not, you can use our docker image

```bash
docker run -p 7700:7700 getmeili/meilisearch:v0.27.2 meilisearch --master-key=XXX
```

Sorry if I miss-understand your post, just a clarification for people coming here
