### ISSUE TITLE
please document use as an embedded search library

### ISSUE THREAD

**Issue by bionicles** [meilisearch/MeiliSearch#1297]
**Is your feature request related to a problem? Please describe.**
This looks amazing to embed it in another project to allow offline-first terminal ui search. However, the docs seem mostly directed to use via remote server-client not something to search locally inside a CLI or Terminal UI

**Describe the solution you'd like**
Please just a simple usage example of how to embed this inside another rust crate (think a CLI or Terminal UI to fetch list of remote JSON and index it)

**Describe alternatives you've considered**
tantivy, skim

**Additional context**
I'd like to build a library, not a service

**Comment by ppamorim** [comment]
This is pretty possible if you use the core library from the project, but it  won't be easy to implement. The project was created around actix-web (it was converted to) but if you are really interested, this is pretty possible. You can read the source code of these two files and create something based on that:

https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/src/main.rs
https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/src/lib.rs

Good luck!

**Comment by curquiza** [comment]
Hello @bionicles

We are currently working on a search engine library that will be used by MeiliSearch soon!
https://github.com/meilisearch/milli
⚠️ This is a work in progress and will break a lot, so we don't recommend production usage. Also, it's complicated to accept contributions on it for the moment.

For a simple usage of the search only:
https://github.com/meilisearch/milli/blob/main/search/src/main.rs
Here is an HTTP server that accepts updates and searches for a single index:
https://github.com/meilisearch/milli/blob/main/http-ui/src/main.rs

**Comment by curquiza** [comment]
Closing this issue then
