### ISSUE TITLE
Add some logging to the project

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#13]
It can be for the `http` server or in the `raptor` library.

Using the [`log`](https://crates.io/crates/log) crate can be a good start.

**Comment by djKooks** [comment]
Would it be good to make separate crate, such as `meilisearch-log`?

**Comment by Kerollmops** [comment]
Ooops, it has already been done, we only use the log crate and it works fine.

It seems I need to make a pass on the ["good-first-issue"](https://github.com/meilisearch/MeiliSearch/labels/good%20first%20issue) issues :)

Thank you!
