### ISSUE TITLE
how to stop ongoing updateDoc or AddDoc operation

### ISSUE THREAD

**Issue by NatBLida68** [meilisearch/MeiliSearch#1305]
OK first of all that was my mistake  
i just made a infinite for-loop 😜
```
for($i=1;$i>-1;$i++){
    $client->index('test')->addDocuments([
        ['id'=>$i]
    ]);
}
```
i got request timed-out  after some time and so i closed that window 
and this keep going  in terminal  and the in  UI page in each refresh number is increasing 
tried everything except deleting  index test 
is there any way to stop it

**Comment by curquiza** [comment]
Hello @NatBLida68!

If I understand well you want to know if you can cancel the updates (your document pushes).
In this case, this is retated to https://github.com/meilisearch/MeiliSearch/issues/1304
