### ISSUE TITLE
Add Java SDK to meilisearch.com homepage

### ISSUE THREAD

**Issue by zack-harrison** [meilisearch/MeiliSearch#1313]
# Summary

Add the Java SDK to the meilisearch.com homepage.

# Motivations

Initially my org wasn't interested in using meilisearch because we didn't want to have to maintain our own Java sdk. In reality, meilisearch has a Java sdk, it just wasn't listed on the website.

**Comment by curquiza** [comment]
Hello!

Sorry for the lack of communication!

Our landing page is kind of obsolete right now, we've just hired someone to re-do it 😁
We also need to highlight our SDKs on the home page of our docs and in the MeiliSearch README. This is planned.

Here is the current list of the SDKs and integrations we maintain: https://docs.meilisearch.com/learn/what_is_meilisearch/sdks.html
