### ISSUE TITLE
is it support utf-8 characters ,like persian or arabic ?

### ISSUE THREAD

**Issue by Hesammousavi** [meilisearch/MeiliSearch#1314]
is meilisearch support utf-8 characters ,like persian or arabic ?

**Comment by curquiza** [comment]
Hello!

We might find what you need here: https://docs.meilisearch.com/reference/features/language.html#

We support the UTF-8 characters but we definitely need to improve our tokenizer for the Arabic language. Feel free to give us any feedbacks 😁

**Comment by curquiza** [comment]
I'm closing this issue since the documentation gives the answer, feel free to re-open if you are any question about the persian and arabic languages 🙂
