### ISSUE TITLE
Slow Docker build time (no dependencies cache)

### ISSUE THREAD

**Issue by shekhirin** [meilisearch/MeiliSearch#1317]
### Is your feature request related to a problem? Please describe.
Every time I want to build the Docker image (or build happens in GitHub Actions) it is required to redownload and recompile all the dependencies listed in Cargo.toml files across the project.
It slows down the development process and the CI a lot.

### Describe the solution you'd like
Separate Docker project compilation phase into multiple steps:
1. Download and compile dependencies from all Cargo.toml files
2. Compile project files

**Comment by curquiza** [comment]
I would rather not close this issue since it's not merged into MeiliSearch

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
