### ISSUE TITLE
Make the indexing more customizable

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#132]
The engine uses a lot of magic numbers. Mostly during the indexing phase. For the typo tolerance configuration, the number of words indexed in a field, the biggest possible proximity, etc.. 

This issue should allow the end user to configures all these parameters. 

One possibility is to store them on the config already saved in the KV store. The search and the indexing config parts could be separated.

**Comment by qdequele** [comment]
This is no more relevant, we close it, feel free to comment here or open a new issue.

**Comment by eikooc** [comment]
Hi. @qdequele I'll take you up on commenting here. 
Is it possible to configure the typo tolerance and if not, is this something that can be made? :)

**Comment by curquiza** [comment]
Hello @eikooc it's currently not possible to customize the typo tolerance. However, we have a discussion open on our product team side. If you take the time to describe your usage and your need, it will be definitely helpful 😄 
https://github.com/meilisearch/product/discussions/312
