### ISSUE TITLE
Remove ARMv7 support

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1320]
We currently fail to push binary for ARMv7: https://github.com/meilisearch/MeiliSearch/actions/runs/551744921

**Comment by curquiza** [comment]
https://github.com/meilisearch/MeiliSearch/runs/2955826451?check_suite_focus=true

**Comment by qdequele** [comment]
After reflection and research, it seems that [ARMv7 is in 32bit](https://en.wikipedia.org/wiki/ARM7). Without more demand for 32bit support, we don't consider this to be important enough to consider significant development. If you need the MeiliSearch version in ARMv7 don't hesitate to contact us on our [Slack](https://slack.meilisearch.com) or to request it on our [public roadmap](https://roadmap.meilisearch.com).

**Comment by curquiza** [comment]
Reopen because still present in the CI
