### ISSUE TITLE
Inconsistency in snapshots documentation

### ISSUE THREAD

**Issue by regzon** [meilisearch/MeiliSearch#1323]
**Describe the bug**
[Documentation about snapshots](https://docs.meilisearch.com/reference/features/snapshots.html#starting-from-a-snapshot) states that there is an env variable (called `MEILI_IMPORT_SNAPSHOT`) that allows starting the server from the snapshot, but I didn't find this option on the [configuration page](https://docs.meilisearch.com/reference/features/configuration.html#options) or in the source code.

**Comment by curquiza** [comment]
Is it this flag you mean? https://docs.meilisearch.com/reference/features/configuration.html#import-snapshot

**Comment by regzon** [comment]
> Is it this flag you mean? https://docs.meilisearch.com/reference/features/configuration.html#import-snapshot

Yeah, the issue is that this functionality can be only controlled via the CLI option, but the "Snapshots" page states that this can be done via the env variable (which is not true).

**Comment by regzon** [comment]
Sorry, I didn't know that the documentation is placed in another repository. I'll close this issue and open a new one in the documentation repository.

**Comment by curquiza** [comment]
> Yeah, the issue is that this functionality can be only controlled via the CLI option, but the "Snapshots" page states that this can be done via the env variable (which is not true).

This might be something we need to fix in MeiliSearch 🙂
@LegendreM do you remember if there is any reason not to add the `MEILI_IMPORT_SNAPSHOT` env variable usage? Otherwise it's a fix to do.

**Comment by regzon** [comment]
I think that the choice was taken in the issue https://github.com/meilisearch/MeiliSearch/issues/1033

**Comment by curquiza** [comment]
Hahah thanks for the investigation I should have done! 😂 Sorry Many for the GH notification.
The fix should be done in the docs indeed 🙂

Thank you again @regzon!!! 🙏

**Comment by regzon** [comment]
Thank you for the fast response!
