### ISSUE TITLE
Query Chinese data documents  

### ISSUE THREAD

**Issue by Song0013** [meilisearch/MeiliSearch#1324]
Query Chinese data documents and return the sequence of result sets, which are not calculated according to the rules of "Proximity", "Attribute", "Words Position", "Exactness" and "Proximity"
![image](https://user-images.githubusercontent.com/18046591/113230688-2532c500-92cc-11eb-84df-647c4c1bbc4b.png)

**Comment by curquiza** [comment]
Hello @Song0013!
Thanks for your feedback. Can you send us (not in screenshot) your dataset? Or at least the concerned documents?
Also, can you send us the query you typed?

**Comment by Song0013** [comment]
steps：

1.First add the document data set

[
    {
        "movie_id": "1",
        "title": "我是中国人",
        "poster": "中国的颐和园",
        "overview": "Yes",
        "release_date": "2019-03-24"
    },
    {
        "movie_id": "2",
        "title": "中国",
        "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
        "overview": " A boy is given the ability to become an adult superhero in times of need with a single magic word.",
        "release_date": "2019-03-24"
    },
    {
        "movie_id": "3",
        "title": "中国魂",
        "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
        "overview": " A boy is given the ability to become an adult superhero in times of need with a single magic word.",
        "release_date": "2019-03-24"
    },
    {
        "movie_id": "4",
        "title": "我是中国人",
        "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
        "overview": "中国的美事",
        "release_date": "2019-03-24"
    }
]

2.Query conditions
{ 
	"q": "中国" 
}
--------------------------------------------------------------------------------------

Problems that arise： Headings have been sorted in "Typo" order，The title field values of Movie_ID 1 and 4 are both "I am Chinese", so the sorting cannot be distinguished. At this time, the rule of "Proximity" or the rule of "Attribute" should be implemented, but they are not. The following is to return the result set:

{
    "hits": [
        {
            "movie_id": "2",
            "title": "中国",
            "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
            "overview": " A boy is given the ability to become an adult superhero in times of need with a single magic word.",
            "release_date": "2019-03-24"
        },
        {
            "movie_id": "3",
            "title": "中国魂",
            "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
            "overview": " A boy is given the ability to become an adult superhero in times of need with a single magic word.",
            "release_date": "2019-03-24"
        },
        {
            "movie_id": "1",
            "title": "我是中国人",
            "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
            "overview": "中国的美食",
            "release_date": "2019-03-24"
        },
        {
            "movie_id": "4",
            "title": "我是中国人",
            "poster": "中国的颐和园",
            "overview": "Yes",
            "release_date": "2019-03-24"
        }
    ],
    "offset": 0,
    "limit": 20,
    "nbHits": 4,
    "exhaustiveNbHits": false,
    "processingTimeMs": 0,
    "query": "中国"
}

**Comment by Song0013** [comment]
I have made a specific reply on GitHub, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Clémentine ***@***.***&gt;; 
发送时间: 2021年4月1日(星期四) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [meilisearch/MeiliSearch] Query Chinese data documents   (#1324)





 
Hello @Song0013!
 Thanks for your feedback. Can you send us (not in screenshot) your dataset? Or at least the concerned documents?
 Also, can you send us the query you typed?

**Comment by curquiza** [comment]
Thanks for your help @Song0013! I'm testing this as soon as possible!

**Comment by Song0013** [comment]
You're welcome. Please let me know if you make any progress,thank you

**Comment by Song0013** [comment]
Hello, I have normalized the document data in Step 1 again, please check

**Comment by curquiza** [comment]
Hello @Song0013!

I checked with the CTO, indeed, it's not normal. We are currently on a new search engine (a lot of work is done on criteria), and we hope the new search engine (released in the v0.21.0) will fix your issue. Be sure we will integrate this test into our process to keep you informed!

Thanks for your feedback!

**Comment by curquiza** [comment]
Hello @Song0013! Sorry for the misunderstanding, but it seems, after a better investigation that these result is completely expected, see the answer of one of our core-engine developer -> https://github.com/meilisearch/milli/issues/265#issuecomment-872050832

Sorry again for the mistake! I'm closing this issue then.
