### ISSUE TITLE
Attributes for faceting cannot be defined for float/int values. Works only for string?

### ISSUE THREAD

**Issue by mikhi** [meilisearch/MeiliSearch#1328]
Hello friends,
I'm trying to define attributes for faceting, in order to use them with vue-instantseach library.

The problem is that i cannot set facets for attributes that contains values as float/double/int
This is a bug or an expected behavior?

I'm looking for example to implement:
`<ais-range-input attribute="price_old" />` this widget requires values to be int | float

**The desired facets**
![image](https://user-images.githubusercontent.com/1406293/113303561-e15eb080-9309-11eb-81b2-9ba19f34c8a5.png)

Fields: `price_old` and `in_stock` fields are not set.
`price_old`: double
`in_stock`: boolean 0/1
![image](https://user-images.githubusercontent.com/1406293/113303434-c2601e80-9309-11eb-8480-a36ba0c1c8d7.png)

Thanks,
Mihai

**Comment by curquiza** [comment]
Hello, thanks for this feedback!
We are aware of this missing feature and this will be integrated into the v0.21.0!
Closing this since it's a duplication of https://github.com/meilisearch/MeiliSearch/issues/919
