### ISSUE TITLE
Not search or index data

### ISSUE THREAD

**Issue by romvarac** [meilisearch/MeiliSearch#1329]
Hi team,
My issue is not search or index data in some time (after running 1-2 hours), and restart it => could be search and index data.
- Resource: 16G Ram and 8 CPU
- Set up
```
docker run -d -it --rm \
    -p 7700:7700 \
    -v /root/meilisearch/production/data.ms:/data.ms \
    --name meilisearch \
    -e MEILI_MASTER_KEY= \
    -e MEILI_HTTP_PAYLOAD_SIZE_LIMIT=1048576000 \
    getmeili/meilisearch:v0.19.0
```
- Index data: 2 index with 514 documents and 11593 documents.
But, sometime could not search or index data.
Check status service in docker: up (everything is ok).
Thanks for any support.

**Comment by curquiza** [comment]
Hello @romvarac! What are the errors you have? Can you detail your steps to get the errors please?

**Comment by curquiza** [comment]
Closing due to the absence of an answer. Feel free to re-open
