### ISSUE TITLE
Store the default pagination configuration

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#133]
The search engine has as default pagination by 20 documents. Set this value alterable.

**Comment by MarinPostma** [comment]
@qdequele Isn't that already the case?

**Comment by qdequele** [comment]
Nope, this issue is about to remove magic numbers from the sources and add more configuration. But at the moment, I think that we should not give the possibility to over-configure the engine. We must still clear and easy to use. 

We could probably close a lot of issues like this one. With the message "This issue is closed because it is not asked from users. If you need this feature feel free to reopen it or create a new one."

**Comment by curquiza** [comment]
Is it about the kind of same configuration that Algolia has with `pages` and `hitsPerPages`?
See: https://www.algolia.com/doc/api-reference/api-parameters/page/
Because this feature would be great for Front-End implementation 😅 (I would like MeilISearch to have it)

**Comment by qdequele** [comment]
This issue is about the ability to set the default hitsPerPages as a setting. But since we no longer have this option on the search, this issue is outdated. 

If you want to talk about adding `pages` and `hitsPerPages` in search parameters, please, feel free to create a new issue.
