### ISSUE TITLE
The software is tracking the user without consent of the user

### ISSUE THREAD

**Issue by nicoduesing** [meilisearch/MeiliSearch#1334]
**Describe the bug**
I have installed the meilisearch package through pacman and started it in the terminal. Afterwards the following error appeared:
> ERROR meilisearch::analytics] Unsuccessful call to Amplitude: https://api.amplitude.com/httpapi: Connection Failed: Connect error: Connection refused (os error 111)

The domain name api.amplitude.com is blocked in the DNS Server as it is a tracking provider to spy on users. I was surprised as I don't expect open source software to spy on me and there was no question whether I like to allow it. So this should only be activated after the user gave it's consent or be removed from the software completely. To spy on users without their consent is at least problematic if not illegal in places like the EU.

**To Reproduce**
1. Take an Arch/Manjaro Linux and use pihole ad DNS blocking tracking providers.
2. Execute `sudo pacman -S meilisearch`
3. Execute `meilisearch`

**Expected behavior**
The Software does not spy on users, so no connection to any external Server will be established.

**Comment by A5rocks** [comment]
https://docs.meilisearch.com/reference/features/configuration.html#options it can be disabled / it's pretty minimal, fwiw. (I believe this should default to `true` but meh, whatever.)

Also, it's right there in the startup screen: https://github.com/meilisearch/MeiliSearch/blob/9587ea7f06042a27e09001398479151a97061785/meilisearch-http/src/main.rs#L148-L155.

**Comment by curquiza** [comment]
Hello @nicoduesing 

Thanks for this feedback!
FYI, the data is anonymized so this is not a GDPR issue. 

As @A5rocks said, MeiliSearch informs you about the telemetry:

<img width="877" alt="Capture d’écran 2021-04-12 à 18 11 54" src="https://user-images.githubusercontent.com/20380692/114426726-a5093b00-9bba-11eb-83b5-50c57065bcb6.png">


However, we agree this would be better to inform the users how to easily disable it with a note in the display for example. We will integrate this change in the next release, see this issue in the appropriate repo: https://github.com/meilisearch/transplant/issues/141

Thanks for your feedback @nicoduesing, and also thank you @A5rocks for taking the time to answer to this 😊

**Comment by nicoduesing** [comment]
@A5rocks @curquiza Thanks for your responses. I welcome the drive for more transparency. If you don't send data that can identify users and amplitude.com doesn't saves IP addresses it is maybe not an GDPR issue but maybe still a trust issue.

I understand that it is helpful to have such data. But collecting this without consent doesn't seem very sympathetic. Such data would certainly be helpful for other open source projects, too. Like for VLC, which was also developed by a French company. But they just count downloads. VLC isn't collecting any telemetry while it is executed on the users device.
Maybe you can do a survey instead to get the same information. Or you switch it to an opt in and ask the user after start up.

This is a very cool project and was really easy to use. But I lost a bit of trust to it, after I have seen the messages. I was wondering what kind of data you collect, if it is really only anonymous data. Whether amplitude.com can be trusted. Whether there might have been more questionable decisions made. You may have built this in with the best intentions and the greatest care for data security, but what is visible as a first impression is that data is being collected. It would be a shame if the project would not spread because others get similar experiences and don't ask.

I'm not sure how big of a problem that is. Maybe a lot also don't use tools like a pihole and don't get that problem so prominent as I did. But at least there are people that care about such things. Maybe even in your team. Imagine you discover a new tool, it sounds promising but one of the first things you see is, that it collects data about your usage by default. Would you trust it? I just wanted to add that as a consideration for the decision.

**Comment by ppamorim** [comment]
You could read the documentation and state that no personal data is shared with amplitude. State that Meilisearch is tracking users and its data is misleading.

Also the source code is open and you can verify each line of the project.

**Comment by curquiza** [comment]
@nicoduesing, we understand this behavior might involve a lack of trust for our users, we are sorry about this, and be sure we are working on this.

FYI, the data we collect is totally anonymized: we get if a MeilISearch instance is launched or not, which is the equivalent of the download metric for VLC. We also use Sentry to track the bugs.
In both cases, the metrics help us:
- build a better product by tracking the bugs
- keep the MeiliSearch project alive: we still need fundraising to live (cf [this article](https://blog.meilisearch.com/meili-fundraise/)) so we need to provide metrics to prove MeiliSearch is a great product used by a large number of people.

Again, we are working on this to find the best way between our need for metrics and the trust of our users! We'll keep you informed! Thanks for your feedback!
Hope you still enjoy using MeiliSearch!

**Comment by react-learner** [comment]
On the documentation side, we will also work to make this information more prominent and transparent. See https://github.com/meilisearch/documentation/issues/908

**Comment by nicoduesing** [comment]
@ppamorim I'm sorry, I didn't wanted to hurt you with my words. I really overreacted with the word "spy". I just was so surprised to see that telemetry sending. You are right, I can read the documentation and I can take a look into the code. And now I did. I didn't understood the code really because I am not that good in rust. 

But I have to look such things up. I didn't expected, that I have to do that. And maybe other users aren't, too. They maybe just leave and use some other tool? And that's the point I liked to make.

I think it is reasonable to expect, that open source software doesn't send such data without the user agreeing. Maybe imagine every open source project would just track the start of the software. You are starting a new server. So Ubuntu and a lot of it's components send a message, that they are started. You install and start nginx, so apt-get and nginx send a message that they are started. You install and start MeiliSearch and postgresql, so they send each a message of their start. You build a webpage with hugo, so it sends telemetry of the start. Additionally you are running a quasar app, that sends telemetry, ... The next day you restart the server for some reason. After Startup all the programs are sending telemetry. So you decide to look up the documentation of the 50 programs and find the deactivation for telemetry for each of them.

That is maybe not a fair comparison, but I hope it helps to make my point more understandable. All these projects could have the same good reasons to track the start of the software as you have. Maybe they are all sending data and I just never realized. But I don't think so. Although I understand what your reasons are, it still feels wrong that MeiliSearch is doing that.

**Comment by nicoduesing** [comment]
Thanks @curquiza. I appreciate, that you like to improve that point, that you are reacting so fast and that you take the time to understand my point and to respond with so much time and explanations. That really shows that this project is in good hands. I will try it out a bit more.

**Comment by curquiza** [comment]
For people following this issue:
- the new version of MeiliSearch (v0.21.0) will display a better message to inform the user about telemetry and how to disable it, which was not present in previous versions.
- here is the detail of our telemetry policy: https://github.com/meilisearch/specifications/blob/main/text/0034-telemetry-policies.md

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421

**Comment by curquiza** [comment]
Here is the PR in the docs giving all the detailed information about our telemetry: https://github.com/meilisearch/documentation/pull/1020
