### ISSUE TITLE
Incorrect search russian words with 'ь' letter

### ISSUE THREAD

**Issue by xtix** [meilisearch/MeiliSearch#1335]
If search query contains russian words with 'ь' letter, search and highlighting behaivor is incorrect.
![screen_1](https://user-images.githubusercontent.com/12378610/114541481-742f1180-9c5f-11eb-8655-7d1397060c32.png)
And scroll down you can see:
![sreen_2](https://user-images.githubusercontent.com/12378610/114541497-785b2f00-9c5f-11eb-90e6-adf8e6b31b64.png)
MeiliSearch seems to treat 'ь' letter as a separator.

**To Reproduce**
1. dataset: 
[movies-ru.zip](https://github.com/meilisearch/MeiliSearch/files/6303212/movies-ru.zip)

2. Search query: Альфа

**Expected behavior**
Same behavior as for words which do not contain 'ь' letter

**Comment by curquiza** [comment]
Hello @xtix!
Looks like this is an issue in our Tokenizer! Thanks for the report!
