### ISSUE TITLE
Error: SocketException: OS Error: Connection refused, errno = 111

### ISSUE THREAD

**Issue by madhavanswami** [meilisearch/MeiliSearch#1336]
when i am trying to post anything on meilisearch it is showing me the error:
 `Error: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 41200
`
this is my code in flutter: 
`http.post(
                Uri.parse('https://...aws_ec2_instance.../indexes'),
                body: json.encode({'uid': 'questions', 'primaryKey': 'id'}),
              );`

**Comment by curquiza** [comment]
Hello @madhavanswami!

It looks like your MeiliSearch is not accessible from your flutter code. Can you try this curl command in your terminal (not from your flutter code)?

```
curl -X GET http://localhost:7700/health
```

**Comment by sanders41** [comment]
If changing from `https` to `http` doesn't work are you using the Andriod emulator? If yes try `http://10.0.2.2` instead of `http://127.0.0.1`. More info on this [here](https://developer.android.com/studio/run/emulator-networking.html).

**Comment by madhavanswami** [comment]
> If changing from `https` to `http` doesn't work are you using the Andriod emulator? If yes try `http://10.0.2.2` instead of `http://127.0.0.1`. More info on this [here](https://developer.android.com/studio/run/emulator-networking.html).

tried both http as well as https but does not work. I've deployed meilisearch on aws and then am using it from a physical device. I also tried the official meilisearch package for flutter but then also facing the same issue. Please help me

**Comment by sanders41** [comment]
So your MeiliSearch you are testing against is running on AWS? If yes, you need to send the request to that address instead of to local host.

**Comment by madhavanswami** [comment]
> So your MeiliSearch you are testing against is running on AWS? If yes, you need to send the request to that address instead of to local host.

yes i am doing that only but the same error comes

**Comment by sanders41** [comment]
Do you have a firewall blocking on the AWS end?

**Comment by madhavanswami** [comment]
> Do you have a firewall blocking on the AWS end?

no

**Comment by curquiza** [comment]
I don't get it, is your MeiliSearch in your local machine?

If you get the error with the `curl` it means this is not a MeiliSearch error, but a connexion error -> you don't use the right address to reach the MeiliSearch server

**Comment by sanders41** [comment]
I suspect @curquiza is correct and the issue is in the address, but one more thing to check is if you gave the app permissions to access the internet in the manifest file? `<uses-permission android:name="android.permission.INTERNET" />`

**Comment by madhavanswami** [comment]
> I don't get it, is your MeiliSearch in your local machine?
> 
> If you get the error with the `curl` it means this is not a MeiliSearch error, but a connexion error -> you don't use the right address to reach the MeiliSearch server

Meilisearch is deployed on aws. The curl gives 200 ok.  I am using the adress of aws

**Comment by madhavanswami** [comment]
> I suspect @curquiza is correct and the issue is in the address, but one more thing to check is if you gave the app permissions to access the internet in the manifest file. `<uses-permission android:name="android.permission.INTERNET" />`

Yes I've done that

**Comment by sanders41** [comment]
Do you have a master key set in MeiliSearch? It looks like you aren't passing one in your request so maybe that is the issue?

**Comment by madhavanswami** [comment]
> Do you have a master key set in MeiliSearch? It looks like you aren't passing one in your request so maybe that is the issue?

Yes i am passing the master key. I've figured out that the problem i am facing is due to aws and not because of meilisearch.
Ive tried to make calls with postman and 

> connect ECONNREFUSED 13.58.11.255:443

this error it shows me eventhough passing the right master key.
