### ISSUE TITLE
Filters parameter can not be empty string

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1338]
**Describe the bug**

When trying to do a search with an empty string an error is thrown. The error message is also not really clear.

**To Reproduce**
1. Make a search
2. use `filters: ""` as a search parameter
3. paf 

```
Error [MeiliSearchApiError]: error parsing filter;  --> 1:1
  |
1 | 
  | ^---
  |
  = expected other

  type: 'MeiliSearchApiError',
  errorCode: 'invalid_filter',
  errorType: 'invalid_request_error',
  errorLink: 'https://docs.meilisearch.com/errors#invalid_filter',
  httpStatus: 400
```

**Expected behavior**
Ignore the empty filter as no filter is still a filter. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IOS
- meilisearch: v0.20

**Comment by curquiza** [comment]
Can you provide the test with curl please?

**Comment by bidoubiwa** [comment]
I cannot reproduce with curl! 
I guess it could be possible with some type of flag but intuitively I did not find how

```bash
curl -X GET 'http://localhost:7700/indexes/movie/search?q=sha?filters=""&limit=1' -i
HTTP/1.1 400 Bad Request
content-length: 0
connection: close
date: Thu, 15 Apr 2021 15:02:21 GMT
```

```bash
➜  ✗ curl -X GET 'http://localhost:7700/indexes/movie/search?q=sha?filters=&limit=1' -i
HTTP/1.1 200 OK
content-length: 112
content-type: application/json
date: Thu, 15 Apr 2021 15:02:44 GMT

{"hits":[],"offset":0,"limit":1,"nbHits":0,"exhaustiveNbHits":false,"processingTimeMs":1,"query":"sha?filters="}%
```

MeiliSearch version: 0.20.0

**Comment by bidoubiwa** [comment]
curl -X POST http://localhost:7700/indexes/movie/search --data '{ "q": "", "filters": "" }'

{"message":"Invalid JSON: expected value at line 1 column 1","errorCode":"bad_request","errorType":"invalid_request_error","errorLink":"https://docs.meilisearch.com/errors#bad_request"}curl: (6) Could not resolve host: q
curl: (6) Could not resolve host: ,
curl: (6) Could not resolve host: filters
curl: (3) URL using bad/illegal format or missing URL
curl: (3) unmatched close brace/bracket in URL position 1:
}’
 ^

**Comment by curquiza** [comment]
Checked with @gmourier
It put it as `good_first_issue`. The expected behavior: not return an error and do not apply any filter.
A test should be added.

**Comment by curquiza** [comment]
Fixed in v0.25.0rc0

Test:

- add:
```json
[
  { "id": 2,    "title": "Pride and Prejudice",                    "author": "Jane Austin",              "genre": "romance",    "price": 3.5 },
  { "id": 456,  "title": "Le Petit Prince",                        "author": "Antoine de Saint-Exupéry", "genre": "adventure" , "price": 10.0 },
  { "id": 1,    "title": "Alice In Wonderland",                    "author": "Lewis Carroll",            "genre": "fantasy",    "price": 25.99 },
  { "id": 1344, "title": "The Hobbit",                             "author": "J. R. R. Tolkien",         "genre": "fantasy" },
  { "id": 4,    "title": "Harry Potter and the Half-Blood Prince", "author": "J. K. Rowling",            "genre": "fantasy" },
  { "id": 42,   "title": "The Hitchhiker's Guide to the Galaxy",   "author": "Douglas Adams" }
]
```
- add filterable attributes
- search
```json
{
    "q": "",
    "filter": ""
}
```

**Comment by bidoubiwa** [comment]
An empty filter gives return no hits?

**Comment by curquiza** [comment]
Discussion about what we need to do here https://github.com/meilisearch/milli/pull/422
