### ISSUE TITLE
Policy for prefix search

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#134]
On a search with one or multiples word in the query. The user can choose if each word can be searched as a prefix or not.

I propose 3 possibilities:
- None => No Prefix, Never!
- Last => Consider that only the last word can be a prefix
- All => Consider that all words in the query can be a prefix

**Comment by brandom** [comment]
MeiliSearch would be a perfect fit for my project if this feature were implemented. Is this a tracking issue for a roadmap feature or just a suggestion at his time?

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/61-policy-for-prefix-search?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to update it on the roadmap.
