### ISSUE TITLE
Unable to upload any documents in meilisearch when deployed on aws and qovery

### ISSUE THREAD

**Issue by madhavanswami** [meilisearch/MeiliSearch#1345]
**Describe the bug**
When I am doing any operations on the local server everything works fine but when I am trying to do the same operations ie. Uploading documents, it does happen. I've tried it on aws as well as Qovery.

Everything else works just fine like creating index, getting keys, deleting index, except the functionality mentioned above.

**To Reproduce**
```
curl   -X POST 'https://hosted-site-url.qovery.io/indexes/movies/documents'   \
--data '[{
      "id": 287947,
      "title": "Shazam",
      "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
      "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
      "release_date": "2019-03-23"
  }]'
```
_output:_ 
> {"updateId":0}

**Exceptional behavior**
In the CLI everything seems fine but when I go and check the hosted site, there is no document.

**Desktop:**
 - OS: WINDOWS 10
 - Browser: CHROME

**Comment by MarinPostma** [comment]
Hey @madhavanswami !

What is the output of `curl   -X GET 'https://hosted-site-url.qovery.io/indexes/movies/updates/0' `?

**Comment by madhavanswami** [comment]
> Hey @madhavanswami !
> 
> What is the output of `curl -X GET 'https://hosted-site-url.qovery.io/indexes/movies/updates/0' `?

Thank you @MarinPostma. I got the answer. Actually the document id key was set to something different in the index and i was trying to upload document with some other document id.
Solved my error.
Thanks
