### ISSUE TITLE
[Docker] Provide an ARM image

### ISSUE THREAD

**Issue by voydz** [meilisearch/MeiliSearch#1347]
**Is your feature request related to a problem? Please describe.**
A current project of mine would require to run on a raspi. Would totally love if you guys provide an image for arm/arm64. If seen some community based ones but I prefer it more reliable. 

**Describe the solution you'd like**
A first look at the Dockerfile does not show any significant problems to pop up, when trying to [build images with buildx](https://docs.docker.com/engine/reference/commandline/buildx_build/#platform). Though I have no rust experience, but I am quite confident that it **might just work**.

**Describe alternatives you've considered**
Like mentioned above there are community provided images, at the cost of potentially introducing caveats like security issues and no maintenance.

**Additional context**
None I can think of right now. If you got some questions left, feel free to ask. :)

thanks for considering and best regards

**Comment by curquiza** [comment]
Hello, thanks for your suggestion.
Until we (or someone else) provide a docker image for raspi, you can download the ARMv8 binary we provide: https://github.com/meilisearch/MeiliSearch/releases

**Comment by voydz** [comment]
Hi @curquiza ,

thanks I already saw that and will absolutely try this.

FYI: Would consider to contribute this, if I end up using MeiliSearch in my projects. So if you guys accept PR's again a short ping would be appreciated. :) 

thank you for your great work with this

**Comment by curquiza** [comment]
For the moment we don't accept PR since we are working on a huge refacto (https://github.com/meilisearch/MeiliSearch#contributing), but once the v0.21.0 is out, we would reconsider this issue. We will keep you informed about what we'll decide to do :)

**Comment by curquiza** [comment]
Closed thanks to the ARMv8 image provided. Feel free to re-open if I miss understood something.

**Comment by mukul-mehta** [comment]
I needed an Arm64 image to run on a Raspberry Pi 4. Thanks to the Armv8 binary, I created a simple image that downloads the binary and runs it. It is available on [Docker Hub](https://hub.docker.com/r/metamehta/meilisearch-arm64)

**Comment by curquiza** [comment]
I updated the open issue about it :)
https://github.com/meilisearch/MeiliSearch/issues/1290
