### ISSUE TITLE
Policy for matching words

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#135]
On a search with one or multiples word in the query. The user can choose what happens if a word on a query is not present on the document or if the engine has not found enough documents. It's mean the possibility to make a query word optional or not.

I propose 4 possibilities:
- None => If a query word is missing the document is not considered
- Last Word => If we have no results we remove the last query word and try again
- First Word => If we have no result we remove the first query word and try again
- Optional => All words in a query are always optional, If one is missing the document is kept

**Comment by tagizaade** [comment]
Is there any progress toward this feature?

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/62-policy-for-matching-words?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to update it on the roadmap.
