### ISSUE TITLE
index limit

### ISSUE THREAD

**Issue by NatBLida68** [meilisearch/MeiliSearch#1350]
is there any option to increase limit of index which is set to 200 ?

i have more than  200 companies  each  having their own clients with same type data 
like company 1  with multiple branches -  have  customer / supplier etc tables  (on db 1 )
company 2 with multiple branches  - have same customer / suppliers.. etc tables (on db 2)
 
and i would like to use  each index to store each companies  data  

yes  may be i can  save all data in same index  by prefixing id with something   and search using filter company's id 

but i have  a large data associated  with each company   hard to mange in single index and i'm  also afraid it may affect performance  
if i can  create more than 200 index  i can split data and it will be simple and easy coding.
so can i ?

**Comment by curquiza** [comment]
Hello, we are currently on a new search engine that will remove this limit :) The max number of indexes will depend on the size of your disk 😉
I close this issue since it's a duplication of https://github.com/meilisearch/MeiliSearch/issues/1242
