### ISSUE TITLE
Doc outdated? Growing DB size on Windows now possible, since LMDB now uses native NT API?

### ISSUE THREAD

**Issue by Boscop** [meilisearch/MeiliSearch#1356]
(Bug is not the right category, it's more about the docs.)

I have a question about this:
<https://docs.meilisearch.com/reference/features/configuration.html#options>
> MEILI_MAX_MDB_SIZE: The maximum size, in bytes, of the main database. The main database stores the processed data.
> Depending on the OS, it is either the size that will be allocated on launch or the maximum size the database can attain.
> On Windows it is a fixed size that will be allocated on launch. Because this allocates 100GiB on MeiliSearch launch, a Windows user can use this option to decrease the size of the database.

Does this mean that it's impossible to start with a small db size and let it grow as needed on windows? (By setting `MEILI_MAX_MDB_SIZE` to a small value during init, and a higher value later.)
I'm asking because I'd like to include MeiliSearch with my application just like sqlite (because I need a faster fuzzy search). And allocating a 100 GB file right away shouldn't be done in this case. It should grow as needed.
Is that possible?

Regarding LMDB's limitations, I found this:
https://stackoverflow.com/questions/33508305/lmdb-maximum-size-of-the-database-for-windows#comment62219239_33571804
Which links to this (now fixed) ticket: https://bugs.openldap.org/show_bug.cgi?id=8324
Does MeiliSearch take advantage of this fix? If so, what's the right way to start with the smallest db file possible and grow it as needed (on windows)? :)

**Comment by MarinPostma** [comment]
Hey @Boscop !

We are aware of this fix, but it still hasn't been propagated to Meilisearch. Meilisearch depends on [Heed](https://crates.io/crates/heed) as a wrapper for LMDB and Heed itself depends on [mozilla bindings](https://crates.io/crates/lmdb-rkv-sys/0.8.2) to the c library, that are outdated. We have plans to roll out our own bindings to LMDB sooner or later, but until then this restriction is still present... Until then, on windows, the only thing you can do is grow the db size manually unfortunately.

**Comment by curquiza** [comment]
Hello @Boscop!

Marin explained it well!
More detail here if yo are interested: https://github.com/meilisearch/MeiliSearch/issues/851#issuecomment-820486885

**Comment by Boscop** [comment]
@MarinPostma Thanks! But what is a good size to start with, and how do I know when it's necessary to grow it?
And for growing it, should I just increase the value of that env var?

**Comment by MarinPostma** [comment]
@Boscop, a good size to start with will really depend on the amount of data you have, and your settings. I would go with whatever you can reasonably allocate, and see what's the size of your data using the `/stats` route. If the you see that you are using much less data that you allocated, then allocate a smaller db. You can also probably reduce the size of the update database (`--max-udb-size`) to something much lower, since you probably don't need that much space anyways.

Ultimately, if windows is your development environment, I suggest you run MeiliSearch in the WSL to avoid all those issue altogether.

**Comment by Boscop** [comment]
@MarinPostma Thanks! But it only works in WSL2, not WSL1, right?
And I plan to bundle meilisearch.exe with my application just like sqlite (because I need a faster fuzzy search) so it should be portable & standalone, not require WSL/docker..
If I insert too many documents into the db so that the allocated size is not enough, what kind of error would it return?

**Comment by MarinPostma** [comment]
I have never used WSL personally, so I can't give you an answer....

You will get an error like this one:
```
[
    {
        "status": "failed",
        "updateId": 0,
        "type": {
            "name": "DocumentsAddition",
            "number": 19547
        },
        "error": "heed error; MDB_MAP_FULL: Environment mapsize limit reached",
        "errorType": "internal_error",
        "errorCode": "internal",
        "errorLink": "https://docs.meilisearch.com/errors#internal",
        "duration": 0.043656761,
        "enqueuedAt": "2021-04-27T13:49:55.999377511Z",
        "processedAt": "2021-04-27T13:49:56.249900055Z"
    }
]
```

**Comment by MarinPostma** [comment]
(the actual error message is subject to change)

**Comment by irevoire** [comment]
Hello @Boscop, we [released a new version](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc0) of the search engine yesterday and we finally forked and updated LMDB.
We are now able to run our tests on windows :tada: 
If you are still following the project and try this new release please let us know if you encountered any issues.

**Comment by curquiza** [comment]
I close this issue then, feel free to re-open the issue if there are any issues @Boscop! And thanks again for your report!
