### ISSUE TITLE
Distinct attribute causes wrong number of documents in placeholder search

### ISSUE THREAD

**Issue by tillschander** [meilisearch/MeiliSearch#1359]
**Describe the bug**
- Setting a distinct attribute causes too few documents in a placeholder search.
- In a regular search with a distinct attribute set MeiliSearch usually returns as many results as the limit allows.
- In a placeholder search the number of results is affected by how many documents with the same distinct attribute were found. Say for example I have a dataset of products with a distinct attribute 'product_id'. If ten of those products have the same product_id only one will be in the results of a placeholder search and nine will be hidden from it. This leaves room for nineteen other products to reach a total of twenty products (default limit). But instead only ten other products will be included in the result as the hidden nine products count towards the limit.

**To Reproduce**
1. Import the example dataset [distinct_movies.csv](https://github.com/meilisearch/MeiliSearch/files/6406942/distinct_movies.csv)
2. Set 'product_id' as a distinct attribute
3. Open the dashboard
4. Only 11 instead of 20 movies are displayed
5. Search for e.g. 'a'
6. Now 20 movies are displayed

**Expected behavior**
Like in a regular search i expect the number of documents in a placeholder search to not be affected by duplicates from to a distinct attribute.

**Comment by curquiza** [comment]
Hello @tillschander! Thanks a lot for this bug report!
We are going to do our best to fix it in the next release!

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
