### ISSUE TITLE
Index language configuration

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#136]
If the user has a database with documents translated in multiples languages, the best use case is to create one index per language. In this case, it should be great to permit the end user to choose a default language for each index. This will apply the tokenizer and the default stop words for this language during the indexing. 

Of course, this option should be totally optional. By default, no stop word will be used. The tokenizer will split by space and use a default sentence separator like dots, coma, etc..

**Comment by qdequele** [comment]
closed in favor of #624

**Comment by pingiun** [comment]
Afaik this is not possible. Could this issue be reopened? I would be willing to work on adding a setting per index that sets the default language

**Comment by curquiza** [comment]
Hello @pingiun 

Here is the related discussion on our product repository, this is were you can see the track about the feature. You can add any information about your use case here: https://github.com/meilisearch/product/discussions/423
