### ISSUE TITLE
Demo in the README

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#1366]
Hello,

I would love to get a list of all the live running demo of Meilisearch directly in the README to give an opportunity to newcomers to try the end product before doing any setup or spending to understand how meili works.  
https://github.com/meilisearch/demos

**Comment by curquiza** [comment]
Isn't this issue part of the @meilisearch/devrel-team? Sorry it's an old one, just found out it still opens 😇

**Comment by ferdi05** [comment]
@irevoire so right now the [Demos repo](https://github.com/meilisearch/demos) has a good list of all our demos in its README.
@curquiza told me that you think that we should add to every relevant README?
I'd be happy to, but these readmes are quite long already? Maybe a link to the demos repo would be enough?

**Comment by curquiza** [comment]
demo-movies is not already published if I'm correct.
I think in any case we should redo the current README of Meilisearch. It's reallyyyyyy consulted, but maybe outdated regarding what we want to do in terms of communications.
I will open a dedicated issue for this.

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/awesome-meilisearch
