### ISSUE TITLE
Invalid JSON 

### ISSUE THREAD

**Issue by dgironella** [meilisearch/MeiliSearch#1369]
When I call a GET search all work correctly, but with POST I get a Invalid JSON: invalid number at line 1 column 2

Where is the problem?

**Comment by sanders41** [comment]
Are you using one of the clients or curl? Can you post an example of your JSON?

**Comment by dgironella** [comment]
I use meilisearch-php but I solved this, I send array var to q parameter.

**Comment by fr3fou** [comment]
![image](https://user-images.githubusercontent.com/1344906/122439634-7e91c280-cfa4-11eb-994f-f5c25707ffb5.png)

I seem to be getting a similar error with the provided JSON example

**Comment by CaroFG** [comment]
Hi @fr3fou your documents should be inside an array, even if it's just one like in [this example](https://docs.meilisearch.com/reference/api/documents.html#example-3) of the documentation

**Comment by fr3fou** [comment]
Thanks! I recommend updating the getting started docs in order not to confuse other people ^^
![image](https://user-images.githubusercontent.com/1344906/122443180-fdd4c580-cfa7-11eb-92e6-e7f9cc28417a.png)
(https://docs.meilisearch.com/learn/getting_started/quick_start.html#add-documents)

**Comment by curquiza** [comment]
I've opened https://github.com/meilisearch/documentation/pull/1000
