### ISSUE TITLE
Is there a way to put new document entries to show on top of search results?

### ISSUE THREAD

**Issue by ghost** [meilisearch/MeiliSearch#1376]
Everytime I add a document. in the website it always loads the oldest one I added. I'm making a search engine for posts on certain sites. and the oldest one becomes irrelevant very fast. how can I put new documents on top of the database to load new stuff first?

I've read the documents about relevancy and I didn't get any of it, but I think making old documents show up first wouldn't be great for that.

**Comment by irevoire** [comment]
I guess an easy solution would be to add a field with the date of your document and then add the criterion `desc(date)` at the end of your [ranking rules](https://docs.meilisearch.com/reference/api/ranking_rules.html#update-ranking-rules)

**Comment by gwynne0190** [comment]
There is a "generated attribute ranking order" available. it should be possible to do it without adding a field date. I'm dealing with information getting submitted into meilisearch every single minute. I can't update this by hand.

>By default, the attribute ranking order is generated automatically based on the attributes' order of appearance in the indexed documents. However, it can also be set manually.

source; https://docs.meilisearch.com/learn/core_concepts/relevancy.html#attribute-ranking-order

This doesn't say what the attribute string name is. I'm trying to set the rules settings to `desc(generated_ranking_order)` (?)
can anyone tell me what it is?

**Comment by curquiza** [comment]
The link you point out in the docs is not related to the custom ranking rules (asc/desc). It's linked to searchable attributes, and it is not necessary for what you ask for 🙂

`desc(generated_ranking_order)` indicates the documents with the highest `generated_ranking_order` will appear first.
`generated_ranking_order` needs to be an int.

**Comment by gmourier** [comment]
I'm closing this issue. The answers given seem to answer the initial problem of the user who no longer exists.
