### ISSUE TITLE
Crash when indexing

### ISSUE THREAD

**Issue by NatBLida68** [meilisearch/meilisearch#1382]
maybe this is not a issue with meili but if anyone know please assist
502 bad gateway on opening  melisearch in browser   so i cant perform search in my project
using DigitalOcean droplet
after restarting droplet it shows melisearch is running but if i perform a search or retrieve index  it works for a little time and goes to 502   also   $client->getAllIndexes(), $client->deleteAllIndexes()  is not working even when search is working idk why but  $client->getIndex('demo') works so no big deal for me

**Comment by sanders41** [comment]
This may not be related, but I have had this issue before with MySQL when the droplet ran out of RAM and that crashed the database. The droplet was still running, but MySQL was not because it crashed. Is it possible that your droplet ran out of RAM and MeiliSearch crashed?

**Comment by NatBLida68** [comment]
@sanders41  yes it was due to  RAM ,  still wondering why such a small data set  consumes   4GB RAM. 
i can import all my data but cant perform a update,delete operation on single data that time it crashes hope it will be fix in upcoming updates.

**Comment by curquiza** [comment]
Hello @NatBLida68
- what is the size of your machine (RAM)?
- what is the size of your dataset?

**Comment by NatBLida68** [comment]
Using DigitalOcean $20/month (4GB- 80GB-4TB) plan 
Formally used  on single index 26 tables around 50k in 4-5 tables  and less than 10k in others .
Now using single index single table around  max 100k documents. 5 columns other than id   and not a single column exceeds 10 characters  most of them below 6 char.  Size of data set ? Idk much in technical since Im just using a droplet.   Correct me if I'm wrong  in the case of RAM   normally  if we use  an application it consumes  mem but in my case  I can see 100% usage in midnight  in which I wasn't even using any search, updates or deletes.  And one more question why  getAllIndex() is not working but getIndex("demo") is working

**Comment by curquiza** [comment]
>  Formally used on single index 26 tables around 50k in 4-5 tables and less than 10k in others .

how many documents is it? How does a document look like? (number of fields and are there a lot of char in each field?)

> Now using single index single table around max 100k documents. 5 columns other than id and not a single column exceeds 10 characters most of them below 6 char.

Is it what you use now? Do you still have issues (crash?) with this?

**Comment by sanders41** [comment]
`getIndex("demo")` looks like you are using meilisearch-js? If so it is `listIndexes()` to get all indexes.

**Comment by curquiza** [comment]
>  And one more question why getAllIndex() is not working but getIndex("demo") is working

What do you mean by "is not working"? Can you send us the error message if you have one?

**Comment by NatBLida68** [comment]
> > Formally used on single index 26 tables around 50k in 4-5 tables and less than 10k in others .
> 
> how many documents is it? How does a document look like? (number of fields and are there a lot of char in each field?)
> 
> > Now using single index single table around max 100k documents. 5 columns other than id and not a single column exceeds 10 characters most of them below 6 char.
> 
> Is it what you use now? Do you still have issues (crash?) on your 4Gb RAM droplet?

Yes I'm having same issue  sample data set will look like this
 `id
c1
base_id
1
row_no
CS210001
model_code
4
company_id
1
user_id
3
posting_date
19-04-2021`

**Comment by NatBLida68** [comment]
> `getIndex("demo")` looks like you are using meilisearch-js? If so it is `listIndexes()` to get all indexes.

No using meilisearch-php

**Comment by NatBLida68** [comment]
> > And one more question why getAllIndex() is not working but getIndex("demo") is working
> 
> What do you mean by "is not working"? Can you send us the error message if you have one?

![IMG-20210623-WA0017](https://user-images.githubusercontent.com/55424433/123108525-1f2a2b80-d458-11eb-90cd-997253757cae.jpg)

**Comment by curquiza** [comment]
It's weird, we succeeded to push and manipulate more than 500k documents in a 4GB RAM droplet. Weird you can't.

How are your documents? Are there a lot of words in each attribute?

Have you tried to have a bigger droplet with a bigger RAM to see if it fixes your issue?

**Comment by NatBLida68** [comment]
> It's weird, we succeeded to push and manipulate more than 500k documents in a 4GB RAM droplet. Weird you can't.
> 
> How are your documents? Are there a lot of words in each attribute?
> 
> Have you tried to have a bigger droplet with a bigger RAM to see if it fixes your issue?

Yes I was also able to index (import) more than .3 million on this index but  I was not able to perform  a search operation when I do it goes 100% spike and  502   then I tried on single table with 55- 90k data (don't know exact since it's production table )

**Comment by NatBLida68** [comment]
Idk much about this but currently I'm just freezed this updates and waiting for v 0.21  and will start from scratch

**Comment by sanders41** [comment]
I think the error happens [here](https://github.com/meilisearch/MeiliSearch/blob/94c0858c276743e8b2f4c8c97880070a198341bf/meilisearch-http/src/routes/index.rs#L52-L54). @curquiza I think this means there is an issue with the index itself? I'm not sure of a way to get more information on the error.

**Comment by curquiza** [comment]
This an unexpected error, will see if the v0.21 fixes this. I let the issue opened then

**Comment by curquiza** [comment]
Hello @NatBLida68, and everyone following the issue!

The [first RC of MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc0) is out.
We did our best to fix indexation and crash issues. We succeeded to improve it, but not to totally fix them.

We will still improve this after the release of the v0.21.0. We would rather release a non-completely optimized version rather than delay it and, at the same time, delay the release of new features. Be sure we are doing our best to always improve this indexation issues.

As a reminder:
* despite the improvements, we always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and can be optionally increased. It means most of the dataset can be pushed with one call to the API.
* If you still have a memory crash, it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.

Thanks for your patience and your help! ❤️

**Comment by curquiza** [comment]
Hello everyone reading this issue.

I close this issue due to the lack of feedback since it was happening with an old version of Meilisearch.

However, for anyone having issues in general with indexation performance, like this issue, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂
