### ISSUE TITLE
Running MeiliSearch on cluster

### ISSUE THREAD

**Issue by shashank-sachan** [meilisearch/MeiliSearch#1383]
Hi,

Is it possible to run MeiliSearch in cluster. Eg. If I have 2 separate server where I'm running the MeiliSearch lib and both are pointing to same data volume.

**Comment by MarinPostma** [comment]
Hello @shashank-sachan,  this is not something that has been done before, and it is probably not a good idea to open the same meilisearch DB with two processes. Maybe it will work, maybe it will not, maybe you will encounter weird race conditions when writing... We can't really help you on this one unfortunately. We will soon start working on high availability, this will maybe fit your usecase once it's shipped.

**Comment by shashank-sachan** [comment]
Thanks @MarinPostma. Is there any load test report or benchmark where we can see how many request can single node handle for given memory and cpu ?

Also just a thought, if we write into ms db from single server but read it from multiple server will that help in scaling? I'm not sure if anyone explorered it.

**Comment by curquiza** [comment]
checked with @gmourier, we are starting to explore the HA, and once this feature is out you should be able to use MeiliSearch in a cluster

**Comment by samatzhusup** [comment]
@curquiza Hi! any update about HA?

**Comment by curquiza** [comment]
Hello @samatzhusup!

You will find more information here: https://github.com/meilisearch/product/issues/49

We plan to work on this next year.

**Comment by vl-kp** [comment]
any update?

**Comment by oluademola** [comment]
Hello @vl-kp,

This is currently in the works, and we have released the first iteration prototype, which is provided [here](https://github.com/meilisearch/meilisearch/pull/3593). Feel free to test it and do not hesitate to share your feedback with us. You can find the dedicated discussion for this feature in this [product discussion](https://github.com/meilisearch/product/discussions/617), and you're welcome to have a chat about it also on this [discord channel](https://discord.com/channels/1006923006964154428/1075374699774742618).

Thanks.
