### ISSUE TITLE
Misplaced highlights when used together with values cropping

### ISSUE THREAD

**Issue by mirorac** [meilisearch/MeiliSearch#1395]
**Describe the bug**
When using search parameters `attributesToHighlight` and `attributesToCrop`, the highlights are occasionally misplaced. Looks like the highlighted chunk of text is of right length but is shifted by several characters. This behavior does not occur in all search hits. Some matches are highlighted as expected and some are not. I was not able to find a pattern in the contents what could make this issue happen. I tried different `cropLength` values with no effect on the issue.

**To Reproduce**
1. Set `attributesToHighlight`, `attributesToCrop` and `cropLength` search parameters
2. See (misplaced) highlights
3. Repeat the query without `attributesToCrop` and `cropLength` parameters
4. See highlighted matches as expected

**Expected behavior**
I expect the highlights be placed in the same position as are placed when cropping is not used.

**Screenshots**
The following code
```python
get_index().search('prickely people', { 
    'limit': 100,
    'attributesToRetrieve': ['title', 'source_url'],
    'attributesToHighlight': ['content'],
    'attributesToCrop': ['content'],
    'cropLength': 150
})
```
produces unexpected behavior:
```html
...the prickl<em>y peopl</em>e<em> are a</em>dvocates of intellectual porcupinism...
```

Whereas omitting parameters for cropping
```python
get_index().search('prickely people', { 
    'limit': 100,
    'attributesToRetrieve': ['title', 'source_url'],
    'attributesToHighlight': ['content'],
    # 'attributesToCrop': ['content'],
    # 'cropLength': 150
})
```
produces expected behavior:
```html
...the <em>prickly</em> <em>people</em> are advocates of intellectual porcupinism...
```
^ please note that I have truncated the example outputs  manually to make the issue easier to notice (denoted with ellipses)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4 (18E226)
 - Environment: Python client `meilisearch==0.14.2`
 - Meilisearch version: `{'commitSha': 'UNKNOWN',
 'buildDate': '2021-02-09T15:29:47.254723645+00:00',
 'pkgVersion': '0.19.0'}`

**Comment by curquiza** [comment]
Hello @mirorac!

I'm trying to reproduce your bug, can you send us the whole document please? 🙂 I cannot perfectly reproduce it without it. It would be really helpful

**Comment by qdequele** [comment]
Hello, this issue is related to version 0.19 of MeiliSearch. It seems that it does not appear anymore in the new versions. So I will close this issue. 

However, there are still some highlight problems introduced with version 0.21. These are described in issue #1480. 

In case you manage to reproduce this bug in version 0.21, please reopen this issue.
