### ISSUE TITLE
Clear update queue?

### ISSUE THREAD

**Issue by hsleewis** [meilisearch/MeiliSearch#1396]
Hi,

Is there a way to clear the update queue and start over? I currently have over 22M queued updates and I can't find a way to clear the queue.

Thanks!

**Comment by curquiza** [comment]
Hello, thanks for your feedback! There is no way currently to stop the updates at the moment. We are thinking about implementing this feature.

**Comment by hsleewis** [comment]
Thanks for your reply. The queue is stuck, restarting the service and server doesn't make a difference unfortunately, is the only solution reinstalling meilisearch?

**Comment by curquiza** [comment]
>  I currently have over 22M queued updates

Do you push documents one by one? You should push document by batch, the add-or-replace-documents routes allow to push multiple documents at the same time and improve performance 🙂 
However, I want to warn you, MeiliSearch is not designed to handle this huge amount of documents, depending on the RAM of your machine it might be complicated (or really long) to add your whole dataset.
The core team is currently working on a new search engine to handle this kind of huge dataset, we'll keep you informed when this release is out.

If you really want to stop all the processes, you need to stop MeiliSearch and remove `data.ms` (the database) but you will lose all your information in MeiliSearch 😕

**Comment by hsleewis** [comment]
Thanks for the replies! 

> Do you push documents one by one? You should push document by batch, the add-or-replace-documents routes allow to push multiple documents at the same time and improve performance 🙂

I currently push in batches of 5000 documents, the documents are relatively small, they contain an ID, SKU and a Title

> The core team is currently working on a new search engine to handle this kind of huge dataset, we'll keep you informed when this release is out.

That sounds awesome, can you please update this issue when there is an update for that?

I redeployed the Meili server and started over, trying to just implement it for the customers that where having issues to keep the amount of documents small. If that doesn't work I'm going to go a different route until the new engine is ready for production :)

**Comment by curquiza** [comment]
> That sounds awesome, can you please update this issue when there is an update for that?

Hum, since there are more than 100 issues I might forget to keep this one up to date. Please follow the release of this repository, we will release a RC version by the end of June 🙂

Thanks for testing MeiliSearch and giving your feedback!

**Comment by hsleewis** [comment]
Thanks! I'll close it!
