### ISSUE TITLE
Meilisearch on ARM platform consume 1GB ram by default

### ISSUE THREAD

**Issue by kappa-wingman** [meilisearch/MeiliSearch#1411]
Version 0.20.0
Since I can't run the provided binary on RHEL 8 based on ARM aarch64 platform. I compile it.
It could run but it consumed 1GB ram while it has very few data.
Previously I run the same data on x86 platform and the memory usage is low.

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   6496 meilise+  20   0  201.1g   1.0g  18880 S   0.0  18.6   0:00.12 meilisearch
```

**Comment by kappa-wingman** [comment]
pmap on it and found this
```
0000aaac3e070000  41792K r-x-- /usr/local/bin/meilisearch-0.20
0000aaac40940000   1600K r---- /usr/local/bin/meilisearch-0.20
0000aaac40ad0000     64K rw--- /usr/local/bin/meilisearch-0.20
0000aaac40ae0000    576K rw---   [ anon ]
0000ffcc00000000 104857600K r--s- /var/lib/meilisearch/database/update/data.mdb
0000ffe500000000 104857600K r--s- /var/lib/meilisearch/database/main/data.mdb
0000fffe00000000 1048576K rw---   [ anon ]
0000fffe417d0000     64K -----   [ anon ]
```

**Comment by curquiza** [comment]
Hello @kappa-wingman!
thanks for your report, can you test the same with this repo: https://github.com/meilisearch/transplant/
This repo is what we are going to release in the v0.21.0, it would help if you tell us if this issue is still present here,

**Comment by kappa-wingman** [comment]
I am running the v0.21.0 alpha, the memory usage goes down to about 580MB.

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  39481 meilise+  20   0  112.1g 580160  32576 S   0.0  10.1   0:06.45 /usr/local/bin/meilisearch --db-path /var/lib+
```

I think it still use a bit too much ram, the total data of meilisearch on the disk is about 34MB
```
22M     indexes
160K    index_uuids
9.6M    main
1.8M    update
544K    updates
4.0K    VERSION
```

**Comment by curquiza** [comment]
>  It could run but it consumed 1GB ram while it has very few data.
I should ask first, but what is few data for you?

**Comment by kappa-wingman** [comment]
The Meilisearch indexed a small web site. After that, Meilisearch only used about 34MB on disk, as you can see in my last message. That is not a lot of data.

I had compared with the memory usage of Meiliserach on a X86_64 platform with the same data, the memory usage is about 62MB.

**Comment by curquiza** [comment]
Hello, we know about this big RAM consumption, we are doing our best, and of course, we are improving it in a near future.

**Comment by kappa-wingman** [comment]
I tested a complied 0.21rc0 version of Meilisearch on ARMv8 (RHEL based). The memory consumption reduced to normal now.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  90058 meilise+  20   0  101.3g  11456   6784 S   0.0   0.2   0:00.00 meilisearch
```

**Comment by curquiza** [comment]
Awesome!! I forgot to tell you the new rc0 was out! My bad!
Fixed by https://github.com/meilisearch/MeiliSearch/pull/1421 then! 🎉
