### ISSUE TITLE
How to use with windows?

### ISSUE THREAD

**Issue by arjunkapoor19** [meilisearch/MeiliSearch#1418]
I want to integrate meili in my website, but I am on a windows machine, what do I do?

**Comment by Kerollmops** [comment]
Hey,

We have a windows binary in [our latest release](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.20.0) that you can easily run.

Note that you will surely need to change the maximum disk space that the database use, you can read about the max MDB and max UDB size parameters [on the documentation](https://docs.meilisearch.com/reference/features/configuration.html#max-mdb-size).

**Comment by curquiza** [comment]
Closing this issue then :) Feel free to re-open if you have any question

**Comment by AndryHTC** [comment]
Hello,

I've been exploring the use of Meilisearch on a Windows Server and I'm interested in ensuring the Meilisearch binary starts automatically whenever the server boots up. Could anyone guide me on how to achieve this?

Additionally, if there are alternative approaches to keep the service continuously running (e.g. using a process manager or scheduling tool), I'd be very interested in learning about them as well. Any recommendations or best practices would be greatly appreciated!

Thank you in advance for your support.

**Comment by gillian-meilisearch** [comment]
Hi @AndryHTC - it might be worth opening this up as a Q&A discussion topic to gather some more visibility & community input? You can [do that here](https://github.com/meilisearch/meilisearch/discussions/categories/q-a) if you wish. I've had a quick look for previous discussions that could be helpful and came across this one if that's helpful at all? https://github.com/meilisearch/meilisearch/discussions/3253
