### ISSUE TITLE
This is slow to insert news data with text content

### ISSUE THREAD

**Issue by dusukang-cjj** [meilisearch/MeiliSearch#1420]
Hello, my scene is based on the search of news articles. I deployed meilisearch on the node of a single machine. Then let it batch import 1 million news data with body content, and the batch quantity of each import is 1000. It took about 24 hours to successfully insert more than 200000 data, about 10000 data per hour. Later, the batch import data volume was changed to 100, and the insertion speed was similar to 1000 per batch. I want to know if it's the wrong way to insert,The JSON format of each news data is as follows:
<img width="884" alt="my_iss" src="https://user-images.githubusercontent.com/78578876/123573262-33777b00-d800-11eb-8535-b7c8e2056f9d.png">

**Comment by curquiza** [comment]
Hello @dusukang-cjj!

Thanks for sharing your feedback!

Each document does not look really big, you should push more than 1000 documents per batch. Indeed, MeiliSearch default payload size limit is 100Mb which is really large! You can index thousands and thousands of documents with one HTTP call. Plus, you can increase this payload size. https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size

We succeeded to index 5 millions of small documents in few hours (between 1 and 4h depending on the machine's RAM)

**Comment by dusukang-cjj** [comment]
Thank you for your answer.

But what I want to express is that when I insert 400000 news data with body, it will be faster to batch insert documents into meilisearch, and the insertion request will be completed in a very short time. It's just that the asynchronous indexing of data will be a bit slow later. At the beginning, the index building speed was relatively fast, about 30000 in an hour. At present, there are about 60000 news data still in indexing state, and more than 33W documents can be searched.
![1625139722117_857E94C4-734E-41B9-8917-9AF12BEC5359](https://user-images.githubusercontent.com/78578876/124119978-c7b63c00-daa5-11eb-83cf-e717c4883edf.png)
![2](https://user-images.githubusercontent.com/78578876/124119191-c6d0da80-daa4-11eb-84d2-2131ffda915a.png)

When I started meilisearch, I did set the HTTP payload size limit parameter to about 8g, and the number of documents inserted in each batch was 1000.
![with_content](https://user-images.githubusercontent.com/78578876/124118362-d26fd180-daa3-11eb-83fd-d9a506769130.png)

I looked at the data directory mounted when docker deployed meilisearch, and saw that the disk storage currently occupied is about 18g
![1625141115685_404B8374-9F6C-4200-AD0C-6A3344C0C862](https://user-images.githubusercontent.com/78578876/124121875-02b96f00-daa8-11eb-8d3c-4dc4dcb49fce.png)

When I imported the news document, I did not bring the body content, that is, there was no data in the "content" field. I successfully inserted 192W data and built the index. I checked the disk storage occupation, which took about 19g
![4](https://user-images.githubusercontent.com/78578876/124122665-f255c400-daa8-11eb-93f7-db89b087480b.png)
![5](https://user-images.githubusercontent.com/78578876/124122676-f4b81e00-daa8-11eb-9fc9-f3412327392e.png)

The memory of my test machine is as follows:
![6](https://user-images.githubusercontent.com/78578876/124122937-3cd74080-daa9-11eb-9369-12b9e72434ca.png)

What other parameters can I set or how can I improve my indexing speed? I look forward to your suggestions.

**Comment by curquiza** [comment]
I'm not sure to understand all the steps you did. Can you send us the datasets?

**Comment by dusukang-cjj** [comment]
How many datasets do you need? I poured out about 20000 news datasets in JSON format.
[meiliSearchData.json.zip](https://github.com/meilisearch/MeiliSearch/files/6753277/meiliSearchData.json.zip)

**Comment by piaoger** [comment]
You can also try the Chinese version of movies.json in PR [PR](https://github.com/meilisearch/MeiliSearch/pull/1227/commits/5626aafaa45d61221f26d397cf2f5038bd0b7922) though it is refused. 

@dusukang-cjj

**Comment by dusukang-cjj** [comment]
Thank you. I have tested the data of movies.json, and the effect is pretty good. But it's a bit slow to test the news data in our business.
@piaoger

**Comment by dusukang-cjj** [comment]
How many news datasets do I need to provide? We want to use meilisearch in our search business. Thank you very much for helping us test our datasets.
@curquiza

**Comment by gmourier** [comment]
Hello @dusukang-cjj!

We are aware of the limitations you encounter when indexing. That's why version 0.21 improves the memory consumption during indexing and allows to index larger volumes of data. 

We will still work on the indexing speed for version 0.22 because we have some ideas for improvement and we think we can do better.

What takes time in indexing is the calculation of proximity criteria on long texts. You can try to index your documents with the 0.21 release candidate, the memory consumption should be much more frugal.

Instead of feeding in a number of lines, try to make 100MB file batch. This way, we managed to index 5 Million documents (with really short text) in 20 minutes.

Hope it helps ✌️

**Comment by dusukang-cjj** [comment]
@gmourier 
Oh, thank you.That's great.
