### ISSUE TITLE
Locking commit during snapshot dumps

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/meilisearch#1439]
@kerollmops suggested that we could lock only the commit phase during the snapshot/dumps process, so I have decided to give it a quick thought.

Currently, when we want to perform a snapshot, we need to acquire a lock on the update store to prevent any update to be processed while we are performing a snapshot. After we acquire the lock, we perform a snapshot of the update store, and, while still holding the lock, a snapshot of all the indexes. For each index, we also try to get a write lock to perform the snapshot, to ensure that any ongoing update is done before we start snapshotting the index. The goal of this process is to make sure that no data is lost between the moment we start snapshotting and the moment the snapshot finishes.

## Locking on commit

Conceptually, since heed is transactional, the only thing we need to synchronize are when each database *commits*. Since most of the update time takes place duting the indexations, we don't actually need to hold a lock during the whole process. Below is a diagram showing the locking process:

```
        UPDATE STORE                                  INDEX
   ┌────────────────────┐             ┌─────────────────────────────────────┐
   │  reads the first   ├─────────────►  acquire a write lock to the index, │
   │       update       │             │       and start processing          │
   └────────────────────┘             │            the update               │
                                      └─────────────────┬───────────────────┘
                                                        │
                                                        │
                                                        │
                                                        │
  ┌─────────────────────┐                   ┌───────────▼─────────────┐
  │ acquire write lock  ◄───────────────────┤request commit permission│
  │ on the update store │                   │       (pre-commit)      │
  └──────────┬──────────┘                   └─────────────────────────┘
             │
             │
┌────────────▼────────────┐                      ┌───────────────┐
│ grant commit permission ├──────────────────────► commit update │
└─────────────────────────┘                      └──────┬────────┘
                                                        │
                                                        │
   ┌─────────────────────┐               ┌──────────────▼────────────────┐
   │ change update state ◄───────────────┤ return result to update store │
   │      and commit     │               └───────────────────────────────┘
   └─────────────────────┘
```

When performing a snapshot or a dump, the thread acquire a write lock on the update store, two cases:
- No other thread currently hold a write lock to the update store, the lock is acquired right away and the thread can perform the snapshot of the update store, and then of the indexes. The only difference is that the snapshot of the indexes must be performed with a read lock instead of a write lock, since an updating thread could be waiting with a write lock for a permission to commit. If an update was ongoing, when it reached the state where the update store need to acquire the write lock to allow the index to commit, it will have to wait that the snapshotting thread is done with it's transaction before it can make progress.
- A lock is currently held: the snapshotting thread will have to wait: either someone is committing an update, or someone is performing a snapshot, so it is not safe to snapshot now.

## Synchronization

tbd

**Comment by curquiza** [comment]
Discussed with @MarinPostma, not relevant anymore since we have changed the behavior of dumps.
