### ISSUE TITLE
Control the maximum number of words indexed

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#146]
Currently the indexer does is not limited to index a certain amount of words. This could produce enormous updates and make the DocIndex index growth fast.

We must also make sure that a word index does not wrap when [converting from an `usize` into an `u16`](https://github.com/meilisearch/MeiliDB/blob/3056b351fa6aba9f45ba23bde438b7a94fe51de0/src/database/serde/indexer_serializer.rs#L80), we could use the `TryInto` trait.

The indexer must be separated from the serializer to make things more modular and configurable.

**Comment by qdequele** [comment]
This is no more relevant, we close it, feel free to comment here or open a new issue. 

The future version of MeiliSearch will be limited to 1000 words per fields.
