### ISSUE TITLE
Can't install via cURL due to tracking analytics being blocked

### ISSUE THREAD

**Issue by lkhrs** [meilisearch/MeiliSearch#1466]
**Describe the bug**
When installing meilisearch via cURL, installation hangs due to Amplitude tracking analytics being blocked at the DNS level.

[2021-07-02T20:41:27Z ERROR meilisearch::analytics] Unsuccessful call to Amplitude: https://api.amplitude.com/httpapi: Connection Failed: Connect error: Connection refused (os error 61)

**To Reproduce**
1. Block Amplitude
2. Install meilisearch via cURL
3. See error

**Expected behavior**
Tracking and analytics calls should **not** be included in an install script.

There's other ways of tracking installs without using invasive analytics. Your server logs can and most likely are already recording requests to install.meilisearch.com.

Would the team consider removing analytics from the install script?

**Comment by lkhrs** [comment]
It appears Meili Search also makes a call to Amplitude when launched - not sure if this is one and the same. I installed it successfully via HomeBrew but got the same error when launched.

**Comment by MarinPostma** [comment]
Hey @lkhrs, you can launch MeiliSearch with the `--no-analytics` to disable the analytics. You can refer to the [doc](for more infos). Hope that addresses your issue :)

**Comment by curquiza** [comment]
I close this issue since the answer has been given!
Feel free to re-open if it's not :)
