### ISSUE TITLE
Unexpected behavior when no valid inferable primary key is provided

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1487]
**Describe the bug**
When I add documents holding no inferable primry key, on a index that does not exist (lazy index creation),  no error is thrown the index is created the primary key is still null and no documents are stored.

**To Reproduce**

Javascript test sample: 
```js
const { updateId } = await client.index("movies").addDocuments([
      {
        unique: 2,
        title: 'Le Rouge et le Noir',
      },
    ])
    await client.index("movies").waitForPendingUpdate(updateId)
    const index = await client.index("movies").fetchInfo()
    console.log({ index })
    const documents = await client.index(indexNoPk.uid).getDocuments()
    console.log(documents)
```
1. Create index using lazy Index with for example this document
```json
{
"title": "Hello"
}
```
2.  Task is completed
3. Index exists, uid does not exists on index
4. get documents
5. No documents exists on the index

**Expected behaviour**
An error thrown or documents stored

**MeiliSearch Version**: 
v0.21.0rc1

**Comment by MarinPostma** [comment]
@bidoubiwa, an error is thrown asynchronously:

```
[
    {
        "status": "failed",
        "updateId": 0,
        "type": {
            "name": "DocumentsAddition"
        },
        "message": "missing primary key",
        "errorCode": "missing_primary_key",
        "errorType": "invalid_request_error",
        "errorLink": "https://docs.meilisearch.com/errors#missing_primary_key",
        "duration": 0.071,
        "enqueuedAt": "2021-07-07T08:42:16.683783950Z",
        "processedAt": "2021-07-07T08:42:16.757691196Z"
    }
]
```

**Comment by bidoubiwa** [comment]
Ah yes, instead of synchronously in the current version? The PR can be closed

**Comment by MarinPostma** [comment]
Yeah, but in the current version, it was not correct to do so : synchronously setting the primary key and then performing the addition could lead to race conditions.
