### ISSUE TITLE
Synonym Updates do not work if Index has just been created

### ISSUE THREAD

**Issue by spuy767** [meilisearch/MeiliSearch#1493]
Synonym Update doesn't work if the search index has just been created.

1) Create new index and insert documents
2) Immediately update synonyms (synonyms do not work)
3) Wait until index returns search results
4) Update synonyms again with identical call to the first
5) Synonyms are Working

I would expect that even if I create synonyms at the same time I insert documents into the index, they would function.

 - OS: debian
 - Version: 0.20.0

**Comment by qdequele** [comment]
Hello @spuy767, I tried to reproduce your bug with one of our datasets. Unfortunately, I was not able to reproduce the problem. Can you send us an example that would work?

**Comment by curquiza** [comment]
Impossible to reproduce at the moment. Closing due to lack of answer after more than a month, feel free to re-open!
