### ISSUE TITLE
v0.21 filterableAttributes including distinctAttribute in addition to values set

### ISSUE THREAD

**Issue by sanders41** [meilisearch/MeiliSearch#1497]
**Describe the bug**
When both `filterableAttributes` and a `distinctAttribute` are set the `distinctAttribute` is being included in the `filterableAttributes`. In v0.20 the equivalent for `filterableAttributes` was `attributesForFaceting`, and when setting this the `distinctAttribute` was not included.

**To Reproduce**
Run the following curl command:

```sh
curl -X POST 'http://localhost:7700/indexes/movies/settings' --data '{"filterableAttributes": ["year", "genre"], "distinctAttribute": "movie_id"}
```

With this `filterableAttributes` includes the `distinceAttribute` in addition to the values set:

```json
{
  "displayedAttributes": ["*"],
  "searchableAttributes":["*"],
  "filterableAttributes": ["genre","year","movie_id"],
  "rankingRules": ["words","typo","proximity","attribute","exactness"],
  "stopWords": [],
  "synonyms": {},
  "distinctAttribute": "movie_id"
}
```

**Expected behavior**
I didn't expect `filterableAttributes` to include `movie_id`

**MeiliSearch version:** [e.g. v0.20.0]
v0.21.0rc2

**Additional context**
Running the equivalent in v0.20.0 does not include the `distinctAttribute`

```sh
curl -X POST 'http://localhost:7700/indexes/movies/settings' --data '{"attributesForFaceting": ["year", "genre"], "distinctAttribute": "movie_id"}'
```
results in:

```json
{
  "rankingRules": ["typo","words","proximity","attribute","wordsPosition","exactness"],
  "distinctAttribute": "movie_id",
  "searchableAttributes":["*"],
  "displayedAttributes":["*"],
  "stopWords":[],
  "synonyms":{},
  "attributesForFaceting":["year","genre"]
}
```

**Comment by gmourier** [comment]
Hi @sanders41! Nice spot! 👍

Indeed, the `distinctAttribute` should not appear  in the list of `filterableAttributes` and be usable as until it has been specified. Technically we have to create a specific data structure for the `distinctAttribute` that makes it filterable. 

You can find more information on the related specification https://github.com/meilisearch/specifications/pull/32/files. Line 188 - 192.
