### ISSUE TITLE
No effect of $client->index()->updateSettings() when running on docker windows.

### ISSUE THREAD

**Issue by saadj55** [meilisearch/MeiliSearch#1525]
**Describe the bug**

When running on windows using docker, if I added my documents and then call `updateSettings` from the PHP sdk or the REST api routes, the settings don't seem to change at all. And vice versa if I call update settings on a given index before adding documents it works but when I try to add documents, it doesn't seems to work at all and shows 0 documents. Keep in my mind I have mapped a local windows directory to my docker image via volumes.

**To Reproduce**
1. Install through docker
2. Add documents 
3. Update settings for a given index
4. Check settings via GET route /settings

**Expected behavior**
It should have updated the settings for the given index

**Screenshots**

**MeiliSearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
Using docker on windows,

**Comment by gmourier** [comment]
Hello @saadj55!

Can you share a sample of one of your documents?

To check the progress of adding documents, you can look at the list of updates. [Documentation here](https://docs.meilisearch.com/reference/api/updates.html#updates) The document additions are done asynchronously.

**Comment by curquiza** [comment]
Closing this issue since we don't have any answer. Feel free to re-open if needed
