### ISSUE TITLE
Synonyms do not work for the Russian language if the letter "ь" is present.

### ISSUE THREAD

**Issue by coolycow** [meilisearch/MeiliSearch#1534]
**Describe the bug**
Synonyms do not work for the Russian language if the letter "**ь**" is present.

**To Reproduce**
Test 1:
I add an entry to the index: "Проверяем алфавит".
I add a couple of synonyms: "Проверяем алфавит" => "bbb", "bbb" => "Проверяем алфавит".
I make a search query "bbb": I get the result "Проверяем алфавит".

Test 2:
I add an entry to the index: "Проверяем ал**ь**фавит".
I add a couple of synonyms: "Проверяем ал**ь**фавит" => "bbb", "bbb" => "Проверяем ал**ь**фавит".
I do a search query "bbb": I get an empty result.

Test 3:
I add an entry to the index: "Хмел**ь**".
I add a couple of synonyms: "Хмел**ь**" => "bbb", "bbb" => "Хмел**ь**".
I do a search query "bbb": I get an empty result.

Test 4:
I add an entry to the index: "Хмел**ь**".
I add a couple of synonyms: "Хмел" => "bbb", "bbb" => "Хмел".
I make a search query "bbb": I get the result "Хмел**ь**" (part of the word matches).

I also checked it with "ё", "э", "ъ", "ю", "й", "ц" - no problems, the synonym search works correctly. 

**MeiliSearch version:** v0.20.0

**Additional context**
Ubuntu 20.04 LTS
Lumen 8
Scout 9

**Comment by curquiza** [comment]
Hello @coolycow!

I checked with the RC of v0.21.0 and this issue seems to not be present, I get results and not an empty array with test 2 and test 3. Can you confirm?

**Comment by coolycow** [comment]
Hi @curquiza!
I have now checked version 0.21.0. Everything works perfectly!
I will wait for the release to update the production.

Thanks!!!
