### ISSUE TITLE
Internal error on wrong document format during documents addition

### ISSUE THREAD

**Issue by mdubus** [meilisearch/MeiliSearch#1535]
**Describe the bug**

By trying to add documents with a wrong format (object for example), I received an `Internal Error` and a non-explicit error message: 

```node
{
  status: 'failed',
  updateId: 52,
  type: { name: 'DocumentsAddition' },
  message: 'invalid type: map, expected a sequence at line 1 column 1',
  errorCode: 'internal',
  errorType: 'internal_error',
  errorLink: 'https://docs.meilisearch.com/errors#internal',
  duration: 0,
  enqueuedAt: '2021-07-28T12:31:33.908278184Z',
  processedAt: '2021-07-28T12:31:33.912978970Z'
}
```

**To Reproduce**
Try to add a document instead of an array of documents: 
```node
{
    "id": 123,
    "title": "Pride and Prejudice",
    "comment": "A great book",
    "genre": "romance"
}
```

**Expected behavior**
Not sure, but certainly a more explicit error 😀

**MeiliSearch version:** 
0.21.0

**Comment by curquiza** [comment]
Hello! Thanks for the report.

The unclear sentence in `message` is already present in v0.20.0.
Guillaume is working on a new error handler and this message will be improved, but not for the v0.21.0. So @gmourier FYI.

However, to stay consistent with v0.20.0, the `errorCode` should be `bad_request` and the `errorType` should be `invalid_request_error`. This would make the error less "aggressive".
