### ISSUE TITLE
malformed keys in web interface

### ISSUE THREAD

**Issue by elonzh** [meilisearch/MeiliSearch#1538]
**Describe the bug**

![image](https://user-images.githubusercontent.com/8749411/127428228-8b4d11e2-e402-4d9b-ab25-c536f417154e.png)

The API response is ok.

```json
// http://127.0.0.1:7700/indexes/books/documents
[
    {
        "book_id": 123,
        "title": "Pride and Prejudice"
    },
    {
        "book_id": 456,
        "title": "Le Petit Prince"
    },
    {
        "book_id": 1,
        "title": "Alice In Wonderland"
    },
    {
        "book_id": 1344,
        "title": "The Hobbit"
    },
    {
        "book_id": 4,
        "title": "Harry Potter and the Half-Blood Prince"
    },
    {
        "book_id": 42,
        "title": "The Hitchhiker's Guide to the Galaxy"
    }
]
```

**To Reproduce**

Follow https://github.com/meilisearch/meilisearch-go#-getting-started to create some documents.

**Expected behavior**

![image](https://user-images.githubusercontent.com/8749411/127429375-75a13937-d76b-43a0-8f82-892319a9eaaa.png)

**Screenshots**

```json
{"commitSha":"UNKNOWN","buildDate":"2021-03-30T15:13:32.344119665+00:00","pkgVersion":"0.20.0"}
```

**Additional context**

Test with browsers: 
- Microsoft Edge 92.0.902.55
- Google Chrome  92.0.4515.107

**Comment by curquiza** [comment]
Hello @elonzh, thanks for the report. The next version of MeiliSearch (v0.21.0) will contain a fresh new dashboard and this issue should be fixed 🙂
You can already test the release candidate (RC) of the v0.21.0 -> https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc2

I close this issue then! Feel free to ask any questions.
