### ISSUE TITLE
Dumps pre v0.21 aren't working on v0.21.0rc3

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/MeiliSearch#1553]
**Describe the bug**
I got an error trying to import a bump into v0.21rc3
Tries both on docker image and compiled from source

**To Reproduce**
1. Create a dump with an older version of MeiliSearch (in my case it's a v0.18.1 dump)
2. Launch MeiliSearch v0.21.0rc3 with the --import-dump path/to/dump option
3. Error returned: 

```
[2021-08-03T17:01:05Z INFO  meilisearch_http::index_controller::dump_actor::loaders::v1] Loading dump, dump database version: 0.18.1, dump version: V1
Error: unknown field `attributesForFaceting`, expected one of `rankingRules`, `distinctAttribute`, `searchableAttributes`, `displayedAttributes`, `stopWords`, `synonyms`, `filterableAttributes` at line 1 column 220
```

**Expected behavior**
The dump should be imported without errors

**MeiliSearch version:** 
v0.21.0rc3

**Comment by MarinPostma** [comment]
Ok found it, this came from when we changed `attributes_for_faceting` to `filterable_attributes`, it should not have been changed in the dump v1 code.
