### ISSUE TITLE
Unable to add documents and endpoints timeout/unresponsive

### ISSUE THREAD

**Issue by carlreid** [meilisearch/meilisearch#1555]
**Describe the bug**
Since running v0.21.0 I've been noticing that after a short while, there are no more documents being added. This is because the document endpoint simply times out (HttpTimeout of 100 seconds is hit on our backend). Also trying to call the `/stats` endpoint for an index does not respond.

However, other endpoints like `/indexes/{index_uid}` and `/indexes/{index_uid}/search` respond fine.

**To Reproduce**
1. Not found.

**Expected behavior**
That documents can be added and `/stats` returns the index statistics. 

**Screenshots**
Timeout from our backend:  
![image](https://user-images.githubusercontent.com/33623601/128160761-c842607f-1941-4b46-b663-63a99f305eee.png)  
  
Example of curl from inside the container on localhost. First showing the index exists/returns. Second with short 10 second timeout.
![image](https://user-images.githubusercontent.com/33623601/128161645-71abd348-0a18-4d28-8316-32e2e275e131.png)

**MeiliSearch version:** v0.21.0rc3

**Additional context**
Running on kubernetes, using the [meilisearch chart](https://github.com/meilisearch/meilisearch-kubernetes).
Deletion of the volume/fresh run doesn't fix anything (have to do this on upgrades anyway)

**Comment by MarinPostma** [comment]
Have you been doing anything particular before this happens? ~ how many documents are you adding in your index? Is the index indexing at the time this happens?

**Comment by carlreid** [comment]
I'm not aware of anything particular before it happens. We're indexing a low amount of documents at a time (mostly 1 document, I know that's not ideal). The logs indicate that indexing is happening after the endpoints time out, whilst it works through the backlog of what was sent before it.

The only odd thing I noticed during investigating so far which may be somehow related was a lot of calls to try create the index again (returning a HTTP 400) and then eventually those calls would return HTTP 500s. When it comes to us sending the data, we make use of the meilsiearch dotnet package as follows (pseudo):
```csharp
ctor:
    _index = _meilisearchClient.Index("index-name");

async Add([DisallowNull] Document document):
    var updateStatus = await _index.AddDocuments(new[] { document });

async Add([DisallowNull] IEnumerable<Document> documents)
    var updateStatus = await _index.AddDocuments(documents);
```

So, nothing all that crazy there either. I looked through the [`AddDocuments`](https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/Index.cs#L94) implementation and nothing really stood out there as it just makes use of `HttpClient` directly.

Something was calling the [`GetOrCreateIndexes`](https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/MeilisearchClient.cs#L117) but I guess the initial get failed somehow and then it tried to `POST` for a new one resulting in the 400s/500s. I didn't observe that happening this morning though.

Also, when I ran meilisearch locally and reindexed all our data, I used the same C# code with no issue 🤷‍♂️

**Comment by MarinPostma** [comment]
It may be related to a large amount of updates constantly being enqueued, starving the process trying to read the stats, this is worth investigating.


Not sure why the sdk needs to call getOrCreate though, @alallema who's in charge of this sdk?

**Comment by carlreid** [comment]
> Not sure why the sdk needs to call getOrCreate though

Don't think you need to look into this too much, I can investigate a bit more on our side because I feel that it may have been using an older package making the `GetOrCreateIndexes` call. When I looked at the code for meilisearch-dotnet it didn't look like it was making the calls and I ran a unittest on my side to see if I could catch it making two calls which it didn't. Just thought it may have been part of the bug (hammering the create index)

I'm quite sure I ran meilisearch locally indexing 1 document at a time and didn't run into the issue but I can try again today when I get a moment to

**Comment by carlreid** [comment]
I tried bumping to the latest release candidate and that didn't help (didn't expect it to from the change log).

We didn't encounter these kind of issues before on v0.20.0. I tried creating a fresh [AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/) and deploying directly to that, which didn't seem to cause the problem either. Again, just reindexing the same data as the production environment.

I've still not been able to reproduce the problem to an extent that you could follow the steps (was trying to do that creating a fresh AKS instance) but it could well have been to do with not using "real" data in those steps. Unfortunately I can't spend too much more time looking into the issue.

We're now making moves to another search engine to replace meilisearch. The hopes were that meilisearch would be production ready when we were, but it's not looking likely. But luckily we have abstracted most away so we can switch easily and switch back if needed 😉

**Comment by curquiza** [comment]
Good to know it was not present in v0.20.0! Thanks a lot for your report. We are sorry you have to switch, especially because you are one of our contributors (I remember you on the meilisearch-k8s repo 😇)

To everyone reading this issue: this bug is a real concern for the core team and a priority to fix. If you have any help/feedback to share about your MeiliSearch usage in production that corresponds to this issue, please feel free to comment here or contact us in private.

**Comment by carlreid** [comment]
I tried another change this morning during meetings. I simply set my resources for meilisearch to be:
```
          resources:
            limits:
              cpu: '3'
              memory: 4Gi
            requests:
              cpu: '3'
              memory: 4Gi
```

After that, meilisearch probably performed for the longest it has since updating to v0.21 as shown below:
![image](https://user-images.githubusercontent.com/33623601/129008184-cfea7471-6c1a-4c78-b547-ecbefa59a06f.png)

Then it died all of a sudden, so I do think it's most likely related to some kind of consumption issue (before the resource scaled as "Burstable"). This is only for around 8000 documents on the index. If I inspect the usage on the node, it's nothing close to the 3 CPU + 4GB RAM:
![image](https://user-images.githubusercontent.com/33623601/129008371-0d0d1782-9158-488a-b52b-6063e77799db.png)
![image](https://user-images.githubusercontent.com/33623601/129008399-e7c111bb-57ec-4d06-9328-a643792f8635.png)

**Comment by curquiza** [comment]
Thank you @carlreid for your investigation!
I'll keep you informed on the issue!

**Comment by MarinPostma** [comment]
I'm really starting to suspect a deadlock in the update store. This shouldn't be too hard to investigate. @carlreid are you also performing snapshots/dumps?

**Comment by carlreid** [comment]
@MarinPostma We were not performing any snapshots or dumps. Just adding documents and hitting /stats on the index is all that was happening

**Comment by Jure-BB** [comment]
I've encountered (probably) the same bug. 

Here's a sample that tries to reproduce the bug. It doesn't always fail, but if you try to run it a few times, it should fail at least once. 

```
public class Book
{
    public string  Id    { get; set; }
    public string  Title { get; set; }
    public string? Description  { get; set; }
    List<string>?  Tags  { get; set; }
}

[Test]
public async Task Add_docs_bug_test()
{
    var client  = new MeilisearchClient("http://localhost:7700");
    var indexes = await client.GetAllIndexes();
    var indexId = "books";
    if (indexes.Select(x => x.Uid).Contains(indexId))
    {
        await client.DeleteIndex(indexId);
        await Task.Delay(1000);
    }

    var newIndex = await client.CreateIndex(indexId);

    for (int batch = 0; batch < 10; batch++)
    {
        var index = await client.GetIndex(indexId);
        for (int i = 0; i < 1000; i++)
        {
            var documents = Enumerable.Range(0, 200)
               .Select(j => new Book { Id = $"{i}_{j}", Title = $"Le Book {i}_{j}" }).ToArray();
            var result = await index.AddDocuments<Book>(documents);
        }
    }
}
```

I tested it using **meilisearch-dotnet** & NUnit, running inside WSL2 docker on windows 

```
meilisearch:
  image: getmeili/meilisearch:v0.22.0
  restart: always
  ports:
    - 7700:7700
  environment: 
    MEILI_ENV: development
    MEILI_NO_ANALYTICS: 1
  volumes:
    - ./meilisearch/data:/data.ms
```

```
Exception:
System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
  ----> System.TimeoutException : The operation was canceled.
  ----> System.Threading.Tasks.TaskCanceledException : The operation was canceled.
  ----> System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
  ----> System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Meilisearch.Index.AddDocuments[T](IEnumerable`1 documents, String primaryKey) in ...\_libs\meilisearch-dotnet\src\Meilisearch\Index.cs:line 103
```

**Comment by curquiza** [comment]
Do you get the same error locally, I mean with a MeiliSearch running locally?

**Comment by Jure-BB** [comment]
@curquiza Like Carl pointed out, timeout is 100 seconds, not ms.

> Do you get the same error locally, I mean with a MeiliSearch running locally?

I only tested with docker.

>  Did your MeiliSearch instance freeze after this?

Maybe. I'll try running it without `restart: always`

**Comment by curquiza** [comment]
Oops! I indeed miss read, sorry 😅

If you can share (in private) your dataset and the steps @Jure-BB it would be awesome. We desperately try to reproduce this bug

**Comment by carlreid** [comment]
The steps provided should be sufficient to encounter a timeout problem. However I am not sure it is related to what I was seeing.

When I run the reproduce steps, I get a timeout if I ran the code from Windows -> WSL/Docker. Though when I run the example after it was compiled for Linux from inside WSL; I don't seem to get the problem so far. So this timeout issue could be related to some WSL networking between Windows and WSL?

Also even though the HttpClient times out, a manual browse to `http://localhost:7700/indexes/books/stats` still returns stats. If it did reproduce the issue I encountered, then we'd expect that call from a browser to timeout also.

I'll keep the example running in WSL for another 30 minutes and 🙏 it crashes 😄

**Comment by Jure-BB** [comment]
> Did your MeiliSearch instance freeze after this?

No, it doesn't freeze.

It seems to be some kind of resource exhaustion, possibly related to Windows -> WSL -> Docker stack. I tried increasing the timeout to 15 minutes and it didn't help. Requests seems to get swallowed somewhere along the way when the load is high. 

If I implement status pooling after each `AddDocuments` call and wait until status is completed (i.e. `"processed"` or `"failed"`) before adding additional documents, the task completes successfully without any timeouts. 

IMO, MeiliSearch's asynchronous operations API lends itself to writing code that can easily overload the server when doing bulk inserts. Maybe add some examples to the documentation of what is considered a best practice for bulk inserts. 

 @carlreid 30 minutes should be plenty 😄 As the issue in my case seems to be related to resource exhaustion, you could try increasing the load on the server by minimizing the delay between `AddDocuments` call by removing awaits and Task.Delay. 

Something like: 
```
...
    for (int batch = 0; batch < 10; batch++)
    {
        var index = await client.GetIndex(indexId);
        for (int i = 0; i < 1000; i++)
        {
            var documents = Enumerable.Range(0, 200)
                .Select(j => new Book { Id = $"{i}_{j}", Title = $"Le Book {i}_{j}" }).ToArray();
            index.AddDocuments<Book>(documents);
        }
    }
    Console.WriteLine("Finished writing books");

    CheckStats(client);
...


async Task CheckStats(MeilisearchClient client)
{
    var targetIndex = await client.GetIndex(indexId);
    var stats = await targetIndex.GetStats();
    Console.WriteLine("Got stats fine... lets try again.");
}
```
This isn't something you would normally write, but just to test, if it's possible that your issue is also due to resource exhaustion. If you don't get a timeout in a few minutes with this, then these issues are probably not related.

**Comment by curquiza** [comment]
Hello!

Is anyone there who has still the issue with the latest version of Meilisearch, currently v0.25.0?

**Comment by curquiza** [comment]
I close this issue due to lack of feedback regarding it
FYI v0.27.0 will be release next week including indexation performance improvement.
Feel free to ask to reopen if needed

**Comment by carlreid** [comment]
@curquiza No problem, sorry I couldn't help pinpoint the issue down, but thanks for taking the time to help out ☺️

**Comment by curquiza** [comment]
Thank you for trying to help us with this bug! A lot of things changed in the core-engine, I don't know if the issue is still present. If it is, let's hope for an issue we succeed to reproduce 🤞 
Thanks again for being such involved!
