### ISSUE TITLE
Search just doesn't return results for some records

### ISSUE THREAD

**Issue by CodeWithClass** [meilisearch/MeiliSearch#1565]
**Describe the bug**
All 1 Million + records have been imported successfully but meilisearch just doesn't seem to bother searching 9/10th of the records. It searches maybe the first 100k?  I've tried increasing php memory limit but with no success. Is there some sort of limit? See screenshots.

**Expected behavior**
I expect all the indexed data to be searched

**Screenshots**
1M+ successfully imported
<img width="482" alt="Screen Shot 2021-08-07 at 11 23 23 AM" src="https://user-images.githubusercontent.com/19517218/128605293-20c7bf47-02bf-4f32-bbd1-aecffaf8dd4f.png">

This doesn't exist? Really
<img width="963" alt="not working" src="https://user-images.githubusercontent.com/19517218/128605534-7df4c576-4134-42fb-8f28-113f53b60d91.png">

Check via SQL query. Yep its there.
<img width="454" alt="Screen Shot 2021-08-07 at 11 20 35 AM" src="https://user-images.githubusercontent.com/19517218/128605296-3d390f4c-ee5e-42c7-aeba-7eb19645b74c.png">

This is one of the "lucky" records that get searched.
<img width="962" alt="working" src="https://user-images.githubusercontent.com/19517218/128605499-f7a339a6-f0c5-488c-b4eb-311c56541439.png">

MeiliSearch version: 
v20

**Additional context**
Both on local (MacOs Big Sur) and Server (Ubuntu 20)

**Comment by Kerollmops** [comment]
Hey @CodeWithClass,

First of all thank you for the interest you put into MeiliSearch.

When you send documents to MeiliSearch the server [will process them asynchronously](https://docs.meilisearch.com/learn/advanced/asynchronous_updates.html#asynchronous-updates). Another very important thing to keep in mind is that it is **way faster** to send big batches of documents at the same time, never send documents one by one (something like batches of 100MiB).

We are currently working on [the v0.21 release](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc3) that will be out in less than 1/2 weeks, this pre-release version can index faster, and, at the same time, working on an auto batching system on the MeiliSearch side (out in v0.22).

You can try this new release as we improved the indexing times. We are also working on a better indexing system for the v0.22.

Have a good day!

**Comment by CodeWithClass** [comment]
> Hey @CodeWithClass,
> 
> First of all thank you for the interest you put into MeiliSearch.
> 
> When you send documents to MeiliSearch the server [will process them asynchronously](https://docs.meilisearch.com/learn/advanced/asynchronous_updates.html#asynchronous-updates). Another very important thing to keep in mind is that it is **way faster** to send big batches of documents at the same time, never send documents one by one (something like batches of 100MiB).
> 
> We are currently working on [the v0.21 release](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc3) that will be out in less than 1/2 weeks, this pre-release version can index faster, and, at the same time, working on an auto batching system on the MeiliSearch side (out in v0.22).
> 
> You can try this new release as we improved the indexing times. We are also working on a better indexing system for the v0.22.
> 
> Have a good day!

I

**Comment by curquiza** [comment]
Hello @CodeWithClass!

@Kerollmops asked you this because we want to be sure all the documents are added and processed by your MeiliSearch instance. The documents that are not processed cannot be retrieved during the search.
Can you check all the updates have been processed using [the `GET /indexes/:uid/updates` route](https://docs.meilisearch.com/reference/api/updates.html#get-all-update-status).
All the updates should be `processed`.

**Comment by CodeWithClass** [comment]
Ahhh Yes. All updates are now "processed" and it works. 

For anyone reading this in the future basically: give it time to index. it may take hours/days.

Thanks guys

**Comment by curquiza** [comment]
Awesome @CodeWithClass! Thanks for your feedback 😄 

I would add something for people that don't see the end of their data indexation: waiting for hours can happen, days are not expected. Here is the optimized way to push data to MeiliSearch: 

* We always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
* If you have a memory crash (not your case @CodeWithClass from what I understand) it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.
* Finally, we fixed some performance issues in the next version (v0.21.0). You can test a [release candidate](https://github.com/meilisearch/MeiliSearch/releases), or wait for the official release in few days. Also, we are still working on a new indexer that will be released in 1-2 months.

**Comment by CodeWithClass** [comment]
Do you know if there is a way to push by batch when using laravel scout + meilisearch? I used the php artisan scout:import command

**Comment by curquiza** [comment]
with the `-c` command of `php artisan scout:import` you can select the number of docs by batch

https://github.com/meilisearch/meilisearch-laravel-scout/issues/58#issuecomment-727102131

**Comment by CodeWithClass** [comment]
Amazing. I was able to batches of 100,000 and my entire DB was indexed in minutes!

Follow up question. Is it possible to cancel "enqueued" operations?

**Comment by curquiza** [comment]
Not at the moment sorry! You can ask for new features here :) https://github.com/meilisearch/product/discussions/categories/feedback-feature-proposal

**Comment by CodeWithClass** [comment]
So how would I stop the enqueuing of the documents that are taking forever?

**Comment by curquiza** [comment]
This is really weird!

I've just tested
- add a lot of documents in an index
- before the update is processed: delete the index
- I cannot get the update status of the index: this is expected because the index does not exist anymore
- I create a new index with the same name
- I get the update status of the index: I get an empty array.

So, contrary to you the "deleting and recreating index" method works.
