### ISSUE TITLE
Sending a non supported `Content-Type` should leads to a `415 Unsupported Media Type`

### ISSUE THREAD

**Issue by gmourier** [meilisearch/MeiliSearch#1587]
**Describe the bug**

When I send a `Content-Type` different from `application/json` like `text/html`, the status code of the response is `202 Accepted`.

**To Reproduce**

- Specify a non supported `Content-Type` like `text/html`

**Expected behavior**

I expect the API to return a `415 Unsupported Media Type` when I'm specifying a non supported `Content-Type` header.

**MeiliSearch version:** [v0.21.0]

**Comment by curquiza** [comment]
Will be fixed during the implementation of new formats: CSV and NDJSON
- https://github.com/meilisearch/specifications/blob/main/text/0028-indexing-csv.md
- https://github.com/meilisearch/specifications/blob/main/text/0029-indexing-ndjson.md
🙂

**Comment by irevoire** [comment]
And once we implement that, are we supposed to refuse `application/x-www-form-urlencoded`?
Because that’s what `curl` sends us when we follow the current commands from the documentation.

```
curl \
  -X POST 'http://127.0.0.1:7700/indexes/movies/documents' \
  --data @./movies.json
```

```
POST /indexes/movies/documents HTTP/1.1
Host: 127.0.0.1:7700
User-Agent: curl/7.64.1
Accept: */*
Content-Length: 9482306
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue

```

**Comment by curquiza** [comment]
Sine the decision has been made, closing this in favor of #1665
