### ISSUE TITLE
Panic error when decoding

### ISSUE THREAD

**Issue by lev-michael** [meilisearch/MeiliSearch#1594]
Hello,

I am trying to update document, but it always fail. 

Status of update it's always same:

```
{
    "status": "failed",
    "updateId": 348,
    "type": {
        "name": "DocumentsPartial"
    },
    "message": "internal: decoding failed",
    "errorCode": "internal",
    "errorType": "internal_error",
    "errorLink": "https://docs.meilisearch.com/errors#internal",
    "duration": 0.007,
    "enqueuedAt": "2021-08-17T13:44:39.126708739Z",
    "processedAt": "2021-08-17T13:44:39.150588898Z"
}
```

Error could be caused by sending only updated fields to database not whole object, but in old version  v0.20 everything works as expected.

Working with Meilisearch in NestJS project. My code:

```
  const client = new MeiliSearch({
    host: `http://http://127.0.0.1:7700/`,
    apiKey: `${appConfig().meiliDatabase.apiKey}`,
  });

....

this.meiliService.meiliSearchClient.index(`notes`).updateDocuments([{_id: '123', text: 'Hello'  }])

```

**Comment by curquiza** [comment]
Hello @lev-michael! Thanks for your return!
can you send us the dataset that causes the failure? Otherwise, we cannot reproduce it.

**Comment by curquiza** [comment]
Also, if you have time, could you check to import your data using our new indexer? It's available at the branch `test-new-indexer` on this PR https://github.com/meilisearch/MeiliSearch/pull/1588:

```bash
git clone git@github.com:meilisearch/MeiliSearch.git
cd MeiliSearch
git checkout test-new-indexer
cargo run --release -- --master-key=YourMasterKey
```
It would be very helpful!
Thanks in advance 🙂

**Comment by lev-michael** [comment]
> Hello @lev-michael! Thanks for your return!
> can you send us the dataset that causes the failure? Otherwise, we cannot reproduce it 
> 
> What is your machine? Are you using the docker image or the binary file of rc5?


Sure, object I am trying to update:

```
{
_id: "611a3dd9d2371e1e31599367",
createdAt: 1629109721442,
label: "New case",
slug: null,
author: "John Cage",
category: 103,
status: {
   "state":"CREATED",
   "updatedAt": "2021-08-16T10:28:41.414Z",
   "description":"Case created"
},
responsiblePersons: ["John Cage"],
advisors: [],
clients: [],
watchers: ["John Cage"],
type: "case",
updatedAt: 1629193455171,
}
```
With update: 
```
this.meiliService.meiliSearchClient.index(`cases`).updateDocuments([{
  _id: '611a3dd9d2371e1e31599367', 
  label: 'Not new case',
  updatedAt: 1629199655171  
}])
```

Index primary key is set as '_id'.





> Also, if you have time, could you check to import your data using our new indexer? It's available at the branch `test-new-indexer` on this PR #1588:
> 
> ```shell
> git clone git@github.com:meilisearch/MeiliSearch.git
> cd MeiliSearch
> git checkout test-new-indexer
> cargo run --release -- --master-key=YourMasterKey
> ```
> 
> It would be very helpful!
> Thanks in advance

Ok if I have time I will try it and check it.

**Comment by curquiza** [comment]
Hello @lev-michael! I'm sorry, I didn't succeed to reproduce your error with the document you gave.

Here are my steps:
- create an index with `_id` as primary key
- add the document with [this route](https://docs.meilisearch.com/reference/api/documents.html#add-or-replace-documents) :
```json
[
{
"_id": "611a3dd9d2371e1e31599367",
"createdAt": 1629109721442,
"label": "New case",
"slug": null,
"author": "John Cage",
"category": 103,
"status": {
   "state":"CREATED",
   "updatedAt": "2021-08-16T10:28:41.414Z",
   "description":"Case created"
},
"responsiblePersons": ["John Cage"],
"advisors": [],
"clients": [],
"watchers": ["John Cage"],
"type": "case",
"updatedAt": 1629193455171
}
]
```
- Update the document with [this route](https://docs.meilisearch.com/reference/api/documents.html#add-or-update-documents):
```json
[
  {
	"_id": "611a3dd9d2371e1e31599367", 
    "label": "Not new case",
    "updatedAt": 1629199655171  
  }
]
```
- Check the update with [this route](https://docs.meilisearch.com/reference/api/updates.html#get-all-update-status), here is the result:
```json
[
    {
        "status": "processed",
        "updateId": 0,
        "type": {
            "name": "DocumentsAddition",
            "number": 1
        },
        "duration": 0.058,
        "enqueuedAt": "2021-08-18T07:30:43.550368Z",
        "processedAt": "2021-08-18T07:30:43.609698Z"
    },
    {
        "status": "processed",
        "updateId": 1,
        "type": {
            "name": "DocumentsPartial",
            "number": 1
        },
        "duration": 0.021,
        "enqueuedAt": "2021-08-18T07:30:47.460047Z",
        "processedAt": "2021-08-18T07:30:47.481681Z"
    }
]
```

Be sure we really want to fix this bug, this is indeed NOT expected and not the user's fault. We just need more information to reproduce it and fix it.
Could you send us the detailed steps? And if possible your dataset. In private by mail if you cannot share it!

**Comment by curquiza** [comment]
Is your machine 32bit?
Can you give us the output of

```bash
uname -a
```

in your terminal?

**Comment by curquiza** [comment]
Hello @lev-michael[
MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/v0.21.0) is out. Does this version solve your issue?

**Comment by lev-michael** [comment]
> Is your machine 32bit?
> Can you give us the output of
> 
> ```shell
> uname -a
> ```
> 
> in your terminal?

I have 64bit machine with Ubuntu 20.04.



> Hello @lev-michael[ MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/v0.21.0) is out. Does this version solve your issue?

Yes, it does. I tried it today with new version and it runs without any problem. Unfortunately I didn't find what caused my problem before. 

Thank you for your help.

**Comment by curquiza** [comment]
Thank you for you report 😄 

I close this issue then
