### ISSUE TITLE
 Panicked at 'Update store loop exited'

### ISSUE THREAD

**Issue by ChillFish8** [meilisearch/MeiliSearch#1597]
**Describe the bug**
Meilisearch can be observed to panic after a fairly large processing of documents followed by some high load followed by dropping all docs.

Once this panic's it becomes impossible to add any more documents, all requests then go to a 500 status code.

**Full Error Message**
```
thread 'tokio-runtime-worker' panicked at 'Update store loop exited', meilisearch-http\src\index_controller\update_actor\store\mod.rs:252:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-08-18T17:20:47Z INFO  actix_web::middleware::logger] 127.0.0.1:51184 "DELETE /indexes/bench/documents HTTP/1.1" 500 146 "-" "-" 0.005879
thread 'tokio-runtime-worker' panicked at 'Update store loop exited', meilisearch-http\src\index_controller\update_actor\store\mod.rs:252:13
[2021-08-18T17:20:47Z INFO  actix_web::middleware::logger] 127.0.0.1:51184 "POST /indexes/bench/documents HTTP/1.1" 500 146 "-" "-" 0.082963
```

**Rough Steps To Reproduce**
Steps to reproduce the behaviour:
1. Upload the movies.json dataset.
2. Search the index about 300k times (I don't know if this number is special or not)
3. Try clear docs -> Panics  (This sometimes does not happen on the first attempt of steps, but does happen consistently enough.)
4. Try upload docs -> Panics

**Steps Using lnxcli**
I ran into this issue while building a benchmarker to measure MeiliSearch, this can give some more info possibly.
1. Download the engine & cli @ https://github.com/chillfish8/lnx
2. Build and run from source giving it the movies.json dataset, the sample set of words in typing mode. 200 concurrency.
3. Run the benchmark.
4. Repeat until it panics.

Resulting benchmark results just before the panic:
```
 INFO  lnxcli > starting benchmark system
 INFO  benchmark > starting runtime with 12 threads
 INFO  benchmark::meilisearch > MeiliSearch took 36.364s to process submitted documents
 INFO  benchmark              > Service ready! Beginning benchmark.
 INFO  benchmark              >      Concurrency @ 200 clients
 INFO  benchmark              >      Searching @ 50 sentences
 INFO  benchmark              >      Mode @ Typing
 INFO  benchmark::sampler     > General benchmark results:
 INFO  benchmark::sampler     >      Total Requests Sent: 294200
 INFO  benchmark::sampler     >      Average Requests/sec: 449.29
 INFO  benchmark::sampler     >      Average Latency: 445.145172ms
 INFO  benchmark::sampler     >      Max Latency: 2.7390933s
 INFO  benchmark::sampler     >      Min Latency: 13.4143ms
 INFO  lnxcli                 > commands complete!
```

**Expected behaviour**
The worker not to panic, after this happens it seems to require a full restart to allow for normal operations.

**MeiliSearch version:** 
`main` branch, built on windows

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 12 Logical Processor(s)
Total Physical Memory	15.9 GB
```

**Comment by ChillFish8** [comment]
With some more digging, it seems like this is a similar re-appearance of the #1465 and #1455 however the related bug fix that was merged doesn't seem to have fixed the root cause.

**Comment by ChillFish8** [comment]
Running in debug we get a little error message:
```
[2021-08-18T18:12:26Z ERROR meilisearch_http::index_controller::update_actor::store] Update store loop exited.
```
Even though docs had finished processing about 30 minutes ago before the benchmark

unfortunately running in debug didn't provide any more info :(

**Comment by curquiza** [comment]
Hello @ChillFish8!
`main` is not the most updated branch at the moment, please try with `release-v0.21.0` or with one of our RCs: https://github.com/meilisearch/MeiliSearch/releases

**Comment by ChillFish8** [comment]
after some more testing, I do believe v0.21.0 has fixed this issue, thanks for pointing out the different branch 👌

**Comment by curquiza** [comment]
Thanks for your report @ChillFish8! I close this issue then :)
