### ISSUE TITLE
unknown field `facetFilters`

### ISSUE THREAD

**Issue by bnfd** [meilisearch/MeiliSearch#1603]
I'm using the latest version (v0.21.0rc6).

```
$ curl 'http://localhost:7700/indexes/moviestest2/search' --data '{ "facetFilters": ["tags:selection1"] }'
```
I get the following error:

```
{"message":"Json deserialize error: unknown field `facetFilters`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `matches`, `filter`, `facetsDistribution` at line 1 column 16","errorCode":"bad_request","errorType":"invalid_request_error","errorLink":"https://docs.meilisearch.com/errors#bad_request"}
```

**Comment by Sembiance** [comment]
I think `facetFilters` was removed in `0.21`.
According to the dev docs: https://dev.docs.meilisearch.com/reference/api/search.html#search-in-an-index-with-get-route
There is just `filter` now, I believe.

**Comment by Sembiance** [comment]
Ahh yes, here is a blog post that discuses how `facetFilters` has been replaced with just `filter`: https://blog.meilisearch.com/refactoring-meilisearch/

**Comment by bnfd** [comment]
Thanks @Sembiance .
Using filter results in an error:
```
$ curl 'http://localhost:7700/indexes/moviestest2/search' --data '{ "filter": ["tags:selection1"] }'
```
```
{"message":" --> 1:5\n  |\n1 | tags:selection1\n  |     ^---\n  |\n  = expected word","errorCode":"invalid_filter","errorType":"invalid_request_error","errorLink":"https://docs.meilisearch.com/errors#invalid_filter"}
```

Am I doing something wrong?

**Comment by Sembiance** [comment]
I also believe the `<term>:<match>` syntax was removed too and replaced with `<term>=<match>` Try using `"tags=selection1"`

**Comment by bnfd** [comment]
Now I'm getting `tags` is not filterable. 

```{"message":" --> 1:1\n  |\n1 | tags=selection1\n  | ^--^\n  |\n  = attribute `tags` is not filterable, available filterable attributes are: ","errorCode":"invalid_filter","errorType":"invalid_request_error","errorLink":"https://docs.meilisearch.com/errors#invalid_filter"}```

**Comment by Sembiance** [comment]
Make sure you have set `tags` as a `filterableAttributes` for the index settings:
```
curl -X POST 'http://localhost:7700/indexes/moviestest2/settings' --data '{"filterableAttributes" : ["tags"]}'
```

**Comment by bnfd** [comment]
Thanks, that helped.

The documentation is problematic: 
https://dev.docs.meilisearch.com/reference/api/filterable_attributes.html#get-filterable-attributes
The examples are missing. 
https://dev.docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#configuring-filters 
The examples still use `attributesForFaceting` which from what I understand has been deprecated in 0.21.0. 

I tried filterableAttributes and there is something weird going on. 
The first time I did:
```curl -X POST 'http://localhost:7700/indexes/moviestest2/settings' --data '{"filterableAttributes" : ["tags"]}'```
Then did:
```curl 'http://localhost:7700/indexes/moviestest2/search' --data '{ "filter": ["tags:selection1"] }' ``` 
It resulted in an error for about a minute and then it worked..

Then I added another filter, `seltags`:

``` curl -X POST 'http://localhost:7700/indexes/moviestest2/settings' --data '{"attributesForFaceting" : ["tags,seltags"]}'```

Tried querying for `"seltags=selection1"` and `"tags=selection1"` but I'm getting an error:
```
curl 'http://localhost:7700/indexes/moviestest2/search' --data '{ "filter": ["seltags=selection1"] }'
```

```
{"message":" --> 1:1\n  |\n1 | seltags=selection1\n  | ^-----^\n  |\n  = attribute `seltags` is not filterable, available filterable attributes are: tags,seltags","errorCode":"invalid_filter","errorType":"invalid_request_error","errorLink":"https://docs.meilisearch.com/errors#invalid_filter"}
```

```
curl 'http://localhost:7700/indexes/moviestest2/search' --data '{ "filter": ["tags=selection1"] }'
```

```
{"message":" --> 1:1\n  |\n1 | tags=selection1\n  | ^--^\n  |\n  = attribute `tags` is not filterable, available filterable attributes are: tags,seltags","errorCode":"invalid_filter","errorType":"invalid_request_error","errorLink":"https://docs.meilisearch.com/errors#invalid_filter"}
```

**Comment by Sembiance** [comment]
Modifying the index settings, adding a new field to `attributesForFaceting` will cause meilisearch to re-process all the documents and this can take some time. You can check the status with: https://dev.docs.meilisearch.com/reference/api/updates.html#get-all-update-status

**Comment by bnfd** [comment]
I checked, it says it took 48 secs:
```
{"status":"processed","updateId":12,"type":{"name":"Settings","settings":{"filterableAttributes":["tags,seltags"]}},"duration":47.951
```
In total there are 20k documents in the index and only 2 have the tag applied.. 
Despite setting the filterable attributes, it erroneously reports they are not filterable when trying to query `"filter": ["tags=selection1"]` .

**Comment by curquiza** [comment]
Hello @bnfd!
Sorry for the confusion with this breaking change, I will open an issue in the documentation: this is a known problem but this is indeed not convenient! 

> Is the speed for faceting the same in 0.20.0?

Adding facets needs a re-indexation. Since v0.21.0, the re-indexation is a little bit longer since it involves more calculations to provide a better search relevancy. However, we are working right now on improving the indexation speed in v0.22.0 (released in the middle of September)

And thanks @Sembiance for the help 🙂

**Comment by curquiza** [comment]
Closing this issue, since
- v0.21.0 is released and the docs as well -> the examples are now are up-to-date
- an issue about pre-prod documentation has been opened
