### ISSUE TITLE
"pdates route gives information" doesnt throw up any results

### ISSUE THREAD

**Issue by zehawki** [meilisearch/MeiliSearch#1611]
**Describe the bug**
Partial word search doesnt throw up a result

**To Reproduce**
1. Go to https://docs.meilisearch.com/
2. Click on the search box
3. Type in "pdates route gives information"
4. No results

**Expected behavior**
Should be the same as with "updates route gives information", or?

**Screenshots**

![image](https://user-images.githubusercontent.com/8095144/130514171-5a4c6e41-4f4f-4fdc-b7de-be2736ad44e5.png)

vs

![image](https://user-images.githubusercontent.com/8095144/130514213-38ea5a3d-7ef1-43d1-9026-6f05454bd2a7.png)

**Comment by curquiza** [comment]
Hello @zehawki!

No, you should not the same result as `updates route gives information` -> no document contain `pdates`, and `pdates` is not a prefix (the beginning of a word contained in some documents) so you cannot have any result 🙂

**Comment by curquiza** [comment]
I would like to complete my note: MeiliSearch is typo tolerant, so `pdates` is indeed a `updates` with a typo of 1. However, MeiliSearch does not take into account typo on the first letter at the moment. This is something we might improve, see this discussion about this improvement: https://github.com/meilisearch/product/discussions/83

**Comment by zehawki** [comment]
Thank you for the additional detail - thats what I was thinking as well, that typo tolerancy should account for this...

**Comment by curquiza** [comment]
Hello again @zehawki! I want to apologize for the confusion in this issue, my bad: the old versions (v0.20.0 and before) contain this "bug". Not v0.21.0 that we just released! The typo tolerance on the first letter is now allowed 😄 

The search bar you use in the document is just an old version at the moment, we plan to change it for v0.21.0 soon 🙂

**Comment by zehawki** [comment]
Okays! I actually saw this in my own installation, then came to check on the site. I see that my install (DO droplet) is on 0.20.0.

**Comment by curquiza** [comment]
Yes, we only release yesterday, it might take time, but someone will answer to your post here: https://github.com/meilisearch/MeiliSearch/discussions/1617

I close this issue then! :)
