### ISSUE TITLE
Use the `Setting` enum fro milli in the Settings

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#1620]
I would like to use the `Setting` enum introduced by @shekhirin in milli in MeiliSearch https://github.com/meilisearch/milli/pull/148.

It makes the code must easier to read, and it would [make this part of the code better](https://github.com/meilisearch/MeiliSearch/blob/850069af75cc79cb2809de616c322f10e914efec/meilisearch-http/src/index/updates.rs#L36-L87).

**Comment by shekhirin** [comment]
Hi @Kerollmops! Long time no see 😄. I think I can work on this one, should be easy to do.

**Comment by Kerollmops** [comment]
Hey @shekhirin,

Very happy to see you ❤️ Indeed long time no see 🙈

You work so fast your 3 pull requests have hidden this notification on my Github notification feed!
