### ISSUE TITLE
MeiliSearch v0.21.0 unknown field `filterableAttributes`

### ISSUE THREAD

**Issue by dorinniscu** [meilisearch/MeiliSearch#1624]
**PHP:** [8.0]
**Laravel:** [8.56.0]
**MeiliSearch:** [0.21.0]
**MeiliSearch PHP:** [0.19.0]

I upgraded MeiliSearch from 0.20.0 to 0.21.0.

As I understand from documentation "**attributesForFaceting**" has been renamed into "**filterableAttributes**" so I am trying to update the settings accordingly.

I receive an error: "**Invalid JSON: unknown field `filterableAttributes`, expected one of `rankingRules`, `distinctAttribute`, `searchableAttributes`, `displayedAttributes`, `stopWords`, `synonyms`, `attributesForFaceting` at line 1 column 52**"

It is like the package has not been upgraded but it actually is the latest version. (Running **meilisearch** command)

Package version: "0.21.0".

**Comment by curquiza** [comment]
Hello, can you get the `/version` route:
```bash
curl -X GET '<your-url>/version'
```

**Comment by dorinniscu** [comment]
{"commitSha":"dd645e6da4f27167d34a1d7a505ad14b27c86203","commitDate":"2021-08-23T11:06:45+00:00","pkgVersion":"0.21.0"}

**Comment by dorinniscu** [comment]
Thanks @curquiza 
I restarted the service and it works fine now. Probably the v0.20.0 was still running. :)

**Comment by curquiza** [comment]
Ok nice 🙂 I'm happy this is now ok for you!
I close this issue then!

**Comment by dorinniscu** [comment]
@curquiza And not least, congrats for an amazing product! :)
