### ISSUE TITLE
MeiliSearch v0.21.0 missing disjunctive filters

### ISSUE THREAD

**Issue by dorinniscu** [meilisearch/MeiliSearch#1626]
@qdequele  I upgraded MeiliSearch to **v0.21.0** and seems that that the possible facets (disjunctive filters) does not come at all (on **v0.20.0** I received them but with count 0). Do I miss something? I send the values as before using inner arrays for "**OR**" conditions. It behaves as "**AND**"

_Originally posted by @dorinniscu in https://github.com/meilisearch/MeiliSearch/issues/1499#issuecomment-904960104_

**Comment by curquiza** [comment]
Hello @1615!
Closing this in favor of https://github.com/meilisearch/MeiliSearch/issues/1499
Your problem is more understandable in this issue 🙂
