### ISSUE TITLE
The attribute does not work attributesToHighlight

### ISSUE THREAD

**Issue by Sliper959595** [meilisearch/MeiliSearch#1630]
Hello everyone! The word highlighting function in meilisearch does not work. Please help me solve this issue.

```php
 public function __invoke (Request $request){
        
        $rubric  = Category::select('id', 'title')->where('type', 0)->get()->sortBy('title');
        $query = $request['query'];
        $post = Post::search($query,  function($meilisearch, $query, $options) use ($request){
            $date = strtotime(now());
            
            if(empty($request->rubric))
            {
                $options['filters'] = "status = 1";
            }
            else
            {
                $options['filters'] = "status = 1 AND (category_id = $request->rubric)";
                $options['attributesToHighlight'] = ['title', 'excerpt'];
            }
           
            return $meilisearch->search($query,$options );
        } )
        ->paginate(10);

        $modelCollection =  $post->load('category');
      
        return view('search.index', compact('post', 'request', 'rubric'));
    }
```

**Comment by CaroFG** [comment]
Could you please specify which version of MeiliSearch and SDK are you using? 🙂

**Comment by Sliper959595** [comment]
@CaroFG docker pull getmeili/meilisearch launched in docker from here image

**Comment by CaroFG** [comment]
Just to be sure could you make a request to [GET /version](https://docs.meilisearch.com/reference/api/version.html#get-version-of-meilisearch)?

**Comment by Sliper959595** [comment]
@CaroFG "pkgVersion": "0.20.0"

**Comment by CaroFG** [comment]
v0.20 doesn't highlight inside of arrays, maybe that's the problem. The latest version is now v0.21.0, a lot of issues have been solved with this new version, including highlight, could you please try it with v0.21.0 and tell us if the problem persists? 🙏  Use the `latest` tag for the docker image `getmeili/meilisearch:latest`

Note that there are some **breaking changes** in this new version (`filters` is now `filter` without `s` for instance), you can see the list of changes and improvements here: https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0

**Comment by Sliper959595** [comment]
@CaroFG  Yes, of course. As soon as I do, I will write the result here

**Comment by Sliper959595** [comment]
@CaroFG  getmeili/meilisearch   latest           0c64516d5478   4 months ago   321MB  / I seem to have the latest selected

**Comment by CaroFG** [comment]
Ok, my bad, the latest at the moment you downloaded it was v0.20 that's why it has this tag. Try: `docker pull getmeili/meilisearch:v0.21.0` 😁

**Comment by Sliper959595** [comment]
@CaroFG In the new version, importing 40,000 records takes a very long time

**Comment by CaroFG** [comment]
Yes, we are aware of this loss of performance in some cases, you can learn more about it in this [blogpost](https://blog.meilisearch.com/refactoring-meilisearch/). But be sure our team is working to improve indexation performance

**Comment by Sliper959595** [comment]
@CaroFG I have updated the relevance settings via insomnia, but they have not yet taken effect, is it rather because the import has not passed yet?

**Comment by CaroFG** [comment]
If I am not wrong, it is recommended to first add the settings and then the documents because when changing the settings MeiliSearch has to reindex the documents to take the new settings into account. So this can take a while...

**Comment by Sliper959595** [comment]
@CaroFG  @gmourier With this, everything is clear. Thanks for the prompt help and clarification. I am glad that there is such support. Respectable. 

I have one more question for you, I need to sort the returned data by the "created_at" field. But when I put "desc (created_at)" the sorting doesn't work for me. The field is in my "timestamp" database. Please help with the ranking settings.

![1](https://user-images.githubusercontent.com/63448959/131215283-d5ac3111-2566-40b9-a59b-174093e4da10.JPG)
![2](https://user-images.githubusercontent.com/63448959/131215284-f73b9013-3fd3-4f64-a500-c0034f8da931.JPG)

**Comment by gmourier** [comment]
Hello @Sliper959595 👋

Custom ranking rules like `desc(created_at)` only work on numeric fields.  See https://docs.meilisearch.com/reference/features/settings.html#custom-ranking-rule

You can store an extra field so you don't have to replace all the logic that is already on `created_at` or change the format of `created_at` and the logic that goes with it.

**Comment by curquiza** [comment]
Closing this since we cannot reproduce the bug. Of course feel free to re open if needed :)

**Comment by mirkos93** [comment]
Hello, i've the same issue:

```
$posts = Post::search($query, function($meilisearch, $query, $options){
            $options['attributesToHighlight'] = ['content'];
            return $meilisearch->search($query, $options);
});
```

If I do a `dd` of `$meilisearch->search($query, $options)` it correctly returns the `_formatted` key:

![image](https://user-images.githubusercontent.com/295767/143559379-121cfab4-46a6-4a67-a6eb-ec2488d6b0ba.png)

But when I go to collect the results from Laravel Scout, however this is not incorporated:

![image](https://user-images.githubusercontent.com/295767/143559550-e187d90b-014d-41d8-abc2-b7170d4b6fcb.png)

The complete code:

```
$query = 'Signori';
$posts = Post::search($query, function($meilisearch, $query, $options){
            $options['attributesToHighlight'] = ['content'];
            return $meilisearch->search($query, $options);
});
dump($posts->get());
```
