### ISSUE TITLE
Use GitHub PAT as env var for `download-latest.sh` script

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1655]
## Motivation

Since the API call to GitHub is really limited without any authentication, the [`download-latest.sh`](https://raw.githubusercontent.com/meilisearch/MeiliSearch/master/download-latest.sh) script is not usable in CIs due to the big amount of calls. We want our users to be able to use the script in CIs.

## How?

- Make the script use the `GITHUB_PAT` environment variable when calling the releases:

https://github.com/meilisearch/MeiliSearch/blob/23ccf4429ebbaf250c5eb875d6365b7f6a85a6f9/download-latest.sh#L74
```bash
curl -H "Authorization: $GITHUB_PAT" -s 'https://api.github.com/repos/meilisearch/MeiliSearch/releases' > "$temp_file" || return 1
```
- Add a comment in the script to explain the `GITHUB_PAT` can be set as env var. The scope of the GitHub token should be at least the `user` scope. Cf the [GitHub OAuth scopes](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps).

**Comment by bidoubiwa** [comment]
Additional comments have been added to the script to find latest release version (and not to download). Maybe this comment can help as a base to the person taking charge of this issue: 

```sh
#!/bin/sh

# This script is used in the SDK CIs to fetch the latest MeiliSearch release name (ex: v0.16.0).
# The MeiliSearch latest version is needed to ensure the version that is downloaded is the latest one.
# The access token ($1) is provided as the first arg of the script: ./latest_release_meilisearch.sh my_token
# The personal access token should have access to the user email.
# See https://docs.github.com/en/rest/guides/basics-of-authentication#checking-granted-scopes


temp_file='temp_file' # temp_file needed because `grep` would start before the download is over

curl -H "Authorization:  $1" -s 'https://api.github.com/repos/meilisearch/MeiliSearch/releases' > "$temp_file" -i
latest_ms_release=$(cat "$temp_file" \
    | grep -E 'tag_name' | grep 'v0' | head -1 \
    | tr -d ',"' | cut -d ':' -f2 | tr -d ' ')
rm -rf "$temp_file"
echo "$latest_ms_release"
exit 0
```

**Comment by Flodur871** [comment]
Can I work on this?

**Comment by curquiza** [comment]
Hello @Flodur871! Yes you can feel free to open a PR, thank you 🙂
