### ISSUE TITLE
Download MeiliSearch binary with cURL on a M1 Apple

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/MeiliSearch#1661]
**Describe the bug**
When trying to install MeiliSearch with cURL, it failed with the following ERROR:
ERROR: MeiliSearch binary is not available for your OS distribution or your architecture yet.
Yet when I used homebrew everything worked well.

**To Reproduce**
```
curl -L https://install.meilisearch.com | sh
./meilisearch
```
with an Apple M1 computer

**Screenshots**
<img width="1387" alt="Capture d’écran 2021-09-01 à 14 52 20" src="https://user-images.githubusercontent.com/2602288/131674472-082ed1e8-5768-4339-89c3-00c298400942.png">

**Comment by curquiza** [comment]
We should make the script work for Mac M1 since the binary does work for this OS and this architecture.
I put it as a `good first issue` 🙂
