### ISSUE TITLE
Replacing pest with nom

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#1687]
The pest dependency we use to parse the our filter expression has been unmaintained for a while, and the fix made in our dependency tree by #1659, I think we need a more long term solution for parsing our syntax. I have fiddled a bit with https://github.com/Geal/nom today and made a mvp that parse our syntax correctly. It still lacks error handling, but it is a good basis to replace pest with nom whenever we have some time.

here is a gist with the parser: https://gist.github.com/MarinPostma/78454ea2bc8a18b5707ab81248a8f0a7

---

TODO
- [x] Merge https://github.com/meilisearch/milli/pull/400
- [x] Release milli
- [x] Integrate the new milli release as MeiliSearch dependency

**Comment by curquiza** [comment]
We are really welcoming to contributions for this one! :)

**Comment by CNLHC** [comment]
I have posted a WIP PR (https://github.com/meilisearch/milli/pull/358) which introduces nom parser into milli and passes all the unit tests locally.  I am still working on the better error handling.

I am interested in doing this work and will greatly appreciate it if you kindly give me some feedback

**Comment by curquiza** [comment]
Thank you very much @CNLHC, be sure we will!

**Comment by CNLHC** [comment]
Since https://github.com/meilisearch/milli/pull/358 is merged, I believe this issue can be closed.

**Comment by irevoire** [comment]
Not now !
We still need to create a new release of milli and use it in MeiliSearch. And since https://github.com/meilisearch/milli/pull/358 was breaking we still have a bit of works 😁

**Comment by irevoire** [comment]
@CNLHC, the release is done. Do you want to bump milli from meilisearch?

**Comment by curquiza** [comment]
I updated the issue, a new PR and a new release of Milli are needed
