### ISSUE TITLE
Handle CSV format

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1691]
Sub issue of https://github.com/meilisearch/MeiliSearch/issues/1593

⚠️ All the implementation details are available in this [section of the specification](https://github.com/meilisearch/specifications/blob/develop/text/0028-indexing-csv.md). Please take a look before starting the implementation.

---

## Basic behavior 

When adding or updating documents (`POST/PUT /indexes/:uid/documents`), MeiliSearch should accept the `Content-Type: text/csv` and the corresponding data should be sent in CSV format.
Cf [this part in the spec](https://github.com/meilisearch/specifications/blob/develop/text/0028-indexing-csv.md#api-endpoints)

The formatting rules for CSV accepted by MeiliSearch are described [here in the spec](https://github.com/meilisearch/specifications/blob/develop/text/0028-indexing-csv.md#csv-formatting-rules).

## Error handler

Also related to [this issue](https://github.com/meilisearch/MeiliSearch/issues/1665)

⚠️ All the errors are sent synchronously

List of expected errors related to the behavior:
  - Omitted `Content-Type` header will lead to a `415 Unsupported Media Type` - `missing_content_type` error code.
  - Sending an empty `Content-Type` will lead to a `415 Unsupported Media Type` - `invalid_content_type error` code.
  - Sending a different `Content-Type` than `application/json`, `application/x-ndjson` or `text/csv` will lead to `415 Unsupported Media Type` -  `invalid_content_type` error code.
  - Sending an empty payload will lead to a `400 Bad Request` - `missing_payload` error code.
  - Sending a different payload type than the `Content-Type` header should return a 400 Bad Request - `malformed_payload` error code.
  - Sending a payload excessing the limit will lead to a `413 Payload Too Large` - `payload_too_large` error code.
  - Sending an invalid CSV format will lead to a `400 bad_request` - `malformed_payload` error code. 

The expected implementation of the different error:

### `missing_content_type`

HTTP Code: `415 Unsupported Media Type`

```json
{
    "message": "A Content-Type header is missing. Accepted values for the Content-Type header are: :contentTypeList",
    "code": "missing_content_type",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#missing_content_type"
}
```

### `invalid_content_type`

HTTP Code: `415 Unsupported Media Type`

```json
{
    "message": "The Content-Type :contentType is invalid. Accepted values for the Content-Type header are: :contentTypeList",
    "code": "invalid_content_type",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_content_type"
}
```

### `missing_payload`

HTTP Code: `400 Bad Request`

```json
{
    "message": "A :payloadType payload is missing.",
    "code": "missing_payload",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#missing_payload"
}
```

### `malformed_payload`

HTTP Code: `400 Bad Request`

```json
"message": ":syntaxErrorHelper. The :payloadType payload provided is malformed.",
"code": "malformed_payload",
"type": "invalid_request",
"link": "https://docs.meilisearch.com/errors#malformed_payload"
```

**Comment by ozgurhangisi** [comment]
Hello,

Is it possible to add gzip compressed csv files with Content-Encoding: gzip header to increase transfer speed ? Also we can use gzip to transfer other formats like json, ndjson etc...

**Comment by gmourier** [comment]
Hello @ozgurhangisi 👋

This is something we want to add in the future 😇 

We've added a discussion in our product repository https://github.com/meilisearch/product/discussions/227

**Comment by ozgurhangisi** [comment]
@gmourier Thank you so much for your fast response. 

It will be great feature for us to implement Meilisearch faster. Because we store our product information in aws s3 with gzipped csv format. So we have to unzip and convert the data to json each time before we transfer the product data. 

So csv+gzip features give ability to transfer product data directly to meilisearch and implement faster for lots of people.

**Comment by MarinPostma** [comment]
@gmourier, @curquiza I have just noticed that the error payloads are using a new umimplemented format. The actual error payloads will look like this:

```
{
  "message": "A Content-Type header is missing. Accepted values for the Content-Type header are: \"application/json\", \"application/x-ndjson\", \"test/csv\"",
  "errorCode": "missing_content_type",
  "errorType": "invalid_request_error",
  "errorLink": "https://docs.meilisearch.com/errors#missing_content_type"
}
```

**Comment by gmourier** [comment]
@MarinPostma Yes, this format will come with https://github.com/meilisearch/specifications/pull/61 in the future. I've kept the next format for the example. This is expected to have the format you describe here for v0.23!
