### ISSUE TITLE
Freeze during indexation

### ISSUE THREAD

**Issue by esmultivac** [meilisearch/meilisearch#1708]
Sometimes Meilisearch 0.22 marks one index with isIndexing = true but there are no updates pending on that index queue. Problem is that when I send updates to that index or others it seems to be unable to process them, probably because it thinks it's already processing an update.

The workaround to this problem is to shut down Meilisearch, delete all updates, processed or not, and restart it.

**Comment by curquiza** [comment]
Hello @esmultivac 

Thanks for your report!

> Problem is that when I send updates to that index or others it seems to be unable to process them

Can you detail what you mean by "unable to process them". Do you get any errors in the logs, in the updates? Does it freeze? Can you give us step to reproduce your context so that we can fix it? :)

**Comment by esmultivac** [comment]
It freezes. Nothing seems to be happening. RAM consumption is lower after we restart, but I don't know if it means something.

I can't help you reproduce the error because it happens in our production environment with LOTS of documents in the indexes. We have four indexes, the two bigger ones having 1 million a 600.000 documents.

**Comment by curquiza** [comment]
Hum, ok! Might be related to this https://github.com/meilisearch/MeiliSearch/issues/1555
I hope 🤞

**Comment by esmultivac** [comment]
I know. Just wanted you to be alert. If it helps, I found out that after banning our users from searching with a big offset option, the problem hasn't happened again. I suspect that it happened in the first time because Meilisearch was too busy attending hard and slow queries, but of course you are the ones that know if that makes sense or not.

**Comment by curquiza** [comment]
Thanks @esmultivac 

Sorry for the delay, I close this issue in favor of this one: https://github.com/meilisearch/meilisearch/issues/2133
