### ISSUE TITLE
Unable to add documents that contain colon character in the id field. 

### ISSUE THREAD

**Issue by Jure-BB** [meilisearch/MeiliSearch#1709]
If a document with a colon character ":" is added, operation succeeds without errors, but the document is not present in the index when checked with mini-dashboard. 

A sample to reproduce the error:
```
public class Book
{
    public string  Id    { get; set; }
    public string  Title { get; set; }
}

[Test]
public async Task Colon_bug_test()
{
    var client  = new MeilisearchClient("http://localhost:7700");
    var indexes = await client.GetAllIndexes();
    var indexId = "books_colon";
    if (indexes.Select(x => x.Uid).Contains(indexId))
    {
        await client.DeleteIndex(indexId);
        await Task.Delay(1000);
    }

    var index = await client.CreateIndex(indexId);

    for (int i = 0; i < 10; i++)
    {
        var documents = Enumerable.Range(0, 200)
           .Select(j => new Book { Id = $"{i}:{j}", Title = "Le Book" })
           .ToArray();
        var result = await index.AddDocuments<Book>(documents);
    }
}
```

I expect documents to be visible in the mini-dashboard, but they aren't. 

**MeiliSearch version:** v0.22.0 & **meilisearch-dotnet** client.

**Comment by curquiza** [comment]
Hello @Jure-BB!

The id of your document should not contain `:` character. Only `A-Z a-z 0-9` and `-_` characters are accepted to avoid URL encoding issues. [see the related documentation](https://docs.meilisearch.com/learn/core_concepts/documents.html#document-id) 🙂

**Comment by Jure-BB** [comment]
Oh, I totally missed that. Thank you for an explanation. I'm closing this then.
