### ISSUE TITLE
Adding an empty array of documents, breaks the index primaryKey

### ISSUE THREAD

**Issue by khash** [meilisearch/MeiliSearch#1728]
I've come across this issue with a pure Ruby client but please see below for a CURL reproduction steps.

(in this example `index = client.index('acme')`)

1. Add some docs `index.add_documents([{id: "foo"}, {id: "bar"}])`
2. Add an empty array `index.add_documents([])`

This will break the index in a way that while the API returns the documents correctly with `/indexes/acme/documents`, doing a `GET` on `/indexes/acme/documents/foo` returns a 404.

This means if you run the first line again (add docs), you will end up with duplicates.

This is caused by adding an empty array. Here is how you can reproduce it with only CURL on a clean setup:

```bash
$ curl -X POST http://localhost:7700/indexes/acme/documents --data '[{"id": "foo"}, {"id":"bar"}]'

$ curl http://localhost:7700/indexes/acme/documents/foo
{"id":"foo"}

$curl -X POST http://localhost:7700/indexes/acme/documents --data '[]'

$curl http://localhost:7700/indexes/acme/documents/foo
{"message":"Document with id foo not found.","errorCode":"document_not_found","errorType":"invalid_request_error","errorLink":"https://docs.meilisearch.com/errors#document_not_found"}
```

All the while, `curl http://localhost:7700/indexes/acme/documents` returns the correct set of documents which makes things very confusing.

**Comment by ManyTheFish** [comment]
This bug seems to be related to #1716, this should be fixed in the next release of Meilisearch.
If your bug is not fixed by the next release, don't hesitate to reopen it, Thanks @khash for your report 👍 

Closing in favor of #1716.
