### ISSUE TITLE
The mini-dashboard does not work anymore

### ISSUE THREAD

**Issue by irevoire** [meilisearch/MeiliSearch#1750]
**Describe the bug**
The mini dashboard does not work anymore.

**To Reproduce**
Steps to reproduce the behaviour:
1. `cargo run`
2. Open your browser on `localhost:7700`

**Expected behaviour**
It works

**Screenshots**
![image](https://user-images.githubusercontent.com/7032172/135531091-5ce938ef-5ebf-485e-8c18-2beec258e1b6.png)

**MeiliSearch version:** main

**Comment by ppamorim** [comment]
I have the same issue.

**Comment by anirudhRowjee** [comment]
Hi! I'd love to give this issue a shot.

**Comment by curquiza** [comment]
Hello @anirudhRowjee! Thank you 😊

**Comment by anirudhRowjee** [comment]
Alright! I appear to have a fix at hand, but I've got no clue why it works as it does.
Here's how I investigated it - 
1. Ran the test suite, all of which passed once I changed the file limit.
2. Investigated the debug built output at `/meilisearch-http/target/rls/debug/build/meilisearch-http-a6e2793cb../out/mini-dashboard/`. At this point, I used the npm package `serve` to run a temporary web server here, which served all files correctly. This confirmed my initial suspicion that it wasn't a problem with the dashboard itself, but rather with how it was being served.
3. Looked into how the server was setup. At this point I used simple print debugging to ensure that the paths were generated correctly, along with their MIME types. All seemed to be in order. I also tried using `format!` to prepend a slash onto the file path, but this didn't make too much of a difference. 
4. At this point I noticed that the `index.html` file was the only file being served correctly, which used 
```rust
                config.service(web::resource("/").route(
                    web::get().to(move || HttpResponse::Ok().content_type(mime_type).body(data)),
                ));
```
as opposed to

```rust
                scope = scope.service(web::resource(path).route(
                    web::get().to(move || HttpResponse::Ok().content_type(mime_type).body(data)),
                ));
```

Given I'm not too familiar with Actix, I took the approach of registering the routes for the static files the same way as the `index.html` file, replacing the above block with the following to serve static files - 

```rust
                config.service(web::resource(path).route(
                    web::get().to(move || HttpResponse::Ok().content_type(mime_type).body(data)),
                ));
```

This works! `localhost:7700` now produces the dashboard properly.

![Screenshot from 2021-10-02 10-44-46](https://user-images.githubusercontent.com/42117791/135704477-c39912c1-78f6-4b7b-aa0b-aecfb06f86fd.png)

I would love to open a PR, and hear your feedback on what I can do better! Thank you :smile: 

(PS This compiles with warnings to remove the unused `scope` variable.)

**Comment by anirudhRowjee** [comment]
Running `cargo test` passes in `meilisearch-http`, but running it outside of that in the main folder leads to the following errors. Do I need to switch to Nightly for it to compile?
![Screenshot from 2021-10-02 11-37-25](https://user-images.githubusercontent.com/42117791/135705715-f2c09158-7461-489e-8c59-eb904cf28b4f.png)

**Comment by Kerollmops** [comment]
Hey @anirudhRowjee,

Thank you very much for this detailed debugging, I will let @MarinPostma look at your PR as I am not familiar with Actix either. For the compilation error, you can just `rustup update` as the [`array::map`](https://doc.rust-lang.org/stable/std/primitive.array.html#method.map) has been stabilized in 1.55 🚀 

Thank you again!

**Comment by rishit-khandelwal** [comment]
Is this issue fixed? If not can i work on it?

**Comment by anirudhRowjee** [comment]
I've opened a PR! Thank you for your patience.
