### ISSUE TITLE
Provide Docker image as non root

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1757]
### Discussed in https://github.com/meilisearch/MeiliSearch/discussions/1756

<div type='discussions-op-text'>

<sup>Originally posted by **igaul** October  1, 2021</sup>
Hi, 
I'd like to request the official docker image run with a non root user, so the final image of Dockerfile would be something like this (what I am using)

`# Run
FROM    alpine:3.14

ARG     USER=meiliuser
ENV     HOME /home/$USER
ENV     MEILI_HTTP_ADDR 0.0.0.0:7700

# download runtime deps as root and create $USER
RUN apk add -q --no-cache libgcc tini curl \
    && adduser -D $USER
WORKDIR $HOME
USER $USER
# copy file as $USER to $HOME
COPY  --from=compiler /meilisearch/target/release/meilisearch .

EXPOSE  7700/tcp

CMD ["tini", "--","./meilisearch"]`

If interested, I would be happy to pr. Have a good weekend!

</div>

**Comment by spinales** [comment]
@curquiza  I'll do, please assign it to me.

**Comment by xvilo** [comment]
As the change has been reverted (in https://github.com/meilisearch/meilisearch/pull/2032), can we re-open this issue? We would like to run Meilisearch on our Kubernetes cluster. Unfortunately we don't allow running images as a root user. Manually setting the `securityContext` to overrides this results in a `Error: Permission denied (os error 13)` error. 

This feature would be highly appreciated

**Comment by K2ouMais** [comment]
Hello everyone, we are having exatcly the same issue in kubernetes.

We dont allow any pod to run as root and so I wanted to ask if there is any solution for this?

Thanks in advance.

**Comment by rtmzshw** [comment]
did any one find a solution? same problem here
