### ISSUE TITLE
Reduce binary size

### ISSUE THREAD

**Issue by irevoire** [meilisearch/MeiliSearch#1782]
We have really large binary (~300MB), with #1781 we'll reduce our binary size to ~50MB. And I was thinking we could also use [`upx`](https://upx.github.io/) to reduce our binary size even more.
Basically, what `upx` is compressing your binary and shipping an “uncompressor” with it. 
And here is what happens when you execute your binary:
1. The binary gets loaded in the RAM by the OS
2. `upx` uncompress the binary in place => no memory is lost
3. Meilisearch is executed
=> we should see no performance impact at all at runtime. But the binary would be a little bit slower to start

----------------------------

We don't want to strip our binary though since we would then lose the ability to see where a panic occurred.

I would like to use this action:
https://github.com/svenstaro/upx-action

@MarinPostma and @Kerollmops do you think it's a good idea?

**Comment by MarinPostma** [comment]
Have you any idea how much that would shave off?

**Comment by irevoire** [comment]
Oops look like upx is _always_ stripping the binary even with the option `strip-relocs=0`. So it's a no-go for us actually.
