### ISSUE TITLE
Sort not working with searchquery in POST search

### ISSUE THREAD

**Issue by soolace** [meilisearch/MeiliSearch#1810]
**Describe the bug**
When the Searchquery has a Value, the sort doesn't work correctly. 
{
    "q": "invest",
    "sort": ["company:asc"]
}

But when it's empty, it works.
{
    "q": "",
    "sort": ["company:asc"]
}

**To Reproduce**
Visible with postman or in the application

**Expected behavior**
The Sorting should work, regardless if a searchquery is sent or not. 
I can't see any error or something else, the request works fine, also with filtering.
Just the output is not what I expected. 

**MeiliSearch version:** 
v0.23.1

**Comment by curquiza** [comment]
> But now I realize that it's probably because of the ranking rule of MeiliSearch, right?

Yes it is! 🙂 Glad the doc helps you find the solution!

@gmourier since it's a user feedback, I ping you! 😇 

Closing the issue then!
