### ISSUE TITLE
Cannot spawn Arbiter's thread: "actix-rt|system:0|arbiter:56"

### ISSUE THREAD

**Issue by Aniket-IN** [meilisearch/MeiliSearch#1823]
### Discussed in https://github.com/meilisearch/MeiliSearch/discussions/1821

<div type='discussions-op-text'>

<sup>Originally posted by **Aniket-IN** October 16, 2021</sup>
Hi, I'm new to MeiliSearch, 
I got MeiliSearch up and running on my local machine, it works great. 

```
Database path:          "./data.ms"
Server listening on:    "http://127.0.0.1:6002"
Environment:            "development"
Commit SHA:             "2e2eeb0a424408e27f4223e58afec303c53e1419"
Commit date:            "2021-10-12T14:47:06+00:00"
Package version:        "0.23.1"
```
But when I tried to setup on the server (Linux), its returning this error. 
```
[2021-10-16T15:10:02Z INFO  actix_server::builder] Starting 64 workers
thread 'main' panicked at 'Cannot spawn Arbiter's thread: "actix-rt|system:0|arbiter:56". Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.2.0/src/arbiter.rs:154:17
```

I have no clue, What's wrong, I have tried changing the port but still same :(

Tho my `data.ms` folder is generated successfully. I think only the web server failing to start.  

Any help would be appreciated..
Thanks in advance :)</div>

**Comment by Aniket-IN** [comment]
> Hello @Aniket-IN 
> Can you try to remove the `data.ms` folder, start MeiliSearch again, and re-import your data? Sorry for the inconvenience 😕

Hi @curquiza , 
That is the first thing I tried but no luck :(

**Comment by curquiza** [comment]
Closing this issue since it's old, feel free to reopen if you or someone else still have the issue of course with the [latest version of MeiliSearch](https://github.com/meilisearch/MeiliSearch/releases).
