### ISSUE TITLE
Empty _matchesInfo if attribute is not retrieved

### ISSUE THREAD

**Issue by remram44** [meilisearch/MeiliSearch#1825]
**Describe the bug**
`"matches": true` doesn't work if the attribute is not included in `"attributesToRetrieve"`

The documentation for `"attributesToHighlight"` mentions:

> If a different type of highlighting is desired, we recommend the matches parameter, which provides much finer control over the output.

However there is little control if I am forced to retrieve the full document from MeiliSearch before I can discard it and do my own highlighting.

**To Reproduce**
1. Do any search with `"attributesToRetrieve": [], "matches": true`

**Expected behavior**
If I set `"matches": true` then `"_matchesInfo"` is returned.

**Screenshots**

**MeiliSearch version:** `0.23.1`

**Comment by curquiza** [comment]
Hello @remram44 

The `attributesToRetrieve` list is the attributes you want to display, so to retrieve, in your search result. 
`matches` is an option to inform about the matching part in the attribute.

What is your use case if you don't want to retrieve the attribute but you want to get the matching part? 🙂

**Comment by curquiza** [comment]
Thanks for opening this issue then! :)

I've created a discussion in the `product` repository where our product team works: https://github.com/meilisearch/product/discussions/280

We are sorry you encountered bugs with MeiliSearch! We would appreciate reading the other issues or feedback you have regarding MeiliSearch.

In the meantime, the current problem of this issue can be solved by adding the attributes on which you want to apply `matches` in `attributesToRetrieve` as well. By default, MeiliSearch considers all the attributes are retrievable if you don't fill the `attributesToRetrieve` option.

**Comment by curquiza** [comment]
Closing this issue since a ticket is open on the product side
Feel free to open an issue for any other problem you will encounter.
