### ISSUE TITLE
Cannot update settings against meilisearch v0.23.1

### ISSUE THREAD

**Issue by agentabstract** [meilisearch/MeiliSearch#1839]
**Describe the bug**
When I update settings the way I did v0.20 the settings do not actually update on the server or give me an error. 

**To Reproduce**
```go
index, err:=client.GetIndex(IndexName)
	if err != nil{
		return err
	}
	settings, err:= index.GetSettings()
	if err != nil{
		return err
	}
	settings.SearchableAttributes = []string{"name","titles","keywords","content","attachments","date"}
	settings.FilterableAttributes = []string{"type"}
	settings.StopWords = StopWords
	settings.RankingRules = []string{"exactness","words", "attribute","desc(boost)","desc(date)","wordsPosition","proximity", "typo"}
	_, err = index.UpdateSettings(settings)
	if err != nil{
		return err
	}
	index, err=client.GetIndex(IndexName)
	if err != nil{
		return err
	}
	settings, err= index.GetSettings()
	if err != nil{
		return err
	}
	log.Println(fmt.Sprintf("%+v", settings))
```

**Expected behavior**
The settings would update.

The result I get is: 
```
&{RankingRules:[words typo proximity attribute sort exactness] DistinctAttribute:<nil> SearchableAttributes:[*] DisplayedAttributes:[*] StopWords:[] Synonyms:map[] FilterableAttributes:[] SortableAttributes:[]}
```

**MeiliSearch version:** [e.g. v0.23.1]

**Comment by agentabstract** [comment]
Yes.  I just did that,  after I found the issue.  It is saying status: failed,  but no error message. What I realized after submitting the ticket was that the ranking rules aren't the same anymore.  I had: 
`settings.RankingRules = []string{"exactness","words", "attribute","desc(boost)","desc(date)","wordsPosition","proximity", "typo"}`

and the new format is: 
`settings.RankingRules = []string{"exactness","words", "attribute","boost:desc","date:desc","proximity", "typo"}`

It should still throw some sort of error though. But not necessarily broken anymore.

**Comment by curquiza** [comment]
So, Is it ok now for you? 🙂

The error message is visible using the update status route I linked, MeiliSearch processes settings and documents asynchronous:
- https://docs.meilisearch.com/learn/advanced/asynchronous_updates.html#which-operations-are-async
- https://docs.meilisearch.com/faq.html#i-did-a-call-to-an-api-route-and-i-only-got-an-updateid-as-a-response-what-does-it-mean
