### ISSUE TITLE
Accept `charset` in `Content-Type` header

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1866]
Replaces https://github.com/meilisearch/MeiliSearch/issues/1791

After discussion with the team, we want to permit `charset` in the `Content-Type` header for the routes requiring a body, so a `Content-Type` header.

### Reminder

The following routes should only accept `application/json` in this header and not `text/csv` or `application/x-ndjson`
- `POST indexes/`
- `PUT indexes/:uid`
- `POST indexes/:uid/documents/delete-batch`
- `POST indexes/:uid/search`
- `POST indexes/:uid/settings`
- all the sub-settings routes like `POST indexes/:uid/settings/XXX`

The following routes can accept `application/json`, `text/csv` or `application/x-ndjson`
- `PUT indexes/:uid/documents`
- `POST indexes/:uid/documents`

**Comment by gmourier** [comment]
Fixed by #1933
