### ISSUE TITLE
Make `matches` work with numerical value

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1883]
Since v0.24.0, and since this issue is done (https://github.com/meilisearch/MeiliSearch/issues/1758) MeiliSearch can apply highlight on numerical fields.

But this does not work when using `matches`.

Example

- With this document:

```json
[
  { "id": 1, "title": "Pride and Prejudice", "price": 3.5 }
]
```

- And this search

```json
{
    "q": "3",
    "attributesToHighlight": ["*"],
    "matches": true
}
```

Current behavior:

```json
{
    "hits": [
        {
            "id": 1,
            "title": "Pride and Prejudice",
            "price": 3.5,
            "_formatted": {
                "id": "1",
                "title": "Pride and Prejudice",
                "price": "<em>3</em>.5"
            },
            "_matchesInfo": {}
        }
    ],
    "nbHits": 1,
    "exhaustiveNbHits": false,
    "query": "3",
    "limit": 20,
    "offset": 0,
    "processingTimeMs": 0
}
```

Expected behavior:

```json
{
    "hits": [
        {
            "id": 1,
            "title": "Pride and Prejudice",
            "price": 3.5,
            "_formatted": {
                "id": "1",
                "title": "Pride and Prejudice",
                "price": "<em>3</em>.5"
            },
            "_matchesInfo": {
                "price": [
                    {
                        "start": 0,
                        "length": 1
                    }
                ]
            }
        }
    ],
    "nbHits": 1,
    "exhaustiveNbHits": false,
    "query": "3",
    "limit": 20,
    "offset": 0,
    "processingTimeMs": 0
}
```

This change should be done in this file: https://github.com/meilisearch/MeiliSearch/blob/main/meilisearch-lib/src/index/search.rs

🔥 Tests should be added 🔥

**Comment by Thearas** [comment]
Hi @curquiza, I‘’m interested in Meilisearch and I'd like to take this issue if no one else is currently working on it.

**Comment by curquiza** [comment]
Hello @Thearas 

Thanks for your interest in this project :)

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 🙂

**Comment by curquiza** [comment]
I ping the @meilisearch/docs-team because I'm not sure, but it could impact the docs. I let you check 😇
