### ISSUE TITLE
Refactoring: have one file for docker image CI instead of two

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#1901]
⚠️ Should be done once https://github.com/meilisearch/MeiliSearch/pull/1897 is merged

We should find a way to have only one file related to the docker image CI instead of two, for maintenance reasons.

Here are the current files:
- https://github.com/meilisearch/MeiliSearch/blob/main/.github/workflows/publish-docker-latest.yml: publish the git tag as docker tag
- https://github.com/meilisearch/MeiliSearch/blob/main/.github/workflows/publish-docker-tag.yml: publish the `latest` tag

-> The CI logic should be handled in one file only.

**Comment by thedanvail** [comment]
Is this issue still open or was it addressed in #1897 ?
