### ISSUE TITLE
[ARMv8] About removing the old ARMv8 workflow and naming for the binary

### ISSUE THREAD

**Issue by patrickdung** [meilisearch/meilisearch#1909]
So, [the new GH workflow](https://github.com/meilisearch/MeiliSearch/blob/main/.github/workflows/publish-crossbuild.yml) could build the aarch64 linux binary in shorter time for the new 0.24 release.
Currently the binary is meilisearch-linux-aarch64.
[Here's Original PR](https://github.com/meilisearch/MeiliSearch/pull/1811)

Here's some discussion:
1) Removing [the old workflow](https://github.com/meilisearch/MeiliSearch/blob/main/.github/workflows/publish-binaries.yml#L40-L64) for aarch64 linux binary (meilisearch-linux-armv8)

2) Should we update the new workflow to generate binary name as meilisearch-linux-armv8?
If not we would need to update the script 'download-latest.sh' for the correct binary name.

Thanks.

**Comment by curquiza** [comment]
Hello @patrickdung! Thanks for this issue.

- [ ] I would have a definitive confirmation from our raspbian users: is the `meilisearch-linux-aarch64` works on their raspberry for example? @kappa-wingman if you are around 😇 
- [ ] If the first point is validated, we also need to update the `download-latest.sh` script

I'll update your issue description :)

**Comment by kappa-wingman** [comment]
@curquiza

I use MeiliSearch with ARM processor with a cloud computing provider, it runs RHEL 8. The v0.24.0 binary works for my case. So you need to find someone using the Raspberry Pi 🍓 to confirm.

**Comment by curquiza** [comment]
Thanks for your answer @kappa-wingman and sorry for the miss-understanding

However, does the [`meilisearch-linux-aarch64`](https://github.com/meilisearch/MeiliSearch/releases/download/v0.24.0/meilisearch-linux-aarch64) work on this machine? Not the `meilisearch-linux-armv8` binary which is the one you download when using the [`download-latest.sh script`](https://github.com/meilisearch/MeiliSearch/blob/main/download-latest.sh) via this command

```bash
curl -L https://install.meilisearch.com | sh
```

Thanks a lot for your reactivity.

**Comment by kappa-wingman** [comment]
@curquiza , I am using the meilisearch-linux-aarch64 (0.24.0 from the release page)and works on the ARM machine.
The first testing about the new binary is in [last month] (https://github.com/meilisearch/MeiliSearch/discussions/1790).

**Comment by curquiza** [comment]
Thank you very much @kappa-wingman for your feedback!

**Comment by bb** [comment]
I'm not sure if this is the right ticket to jump on, but I noticed that the image tagged getmeili/meilisearch:v0.24.0 does NOT run with Docker Desktop for Mac with Apple Silicon (while it runs fine on x86).

I tried the test image by @tpayet (meilisearch:test-arm2) and it runs on Docker Desktop for Mac with Apple Silicon.

It would be great if you could publish images to docker with arm64 arch.
BTW, I've seen others using arm64/v8 (and additionally providing 32 bit binaries), e.g. https://hub.docker.com/_/redis?tab=tags. As 32 bit is not really a topic for Meili, I don't know if it makes a difference.

Regarding Apple Silicon Macs in general: has anybody here looked into arm64**e**? The additional features like javascript type conversion speed up parsing JSON of input documents. Researching if/how this works within Docker, I stumbled across https://hub.docker.com/r/joseluisq/rust-linux-darwin-builder.

**Comment by curquiza** [comment]
Hello @bb 😄 

> I'm not sure if this is the right ticket to jump on, but I noticed that the image tagged getmeili/meilisearch:v0.24.0 does NOT run with Docker Desktop for Mac with Apple Silicon (while it runs fine on x86).

That's normal, this will be available for v0.25.0. It's not available for v0.24.0

**Comment by curquiza** [comment]
`v0.25.0rc0` should work for you @bb ;)

**Comment by bb** [comment]
Thank you, will try as soon as I get the time to adapt to the breaking changes. I'm running getmeili/meilisearch:test-arm2 successfully since two weeks.
