### ISSUE TITLE
Phrase search doesn't return existing document

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/MeiliSearch#1913]
**Describe the bug**
Phrase search doesn't return existing document

**To Reproduce**
1. Download and launch v0.24 of MeiliSearch
2. Add the movies dataset provided in the documentation
3. Search for "the path of Fallon" without quotes
4. A document with this sentence in the description is returned (movie name: Judgment Night)
5. Search this time with the same query surrounded by quotes (phrase search)
6. No results

**Expected behavior**
The document with the matching query words should be returned

**Screenshots**

<img width="1045" alt="Capture d’écran 2021-11-18 à 12 31 30" src="https://user-images.githubusercontent.com/48251481/142407694-62ad222b-2c5a-4977-bced-49db9432fc42.png">

<img width="936" alt="Capture d’écran 2021-11-18 à 12 31 43" src="https://user-images.githubusercontent.com/48251481/142407892-1b2ee190-0db9-48f6-a779-eff5036a6e2d.png">

**MeiliSearch version:** 
v0.24

**Additional context**
Additional information that may be relevant to the issue.
macOS

**Comment by curquiza** [comment]
Hello @CaroFG!

Thanks for the report. Looks like the phrase search does not work with more than 3 words.
This is indeed a bug, we will do our best to fix it for v0.25.0!

@meilisearch/core-team 🔥 we should add tests (probably on milli's side 🔥

**Comment by CaroFG** [comment]
It works when I search for "the four become his unwilling prey" (same movie, another part of the overview)...

**Comment by curquiza** [comment]
So weird... thanks for this!

**Comment by curquiza** [comment]
For people wanting a perfect working phrase search, use v0.21.0 in the meantine.

**Comment by ManyTheFish** [comment]
Reopen this issue because it is not fix in meilisearch but only in milli.

**Comment by alfonsrv** [comment]
Having a similar issue; searching for a single, distinct word e.g. `"PCS5581337"` doesn't return/find all documents with that content.

It returns *some*. Looking at the document contents for returning and non-returning documents, they seem to be structured very similarly, both having the search phrase as a standalone word of the list/array. Can provide more in-depth details if required.

**Comment by gmourier** [comment]
Hi @alfonsrv. Your description makes me think of this bug too. The next release should fix it. You will be able to test it in advance when the release candidate is out. If all goes well, it should happen next week!

**Comment by curquiza** [comment]
Fixed when milli has been updated, so in #1796

**Comment by alfonsrv** [comment]
@gmourier I actually realized I'm on `meilisearch-http 0.22.0` judging by the Docker executable `/meilisearch -V` fyi

Will wait for v0.25 to be released on Dockerhub and then report back.

**Comment by curquiza** [comment]
Hello @alfonsrv, the first RC of v0.25.0 is out if you want to test :) https://github.com/meilisearch/MeiliSearch/releases/tag/v0.25.0rc0

**Comment by francoism90** [comment]
@curquiza Any ETA on when a new release would be possible?

I'm going to try the new RC, ty. :)

**Comment by curquiza** [comment]
@francoism90 
v0.25.0 will be released next week!
Let us know if the RC works as you expect!

**Comment by alfonsrv** [comment]
Hard to get reproducible results since the index has to be recreated, but so far it works as expected aka no missing documents were noticed.

**Comment by francoism90** [comment]
@curquiza I did tried the RC, but it doesn't seem to work with the current Laravel Scout driver?

**Comment by curquiza** [comment]
The RCs are the release candidate versions, so not the official releases. It means our integrations are not up-to-date with the RCs.
It currently does not work with the laravel scout driver because the latest version of [meilisearch-php](https://github.com/meilisearch/meilisearch-php) you use is only compatible with v0.24.0. The compatible version of meilisearch-php with MeiliSearch v0.25.0 is not released yet.

**Comment by francoism90** [comment]
@curquiza Ok, will you provide a `meilisearch-php` version for next release?

It states the following:
```
This package version is compatible with MeiliSearch v0.24.0 and later, but not with v0.23.1 and older. Be sure you are using at least MeiliSearch v0.24.0 or newer before doing the upgrade.
```
Should I report the issue I've encountered when using it on the RC or should I try the `bump-meilisearch-v0.25.0` branch? :)

**Comment by curquiza** [comment]
> Will you provide a meilisearch-php version for next release?

Yes :)

> Should I report the issue I've encountered when using it on the RC or should I try the bump-meilisearch-v0.25.0 branch first? :)

No need to report the issue. However the `bump-meilisearch-v0.25.0` branch is still in development, not sure you will be able to use it immediately.

**Comment by vdiaz1130** [comment]
Hi, 

I'm not sure if this is related but I'm searching in my categories index for `"men"` and expecting both `"women"` and `"men"` to be returned but am only seeing `"men"`. 

Am I missing something in my configuration? Using `meilisearch: ^0.24.0`.

```
// 
query: {
  q: "men",
  options: {
    offset: null,
    limit: 1000,
    attributesToRetrieve: [
      "*",
    ],
  },
};

client.search(query.q, query.options); // only returns mens category
```

**Comment by francoism90** [comment]
@vdiaz1130 Could you try "*men"?

If I'm not mistaken, this is default behavior, as Meilisearch is more autocomplete searching.

**Comment by vdiaz1130** [comment]
@francoism90 That doesn't seem to work. I tried it on the Meili client as well as in my search field.

**Comment by MarinPostma** [comment]
@francoism90 globbing like that is not supported by MeiliSearch

@vdiaz1130 unfortunately, MeiliSearch only supports prefix search, not suffix/infix search, so women is not matched by men

Hope that helps
