### ISSUE TITLE
Empty index with primary key update inconsistency

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1927]
**Describe the bug**
In the following very niche case: 
- Index exists
- Primary key has been set
- No documents are indexed

When I update the `searchableAttribute` settings in this case, the `update` comes back as `processed` when it hasn't been processed yet. 

**To Reproduce**
1. Create index
2. Set primary key to ID
3. Update `searchableAttributes` settings
4. Watch updates
5. The `processed` status of the update is given back before the changes are applied to the settings

**Expected behavior**
Update status should be processed only when changes have been applied

**Screenshots**
<img width="769" alt="Screenshot 2021-11-22 at 14 47 12" src="https://user-images.githubusercontent.com/33010418/142873731-bc1b984b-e5da-444b-871a-298a9eb585c4.png">

**MeiliSearch version:** v0.24.0

**Comment by MarinPostma** [comment]
this is an instance of race condition that will be solved by #1796

**Comment by curquiza** [comment]
@bidoubiwa we will need your feedback here about your test suite against `v0.25.0rc0` before closing this issue

**Comment by bidoubiwa** [comment]
It is resolved! Thanks :)
