### ISSUE TITLE
Panic at `segment_analytics.rs`

### ISSUE THREAD

**Issue by Thearas** [meilisearch/MeiliSearch#1940]
**Describe the bug**

I run meilisearch on my macbook and saw a panic in log:

```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', meilisearch-http/src/analytics/segment_analytics.rs:410:30
```

**To Reproduce**

No reproducible.

**MeiliSearch version:**

0.24.0

**Additional context**

macOS arm64

**Comment by gmourier** [comment]
Thanks, @Thearas for the bug report 🙏. It should be fixed for v0.25.0. 🤓
