### ISSUE TITLE
Unicode characters are incorrectly highlighted

### ISSUE THREAD

**Issue by ThePicoNerd** [meilisearch/MeiliSearch#1971]
**Describe the bug**
MeiliSearch seems to fall short of highlighting phrases containing multi-byte unicode characters such as "Hammarskjöld":

![image](https://user-images.githubusercontent.com/17624114/144910446-f3965bf2-c6ad-4f47-a2cd-4394d45d7990.png)

(Note that the last character is not highlighted.)

**To Reproduce**
1. Spin up a MeiliSearch instance.
2. Add the following dataset:
```json
[
  {
    "id": 1,
    "name": "Hjalmar Hammarskjöld"
  },
  {
    "id": 2,
    "name": "Per Albin Hansson"
  },
  {
    "id": 3,
    "name": "Östen Undén"
  },
  {
    "id": 4,
    "name": "Tage Erlander"
  }
]
```
3. Try searching for `Hammarskjöld` or `Undén`.

**Expected behavior**
The whole word should be highlighted (as per the search query).

**Screenshots**

![image](https://user-images.githubusercontent.com/17624114/144911720-0444f05d-4dd4-4056-9194-12fd16f42218.png)

**MeiliSearch version:**
v0.24.0

**Additional context**
I was able to reproduce this issue on my Windows 10 amd64 machine but originally observed it on my Linux boxes.

**Comment by curquiza** [comment]
Hello @ThePicoNerd thanks for the issue
you issue is a duplication of #1460 so I close it! Thanks for your feedback, we will fix this problem at the beginning of 2022
