### ISSUE TITLE
Impossible to get the latest stable version of MeiliSearch.

### ISSUE THREAD

**Issue by benoitxp** [meilisearch/MeiliSearch#1975]
Hi,

I'm trying to install this awesome search engine on a debian 10 system but I get the following error:
Impossible to get the latest stable version of MeiliSearch.

The command I use:
`curl -L https://install.meilisearch.com | sh`

Does someone have advice?
Thanks in advance

**Comment by curquiza** [comment]
Closed by #1976

**Comment by curquiza** [comment]
Not on main yet! I re-open!
