### ISSUE TITLE
Multiple addDocuments triggered on non-existent index fails

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1988]
**Describe the bug**

⚠️ this might be solved with the v0.25.0 but just in case it is still a bug

When running `addDocuments` almost simultaneously on an index that does not exists, all `addDocuments` except the first one throw an `index already exists` error. 

I think this is why: 

<img width="1502" alt="Screenshot 2021-12-08 at 16 16 38" src="https://user-images.githubusercontent.com/33010418/145233752-736377ed-e19e-44c5-a7ee-10eb39817dd4.png">

**To Reproduce**
1. Make multiple async calls that you do now await  to `POST /documents`
2. Errors are thown

**Expected behavior**
Well no throws

**MeiliSearch version:** 0.24.0

**Comment by curquiza** [comment]
Wonderful schema!
@bidoubiwa Can you check it's fixed with v0.25.0?

**Comment by bidoubiwa** [comment]
It's fixes with v0.25.0 !
