### ISSUE TITLE
Data not persisting in Docker Volume

### ISSUE THREAD

**Issue by K2ouMais** [meilisearch/MeiliSearch#1992]
Hello everyone,

I was trying Meilisearch on Laravel Sail with Laravel Scout and I indexed about 2 Million Documents into Meilisearch in about 2 hours.

Just found out, that Data from Meilisearch isnt persisted into the Docker Volume.

Found this the hard way, after restarting my containers, jut to find out the 2 million documents arent there anymore.

This is in the docker-compose file:

```
volumes:
            - 'sailmeilisearch:/data.ms'
```

I took a look into the Meilisearch container and the folder seems to be the one on the docker-compose file.

Why isnt the data not getting persisted? Any idea?

Thanks in advance

**Comment by K2ouMais** [comment]
I just tested some Docker Meilisearch versions and the last one, where my volume works is v0.23.0.

If you want persistence in a Docker volume the best way right now is to download an older version of Meilisearch.

```
docker pull getmeili/meilisearch:v0.23.0
```

Dont know what changed since then.

**Comment by curquiza** [comment]
Hello @K2ouMais,

Sorry for this problem, here is the current issue about this: https://github.com/meilisearch/MeiliSearch/issues/1969

I close this issue since it's a duplication
