### ISSUE TITLE
Inconsistent `nbHits` with different `offset`

### ISSUE THREAD

**Issue by Thearas** [meilisearch/MeiliSearch#1993]
**Describe the bug**
```bash
# offset=0
curl -s -X POST 'http://localhost:7700/indexes/plans/search' -H 'Content-Type: application/json' \
--data-binary '{ "q": "oltp-fun", "offset":0, "filter": [["deletedAt=0"]]}' | jq | rg nbHits
  "nbHits": 51,

# offset=40
curl -s -X POST 'http://localhost:7700/indexes/plans/search' -H 'Content-Type: application/json' \
--data-binary '{ "q": "oltp-fun", "offset":40, "filter": [["deletedAt=0"]]}' | jq | rg nbHits
  "nbHits": 125, # <--- nbHits should be 51
```

**To Reproduce**
I don't known how to reproduce. Only some queries will have this problem and others work fine.

**Expected behavior**
`nbHits` should always be 51.

**MeiliSearch version:**
v0.23.1

**Comment by Kerollmops** [comment]
Hey @Thearas,

MeiliSearch is a lazy search engine, it means that it will try its best to compute the least amount of things to answer user queries as fast as possible. And this is why we use a bucket sort algorithm, a kind of tie-breaking algorithm. This algorithm tries to fetch the minimum amount of documents required to answer the 20 requested documents one for the first ranking rule and gives the documents that are considered equal to the second ranking rule and so on...

For the first query you made there are 51 documents that are fetched by the first ranking rule and this is the value that the engine returns as the `nbHist`, it will not try to fetch more as this would take too much time to fetch more. The second query shows that you offset forced the engine to fetch 125 documents from the first ranking rule.

[We also return a `exhaustiveNbHits` in the response](https://docs.meilisearch.com/reference/api/search.html#response) that indicates if the nbHist is perfect or not. Spoiler alert: it is _never_ exhaustive at the moment. Computing how many documents exhaustively match a query would force the engine to try increasing the number of typos of all of the query words, force it to remove words from the end of the query, etc...

**Comment by gmourier** [comment]
Hey 👋

We opened a product discussion on this topic here https://github.com/meilisearch/product/discussions/335

**Comment by Thearas** [comment]
Thanks for your reply.
