### ISSUE TITLE
No meiliSearch plugin that supports strapi_v4

### ISSUE THREAD

**Issue by andyalex234** [meilisearch/MeiliSearch#1997]
### Discussed in https://github.com/meilisearch/MeiliSearch/discussions/1996

<div type='discussions-op-text'>

<sup>Originally posted by **andyalex234** December 14, 2021</sup>
I wanted to use meilisearch in the new Strapi v4 CMS and when I installed the latest version of meilisearch plugin for strapi, It doesn't work. Are you working on it? When do we get support for the new Strapi version?</div>

**Comment by curquiza** [comment]
Hello @andyalex234 

Thiis not related to MeiliSearch itself. Please follow this issue instead: https://github.com/meilisearch/strapi-plugin-meilisearch/issues/271 🙂
