### ISSUE TITLE
v0.25.0 RC: Default keys are regenerated on every meilisearch instance relaunch

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#2000]
**Describe the bug**
Default keys are changed if I relaunch MeiliSearch.

**To Reproduce**
1. `/keys`
2. Relaunch MeiliSearch
3. `/keys`
4. Default keys are different

**Expected behavior**

The API keys should only change if the masterKey is changed. 

**As per the specifications**: 

> If the master-key changes, all API Keys are re-generated and not every time the MeiliSearch instance is stoped and re-started.

[4 bullet point](https://github.com/meilisearch/specifications/blob/67505bbeb66841cfe64460930655842973ad255f/text/0085-api-keys.md#151-summary-key-points)

Same in the category [on defaults Keys](https://github.com/meilisearch/specifications/blob/67505bbeb66841cfe64460930655842973ad255f/text/0085-api-keys.md#153-default-api-keys).

> When the user accessing the machine launches MeiliSearch with a master key the first time, MeiliSearch will generate two API keys described below, as it did before with the public and private key. 

> These default API Keys can be modified/deleted with the /keys endpoint but are not re-created if MeiliSearch has already created them.

Relaunching MeiliSearch should not be a process that requires users to change their default key. If your server crashes and you have a automatic relaunch, without knowing, all your API keys are obsolete. 

**MeiliSearch version:** v0.25.0rc0

**Comment by curquiza** [comment]
This should not! Thanks @bidoubiwa for the report

**Comment by bidoubiwa** [comment]
The confusion came because I used a non-persistent docker to run my MeiliSearch instance. Which leads that on every relaunch of MeiliSearch I start with no data.ms thus the API keys are re-generated. 

When the data.ms is present, it stores the previously generated default API keys and only change if you change the master key!

**Comment by curquiza** [comment]
Thanks for the explanation!!
