### ISSUE TITLE
Why 2 results ?

### ISSUE THREAD

**Issue by zjttfs** [meilisearch/MeiliSearch#2004]
**Describe the bug**
Searching for `woman` brought up irrelevant results `Carol`

**To Reproduce**
```
<?php

require_once __DIR__ . '/vendor/autoload.php';

use MeiliSearch\Client;

$client = new Client('http://127.0.0.1:7700', 'masterKey');

# An index is where the documents are stored.
$index = $client->index('movies');

$documents = [
    ['id' => 1,  'title' => 'Carol', 'genres' => ['Romance, Drama']],
    ['id' => 2,  'title' => 'Wonder Woman', 'genres' => ['Action, Adventure']],
    ['id' => 3,  'title' => 'Life of Pi', 'genres' => ['Adventure, Drama']],
    ['id' => 4,  'title' => 'Mad Max: Fury Road', 'genres' => ['Adventure, Science Fiction']],
    ['id' => 5,  'title' => 'Moana', 'genres' => ['Fantasy, Action']],
    ['id' => 6,  'title' => 'Philadelphia', 'genres' => ['Drama']],
];

# If the index 'movies' does not exist, MeiliSearch creates it when you first add the documents.
$index->addDocuments($documents); // => { "updateId": 0 }
```

**Expected behavior**

only `Wonder Woman`

**Screenshots**

![1](https://user-images.githubusercontent.com/24729880/146137470-783672b2-69c6-4e77-b060-dcb8269cc631.png)
![2](https://user-images.githubusercontent.com/24729880/146137483-bc12d3cc-5b58-48b3-91be-567a9d1b9e03.png)

**MeiliSearch version:**

 v0.24.0

**Additional context**

Installing with docker
`docker pull getmeili/meilisearch:latest`

**Comment by Kerollmops** [comment]
Hey @zjttfs,

It can feel like a bug but it is not, the engine found out that _woman_ with a typo can match **the start of** _Romance_. You would say that it is the same with the word _woma_ but that's not as the engine will discard any typo on a word with 4 or fewer characters. You can read more about [the typo rules on this documentation page](https://docs.meilisearch.com/learn/advanced/typotolerance.html#typo-tolerance-rules).

Furthermore, the _woman_ query is considered as a prefix word query as it is the last word of the query and it doesn't contain a space and this is why the _e_ of _romance_ is not part of the comparison with _woman_, there is only one typo. You can read more about [the search engine prefix feature on the documentation](https://docs.meilisearch.com/learn/advanced/prefix.html#prefix-search).

**Comment by gmourier** [comment]
Hi @zjttfs 

If the expected behavior is to not want to consider the field `genres` as an attribute that users could search via the search bar, you can explicitly set `title` as a [searchableAttributes](https://docs.meilisearch.com/reference/api/searchable_attributes.html). By default, all fields are set as searchableAttributes on a newly created index.

To be able to filter interactively by `genres`, you can set it as a [filterableAttributes](https://docs.meilisearch.com/reference/api/filterable_attributes.html#filterable-attributes).
