### ISSUE TITLE
docs.meilisearch.com is down

### ISSUE THREAD

**Issue by moises-marquez** [meilisearch/MeiliSearch#2030]
**Describe the bug**
Sorry to bug you, but docs.meilisearch.com is down. I thought about contacting you over the contact form rather than creating a github issue, but the contact form is part of docs.meilisearch.com as well :rofl:

**Comment by MarinPostma** [comment]
It's working for me :thinking:

**Comment by moises-marquez** [comment]
Nice! I swear it was down just a few minutes ago :+1:

**Comment by MarinPostma** [comment]
I believe you :smile:
