### ISSUE TITLE
Cargo.toml of release 0.25.1 is still tagged as 0.25.0

### ISSUE THREAD

**Issue by Moisan** [meilisearch/MeiliSearch#2078]
**Describe the bug**
MeiliSearch version reports version `0.25.0` in release `0.25.1`

**To Reproduce**
1. Execute `meilisearch --http-addr 127.0.0.1:57943`
2. In a different shell, execute `curl -s 127.0.0.1:57943/version`
3. See the version being 0.25.0

**Expected behavior**
The new release should be at version 0.25.1

**MeiliSearch version:** [e.g. v0.20.0]
0.25.1
**Additional context**
See https://github.com/meilisearch/MeiliSearch/blob/d0aa5f747c0e5818184632623ece570b05a09423/meilisearch-http/Cargo.toml#L7

**Comment by MarinPostma** [comment]
Hello @Moisan ! We are aware of this, this is a mistake from our end. @curquiza will confirm, but I think the plan is to leave it like that until the next release?

**Comment by curquiza** [comment]
Yes, I confirm, sorry for this @Moisan. This is indeed v0.25.1 but with the wrong version in the Cargo.toml.
We will not be able to change this until the next release.

**Comment by Moisan** [comment]
When is the next release planned to be?

**Comment by curquiza** [comment]
Next release should be v0.26.0, and the planned date is 07/03/2022
Except if we figure out a critical bug, in this case, we would release a patch (v0.25.2) in the meantime.

**Comment by curquiza** [comment]
Closing this, v0.25.2 is released and is having the right version in cargo.toml :)
