### ISSUE TITLE
filterableAttributes does not support camel-case'd keys

### ISSUE THREAD

**Issue by jmonster** [meilisearch/MeiliSearch#2082]
**Describe the bug**
I've declared multiple keys to be filterable; one is camelCase.
- When filtering an empty DB, filtering fails for any/all attributes.
- When filtering a non-empty DB, filtering fails for only the camelCase'd attribute (and with a different error)

It seems that for some reason the camelCase'd attribute doesn't match and is rejected as if it wasn't specified in the `filterableAttributes` -- but it is, and is even echoed back in the array of possible values.

On a hunch I changed the name from `episodeNumber` to `episode_number` and it then behaved the same as the other attributes -- i.e. it no ceased to to reject the attribute name.

```
message: 'Attribute `episodeNumber` is not filterable.
Available filterable attributes are: `episodeNumber series`.' 
```

**To Reproduce**
- Configure `filterableAttributes`
```js
fetch(`${searchUrl}/settings`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    // authorization,
  },
  body: JSON.stringify({
    filterableAttributes: ['episodeNumber', 'series']
  })
})
```

- Add items to the DB (or else it'll error!)
- Perform a filtered search:

```js
fetch(`${indexUrl}/search`, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
    // authorization,
  },
  body: JSON.stringify({
    filter: `series = "${series}" AND episodeNumber = ${episodeNumber}`
  }),
});
```

**Expected behavior**
A 200 response with an array containing 0 or more elements.

**MeiliSearch version:** [e.g. v0.25.0]

**Additional context**
Additional information that may be relevant to the issue.
> Apple Silicon m1 macOS 12.1 arm64

# ⚠️
I found it very confusing that none of this works until after you've inserted at least 1 record under this index -- even when I've already created the index and explicitly specified an index id. When there is no data the following error is triggered:

```js
 fetch(`${url}/indexes`, {
    method: 'POST',
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      "uid": "cues",
      "primaryKey": "id"
    })
  })
```
```js
fetch(`${url}/indexes/cues/settings`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      // authorization,
    },
    body: JSON.stringify({
      filterableAttributes: ['episodeNumber', 'series']
    })
  })
```
```js
fetch(`${url}/indexes/cues/search`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      // authorization,
    },
    body: JSON.stringify({
      filter: `season = "series = "${series}" AND episodeNumber = ${episodeNumber}`,
    }),
  });
```
```
message: 'Internal error while executing this filter.
```

**Comment by Kerollmops** [comment]
Hello and thank you for your issue @jmonster,

We indeed found out the source of the bugs, there are two of them and we will probably release a patched version shortly (v0.25.2). The engine should indeed support non-full-lowercase field names and should not return an error for when a field has never been encountered in any document.

**Comment by irevoire** [comment]
Oops sorry, this issue will be closed once we release a new version of MeiliSearch containing the fix!

**Comment by irevoire** [comment]
The release is done: https://github.com/meilisearch/MeiliSearch/releases/tag/v0.25.2
Thank you for your report, I'm closing now :+1:

**Comment by juliancesar** [comment]
Hey guys, great job fixing this!

When version *v0.25.2* will be available in Debian repo (https://apt.fury.io/meilisearch/)?

Tks!

**Comment by juliancesar** [comment]
Today! Tks!

![image](https://user-images.githubusercontent.com/4247825/149988018-cb17d3d8-4267-4f54-a43d-93cc17d4dc1f.png)
