### ISSUE TITLE
Results of sorting by float field unexpected

### ISSUE THREAD

**Issue by leopku** [meilisearch/MeiliSearch#2083]
**Describe the bug**
Result of sorting by float field was unexpected.

**To Reproduce**
1. add documents with a float field
2. query and sort by the float field
3. checking the results can found that the results were not sort by float exactly.

**Expected behavior**

**Screenshots**
```
xh -b POST 10.0.1.7:7700/indexes/91video/search <<< '{"q":"kw", "sort": ["m3u8_duration:desc"]}' | dasel -p json -m -s 'hits.[*].m3u8_duration'
707.311496
424.3999919999999
273.76666200000005
228.233331
137.49999799999998
40.566667
34.083332999999996
30.466667
753.522
582.846
151.76666400000002
77.243833
35.566666000000005
33.84
29.7
17.533333
3736.57 
1262.5333090000015
828.6333180000004
682.8399999999999
```

**MeiliSearch version:** [e.g. v0.20.0]
0.25.0

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]
Ubuntu 20.04
amd64

**Comment by Kerollmops** [comment]
Hey @leopku,

This doesn't seem like a bug, if you only look at the sorted values, indeed, those are not exactly sorted in descendant order, and it is like that for good reasons. The default sort settings don't declare the sort ranking rule as the first rule to use, if we were doing this, the relevancy would be totally gone.

So, [the default ranking rules order](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#built-in-rules) have the sort ranking rule in the 5th place, to make sure that the relevancy is good enough, you can obviously move the sort ranking rule at the first place if you want. We have [a dedicated guide for sorting documents](https://docs.meilisearch.com/reference/features/sorting.html#sorting).

**Comment by leopku** [comment]
@Kerollmops Okay, got it. Big thanks.
