### ISSUE TITLE
Error while persisting update to disk: No such file or directory

### ISSUE THREAD

**Issue by hahmad748** [meilisearch/meilisearch#2085]
**Getting INTERNAL error while accessing MeiliSearch**
{
    "message": "An internal error has occurred. `Error while persisting update to disk: No such file or directory (os error 2)`.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
}

**To Reproduce**
1. Go to POSTMAN
2. Add Authorization Key
3. Add IP and Port
4. Hit any API, Like See stats, or get indexes list
5. Got above mentioned error in every case

**Expected behavior**
Should display the desired result, stats or indexes

**MeiliSearch version:**
{
    "commitSha": "0a1d2ce2318c26f36ddcb82d3159b8003120b84f",
    "commitDate": "2021-11-15T18:02:07+00:00",
    "pkgVersion": "0.24.0"
}

**Comment by curquiza** [comment]
Hello @hahmad748 

Sorry for the inconvenience :(

Can you share the logs?
Can you say which actions (adding documents, adding settings) you did before having this error?

Also, if it's possible, can you try using [MeiliSearch v0.25.2](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.25.2), which is the latest one, and report us if you have the same error?

Thanks in advance!

**Comment by hahmad748** [comment]
Hello @curquiza 

- I can easily get the indexes that are listed before the mentioned error. Now am getting error for almost every request for settings, like fetching global stats, getting list of indexes, fetching filterable attributes etc.

I'll update the MeiliSearch version to 0.25.2 and verify if the issue persist or not

**Comment by curquiza** [comment]
Thank you @hahmad748, let us know!

**Comment by geoioanid** [comment]
_Meilisearch Version_: v0.25.2
_Dockerized_: Yes

I'm facing a similar issue, when trying to create a dump. 
The dump creation process runs for some minutes, and then fails with the following error:
```
{
    "uid": "20220130-072536070",
    "status": "failed",
    "error": "An internal error has occurred. `Internal error: Error while persisting update to disk: No such file or directory (os error 2)`.",
    "startedAt": "2022-01-30T07:25:36.070952400Z",
    "finishedAt": "2022-01-30T07:45:21.146419389Z"
}
```
This error doesn't create any side effects for me as @hahmad748 has mentioned (like fetching global stats, getting list of indexes, fetching filterable attributes etc.) Refer to the following quote
> Hello @curquiza
> 
> * I can easily get the indexes that are listed before the mentioned error. Now am getting error for almost every request for settings, like fetching global stats, getting list of indexes, fetching filterable attributes etc.
> 
> I'll update the MeiliSearch version to 0.25.2 and verify if the issue persist or not

**Comment by curquiza** [comment]
Hello @geoioanid 

How do you run your dockerized instance of Meilisearch, I mean, what is your command? What are your mounted files?

**Comment by geoioanid** [comment]
Hello @curquiza 
Docker for Windows.
OS: Windows 10
I run meilisearch with docker-compose.
I use a volume for data.ms

**Comment by curquiza** [comment]
Thanks! For more context
- which usage of Meilisearch did you have before encountering the error? 
- Were you trying to add documents or search during the dump creation?

**Comment by geoioanid** [comment]
Some updates were pending when I got the error.

**Comment by MarinPostma** [comment]
@geoioanid 's issue is fixed on the new version thanks to work done on #2005. The was a data race that was occurring when reading from the file system that I had noticed and fixed there.

**Comment by MarinPostma** [comment]
I don't have enough reproduction info from @hahmad748 to be able to reproduce, what is your setup?

**Comment by hahmad748** [comment]
> I don't have enough reproduction info from @hahmad748 to be able to reproduce, what is your setup?
https://lindevs.com/install-meilisearch-on-ubuntu/
I followed this article to setup meileSearch on Ubuntu 20.04 which was working fine for almost 2-3 months, but i faced this issue recently while accessing with POSTMAN.

**Comment by MarinPostma** [comment]
good, let me try that then :)
