### ISSUE TITLE
New flag behavior for the CLI

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#2097]
After discussion with @MarinPostma and @gmourier, we noticed the current flag behavior of MeiliSearch in the CLI was not user-friendly.

It's common to not define the value of an argument when the value is a boolean. That's why the flags of MeiliSearch will change their behavior.

Before

```bash
meilisearch --no-analytics=true
```
 After
```bash
meilisearch --no-analytics
```

The previous usage (`--no-analytics=true`) will not work anymore, that's why it impacts @meilisearch/docs-team but also @meilisearch/integration-team in their CONTRIBUTING.md guidelines and in their CIs.

Concerned flags
- `--no-analytics`
- `--schedule-snapshot`
- `--ignore-missing-snapshot`
- `--ignore-snapshot-if-db-exists`
- `--ssl-require-auth`
- `--ssl-resumption`
- `--ssl-tickets`

**Comment by guimachiavelli** [comment]
Just to confirm, once this is merged a user who runs e.g. `meilisearch --no-analytics=true ./` will get an error, right?

**Comment by curquiza** [comment]
Exactly

<img width="788" alt="Capture d’écran 2022-01-20 à 17 10 40" src="https://user-images.githubusercontent.com/20380692/150376995-5b7e94b0-cbca-455a-be28-e131ed6f10a4.png">

**Comment by guimachiavelli** [comment]
Sorry, another question. 

This issue only mentions CLI instance options. What about env vars? If I use`MEILI_NO_ANALYTICS=false`, will it be parsed as `false` or as a truthy value because it is a string?

**Comment by MarinPostma** [comment]
@guimachiavelli the pr explains what values are accepted, and their meaning:
