### ISSUE TITLE
Error message contains whole payload when the type is not correct

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2107]
**Describe the bug**
I tried to send (wrongly) a string using `POST /indexes/x/documents`. The returned error message from MeiliSearch is as follows: 
`MeiliSearchApiError: The json payload provided is malformed. "whole payload"`.

In my case the `whole payload` is 3million character long. So my error message looks like this:

<img width="834" alt="Screenshot 2022-01-24 at 13 39 54" src="https://user-images.githubusercontent.com/33010418/150785664-020453c7-a89d-4647-80f6-0def3014874e.png">

(ignore the popup from vscode)

**To Reproduce**
1. Add a string instead of a document with content-type json
2. It throws an error containing the whole string

**Expected behavior**
Maybe a more explicit error `The json payload provided is malformed, expected an array but go a string instead`

**Screenshots**
see above

**MeiliSearch version:** v0.25.1

**Comment by MarinPostma** [comment]
do you you have a minimum reproducible example so I can see what triggers this error?

**Comment by bidoubiwa** [comment]
Could you try by adding the following as the body of `POST /documents` 

```
""\{ "\id"\: 1 }"\"
```

As you can see it is a json inside a string inside a string. That was my mistake. The error should be 
```
MeiliSearchApiError: The json payload provided is malformed. "whole payload". ""\{ "\id"\: 1 }"\"
```

In my use case, the string is 3 million chars long. So the error is a bit longer 😂

**Comment by curquiza** [comment]
Thanks @bidoubiwa for the report :) Will check with the @meilisearch/product-team and core team what to do

**Comment by irevoire** [comment]
Hello @ilyatrefilov sorry for the delay, yes the issue is still present!
Look at this simpler example:
```bash
% curl http://localhost:7700/indexes/mieli/documents -X POST -H 'Content-type: application/json' --data '"Hello @ilyatrefilov"'
```
Which returns:
```json
{
  "message": "The `json` payload provided is malformed. `Couldn't serialize document value: invalid type: string \"Hello @ilyatrefilov\", expected a documents, or a sequence of documents. at line 1 column 21`.",
  "code": "malformed_payload",
  "type": "invalid_request",
  "link": "https://docs.meilisearch.com/errors#malformed_payload"
}
```
