### ISSUE TITLE
Deploy Meilisearch v0.25.2 on K8s arm64 node failed

### ISSUE THREAD

**Issue by Thearas** [meilisearch/meilisearch#2115]
**Describe the bug**

Deploy Meilisearch v0.25.2 on K8s arm64 node failed.
Pod log:
```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
```

**To Reproduce**

1. Apply the yaml <https://github.com/meilisearch/meilisearch-kubernetes/blob/main/manifests/meilisearch.yaml>

**Expected behavior**
No error.

**Screenshots**
No.

**MeiliSearch version:**

v0.25.2

**Additional context**
OS: Linux xxx.xxx.xxx.xxx 4.18.0-305.10.2.el7.aarch64 #1 SMP Fri Jul 23 21:19:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
Architecture: arm64

**Comment by Thearas** [comment]
I find a issue related issue: <https://github.com/meilisearch/MeiliSearch/pull/1666>. It seems that the env `JEMALLOC_SYS_WITH_LG_PAGE=16` will be set when [publishing binaries](https://github.com/meilisearch/MeiliSearch/blob/main/.github/workflows/publish-binaries.yml), but not when publishing docker images.

**Comment by Thearas** [comment]
Two ideas:
1. Use `Makefile` and set the environment variable on `make build`
2. Set the environment variable in `build.rs`, like #2122 
Would you like to give me some advice? :) @curquiza

**Comment by curquiza** [comment]
Hello @Thearas 

Sorry for the delay, and thanks for the contribution! 😄 

We would rather not having this in our build.rs. Can you add the env variable in our docker CIs here
- https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-docker-latest.yml
- https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-docker-tag.yml
?

Thanks :)
