### ISSUE TITLE
Hightlight with special characters

### ISSUE THREAD

**Issue by lemonlab** [meilisearch/meilisearch#2121]
**Description**
When a search contains a special character, the highlight feature is not highlighting the full word

**To Reproduce**
1. Add an index with a field {"title": "françois"}
2. Search for "françois"
3. Only "françoi" will be highlighted

**Expected behavior**
"françois" (the full word) should be highlighted

**Screenshot**
![Screen 2022-01-26 at 21 04 05@2x](https://user-images.githubusercontent.com/2278002/151238366-1cd22fc9-926c-49c3-9487-c338fcd3d604.png)

**Meilisearch version:** 
v0.24.0

**Additional context**
- Running on Meilisearch Cloud

**Comment by interlark** [comment]
Looks like it's related to this [PR](https://github.com/meilisearch/milli/pull/426) which I believe is not yet included. You could try to upgrade milli dependency (v0.22.0) or wait until Meilisearch (v0.26).

**Comment by lemonlab** [comment]
Thanks ! I will wait Meilisearch v0.26 since i can't upgrade milli dependency on MeiliSearch Cloud.

**Comment by curquiza** [comment]
Hello @lemonlab 

Indeed, @interlark is right, it's planned for v0.26.0.
This issue is a duplication of https://github.com/meilisearch/meilisearch/issues/1480 :)
