### ISSUE TITLE
Phrase search returns false positive when more than 2 words are searched

### ISSUE THREAD

**Issue by tao** [meilisearch/meilisearch#2123]
**Describe the bug**
The phrase search does not yet return documents that match the phrase in the correct order.

![Screenshot 2022-01-28 at 11 33 51](https://user-images.githubusercontent.com/1446331/151522770-4e998338-31a3-43f0-8107-1b359f871e0c.png)

Although I known the phrase search highlighting is still being fixed #1912, this is another issue.

In this example the second, third and sixth search results onwards don't contain the phrase `"known to your peoples"`, these documents only contain the phase `"known to"` and `"your peoples"` with large gaps between them, sometimes not even in the right order.

**Expected behavior**

The phrase search should return documents with `"known to your peoples"` only. I did not search for `"known to" "your peoples"`, it's just not working as expected and I've tried changing all the ranking rules around to see if those have an effect too.

**Screenshots**

For example, in this second document it contains `"known to"` once and `"your peoples"` twice so it's probably why it's ranked higher, but it's not the correct phrase.

![Screenshot 2022-01-28 at 11 16 12](https://user-images.githubusercontent.com/1446331/151519914-5321dcbf-efb3-4c54-8c15-a72c5751a958.png)

The third document is the same issue, it has `"your peoples"` twice, and `"I am (known to) you as"` but the gap between these words is many paragraphs. The same applies to the sixth document...

The forth document does contain `"known to your peoples"` as the exact phrase so it should be ranked higher than the previous examples. It also contains `"your peoples"` in another place in the document.

![Screenshot 2022-01-28 at 11 18 52](https://user-images.githubusercontent.com/1446331/151520365-b0aeaab6-80d1-4959-b75f-acdabda3ed86.png)

The fifth document also contains the exact phrase `"known to your peoples"` which is shown in the first screenshot of the search results.

If I look at the last document returned in the results it doesn't contain the right phrase either but it seems more correct than the second and third documents which has `"your peoples"` twice, as this one has all the words in order in the same paragraph, While the second and third results have large paragraphs or gaps between the phrases... but that's not what I'm looking for either. I'm looking for documents that contain the phrase `"known to your peoples"` only.

![Screenshot 2022-01-28 at 11 19 14](https://user-images.githubusercontent.com/1446331/151520413-84d1944d-9989-4001-93d5-0ec8d93ca62c.png)

**Meilisearch version:**
v0.25.2

**Comment by ManyTheFish** [comment]
Hey @tao!
Your bug is due to [how we compute proximity in phrase search](https://github.com/meilisearch/milli/blob/main/milli/src/search/criteria/mod.rs#L319-L339), in your example, we are searching:
- documents that contain `known` side to side to `to`
- documents that contain `to` side to side to `your`
- documents that contain `your` side to side to `peoples`

and we keep the intersection of the 3 "queries", but, as we can see in your example, we can have false positives.
This can be enhanced, relatively easily, by iterating over words 3 by 3 instead of 2 when we have more than 2 words in the phrase, and checking that:
- documents that contain `known` side to side to `to` AND `to` side to side to `your` AND `known` is exactly at a distance of 2 to `your`
- documents that contain `to` side to side to `your` AND `your` side to side to `peoples` AND `to` is exactly at a distance of 2 to `peoples`

This could reduce the false positives without impacting significantly the search time. ☺️

Thanks @tao for your report!

**Comment by curquiza** [comment]
This issue can be done by the community 😄 
This should be done in the [Milli's repository](https://github.com/meilisearch/milli).
Don't hesitate to ask for any help.

**Comment by tao** [comment]
I would greatly appreciate if someone from the community or your team could help, you make it sound like an easy issue that could be fixed but I don't know Rust myself, so I had to post the issue here.

It seems to me like phrase search should work with more than two words, or a sentence, otherwise it wouldn't be much different from running a normal keyword search.

We already had to delay our launch because phrase search wasn't working since `v0.21.0`, and now we're finding it doesn't return accurate enough results for us to release it. I already mentioned this before but you asked me to talk about it in the [Policy for matching words](https://github.com/meilisearch/product/discussions/255) discussion, and I also didn't get a response then since November about making phrase search stricter. Now it seems like you passing this off and leaving it for the community to fix and you're not that concerned about phrase search working. Now I have to think about delaying the product further while we wait or look for alternate solutions if it's not a concern to you.

I understand if you are busy, trying to scale up and release new features, but if I knew that the issue would get addressed in a certain timeframe then at least I could try plan my next software release around it.

**Comment by ManyTheFish** [comment]
Hey @tao,
I'm sorry if letting this issue for the community sounds like we under-estimate the value of this issue, we don't.
However, as you said, we are a bit busy, I'm currently working on #1912.
But, we are an open-source product, and sometimes, the community is faster than us to solve issues, and if no one comes we'll fix this. 🙂

**Comment by MarinPostma** [comment]
@tao, I'm taking a look at this :)

**Comment by MarinPostma** [comment]
I have opened a pr with the fix https://github.com/meilisearch/milli/pull/442, hopefully we roll it out with the next version @tao :) cheers

**Comment by tao** [comment]
Thanks for the help @MarinPostma  and @ManyTheFish. I really appreciate it. I understand search is a difficult problem and you may have to deal with many users asking for different goals and features, but a working phrase search has been really important to us and I hope it's useful for others as well.
