### ISSUE TITLE
Limits the recoverable attributes in case of sorting

### ISSUE THREAD

**Issue by qdequele** [meilisearch/meilisearch#2128]
**Describe the bug**
I'm using a dataset of 24M hacker news posts. Here is an example of a document:
```
{
    "by": "perler",
    "descendants": 0,
    "id": 5,
    "kids": [454414],
    "score": 7,
    "time": 1160419864,
    "title": "Google, YouTube acquisition announcement could come tonight",
    "type": "story",
    "url": "http://www.techcrunch.com/2006/10/09/google-youtube-sign-more-separate-deals/"
}
```

I created an index with the following configuration:
```
{
    "displayedAttributes": [
        "by",
        "id",
        "score",
        "time",
        "title",
        "type",
        "url"
    ],
    "searchableAttributes": [
        "title"
    ],
    "filterableAttributes": [
        "by",
        "type"
    ],
    "sortableAttributes": [
        "score",
        "time"
    ],
    "rankingRules": [
        "words",
        "typo",
        "proximity",
        "attribute",
        "sort",
        "exactness"
    ],
    "stopWords": [],
    "synonyms": {},
    "distinctAttribute": null
}
```

When I try to search without sorting, here is the result. I have the full document (following my settings).
![Screenshot 2022-01-30 at 22 38 44](https://user-images.githubusercontent.com/6064892/151719109-8d95f4bf-aad3-4dc6-a252-5222bcc3323f.jpg)

But if I add a sort, I only have a few fields returned.
![Screenshot 2022-01-30 at 22 38 58](https://user-images.githubusercontent.com/6064892/151719137-e92211cb-13ea-4102-bf5b-b33954065a76.jpg)

**Meilisearch version:** [e.g. v0.25.2] (Cloud)

**Additional context**
If you need access to my server to test, I can share my URL and my key with you, don't hesitate to contact me.

**Comment by Kerollmops** [comment]
Hey @qdequele,

Are you sure that it is not part of your dataset? Can you check that the document with id `11017550` does contain the fields you thought it should? We never had this issue before.

**Comment by qdequele** [comment]
Indeed this is a mistake on my part, I had checked the `1101755` instead... From ID 10000000 onwards the deleted elements no longer have the metadata and as I didn't know about the `deleted` field I didn't realize that this could happen. Good catch @Kerollmops!
