### ISSUE TITLE
Accepting null (empty) values for numeric fields on CSV upload

### ISSUE THREAD

**Issue by ozgurhangisi** [meilisearch/meilisearch#2138]
**Describe the bug**

Sample CSV file:
id,title,market_price:number,sale_price:number,status
1,product1,123,100,in_stock
2,product2,,,out_of_stock

Our case is (probably most of the e-commerce sites have this case) some products have sale price and some of them don't. If I send empty value with CSV file meilisearch doesn't accept the update. If I send 0 for empty for sale_price I have to do lots of things to use all the sorting features (If I sort results by sale_price from lower to higher products with 0 sale_price appear first.) and I have to manipulate the data before I show in instantmeilisearch. Because the price appears 0 $  and it's not a good practice. If I convert it to string field I loose sorting ability.

I actually solved my issue (with lots of modification) but I wanted to let you know the case. If it's not possible to send the empty(null) values to numeric fields so you can close the issue. 

**To Reproduce**

Try to upload the sample CSV file above. You are going to see the error. 

**Expected behavior**
System should accept empty or null values for numeric fields.

**Meilisearch version:** [e.g. v0.20.0]
0.25.0

**Additional context**
I use meili community image in aws.

**Comment by MarinPostma** [comment]
@ozgurhangisi I have made a PR to address that here https://github.com/meilisearch/milli/pull/445. Thank you for your report :) cheers

**Comment by curquiza** [comment]
Here are the related spec changes: https://github.com/meilisearch/specifications/pull/110
