### ISSUE TITLE
Only shows the full message when the user have configured the settings for it

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch#2140]
**Describe the bug**
When I provide a search request with a sort option, I should receive the error with the available sortable attributes but I'm getting an empty list:
```json
{
    "message": "Attribute `name` is not sortable. Available sortable attributes are: ``.",
    "code": "invalid_sort",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_sort"
}
```
My request: `GET http://localhost:7700/indexes/rails_e661e74611d4d7b8_Color_development/search?sort=name:asc`
My index settings:

```json
{
    "displayedAttributes": [
        "*"
    ],
    "searchableAttributes": [
        "name"
    ],
    "filterableAttributes": [
        "short_name"
    ],
    "sortableAttributes": [],
    "rankingRules": [
        "words",
        "typo",
        "proximity",
        "attribute",
        "sort",
        "exactness",
        "hex:asc"
    ],
    "stopWords": [],
    "synonyms": {},
    "distinctAttribute": null
}
```

I know that I didn’t configure the `sortableAttributes`, so the question I make is, should we receive a different message? Or is ok to keep the current behavior? Because when I read it the first time, I really thought that something was wrong on my end.

An idea could be having a conditional to show up when the user doesn't have any sortable attributes configured.

```
{
    "message": "Attribute `name` is not sortable. This index doesn't have configured sortable attributes",
    "code": "invalid_sort",
    ...
}
```

I've spotted the code here: https://github.com/meilisearch/milli/blob/8dff08d772db7ee2bccfed4a75b943ec8be455a2/milli/src/error.rs#L254 but I wasn’t sure if I need to post the issue here or in `milli` repo, please let me know :D

**Meilisearch version:** v0.25.2

**Additional context**
Running in the dockerized environment (using the official docker image)

----

TODO
- [X] Merge https://github.com/meilisearch/milli/pull/461
- [x] Does the same change for `filterableAttributes` on Milli's side
- [x] Release milli with these changes
- [x] Bump milli dependency with this new version

**Comment by gmourier** [comment]
Hi @brunoocasali, I find this type of message in this case also clearer!

**Comment by MarinPostma** [comment]
@gmourier So you like the new message idea?
@brunoocasali yup, that right there, how would you like a first core contribution? ;)

**Comment by gmourier** [comment]
@MarinPostma Yes!

**Comment by curquiza** [comment]
Re-opening since it's still not fixed on Meilisearch side. 
I updated the issue description accordingly with the next steps

**Comment by gmourier** [comment]
I will patch the error spec to add this new message variant. It should also be put on the `filter` parameter in case `filterableAttributes` is empty. 🤓

**Comment by gmourier** [comment]
Don't forget to add the same variant on `filter` when the `filterableAttributes` are empty 🤓  I will spec the 2 new variants for `v0.27.0`

**Comment by gmourier** [comment]
Specified here https://github.com/meilisearch/specifications/pull/125

**Comment by curquiza** [comment]
Reopening since it's not fixed on milli's side

**Comment by curquiza** [comment]
Milli was bumped in https://github.com/meilisearch/meilisearch/pull/2244, with [milli v0.24.0](https://github.com/meilisearch/milli/releases/tag/v0.24.0) containing the required change for the new error message. We can close this issue. The change will be effective in v0.27.0.
