### ISSUE TITLE
Error parsing response JSON: missing field `updateId` at line 1 column 117

### ISSUE THREAD

**Issue by adaszko** [meilisearch/meilisearch#2143]
Hi 👋 

**Describe the bug**
After an upgrade of Meilisearch to 0.25.2 via Homebrew on macOS, I started getting an error from `add_documents()`:

```
2022-02-05T09:35:20.340295Z ERROR meilisearch_sdk::request: Request succeeded but failed to parse response
Error parsing response JSON: missing field `updateId` at line 1 column 117
```

**To Reproduce**
I *think* the steps are (I'm hoping here that to authors, the reasons for JSON schema incompatibility shouldn't be a big mystery):
1. Index some documents on Meilisearch 0.24
2. Upgrade Meilisearch to 0.25.2
3. Index to same documents on Meilisearch 0.25.2

**Expected behavior**
meilisearch-sdk should be working with 0.25.2

**Meilisearch version:** [e.g. v0.20.0]
0.25.2

**Additional context**
`meilisearch-sdk` crate version from `Cargo.lock`:

```
[[package]]
name = "meilisearch-sdk"
version = "0.13.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "224d36812b5337fc4591f58bd1d9b19e3504558551ab47f8b9319a1644706976"
```

**Comment by adaszko** [comment]
I am only just now looking at <https://crates.io/crates/meilisearch-sdk> and see this:

![image](https://user-images.githubusercontent.com/165678/152636673-d421cdb3-599e-4129-bd8a-1b9af517b45e.png)

**Comment by irevoire** [comment]
Which sdk are you talking about?
If it's the rust sdk then yes, I'm currently working on it 🫡

**Comment by adaszko** [comment]
Yes, it's the Rust SDK

**Comment by curquiza** [comment]
Hello @adaszko!
Thanks for using Meilisearch and its Rust SDK 😄 
Sorry for the delay to update it, @irevoire is indeed working on it to help the integration team make the SDK compliant with v0.25.0
This should be available soon! sorry for the delay again!

I'm closing this since an answer has been given
