### ISSUE TITLE
API key creation should returns an error

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2158]
**Describe the bug**
While creating an API key we can specify the indexes it applies to.
And if we specify a [bad formatted index name](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#invalid_index_uid) we’re supposed to get an [`invalid_api_key_indexes`](https://github.com/meilisearch/specifications/blob/develop/text/0061-error-format-and-definitions.md#invalid_api_key_indexes) error from what I see.

That’s not the case.
The same happens for the update route.

**To Reproduce**
1. Send the following request: `echo '{ "actions": [], "description": "test_error_create_key", "indexes": ["invalid index # / \\name with spaces"], "expiresAt": null }' | http :7700/keys 'Authorization: Bearer masterKey'`
2. Get the result:
```
{
    "actions": [],
    "createdAt": "2022-02-09T14:47:49Z",
    "description": "test_error_create_key",
    "expiresAt": null,
    "indexes": [
        "invalid index # / \name with spaces"
    ],
    "key": "AG5o4s740edcfd04ce86f2a92259ca6f886485caf22ebb156b91211ac4e10119482f6e67",
    "updatedAt": "2022-02-09T14:47:49Z"
}
```

**Expected behavior**
Error

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7032172/153227209-4df7a345-9ce9-43a7-88f4-f7f29188f680.png">

**Meilisearch version:** v0.25.2

**Additional context**
I gave you my private key please don’t hack me.

--- 

Edit by @curquiza 

TODO:

The spec specifies:
> Sending a value that is not a valid `index` (e.g. regarding the index uid format) in the `indexes` field returns an [invalid_index_uid](0061-error-format-and-definitions.md#invalid_index_uid) error.

See https://github.com/meilisearch/specifications/pull/112/files

We want to make the search engine returns an error when the index uid is invalid

Definitely something that can be fixed by an external contributor! Feel free to ask for help

**Comment by MarinPostma** [comment]
I had a similar discussion with @gmourier about the error one should get when `GET`ing an index with a badly formatted index uid, I was on the side of returning a badly formatted index name error here, before the index doesn't exist error, but he was aging the opposite. Anyway, the result is that we return an  index not found error. So what you get seems consistent with that to me

**Comment by gmourier** [comment]
Thanks, I understand the problem better!

Indeed, we could add a variant of the error message in this case. It can be also extended to the `actions` field that works in the same way (expecting valid values). Currently, we just check that it is an array made of string. Thus, we already have a [message](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#invalid_index_uid) for it. (See message field).

Nevertheless, I make the difference between filling a value for an API resource (this specific case) and requesting a resource via `GET`.

It makes sense to me to get a 404 when the resource doesn't exist on `GET /indexes/{index}` (An index having an invalid uid will never exist) and this is, I believe, common to most APIs. Although this route also allows creating indexes asynchronously but I think this one particular case should not take precedence over requesting a resource more than creating it.

What do you think?

**Comment by curquiza** [comment]
Checked with @gmourier and the @meilisearch/core-team, need to change [the spec (API key)](https://github.com/meilisearch/specifications/blob/main/text/0085-api-keys.md) before starting this issue

**Comment by curquiza** [comment]
I've updated the spec here: https://github.com/meilisearch/specifications/pull/112/files

> Sending a value that is not a valid `index` (e.g. regarding the index uid format) in the `indexes` field returns an [invalid_index_uid](0061-error-format-and-definitions.md#invalid_index_uid) error.

**Comment by curquiza** [comment]
Here is the new spec: https://github.com/meilisearch/specifications/pull/113
