### ISSUE TITLE
Setting two words as synonyms returns a different number of results 

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/meilisearch#2162]
**Describe the bug**
If I set `winnie` and `piglet` as synonyms, searching for either should return the same results, the only exception being one-way association.
With the default settings, I got 205 results for `winnie` and 9 for `piglet`.
When I set `winnie` and `piglet` as synonyms: I get 208 results for `winnie` and 17 for `piglet`.

How is this working?

**To Reproduce**
1. Use the [movies dataset](https://github.com/meilisearch/datasets/tree/main/datasets/movies)
2. Search for `winnie` using:
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/search' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "q": "winnie" }'
```
Returns **205** results
3. Search for `piglet` using:
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/search' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "q": "piglet" }'
```
Returns **9** results
4. Set `winnie` and `piglet` as synonyms:
```
  curl \
    -X POST 'http://localhost:7700/indexes/movies/settings/synonyms' \
    -H 'Content-Type: application/json' \
    --data-binary '{
      "winnie": ["piglet"], "piglet": ["winnie"]
      }'
```
5. Search for `winnie` using:
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/search' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "q": "winnie" }'
```
Returns **208** results
6. Search for `piglet` using:
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/search' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "q": "piglet" }'
```
Returns **17** results

**Expected behavior**
This should return the same number of results since they are synonyms. Not sure if I understand correctly though 

**Meilisearch version:** v025.2

**Comment by curquiza** [comment]
hello @maryamsulemani97 thanks for your detailed issue!

When you talk about "... results" do you mean the number returned in `nbHits`?

**Comment by maryamsulemani97** [comment]
Hi @curquiza, 

Yes `nbHits`

**Comment by curquiza** [comment]
Thanks many for the detailed answer!
I close this issue. Feel free to ask for re-opening if you have any question :)
