### ISSUE TITLE
Meilisearch 0.20.0 won't find sub-strings containing non english characters like (¿, ¡)

### ISSUE THREAD

**Issue by Dialvive** [meilisearch/meilisearch#2167]
I have a Meilisearch 0.20.0 instance at production that won't find sub-strings containing non english characters like (¿, ¡). For example, if I have a document that contains "¡Hola!", and I search for "Hola", "¡Hola!" won't appear on the results, interestingly if I search "¡Hola" then the word appears in the results.

1. Run a Meilisearch 0.20.0 instance,
2. Insert a document containing a word "¿Like?" "¡This!",
3. Insert other words that are syntactically similar to the ones above,
4. Search the first words but without the "¿" or "¡",
5. Does the words appear as the first result?

I expected that if a user searches for words containing left and right (question or exclamation) marks, the most relevant result would be those words with marks. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30503143/153730711-836b001c-1694-430a-9a6e-40673059d837.png)
Img 1: Cero matches.
![image](https://user-images.githubusercontent.com/30503143/153730737-1fd979c7-ea59-4110-8cc6-25cbee16360d.png)
Img 2: Multiple Matches.
![image](https://user-images.githubusercontent.com/30503143/153730778-88131f7b-ca47-4059-b14a-c8659b293bbd.png)
Img 3: Cero Matches.
![image](https://user-images.githubusercontent.com/30503143/153730882-997714ff-88d1-4ed2-aa37-ec2da43beb70.png)
Img 4: Exact match.

**Meilisearch version:**
0.20.0

**Additional context**
Running on GCP, e2-medium, Ubuntu 20.0, passing through [Meilisearch-Go](github.com/meilisearch/meilisearch-go) v0.14.1, and consulting on Postman and Google Chrome/Firefox (both latest).

**Comment by curquiza** [comment]
Hello @Dialvive 
Meilisearch v0.20.0 is a really old version, released 1 year ago.
Looks like the bug is fixed with the latest version of Meilisearch (https://github.com/meilisearch/MeiliSearch/releases). Can you confirm?
