### ISSUE TITLE
Malicious search queries may cause very high CPU and RAM usage

### ISSUE THREAD

**Issue by THE-FYP** [meilisearch/meilisearch#2175]
**Describe the bug**
I have discovered two cases when some special search queries can take up CPU for a long time and consume a lot of RAM.
The first one is multiple occurrence of one/two-symbol words that often appear in documents and start other words.
The second one is very very long text as a single word, being changed and queried multiple times.

Search index on our staging server has about 1M documents with numbers all over the content (actual content is configured as the only search field), so simple search query `1 2 3 4 5 6 7 8` takes about 25 seconds with an accompanying high CPU load.
The problem exists with a relatively small index such as the movies dataset provided by meilisearch.
All tests were performed when indexing is completed and without active tasks.

This issue is not easily manageable on the frontend by filtering search queries, so if it is not a bug but implementation trait, a configurable search time limit would be helpful.

**To Reproduce**
First case:
1. Create sandbox instance at https://sandbox.meilisearch.com/ and upload official movies dataset provided in the email instructions
2. Put text into the search box: `a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a`
3. Get very long response times resulting in ` Hits ~ 4363    Time spent 32282 ms `

Second case:
1. Create sandbox instance at https://sandbox.meilisearch.com/ and upload official movies dataset provided in the email instructions
2. Paste a very long string as a single word into the search box: https://gist.github.com/THE-FYP/c844d7a1fcfb1c6130e7e0230558d2a7
3. Hold key A in search field for a few seconds for more 'a's
4. There will be no results but search goes unresponsive. Reload the page
5. 503

**Expected behavior**
Quick response with no resource overconsumption or refusal to process the request due to exceeding the limits.

**Screenshots**
Result of running the second case on my test machine ('A' is held for about 3 secs)

https://user-images.githubusercontent.com/6823037/154342574-e467222b-a2ed-4f63-8e0e-dc61e040c0da.mp4

**Meilisearch version:** v0.25.2, v0.26.0rc0

**Comment by Kerollmops** [comment]
Thank you @THE-FYP for this analysis,

I assigned @ManyTheFish and myself on finding why those kinds of queries kill the engine. We have already reduced the number of words the engine will process to a hard limit of 10 words, no more. The second case is strange, it looks like a long long word can also affect the engine 🤔

Looking at this!

**Comment by ManyTheFish** [comment]
I'm closing this issue in favor of https://github.com/meilisearch/product/discussions/397 and https://github.com/meilisearch/meilisearch/issues/2182

**Comment by THE-FYP** [comment]
@ManyTheFish I have to clarify that first case is not the repeated words only as stated in #2182. Different short words cause this problem too. In my experience it only matters how often these words appear in the search index. For example such query with all different words `the-a-en-of-t-p-org-jpg-and-in` is resulting in `Hits ~ 1662  Time spent 9576 ms` with the same movies dataset. While some of these words may be listed as stop-words to reduce the impact on performance, it is not helpful with big search index having 1M documents containing many numbers for example, simple search query `1 2 3 4 5 6 7 8` will make meilisearch work for a long time.

**Comment by ManyTheFish** [comment]
Thanks @THE-FYP, I update my issue 😄
