### ISSUE TITLE
Filtering on an empty index returns invalid_filter

### ISSUE THREAD

**Issue by moy2010** [meilisearch/meilisearch#2180]
**Describe the bug**
When performing a search with a filter on an empty index, an `invalid_filter` error is returned.

**To Reproduce**
1. Create an index
2. Set the filterable attributes
3. Perform a search with a filter using one of the fields set in the filterable attributes

**Expected behavior**
Filtering on an empty index shouldn't return an error

**Meilisearch version:** [e.g. v0.25.0]

**Additional context**
I'm using the rust client v0.14. During the server startup, I set the index and the filterable attributes via `index.set_settings(&settings)`.

**Comment by irevoire** [comment]
Which version of meilisearch are you y using ?
I thought this bug was fixed in the v0.25.2 🤔

**Comment by moy2010** [comment]
> Which version of meilisearch are you y using ? 

Oops, I made a small mistake when editing the template :sweat_smile: . I'm using meilisearch 0.25.0. That clarifies it.

Thanks, @irevoire !
