### ISSUE TITLE
Handle Japanese by setting up Lindera tokenizer

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2185]
In progress by the community here:
- https://github.com/meilisearch/tokenizer/pull/49
- https://github.com/meilisearch/tokenizer/pull/70

If there is no answer from the community, the work should be finished to be integrated to v0.27.0

⚠️ This version of our tokenizer will NOT use `whatlang::detect_lang()` since we don't know the impact on the performance. For this first implementation, we will use only `whatlang::detect_script()` to detect the script and use Lindera accordingly or not.
The `whatlang::detect_script()` will not be perfectly efficient since Japanese documents can be detected as `Mandarin` script, and in this situation, our tokenizer will use Jieba tokenizer instead of Lindera.
A usage of `whatlang::detect_lang()` can be considered in the future but will need benchmarks to avoid any loss of performance.

Should also fix https://github.com/meilisearch/meilisearch/issues/2159

--- 

Steps
- [X] Merge https://github.com/meilisearch/tokenizer/pull/70
- [x] Release tokenizer
- [x] Bump tokenizer dependency in Milli
- [x] Release Milli with the new tokenizer dependency
- [x] Bump milli in Meilisearch

**Comment by Northn** [comment]
> @meilisearch/docs-team, I don't know if you have a page where you listed the supported languages.

https://docs.meilisearch.com/learn/what_is_meilisearch/language.html

**Comment by curquiza** [comment]
Milli was bumped in https://github.com/meilisearch/meilisearch/pull/2244, with [milli v0.24.0](https://github.com/meilisearch/milli/releases/tag/v0.24.0) containing the new version of the tokenizer. We can close this issue. The change will be effective in v0.27.0.

**Comment by curquiza** [comment]
We have an issue with Lindera compilation. I re-open this issue until we find out a fix! @Kerollmops is on it

**Comment by Kerollmops** [comment]
We are awaiting the next release of milli, the version after _v0.24.0_ which contains https://github.com/meilisearch/milli/pull/475 that uses the latest version of lindera with https://github.com/lindera-morphology/lindera/pull/164.

There were two issues:
  1. The lindera reqwest version was colliding with our own version and,
  2. lindera was downloading its dictionary from Google Drive and it was failing very often, breaking our builds, they switched to Sourceforge, which is more stable now.

**Comment by Kerollmops** [comment]
We bumped milli to v0.24.1 in https://github.com/meilisearch/meilisearch/pull/2280, so we can close this issue now.
