### ISSUE TITLE
Problem in the format of the `uid` of the Dump response

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch#2187]
**Describe the bug**
The `uid` field in response when creating dumps is bad formatted.

**To Reproduce**
Post a request on `/dumps/` route
```
curl \
  -X POST 'http://localhost:7700/dumps'
```
Response:
```
{
	"uid": "%Y%m%d-%H%M%S%3f",
	"status": "in_progress",
	"startedAt": "2022-02-21T18:07:09.436965586Z"
}
```

**Expected behavior**
Response expected:
```
{
	"uid": "20220221-181401337",
	"status": "in_progress",
	"startedAt": "2022-02-21T18:14:01.337987763Z"
}
```

**Meilisearch version:** v0.26.0-rc1

**Additional context**
The access to the dumps status route is now impossible

**Comment by curquiza** [comment]
Thanks so much @alallema 

🔥 Please could we add better tests regarding the response of the dumps route? (and every route in general) 🔥 

We should avoid missing this kind of changes 😇

**Comment by MarinPostma** [comment]
@irevoire is that related to the change from Chrono to time?

**Comment by irevoire** [comment]
Yes, I forgot to patch the formatter at this place my bad!

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/2189
