### ISSUE TITLE
Blocking calls in authentication extractor

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/meilisearch#2201]
Reviewing the auth implementation, I found that blocking calls to heed were performed in the implementation of the extractor.

- [blocking calls](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-auth/src/lib.rs#L54-L58) are made in async contexts.
- [`FromRequest`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-http/src/extractors/authentication/mod.rs#L37) should not return a `Ready` future, but a custom future, encapsulating the authentication action. a boxed future should do the trick, but it should be possible to do it more elegantly.

**Comment by curquiza** [comment]
Fixed by #2204
