### ISSUE TITLE
Proximity is time-consuming when the query contains a lot of common words

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#2202]
**Describe the bug**
Proximity is time-consuming when the query contains a lot of common words that have few chances to be near.

**To Reproduce**
- Make a search query like `1 2 3 4 5 6 7 8` or `the a en of t p org jpg and in` 
- `Hits ~ 1662 Time spent 9576 ms`

**Expected behavior**
Give a faster response

**Screenshots**

**Meilisearch version:** v0.26

**Additional context**
related to:
https://github.com/meilisearch/meilisearch/issues/2175

**Comment by loiclec** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3542
