### ISSUE TITLE
Filter does not work with BigInt

### ISSUE THREAD

**Issue by andresribeiro** [meilisearch/meilisearch#2205]
**Describe the bug**

The filter option does not work with BigInt numbers. For example, the filter "id = 4223372036854775806" returns documents with id 422337203685477580**5**, 422337203685477580**6**, 422337203685477580**7**...

But if the filter is, for example, "id = 4", it returns only the document with id 4

**Expected behavior**

Only the document with the specified id should be returned

**Meilisearch version:**

v0.25.2

**Comment by ChillFish8** [comment]
Are your documents just using regular integer fields rather than strings? If so you probably want to make the strings. It's not recommended to go beyond `[-(2**53)+1, (2**53)-1]` due to how some parsers work and general language limitations.

**Comment by andresribeiro** [comment]
@ChillFish8 I thought about doing this, but I don't think it would be possible to make a filter like id > 422...

**Comment by andresribeiro** [comment]
@Kerollmops oh okay, thx
