### ISSUE TITLE
meilisearch 0.25.2 checksum mistmatch issue

### ISSUE THREAD

**Issue by chenrui333** [meilisearch/meilisearch#2219]
**Describe the bug**

👋  it looks like the meilisearch 0.25.2 [source tarball got changed](https://github.com/Homebrew/homebrew-core/pull/96380), raising this issue to confirm if that is intended. Thanks!

**Comment by SMillerDev** [comment]
If you didn't retag this on purpose and the hash just changed that could point to a compromised git repo. Are you sure nobody recreated the tag?

**Comment by curquiza** [comment]
Hello @SMillerDev we took the time to check with @Kerollmops but we don't know why and how the first sha were even created (`5097f0...`).
We downloaded manually our tar.gz https://github.com/meilisearch/meilisearch/archive/refs/tags/v0.25.2.tar.gz and applied sha256 to find out the second hash (`544f04...`) and not the original one (`5097f0...`). This tar.gz was created 18/01/2022 and was not modified
As far as we know, the tag was not modified, and still correspond to the github release created the same day, on the same commit: https://github.com/meilisearch/meilisearch/commit/523fb5cd566f22168e89cb0af1f341d9b6f99ede

**Comment by curquiza** [comment]
FIY, we've just release v0.26.0 today -> https://github.com/Homebrew/homebrew-core/pull/96820#pullrequestreview-909043670
