### ISSUE TITLE
laravel scount brokes when using meilisearch version 0.25.2 

### ISSUE THREAD

**Issue by mohsenMJ** [meilisearch/meilisearch#2225]
**Describe the bug**
OS : Ubuntu 20.04 LTS
laravel : v8.69.0
laravel-scout : v9.3.1
meilisearch: v0.25.2

For version 0.24.0 every thing works fine but when I upgrade to version 0.25.2 the system fall apart and stops working..

and for every request to meilisearch service it returns 

`The Authorization header is missing. It must use the bearer authorization method`

please help!

**Comment by sanders41** [comment]
What version of meilisearch-php are you using? The error message makes me think an older version, it needs to be v0.22.0 to work with Meilisearch 0.25.2.

**Comment by curquiza** [comment]
Hello @mohsenMJ 

@sanders41 is right, your need to use the right meilisearch-php version to use it, so [meilisearch-php v0.22.0](https://github.com/meilisearch/meilisearch-php/releases/tag/v0.22.0).

Closing this issue :) feel free to ask to re-open if needed.
