### ISSUE TITLE
Dumps tests in CI

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2236]
Since
- we have to test the dump behavior manually
- we often get bug reports during pre-release regarding the dumps

We might want to add a CI testing the dumps behavior
- [ ] Using each already created dump file on our [public S3](https://milli-benchmarks.fra1.digitaloceanspaces.com/dumps) 
  - [ ] try to import them into Meilisearch and check it was well imported (same documents, same keys...)
  - [ ] Check the dump version file we don't support make Meilisearch send the right error message, example using dump v1 files
- [ ] Try to create a dump using the latest version of Meilisearch, and try to import it

These tests should be added to our CI in the `.github/workflows` folder

**Comment by ppamorim** [comment]
@curquiza Maybe have a look on https://github.com/localstack/localstack, we could emulate/mock the S3 using this.

**Comment by curquiza** [comment]
⚠️ We should check the API keys have been well imported as well (from Meilisearch v0.25.0)
