### ISSUE TITLE
Cargo run does not work

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2242]
**Describe the bug**
When I execute `cargo run` meilisearch panic with the following message;
```
thread 'main' panicked at 'Command meilisearch-http: Argument or group 'enable-autobatching' specified in 'requires*' for 'max-batch-size' does not exist', /home/irevoire/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.2/src/build/debug_asserts.rs:128:13
```

**To Reproduce**
1. cargo run
2. wait
3. wait

**Expected behavior**
It doesn't panic.

**Screenshots**
![image](https://user-images.githubusercontent.com/7032172/158582654-b9282bce-216c-47f9-a6d6-f363238ddff6.png)

**Meilisearch version:** running on main

**Additional context**
Additional information that may be relevant to the issue.
I use firefox.

**Comment by sanders41** [comment]
I get the same error.

**Comment by MarinPostma** [comment]
that's annoying, trying to bisect right now.

**Comment by curquiza** [comment]
How is it possible the CIs did not fail?

**Comment by curquiza** [comment]
Running on my macos (not M1), I don't have the issue on `main`...

**Comment by irevoire** [comment]
Yeah since it comes from a `debug_asserts` in clap, we probably have a bug that we can't see when running in release.

**Comment by MarinPostma** [comment]
Yeah I figured that one, but I don't know how it affects clap in the end
