### ISSUE TITLE
Add end-to-end tests: add CI importing documents to the Meilisearch server 

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2252]
To prevent having this [kind of issue](https://github.com/meilisearch/meilisearch/issues/2251) in the future, we need to add a CI that checks the Meilisearch server can receive documents and well process them.

A basic version of the CI script should
- Run the Meilisearch server without any argument
- Add a simple document, ex: `[{"id": 1, "name": "toto l'asticot"}]`
- Check the document was well processed.

The script should be run in a new job in [this file](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/rust.yml).
We also need to add this job to our [bors.toml](https://github.com/meilisearch/meilisearch/blob/main/bors.toml) file.

**Comment by Kerollmops** [comment]
The #2254 PR fixes this issue in another way: All the tests are now running with the default CLI parameters instead of the `Default` implementation. Doing so exposes the values that Clap would have given you if a user had run Meilisearch without any arguments, except the DB and dumps path.
