### ISSUE TITLE
Meilisearch Indexing takes a lot of time (4-5 days)

### ISSUE THREAD

**Issue by deadsec07** [meilisearch/meilisearch#2260]
**Indexing takes a lot of time (4-5 days)**
Indexing takes a lot of time (4-5 days), even though from the PHP end, we batch together the records. The number of records are like 20000 - 50000 each with 200 byte sized

**To Reproduce**
1. Process data from backed via a queue with batches
2. Queue processing is getting completed in no time (very fast , > 1 minute)
3. Send to Meilisearch to index via invoking the "searchable" method

**Expected behavior**
The Meilisearch STATS API show allways indexing, and TASKS API's response is quite large (<20MB), and has more than 7000 records 'enqueued'. For one record to be enqueued->succeed takes around 1 minute

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
The applcations runs on,

PHP 7.4.25 (cli) (built: Oct 22 2021 12:34:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies

Laravel Framework 8.65.0

meilisearch-http 0.25.0

Please can anybody suggest is there anything that i can do to speed up the indexing time?
Thank you.

**Comment by irevoire** [comment]
Hello, you could try to use the auto-batching feature; https://github.com/meilisearch/meilisearch/discussions/2070

**Comment by Kerollmops** [comment]
Hey @deadsec07,

We are aware of this issue and worked hard to improve the situation, you can send your feedback in [the appropriate discussion](https://github.com/meilisearch/meilisearch/discussions/2131). If you want to try out our auto-batching experimental feature you can look [at the dedicated discussion](https://github.com/meilisearch/meilisearch/discussions/2070).

We are also working on reducing the base time of indexing documents! You will see those improvements in the next release (_v0.27_).

**Comment by curquiza** [comment]
Closing this issue then since we have an already dedicated discussion :)
