### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2266]
Our README is one of the showcases of Meilisearch, we indeed got more than 9000 this month:

<img width="431" alt="Capture d’écran 2022-03-24 à 16 58 52" src="https://user-images.githubusercontent.com/20380692/159961698-a321f495-03c0-469e-a672-f4aed8699505.png">

Regarding its fame, I think we should more care about it, and maybe we should re-think our README, by making it more attractive and impactful. Indeed, I deeply think this is not the best version of README we could provide. Without making the perfect one, at least improving it since many things can be reconsidered and improved.

The core team is not the more appropriate team to solve this issue, I think we would need the help of
- @meilisearch/product-team for the feature they want to highlight
- maybe also @meilisearch/devrel-team for the communication in general
- maybe also @meilisearch/docs-team for the review, and also what examples could be great for the users

Some parts we could reconsider (I'm not saying it's bad, I say this is the opportunity to reconsider)
- the title: `Lightning Fast, Ultra Relevant, and Typo-Tolerant Search Engine`
- the description
- the gif of the mini-dashboard
- highlight the feature? If yes, which ones?
- Highlight some integrations
- "how to install meilisearch" examples: I'm not sure we are showing the most simple ways to launch with Meilisearch. Should we show all the alternatives?
- highlight the DO and platform.sh one-click button
- the size of the README in general (maybe too long?)
- add a link to one of our deployed demos? make people test meilisearch via a search bar as quickly as possible
- Link to our [demos](https://github.com/meilisearch/demos) repo?
- Link to our [awesome meilisearch](https://github.com/meilisearch/awesome-meilisearch) repo?
- the topic description and the tags (top right of the repo home page)
- any other part I forget...

If you have any other ideas, don't hesitate to put them in comments here. I will initiate the beginning of the job by probably setting up some working groups :) this issue is just to let you know!

**Comment by bidoubiwa** [comment]
If I remember correctly @irevoire received multiple feedbacks from acquaintances that the gif from the readme should go with a link to the demo of the same dataset so that users can try it out immediately.

**Comment by irevoire** [comment]
Yes, I showed our repo to a bunch of friends, and their first question was always, « cool, but where can I try it ». And by « try it » they meant « show me a search bar where I can type something without configuring anything

**Comment by gmourier** [comment]
@irevoire We could kill two birds with one stone. Moving a visible demo link at the top-most section, plus linking to the movies demo revamped.

**Comment by guimachiavelli** [comment]
The @meilisearch/docs-team would also be happy to help 👍 
I think a short meeting could be useful in reaching a consensus—I'm particularly curious about @meilisearch/devrel-team's perspective on what's the best type of content to have on our main repo's readme.

**Comment by curquiza** [comment]
I will organize meetings, who wants to represent @meilisearch/devrel-team and @meilisearch/docs-team? (one for each team)
Same question for @meilisearch/product-team?

A meeting of 4 people is wayyy enough to start.

**Comment by CaroFG** [comment]
🙋🏻‍♀️

**Comment by gmourier** [comment]
👋

**Comment by guimachiavelli** [comment]
✨

**Comment by curquiza** [comment]
Here are the meeting notes we had today

Involved people: @CaroFG, @guimachiavelli, @gmourier, @curquiza 

### Goals of the meeting

- Define what we expect for the Meilisearch README
- List every part we want to reconsider

## Purpose of the README

- A short README
- TOC (depending on the size of the README)
- Useful links easily accessible: Slack, docs...
- An easy and highligted way to try Meilisearch on an existing demo!
- Clear information about the product, what is the point of this project
- Start quicky to use the product**: f**ind the documentation or have a quick start. We don’t want a really detailed documentation
- Section to promote the integrations
- A more developer-relation part: where can I let a feature request? Where can I ask a question? Who can I contact?
- Telemetry section: remind about the telemetry and how to disable them
- Contributor section at the end? Not an exhaustive list of contributors, but we want at least to thank the community. Should be quick but nice and thankfull.

## What we want to reconsider

- Top right part
    - tags: focus on what is the purpose of the tags before defining them.
    - link: landing or docs?
    - Catchy phrase description: should be short and clear
        - “An open-source, lightning-fast, and hyper-relevant search engine”
        - “Shape a delightful search experience in a snap”
        - ...
- Gif → keep it, but maybe another gif in the future, why not demo movies.
- Header
    - Logo in the header → could be centered, more beautiful
    - Header link → only appropriate ones (remove LinkedIn and Twitter, then add Slack?)
    - Header badges → Remove github discussion and slack?
    - Quick description → same as the “About” at top right?
- First description of the product + more detailed description → Keep them but improve them. It does not have to be too long.
- Getting started → remove it and replace it by documentation links (quick start, some useful tutorials, API reference...). Also promote the cloud in the future.
- Documention section → be removed an put in the section above
- Core engine and tokenizer → put in [contributing.md](http://contributing.md/)
- Telemetry → keep it but re-work it
- Contributing, Contact Us, Feature request → should be put in a more “developer-relation” section

## What’s next?

- Clem will provide a plan of the future README on Notion. Gui, caro and guigui will review and comment it. Other Meili people opinion will be welcome.
- When we will find the best README plan, Clem will dispatch the work to each team
