### ISSUE TITLE
The task status has frozen

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/meilisearch#2274]
### Discussed in https://github.com/meilisearch/meilisearch/discussions/2273

<div type='discussions-op-text'>

<sup>Originally posted by **oswaldB** March 28, 2022</sup>
Hello,

My tasks are frozen after adding 177K+ documents of 30 fields. It works fine upto the index 33892. But it has been 7 days, the tasks are not processing anymore.

Is there a way to restart the tasks? 

thank you so much</div>

**Comment by oswaldB** [comment]
Hello,

I use meilisearch installed on GCP : https://docs.meilisearch.com/learn/cookbooks/gcp.html
My version is 0.26.0

**Comment by curquiza** [comment]
Hello @oswaldB sorry for the inconvenience

- can you share your Meilisearch log?
- can you give us your CLI arguments? I mean, the options you use to start meilisearch, `meilisearch --no-analytics --masterKey=XXX`

**Comment by curquiza** [comment]
Closing this due to lack of answer and information.
Feel free to re-open if needed
