### ISSUE TITLE
V0.27 Breaking change with attributesToRetrieve's impact on _formatted field

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2318]
**Describe the bug**
In v0.26 when `attributesToRetrieve` did not impact `attributesToHighlight` or at least it did not in the example showed beneath. 

Nonetheless the specification seems to say that `attributesToRetrieve` should impact `attributesToHighlight` 

**To Reproduce**

given the following very minimal dataset: 

```json
[ {
      "id": 1,
      "title": "Pride and Prejudice",
      "comment": "A great book"
 }]
```

1. Index the dataset, no settings required
2. Make a search with the following parameters: 
```json
{
      "attributesToRetrieve": ["id", "title"],
      "attributesToHighlight": ["*"],
}
```
3. In the results `comment` is not inside `_formatted`

**Expected behavior**
Mark as breaking change

**Meilisearch version:** [e.g. v0.20.0]
v0.27.0.rc0

**Comment by bidoubiwa** [comment]
As per the spec 

https://github.com/meilisearch/specifications/blob/main/text/0118-search-api.md#1218-attributestohighlight it seems that this behavior is what is expected!

**Comment by bidoubiwa** [comment]
Re-opening as it is still a breaking change. 
Not sure if the previous behavior was incorrect or if this one is. 

Following [this comment](https://github.com/meilisearch/specifications/pull/120#discussion_r828336878): 

> If a list of fields is defined for `attributesToRetrieve` and `attributesToHighlight` / `attributesToCrop` contains a list of fields, `_formatted` is returned and contains `attributesToRetrieve` fields, plus the fields set in `attributesToHighlight` or `attributesToCrop` then compute highlights and crops only for fields defined in attributesToHighlight / attributesToCrop parameters.

In this case, it seems that my issue is a  a bug

Nonetheless following [this spec](https://github.com/meilisearch/specifications/blob/main/text/0118-search-api.md#1218-attributestohighlight): 

> If "*" is provided as a value: attributesToHighlight=["*"] all the attributes present in attributesToRetrieve will be assigned to attributesToHighlight.

Which implies the opposite. Unless I'm mistaken

**Comment by curquiza** [comment]
This breaking change was not highlighted by this spec: https://github.com/meilisearch/specifications/pull/120
Is it expected @gmourier, what is the expected behavior for v0.27.0?
