### ISSUE TITLE
G

### ISSUE THREAD

**Issue by Corn68** [meilisearch/meilisearch#2324]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Considered as spam since no issue is described. Please open another detailed issue to describe any problem you could have when using Meilisearch, if you have any.
