### ISSUE TITLE
Slow queries with repeating words

### ISSUE THREAD

**Issue by K3das** [meilisearch/meilisearch#2327]
**Describe the bug**
A search query with a long string of repeating words that appear in the data causes the queries to become very slow.

**To Reproduce**
1. Load a data set, I was testing this on the example movies data
2. Enter a search query of a repeated common word in the data, for example "a a a a a a a a a a a a a a a a a"
3. Query would take a very long time, almost 3s in my case

**Expected behavior**
A faster query (I'm not sure if this is possible, so correct me if I'm wrong)

**Screenshots**
![image](https://user-images.githubusercontent.com/20052500/163694894-5096eff1-42f6-4a0f-8300-858e66daeb1f.png)

**Meilisearch version:** 0.26.1

**Additional context**
16GB of RAM and and a AMD Ryzen 7 5800H, so CPU or RAM shouldn't be causing this

**Comment by curquiza** [comment]
Hello @K3das thanks for your report and sorry for the inconvenience!

@ManyTheFish can you confirm this is a duplication of https://github.com/meilisearch/meilisearch/issues/2202?

**Comment by ManyTheFish** [comment]
@curquiza, yes it's the same issue 🙂

**Comment by curquiza** [comment]
Ok, I close this in favor of #2202 then!
Thanks again @K3das for your issue
