### ISSUE TITLE
Setting field ordering is invalid

### ISSUE THREAD

**Issue by jw-star** [meilisearch/meilisearch#2333]
**Describe the bug**
Setting field ordering is invalid

**To Reproduce**
```
# client.index(indexName).update_ranking_rules([
#     "sort",
#     "typo",
#     "words",
#     "proximity",
#     "attribute",
#     "wordsPosition",
#     "exactness",
# ])
```
```
# print(client.index(indexName).search('4P', {
#     'sort': ['id:desc']
# }))
```
result: 
Results are not sorted by id

**Comment by irevoire** [comment]
Hello, can you show me your documents and the result of your query?
And are you sure the update finished processing?

**Comment by jw-star** [comment]
> Hello, can you show me your documents and the result of your query? And are you sure the task finished processing?
> 
> You can check it using this route: https://docs.meilisearch.com/reference/api/tasks.html#get-all-tasks

Thank you very much, I added the attribute ranking of the location in the global settings, and the modification was not successful
