### ISSUE TITLE
Error message when `oneTypo `/`twoTypos` is greater than 255

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/meilisearch#2337]
**Describe the bug**
When `oneTypo `/`twoTypos` is greater than 255, Meilisearch throws a `bad_request` error. According to the [spec](https://github.com/meilisearch/specifications/pull/117/files), it should be `invalid_typo_tolerance_min_word_size_for_typos ` 

**To Reproduce**
1. Set `oneTypo `/`twoTypos` to greater than 255:
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/settings/typo-tolerance' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "minWordSizeForTypos": {
      "oneTypo": 255,
      "twoTypos": 256
    }
  }'
```

**Expected behavior**
Error from the [spec](https://github.com/meilisearch/specifications/pull/117/files):
```
{
    "message": "`minWordSizeForTypos` setting is invalid. `oneTypo` and `twoTypos` fields should be between `0` and `255`, and `twoTypos` should be greater or equals to `oneTypo` but found `oneTypo: :oneTypo` and twoTypos: twoTypos`.",
    "code": "invalid_typo_tolerance_min_word_size_for_typos",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#invalid_typo_tolerance_min_word_size_for_typos"
}
```

**Screenshots**

![Screen Shot 2022-04-21 at 00 09 04](https://user-images.githubusercontent.com/90181761/164316430-39fe46b1-c458-4a7d-b780-7d5f7e15c2f7.png)

**Meilisearch version:** v0.27rc2

**Comment by MarinPostma** [comment]
This is not a bug, but expected behavior until we have better control over the error returned by serde.

Seen with @gmourier
