### ISSUE TITLE
Telemetry: Add `X-Meilisearch-Client` header

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#2367]
Why?
Following this [comment](https://github.com/meilisearch/integration-guides/issues/150#issuecomment-966360488) pointing out that some browsers forbid the customization of the User-Agent header, the analytics stack can now take the value of a `x-meilisearch-client` query parameter if found instead of the user-agent header to track the usage of our SDKs/Integrations.

Spec: https://github.com/meilisearch/specifications/pull/145

Reminder: the telemetry can be disable at any moment using the `--no-analytics` flag when launching Meilisearch
```bash
meilisearch --no-analytics
```
----

⚠️ EDIT ⚠️

After discussion with @brunoocasali, @Kerollmops and @irevoire, it appears adding a query parameter is not a good solution (cf the [related specification PR description](https://github.com/meilisearch/specifications/pull/150#issue-1241650655))
Instead, we will use the `X-Meilisearch-Client` header for front-end integration analytics

Please refer to the specification: https://github.com/meilisearch/specifications/pull/150

**Comment by gmourier** [comment]
👍  Beware of writing in the right format because the engine will not do case insensitivity matching on it. So you could lose metrics on an SDK release if a mistake is made.

**Comment by curquiza** [comment]
My bad! I did not realized that!

**Comment by curquiza** [comment]
@meilisearch/docs-team @meilisearch/integration-team 
I've udpated the issue description: we are not adding an query parameter but a header!

**Comment by guimachiavelli** [comment]
Just to confirm: the header must be capitalised as described on the issue title, correct? Meaning, `X-Meilisearch-Client` and not `x-meilisearch-client`.
