### ISSUE TITLE
Add limit of facet value and a setting to let the users customize it

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2368]
Following this issue: https://github.com/meilisearch/meilisearch/issues/2349
Validated with @gmourier and @Kerollmops 

For performance reasons, Meilisearch should limit the number of facet values to `1000`.

Customizing this limit could be considered in the future. If you want it, please open a [discussion in the product repository](https://github.com/meilisearch/product/discussions).

-----

New update on 2022-06-08

Decided with @gmourier, following this spec: https://github.com/meilisearch/specifications/pull/157 
To avoid the users being stuck with this limit using v0.28.0, we want to introduce a setting to let them customize it to their needs.

Task
- [ ] Introduce a `faceting` settings API resource. `GET/PATCH/DELETE` - `/indexes/:indexName/settings/faceting`
- [ ] In the `faceting` setting object, a field is present: `maxValuesPerFacet` property - Type: Integer - Default to `100`
- [ ] Add tests

**Comment by gmourier** [comment]
What do you think about delaying this to v0.29 so that you can integrate customization settings like the maximum limit for search results?

I would like to avoid blocking users for whom this is not necessarily a problem and who could end up being blocked if we add a non-configurable limit.

**Comment by curquiza** [comment]
@meilisearch/docs-team @meilisearch/integration-team

A setting to customize this limit has been introduced. The reasons and how it will be implemented are described in this issue description
