### ISSUE TITLE
End-user pagination: the product vision

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2370]
Currently, Meilisearch does not have the possibility to let the users do finite pagination because it does not return an exhaustive number of matches. See:
- https://github.com/meilisearch/documentation/issues/561
- https://github.com/meilisearch/product/discussions/335
- https://github.com/meilisearch/product/discussions/467

I open this issue, but nothing has to be implemented on the core side.
@gmourier @bidoubiwa and @guimachiavelli are already working on defining the product vision regarding the end-user pagination. This has to be handled:
- on the @meilisearch/product-team side by created clear discussions to gather the feedback of the users potentially wanting to get this exhaustive number of match
- on the @meilisearch/docs-team side by creating a complete guide "how to paginate with Meilisearch" showing which kind of pagination we promote and redirect the users to the product discussions for any requests.

Also pinging @meilisearch/integration-team FYI since you often have issues related to the finite pagination of the users.

**Comment by guimachiavelli** [comment]
Should this be tied to the v0.28 milestone, though? I understand we need to supply this guide ASAP, but unless I misunderstand it we could have this up any time before or after v0.28 is released, no?

**Comment by curquiza** [comment]
Indeed, you're right, if it's done before it's even better 😄 
The deadline (with DEAD inside, like this is the maximum 😂) is the v0.28.0 release to help users. In v0.28.0 some of them will find out they cannot use `nbHits` (because of the name change) and will need a guide to help them switch from their pagination to the one we recommend.

**Comment by curquiza** [comment]
I can close it gui if everything is ready to be done (not already written yet) on your side, WDYT?

**Comment by guimachiavelli** [comment]
Hmmm…the reason why I'm suggesting separating the guide from v0.28 is because I'm not sure we'll have enough resources to do all the updates absolutely required by v0.28 AND write a new full guide. I do appreciate how pagination will become more critical for basic Meilisearch usage once v0.28 is out.

@dichotommy. what do you think?

**Comment by curquiza** [comment]
> on the https://github.com/orgs/meilisearch/teams/product-team side by created clear discussions to gather the feedback of the users potentially wanting to get this exhaustive number of match

This has been done with https://github.com/meilisearch/product/discussions/483

> on the https://github.com/orgs/meilisearch/teams/docs-team side by creating a complete guide "how to paginate with Meilisearch" showing which kind of pagination we promote and redirect the users to the product discussions for any requests.

We removed confusion during the yesterday's meeting: based on [this draft](https://www.notion.so/meilisearch/Navigate-through-search-results-ef75d82a75b74df6b1e86d2585cba628) (internal only sorry) docs team will create the first pagination guide. The following kind of pagination should be present:
- Page selection pagination
- Prev/Next button pagination
Other kinds of pagination exist but are not a priority to put in the guide
- Infinite scroll
- Load more

I close this issue since the work is in the docs team's hands now! Feel free to ask any additional questions if needed! 😊

**Comment by dichotommy** [comment]
Hello, coming in late to this conversation 👋🏻

I just wanted to confirm that @meilisearch/docs-team is planning to edit and release the pagination guide with v0.28. However, if we run out of time before the release, we will prioritize updating the documentation to be accurate with the new version. For our team and product's goals, maintaining accurate documentation is more important than releasing a new guide that is not directly related to the release.

Of course we will try our best so this does not happen, but it is a possibility—this version has a massive impact on the API, and on top of that @meilisearch/docs-team is down a person (me) for this release. We will try our best to keep you informed! 🤝

**Comment by curquiza** [comment]
> it is not necessary to comprehensively solve the problem of pagination for users with this release, but it is necessary to offer some kind of support or direction on how we expect users to paginate with Meilisearch.

Exactly, especially regarding the "page selection" pagination (which basically is "I can click to access any page, including the last one")

> Thanks to the first draft from @gmourier and @bidoubiwa (🧱) we should not have a problem releasing a pagination guide with v0.28, but as you said it may be a less-than-perfect version.

Regarding the time "less-than-perfect version" is perfect for me 😄 

Again, sorry for the lack of clarity.
