### ISSUE TITLE
use cargo run --release run from code source could not compile.

### ISSUE THREAD

**Issue by endingman** [meilisearch/meilisearch#2379]
build faild:
![image](https://user-images.githubusercontent.com/16915802/167096861-264e7e43-3b0e-4d68-aca8-1d5605a08de3.png)
error: there is no argument named `base_key` and there is no argument named `key`

**Comment by irevoire** [comment]
Hello, sorry that’s because we use the [“capture identifiers in format strings”](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings) feature of the rust compiler which came out in 1.58. I guess you need to update your compiler.
```
rustup update
```

**Comment by endingman** [comment]
> Hello, sorry that’s because we use the [“capture identifiers in format strings”](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings) feature of the rust compiler which came out in 1.58. I guess you need to update your compiler.
> 
> ```
> rustup update
> ```

Thanks，it is work now.
