### ISSUE TITLE
Searching for 本田 yields all results with 本

### ISSUE THREAD

**Issue by cheewoei1997** [meilisearch/meilisearch#2390]
**Describe the bug**
When searching for mandarin characters, for example '本田' which is the mandarin character for Honda, the search results returns to all results with individual characters which are 本&田, rather than 本田. both are very different in meaning and the desired outcome is to return results for both characters only.

Referring to the screenshot, the term '本田' was searched, but '本地' was also shown. These two words hold very different meaning.

**To Reproduce**
1. Create indexes for documents with mandarin titles and descriptions
2. Search for said articles

**Expected behavior**
Articles which does not have the characters should not show up in the search.

**Screenshots**
![Example search results](https://user-images.githubusercontent.com/14294811/168035736-61824751-afdf-4e16-b70d-8ad281c55fe6.png)

**Meilisearch version:**
v0.15.1

**Additional context**
We're using meilisearch as the default search for the Chinese language.

**Comment by oluademola** [comment]
Hello @cheewoei1997  👋

I'm sorry for the inconvenience.

We only maintain the latest version of Meilisearch and perhaps this is most likely to have been resolved in this version. 

We recommend you upgrade to the latest version and if this issue persists, please do not hesitate to open a new issue. I'll proceed to close this one.

Thank you very much 🙂
