### ISSUE TITLE
Improve the geosearch error message

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2398]
A typical document containing a geo field should look like this;
```JSON
{
  "id": 1,
  "_geo": {
    "lat": 12.15,
    "lng": 42.38
  }
}
```

It gets flattened in the engine to something like that;
```JSON
{
  "id": 1,
  "_geo.lat": 12.15,
  "_geo.lng": 42.38
}
```

Thus, when we're indexing the geopoint, all we can check is if we can find the `_geo.lat` and `_geo.lng` fields.
If we find both, then we can go on and index the document.
If we find one of the two, we know the person is probably trying to index a document but missed a latitude or longitude.

But if we find none of the two, currently, we consider that the document did not contain any `_geo` field and did not index anything.
It's not the best because, for example:
```JSON
{
  "id": 1,
  "_geo": "plouf"
}
```

Or
```JSON
{
  "id": 1,
  "_geo": {
    "latitude": 12.45,
    "longitude": 32.65
  }
}
```
Won't throw any error.

**Comment by curquiza** [comment]
Thanks for the issue @irevoire 

@gmourier, once an implementation decision is done, the spec will need to be updated (not necessarely by you) but I ping you so that you are aware of it 😇

**Comment by curquiza** [comment]
Fix with the auto-batching integration by default 🎉
