### ISSUE TITLE
Improve ranking rules error message

### ISSUE THREAD

**Issue by juchom** [meilisearch/meilisearch#2407]
**Describe the bug**
When changing the rules, the error message is misleading. According to the code :

https://github.com/meilisearch/meilisearch/blob/6d221058f19f9f262a99245882176ae9b7d48bec/meilisearch-http/tests/settings/get_settings.rs#L285-L290

Accepted rules are `Words, Typo, Sort, Proximity, Attribute, Exactness` in fact accepted rules are `words, typo, sort, proximity, attribute, exactness`

**To Reproduce**
Try sending a rule with a capital letter

**Expected behavior**
The rule name is case insensitive and the endpoint needs a fix and the error message is correct.

The rule name is case sensitive and the error message needs a fix to match this requirement.

**Meilisearch version:** [e.g. v0.27.1]

**Comment by curquiza** [comment]
Hello @juchom 

Thanks for this report, I put it as good first issue. The change should be done on the [milli's repo](https://github.com/meilisearch/milli).
For any person who wants to contribute: feel free to ask any question or help 😄

**Comment by MarinPostma** [comment]
hello @YanivDan, a PR has already been opened to address this issue here https://github.com/meilisearch/milli/pull/536. Thanks for helping out!

**Comment by MarinPostma** [comment]
closed by https://github.com/meilisearch/milli/pull/536

**Comment by curquiza** [comment]
I re-open, we will close it once the fix is available in Meilisearch 😊 
Will be closed by #2468
