### ISSUE TITLE
authentication_error with correct Authorization headers.

### ISSUE THREAD

**Issue by aleixisp** [meilisearch/meilisearch#2421]
**Describe the bug**
After Setting up the master key to access the API of meilisearch I get authorization is required (401) even though I'm passing such key in the headers

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your local machine (Digital Ocean droplet)
2. Call `meilisearch-setup`
3. Set an API key, no need to set up a domain. (Consul is set up so the domain name is provided by Consul)
4. Perform a call which requires passing the masterKey, such as: `GET http://localhost:7700/keys`

**Expected behaviour**
I would see an empty list since no keys are created yet.

**Screenshots**
Screenshot of the terminal with the issue
![Screenshot 2022-05-24 at 10 19 32](https://user-images.githubusercontent.com/54447877/169984303-c2efc691-f295-4e52-b0f4-98f7a78aec51.png)

**Meilisearch version:** [e.g. v0.20.0]
I can't access /version endpoint because of the same issue described above.
The only information I can provide is that the droplet name is when it was created: Debian meilisearch-2021-10-20T14:06:52Z

**Comment by CaroFG** [comment]
Hi @aleixisp!

Could you please try with the following header?

`X-Meili-API-Key: masterKey`

**Comment by CaroFG** [comment]
What version of Meilisearch are you using? The `X-MEILI-API-KEY: <apiKey>` header was replaced by the `Authorization: Bearer <apiKey> header` on v0.25

**Comment by CaroFG** [comment]
The latest SDKs versions ensure compatibility only with the latest Meilisearch version but you can use older package versions. You can check the releases of the python package and their compatibility [here](https://github.com/meilisearch/meilisearch-python/releases)

**Comment by CaroFG** [comment]
And you are probably right, maybe we should add that information in the docs, I have created an [issue](https://github.com/meilisearch/documentation/issues/1649)

**Comment by aleixisp** [comment]
Thanks! Really appreciate it, we currently have 0.23.1, and will schedule an update of the service for my team. 
👍
