### ISSUE TITLE
Create custom error types for parsing issues

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#2443]
We should create custom error types for when we parse the `TaskType`, and `TypeStatus` in our `FromStr` implementations. The same applies to the `IndexUid::new` method that returns an `IndexResolverError`, we should implement the right `IndexResolverError::from` for a custom error type too.

It would be much more Rust idiomatic and easier to work with.

---

We have [a `String` error for the `TaskType` and `TypeStatus` structs](https://github.com/meilisearch/meilisearch/pull/2399#discussion_r884592697) and `FromStr` implementation for `IndexUid` returns an `IndexResolverError`, this is not super consistent, maybe we want a custom error type for this error?

_Originally posted by @MarinPostma in https://github.com/meilisearch/meilisearch/pull/2399#discussion_r884579948_

**Comment by walterbm** [comment]
@Kerollmops I would be interested in working on this issue if that's possible!

I'm relatively new to Rust so I might need some guidance before I can wrap my head around this issue.

From what I understand the task would be to create something like `TaskTypeParseError` and `TypeStatusParseError` enums and use that instead of bare strings for the `FromStr` implementation of `TaskType` and `TypeStatus`?  And these custom errors should match the pattern set by the [`IndexResolverError`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-lib/src/index_resolver/error.rs#L12-L30) which leverages `thiserror` and carry `String` associated values for user-facing messages?

Is that on the right track for what needs to be done?

**Comment by Kerollmops** [comment]
> @Kerollmops I would be interested in working on this issue if that's possible!

It's absolutely possible, you can take it and open a PR 😃

> From what I understand the task would be to create something like `TaskTypeParseError` and `TypeStatusParseError` enums and use that instead of bare strings for the `FromStr` implementation of `TaskType` and `TypeStatus`? And these custom errors should match the pattern set by the [`IndexResolverError`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-lib/src/index_resolver/error.rs#L12-L30) which leverages `thiserror` and carry `String` associated values for user-facing messages?
> 
> Is that on the right track for what needs to be done?

I am not sure that `TaskTypeParseError` and `TypeStatusParseError` should be enums, you can create simple structs and make sure that they [implement the `Error` trait](https://doc.rust-lang.org/nightly/std/error/trait.Error.html) for it to work correctly with the other types. These custom error types should only implement `Display` (needed by `Error`) as it is directly returned by serde when deserialized [from the `TaskFilterQuery` struct](https://github.com/meilisearch/meilisearch/blob/681b9219606c9c8530d82e49424dfef42ca29bcc/meilisearch-http/src/routes/tasks.rs#L21-L28).

I am not sure we want to keep `IndexUid::new` but maybe make `IndexUid` implement `FromStr` and return a custom error struct like the above types I described. This custom error type should be returned to the user via the `IndexResolverError`, so [you should implement `From` to convert types](https://doc.rust-lang.org/std/convert/trait.From.html).

**Comment by walterbm** [comment]
@Kerollmops sounds good! Thank you for the guidance & patience!

I think I understand what to do with `TaskType` and `TypeStatus` so I started working on that piece.

But I'm a bit confused on the updates that are needed for `IndexUid`. Looks like `IndexUid` already implements [`FromStr`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-lib/src/index_resolver/mod.rs#L92) which calls `IndexUid::new` and returns a `IndexResolverError`. Is the idea that `IndexUid::new` should return a new custom error and then that the custom error should implement `impl From<CustomError> for IndexResolverError`? Or should  `IndexUid::new` be removed entirely and have its logic moved to `FromStr`?

**Comment by Kerollmops** [comment]
> I think I understand what to do with `TaskType` and `TypeStatus` so [I started working on that piece](https://github.com/walterbm/meilisearch/tree/add-custom-errors-for-tasktype-taskstatus-indexuid).

Looks already quite good, thank you! However, I would rather format the message at the moment you need to print it (in the `Display` impl).

> But I'm a bit confused on the updates that are needed for `IndexUid`. Looks like `IndexUid` already implements [`FromStr`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-lib/src/index_resolver/mod.rs#L92) which calls `IndexUid::new` and returns a `IndexResolverError`. Is the idea that `IndexUid::new` should return a new custom error and then that the custom error should implement `impl From<CustomError> for IndexResolverError`? Or should `IndexUid::new` be removed entirely and have its logic moved to `FromStr`?

Maybe we can get rid of the `IndexUid::new` method and only keep the `FromStr` impl first, just to keep being consistent and always use the `FromStr` one. I would also say that you should maybe return a custom error instead of the `IndexResolverError` one that can be converted into the `IndexResolverError` one.

Thank you very much for the time you take to work on this, very appreciated!

**Comment by walterbm** [comment]
@Kerollmops I opened up #2460 with my attempt at fixing this issue. I'm not entirely happy with the state of the code in that PR but I wanted to make sure _something_ was available for you to review. 

If you have any feedback I'll gladly make improvements! Thanks again for the help!
