### ISSUE TITLE
Failing to start docker container when there is a `lost+found` directory present

### ISSUE THREAD

**Issue by ohemelaar** [meilisearch/meilisearch#2457]
**Describe the bug**
Starting the Meilisearch docker image with a volume that contains a `lost+found` folder fails with the following error:
```
Error: Version file is missing or the previous MeiliSearch engine version was below 0.24.0. Use a dump to update MeiliSearch.
```

**To Reproduce**
```bash
mkdir -p data.ms/lost+found
docker run --rm -v $(pwd)/data.ms:/data.ms getmeili/meilisearch:v0.25.2
# Error: Version file is missing or the previous MeiliSearch engine version was below 0.24.0. Use a dump to update MeiliSearch.
```

**Expected behavior**
Apparently, some cloud providers include that `lost+found` directory in newly provisioned volumes to use in Kubernetes.
I guess that Meilisearch thinks that there is an existing install as the volume is not empty, and thus refuses to create the version file itself.
So my expectation is that the `lost+found` directory being present should not count as an "existing install".

**Meilisearch version:** `0.25.2`

**Additional context**
Issue initially encountered when deploying on Kubernetes provided by Scaleway. Storage class is `scw-bssd`.

**Comment by ohemelaar** [comment]
I had to update to Meilisearch `0.26.1` for another issue and it had the same behavior.

**Comment by oluademola** [comment]
Hi @ohemelaar 

I can confirm that this isn't a bug. The `mkdir -p data.ms/lost+found` command will attempt to create a `data.ms` directory if it doesn't exist which will result in starting meilisearch with an empty database (data.ms). I believe you ran into this issue because you did not have an existing meilisearch database (data.ms). With valid `data.ms` I did a test on my end and it works fine.

Hope this helps. Thank you.

**Comment by ohemelaar** [comment]
Hi @oluademola, thanks for the reply.

I think I should rephrase my issue though, now that I have looked around a little bit more especially about the role of the `lost+found` directory.

What I notice is that Meilisearch will fail to start if to root of an `ext4` partition is mounted on the `data.ms` directory. That is because an `ext4` partition will have a `lost+found` directory at the root. Maybe what I'm talking about is more of a feature request then ?

**Comment by ohemelaar** [comment]
I failed to notice last time but this issue was already seen in https://github.com/meilisearch/meilisearch/issues/2166.

**Comment by oluademola** [comment]
@ohemelaar indeed, that's a good catch. With the most recent version, this shouldn't happen. Feel free to reopen the issue if you have any problems with it.
