### ISSUE TITLE
`/indexes/movies/tasks` and `/indexes/movies/tasks/:uid` endpoints result in a 404

### ISSUE THREAD

**Issue by phanirithvij** [meilisearch/meilisearch#2458]
**Describe the bug**

<details><summary>The global <code>/tasks</code> endpoint gives results properly.</summary>

```sh
curl \
  -X GET 'http://localhost:7700/tasks'
```
```
{"results":[{"uid":0,"indexUid":"movies","status":"succeeded","type":"documentAdditionOrUpdate","details":{"r
eceivedDocuments":19547,"indexedDocuments":19547},"duration":"PT205.813694S","enqueuedAt":"2022-06-03T10:08:56.2076732Z","startedAt":"2022-06-03T10:08:56.
2175593Z","finishedAt":"2022-06-03T10:12:22.0312533Z"}],"limit":20,"from":2,"next":null}
```
</details>

<details><summary>But <code>/idexes/movies/tasks/:uid</code> and <code>/indexes/movies/tasks</code> give 404</summary>

```sh
curl \
  -X GET 'http://localhost:7700/indexes/movies/tasks'
curl \
  -X GET 'http://localhost:7700/indexes/movies/tasks/0'

[2022-06-03T11:16:10Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /indexes/movies/tasks HTTP/1.1" 404 0 "-" "curl/7.79.1" 0.000116
[2022-06-03T11:19:59Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /indexes/movies/tasks/0 HTTP/1.1" 404 0 "-" "curl/7.79.1" 0.000103
```
</details>
I do have movies in indexes.
<details><summary>Here is the <code>/indexes</code> result</summary>

```
{"results":[{"uid":"movies","createdAt":"2022-06-03T10:08:56.2728929Z","updatedAt":"2022-06-03T11:02:20.2181589Z","primaryKey":"id"}],"offset":0,"limit":20,"total":1}
```
</details>

**Expected behavior**
They should not be 404 or the documentation needs to be updated if they are moved to somewhere else.

https://docs.meilisearch.com/reference/api/tasks.html#get-all-tasks-by-index

**Meilisearch version:**

<details><summary>on latest commit on main branch</summary>

```
Database path:          "./data.ms"
Server listening on:    "http://127.0.0.1:7700"
Environment:            "development"
Commit SHA:             "b83455f345cc42d0fac579daebb25e4783945344"
Commit date:            "2022-06-02T15:01:43Z"
Package version:        "0.27.1"
```
</details>

**Additional context**

- I am on the main branch, not pinned to any version
- Not using any master key

<details><summary>Windows 10</summary>

```
Edition	Windows 10 Home Single Language
Version	21H1
Installed on	‎07-‎08-‎2020
OS build	19043.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz
Installed RAM	8.00 GB (7.84 GB usable)
System type	64-bit operating system, x64-based processor
```
</details>

**Comment by Kerollmops** [comment]
Hey @phanirithvij,

Indeed, if you are on the main branch of the repository, we changed the API to get the tasks, all [the tasks are now accessible from one single route](https://github.com/meilisearch/specifications/pull/116), the `/tasks` one.

You can filter by `indexUid`, `status`, and `type`. This route also [support seek-based pagination](https://github.com/meilisearch/specifications/pull/115).

**Comment by phanirithvij** [comment]
So the documentation is yet to be updated? got it.

**Comment by gmourier** [comment]
Hello @phanirithvij

The current state of the main branch has not been officially released, so the documentation is not yet up to date.

These changes will be documented when version v0.28.0 is released.

In the meantime, you can look at the specifications for the endpoint `tasks` to find the changes there:

https://github.com/meilisearch/specifications/pull/115
https://github.com/meilisearch/specifications/pull/116

**Comment by curquiza** [comment]
Hello @phanirithvij 

I close this issue since it is related to v0.28.0 which has not been released yet.

I recommend following [the documentation](https://docs.meilisearch.com/learn/getting_started/quick_start.html#local-installation) (`Source` tab) that indicates to choose a specific tag when compiling from the source.
Indeed, `main` is our development branch and should not be used for production, only for the maintainers.

Have a nice day! 👋
