### ISSUE TITLE
Please, what does this error mean? how to correct?

### ISSUE THREAD

**Issue by topmask** [meilisearch/meilisearch#2467]
Database path:		"./data.ms"
Server listening on:	"http://127.0.0.1:7700"
Environment:		"development"
Commit SHA:		" xxxxxxxxxxxxxxxxxxxxxxxxxxx"
Commit date:		"2022-05-17T10:09:16Z"
Package version:	"0.27.1"

Thank you for using Meilisearch!

We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html

Anonymous telemetry:	"Enabled"
Instance UID:		"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

No master key found; The server will accept unidentified requests. If you need some protection in development mode, please export a key: export MEILI_MASTER_KEY=xxx

Documentation:		https://docs.meilisearch.com
Source code:		https://github.com/meilisearch/meilisearch
Contact:		https://docs.meilisearch.com/resources/contact.html

Error: Address already in use (os error 98)

**Comment by topmask** [comment]
/etc/systemd/system/meilisearch.service

```
[Unit]
Description=Meilisearch
After=systemd-user-sessions.service

[Service]
Type=simple
ExecStart=/usr/bin/meilisearch --http-addr 127.0.0.1:7700 --env production --master-key xxxxxxxxxxxxxxxxxxxx

[Install]
WantedBy=default.target

```

**Comment by oluademola** [comment]
Hi @topmask 👋

Your operating system is reporting that the address is already in use. It is possible that you already have an instance running on this same address. You'll need to stop the already running instance to be able to launch a new one.

Hope this helps.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
