### ISSUE TITLE
Implements the new `IN` filter

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2479]
After the following discussion and a meeting with @gmourier and @loiclec; https://github.com/meilisearch/product/discussions/479

The first version of the filter should be implemented with the following syntax;
```
 The space is NOT mandatory
     v
id IN [1, 3, 4]
      ^       ^
  The square brackets are mandatory.
```

- The `NOT` can be either as a prefix or infix operator:
```
NOT id NOT IN [1, 3, 4]
```

- It must be possible to send an empty array;
```
id IN []
```

- It should be possible to add a trailing comma at the end of the array;
```
id IN [
  1,
  3,
  4,
]
```
But creating an array containing only a trailing comma is not possible: `id IN [,]`

**Comment by curquiza** [comment]
For people following this issue, we have already published a docker tag to test the feature

```bash
docker run -it --rm \
    -p 7700:7700 \
    getmeili/meilisearch:v0.29.0-filter.beta.0
```

Or you can compile the source code on the `filter/field-in` branch on this repo

All the information about the new addition is detailed [here](https://github.com/meilisearch/product/discussions/407#discussioncomment-3084053)

Any feedback is more than welcome!! ❤️
