### ISSUE TITLE
Add settings to customize the maximum number of reachable documents during the search

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2495]
In v0.27.0, for security reasons, we added a hard limit when searching documents with Meilisearch, see https://github.com/meilisearch/meilisearch/issues/2133

Following this spec: https://github.com/meilisearch/specifications/pull/157

We now want to let the users customize this limit. Reasons and implementation details are described in the spec.

TODO
- [ ] Introduce a `pagination` settings API resource. `GET/PATCH/DELETE` - `/indexes/:indexName/settings/pagination`
- [ ] In the `pagination` setting object, a field is present: `limitedTo` property - Type: Integer - Default to `1000`
- [ ] Add tests

Pinging @meilisearch/docs-team and @meilisearch/integration-team

**Comment by dichotommy** [comment]
Hello 👋🏻 

I'm wondering about the name `Pagination`, how or why was this chosen?

**Comment by curquiza** [comment]
Hey @dichotommy 
You can give any feedback and ask any question regarding the product in the related spec: https://github.com/meilisearch/specifications/pull/157 😇 

As I said (internally on Slack) since it's a last-minute spec, you are more than welcome to suggest improvements. The core team is ready to change quickly during the pre-release if needed 💪

**Comment by curquiza** [comment]
Update: the new settings name is `limitedTo` -> `maxTotalHits` 
See: https://github.com/meilisearch/specifications/pull/157/commits/5e1eeeacbbdd352f612ea4fa3514494584b58e7c

I've updated the issue
