### ISSUE TITLE
V0.28.0rc0 attributesToHighlight/attributesToCrop: * not working on GET /search route

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2527]
**Describe the bug**
When making a request on the `GET` /search routes adding `attributesToHighlight: *` does not create a `_formatted` object.
At the contrary, adding a specific field `attributesToHighlight: title` for example, works correctly.

**To Reproduce**
1. Make a search request using the GET method
2. add `attributesToHighlight: *` as a query parameter
4. _formatted is not created nor is there anything highlighted

**Expected behavior**
`attributesToHighlight` should be taken into account.

**Screenshots**
<img width="936" alt="Screenshot 2022-06-15 at 18 31 45" src="https://user-images.githubusercontent.com/33010418/173879019-67625a17-6588-4942-9843-fec719c136d4.png">

**Meilisearch version:** [e.g. v0.20.0]
v0.28.0rc0

**Comment by curquiza** [comment]
Thanks @bidoubiwa 

We need to add tests 🔥

**Comment by curquiza** [comment]
Closed by #2543
