### ISSUE TITLE
Create index task error

### ISSUE THREAD

**Issue by shivabohemian** [meilisearch/meilisearch#2535]
**Describe the bug**
I could only create three indexes. When I create the fourth index, an error has occurred.
The error is as follows:

{"uid":9,"indexUid":"XXXX","status":"failed","type":"settingsUpdate","details":{"filterableAttributes":["addTime","customRank","filename","inode","playTimes"],"sortableAttributes":["addTime","customRank","filename","playTimes"]},"error":{"message":"Cannot allocate memory (os error 12)","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"},"duration":"PT0.042510261S","enqueuedAt":"2022-06-18T11:07:12.932189315Z","startedAt":"2022-06-18T11:07:12.970245561Z","finishedAt":"2022-06-18T11:07:13.012755822Z"}

**To Reproduce**
1. First, I create three indexes on my machine.
2. And I create my fourth index.
3. I met the error above.

**Expected behavior**
Index can be created normally.

**Screenshots**
free -h
<img width="677" alt="截屏2022-06-18 19 20 38" src="https://user-images.githubusercontent.com/39078424/174435344-0c58bd8c-406a-4859-8770-ddac27c6438a.png">

**Meilisearch version:**
v0.27.2

**Additional context**
Linux XXX 4.19.219 #21 SMP Thu Apr 7 22:56:20 PDT 2022 aarch64 GNU/Linux

**Comment by oluademola** [comment]
Hello @shivabohemian 

I believe this is not a bug. I have a meilisearch database containing about 300k documents with more than 4 indexes and adding another index works fine. It looks to me like your machine ran out of memory. In this situation, we often recommend increasing your machine's RAM and ensuring you adhere to the [performance optimization suggestions mentioned in the dedicated documentation](https://docs.meilisearch.com/learn/advanced/indexation.html#improving-indexation-performance).

Hope this helps. Thank you very much.

**Comment by shivabohemian** [comment]
Thanks, I agree with you. But what puzzles me is that I can no longer create index when I use only half of my memory...

**Comment by oluademola** [comment]
Hello, In this scenario, it appears the problem is most likely related to the RAM rather than the disk space

**Comment by shivabohemian** [comment]
Sorry, I made a mistake. I mean half of RAM space, not memory

**Comment by oluademola** [comment]
Hello @shivabohemian 

Sorry for the trouble. We have discussed this internally, it appears that your machine might need more memory to run Meilisearch, and there is not much I can do. 

That said, I'd encourage you to increase your machine's RAM, enable auto-batching and follow the performance optimization options in the [dedicated documentation](https://docs.meilisearch.com/learn/advanced/indexation.html#improving-indexation-performance). 

I hope this helps you. Many thanks 🙏

**Comment by shivabohemian** [comment]
Ok, thanks for your reply. I'll try it
