### ISSUE TITLE
V0.28.0rc0 `/keys` routes are accessible with admin key

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2538]
**Describe the bug**
As per the [specification](https://github.com/meilisearch/specifications/blob/29c3ec96504a506e4a88e43d070cbe134480c5a5/text/0085-api-keys.md)

> the endpoint /keys is accessible for the master key holder

Nonetheless it is accessible with the Admin key as well.

**To Reproduce**
1. Create an instance of meilisearch protected by password
2. Fetch the admin key
3. make a request on `GET /keys` (or POST)
4. Should throw an invalid API key but instead it works

**Expected behavior**
Admin key should not have access to this route

**Meilisearch version:**
v0.28.0rc0

**Comment by curquiza** [comment]
Thanks @bidoubiwa 

I don't know if it's already the case but we need to add tests, checking the routes are only accessible with the right key, since it can lead to security issues 🔥 🔥

**Comment by gmourier** [comment]
Admin API Key should have access to it since the defined `actions` is `*`. 

I did not find any mention in the specification that this should not be the case. 

I forgot to update this sentence "Default Admin API Key authorizing all actions on all indexes (except managing /keys resource)." 😫

**Comment by curquiza** [comment]
Ok, thank you @gmourier, I let you update the spec! Thanks, I close this issue
Sorry @bidoubiwa for the confusion!

**Comment by bidoubiwa** [comment]
I think the specification is not up to date yet: 

> When a master key is set at Meilisearch first-launch, it generate two pre-configured default API Key resources. A Default Search API Key authorizing the search action on all indexes and a Default Admin API Key authorizing all actions on all indexes (except managing /keys resource).

**Comment by gmourier** [comment]
It has been updated https://github.com/meilisearch/specifications/pull/148/files (The spec is not merged on develop yet)
