### ISSUE TITLE
pagination.limitedTo setting is not working

### ISSUE THREAD

**Issue by oluademola** [meilisearch/meilisearch#2551]
**Describe the bug**
According to the release note for version 0.28 RC. It seems as though the `pagination.limitedTo` setting is not functioning and is returning a not found error.

<img width="904" alt="Screenshot 2022-06-25 at 11 07 11" src="https://user-images.githubusercontent.com/101267639/175769082-1f22830f-cdd7-4712-8b8b-466d1ac6d351.png">

**To Reproduce**
1. Use the movies.json dataset
2. Update the pagination setting as described in the screenshot above
3. Meilisearch returns a 404 Not Found error.

**Expected behavior**
I expect the `limtedTo `value to be updated to 2000

**Screenshots**
<img width="1081" alt="Screenshot 2022-06-25 at 10 40 51" src="https://user-images.githubusercontent.com/101267639/175769223-0a556058-080b-4fff-91c5-1d1b62611582.png">

**Meilisearch version:** 
v0.28.0rc0

**Comment by oluademola** [comment]
Hey @curquiza yes, you are correct. The issue is closed so If I understand you correctly the fix will be released with the v0.28 final release.

**Comment by curquiza** [comment]
Yes! exactly. The bug fix will be even present in v0.28.0rc1 I'll release today!

I close this issue then 😄
