### ISSUE TITLE
Task uid limit: can not parse "99999999999" to a u32

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch#2555]
**Describe the bug**
I'm not sure if this "is" a bug but in any case, I would like to have more explanations about the behavior.

I'm working on the PHP repo, and I encountered a bug when trying to make it work in this new version, we have a test to force an error that accesses a really big task id the number is 99.999.999.999 (I've added the dots to make it easier to read).

Looking in the last stable version I could check the task#uid used to support u64. Knowing this is something we don't expect to reach so soon, some users may have to handle this bug in the future.

So the question is why changing to u64 (if it was conscious)

**To Reproduce**
Access a task route: `GET /tasks/99999999999` 

**Expected behavior**
~Access the desired task or an 404 error not a 500.~. 
Access the desired task or a 404 error, not a 404 with a different content-type

**Meilisearch version:** v0.28.0rc1

**Additional context**
Additional information that may be relevant to the issue.
Docker on macOS

**Comment by curquiza** [comment]
Thank you @MarinPostma for the answer ❤️ 
I close this issue then!

**Comment by brunoocasali** [comment]
@MarinPostma I liked your example, but you're considering just a serial execution, not a parallel one correct? Because if we have a multi-threaded environment for example a background job process configured in a rails app like sidekiq, you can exponentially increase the number of tasks per minute.

In a recent job experience I had, we used to send at least 1mm emails per day, if I indexed that + the other data we used to have in background jobs we would reach that in a couple of years.

@curquiza WDYT to open a new issue to handle the parsing error? The content type of the response is not compatible with the request's content type.

**Comment by MarinPostma** [comment]
@brunoocasali all writes are serialized, so that wouldn't change much :)

**Comment by MarinPostma** [comment]
@brunoocasali I mean that writing to disk is single-threaded, so even if you submit tasks concurrently, they will be registered sequentially.

The reason it is done this way is that the filtering of tasks is backed by roaring bitmaps. They have the advantage of being easily serializable to disk, zero-copy reads, efficient set operations, and great compression. The drawback is that we can only use u32s. The advantage of using bitmap largely outbalances that of having u64 here

I understand your concern, but other limits are probably gonna be hit long before this one

**Comment by curquiza** [comment]
@brunoocasali when the PR is merged, the specificiation regarding task error message needs to be updated with the new error message 😇

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/meilisearch/issues/2593
