### ISSUE TITLE
Add new CI: cron GHA to create an issue "Update dependencies"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2569]
In Meilisearch we don't want to use Dependabot since we have a loooooot of dependencies and Dependabot updates them one by one

Using the `cron` event in a GitHub Actions, we want a CI that creates a new issue every 3 months in this repository with
- title: "Upgrade dependencies"

- description:
"We need to update the dependencies of the Meilisearch repository, and, if possible, the dependencies of all the core-team repositories that Meilisearch depends on (milli, charabia, heed...).

⚠️ This issue should only be done at the beginning of the sprint!"

- labels: `dependencies` and `maintenance`

**Comment by VasiliySoldatkin** [comment]
If there is no one assigned I'll do it this week

**Comment by curquiza** [comment]
Hello @VasiliySoldatkin 
Thanks for your interest in this project :)

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
