### ISSUE TITLE
Indexation improvement: skip the already-existing documents during indexation

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2600]
Currently, Meilisearch indexes all the documents it gets, even if the EXACT same document already exists.
Some users have the following use case: they run cron jobs every X times to send documents to Meilisearch, and most of the documents sent haven't changed. But Meilisearch is still slow indexing them, considering them as a document update, despite the documents where unchanged

What we want to do? Skip the indexation for the documents that fully already exist (i.e the exact same document already exists in the Meilisearch DB).

Example

Meilisearch already contains the following documents
```json
[
  {
    "id": 1,
    "name": "tamo"
  }
]
```

If the user sends
```json
[
  {
    "id": 1,
    "name": "tamo"
  }
]
```
-> the indexation will be skipped

If the user sends
```json
[
  {
    "id": 1,
    "name": "many"
  }
]
```
-> the indexation will be processed as usual, since it's a partial update.

This feature is totally transparent for the users: no customization to do.

----

Pinging @meilisearch/devrel-team to inform you the search engine should be faster in v0.29.0 (for this usecase only).
Maybe @irevoire can share some metrics even if we cannot ensure there are linked to official use cases.

**Comment by irevoire** [comment]
Hey, on this specific use case, we are between 3 and 9 times faster depending on the datasets

**Comment by hiepxanh** [comment]
How you know that document changed, should you hash it then compare?

**Comment by irevoire** [comment]
Hey @hiepxanh, when we detect that a primary-key is already present in the database, we need the old version of the document to merge it with the new version.
Basically, I added a simple condition at this spot where, if the old document is exactly equal to the new one (bytes by bytes), then I do nothing.

You can see it here on line 288; https://github.com/meilisearch/milli/pull/579/files#diff-5a1cf7314b23e7a229c82c639a3c987be63961db2de4ff7d77d5b3bd96288ccfR288-R295
