### ISSUE TITLE
Update meilisearch version

### ISSUE THREAD

**Issue by MathiasWeisheit** [meilisearch/meilisearch#2603]
**Describe the bug**
Hi, I used the docker image 0.27.. with "getmeili/meilisearch:latest" in my compose.
So with your update to 0.28 the image is pulled and restarted.
After this meilisearch does not work becaus of the diffrent engine versions.
expected Meilisearch engine version: 0.27.X, current engine version 0.28.

**Expected behavior**
The https://docs.meilisearch.com/learn/advanced/updating.html#verify-your-database-version is not practical
I think there must be an auto update! Or the engine 0.28 must be compatible with 0.27.... or something else.
What do you think?

**Meilisearch version:** [e.g. v0.28.0]

**Additional context**
Docker, Docker-Compose

**Comment by curquiza** [comment]
Hello @MathiasWeisheit 

Indeed, Meilisearch does not have any auto-update for the moment, this is something we are currently working on, see this issue: https://github.com/meilisearch/meilisearch/issues/2590

In the meantime, you have to use dump to make the update. In the documentation you linked, there is [a section](https://docs.meilisearch.com/learn/advanced/updating.html#updating-from-v0-15-0-or-above) to explain how to process

**Comment by MathiasWeisheit** [comment]
until this issue is solved i will fix my dockerimage to v.0.28
