### ISSUE TITLE
Highlighting only for the first occurance of a searchterm

### ISSUE THREAD

**Issue by erichk4** [meilisearch/meilisearch#2627]
Hi, if the "cropLength", "attributesToHighlight" and "attributesToCrop" search attributes are set **only the first occurance** of the searchterm is highlighted/marked with "highlightPreTag" and "highlightPostTag" in the "_formatted" output...is this by design or is it a bug?

{ 
    "q": "test",
    "attributesToHighlight": ["content"],
    "attributesToCrop":["content"],
    "cropLength": 50,
    "highlightPreTag": "`<mark>`",
    "highlightPostTag":"`</mark>`"
  }

["_formatted"]["content"]: "Lorem ipsum dolor `<mark>`**test**`</mark>` sit amet, consetetur sadipscing elitr, sed **test** diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus…",

**Meilisearch version:** 
v0.28.0

**Additional context**
docker version

**Comment by curquiza** [comment]
Hello @erichk4 thanks a lot for this report!! This is indeed a bug, we are fixing it and we are releasing a new version of Meilisearch fixing this bug asap!
@ManyTheFish is working on it 💪

**Comment by curquiza** [comment]
Closed by #2633 
Will be released in v0.28.1

**Comment by curquiza** [comment]
[v0.28.1](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.1) has been released, should be ok now @erichk4 
thanks again for the report! 🙏

**Comment by erichk4** [comment]
Works like a charm now! 

Many thanks to you and the whole team!! :thumbsup:
