### ISSUE TITLE
Chinese word segmentation is not very good

### ISSUE THREAD

**Issue by kipp01** [meilisearch/meilisearch#2632]
Chinese word segmentation is not very good

**Comment by curquiza** [comment]
Hello @kipp01 

Could you please detail it a little bit more? What do you mean by "is not very good"? What do you get? What would you expect instead?

Plus, what is your Meilisearch version?

**Comment by kipp01** [comment]
For example: 测试工具箱，我想要分词出，测试，工具箱，工具。But only the word test kit came up。
Chinese word segmentation is not very good word segmentation。
latest version

**Comment by kipp01** [comment]
@curquiza 
For example: 测试工具箱，我想要分词出，测试，工具箱，工具。But only the word test kit came up。
Chinese word segmentation is not very good word segmentation。
latest version

**Comment by liaohongxing** [comment]
Meilisearch uses jieba-rs, which is mediocre. In retrospect, nothing written by pure rust is better than jieba-rs

**Comment by ManyTheFish** [comment]
Hello @kipp01 and @liaohongxing,
> For example: 测试工具箱，我想要分词出，测试，工具箱，工具。But only the word test kit came up。
Chinese word segmentation is not very good word segmentation。
latest version

Sorry, we don't have any native Chinese in the team, so what do you expect from Meilisearch?
1) do you expect to find documents containing `测试工具箱` by searching `测试`, `工具箱`, or `工具`? Meaning that we should cut our words differently.
2) do you expect the typo tolerance to work differently?

> Meilisearch use jieba-rs, which is mediocre. In retrospect, nothing written by pure rust is better than jieba-rs

3) do you know an open source product, in any Programmation language, that has better support for Chinese Languages?

Thanks for your reply!

**Comment by ManyTheFish** [comment]
Hello @kipp01 and @liaohongxing,

I'm closing this issue in favor of a [mutualized discussion on the product repository (product#503)](https://github.com/meilisearch/product/discussions/503).

Don't hesitate to give some feedbacks on upper discussion.

**Comment by houlang** [comment]
I had the same issue, "新" ==> “芯” 

I think this Chinese language issue is very important. If it's not solved, Meilisearch cannot be applied in a production environment.

Data List：
```json
[{
        "id": 1763204760840700001,
        "create_date": "2023/9/8 17:20:23",
        "search_text": "新中",
		"search_times": 10
    }, {
        "id": 1763204760840700002,
        "create_date": "2023/9/8 17:20:23",
        "search_text": "浮雕装饰画",
		"search_times": 155
    }, {
        "id": 1763204760840700003,
        "create_date": "2023/9/8 17:20:23",
        "search_text": "新中背景墙",
		"search_times": 20
    }, {
        "id": 1763204760840700004,
        "create_date": "2023/9/8 17:20:23",
        "search_text": "中式",
		"search_times": 50
    }, {
        "id": 1763204760840700005,
        "create_date": "2023/9/8 17:20:23",
        "search_text": "画芯",
		"search_times": 100
    }, {
        "id": 1763204760840700006,
        "create_date": "2023/9/8 17:20:23",
        "search_text": "抽象装饰画",
		"search_times": 550
    }, {
        "id": 1763204760840700007,
        "create_date": "2023/9/8 17:20:23",
        "search_text": "中式背景墙",
		"search_times": 120
    }
]
```
Search Request:
```json
{
    "q": "\"新\"",
    "matchingStrategy": "all",
    "attributesToSearchOn": [
        "search_text"
    ],
    "attributesToHighlight": [
        "search_text"
    ],
    "attributesToRetrieve": [
        "search_text"
    ],
    "limit": 10,
    "offset": 0,
    "showRankingScore": true
}
```
Search Result:
```json
{
    "hits": [
        {
            "search_text": "新中",
            "_formatted": {
                "search_text": "<em>新</em>中"
            },
            "_rankingScore": 0.49242424242424243
        },
        {
            "search_text": "新中背景墙",
            "_formatted": {
                "search_text": "<em>新</em>中背景墙"
            },
            "_rankingScore": 0.49242424242424243
        },
        {
            "search_text": "画芯",
            "_formatted": {
                "search_text": "画<em>芯</em>"
            },
            "_rankingScore": 0.4621212121212121
        }
    ],
    "query": "\"新\"",
    "processingTimeMs": 0,
    "limit": 10,
    "offset": 0,
    "estimatedTotalHits": 3
}
```
Moreover, I found that words added to the stop_words list still seem to be searchable.
cURL:
```bash
localhost:7700/indexes/ithome_search_suggestions/settings/stop-words
```
Response：
```json
[
    "画芯"
]
```
Test Request:
```json
{
    "q": "\"画芯\"",
    "matchingStrategy": "all",
    "attributesToSearchOn": [
        "search_text"
    ],
    "attributesToHighlight": [
        "search_text"
    ],
    "attributesToRetrieve": [
        "search_text"
    ],
    "limit": 10,
    "offset": 0,
    "showRankingScore": true
}
```
Response Result: you can see "画芯" still seem to be searchable.
```json
{
    "hits": [
        {
            "search_text": "画芯",
            "_formatted": {
                "search_text": "<em>画</em><em>芯</em>"
            },
            "_rankingScore": 0.5
        }
    ],
    "query": "\"画芯\"",
    "processingTimeMs": 0,
    "limit": 10,
    "offset": 0,
    "estimatedTotalHits": 1
}
```
