### ISSUE TITLE
The generated Tenant Token cannot be used

### ISSUE THREAD

**Issue by smell-iron** [meilisearch/meilisearch#2638]
**Describe the bug**
The generated Tenant Token cannot be used

**To Reproduce**
1. Use the existing APIkey UID which complies with UUIDV4 standard '12718d4f-b2f7......'
2. Generate the token using the client.generateTenantToken method
3. The token is: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZWFyY2hSdWxlcyI6eyJhbGxfcHJpdmF0ZSI6eyJmaWx0ZXIiOiJ1c2VyaWQgPSBhZG1pbiJ9fSwiYXBpS2V5VWlkIjoiYzlhZTE2MjAtM2U1MC00MjMwLThjNGUtZDlmMWI4NWQxZDYyIn0.ERBdWcQSjdhDKMG2YrbCfgR0-YRP-4JDPOLKYkuUrnQ
4. Use this token as a APIkey usage : const frontEndClient = new MeiliSearch({ host: 'http://127.0.0.1:7700', apiKey: **token** })
5. meilisearch returns
 {
  code: 'invalid_api_key',
  type: 'auth',
  link: 'https://docs.meilisearch.com/errors#invalid_api_key',
  httpStatus: 403
}

**Expected behavior**
Can act like an APIkey and implement the filtering conditions in search_Rule

**Meilisearch version:** [e.g. v0.28.0]
The same thing happens in lower version

**Additional context**
The documentationv0.28 of tenant token seems not up-to-date

**Comment by oluademola** [comment]
Hi @smell-iron.  What function or endpoint are you trying to access with this tenant token?

**Comment by smell-iron** [comment]
Thank you very much! I just want to use Tenant Token to filter the search results. The API key I used earlier to generate Tenant tokens contains an [API action](https://docs.meilisearch.com/reference/api/keys.html#actions-2) other than **search**, and it works fine when I use the new token which generated with an API key contains only **search** action.

**Comment by gmourier** [comment]
Hey @smell-iron,

A tenant token is only usable for search requests; thus, the API Key generating them must have at least the `search` action defined. Note that: `*` also works since it defines all possible actions.

Using the meilisearch-js SDK in the latest version

```js
import { MeiliSearch } from 'meilisearch'

const client = new MeiliSearch({
  host: 'http://127.0.0.1:7700',
  apiKey: '1234',
})

const searchRules = {
  products: {
    filter: 'id = 1'
  }
}
const apiKeyUid = 'c2f0801a-7447-40b2-bd61-934efc5a27f7'; //uid of an API key having search and tasks.get actions defined
const expiresAt = new Date('2025-12-20') // optional

const token = client.generateTenantToken(apiKeyUid, searchRules, {
  expiresAt: expiresAt,
  apiKey: '56d086cd35b4fa1e273c037aba208f843a8a9aae2d0e7efa8e83302c38a66117' //api key of the API Key having search and tasks.get actions
})

console.log(token)
```

The generated token work at search time while the signing API Key has another added action than the `search` one.

Not sure, if it's answer your question; Let us know.

Note: We updated the [sample code on the documentation](https://github.com/meilisearch/meilisearch-js/pull/1314#pullrequestreview-1057289474) because it was not up-to-date.

**Comment by curquiza** [comment]
I close this issue then. Nothing is definitive of course, feel free to ask to re-open if needed 😊
