### ISSUE TITLE
Missing Search Results

### ISSUE THREAD

**Issue by SenojLuap** [meilisearch/meilisearch#2642]
**Describe the bug**
When performing a search, results are missing for certain searches

**To Reproduce**
1. Create an index with the documents available here: [PasteBin](https://pastebin.com/AtkM8DfF)
2. Update searchable attributes to ["change", "module", "version", "release"] (I'm not actually sure this step is required)
3. Update ranking rules to ["version:desc", "release_order:asc"] (I'm not actually sure this step is required)
4. Perform a search for 'DataSymbol' (default search parameters is fine)

**Expected behavior**
Should receive 3 hits

**Screenshots**
n/a

**Meilisearch version:**
v0.28.0 Docker Image

**Additional context**
* Running on Docker image 'getmeili/meilisearch:v0.28.0'
* MEILI_ENV is set to 'production'

**Comment by oluademola** [comment]
Hi @SenojLuap 

I am not sure this is a bug. I received a hit containing the search term in the search result in my test. I'd like to know your specific expectation to assist you better.
<img width="1066" alt="Screenshot 2022-08-01 at 08 18 16" src="https://user-images.githubusercontent.com/101267639/182094023-2bbf7844-420b-46d0-b3bf-c6114f270987.png">

**Comment by SenojLuap** [comment]
When I run the test on the provided data, I don't get a single result, though there should be at least 2.
You can do a quick search through the sample data to see that there are multiple hits, so even your result is incorrect.

**Comment by oluademola** [comment]
Hi @SenojLuap,

I am not sure I completely understand the issue. The data you have provided on Pastebin appears to be replicated in 2 places, a set appears as JSON and another under the section Raw Paste Data. A quick search (command f) for `"Data symbol"`  through either of the datasets returns a single document with the `"id" : "12_5-major-runtime_behavior-cm_abstract_dataSymbol"`. MeiliSearch is a prefix-based search engine that starts by comparing the search term against the beginning of each word in your dataset. Therefore queries such as `cm.abstract.dataSymbol` and `Datasymbol` are treated differently as Meilisearch cannot find parts of the query that lie in the middle or at the end of a word or string. For more information and a possible workaround please see this [discussion](https://github.com/meilisearch/meilisearch/discussions/2092). 

Hope this answers your question. Many thanks.

**Comment by SenojLuap** [comment]
As for the paste bin thing: that's just how paste bin works. It will show you a syntax highlighted/formatted version of the paste, as well as a raw version. But it is the same data.

As for the prefix thing: I didn't know about that; that's pretty disappointing. However, it does answer the question so I _guess_ the issue is closed? Maybe I'll hunt down a ticket with a feature request for more comprehensive searching.
