### ISSUE TITLE
Index not found when Laravel Scout ShouldBeSearchable is False

### ISSUE THREAD

**Issue by makoy71692** [meilisearch/meilisearch#2645]
**Describe the bug**
When i am creating a data from my Model with scout searchable trait and whenever the function shouldBeSearchable returns a false value i am encountering an error that the INDEX of the model is not found... this particular error appears when my meilisearch is fresh or no index yet...

**To Reproduce**
1. Fresh Meilisearch instance
2. Create a data from Model with scout searchable trait
3. shouldBeSearchable should return a false value
4. Error will appear telling that Index {index_name} not found

**Expected behavior**
Scout Shouldn't check for an existing index since the shouldBeSearchable is false or is not required to be indexed

**Meilisearch version:0.23.1**

**Comment by oluademola** [comment]
Hi @makoy71692. What version of the PHP package is installed on your application?

**Comment by makoy71692** [comment]
hello @oluademola heres the package
PHP v7.4.3
Laravel framework v7.28.4
Laravel Lumen Framework v7.2.1

**Comment by oluademola** [comment]
Hi @makoy71692. Sorry for the confusion. I meant the version of `meilisearch/meilisearch-php` SDK

**Comment by makoy71692** [comment]
Hello @oluademola im using this versions

> meilisearch/meilisearch-laravel-scout v0.12.5          Laravel Scout custom engine for MeiliSearch
> meilisearch/meilisearch-php           v0.17.2          PHP wrapper for the MeiliSearch API

**Comment by oluademola** [comment]
Hi @makoy71692 

I observed you're using a meilisearch/meilisearch-php package that is incompatible with v0.23. It is worth noting that meilisearch v0.23 is only compatible with the meilisearch/meilisearch-php v0.19.2. Probably this could be related to the problem. I suggest you ensure the compatibility of the engine and SDK. 

Let me know if that helps.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
