### ISSUE TITLE
Different result when search keyword having 2 words and change order.  

### ISSUE THREAD

**Issue by kalpeshtreesha** [meilisearch/meilisearch#2646]
**Describe the bug**
When search keyword have 2 words and I change the order it result different result and also consider the first word in search.

**To Reproduce**
As shown in image if I do search keywords Planet Apes and Apes Planet  it's having different result as well as. It's not searhing for Plant or Apes it's searching for First work of keyword.

![image](https://user-images.githubusercontent.com/58501041/181491462-cb3e6748-347d-4a2d-914b-900fc282723b.png)
![image](https://user-images.githubusercontent.com/58501041/181491503-9bd31825-241c-42dd-9e5d-5618335e04f0.png)

Used the sample data for testing purpose to index:
https://docs.meilisearch.com/movies.json

**Comment by ManyTheFish** [comment]
Hello @kalpeshtreesha!
Meilisearch behaves differently depending the order of the words in your query.
There are 3 [ranking rules](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#ranking-rules) that take into account the position of the word in the query and the main one is `words` which removes the last query words if there is not enough results returned.
> In your case the first query will search for `Planet Apes`, then `Planet` if there are not enough results;
> where the second query will search for `Apes Planet`, then `Apes` if there are not enough results.

However! If you want to change this behavior, we recently released a prototype testable by anyone that uses docker.
To know more about what it is and how to use it please refer to [the dedicated discussion](https://github.com/meilisearch/meilisearch/discussions/2635).
your feedback would be of great help to know if we are going into the right direction. :pray:

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
