### ISSUE TITLE
Meilisearch does not processs enqueued tasks

### ISSUE THREAD

**Issue by taiganowdev** [meilisearch/meilisearch#2656]
**Describe the bug**
Meilisearch does not process "enqueued" tasks

**To Reproduce**
I honestly don't know how this happens. Running the `{{url}}/indexes/{{indexUID}}/tasks` API , I get over 100k enqueued tasks. Restart Meilisearch with `systemctl restart meilisearch.service` does not work. Reboot AWS instance and Stop/Start AWS instance also does not work.

**Expected behavior**
MeiliSearch should start working on enqueued tasks.

**Screenshots**
None

**Meilisearch version:** [e.g. v0.20.0]
v0.27.0

**Additional context**
I followed https://docs.meilisearch.com/learn/cookbooks/aws.html

**Comment by CaroFG** [comment]
Hi @taiganowdev, 
Tasks are processed one by one, are you sending your documents in batches or one by one? They should be sent in batches. The bigger, the better. Are you sure tasks are not being processed at all?

I encourage you to try  [auto-batching ](https://docs.meilisearch.com/learn/experimental/auto-batching.html#enable-auto-batching). When auto-batching is enabled, consecutive document addition requests may be automatically combined into a batch and processed together, significantly speeding up the indexation process. It's still an experimental feature, so any feedback is appreciated. To enable it you have to start Meilisearch with the `--enable-auto-batching` flag.

**Comment by julesrenaud** [comment]
I'm having the same issue, my meilisearch AWS EC2 instance was rendered completely useless. Had to terminate it and start from scratch. Also, unrelated, but the current version isn't available in the EC2 AMI listing.

**Comment by oluademola** [comment]
Hello @julesrenaud 

Sorry for the trouble. We understand the ability to cancel or abort enqueued tasks would be helpful in such scenarios, and the only workaround is to start afresh. However, I'm happy to let you know the feature is in the works, as seen on the [roadmap page](https://roadmap.meilisearch.com/c/71-abort-enqueued-updates). Regarding the meilisearch version in the EC2 AMI listing, v0.28.0 is currently available. v0.28.1 would be available in the coming days.

Thank you.

**Comment by oluademola** [comment]
Hello @julesrenaud. Meilisearch v0.28.1 is now available in the EC2 AMI listing 😄

**Comment by julesrenaud** [comment]
> Hello @julesrenaud. Meilisearch v0.28.1 is now available in the EC2 AMI listing 😄

@oluademola thank you!

**Comment by abhay187** [comment]
@julesrenaud and @ManyTheFish 
I am facing the same issue where the task failed and the server crashed but restarting again starts the same task and the server crashes again. We need a way to terminate a task. Let me know if there is a way to terminate a enqueue task.

Thank you

**Comment by oluademola** [comment]
Hello @abhay187 

Sorry for the inconvenience. Sadly there is no way to cancel enqueued task at the moment. However, an abort feature is in the works, as seen on the [roadmap page](https://roadmap.meilisearch.com/c/71-abort-enqueued-updates). The only workaround, for now, is to stop the meilisearch server, delete the `data.ms`, and restart it.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
