### ISSUE TITLE
Internal error when index size is not set to a multiple of page size

### ISSUE THREAD

**Issue by agucova** [meilisearch/meilisearch#2659]
**Describe the bug**
When `--max-index-size` is set to a size which is not a multiple of 4096, the API returns:
```json
{
  "message": "map size (201000000000) must be a multiple of the system page size (4096)",
  "code": "internal",
  "type": "internal",
  "link": "https://docs.meilisearch.com/errors#internal"
}
```

**To Reproduce**
1. Start meilisearch with ```meilisearch --max-index-size 201Gb```
2. Attempt a search to an existing index
```shell
$ https api.reguleque.cl/indexes/reguleque/search q="test"
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Sun, 07 Aug 2022 00:34:29 GMT
Server: cloudflare
Transfer-Encoding: chunked
access-control-allow-origin: *
{
    "code": "internal",
    "link": "https://docs.meilisearch.com/errors#internal",
    "message": "map size (201000000000) must be a multiple of the system page size (4096)",
    "type": "internal"
}
```

**Expected behavior**
Normal search results.

**Meilisearch version:** 0.28.1

**Additional context**
This is under ARM64 in an ARM Ampere server running Ubuntu Server 22.04. The disk being used is a high-performance Oracle Cloud block storage device using an ext4 filesystem.

**Comment by ManyTheFish** [comment]
Hello @agucova!
This issue will be fixed in the next version of Meilisearch, before the release, I suggest setting your sizes in GibiBytes instead of GigaBytes using `201GiB` instead of `201GB`.

Thank you a lot for your report! 🙂
