### ISSUE TITLE
"浙江大学" works but "浙大" doesn't

### ISSUE THREAD

**Issue by tesla-cat** [meilisearch/meilisearch#2666]
- when I search "浙江大学", the result is good:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/28215638/184368034-250ea153-fa3b-4e27-8745-b4077fd0805a.png">

- but when I search "浙大", no result:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/28215638/184368220-84130a12-4638-45e2-803f-ecdd8d12b57b.png">

**Comment by Thearas** [comment]
Hi @tesla-cat, you may want [synonyms](https://docs.meilisearch.com/learn/configuration/synonyms.html#normalization).

**Comment by curquiza** [comment]
Hello @tesla-cat
Have you solved your issue?

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
