### ISSUE TITLE
Crashing when creating index on railway.app

### ISSUE THREAD

**Issue by abhay187** [meilisearch/meilisearch#2685]
Hello,
I am trying to deploy meilisearch on the railway.app. I have followed all the step in the documentation but when I try to add an index it crashes. I am on the free tier of 512MB RAM plan. 
Is 512MB enough or not?

**Comment by ManyTheFish** [comment]
Hello @abhay187,

unfortunately, 512MB is a bit tiny for the memory size, I suggest reserving at least 1GB for a small dataset (under ~300 000 documents) and at least 2GB for bigger ones.

**Comment by abhay187** [comment]
thanks, @ManyTheFish  for the clarification.

**Comment by curquiza** [comment]
Closing this issue then, thanks @ManyTheFish for the explanations

**Comment by ManyTheFish** [comment]
Hello @abhay187,

After some investigations, your issue could come from a bad estimation of the accessible memory, I suggest setting manually the [max-indexing-memory](https://docs.meilisearch.com/learn/configuration/instance_options.html#max-indexing-memory) between 192MB and 256MB for a total accessible memory of 512MB. 🤔

**Comment by abhay187** [comment]
Thanks a lot @ManyTheFish it works. 
Since I am testing meilisearch for my project. I did not want to buy large paid servers.

Also, is there a way to find index-size? so that I can know when to buy more ram size.

**Comment by ManyTheFish** [comment]
@abhay187,
It's hard to estimate the optimized amount of RAM for a defined data size and I suggest you to try Meilisearch on your environment and with a dataset that is the most similar to your expected use case.
However, you don't need to scale your RAM as you would scale your Disk space, so, you shouldn't have to upgrade your RAM frequently. 🤔 

What is the data size you would use with a 512MB instance?

**Comment by abhay187** [comment]
I am trying to index movie.json which is 15-16 MB. Max index size is set at 256.

**Comment by ManyTheFish** [comment]
@abhay187, did you mean [max-indexing-memory](https://docs.meilisearch.com/learn/configuration/instance_options.html#max-indexing-memory) instead of [max-index-size](https://docs.meilisearch.com/learn/configuration/instance_options.html#max-index-size)? Otherwise, it is max-indexing-memory that should be set to 256MB and not max-index-size because max-index-size is the maximum size an index can take on your disk.

**Comment by abhay187** [comment]
@ManyTheFish my bad I have set MEILI_MAX_INDEXING_MEMORY.
