### ISSUE TITLE
restrictSearchableAttributes feature missing.

### ISSUE THREAD

**Issue by abhay187** [meilisearch/meilisearch#2688]
There is no way to restrictSearchableAttributes per query.
For detail you can refer to algolia documentation [restrictSearchableAttributes](https://www.algolia.com/doc/api-reference/api-parameters/restrictSearchableAttributes/)

**Comment by oluademola** [comment]
Hello @abhay187 

Indeed we do not provide support for this feature at the moment. I suggest you start a new discussion on the [product repo](https://github.com/meilisearch/product/discussions) for feature requests. 

Many thanks 🙂

**Comment by curquiza** [comment]
I close this issue then. Feel free to ask to re-open if needed 😊
