### ISSUE TITLE
`/metrics` do not return `http_requests_total` and `http_response_time_seconds`

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#2695]
**Describe the bug**

`/metrics` do not return `http_requests_total` and `http_response_time_seconds`

**To Reproduce**
1. Use `main` branch
2. Launch Meilisearch with `--enable-metrics-route`
3. Make some search requests (Ps: `processingTimeMs` seems to be always 0) 
4. GET `/metrics`

**Expected behavior**
Seems that `http_response_total` and `http_response_time_seconds` should be returned.

**Additional context**
[Observability, Prometheus]

**Comment by Kerollmops** [comment]
Hey,

We found the bug this morning with @gmourier and we decided that it is not a bug on the Meilisearch but rather on the Postman/cURL side. The URL that was used to call the `/metrics` routes was containing two slashes i.e. `localhost:7700//metrics`, and was therefore breaking the stats collector.

https://github.com/meilisearch/meilisearch/blob/c4453340707f0b8ed6168118dff2e4d2ae634f8d/meilisearch-http/src/route_metrics.rs#L50-L52
