### ISSUE TITLE
In the payload of a tenant token the searchRule `[]` changed behavior from v0.27 to v0.28

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2705]
**Describe the bug**
In v0.27 the `searchRules` in the payload, when the value was set to `[]`, gave the token access to search on all indexes on which the parent API key also has access.

In `v0.28`, when searchRules is set to `[]`, the token receive no rights at all on any index and thus throw an `invalid_api_key` error.

**To Reproduce**
1. use the admin key to create a token with `searchRules: []`
2. Try to search on any existing index with the token just created
3. Error is thrown: `invalid_api_key`

**Expected behavior**
One of the following:
- No error
- Being made aware of the breaking change
- Better error response, `No permission to search with the provided rights` instead of `Invalid API Key`

**Additional context**
To avoid losing time in understanding why my token is suddenly marked as `invalid_api_key` is it possible to add more tests to cover all formats?

**Comment by curquiza** [comment]
Hello @bidoubiwa 

Thanks for the report, I was not aware of this breaking change, sorry for the trouble in debugging 😅 

@gmourier would you rather come back to the old behavior (`[]` = access to all indexes) or the current one (`[]` = no access at all)?

**Comment by bidoubiwa** [comment]
Just to give my two cents, if prefer

> ([] = no access at all)

**Comment by ManyTheFish** [comment]
Hello @bidoubiwa @curquiza,
this behavior doesn't seem to be [defined in the spec](https://github.com/meilisearch/specifications/blob/main/text/0085-api-keys.md#3241-api-key-resource-representation) nor [in the documentation](https://docs.meilisearch.com/reference/api/keys.html#indexes). So I honestly think that the previous behavior (v0.27) was a bug.

**Comment by gmourier** [comment]
> Just to give my two cents, if prefer
> ([] = no access at all)

That made me think about something:

What is the point of generating a tenant token without access to anything on the SDK side? 

The same question can go for the API key with the `actions` field, but there may be a case where you may want to remove any action for an API key without expiring it or deleting it 🤔

**Comment by curquiza** [comment]
Ok, following the discussion, this was an old bug fixed in v0.28.0, I will update the v0.28.0 changelog with this bug fix.
@ManyTheFish if you know the PR where this has been fixed, it would be even perfect! 👌 
 
I close this issue in the meantime and associated it to v0.28.0 Milestone

**Comment by curquiza** [comment]
> What is the point of generating a tenant token without access to anything?

I don't know honestly, maybe @bidoubiwa can help on it

**Comment by ManyTheFish** [comment]
@bidoubiwa I don't manage to reproduce your case in v0.27.0, are you sure that you had exactly `searchRules: []` in your tests?

**Comment by bidoubiwa** [comment]
Mmh that's weird, we made multiple tests with @irevoire and there was a change in behavior. But I'm not able to reproduce it either. Well! That fixes the issue then 😊

**Comment by bidoubiwa** [comment]
@gmourier would you suggest returning an `invalid_api_key` error ?

**Comment by gmourier** [comment]
If the syntax `"searchRules": []` is not described as an acceptable behavior in the specification. The resulting tenant token is therefore invalid, and the API must return an `invalid_api_key` error.

A discussion to improve this can be created on the product side for future consideration.

**Comment by bidoubiwa** [comment]
If you are refering to the error messages, I think there is already a discussion about it [here](https://github.com/meilisearch/product/discussions/398)

If you are referring to the accepted format, I don't think there is indeed!
