### ISSUE TITLE
unable to add documents on (cloud run + cloud storage) meilisearch

### ISSUE THREAD

**Issue by shamsmosowi** [meilisearch/meilisearch#2720]
**Disclaimer**
I know this isn't an intended usecase😅, however would love to get it to work!
**Describe the bug**
I'm trying to deploy meilisearch on GCP Cloud Run and Cloud Storage using [gcsfuse](https://github.com/GoogleCloudPlatform/gcsfuse). I am able to get an instance url that loads meilisearch UI [here](https://serverless-meilisearch-qtcobgiyyq-uc.a.run.app/) and it seems to have successfully created files on the connected storage bucket
<img width="1209" alt="Screen Shot 2022-08-29 at 5 09 51 pm" src="https://user-images.githubusercontent.com/13803906/187280784-120a9cc6-306a-4298-b424-41b8a864dbae.png">
**To Reproduce**
1) deploy melisearch to Cloud Run using [this  repo](https://github.com/shamsmosowi/serverless-meilisearch)
this step appears to be successful
 
2) try to add a document using curl

```
curl \
  -X POST 'https://serverless-meilisearch-qtcobgiyyq-uc.a.run.app/indexes/movies/documents' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer superSecret' \
  --data-binary '[
    {
      "id": 287947,
      "title": "Shazam",
      "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
      "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
      "release_date": "2019-03-23"
    }
  ]'
```
returns successful response of the pending task
```
{"taskUid":0,"indexUid":"movies","status":"enqueued","type":"documentAdditionOrUpdate","enqueuedAt":"2022-08-29T19:18:02.100185041Z"}
```
it also appears to have created the index 
<img width="1059" alt="Screen Shot 2022-08-29 at 9 26 18 pm" src="https://user-images.githubusercontent.com/13803906/187282369-deb57f63-4431-4b9b-8448-5627bb4c308e.png">

3) checking the task, 
```
curl \      
  -X GET 'https://https://serverless-meilisearch-qtcobgiyyq-uc.a.run.app/tasks/0' -H 'Authorization: Bearer superSecret'
```
it remains as pending for about a minute then starts returning the following error
```
{"uid":0,"indexUid":"movies","status":"failed","type":"documentAdditionOrUpdate","details":{"receivedDocuments":1,"indexedDocuments":0},"error":{"message":"An internal error has occurred. `failed to fill whole buffer`.","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"},"duration":"PT25.230456086S","enqueuedAt":"2022-08-29T19:18:02.100185041Z","startedAt":"2022-08-29T19:18:02.540759336Z","finishedAt":"2022-08-29T19:18:27.771215422Z"}
```

**Expected behavior**

expected to have successful document created
 
**Screenshots**

**Meilisearch version:** v0.28.1
```
{"commitSha":"22aa349e31bc7662a065f4dc3229a93abd1f1f33","commitDate":"2022-07-21T11:08:37Z","pkgVersion":"0.28.1"}
```

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by oluademola** [comment]
Hi @shamsmosowi,

As explained on the Slack thread. I am not sure this is a problem with Meilisearch, but we found that it could be related to an issue when reading something from an IO stream (file or network), as discussed in this [thread](https://www.reddit.com/r/rust/comments/b095ag/failed_to_fill_whole_buffer_error_with_bufreader/). 

Hope it helps. Many thanks 🙂
