### ISSUE TITLE
Add missing instance options environment variables

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/meilisearch#2721]
There are some missing environment variables in [the instance options](https://docs.meilisearch.com/learn/configuration/instance_options.html#all-instance-options), and it would be really helpful if you could add them 🙏 

I'm thinking of the one corresponding to the following CLI options:
- `--import-dump` -> `MEILI_IMPORT_DUMP`
- `--ignore-missing-dump` -> `MEILI_IGNORE_MISSING_DUMP`
- `--ignore-dump-if-db-exists` -> `MEILI_IGNORE_DUMP_IF_DB_EXISTS`
- `--import-snapshot` -> `MEILI_IMPORT_SNAPSHOT`
- `--ignore-missing-snapshot` -> `MEILI_IGNORE_MISSING_SNAPSHOT`
- `--ignore-snapshot-if-db-exists` -> `MEILI_IGNORE_SNAPSHOT_IF_DB_EXISTS`

----

Edit from @curquiza 

## TODO
- [ ] Apply changes in PR
- [ ] Update the specfication

## Contributing

All the environment variables need to be added in a single PR. Once activated, they should involve the exact same behavior as the corresponding flag.
Example: `MEILI_IMPORT_DUMP` is the env variable corresponding to the `--import-dump` flag already present in Meilisearch.

Priority: if the env variable and the corresponding flag are set, the priority is for the flag.

Feel free to ask any question to implement this issue, the core team is available to guide you through this contribution, even if it's your first one.
We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by irevoire** [comment]
is this for v0.29? @gmourier @curquiza

**Comment by curquiza** [comment]
Nope, we don't add new features to v0.29.0, it's for v0.30.0 or later. I put it for v0.30.0 for the moment, it's fast to implement if I'm correct, should be ok for v0.30.0

**Comment by curquiza** [comment]
Pinging @meilisearch/docs-team

**Comment by curquiza** [comment]
The spec has been updated and has been added to the issue description
https://github.com/meilisearch/specifications/pull/190
