### ISSUE TITLE
Improve the stat route

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2729]
Currently, the stats route returns the sum of the used map size of each index without any information on the task queue.
That's pretty useless, IMO.

I would like the stats route to return;
- Per index
    - The size used by each index (without the free pages)
    - The _REAL_ size used by each index on the disk
- The size used by the whole `data.ms` (including the task queue and the updates stored on disk but not yet indexed) 
- The _real_ size used by the tasks queue without the free pages + the update files + the _real_ size used by each index

**Comment by curquiza** [comment]
Closing this in favor of https://github.com/meilisearch/product/discussions/527
Feature requests should be done in the product repository 😄
