### ISSUE TITLE
Better support for index creation and deletion

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#273]
Currently when an index is open, multiple database are opened. For an index named "example" we open `example-main`, `example-postings-lists`...

LMDB and therefore heed do not support database deletion as we would like, it [is really unsafe to close a dbi (database)](http://www.lmdb.tech/doc/group__mdb.html#ga52dd98d0c542378370cd6b712ff961b5). This is why we do not close those but just [remove the database name from the list of databases and the cache hashmap](https://github.com/meilisearch/MeiliDB/pull/264/files#diff-06f6c6475eed59a823b1ad978aeff31bR199-R219).

With this solution we do not support deletion and creation as we would like, if we let LMDB open 3000 databases, we are limited to 374 indexes (because they need 8 dbis each). Once this limit is reached we will need to restart the program to be able to reuse those dbis.

I would like to introduce a better solution: using numbers to identify database instead of names, this way we would be able to create/delete and reuse identifiers. We could achieve this by using the databases-name index and associate a unique number to the real name of the database.
If we delete a database, we remove the number from this list and if we need to create a new index, we search for the first available number in this list and associate the index name to it.

**Comment by vladdy** [comment]
Can I try to help with this?

**Comment by Kerollmops** [comment]
Hey,

I am currently working on a new core engine that can support much more documents and answer in much less time, it also consumes much less space. This core engine will only serve one index at a time, we will make it be a library and the multi-index will be handled by another library.

So, a big refactoring of the internal of MeiliSearch is coming soon. I will not be able to guide you through this until we use [this new core engine I am working on](https://twitter.com/kerollmops/status/1282737080435605505?s=21).

**Comment by vladdy** [comment]
Sure, not a problem! I'll try to see where else I could help with the project in the meantime.

**Comment by qdequele** [comment]
This is no more relevant, we close it, feel free to comment here, or open a new issue.
