### ISSUE TITLE
Internal representation of synonyms shouldn't be showed when displaying settings

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#2760]
## current behavior

When setting synonyms on the settings route:
```java
'推进之王': ['王维娜']
```
Synonyms are segmented and normalized before being stored in Meilisearch and the original value is dropped.
```java
{["推进", "之王"]: [["王维", "娜"]]}
```
> In this example, only the segmentation has an effect, but normalization could alter synonyms in higher proportions by replacing some characters. (`Dæmon` -> `daemon`)

When getting the settings (GET `/indexes/:uid/settings`) the displayed version of synonyms is the normalized one with 1 space between each segmented part.
```java
'推进 之王': ['王维 娜']
```

## drawback

This behavior leads to confusion because users don't see what they originally set.
related to: #2756
related to: https://github.com/meilisearch/product/discussions/503#discussioncomment-4086135
related to: #3883

## Possible enhancement

We should have both versions of the synonyms stored in different "databases"  to:
- remove the confusion coming from the inconsistency between what the user set and what is displayed
- allow Meilisearch to reformat internal synonyms enhancing the relevancy

**Comment by mason-stewart** [comment]
I'm assuming this issue is also why I'm seeing English language contractions that we have in our `synonyms` appearing to have an extra space when getting the index settings in a new index on v1.0.2:

```json
    "ive": [
      "i've"
    ],
    "id": [
      "i'd"
    ],
    "ill": [
      "i'll"
    ],
```

becomes

```json
    "ive": [
      "i' ve"
    ],
    "id": [
      "i' d"
    ],
    "ill": [
      "i' ll"
    ],
```

It appears that the synonyms still behave correctly, but this is _really_ confusing when fine-tuning an index.

**Comment by corean** [comment]
Korean synonyms problem
```
PUT http://localhost:7700/indexes/restaurants_index/settings/synonyms
Content-Type: application/json

{
  "퀸즈" : [
    "퀸스"
  ],
  "퀸스" : [
    "퀸즈"
  ]
}
```
after
```
GET http://localhost:7700/indexes/restaurants_index/settings/synonyms
Accept: application/json

# result
{
  "퀸 즈": [
    "퀸스"
  ],
  "퀸스": [
    "퀸 즈"
  ]
}
```
