### ISSUE TITLE
Improve geo-search: introduction of `_geoBoundingBox`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2761]
Following this product discussion: https://github.com/meilisearch/product/discussions/431
Specification: https://github.com/meilisearch/specifications/pull/197

## API

`_geoBoundingBox((lat, lng), (lat, lng))` using the [`filter` search parameter](https://docs.meilisearch.com/reference/api/search.html#filter)

`{lat, lng}` <- Top left corner,
`{lat, lng}` <- Bottom right corner

## Implementation

- [ ] Implement changes
- [X] Create the spec about name and behavior changes -> https://github.com/meilisearch/specifications/pull/197

## Impacted teams

Pinging @meilisearch/docs-team, also @meilisearch/integration-team even if I'm not sure. Feel free to unsubscribe from this issue if I was wrong to ping you.

---

<s>Pinging @mlemesle since I think you are interested in implementing this 😄 </s>
This issue is opened to anyone!

Feel free to ask any questions to implement this issue. The core team is available to guide you through this contribution, even if it's your first one.
We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by mlemesle** [comment]
Starting the implementation. @curquiza Is there an issue on Milli’s repository that I can link the upcoming PR to ?
If not I can do it but it won’t be as descriptive as yours 😄

**Comment by curquiza** [comment]
Hello @mlemesle 
No need to open an issue on milli side, you can mention this one (only in the PR description not adding it in the `Development` section on the right)
However if you would rather work with an issue on Milli's side, you can open one of course, but it's not mandatory for our synchronisation 😄

**Comment by curquiza** [comment]
Hello @mlemesle! Do you plan to continue your work on https://github.com/meilisearch/milli/pull/640? Since we are in Hacktoberfest, and we would love to see this new feature in the engine, do you think it's possible to open this issue to anyone else? 😄 We would totally understand you don't have the time anymore to work on it

**Comment by curquiza** [comment]
Due to lack of answer this issue is open to anyone wanting to contribute 😇 
A work has already been started at https://github.com/meilisearch/milli/pull/640 (thank you for this)! Someone can take it and start from this point, if useful.

**Comment by mlemesle** [comment]
So sorry @curquiza !
Unfortunately I don't think I'll manage to do this before the end of Hacktoberfest. A lot of work came up recently.
Apologies for not answering earlier

**Comment by curquiza** [comment]
That's ok @mlemesle thanks for letting us know 😄 we completely understand

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.1.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation in [this discussion](https://github.com/meilisearch/product/discussions/431).
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 3rd April 2023

⚠️ RC (release candidates) are not recommended for production
