### ISSUE TITLE
Reduce size of the meilisearch binary

### ISSUE THREAD

**Issue by jirutka** [meilisearch/meilisearch#2774]
Meilisearch binary has over 100 MiB, which is quite huge. About 90% (!) of the size is made up of specialized tokenizations for Chinese, Hebrew, Japanese, and Thai – they bundle large dictionaries. Many Meilisearch users don’t need support for these languages, so it would make sense to make them optional.

**Comment by curquiza** [comment]
@meilisearch/docs-team is it something you want to document?
This involves re-compiling Meilisearch with specific arguments
