### ISSUE TITLE
Re-introducting dumps v1 support for Meilisearch v1?

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2776]
Following the discussion with @Kerollmops but can interest any people in the core team to have your opinion

What we want when releasing v1 is to ensure most people will use it. One of the issue is the migration: currently, someone using Meilisearch v0.20.0 cannot migrate to v0.28.0 (so future meilisearch v1)
See the following table in the specs: https://github.com/meilisearch/specifications/blob/main/text/0105-dumps-api.md#34-dump-version-support

 We just realized this could be a huge issue for our users; indeed, until last August, we had more users in v0.20.0 and before than in v0.21.0 and after, meaning we have a lot of people to migrate to v1! See the [Amplitude graph](https://analytics.amplitude.com/meili/chart/am0ldqv?source=workspace) (internal only)

I open this issue following my discussion with Kero, to see if it's possible to make the v1 dump support come back, or if it's really impossible.
Another question: is it really useful to avoid these two steps since we made a lot of breaking API? Are v0.20.0 and v0.24.0 really different regarding the main API routes (`/search`, `/documents`)? Same question for v0.20.0 -> v0.24.0 and v0.24.0 -> v0.28.0? I mean, it could be useful to let these two steps if the breaking are big between v0.20.0 and v0.24.0

**Comment by curquiza** [comment]
@meilisearch/core-team I would like to have your opinion on this 😇

**Comment by irevoire** [comment]
> is it really useful to avoid these two steps since we made a lot of breaking API?

If someone wants to do it, I think he'll be happier with a one-step process and then fix your settings than a two or three steps process to fix your settings in the exact same way finally.
Also, we're emitting warnings when something changes or a setting has been renamed. To me, it's way easier to follow a one-step process with every warning happening at the same time than aggregating everything over multiple steps.

> I open this issue [...] to see if it's possible to make the v1 dump support come back

Yes, it's possible.

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/meilisearch/issues/2985
