### ISSUE TITLE
bind to ::1 (ipv6) as well by default

### ISSUE THREAD

**Issue by derhuerst** [meilisearch/meilisearch#2782]
**Describe the bug**

By default, Meilisearch will bind to `127.0.0.1:7700`, which makes it IPv4-only. I think nowadays, any networked software should handle IPv6 by default.

```shell
meilisearch &
# Server listening on:	"http://127.0.0.1:7700"

curl -6 'http://localhost:7700/' -f --no-progress-meter >/dev/null
# curl: (7) Failed to connect to localhost port 7700 after 7 ms: Connection refused
curl 'http://[::1]:7700/' -f --no-progress-meter >/dev/null
# curl: (7) Failed to connect to ::1 port 7700 after 11 ms: Connection refused
```

**Expected behavior**

I expect Meilisearch to bind both on `127.0.0.1` and `::1` by default, unless you specifically specify an (different) address via `--http-addr`.

```shell
meilisearch &
# Server listening on:	"http://localhost:7700"

curl -6 'http://localhost:7700/' -f
# <!doc…
```
**Meilisearch version:** [e.g. v0.20.0]

```shell
meilisearch --version
# meilisearch-http 0.28.1
```

**Additional context**

```
Darwin jannis-mba 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64
```

----

# EDIT from the Meilisearch team

**We accept contributions to this issue.**

### How should it work?

When the user is not passing `--http-addr`, the default localhost address should work for ipv4 and ipv6 as well. Only ipv4 is working so far

We have not investigated it yet, and we don't know how to solve it so far. Any help is really appreciated. It means we need someone who already knows how to implement this or who is ok to do some research on their own 😊 

We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by curquiza** [comment]
Hello @derhuerst 

I think this is something we could consider in our CLI stabilization work (https://github.com/meilisearch/meilisearch/issues/2752) @gmourier, if we want to change this or not

**Comment by gmourier** [comment]
Hey @derhuerst

I'm not sure to understand. Why are you trying to reach Meilisearch with `7701` and not `7700`?

**Comment by derhuerst** [comment]
> Why are you trying to reach Meilisearch with `7701` and not `7700`?

Sorry, that is a mistake, I meant `7700`. The point of the `curl -6` command under *Expected behavior* is to show that it should work IPv6-only.

**Comment by derhuerst** [comment]
I have edited the Issue to reflect what I'm asking for.

**Comment by gmourier** [comment]
Thanks, @derhuerst. 

I've asked for confirmation about ipv6 support from the technical team. I will keep you informed, in the meantime you could maybe help us to understand a bit more about your issue.

I'm not sure I understand, my knowledge of the differences with ipv4 and ipv6 is limited.

Tell me if I'm wrong:

- If Meilisearch is mounted on the local loop address in ipv4 format.
- That the server hosting the Meilisearch instance has a public ipv6 address.

If a search client is connected to the ipv6 address, the system should pass the information to the local loop without any problem, right?

If this is the case, what is the need to mount Meilisearch on an ipv6? I may be saying something stupid but I'm curious. :geek: 

Thanks!

**Comment by derhuerst** [comment]
> * If Meilisearch is mounted on the local loop address in ipv4 format. (`127.0.0.1`)
> * And if the server hosting the Meilisearch instance has a public ipv6 address.
> 
> If a search client is reaching the ipv6 address on the right port, the system should pass the request to the local loop ipv4 address without any problem, right?

Sorry for being pedantic here, but I feel like it clarifies the situation: It doesn't have to "pass" the request on. Meilisearch can handle the IPv6 request directly, just like it handles IPv4 requests. In fact, letting Meilisearch listen on the IPv6 loopback interface (`::1`) *already works*!

> If this is the case, what is the need to mount Meilisearch on an ipv6 format locally?

`meilisearch --http-addr '[::1]:7700'` works already.

What I want is that, if a *hostname* (or domain, if you will, e.g. `localhost`) is specified instead of an IPv4/IPv6 address, it should bind to *both* the IPv4 *and* IPv6 address that this hostname resolves to.

For example, if I run `meilisearch --http-addr localhost:7700`, I want to be able to reach it both via `[::1]:7700` and via `127.0.0.1:7700`.

**Comment by curquiza** [comment]
I discussed with @Kerollmops and @gmourier, this is an improvement we would indeed see in our engine. Since we don't really know how to do it and it's not one of our priorities so far, we are really open to contributions!
I've updated the issue description accordingly

**Comment by Fall1ngStar** [comment]
According to [actix doc](https://actix.rs/actix-web/actix_web/struct.HttpServer.html#hostname-resolution), the bind is made for both IPv4 and IPv6 when a hostname is specified (localhost or any FQND). The issue here is that meilisearch binds by default to `127.0.0.1:7700` instead of `localhost:7700`, which limits the bind to the IPv4 address.

The simple fix would then be to change the default bind address value to `localhost:7700`. This may also be an occasion to implement binding to multiple addresses. I have tested some code doing just that, and could make a PR if you are interested in having such a feature

**Comment by Fall1ngStar** [comment]
I was fiddling with binding to multiple addresses before finding that this issue can be addressed with the change to `localhost`. I'm not sure about your question, maybe the original author (@derhuerst) have the answer. The bind to multiple addresses can be useful if one wants to bind to multiple domain name (for instance `foo.com` and `bar.com`). I can submit a PR for either change

**Comment by derhuerst** [comment]
> According to [actix doc](https://actix.rs/actix-web/actix_web/struct.HttpServer.html#hostname-resolution), the bind is made for both IPv4 and IPv6 when a hostname is specified (localhost or any FQND). The issue here is that meilisearch binds by default to `127.0.0.1:7700` instead of `localhost:7700`, which limits the bind to the IPv4 address.
> 
> The simple fix would then be to change the default bind address value to `localhost:7700`.

👍

> Rephrasing; **_Is there a need to bind a ipv4 and a ipv6 addresses other than `127.0.0.1` and `[::1]` with `localhost`_** ?

For example, I might want to bind to a specific network interface that has both (an) IPv4 address(es) as well as (an) IPv6 addresses(es).

**Comment by gmourier** [comment]
Thanks, @Fall1ngStar, and @derhuerst.

Let's change the default binding address to `localhost`. 🚀

> For example, I might want to bind to a specific network interface that has both (an) IPv4 address(es) as well as (an) IPv6 addresses(es).

Wouldn't the convention, in this case, be to give a hostname to the addresses of this network interface within the host file and then use that hostname at launch with `--http-addr`?

**Comment by Fall1ngStar** [comment]
Perfect, I’ll make the PR in the day

**Comment by curquiza** [comment]
@meilisearch/cloud-team let us know if it's ok for you or not!
