### ISSUE TITLE
Corrupted data during search/documents meilisearch

### ISSUE THREAD

**Issue by sojeda** [meilisearch/meilisearch#2784]
**Describe the bug**
On Friday I had 50 thousand records indexed, and at the time of searching everything worked fine. On Sunday it indexes 150 thousand documents, and now when using the endpoint the JSON the returned json is cut (o is cut short)

I couldn't figure out what it was, or if I have to configure anything extra because it used to work with fewer documents before.

**To Reproduce**
1. Go to '/indexes/sn_hotels/search?limit=10000'
2. Response 200 but Json Cut no valid

**Expected behavior**
It should return all hits and a valid JSON

**Screenshots**
![image](https://user-images.githubusercontent.com/17851841/191042070-796c33b5-4a75-4b74-a6ac-53dd827e7bff.png)

Should be:
![image](https://user-images.githubusercontent.com/17851841/191042226-24c60004-f79b-4c5a-956a-8de85f8d7de4.png)

**Meilisearch version:** [e.g. v0.28.0]

**Additional context**
Deployed on GCP
e2-medium

**Comment by sojeda** [comment]
When I have few records it does not happen to me, but when it exceeds 20000, yes.

Could it be the server? I have task enqueued for a long time
```

{
    "uid": 91,
    "indexUid": "sn_hotels",
    "status": "succeeded",
    "type": "documentAdditionOrUpdate",
    "details": {
        "receivedDocuments": 500,
        "indexedDocuments": 500
    },
    "duration": "PT623.204844862S",
    "enqueuedAt": "2022-09-21T15:10:41.257242113Z",
    "startedAt": "2022-09-21T19:51:59.269900588Z",
    "finishedAt": "2022-09-21T20:02:22.47474545Z"
}
```

**Comment by oluademola** [comment]
Hello @sojeda 

It is difficult to ascertain what is wrong as I cannot reproduce the problem. I have tried with an index containing over 100k records, but I do not experience the JSON cut. If your data contains sensitive information, perhaps you could assist prepare non-sensitive data we could use for troubleshooting. 

Regarding indexing speed, it depends on many factors like your server resource (CPU, storage space, and RAM) and many others. How are you sending your documents? Meilisearch prefers to receive documents in batches; hence we often recommend batching your document before sending them to meilisearch for indexing. Meilisearch could do this for you by enabling the [auto-batching feature](https://github.com/meilisearch/meilisearch/discussions/2070); we plan to make this feature available by default in the next version of the engine. Also, kindly follow the best practices in this [guide](https://docs.meilisearch.com/learn/advanced/indexing.html#improving-indexing-performance) and configure your settings before adding your documents to avoid unnecessary double-indexing.

I hope you find this helpful. Thank you 🙂

**Comment by sojeda** [comment]
No problem, thank u! 
Solved!

the problem was that the server had very little disk space left, I leave the comment here in case it helps

**Comment by gmourier** [comment]
Thanks, @sojeda!

DId you find that information by looking at the asynchronous `tasks` resources?
