### ISSUE TITLE
Increase the number of concurrent reader on the indexes

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2786]
In order to fix #2648 you need to find every time we open an index and update the [`EnvOpenOptions`](https://docs.rs/heed/latest/heed/struct.EnvOpenOptions.html) to add the `max_readers` option to 1024.

**Comment by curquiza** [comment]
As far as I understand, the number of readers will now be 1024 and not 126 anymore

Pinging @meilisearch/docs-team: it's related to this issue I opened: https://github.com/meilisearch/documentation/issues/1870
