### ISSUE TITLE
Use wildcard (`*`) at the end of the index names when creating API keys

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2788]
Following
- this product discussion: https://github.com/meilisearch/product/discussions/491
- this spec: https://github.com/meilisearch/specifications/pull/189

## Goal

Allow using the wildcard `*` at the end of the index name (in `indexes` field) when creating API keys

## How does it work?

When [creating an API key](https://docs.meilisearch.com/reference/api/keys.html#create-a-key), the `*` should be available this ways:

```bash
curl \
  -X POST 'http://localhost:7700/keys' \
  -H 'Authorization: Bearer MASTER_KEY' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "description": "Add documents: Products API key",
    "actions": ["documents.add"],
    "indexes": ["products_*"],
    "expiresAt": "2042-04-02T00:42:42Z"
  }'
```

This means the newly created keys will be available for the `products_main`, `products_dev`, but not for `products`

#### Additional explanation of the matching

The `books*` expression will match the following indexes: `books`, `books_staging`, but NOT `book` (without `s`)

#### Errors

- if no indexes are matched, no error are thrown during the API key creation. However this key will be useless until a matching index is created

## Impacted teams

Pinging @meilisearch/docs-team, but also @meilisearch/integration-team (I'm not sure for you)

--- 

## Todo
- [ ] Implementation the changes -> Open to external contributions
- [X] Update the spec -> https://github.com/meilisearch/specifications/pull/189

---
Feel free to ask any questions to implement this issue. The core team is available to guide you through this contribution, even if it's your first one.
We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by suselunarwolf** [comment]
Hi ,is the issue is still open.how can i contribute on this issue.

**Comment by curquiza** [comment]
Hello @suselunarwolf 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!
Our contributing guidelines are available [here](../blob/main/CONTRIBUTING.md) and will guide you through your contribution. If you have any question you can also ask them here!

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by Ugzuzg** [comment]
- Can the wildcard be at the start of the pattern? `*_end`
- Can it be in the middle of the pattern? `start_*_end`
- Can there be multiple wildcards in a single pattern? `start_*_middle_*_end`

**Comment by irevoire** [comment]
From what I understand of the product discussion, what we want here is;
> It could make the creation of an API key easier and faster in case several indexes are **prefixed** by a fixed string and need to be accessible by the same key.

This means we only accept API keys that end with a wildcard and nothing more.
Thus only `start_*` and none of your examples.

Just to be absolutely sure, can you confirm @gmourier?

**Comment by Enforcer007** [comment]
I've started working on this feature. Will let you give a PR shortly.

**Comment by Enforcer007** [comment]
What's the idea behind using (uid, action, index_name) as key for action_keyid_index_expiration database ?

Can just use (UID,) as the key 🗝️.

**Comment by gmourier** [comment]
Hi everyone 👋

Answering to https://github.com/meilisearch/meilisearch/issues/2788#issuecomment-1264628190 and https://github.com/meilisearch/meilisearch/issues/2788#issuecomment-1264478468

> This means we only accept API keys that end with a wildcard and nothing more.
Thus only start_* and none of your examples.

What do you think of making it more versatile without enforcing a specific indexes name format? Do we see issues by doing that?

Listing @Ugzuzg ideas here:

- Can the wildcard be at the start of the pattern? *_end
- Can it be in the middle of the pattern? start_*_end
- Can there be multiple wildcards in a single pattern? start_*_middle_*_end
- Can it be at the start and the end? *_middle_*

@Ugzuzg Do you have particular needs for these syntaxes?

**Comment by gmourier** [comment]
> What's the idea behind using (uid, action, index_name) as key for action_keyid_index_expiration database ?

Can just use (UID,) as the key 🗝️.

Not sure to understand your question @Enforcer007! I'm sorry.

**Comment by Ugzuzg** [comment]
Not really. I wanted to start working on this, so tried to clear up the requirements.

**Comment by Enforcer007** [comment]
> What's the idea behind using (uid, action, index_name) as key for action_keyid_index_expiration database ?
> 
> Can just use (UID,) as the key old_key.

I've got it, keys are hashed with respect to uid ,index_name, and action. For every request, uid, index_name and action are extracted and then compared with the hashed keys of action_keyid_index_expiration database.

For implementing the index pattern, I think we need to take out the index_name from the key and put into value as series of indexes. i.e, `uid, action` will be key  and `all indexes, key_expires at` form the values.

**Comment by irevoire** [comment]
@gmourier 
> What do you think of making it more versatile without enforcing a specific indexes name format? Do we see issues by doing that? 

Personally I don't mind, maybe someone else from the core-team will have something to say though @ManyTheFish, @loiclec or @Kerollmops (answer fast please so we don't block the contributors).

BUT;
1. We should not try to handle anything more than what is provided in the regex crate of rust.
2. We should put some limit on the regex engine to be sure nothing can DOS us. See https://docs.rs/regex/latest/regex/#untrusted-input

**Comment by gmourier** [comment]
Thanks, @irevoire and @Ugzuzg!

In my opinion, these patterns can be adapted to most cases.

- *_end
- start_*_end
- start_*

I think it should also be integrated into the `searchRules` of the tenant tokens.

**Comment by curquiza** [comment]
> 🤓 I think It should also be integrated into the searchRules of the tenant tokens.

For contributors: please only open a PR for the actions when creating indexes, I will open another issue (+ PR) for the tenant token

**Comment by curquiza** [comment]
Discussed with the team: this issue is finally not about "globing" but only allowing the `*` character at the END of the `indexes` field when creating API key. I've clarify the issue accordingly.

The other patterns described in this issue are still relevant but lead to
- more product discussion: it means creating a real globing, and so, which globbing RFC do we want to follow? Bash? Another?
- how do we want to implement this regarding the code base?

📣 If anyone here thinks the globing can be relevant in their use case or have ideas about implementation, please open a discussion describing your use case and what you would expect to have as feature here: https://github.com/meilisearch/product/discussions

**Comment by curquiza** [comment]
For meili team: the related spec has been updated and added to the issue description: https://github.com/meilisearch/specifications/pull/189

**Comment by curquiza** [comment]
Impossible to do it during the v1 sprint to prioritize other improvements.

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.1.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation in [this discussion](https://github.com/meilisearch/product/discussions/491).
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 3rd April 2023

⚠️ RC (release candidates) are not recommended for productionhttps://github.com/meilisearch/product/discussions/491
