### ISSUE TITLE
Selecting multiple of the same facet not working

### ISSUE THREAD

**Issue by anthonycook** [meilisearch/meilisearch#2791]
When I select a facet I can't select more than one as they disappear, see the example video below where I can not select another brand as it they disappear when applying the filter.

[Video Here](https://drive.google.com/file/d/1s0oPtGWL7CI4VhJFFcZ6aMefq7uavilU/view?usp=sharing)

That example is using instant search but even when writing a raw query it happens:

Example query:
```json
{
    "q": "warhammer",
    "facets": [
        "brand",
        "type"
    ],
    "filter": [
        [
            "brand=\"Games Workshop\""
        ]
    ]
}
```

Example response (notice only one brand in facetDistribution)

```json
{
    "hits": ["...."],
    "estimatedTotalHits": 20,
    "query": "warhammer",
    "limit": 20,
    "offset": 0,
    "processingTimeMs": 3,
    "facetDistribution": {
        "brand": {
            "Games Workshop": 20
        },
        "type": {
            "Box Set": 1,
            "Card Pack": 7,
            "Dice": 4,
            "Miniatures": 1,
            "Model": 5,
            "Model Pack": 2
        }
    }
}
```

I've tried indexing my documents with the date types of string and then as an array of strings on a fresh index, neither of which worked. Both brand and type are in the `filterableAttributes` settings array.

**To Reproduce**

1. Create and index and populate data
2. Use a  MeiliSearch example with instantsearch or write a simple facet query

**Expected behaviour**

I expect to be able to apply multiple facets for the same facet, for example if I want to select multiple brands, colours, sizes etc.

**Meilisearch version:**

v0.28.1

**Additional context**

When running the MeiliSearch e-commerce example this issue is not present and multi-faceting works as intended. I have read the documentation on facets and I still can see a reason why it's not working for me

**Comment by gmourier** [comment]
Hi, @anthonycook 

This is related to how facets are computed; you will find more information [here](https://github.com/meilisearch/product/discussions/187#discussioncomment-3631390). There is something we want to solve, but we do not know how/when exactly (It could be solved by emitting multiple requests from instant-meilisearch (for a first iteration) or Meilisearch API could accept an array of requests).

**Comment by anthonycook** [comment]
> Hi, @anthonycook
> 
> It seems related to how facets are computed; you will find more information [here](https://github.com/meilisearch/product/discussions/187#discussioncomment-3631390).
> 
> We want to solve this, but we do not know how/when exactly (It could be solved by emitting multiple HTTP requests from instant-meilisearch or Meilisearch API could handle it (either with one HTTP request containing multiple search requests, either by managing it automatically in a single request from the `filter` clause).

Hi @gmourier,

Thanks for the reply, when checking out the demos repo I can see that it has this functionally and it works as I would expect (you can select multiple genres for example). How does the demo achieve this?

Demo:
[https://codesandbox.io/s/ms-is-mese9?fontsize=14&hidenavigation=1&theme=dark](url)

**Comment by gmourier** [comment]
I think this is because you may only have one brand per document, right?

So Meilisearch will filter out every other documents that are branded by `Games Workshop`. In the demo that you shared, documents have multiple genres.

**Comment by anthonycook** [comment]
> I think this is because you may only have one brand per document, right?
> 
> So Meilisearch will filter out every other documents that are not branded by `Games Workshop`. In the demo that you shared, documents have multiple genres. Thus, Meilisearch can extract other values for that facet from the documents being returned.

That makes sense, thank you for taking the time to explain it to me. Hopefully there will be a solution for this in the future.

**Comment by gmourier** [comment]
https://github.com/meilisearch/product/discussions/187#discussioncomment-3699746 

We will try to fix this from the instant-meilisearch side as a first iteration!
