### ISSUE TITLE
Add CI job to create a silicon macos binary

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2792]
Following this product discussion: https://github.com/meilisearch/product/discussions/518

## Goal

For each release, we run a CI creating binaries corresponding to the new release.
Currently, we don't provide any binaries natively compatible with Apple Silicon computers

## How?

In this file: https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-binaries.yml
- create a new job `publish-macos-apple-silicon`
- This new job should have `needs: check-version`
- This new job should run on `runs-on: macos-latest`
- This binary should be compiled with the following Rust target: `aarch64-apple-darwin`
- The final binary name should be `meilisearch-macos-apple-silicon`

---

Feel free to ask any questions to implement this issue. The core team is available to guide you through this contribution, even if it's your first one.
We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by mohitsaxenaknoldus** [comment]
Hey, can I work on this one?

**Comment by curquiza** [comment]
Hello @mohitsaxenaknoldus

yes you can! 😄 
Thanks for your interest in this project :)

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch-dotnet/blob/main/CONTRIBUTING.md).

We are looking forward to reviewing your PR 😊

**Comment by evanxg852000** [comment]
Please @curquiza, I guess this is using a self-hosted runner right?

**Comment by curquiza** [comment]
Hello @evanxg852000, we are using a provided GitHub runner to compile and publish this binary.
Why?

**Comment by evanxg852000** [comment]
I am trying to achieve the same thing but the runner Github action is providing is x86_64 instead of an M1 arm64 platform.

**Comment by curquiza** [comment]
We simply use the `macos-latest` GitHub runner, with the following target when building Meilisearch
https://github.com/meilisearch/meilisearch/blob/914f8b118ceb1e236e1d2c2bbaa8a788fc5a3648/.github/workflows/publish-binaries.yml#L81

And the final binary is as following

```bash
$ file meilisearch-macos-apple-silicon
meilisearch-macos-apple-silicon: Mach-O 64-bit executable arm64
```
