### ISSUE TITLE
Rename `receivedDocumentIds` into `matchedDocuments`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2799]
In the case Meilisearch is doing a deletion by batch using the following route `POST /indexes/{{indexUID}}/documents/delete-batch`, the task information retrieve when getting `GET /tasks/{{taskUID}}` are as following:

```json
{
            "uid": 1,
            "indexUid": "books",
            "status": "succeeded",
            "type": "documentDeletion",
            "details": {
                "receivedDocumentIds": 2,
                "deletedDocuments": 2
            },
            "duration": "PT0.007031500S",
            "enqueuedAt": "2022-09-26T12:39:38.7957508Z",
            "startedAt": "2022-09-26T12:39:38.8008695Z",
            "finishedAt": "2022-09-26T12:39:38.807901Z"
}
```

We need to replace `receivedDocumentIds` by `matchedDocuments`

## TODO

- [ ] Implement the changes and merge to the `main` branch (this part is available for external contributions)
- [ ] Update the related spec

## Impacted teams

This issue impacts the following teams: @meilisearch/docs-team and @meilisearch/integration-team in some of your strongly typed SDKs
Sorry for this breaking change, we missed it during the stabilization. Should not be that much impactful for the users since the route is not the most used one

**Comment by YashPimple** [comment]
@curquiza can you assign it to me would like to work on it?

**Comment by curquiza** [comment]
Hello @YashPimple 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by curquiza** [comment]
Spec added to the issue description https://github.com/meilisearch/specifications/pull/188

**Comment by curquiza** [comment]
⚠️ This issue is not over and continue here: https://github.com/meilisearch/meilisearch/issues/3078
`matchedDocuments` is not the definitive word
