### ISSUE TITLE
Add environement variable `MEILI_CONFIG_FILE_PATH` to define the config file path

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2800]
Should be done once this PR is merge: https://github.com/meilisearch/meilisearch/pull/2745
This issue is a sub issue of https://github.com/meilisearch/meilisearch/issues/2558

Once https://github.com/meilisearch/meilisearch/pull/2745 is merged, it will be possible to pass a config file by using `--config-file-path` flag. We need to create the associated env variable `MEILI_CONFIG_FILE_PATH`

**Comment by choznerol** [comment]
If both `--config-file-path` and `MEILI_CONFIG_FILE_PATH` are present, which one should take precedence?
