### ISSUE TITLE
Return error when `config_file_path` is put in the config file

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2801]
It should be done once this PR is merged: https://github.com/meilisearch/meilisearch/pull/2745
This issue is a sub-issue of https://github.com/meilisearch/meilisearch/issues/2558

Once https://github.com/meilisearch/meilisearch/pull/2745 is merged, it will be possible to pass a config file to Meilisearch. When using a key that is not known by Meilisearch in the config file (for instance, "no_analytic" instead of "no_analytics"), Meilisearch returns an error when trying to read the config file.
Currently, if you enter the `config_path_file` key, Meilisearch does not return any error and ignores the key silently. We need to return an error saying this key is not accepted.

**Comment by Celeo** [comment]
Is this the only key that would prompt such an error, or is / would there be a list of these such keys?

**Comment by curquiza** [comment]
Hello @Celeo 
So far, it's the only key with this specificity 😊

**Comment by curquiza** [comment]
FYI https://github.com/meilisearch/meilisearch/pull/2745 has been merged and is ready to be implemented! 🎉

**Comment by curquiza** [comment]
Not exactly.
Meilisearch accepts a config file since https://github.com/meilisearch/meilisearch/pull/2745 was merged.
To let Meilisearch know you have a config file, either your file is `./config.toml`, or your file is passed via the `--config-file-path` flag.

But in the config file itself, we don't want to let the users define the path of the config file: it makes no sense, like a "loop", since you already are in the config file. Do you see what I mean?
That's why we would like Meilisearch to return a message saying the key `config_file_path` is not valid.
