### ISSUE TITLE
Support gzip, brotli, and deflate in requests and responses

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#2802]
We would like Meilisearch to accept user queries that are `content-encoded` in `gzip`, `br`, and `deflate`. This way, users will be able to send their payloads directly in gzip, brotli, or deflate to the engine, and the engine should be able to receive it blindly.

We are using actix-web for our HTTP engine. There already is [a middleware that is made explicitly for that](https://docs.rs/actix-web/latest/actix_web/middleware/struct.Compress.html).

Another functionality that this middleware should support is compressing the output of the engine too. It is useful when requesting many documents or facets, for example.

We want this feature to be tested to ensure that nothing wrong can happen when a user sends compressed documents or wants to receive a compressed HTTP response. You can look [at the actix-web tests to start](https://github.com/actix/actix-web/blob/ad7e67f940f0ebd25e0ad2bf1642b65b92df8e18/actix-web/src/middleware/compress.rs#L292-L302).

---

Edit from @curquiza 

## Impacted team

@meilisearch/docs-team this is something we would like to see mentioned in the documentation but NOT detailed. I mean, people should find the information about "the engine can accept gzip content" when typing "gzip" or "compressed". No need to detailed, this is something people already know if they need it, and 90% of the job is done by the browser

## TODO

- [ ] Implement the changes and merge to the `main` branch
- [ ] Update the related spec

**Comment by amab8901** [comment]
I'll try solving this!

**Comment by curquiza** [comment]
Hello @amab8901 

Thanks for your involvement 😇

**Comment by amab8901** [comment]
that makes sense. Also if someone finishes it before me, then I can use their solution as feedback on what I missed in my own attempts

**Comment by psvnlsaikumar** [comment]
I have run the below cURL and the index did seem to have created.

`echo '{"uid": "sai-test-temp","primaryKey": "id"}' | gzip | curl -v -i --data-binary @- -H "Content-Encoding: gzip"  -H "Content-Type: application/json" http://localhost:7700/indexes`

Below is the full verbose mode of this cURL

` $ echo '{"uid": "sai-test-temp","primaryKey": "id"}' | gzip | curl -v -i --data-binary @- -H "Content-Encoding: gzip"  -H "Content-Type: application/json" http://localhost:7700/indexes
*   Trying ::1:7700...
* TCP_NODELAY set
* connect to ::1 port 7700 failed: Connection refused
*   Trying 127.0.0.1:7700...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 7700 (#0)
> POST /indexes HTTP/1.1
> Host: localhost:7700
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Encoding: gzip
> Content-Type: application/json
> Content-Length: 59
> 
* upload completely sent off: 59 out of 59 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 202 Accepted
HTTP/1.1 202 Accepted
< content-length: 129
content-length: 129
< access-control-allow-origin: *
access-control-allow-origin: *
< content-type: application/json
content-type: application/json
< vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
< date: Sun, 02 Oct 2022 18:11:59 GMT
date: Sun, 02 Oct 2022 18:11:59 GMT

< 
* Connection #0 to host localhost left intact
{"taskUid":7,"indexUid":"sai-test-temp","status":"enqueued","type":"indexCreation","enqueuedAt":"2022-10-02T18:11:59.154494098Z"}
`
Based on what I've understood, if we were to compress a request using gzip compression, then the request is expected to either not work, or fail. This does not seem to be happening here.

Is my interpretation correct?

**Comment by Kerollmops** [comment]
Hey @psvnlsaikumar,

It is strange indeed as we never changed anything on our side to accept compressed requests. This issue was raised because we wanted our users to be able to send documents, e.g. CSV, JSON, JSON-lines, in a compressed manner. On the other hand, we would also like to compress a server answer if it is possible.

> Is my interpretation correct?

Don't you think that it would be possible that cURL would do a preflight call to the server to check that it support gzip compressed content and uncompress it on the fly? I would find it **very** strange. I am just guessing...

**Comment by psvnlsaikumar** [comment]
@Kerollmops 
if the cURL would do a preflight call, and then uncompress it before sending the request, the content-encoding header of the request would have been changed is what I am expecting
I am not sure if it would uncompress the requests while in transit though. or maybe there is some change in the actix?
Were there any logs that we can look at when the request failed from the time when we created the issue?

**Comment by amab8901** [comment]
> @Kerollmops
> 
> I guess the request works fine for creating indexes, but fails on creating documents. I just tried sending request for documents, and it seems to be failing.
> 
> Reference cURL
> 
> ```
> cat movies.json | gzip | curl -v -i --data-binary @- -H "Content-Type: application/json" -H "Content-Encoding: gzip" -X POST http://localhost:7700/indexes/sai-test-temp/documents
> ```
> 
> response :
> 
> ```
> "message":"The `json` payload provided is malformed. `Couldn't serialize document value: expected value at line 1 column 1`.","code":"malformed_payload","type":"invalid_request","link":"https://docs.meilisearch.com/errors#malformed_payload
> ```

Why do you have to write `--data-binary` on the curl? Isn't the data already binary from the gzip?

**Comment by amab8901** [comment]
Oh! I found how to reproduce the problem for POST method (inserting docs into the database):
```
cat meteorites.json | gzip | curl -vi --data-binary @- -H "Content-Type: application/gzip" -X POST http://localhost:7700/indexes/meteorites/documents
```
Here is the output:
```
{"message":"The Content-Type `application/gzip` is invalid. Accepted values for the Content-Type header are: `application/json`, `application/x-ndjson`, `text/csv`","code":"invalid_content_type","type":"invalid_request","link":"https://docs.meilisearch.com/errors#invalid_content_type"}
```
That looks about right!

**Comment by mou** [comment]
The reason why some requests support various content-encodings and others do not lie in structures representing requests. Most of the bodies are represented by actix built-in JSON-related structs, which utilize decompression logic (via Payload wrapping). Still, API for documents uses custom-implemented stream-like structures (I think to avoid huge instant allocations).

**Comment by amab8901** [comment]
so what is left to do, now that a commit has been submitted?

**Comment by curquiza** [comment]
Hello @amab8901 we will review the PR soon, and we'll let you know if something is missing and still need to be implemented 😄

**Comment by curquiza** [comment]
For meili teams: I've added the spec freshly opened to the issue description 
https://github.com/meilisearch/specifications/pull/178
