### ISSUE TITLE
Enable the client to specify a custom csv delimiter for parsing documents

### ISSUE THREAD

**Issue by MixusMinimax** [meilisearch/meilisearch#2806]
Relates to [meilisearch/product#535](https://github.com/meilisearch/product/discussions/535)

Currently, a default `csv::Reader` is created to parse documents that are passed as csv. I think it would be nice if the user could specify the delimiter, because very often, we have tons of documents from other sources that don't use commas.

**Comment by curquiza** [comment]
Hello @MixusMinimax!

Thanks again for this suggestion, I discussed it with our PM, and we think it could be indeed useful. However, as I told you already in the PR, this impacts the user interface and the product team need more time to really think about the suggestion.

So I will close this issue in favor of this discussion in the product repo https://github.com/meilisearch/product/discussions/541
The [product repository](https://github.com/meilisearch/product/discussions) is where we discuss the product improvements before choosing to implement them in the code base

However I let the PR open: if we decide to go with your solution, we will use your work. If you're not available at the this moment, and if we need to apply changes, we will merge your branch in a temporary branch, we will continue the work, and then merge this temporary branch into `main`.

Thanks again for the suggestion, it brings an interesting point to our product table! 😄
