### ISSUE TITLE
Missing Test for Filtering of GET Requests

### ISSUE THREAD

**Issue by amab8901** [meilisearch/meilisearch#2809]
**Describe the bug**
You can send GET request to get filtered documents, but this functionality isn't covered in the tests. We need this scenario to be covered in the tests to increase robustness and not leave anything to chance. Otherwise it could be a blindspot for bugs and other types of issues.

**To Reproduce**
1. Send API request to `http://localhost:7700/indexes/meteorites/search` (after you uploaded meteorites documents, of course). API request should include query parameter ` "filter": "mass < 1" `
2. Now try finding tests in the source code that describe this type of scenario. Can't find anything.

**Expected behavior**
There should be a test that specifies how the app should behave in this scenario.

**Meilisearch version:** [e.g. v0.20.0]
I pulled the source code from main repository about a week ago (~20 september)

**Comment by amab8901** [comment]
Here's what I wrote so far:

```
#[actix_rt::test]
async fn get_filtered_document() {
    let server = Server::new().await;
    let index = server.index("test");
    index.create(None).await;
    let documents =
        serde_json::json!([
        {
            "id": 0,
            "results": [
                {
                    "name": "Aachen",
                    "id": "1",
                    "nametype": "Valid",
                    "recclass": "L5",
                    "mass": 21,
                    "fall": "Fell",
                    "_geo": {
                        "lat": 50.775,
                        "lng": 6.08333
                    }
                },
                {
                    "name": "Aarhus",
                    "id": "2",
                    "nametype": "Valid",
                    "recclass": "H6",
                    "mass": 720,
                    "fall": "Fell",
                    "_geo": {
                        "lat": 56.18333,
                        "lng": 10.23333
                    }
                },
            ],
            "offset": 0,
            "limit": 2,
            "total": 2
	    }
    ]);

    let (_, code) = index.add_documents(documents, None).await;
    assert_eq!(code, 202);
    index.wait_task(1).await;

    let get_document_options = GetDocumentOptions {
        fields: Some(vec!["filter"]),
    };

    let option = Some(get_document_options);
    let (response, code) = index.get_document(
        0,
        option,
    ).await;
    assert_eq!(code, 200);
    assert_eq!(
        response,
        serde_json::json!(
        {
            "id": 0,
            "results": [
                {
                    "name": "Aachen",
                    "id": "1",
                    "nametype": "Valid",
                    "recclass": "L5",
                    "mass": 21,
                    "fall": "Fell",
                    "_geo": {
                        "lat": 50.775,
                        "lng": 6.08333
                    }
                },
                {
                    "name": "Aarhus",
                    "id": "2",
                    "nametype": "Valid",
                    "recclass": "H6",
                    "mass": 720,
                    "fall": "Fell",
                    "_geo": {
                        "lat": 56.18333,
                        "lng": 10.23333
                    }
                },
            ],
            "offset": 0,
            "limit": 2,
            "total": 2
        }
    ));

}
```

The biggest challenge for me is this row:
`fields: Some(vec![""]),`

No matter what I insert as argument in `vec![]`, it returns only an empty object (and consequently the test fails

**Comment by irevoire** [comment]
Hey, @amab8901, thanks for your enthusiasm!

Meilisearch does not execute the filters; that's why there is not much test in this repository.
The actual filtering happens in [milli](https://github.com/meilisearch/milli), and there is a bunch of tests that cover a different part of the filtering process;
- [The parsing tests](https://github.com/meilisearch/milli/blob/main/filter-parser/src/lib.rs#L400)
- [The unit tests of the execution](https://github.com/meilisearch/milli/blob/main/milli/src/search/facet/filter.rs#L496)
- [The integration tests](https://github.com/meilisearch/milli/blob/main/milli/tests/search/filters.rs)

**Comment by curquiza** [comment]
Hello @amab8901!
Thanks @irevoire, for having answered

I close this issue then since the answer has been given, and the tests exist on milli's side! 😊
