### ISSUE TITLE
Add support for logging to local syslog

### ISSUE THREAD

**Issue by jirutka** [meilisearch/meilisearch#2811]
Meilisearch HTTP currently logs all messages to the stderr output. When Meilisearch is run as a system service, users usually want to aggregate logs from all system services and reroute them as needed (to different files, remote log servers etc.). Unix systems typically use syslog for this.

**Comment by curquiza** [comment]
Hello @MixusMinimax!

Thanks again for this suggestion, I discussed it with our PM, and we think it could be indeed useful. However, this impacts the user interface, and the product team needs more time to really think about the suggestion. Unfortunately, this feature is not the one we want to prioritize right now, we have other features to work on before this one, so I cannot give you any precise ETA.

So I will close this issue in favor of this discussion in the product repo https://github.com/meilisearch/product/discussions/543
The [product repository](https://github.com/meilisearch/product/discussions) is where we discuss the product improvements before choosing to implement them in the code base

However, I let [the PR](https://github.com/meilisearch/meilisearch/pull/2812) open: if we decide to go with your solution, we will use your work. If you're not available at this moment, and if we need to apply changes, we will merge your branch into a temporary branch, we will continue the work, and then merge this temporary branch into `main`.

Thanks again for the suggestion, it brings an interesting point to our product table! 😄

**Comment by jirutka** [comment]
> Some users seem to ask Meilisearch to return the information into a specified file (if required).

Not to a specific file, but to [syslog](https://en.wikipedia.org/wiki/Syslog), the standard for message logging on unix systems.
