### ISSUE TITLE
Cannot allocate memory (os error 32) when there is memory left 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2832]
**Describe the bug**
I created 1200 indexes, for that I updated my `ulimit` to 2000. Then I opened the mini-dashboard and received the following error:

```
Cannot allocate memory (os error 12)
```

After checking with my ram consumption this is where I am:
<img width="851" alt="Screenshot 2022-10-03 at 12 44 07" src="https://user-images.githubusercontent.com/33010418/193558991-e0212496-2a46-4cf0-8f39-eba312baf209.png">

<img width="607" alt="Screenshot 2022-10-03 at 12 44 20" src="https://user-images.githubusercontent.com/33010418/193559030-02dce686-dd96-4d70-8b64-c8c6ddd8b21f.png">

I'm not sure why I get this error as it seems that I still have enough space left.

**To Reproduce**
1. Create 1200 indexes
2. Run mini dashboard

**Expected behavior**
No memory issue

**Screenshots**

**Meilisearch version:**
v0.29.0

**Additional context**
Additional information that may be relevant to the issue.
MacOs Monterey
M1
Memory: 32gb
Used `chrome` for the mini dashboard

**Comment by bidoubiwa** [comment]
It is not linked to the minidashboard. I tried it on a different browser configuration

**Comment by curquiza** [comment]
Hello @bidoubiwa 
Isn't it the same issue as https://github.com/meilisearch/meilisearch/issues/1841?

**Comment by bidoubiwa** [comment]
Indeed it is a duplicate!

**Comment by curquiza** [comment]
Closing then!
