### ISSUE TITLE
POST & PUT are not used in restful style?

### ISSUE THREAD

**Issue by kuchaguangjie** [meilisearch/meilisearch#2842]
In `Restful` API:
- `POST` should always create a new entity.
- `PUT` should replace the entity entirely.
- `PATCH` is the one used to update entity partially.

But in `meilisearch`:
- `POST` `/indexes/{index_uid}/documents` add or replace documents.
  So, it's like a combination of restful's `POST` and `PUT`.
- `PUT` `/indexes/{index_uid}/documents` add or update documents.
  So, it's like a combination of restful's `POST` and `PATCH`.

Isn't that a bit weird? Or, it's a trade off for simplicity?

**Comment by curquiza** [comment]
Hello @kuchaguangjie 

@gmourier will be the best to answer this 😇

**Comment by gmourier** [comment]
Hi everyone 👋

I understand it can be a bit weird at first but it seems there is no direct solution to that. 

The **resource** being manipulated is not a document but the documents in an index.

If we wanted to be fully compliant with the HTTP Verbs RFC, we would have to update the documents directly via an `indexes/:indexUid/documents/:documentId` resource. Doing that could be dramatic for the DX.

To avoid making a huge breaking change without being much impactful before v1.0, we don't want to change the verbs used.

We could consider it for a v2.0, giving us more time to look at it and communicate effectively the reasons for the change.

I hope that my answer helps you to understand the reasons.

**Comment by kuchaguangjie** [comment]
If u r going to change that some way later, don't forget that: **user api capability has higher priority than obey some standards.** (aka. don't break user's code).

**Comment by curquiza** [comment]
Thanks @kuchaguangjie for your feeedback, I personally completely agree with you.

I close this issue then. Feel free to ask to re-open if needed 😊

**Comment by gmourier** [comment]
> If u r going to change that some way later, don't forget that: user api compatibility has higher priority than obey some standards. (aka. don't break user's code, unless absolutely necessary).

Thanks, @kuchaguangjie. That's exactly our mantra about it.  If it has to happen someday we will consider it twice before doing it.
