### ISSUE TITLE
Upgrade `clap` dependency to 4.0

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#2846]
Currently `meilisearch-http` and `meilisearch-lib` depend on `clap 3.1.6`. We would like to upgrade it to `clap 4.0.9`. The changelog/migration guide with the list of breaking changes is available here: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#400---2022-09-28

Ideally the behaviour and format of the meilisearch command line would not change by upgrading `clap`.

---
Feel free to ask any questions to implement this issue. The core team is available to guide you through this contribution, even if it's your first one.
We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by yenwel** [comment]
I'm attempting this for hacktoberfest

**Comment by choznerol** [comment]
> I'm attempting this for hacktoberfest

Hi @yenwel not sure why it doesn't show up in the `Development` section of right panel, but earlier I have submit #2851 for this issue 😅

**Comment by curquiza** [comment]
> Hi @yenwel not sure why it doesn't show up in the Development section of right panel, but earlier I have submit https://github.com/meilisearch/meilisearch/pull/2851 for this issue 😅

Don't know why but sometime GitHub fails to link the issue to the PR when you write "fixes #..." in the PR description, but you can add it manually on your PR @choznerol 😉 

Indeed @yenwel someone already submitted a PR, if it follows the quality standard and what we expect, we will merge this one! Thanks for your interest, we still have plenty of issues to solve: https://github.com/search?q=org%3Ameilisearch+label%3Ahacktoberfest&state=open&type=Issues

**Comment by yenwel** [comment]
> > Hi @yenwel not sure why it doesn't show up in the Development section of right panel, but earlier I have submit #2851 for this issue 😅
> 
> Don't know why but sometime GitHub fails to link the issue to the PR when you write "fixes #..." in the PR description, but you can add it manually on your PR @choznerol 😉
> 
> Indeed @yenwel someone already submitted a PR, if it follows the quality standard and what we expect, we will merge this one! Thanks for your interest, we still have plenty of issues to solve: https://github.com/search?q=org%3Ameilisearch+label%3Ahacktoberfest&state=open&type=Issues

Ok thx good then that I commented. Got it compiling anyway so far I'll if there is any low hanging fruit remaining

**Comment by choznerol** [comment]
> Don't know why but sometime GitHub fails to link the issue to the PR when you write "fixes #..." in the PR description, but you can add it manually on your PR @choznerol 😉

Turn out it was me accidentally write `fixes #2847` instead of `fixes #2846` 😂
