### ISSUE TITLE
Help us improve Meilisearch's language support!

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2859]
Hello everyone,

I know a lot of you are watching this repository and are coming from different countries, speaking different languages, and you might want Meilisearch to improve regarding your own language. It could be possible thanks to you!
However, the issues are not available in this repository since another repository handles the language: [charabia](https://github.com/meilisearch/charabia), the Meilisearch's tokenizer 

For Hacktoberfest, @ManyTheFish worked on opening a lot of issues to make you improve Meilisearch's language support
- For Chinese issues, [check out this discussion](https://github.com/meilisearch/product/discussions/503#discussioncomment-3806130)
- For Japanese issues, [check out this discussion](https://github.com/meilisearch/product/discussions/532#discussioncomment-3806543)
- To add the Arabic language, [check out this one](https://github.com/meilisearch/product/discussions/139#discussioncomment-3806672)
-  And for any other language issues, please check [the charabia's issues](https://github.com/meilisearch/charabia/issues)

Thanks in advance for your help, see you soon in the Charabia repo then 👋

**Comment by ManyTheFish** [comment]
@curquiza, should we close this issue?

**Comment by curquiza** [comment]
Indeed! Hacktoberfest is over! thanks many
