### ISSUE TITLE
Help us improve the engine for Hacktoberfest!

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2860]
Hello everyone,

I know a lot of you are watching this repository, and if you read our [contributing guidelines](../blob/main/CONTRIBUTING.md), you might see the core-search-engine is not in this repository but in the [Milli](https://github.com/meilisearch/milli) one, that handle the indexation and the search of one single index.

This means, a lot of issues you might want to do are present in the Milli repo, and not in this one. If you are interested in contributing to the deep search engine of Meilisearch, please check out [these issues](https://github.com/meilisearch/milli/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest)

Thanks in advance for your help, see you soon in the Milli repo then 👋

**Comment by Thenitesh143** [comment]
Can you please assign me this project

**Comment by ManyTheFish** [comment]
@curquiza, should we close this issue?

**Comment by curquiza** [comment]
Indeed! Hacktoberfest is over! thanks many
