### ISSUE TITLE
Cache in GitHub CI - temporarelly commented

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2864]
We had weird issue with our CI to be able to merge our PR:

<img width="1905" alt="Capture d’écran 2022-10-06 à 15 14 24" src="https://user-images.githubusercontent.com/20380692/194322335-87400673-f5d1-44df-a548-691c05fd8c45.png">

[Detailed logs](https://github.com/meilisearch/meilisearch/actions/runs/3196622099/jobs/5218796961) (will disappear in 90 days)

To fix this, we had to comment the job steps about the cache: https://github.com/meilisearch/meilisearch/pull/2862/commits/ab17c0acd570eb3c917b7c98c984a84bea070115

I currently don't know where this issue comes from, especially it only happens when using bors.

If someone has a clue, please let us know. So far, we let the steps commented, but the goal is to use the cache again.

**Comment by curquiza** [comment]
Some additional information: the issue never happened when using ubuntu-20.04, it's maybe related. In any case, we cannot use ubuntu-20.04 for the moment.

**Comment by AntoniosBarotsis** [comment]
Not entirely sure but with some googling it seems that this might be an issue with GH Runners.

See [here](https://github.com/community/community/discussions/26321?sort=new).

**Comment by AM1TB** [comment]
Looking at this error: 
```
Download action repository 'actions/checkout@v3' (SHA:2541b1294d2704b0964813337f33b291d3f8596b)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_942bfc42-c672-42eb-a2d9-72752fbe8882/83cc7301-c940-4699-8e89-4fa5ee28a2f1.tar.gz. return code: 2.
```
![image](https://user-images.githubusercontent.com/6761018/194375539-4f98df1f-1a24-4597-93f6-54f8e7f09272.png)
And going through the issue reported here https://github.com/actions/checkout/issues/948 this seems related to the [incident](https://www.githubstatus.com/incidents/gq1x0j8bv67v) linked above.

Since Github has marked the incident as resolved, I'll try to rerun the workflow by creating a PR that uncomments the cache steps.

**Comment by beheradibas** [comment]
I would like to fix this issue.
But prior to that if you want me to go through some documentation, I would love to.
I am new to this project and point me in the right direction keeping that in mind.

**Comment by AM1TB** [comment]
Looks like the CI builds linked to #2868 are passing along with the cache steps after uncommenting them: 
![image](https://user-images.githubusercontent.com/6761018/194856346-8c8a70e9-54db-4553-af5d-35957765607c.png)

![image](https://user-images.githubusercontent.com/6761018/194856544-ff17f1be-9305-417b-8ad0-212beb8b7e00.jpeg)

@curquiza can we pl run the CI builds again to check if the cache is being utilized as the first run logged "No cache found"
