### ISSUE TITLE
Tasks request with type `dumpCreation` is always empty

### ISSUE THREAD

**Issue by kaermorchen** [meilisearch/meilisearch#2874]
**Describe the bug**
Tasks request with type `dumpCreation` is always empty

**To Reproduce**
1. Create a dump
2. Get request `http://127.0.0.1:7700/tasks?limit=20&type=dumpCreation`
3. Check the response, it will be `{"results":[],"limit":20,"from":null,"next":null}`

**Expected behavior**
The request should contain a task with the type `dumpCreation`

**Meilisearch version:**
Checked in v0.28.0 - v0.29.0

**Additional context**
Windows 10 - WSL2 - Ubuntu 20.04.2 LTS

**Comment by oluademola** [comment]
Hello @kaermorchen 

Sorry for the inconvenience. Indeed this appears to be a bug. I was able to reproduce this on Windows 11 - WSL2 - Ubuntu 20.04.2 LTS and macOS. Thank you for bringing this to our notice. 

<img width="829" alt="Screenshot 2022-10-10 at 16 15 42" src="https://user-images.githubusercontent.com/101267639/194903805-882112d6-2381-400f-ad76-6ad469d10a67.png">


Escalating to the @meilisearch/core-team.

**Comment by curquiza** [comment]
Thanks @kaermorchen for the report and @oluademola for the support side

This is something we will fix in the next version (v0.30.0)! Thanks

**Comment by Kerollmops** [comment]
To fix this issue, I think a simple change to this function [in the tasks route](https://github.com/meilisearch/meilisearch/blob/0f024e7d97568d3763c2817cbea67008e90dfa2d/meilisearch-http/src/routes/tasks.rs#L39-L48) would make everything work as expected.

**Comment by washbin** [comment]
I have create a pr for this issue at #2890 , 

had to add one whole line. thanks @Kerollmops  :see_no_evil:
