### ISSUE TITLE
OOM error only for new indexes despite low resource consumption and even after restart.

### ISSUE THREAD

**Issue by sbleh** [meilisearch/meilisearch#2875]
**Describe the bug**
After adding around 1300 indices (sometimes 800) I get an "Out of memory (os error 12)" error for every new index I create. Resources were never even close to being exhausted. Adding documents to old indexes works without any problems. Even after restarting the container and adding a single index, I get the same error.

- I run Meilisearch as a docker image in a docker-compose stack on an EC2 t3 (ubuntu image) with unconstrained resources.
- Indexes are small (max. 40 Mb fully indexed) and max 4000 documents per index.
- Total database size at the point when OOM errors occur was around 700 Mb.
- Document attributes are constrained to a max. of 3.000.000 characters.
- Meilisearch uses less than 10 % of CPU and less than 300 Mb of Memory while indexing

Tests:
- Adding indexes was done with timeouts (1 to 20 seconds) in between and without. No difference.
- Documents were added as single updates, as one update per index, and in batches of 100. No difference.
- First added all indices then all documents, then index plus documents in order. No difference.
- Tried different values for MEILI_MAX_INDEXING_THREADS and MEILI_MAX_INDEXING_MEMORY. No difference.

**Expected behavior**
Adding more indexes is possible. An OOM error is not thrown if resources are not exhausted.

**Meilisearch version:** [e.g. v0.20.0]
v0.29.0

**Additional context**
Additional information that may be relevant to the issue.

Error screenshot
![image](https://user-images.githubusercontent.com/44573600/194759277-29eb247b-48aa-4677-81f1-3e67871358f3.png)

Thanks a lot, you're doing incredible work with Meili!

**Comment by sbleh** [comment]
Some additional observations:
- Tasks are always OOM after 1307 indexes created
- Going back to v0.28.0 does not solve the issue
- After creating 4000 indexes (1307 successful) the database uses already 63 MB storage (without any documents being added).

**Comment by curquiza** [comment]
Hello @sbleh 

Thanks for the detailed explanation.

I think unfortunately it is related to this issue: https://github.com/meilisearch/meilisearch/issues/1841. WDYT?

However, I would like to know why do you have so many indexes.

**Comment by curquiza** [comment]
> Did not see https://github.com/meilisearch/meilisearch/issues/1841. It's the same issue, feel free to merge it. Interestingly, on the Mac, it also stops at around 1300 indexes.

I will close it then 

> We're running a personalized search environment for every user, so it will become a lot more than that. The alternative is to put all data into one index. The problem is that index size then correlates with user size which sounds like a bad design choice. Is there any data on performance for using filters vs. multiple indexes? What do you think?

Maybe multi-tenancy can help you: https://docs.meilisearch.com/learn/security/tenant_tokens.html#what-is-multitenancy
All your data in the same index, but depending on the user, they can only access to their own data without accessing to the other user data.

**Comment by curquiza** [comment]
Closing this with some latency, my bad!
