### ISSUE TITLE
Idle timeout reached on the `/search` endpoint

### ISSUE THREAD

**Issue by warmwhisky** [meilisearch/meilisearch#2879]
I keep getting the following error even though cpu and memory are not at 100 percent.

```
Idle timeout reached for "http://127.0.0.1:7700/indexes/guitar_tunings_posts/search".
```

I have 73,000 documents in the index `guitar_tunings_posts`

I found this issue https://github.com/meilisearch/meilisearch-php/issues/262 however I was not able to figure out how to do the following in Laravel 

> Probably, the easiest solution would be to either update HttpClientTrait to set $options['timeout'] to INF (or null?) if ini_get('default_socket_timeout')) is negative, or to update TransportResponseTrait to ignore negative timeout values.

Do you have any ideas on a solution?

Meilisearch Search version : 0.27.1 
meilisearch-php version 0.24.2 // edit: now using 0.23.3
Laravel 9

I cannot upgrade Meilisearch to 0.28 as I am using Centos 7 which has a conflict as GLIBC cannot be installed with Centos 7 or a particular version on GLIBC cannot be installed on Centos 7

**Comment by brunoocasali** [comment]
Discussing internally with @oluademola we understand that this issue is more related to the engine than the PHP integration ;)

**Comment by warmwhisky** [comment]
@gmourier I have considered caching. Though Laravel caching is something I have never used. I thought about caching the results to html files, but I wanted to see if I could resolve the issue first before making any plans for it.

I have drastically reduced the response time by blocking a large list of bots. Now I am only getting the idle timeout every 24 hours or so.

**Comment by warmwhisky** [comment]
I can see what is causing this now. The tokenizer is creating spaces on my `#` as per the documentation
```
For Latin-based languages, there are two kinds of space separators:

Soft spaces (distance: 1): whitespaces, quotes, '-' | '_' | '\'' | ':' | '/' | '\\' | '@' | '"' | '+' | '~' | '=' | '^' | '*' | '#'
```

I'm pretty sure that this is the cause.

There are also cases where guitar players will write a guitar tuning with spaces; E A D G B E instead of EADGBE.

Am I able to bypass a soft space separator? I couldn't find anything in the docs about it. however I did find this issue https://github.com/meilisearch/MeiliSearch/issues/993#issuecomment-704167467 from 2020 which said you cannot do it :/ But maybe that's changed?

**Comment by gmourier** [comment]
Hi @warmwhisky!

Thanks for the details. That's an interesting use case. We cannot yet define the soft/hard separators, but we have a [product discussion](https://github.com/meilisearch/product/discussions/160) for that particular subject.

I would like to see your feedback on that discussion. I can copy/paste your message and ping you on it if you prefer. It also seems to be a problem for searching in docs containing code syntax.

This topic is not a priority now (until 2023 at least), and I hope it can be explored in some way or another soon.

**Comment by warmwhisky** [comment]
Thank you @gmourier

I'm pleased to have now figured out what the cause is. And hopefully look forward to 2023 for a fix.

I would appreciate you copying me into the discussion. However, all I can offer is my use case and how my results are split into single letters. 

You say it should be possible to customize the separators my end. Would I be able to do that in meilisearch/meilisearch-php vendor files or will this be in meilisearch/meilisearch ? I am using docker to install meilisearch locally, but my Centos server may be easier as I installed it from source?

**Comment by curquiza** [comment]
Hello everyone following this issue!

The discussion about a workaround and a product improvement has been done [here](https://github.com/meilisearch/product/discussions/160)

However, @meilisearch/core-team, for the next sprint, we need to investigate why we have this kind of latency with hard separator. Could help us be more stable for v1.

**Comment by curquiza** [comment]
Hello everyone here, having performance issue.
Could you test if you still have issue of performance when using [v1.2.0-rc.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.2.0-rc.0) of Meilisearch? This is the release candidate of v1.2.0 (released officially the 5th of June), and that contains a lot of performance improvement.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
