### ISSUE TITLE
Not all documents added after processing

### ISSUE THREAD

**Issue by strssdout** [meilisearch/meilisearch#2889]
**Describe the bug**
Meilisearch for some reason skips some of the documents when processing tasks in batches of 300000. All the documents i have doesn't duplicate, so i'm sure that there is problem in meilisearch

**To Reproduce**
1. Get 3.5 million documents, without duplicates (1 document have 30 fields)
2. Start adding them by batches of 300000 documents
3. Wait for all tasks finish
4. Check documents count with endpoint /indexes/{name}/stats

**Expected behavior**
All the documents added successfully.

**Meilisearch version:** [e.g. v0.20.0]
v0.29.0

**Additional context**
Linux Ubuntu 20.04, CPU 3 ghz 4 cores, RAM 8 GB, SSD.

**Comment by asypost** [comment]
I encounted the same issue.The import data count is 20048186 and the stats result says there are only 13348186.
Version: 0.29.1
OS: Windows 11

**Comment by strssdout** [comment]
Hello @oluademola 

I think yes, but i can't be sure about it :)

**Comment by asypost** [comment]
> Hello @strssdout and @asypost
> 
> If I understand you correctly this appears to be related to this #2909.

Maybe yes.

**Comment by oluademola** [comment]
Hello @strssdout and @asypost 

Can you confirm if you have the correct number of documents displayed in the [tasks object](https://docs.meilisearch.com/reference/api/tasks.html#tasks)? I want to be sure this is an issue with Meilisearch not indexing all documents and isn't related to this #2909  or a bug on the [stats route](https://docs.meilisearch.com/reference/api/stats.html#stats).

Thanks.

**Comment by strssdout** [comment]
@oluademola 

I have 11 tasks with 300000 documents and 1 task with 153489 documents, with the total number of documents of 3453489, so yes, i can confirm. But i cant be sure if its bug on the stats route or on documents indexing.

**Comment by curquiza** [comment]
Thanks @strssdout, this is indeed a bug on the `/stats` route, the source of truth is the answer in the task object.

I close this issue in favor of #2909!

Thanks everyone, for the report, and sorry for the inconvenience. The most important is all your documents are indexed at the end, if it's not, please open a new issue!
