### ISSUE TITLE
Some settings can recieve `null` as a value while they shouln't 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#2929]
**Describe the bug**
Some settings, I only have two examples but there are probably more, can receive the value `null` during an update while it should raise an error. 

Example: [See spec](https://github.com/meilisearch/specifications/blob/main/text/0117-typo-tolerance-setting-api.md#32222-errors)

> 🔴 Sending a value with a different type than Boolean for the enabled field returns an [bad_request](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#bad_request) error.
> 🔴 Sending a value with a different type than Array of String for the disableOnAttributes field returns an [bad_request](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#bad_request) error.

Upon receiving `null` as a value, they are reset to their default value

**To Reproduce**
1. Create an index
2. Update the settings `{ typoTolerance: { enabled: false }}`
3. Check if is indeed has `false` as a value
4. Update the settings `{ typoTolerance: { enabled: null }}`
3. Check the settings, enabled is now `true`

**Expected behavior**
Should follow the spec, either the spec should change or the behavior.

**Meilisearch version:** v0.29.1

**Comment by curquiza** [comment]
Thanks for the report @bidoubiwa 
Will try to fix this for v0.30.0 (during pre-release) or for v1 if too risky to fix this during a pre-release phase

**Comment by guimachiavelli** [comment]
We will probably want to clarify the behaviour when assigning `null` to settings in the docs. I took the liberty to add the `impacts-docs` myself, if that's alright.

**Comment by curquiza** [comment]
discussed with @gmourier -> the spec should be followed, not modified.

**Comment by Pranav-yadav** [comment]
@curquiza I can work on this if I know which settings are affected?
maybe a list with permalinks to all of such settings would be appreciated :)

**Comment by curquiza** [comment]
We don't know exactly which ones are concerned, this issue involves also a small investigation by testing all the settings
The list of all the settings present in Meilisearch are described in the [docs here](https://docs.meilisearch.com/reference/api/settings.html#settings)

**Comment by Pranav-yadav** [comment]
Ohh! Then, I shall come to this after tackling easier ones... hahaha

**Comment by dureuill** [comment]
Discussed with @Kerollmops, @ManyTheFish  and @gmourier:

- The current implementation behavior of resetting to the default value when sending `null` is the desired behavior, so I will send a PR so that the specification reflects the implementation behavior
- I will also check that the behavior is consistent in the implementation at any level of settings (top level, when setting eg `typoTolerance` to `null`, when setting `minWordSizeForTypos` to `null`, and also for `faceting` and `pagination`).

**Comment by curquiza** [comment]
Ok, thanks for the return @dureuill 

I close this issue then!

**Comment by curquiza** [comment]
Sorry, I reopen because investigation needed before closing, sorry!

**Comment by dureuill** [comment]
> - I will also check that the behavior is consistent in the implementation at any level of settings (top level, when setting eg typoTolerance to null, when setting minWordSizeForTypos to null, and also for faceting and pagination).

Checked the behavior. It is consistent at any level of settings, with a `null` value always resetting the value to the default.

We can close this task.
