### ISSUE TITLE
`invalid_task_type` is never raised on `GET /tasks`

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#2939]
**Describe the bug**

Sending an inexistent status returns a `bad_request` error while it should be `invalid_task_type`.

**To reproduce**

`curl 'http://127.0.0.1:7700/tasks?type=1`

```json
{
    "message": "Query deserialize error: invalid task type `1`, expecting one of: indexCreation, indexUpdate, indexDeletion, documentAdditionOrUpdate, documentDeletion, settingsUpdate, dumpCreation",
    "code": "bad_request",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#bad_request"
}
```

**Expected behavior**
[A clear and concise description of what you expected to happen.](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#invalid_task_type)

```json
{
    "message": "Task type `:type` is invalid. Available task types are: `:taskTypes`.",
    "code": "invalid_task_type",
    "type": "invalid_request",
    "link":"https://docs.meilisearch.com/errors#invalid_task_type"
}
```

**Meilisearch version:** [e.g. v0.29.1]

**Comment by shogohida** [comment]
@gmourier 
Can I work on this? I would like to tackle this with [another similar issue](https://github.com/meilisearch/meilisearch/issues/2940)

**Comment by irevoire** [comment]
Hey @shogohida, yes you can work on both issues

**Comment by shogohida** [comment]
Hi @irevoire, thanks for your comment!

I started from invalid_task_status and created [a draft pull request](https://github.com/meilisearch/meilisearch/pull/2948/files). I spent time to write code but I got stuck... 

Am I going to a right direction? In any case, I got stuck so please give me some advice after checking my implementation. I really appreciate your support 🙏

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3023
