### ISSUE TITLE
Add missing events as telemetry

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2955]
Following: https://github.com/meilisearch/specifications/pull/186/files

This issue is about adding the missing telemetry information to Meilisearch

[Reminder](https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html#what-tools-do-we-use-to-collect-and-visualize-data):

> We collect telemetry data for only two reasons: so that we can improve our product, and so that we can continue working on this project full-time.
>
> In order to create a better product, we need reliable quantitative information. The data we collect helps us fix bugs, evaluate the success of features, and better understand our users' needs.
>
> We also need to prove that people are actually using Meilisearch. Usage metrics help us justify our existence to investors so that we can keep this project alive.
[#](https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html#why-should-you-trust-us)

## Impacted teams

@meilisearch/docs-team

**Comment by curquiza** [comment]
Is this issue finished @irevoire? Can we close it thanks to #3059 #3060 #3049 #3063 #3065?

**Comment by irevoire** [comment]
Ah yes! I thought the last one would auto-close it once merged, but it looks like once again, the voix of github are waterproof

Thanks for noticing!

**Comment by curquiza** [comment]
Lord GitHub only closes an issue when you merge a PR into `main` 👁️
