### ISSUE TITLE
Improve error message for config file

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2959]
Following https://github.com/meilisearch/specifications/pull/185/files#r1000423262

We need to update the error message:

```
Error: `config_file_path` is not supported in config file
```

should be 

```
Error: `config_file_path` is not supported in the configuration file
```

**Comment by DarioCostaAlves** [comment]
Can I ? Thanks

**Comment by curquiza** [comment]
Hello @DarioCostaAlves 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
