### ISSUE TITLE
Inconsistent behavior with other routes regarding `indexes` access when I'm trying to swap indexes I do not have access to

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#2975]
**Describe the bug**

When I use an API key that doesn't have access to an index I specify in a swap operation, I get a synchronous `index_not_found` error, whereas, in this type of case on other routes, it is an `invalid_api_key` error that is returned.

e.g. Trying to access `GET /indexes/B` while the API Key does not have access to it does not return an `index_not_found` but an `invalid_api_key` error instead.

I think we went a bit too fast in our error definition. For consistency, I think we should adopt the same behavior. 

**We could consider changing that later.**

**To Reproduce**

1. Create an API Key having the `action` `indexes.swap` and being able to access one of the two indexes to be swapped `["indexes": ["A"]`.

```json
{
            "name": "swap-key",
            "description": "Swap indexes",
            "key": "7193ddd98d380cb636a6c74674e8011885bbeef02c052ffac55f95816231d9ad",
            "uid": "f23127e0-4e4c-4968-b214-d2e397c59d76",
            "actions": [
                "indexes.swap"
            ],
            "indexes": [
                "A"
            ],
            "expiresAt": null,
            "createdAt": "2022-10-26T10:41:55.926719759Z",
            "updatedAt": "2022-10-26T10:41:55.926719759Z"
        }
```

2. Try to swap `A` and `B` using that API Key.
3. See the error response

```json
{
    "message": "Index `B` not found.",
    "code": "index_not_found",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#index_not_found"
}
```

**Expected behavior**

In this case, I would expect to receive an `invalid_api_key` error, as with the other routes.

```json
{
    "message": "The provided API key is invalid.",
    "code": "invalid_api_key",
    "type": "auth",
    "link": "https://docs.meilisearch.com/errors#invalid_api_key"
}
```

**Meilisearch version:** `v0.30.0-new-index-scheduler.beta.1`

**Comment by curquiza** [comment]
Fixed by #2763
