### ISSUE TITLE
Extract the dates ouf of the dumpv2

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2989]
When importing a dump v2, we should extract the creation and last updated timestamp.
https://github.com/meilisearch/meilisearch/blob/main/dump/src/reader/v2/mod.rs#L145-L164

The idea is to look at the whole task queue until you find the first task concerning your index (=last_updated_at), and you already have the task_uid of the task_creating it. Thus you then need to continue until you reach this task and extract its date as the creation_date.

**Comment by curquiza** [comment]
Thank you very much @vivek-26 for your involvement in this project!

@irevoire will review your PR when he will have some time 😊
