### ISSUE TITLE
Create a tokenizer

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#3]
...that can be based on the [Michael Nitschinger's blog post about tokenization](http://nitschinger.at/Text-Analysis-in-Rust-Tokenization/) in Rust.

**Comment by djKooks** [comment]
@Kerollmops seems this has been implemented...isn't it?

**Comment by Kerollmops** [comment]
Hey @djKooks,

There actually is a tokenizer in the engine but that is not a good one, for example it doesn't support CJK langage well, I would also like to make it be like [the one from tantivy](https://docs.rs/tantivy/0.12.0/tantivy/tokenizer/trait.Tokenizer.html), and potentially be able to give it dynamically at run time, but that's another subject.

**Comment by djKooks** [comment]
@Kerollmops well, it seems not 'good first issue'(this would be big mission), but interesting.

Is there some features you are planning(or willing) to apply for this feature, or is there a roadmap?
It will be helpful to contributor to work on 😆 .

**Comment by djKooks** [comment]
@Kerollmops seems it is duplication with #275 ...how do you think?

**Comment by Kerollmops** [comment]
Hey @djKooks, sorry for the late response.

Yeah, it is kind of a related to the same feature but #275 is more related to the features I would like to see supported by the tokenizer, and #3 is more a guide to implement it. We will clean-up those when times comes.

Thank you again for your involvement!

**Comment by erlend-sh** [comment]
It seems this has been superseded by https://github.com/meilisearch/MeiliSearch/issues/624 and is therefore an occupied task already, yes?

**Comment by MarinPostma** [comment]
@erlend-sh  yes sir!

closed in favor of #624
