### ISSUE TITLE
Filtering by value of "inf" or "infinity" yields an internal error

### ISSUE THREAD

**Issue by Martinusius** [meilisearch/meilisearch#3000]
When Filtering by comparing the value of an attribute to the values "inf" or "infinity" an internal error is caused. I randomly stumbled upon this when I was using the value "inf" in one of my attributes. I assume it is caused by some number conversion function which thinks "inf" or "infinity" should be a number representing infinity instead of the actual string.

**Steps to reproduce**
1. Create a new index with some filterable attributes
2. Add one or more documents to the index
3. Make a search request with a filter which compares an attribute's value to the values "inf" or "infinity"
4. Get internal error as a response

**Expected behavior**
Comparing values to "inf" or "infinity" should not cause an internal error. Also, it should be possible to compare these values as strings instead of numbers. This could be specified by putting "inf" inside quotes (similar to strings containing space). Right now putting the value in quotes does not change the outcome and an internal error is still produced.

**Screenshots**
![image](https://user-images.githubusercontent.com/46503828/198832439-dc0a1a8e-4009-4b55-84be-ba552334f919.png)
(The 400 Bad Request is not coming from the Meilisearch API, only the JSON is)

**Meilisearch version:** 
I tested the bug on both the stable 0.28.1 version and the new pagination beta version 0.30.0-pagination-beta.4

----
EDIT by @curquiza 

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/) ->https://github.com/meilisearch/milli/pull/689
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by curquiza** [comment]
Closed by #3036
