### ISSUE TITLE
When both `lat` and `lng` are missing it doesn't return the right error

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3005]
When both are missing, we must return an error telling us both fields are missing. Right now, it returns only one error for each, the `lng` is missing, or the `lat` is missing. [This specific function](https://github.com/meilisearch/milli/blob/365f44c39b2b2fe47b04c30aa7bca6e1669a2141/milli/src/update/index_documents/enrich.rs#L342-L363) should catch this but, instead isn't returned to the user.

**Comment by zafar-hussain** [comment]
Hi, @Kerollmops,
I am confirming before making a commit, 

I reckon, (None, None) should be checked before (None, Some(_))  and  (Some(_), None).
Hence, the (None, None) error checking should be brought up (see code below)

cheers


pub fn validate_geo_from_json(id: &DocumentId, bytes: &[u8]) -> Result<StdResult<(), GeoError>> {
......
            (None, None) => Ok(Err(MissingLatitudeAndLongitude { document_id: debug_id() })),
            (None, Some(_)) => Ok(Err(MissingLatitude { document_id: debug_id() })),
            (Some(_), None) => Ok(Err(MissingLongitude { document_id: debug_id() })),
            //(None, None) => Ok(Err(MissingLatitudeAndLongitude { document_id: debug_id() })), this line moved up 
        },
        value => Ok(Err(NotAnObject { document_id: debug_id(), value })),
    }
}

**Comment by Kerollmops** [comment]
Hey @zafar-hussain,

The order of the match is not important with these matches as they are explicit; the code will not enter the first branch if it doesn't match the condition. I would prefer that you reproduce the bug and follow the code path to debug it.

 - [Change the settings to trigger the geo feature on the engine](https://docs.meilisearch.com/learn/getting_started/filtering_and_sorting.html#geosearch).
 - Send documents to index that is missing the `lat` or `lng` key under the `_geo` field.
 - Look at [the error message returned in the tasks route](https://docs.meilisearch.com/reference/api/tasks.html#tasks).

**Comment by irevoire** [comment]
Fixed by https://github.com/meilisearch/milli/pull/763

**Comment by curquiza** [comment]
@irevoire we prefer not closing the issue until it's not fixed on the Meilisearch side
If it's already fixed on the meilisearch side, please link the PR that imports the new version of Milli containing the fix 😄

**Comment by irevoire** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3395
