### ISSUE TITLE
Bad latitude / Bad longitude should share a common message between the invalid sort and invalid filter 

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3006]
**Describe the bug**

- `filter`: `Bad latitude `1000`. Latitude must be contained between -90 and 90 degrees.`
- `sort`: `Latitude must be contained between -90 and 90 degrees.`

We should throw the same error in both case (the one from the filter) => Fixed by #3479

This changes should be done in milli folder.

More information about the expectations
- [ ] If I try to filter on `_geo(x, y, z)` we should trigger the special reserved keywords error 
- [ ] If I try to filter on `_geoDistance(x, y, z)` we should trigger the special reserved keywords error 
- [x] If I try to sort on `_geoRadius(x, y)` we should trigger the special reserved keywords error. Fixed by #3479
- [x] If I try to sort on `_geo(x, y)` we should trigger the special reserved keywords error. Fixed by https://github.com/meilisearch/meilisearch/pull/3631
- [x] If I try to sort on `_geoDistance(x, y)` we should trigger the special reserved keywords error. Fixed by https://github.com/meilisearch/meilisearch/pull/3631

**Comment by gentcys** [comment]
Hi @irevoire 
I'd like to work on this, could you guide me what should I do to this issue?

**Comment by maryamsulemani97** [comment]
Hi @irevoire!

Is this message for an existing error code or a new one?

**Comment by curquiza** [comment]
Hello @maryamsulemani97 
This is issue is related to a bug fix, it does not impact the docs team 😊 

Hello @gentcys 
I let @irevoire answer to your question, thanks for being involved in this issue 😊

**Comment by Azanul** [comment]
Should I fix it or is someone else working on it?

**Comment by curquiza** [comment]
Hello @Azanul 
You can indeed do it, looks like no one is working on it right now 😄 
thanks in advance for your contribution.

**Comment by curquiza** [comment]
For your information, I've just added some information regarding the expectation in the issue description 😇

**Comment by Azanul** [comment]
Does "the special reserved keywords error" here mean `is a reserved keyword and thus can't be used as a filter expression. Use the _geoRadius(latitude, longitude, distance) built-in rule to filter on _geo field coordinates.` ?

**Comment by irevoire** [comment]
Hey @Azanul, sorry for the delay :pray: 

« The special reserved keywords error » can be either;
- `_geoRadius` is a reserved keyword and thus can't be used as a sort expression. Use the _geoPoint(latitude, longitude) built-in rule to sort on _geo field coordinates.
  **When used in a sort**
- `_geoPoint` is a reserved keyword and thus can't be used as a filter expression. Use the `_geoRadius(latitude, longitude, distance), or _geoBoundingBox([latitude, longitude], [latitude, longitude]) built-in rules to filter on `_geo` coordinates.
  **When used in a filter**
- `_geoDistance` is a reserved keyword and thus can't be used as a ranking rule
  **When used in a ranking rule**

**Comment by curquiza** [comment]
@irevoire is this issue solved thanks to #3638?
