### ISSUE TITLE
Flaky test CI is failing

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3009]
Flaky test CI is stuck and then failing because too long.

We need to investigate why it's failing, fix the bug related to it (if there is any) or fix the CI (if the CI is the issue)

See: https://github.com/meilisearch/meilisearch/actions/runs/3345273974/jobs/5569620230

**Comment by curquiza** [comment]
After discussion with @irevoire, it looks like it's not a production bug (a bug in Meilisearch) but a bug in the CI

**Comment by irevoire** [comment]
The test may be in production, actually; see this PR to understand why I thought only the tests were impacted + why I was wrong: https://github.com/meilisearch/meilisearch/pull/3010

**Comment by dureuill** [comment]
I'm not working on this currently, unassigning myself

**Comment by curquiza** [comment]
Flaky CI is working on `release-v0.30.0` again, see https://github.com/meilisearch/meilisearch/actions/runs/3490276353

Meaning once we release v0.30.0 and bring the change from `release-v0.30.0` to `main`, the scheduled CI will work again.

Closing this issue.
