### ISSUE TITLE
v0.30.0 canceledBy filter not implemented on GET /tasks route 

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#3026]
**Describe the bug**
I recieve the following error on GET /tasks when using `canceledBy` as a filter query parameter

> Query deserialize error: unknown field canceledBy
> Meili logs [2022-11-03T13:55:15Z INFO  actix_web::middleware::logger] 127.0.0.1 “GET /tasks?canceledBy=12777 HTTP/1.1” 400 168 “-” “node-fetch/1.0 (+https://github.com/bitinn/node-fetch)” 0.000061

It's based on this doc https://bump.sh/doc/meilisearch/changes/a4fc0eb4-f0ea-4b20-bcdf-d4265ac98069#operation-tasks-list-canceledby (edited) 

**To Reproduce**
1. make a request on `GET /tasks` with `canceledBy` as a filter parameter
2. Error is thrown

**Expected behavior**
Should be a valid filter as per the spec

**Meilisearch version:** v0.30.0

**Comment by curquiza** [comment]
Thanks charlotte for the report, will be fixed for v0.30.0 🙏

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3023
