### ISSUE TITLE
Improve the way we receive the documents payload

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3037]
We currently use the above-linked method to receive the documents payload sent by the users. This function stores everything into memory, this is not optimal, we could probably do much better and stream that to disk at least with [a `BufWriter` or equivalent](https://doc.rust-lang.org/std/io/struct.BufWriter.html).

https://github.com/meilisearch/meilisearch/blob/9e189f5041fad0312fc0aa94038a890ad922e92c/meilisearch-http/src/routes/indexes/documents.rs#L197-L293

**Comment by jiangbo212** [comment]
BufWritter I've looked at the documentation. There doesn't seem to be a suitable way to deserialize the playload stream directly by serde. I tried writing the playload to a temporary file via BufWritter and then serialising the json to an array of Objects by means of a memory map. The contents of the file do not go directly into memory during this process. On my machine indexing a 500+M file would have directly run out of memory and caused the machine to reboot. After the update, the same 500M+ file is indexed and this time it is working fine.
```rust
pub fn read_json_buffer(path: &str, writer: impl Write + Seek) -> Result<usize> {
    let mut builder = DocumentsBatchBuilder::new(writer);
    let file = File::open(path).unwrap();
    let mmap = unsafe { MmapOptions::new().map(&file).unwrap()};
    let mut deserializer = serde_json::Deserializer::from_slice(&mmap);

    for_each(&mut deserializer, |obj: Object | {
        builder
            .append_json_object(&obj)
            .map_err(Into::into)
            .map_err(DocumentFormatError::Internal)
            .unwrap();
    }).unwrap();

    let count = builder.documents_count();
    let _ = builder.into_inner().map_err(Into::into).map_err(DocumentFormatError::Internal)?;

    Ok(count as usize)
}
```

``` rust
/**
 * References
 * https://github.com/serde-rs/json/issues/160
 * https://serde.rs/stream-array.html 
 */
fn for_each<'de, D, T, F>(deserializer: D, f: F) -> std::result::Result<(), D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
    F: FnMut(T),
{
    struct SeqVisitor<T, F>(F, PhantomData<T>);

    impl<'de, T, F> Visitor<'de> for SeqVisitor<T, F>
    where
        T: Deserialize<'de>,
        F: FnMut(T),
    {
        type Value = ();

        fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
            formatter.write_str("a nonempty sequence")
        }

        fn visit_seq<A>(mut self, mut seq: A) -> std::result::Result<(), A::Error>
        where
            A: SeqAccess<'de>,
        {
            while let Some(value) = seq.next_element::<T>()? {
                self.0(value)
            }
            Ok(())
        }
    }
    let visitor = SeqVisitor(f, PhantomData);
    deserializer.deserialize_seq(visitor)
}
```

Here is another question, if the parameter "http_payload_size_limit" can be set arbitrarily by the user, then for a very large indexed file, e.g. 1GB, 10GB. is the current way of indexing directly via the http interface appropriate. The current interface in this case above, the bottleneck is not really in the indexing process of meilisearch, but in the process of accepting the file. Is it possible to consider separating the process of accepting indexed files from the actual indexing process. Uploading the index file is a separate interface, and at this point the uploaded index file could even be in a compressed format, while the interface for indexing only needs to accept the path to the index file and other indexing parameters.

**Comment by Kerollmops** [comment]
Hey @jiangbo212,

What you found looks interresting, storing the content into a temporary file and reading it using `serde_json` seems good to me. Would it be possible for you to open a PR? This way we will be able to test your changes and run the tests.

About the `http-payload-size` parameter, it should indicate the maximum size of a body in an HTTP request but I'm not sure if we must take the compression into account. Does it make any sense to measure it compressed or uncompressed?

**Comment by jiangbo212** [comment]
@Kerollmops  I will submit a PR within a week.

About compression. I think the biggest benefit is to reduce network traffic, so let's try to consider such a scenario. Now I use "post /indexes/{index_uid}/documents" to index a 10G json file to the meilisearch cloud service, and with the current api there will be 10G of traffic flowing from the public network to the meilisearch service. After a simple zip compression, we can almost compress the source file to 1/4 of its size, which is about 2.5G. Then the traffic from the public network to meilisearch is also compressed to about 2.5G. Also for "post /indexes/{index_uid}/documents", the efficiency will be improved, a large part of the api's time is actually spent on accepting json files.

Of course, for general "add documents", the current api is already very suitable.
