### ISSUE TITLE
Thread panicked in incremental facets

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3042]
**Describe the bug**
This error was thrown while indexing documents.
The logs:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /usr/local/cargo/git/checkouts/milli-00376cd5db949a15/c3b75bb/milli/src/update/facet/incremental.rs:151:50
```

The task:
```json
{
  "uid": 1338,
  "indexUid": "acs1_stat",
  "status": "failed",
  "type": "documentAdditionOrUpdate",
  "canceledBy": null,
  "details": {
    "receivedDocuments": 51
  },
  "error": {
    "message": "An unexpected crash occurred when processing the task.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
  },
  "duration": "PT0.085355044S",
  "enqueuedAt": "2022-11-12T17:57:01.317844693Z",
  "startedAt": "2022-11-12T17:57:02.448542286Z",
  "finishedAt": "2022-11-12T17:57:02.53389733Z"
}
```

**To Reproduce**
Steps to reproduce the behaviour:
I don't really know, it's @ryanrussell that found it.
He said:
> This is happening when a filterable field is None or "" from python-land.

And

> With some larger sample size, this is also happening randomly on over-writing id's when the filterableAttributes have valid values.

**Expected behavior**
It works or throws a clean error.

**Meilisearch version:** v0.30rc1

**Additional context**
@ryanrussell, if you have any other information, please comment below!
And thanks a lot for your bug report!

---

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/)
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `release-v0.30.0`

**Comment by loiclec** [comment]
Hi @ryanrussell ,

Thanks a lot for finding and investigating this bug. It helped a lot. I think I found the source of the issue and a fix _should_ be released for it in the next release candidate :)

**Comment by curquiza** [comment]
reopening since it's still not fixed on Meilisearch side

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3084
