### ISSUE TITLE
v0.30.0rc1 error code on cancel tasks not updated with new filters naming

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#3045]
**Describe the bug**
Between v0.30.0rc0 and v0.30.0rc1 some naming of filters were changed. For example `uid` to `uids`, `status` to `statuses`

Nonetheless, when providing `no` query parameters the error raised still has the old 

> Error: Meilisearch(MeilisearchError { error_message: "Query parameters to filter the tasks to cancel are missing. Available query parameters are: `uid`, `indexUid`, `status`, `type`.", error_code: MissingTaskFilters, error_type: InvalidRequest, error_link: "https://docs.meilisearch.com/errors#missing_task_filters" })

**To Reproduce**
1. `POST /tasks/cancel` without query parameters
2. Error raised is outdated

**Expected behavior**
The error should specify the correct queru parameters name. Also, 

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3049
