### ISSUE TITLE
Task future details fields are not displayed at `null` when the task status is enqueued

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#3057]
**Describe the bug**

Note: I did not test the other task types in their enqueued state.

```json
{
            "uid": 0,
            "indexUid": "mtg",
            "status": "enqueued",
            "type": "documentAdditionOrUpdate",
            "canceledBy": null,
            "details": {
                "receivedDocuments": 76116,
                <- "indexedDocuments" should be displayed to null here
            },
            "error": null,
            "duration": "PT12.028011S",
            ...
 }
```

**Expected behavior**

https://github.com/meilisearch/specifications/blob/198d6a41eb2bcd2defb17f8e3520892cdfef113f/text/0060-tasks-api.md#4-details-field-object
https://github.com/meilisearch/specifications/blob/70c4b4bb3eeea048835be6b3f339dfb31c8e3203/text/0060-tasks-api.md#taskdeletion

**Meilisearch version:** `v0.30.0RC1`

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3067
