### ISSUE TITLE
Tasks "future" details fields are not displayed to `0` when the task reach a finished state `canceled`

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#3058]
**Describe the bug**

Note: I did not test the other task types being canceled.

```json
{
            "uid": 0,
            "indexUid": "mtg",
            "status": "canceled",
            "type": "documentAdditionOrUpdate",
            "canceledBy": 1,
            "details": {
                "receivedDocuments": 76116,
                <- "indexedDocuments": 0 should be displayed here
            },
            "error": null,
            "duration": "PT12.028011S",
            ...
 }
```

**Expected behavior**

I expect to have `indexedDocuments` field to be shown with a `0` value if the task has been canceled. 
It should be the case for every "future" details field that are displayed at `null` when the task is enqueued.

See https://github.com/meilisearch/meilisearch/issues/3057

In the case of a `dumpCreation` it should stay `null`

**Meilisearch version:** `0.30.0RC1`

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3067
