### ISSUE TITLE
Contents of directory pointed to by `--db-path` is lost if the database cannot be read

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3069]
**Describe the bug**
When a `VERSION` file exists in the `--db-path` directory, but for any reason, the database cannot be read (could be a spurious IO error), the current behavior of `meilisearch` is to silently remove the entire contents of that directory and replace it with a fresh database.

**To Reproduce**
1. Create a fresh db: `meilisearch -- --db-path tmp-db.ms`
2. Add something to the db: 
   ```bash
   curl \
       -X POST 'http://localhost:7700/indexes' \
       -H 'Content-Type: application/json' \
       --data-binary '{
           "uid": "movies",
           "primaryKey": "id"
       }'
   ```
3. Check it is there:
   ```
   curl -X GET 'http://localhost:7700/indexes'
   ```
    returns:
   ```
   {"results":  [{"uid":"movies","createdAt":"2022-11-16T13:44:58.985399Z","updatedAt":"2022-11-16T13:44:58.988185Z","primaryKey":"id"}],"offset":0,"limit":20,"total":1}
   ```
4. Stop meilisearch, then simulate IO errors: `chmod -r tmp-db.ms/tasks/data.mdb`
5. Restart meilisearch on the DB, in this instance, it exits with an error: `Error: Permission denied (os error 13)`
6. Restart meilisearch again, this time it restarts although we didn't `chmod +r`
7. `curl -X GET 'http://localhost:7700/indexes'` returns `{"results":[],"offset":0,"limit":20,"total":0}`

**Expected behavior**
- The returned error indicates that the database cannot be read
- The database is not removed

**Meilisearch version:** v0.30.0-rc1

**Additional context**
Encountered in a less contrived case of having mistakenly opened a database created with a different (future) version of lmdb, resulting in the loss of that database.

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3077
