### ISSUE TITLE
Rename `meilisearch-http`

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3073]
Once the pre-release is over, and the change has been ported back into the `main` branch, we should rename the `meilisearch-http` module into `meilisearch`.

**Comment by colbsmcdolbs** [comment]
@irevoire Hello! I am wanting to begin contributing to this repository, and thought this issue might be a good one to begin getting accustomed to the codebase. If anything further needs to be done, or if this needs to be rebased before it can be merged later, I would be happy to help. Thanks!
