### ISSUE TITLE
IN array not working

### ISSUE THREAD

**Issue by adgower** [meilisearch/meilisearch#3075]
**Describe the bug**
When I create custom string filter "IN" array doesn't work

**To Reproduce**
```
App\Models\User::search(
  '',
  function(Indexes $meiliSearch, string $query, array$options) {
    $options['filter'] = 'id IN [1001]';
    return $meiliSearch->search('', $options);
  }
)->get();
```
Output:
```
MeiliSearch\Exceptions\ApiException with message 'Was expecting an operation `=`, `!=`, `>=`, `>`, `<=`, `<`, `TO` or `_geoRadius` at `id IN [1001]`.
1:13 id IN [1001]'
```

**Expected behavior**
I expected the only results to show options in the array of ids.

**Meilisearch version:** [e.g. v0.28.1]

**Additional context**
This works, but not ideal:
```
$ids = [1001,1];

// append 'id = ' to each id
$ids = array_map(function($id) {
    return 'id = ' . $id;
}, $ids);

// join the array with ' OR '
$ids = implode(' OR ', $ids);

App\Models\User::search(
  '',
  function(Indexes $meiliSearch, string $query, array$options)  use ($ids) {
    $options['filter'] = $ids;
    return $meiliSearch->search('', $options);
  }
)->get();
```

**Comment by oluademola** [comment]
Hello @adgower,

What version of Meilisearch are you using? The `IN` operator was introduced with [v0.29.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.0). I believe updating to the latest version should resolve this issue.

Thanks.

**Comment by ThisIsMyFavouriteJar** [comment]
Same issue, exact same error message, and I am running Meili 0.29.2
This only seems to occur when using IN [], NOT IN[] works fine though!

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
