### ISSUE TITLE
Rename `originalFilters` into `originalFilter`

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3079]
Both cancelation and deletion tasks have the `originalFilters` field in their task details when calling `GET /tasks`.

This field must be renamed into `originalFilter` as a sack of consistency [with the `filter` field in the search route](https://docs.meilisearch.com/learn/getting_started/filtering_and_sorting.html#filtering).

 - [ ] Update [the cancelation spec](https://github.com/meilisearch/specifications/pull/195).
 - [ ] Update [the deletion spec](https://github.com/meilisearch/specifications/pull/198).
 - [ ]  Update Meilisearch.

**Comment by curquiza** [comment]
@meilisearch/integration-team @meilisearch/docs-team 
Sorry for the last minute change. See more information [here](https://meilisearch.slack.com/archives/C044GEXNEUC/p1668687911768989) (internal link)
