### ISSUE TITLE
`cargo test` fails out-of-the-box

### ISSUE THREAD

**Issue by amab8901** [meilisearch/meilisearch#3088]
Problem:
`cargo test` fails directly out-of-the-box, in the latest version of main branch. 

Expectation:
`cargo test` should pass the tests in the latest version of main branch

Steps to reproduce:
1. pull latest meilisearch version from main branch
2. `cargo test`
3. see failed test results

<details>
<summary>$ cargo test</summary>

```
    Finished test [unoptimized + debuginfo] target(s) in 0.20s
     Running unittests src/lib.rs (target/debug/deps/dump-634a39b32658b2a5)

running 14 tests
test reader::compat::v2_to_v3::test::compat_v2_v3 ... ignored
test reader::compat::v3_to_v4::test::compat_v3_v4 ... ignored
test reader::compat::v4_to_v5::test::compat_v4_v5 ... ignored
test reader::compat::v5_to_v6::test::compat_v5_v6 ... ignored
test reader::test::import_dump_v2 ... ignored
test reader::test::import_dump_v3 ... ignored
test reader::test::import_dump_v4 ... ignored
test reader::test::import_dump_v5 ... ignored
test reader::v2::test::read_dump_v2 ... ignored
test reader::v3::test::read_dump_v3 ... ignored
test reader::v4::test::read_dump_v4 ... ignored
test reader::v5::test::read_dump_v5 ... ignored
test test::test_creating_and_read_dump ... ignored
test writer::test::test_creating_dump ... ignored

test result: ok. 0 passed; 0 failed; 14 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/file_store-fb3e922109d98ab4)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/index_scheduler-2ffede9a59e5f983)

running 44 tests
test autobatcher::tests::clear_and_additions ... ok
test autobatcher::tests::allowed_and_disallowed_index_creation ... ok
test autobatcher::tests::clear_and_additions_and_settings ... ok
test autobatcher::tests::autobatch_simple_operation_together ... ok
test autobatcher::tests::document_addition_batch_with_settings ... ok
test autobatcher::tests::simple_document_operation_dont_autobatch_with_other ... ok
test autobatcher::tests::anything_and_index_deletion ... ok
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/cancel_mix_of_tasks/first_task_processed.snap.new
test tests::cancel_enqueued_task ... ok
test tests::cancel_mix_of_tasks ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/cancel_succeeded_task/initial_task_processed.snap.new
test tests::cancel_succeeded_task ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/document_addition/3.snap.new
test tests::document_addition ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/document_addition_and_index_deletion/2.snap.new
test tests::document_addition_and_index_deletion ... FAILED
test tests::document_addition_and_index_deletion_on_unexisting_index ... ok
test tests::fail_in_process_batch_for_document_addition ... ok
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/do_not_batch_task_of_different_indexes/all_tasks_processed.snap.new
test tests::do_not_batch_task_of_different_indexes ... FAILED
test tests::fail_in_process_batch_for_index_creation ... ok
test tests::insert_task_while_another_task_is_processing ... ok
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/fail_in_update_task_after_process_batch_success_for_document_addition/second_iteration.snap.new
test tests::fail_in_update_task_after_process_batch_success_for_document_addition ... FAILED
test tests::panic_in_process_batch_for_index_creation ... ok
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/process_tasks_inserted_without_new_signal/all_tasks_processed.snap.new
test tests::process_tasks_inserted_without_new_signal ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/process_tasks_without_autobatching/all_tasks_processed.snap.new
test tests::process_tasks_without_autobatching ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/query_tasks_from_and_limit/finished.snap.new
test tests::query_tasks_from_and_limit ... FAILED
test tests::query_tasks_simple ... FAILED
test tests::query_tasks_special_rules ... ok
test tests::register ... ok
test tests::simple_new ... ok
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/swap_indexes/initial_tasks_processed.snap.new
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/swap_indexes_errors/initial_tasks_processed.snap.new
test tests::swap_indexes ... FAILED
test tests::swap_indexes_errors ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/task_deletion_delete_same_task_twice/initial_tasks_processed.snap.new
test tests::task_deletion_delete_same_task_twice ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/task_deletion_deleteable/initial_tasks_processed.snap.new
test tests::task_deletion_deleteable ... FAILED
test tests::task_deletion_undeleteable ... ok
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_addition_cant_create_index_with_index/1.snap.new
test tests::test_document_addition_cant_create_index_with_index ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_addition_cant_create_index_with_index_without_autobatching/1.snap.new
test tests::test_document_addition_cant_create_index_with_index_without_autobatching ... FAILED
test tests::test_document_addition_cant_create_index_without_index ... ok
test tests::test_document_addition_cant_create_index_without_index_without_autobatching ... ok
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_addition_mixed_right_without_index_starts_with_cant_create/3.snap.new
test tests::test_document_addition_mixed_right_without_index_starts_with_cant_create ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_addition_mixed_rights_with_index/1.snap.new
test tests::test_document_addition_mixed_rights_with_index ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_replace_without_autobatching/2.snap.new
test tests::test_document_replace_without_autobatching ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_replace/2.snap.new
test tests::test_document_replace ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_update_without_autobatching/2.snap.new
test tests::test_document_update_without_autobatching ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_document_update/2.snap.new
test tests::test_document_update ... FAILED
stored new snapshot /home/amab/src/meilisearch/index-scheduler/src/snapshots/lib.rs/test_mixed_document_addition/2.snap.new
test tests::test_mixed_document_addition ... FAILED
test tests::fail_in_create_batch_for_index_creation ... ok
```

</details>

<details>
<summary>$ lscpu</summary>

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
    CPU family:          6
    Model:               126
    Thread(s) per core:  2
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            5
    CPU(s) scaling MHz:  48%
    CPU max MHz:         3400,0000
    CPU min MHz:         400,0000
    BogoMIPS:            2380,80
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology 
                         nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_l
                         m abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx 
                         smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku
                          ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   96 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    1 MiB (2 instances)
  L3:                    4 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Mitigation; Clear CPU buffers; SMT vulnerable
  Retbleed:              Mitigation; Enhanced IBRS
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
  Srbds:                 Mitigation; Microcode
  Tsx async abort:       Not affected

</details>

OS: Archlinux (Garuda Linux)

This is a follow-up on issue https://github.com/meilisearch/meilisearch/issues/3017 which made some progress on getting `cargo test` to work, but hasn't completed that goal all the way.

**Comment by amab8901** [comment]
I realize there are 2 tasks left on the same problem described in previous issue (https://github.com/meilisearch/meilisearch/issues/3017)

**Comment by amab8901** [comment]
actually, those 2 tasks were finished but weren't marked as such at the time of my previous comment.

**Comment by curquiza** [comment]
Hello @amab8901 
Sorry for the late answer. Do you think it could be related to the issue we just opened here: https://github.com/meilisearch/meilisearch/issues/3133?

**Comment by irevoire** [comment]
Hey, I think I actually know exactly what's happening.
This person is using archlinux and thus is encountering the same problem I have.
It's been fixed in this PR: https://github.com/meilisearch/meilisearch/pull/3084.
But we merged it on `release-v0.30.0` thus, we need to wait until we bring back release-v0.30.0 into main to fix the main branch.

And as you said in https://github.com/meilisearch/meilisearch/issues/3017.
> [v0.30.0rc2](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.0rc2) is now out containing this fix

**Comment by amab8901** [comment]
when will the `release-v0.30.0` be in main?

**Comment by curquiza** [comment]
On Monday 😇
