### ISSUE TITLE
Ignore diacritics

### ISSUE THREAD

**Issue by ovari** [meilisearch/meilisearch#3092]
**Describe the bug**

Please ignore `diacritics` when searching, so [vidéö](https://beta.flathub.org/hu/apps/search/vid%C3%A9%C3%B6) will show the same results as [video](https://beta.flathub.org/hu/apps/search/video) and [viDeO](https://beta.flathub.org/hu/apps/search/viDeO).

**To Reproduce**
1. https://github.com/flathub/website/issues/611#issuecomment-1320950891
2. For some diacritics, please see https://zombiekeys.quickfolders.org/

**Expected behavior**
Ignore `diacritics`

**Screenshots**
Please advise if you would like screenshots to the above searches at [Flathub](https://beta.flathub.org/hu/)

**Meilisearch version:** [e.g. v0.20.0]

Sorry, unsure, whatever https://beta.flathub.org/ is using.

Thank you

**Comment by ManyTheFish** [comment]
Hello @ovari,
Yes you're right, Meilisearch doesn't remove nonspacing marks so far.
However, this will be fixed in V1.0 which will be released in Q1 2023.

Thank you for your report!

**Comment by ovari** [comment]
1. Will entering `o` or `O` find `o`, `O`, `ó`, `Ó`, `ö`, `Ö`, `ő`, `Ő` (the last 2 characters are only available in Unicode, not ASCII)?
2. Will entering `u` or `U` find `u`, `U`, `ú`, `Ú`, `ü`, `Ü`, `ű`, `Ű` (the last 2 characters are only available in Unicode, not ASCII)?
3. Will entering `ű` be converted to `u` before searching too?

Thank you

**Comment by ManyTheFish** [comment]
> 1. Will entering o or O find o, O, ó, Ó, ö, Ö, ő, Ő (the last 2 characters are only available in Unicode, not ASCII)?
> 2. Will entering u or U find u, U, ú, Ú, ü, Ü, ű, Ű (the last 2 characters are only available in Unicode, not ASCII)?

Yes! I put below the complete table on the ignored characters:
https://www.compart.com/en/unicode/category/Mn

> 3. Will entering ű be converted to u before searching too?

Yes, and it is, somehow, a lake of relevancy from Meilisearch, but it's harder to fix unfortunately.

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3269
Already released in [v1.0.0-rc.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0-rc.0), will be released officially in v1.0.0
