### ISSUE TITLE
Error links hash is formatted incorrectly

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/meilisearch#3097]
**Describe the bug**
When a user gets an error, as part of the error object Meilisearch returns a link to the docs (e.g. `"link": "https://docs.meilisearch.com/errors#index_not_found"`). The problem is that the hash does not take the user to the correct section of the errors page. This is because VuePress's slugification changes `_` to `-`.

(Actually, the hash is formatted correctly, and it's VuePress that works strangely.)

**To Reproduce**
1. Open Meilisearch and cause an error
2. Try to follow the link to the docs
3. Observe that it takes you to the error page, but not to the correct section corresponding to the specific error code
4. Change the `_` characters in the link hash to `-`
5. ...?
6. Profit

**Expected behavior**
Errors page should scroll automatically to the correct hash. Should be achievable by transforming the `_` character to `-` before concatenating the `error_code` to the link. 

**Screenshots**

**Meilisearch version:** any

**Additional context**
Thank you engine team 🙏🏻 🚂

**Comment by curquiza** [comment]
Thanks @dichotommy for the report. Will be fixed in v1

**Comment by irevoire** [comment]
Also, by making the engine following the documentation instead of the opposite, it brokes all the links for the current and older version :pensive:

**Comment by dichotommy** [comment]
I agree with you @gmourier .

Especially now that we know that basement will be working on the new documentation site soon, there's no good reason to change the engine's behavior to match Vuepress's particularities.

I haven't looked into transforming the slugification. I imagine that it is doable but not sure if it's worth devoting time to with so many other things we need accomplish before v1.

On the other hand, being taken directly to the correct error code is a big quality of life improvement, especially for new users who are seeing an error for the first time. It may be worth fixing even if just for the weeks between the launch of v1 and the release of the new docs site.

@maryamsulemani97 Would you be able to have a look at Vuepress's docs and see if there is an easy solution for this? Ideally, it would affect only the error codes page as we don't want to have to redo all of our links. Thanks, and let me know if anything is unclear 🙏🏻

Since this issue will not be fixed on the engine side, could someone transfer it to the docs repo, please?

**Comment by gmourier** [comment]
Seen it with the engine team @dichotommy! You have nothing to do on your side, we will keep the `-` character in the error `link` field. We just have to be more careful about that in the future.

Thank you for the follow-up!
