### ISSUE TITLE
The `IndexDeletion` task details must show the `deletedDocuments` field

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#3108]
**Describe the bug**
[According to the specification of the tasks](https://specs.meilisearch.dev/specifications/text/0060-tasks-api.html#indexdeletion), we must always display the number of documents that were present in an index when we delete it. This number must be displayed under the `deletedDocuments` field in the task details.

**Meilisearch version:** v0.30.0rc2

**Comment by curquiza** [comment]
Fixed by #3110
