### ISSUE TITLE
Proximity ranking rule sometimes doesn't/can't use the proximity prefix cache

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3118]
The `proximity` ranking rule is responsible for prioritising documents where consecutive terms from the search query occur close to each other. For example, with the search query:
```
hello a
```
Then we want to prioritise documents where the word `hello` is close to a word starting with `a`.

To implement this, we have three databases:
- `word_pair_proximity` with the key `(proximity, word1, word2)` returns the documents where `word1` is followed by `word2` after `proximity` words.
- `word_prefix_pair_proximity` with the key `(proximity, word1, prefix2)` returns the documents where `word1` is followed by a word starting with `prefix2` after `proximity` words.
- `prefix_word_pair_proximity` with the key `(proximity, prefix1, word2)` returns the documents where a word starting with `prefix1` is followed by `word2` after `proximity` words.

Additionally:
- `word_prefix_docids` with key `prefix` returns the documents that contain a word starting with `prefix`

Note that:
1. only prefixes that correspond to a large number of words are stored in these databases
2. in `word_prefix_docids`, there is no length limit for `prefix`, whereas in `word_prefix_pair_proximity` and `prefix_word_pair_proximity`, prefixes can only be two bytes long.

In the implementation of the proximity ranking rule for the search `hello a`, we will check the following keys in the prefix databases:
- `word_prefix_pair_proximity(prox, "hello", "a")` for `prox` in `0..=7`
- `prefix_word_pair_proximity(prox, "a", "hello")` for `prox` in `0..=6`

A problem occurs when one of these database queries doesn't return any result. Then, we assume that the query did not return anything _because the prefix cannot be in this database_ (because it does not correspond to enough different words). Therefore, we fall back to a second implementation strategy that is much more expensive. We get the exhaustive list of words starting with `a` and perform the query `word_pair_proximity(prox, "hello", word_starting_with_a)` for each word, and then we take the union of all these results. 

This is especially a problem when the dataset contains many random-looking strings such as `hgb3p6a7r2` because they grow the list of words corresponding to many prefixes dramatically.

A potential solution is to avoid falling back to the secondary (expensive) implementation strategy if:
1. `word_prefix_docids(prefix)` returns any result; and
2. the length of the prefix is <= 2 bytes

But if:
1. `word_prefix_docids(prefix)` returns any result; and
2. the length of the prefix is > 2 bytes

then we "disable" the proximity ranking rule for this specific word pair by assuming that each document's proximity score for it is equal to 8 so long as the document contains both `word1` and `prefix`. This saves the performance of the search query at the cost of somewhat degrading the relevancy of the search results.

I hope that this modification will mitigate, somewhat, the latency issues found in https://github.com/meilisearch/meilisearch/issues/2966 and especially https://github.com/meilisearch/product/discussions/553 .

---

## TODO

- [ ] Implement changes in [Milli](https://github.com/meilisearch/milli/)
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by curquiza** [comment]
Close by https://github.com/meilisearch/meilisearch/pull/3269, which integrates milli v0.38.0, which integrates the changes for this issue.
