### ISSUE TITLE
CLI stabilization: rename the dumps commands

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3132]
Following this discussion: https://github.com/meilisearch/product/discussions/560
Specification: WIP

As part of the [CLI stabilization](https://github.com/meilisearch/meilisearch/issues/2752), we want to rename the dump commands.

- `dumps-dir` in the config file should be renamed to `dump-dir`
- `--dumps-dir` option when launching Meilisearch binary should be renamed `--dump-dir`
- `MEILI_DUMPS_DIR` env variable should be renamed to `MEILI_DUMP_DIR`

⚠️ Don't forget to change the [default config](https://github.com/meilisearch/meilisearch/blob/main/config.toml) file as well.

## Impacted teams

@meilisearch/integration-team, @meilisearch/cloud-team and @meilisearch/docs-team 

## TODO

- [ ] Implement the changes and merge to the `main` branch
- [X] Update the related spec -> https://github.com/meilisearch/specifications/pull/204

**Comment by brunoocasali** [comment]
@alallema do you think this can impact DevOps or meilisearch-migration?

**Comment by dureuill** [comment]
[PR is open](https://github.com/meilisearch/meilisearch/pull/3175), but I have a few remaining questions:

- should the default dump dir remain `dumps/` or become `dump`?
- I guessed that the default config file was `config.toml` at the root of the repository is that correct?

**Comment by dureuill** [comment]
[Spec PR is open](https://github.com/meilisearch/specifications/pull/204) too

**Comment by curquiza** [comment]
> should the default dump dir remain dumps/ or become dump?

Good question, can you ask this in the related product discussion: https://github.com/meilisearch/product/discussions/560?

> I guessed that the default config file was config.toml at the root of the repository is that correct?

Yes ! I updated the issue, thanks Louis!

**Comment by dureuill** [comment]
Thanks curqui I did so! https://github.com/meilisearch/product/discussions/560#discussioncomment-4284904

I was about to say that it would have been nice to have the product discussion referenced in the issue, but it looks like it was already there 😬

**Comment by alallema** [comment]
>@alallema do you think this can impact DevOps or meilisearch-migration?
Yes, but only names because the folder for dumps's creation are configured
