### ISSUE TITLE
Homebrew CI: run only after docker image and binaries are published

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3146]
To avoid this [kind of issue](https://github.com/meilisearch/meilisearch/issues/3139), when we publish a [GitHub release of Meilisearch](https://github.com/meilisearch/meilisearch/issues/3139), we should ensure the [Homebrew workflow](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-deb-brew-pkg.yml) runs only if the following workflows have passed:
- [docker image workflow](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-docker-images.yml)
- [binaries workflow](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-binaries.yml)

The best would be to create dependencies btw worklows.
Looks like it's possible following [this Stackoverflow answer](https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions), by using [`workflow_run`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)

## EDIT
Not really possible to only add `workflow_run` because our Docker and binaries CIs also run when we are publishing pre-release, and the Homebrew CI should not run in this case despite Docker and binaries CIs succeeded
I realized it's not that easy to do, it would involve a whole refactoring of our CIs, if I'm correct.
I would love to have some help/insight on this

To give more information to the community
- [docker image workflow](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-docker-images.yml) should run when a tag is created (not a GitHub release, a git tag!)
- [binaries workflow](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-binaries.yml) should run when a GitHub release or a GitHub pre-release is created
- [Homebrew workflow](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/publish-apt-brew-pkg.yml) should only run when a GitHub release is created

Thanks in advance for any help 🙏

**Comment by vvv** [comment]
Is this issue still relevant? Or has the desired outcome been achieved with [`on.release.types = [released]`](https://github.com/meilisearch/meilisearch/blob/fdb23132d4177139441b63ca854deef13e882245/.github/workflows/publish-apt-brew-pkg.yml#L5)?

**Comment by vvv** [comment]
AFAIU, here is current state of affairs,

```mermaid
stateDiagram
    dk: publish-docker
    bin: publish-binaries
    brew: publish-brew
    
    [*] --> dk: on.push.tags
    dk --> [*]

    [*] --> bin: on.release.types = [published]
    bin --> [*]

    [*] --> brew: on.release.types = [released]
    brew --> [*]
```

and this is the desired setup (@curquiza please confirm):

```mermaid
stateDiagram
    dk: publish-docker
    bin: publish-binaries
    brew: publish-brew
    
    [*] --> dk: on.push.tags
    %% dk --> [*]: fail
    dk --> brew: workflow_run.conclusion == 'success'

    [*] --> bin: on.release.types = [published]
    %% bin --> [*]: fail
    bin --> brew: workflow_run.conclusion == 'success' &&\n“on.release.types = [released]”

    brew --> [*]
```

`on.release.types = [published]` [ensures](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=published#release) that `publish-binaries` workflow is triggered when release, pre-release, or draft of a release is published.

`on.release.types = [released]` triggers a workflow when a release is published, or a pre-release is changed to a release.

We can make `publish-brew` differentiate between release and pre-release by passing an artifact from the triggering workflow (`publish-binaries`). The solution is [described here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow).

Now, according to [GitHub documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run), we cannot make `workflow_run` wait for both workflows to succeed. Here is the relevant snippet:

> If you specify multiple `workflows` for the `workflow_run` event, only one of the workflows needs to run. For example, a workflow with the following trigger will run whenever the "Staging" workflow or the "Lab" workflow completes.
>
> ```yaml
> on:
>   workflow_run:
>     workflows: [Staging, Lab]
>     types:
>       - completed
> ```

🤔

@curquiza How much do you hate the idea of merging the three workflows into one?

**Comment by curquiza** [comment]
Thank you very much for your help @vvv, your involvement is really appreciated.

Looks like it could work.

I don't know if I hate having everything in the same file. It could be a manifest for release/pre-release workflow.
In this case we need to add [this workflow](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/latest-git-tag.yml) as well (updating the `latest` git tag)

⚠️ Also, we need to keep
- the scheduled workflow
- the ability to trigger them manually (`workflow_dispatch`)

I don't know how complexe it would look for this small advantage of solving the first purpose of the issue..

What do you think @vvv?

**Comment by curquiza** [comment]
Hello @vvv 

Again thank you very much for your involvement and your reactivity.
I will review your PR as soon as I can. I have to be transparent with you: it can take time since I have a lot to do currently, so I will try to fully review it and test it during June. I hope it's ok for you. In any case your work is still valuable, now or late 😊 

Again, thank you for your PR.

**Comment by vvv** [comment]
@curquiza Absolutely! Take your time. 🙂

**Comment by curquiza** [comment]
Closing this issue for the reasons explained [here](https://github.com/meilisearch/meilisearch/pull/3794#issuecomment-1618460369)

Thank you again @vvv for the time you spent here, it's really appreciated to have people like you around us in the Meilisearch community ❤️
