### ISSUE TITLE
Config sizes in GiB instead of Gb

### ISSUE THREAD

**Issue by thijndehaas** [meilisearch/meilisearch#3150]
Meilisearch 0.29:
```--max-task-db-size=150Gb --max-index-size=250Gb```

Meilisearch 0.30:
```--max-task-db-size=150GiB --max-index-size=250GiB```

https://docs.meilisearch.com/learn/configuration/instance_options.html#max-index-size
**Current documentation:**
Sets the maximum size of the index. Value must be given in bytes or explicitly stating a base unit. For example, the default value can be written as `107374182400`, `'107.7Gb'`, or `'107374 Mb'`.

**Comment by curquiza** [comment]
Hello everyone here!

Fixed by #3160
Will be released in v0.30.1 in the coming days (or next week)
Sorry for the inconvenience
