### ISSUE TITLE
The `databaseSize` field of the `/stats` route is wrong

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3201]
**Describe the bug**
Currently, the `databaseSize` actually represents the sum of the size of all indexes.
It ignores;
1. The size of the api-key database
2. The size of the task queue
3. The size of all the pending tasks (which can get pretty big, so this one is definitely an issue)

**Comment by curquiza** [comment]
@irevoire, thanks for the report

How should we fix it? I mean, all of these 3 points should be taken into account for the fix?

Also, do you think we should fix this for v1?

**Comment by irevoire** [comment]
Yep, we should take the three points into account, but it shouldn't take a lot of locs; thus, it should be done in one PR.

> Also, do you think we should fix this for v1?

Personally, I think it would be nice to fix it for v1, but since it's non-breaking and no one ever complained about it, I would say it's a P3 task.
Also, I think it's a good first issue, so if someone from the community wants to tackle it, I could definitely help him!!

**Comment by dcm03** [comment]
It sounds like you are experiencing an issue with a database where the databaseSize value is not accurately reflecting the actual size of the database. Specifically, you mentioned that the databaseSize value is only considering the size of indexes and is not taking into account the size of the api-key database, the task queue, and pending tasks.

To fix this issue, you will need to modify the code that calculates the databaseSize value to include the sizes of the api-key database, task queue, and pending tasks. Depending on how the database is structured and how the databaseSize value is currently being calculated, this may involve adding additional code to iterate over the api-key database, task queue, and pending tasks and summing their sizes.

It's also worth considering why the databaseSize value is not accurately reflecting the actual size of the database. It's possible that there is a bug in the code that is causing certain elements of the database to be excluded from the calculation, or that the databaseSize value is not being updated properly when the database is modified. Identifying and fixing these issues may also be necessary to ensure that the databaseSize value is accurate.

**Comment by Kerollmops** [comment]
Hey @dcm03,

Please don't use chatGPT or alternative bots/AIs to answer our issues. Answers are empty, don't bring any information or help, and pollute the issue. One day, we can use those AIs to help us fix code problems but not for now. As you have probably noticed, your answer is just writing tree times the content of the original issue content.

Have a happy Christmas 🎄 😃

**Comment by dcm03** [comment]
Understood. Thanks for the response. Merry Christmas.On Dec 25, 2022 4:49 PM, Clément Renault ***@***.***> wrote:

Hey @dcm03,

Please don't use chatGPT or alternative bots/AIs to answer our issues. Answers are empty, don't bring any information or help, and pollute the issue. One day, we can use those AIs to help us fix code problems but not for now. As you have probably noticed, your answer is just writing tree times the content of the original issue content.

Have a happy Christmas 🎄 😃

**Comment by walterbm** [comment]
Hi @irevoire, 

I would definitely be interested in helping fix this issue but I'm still learning this project and would need some guidance to compute the missing metrics.

From what I can tell the `databaseSize` for `/stats` is computed here:
https://github.com/meilisearch/meilisearch/blob/e27bb8ab3e51b5fa06345d00f3ef2a23ca434cb4/meilisearch/src/routes/mod.rs#L295

And based on that it makes sense that the total is only showing the size of all indexes. I'm guessing the missing metrics could be computed in a similar way but I'm not familiar enough with this project to know how I could calculate the size of the api-key database and the size of the task queue.

Do you have any guidance to help me understand where to grab that data?

**Comment by irevoire** [comment]
Hey @walterbm, I'm so sorry, I kinda missed your message, and we were running a bit late on the release; thus, I implemented it myself :confounded: 

If you want, you can [check out my PR](https://github.com/meilisearch/meilisearch/pull/3418)

**Comment by curquiza** [comment]
Fixed by #3418
