### ISSUE TITLE
Change RC format

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3211]
This issue is only for traceability regarding an internal process of the @meilisearch/engine-team. Nothing to implement on the code base side (only CIs), only to let you know and be transparent.

Meilisearch versioning will follow [semantic version guidelines](https://semver.org/) starting from v1.0.0
You might know that our current RC format is not correct. It's currently `vX.X.XrcX`, but should be `vX.X.X-rc.X`
This is something we consider changing.

I checked with @meilisearch/integration-team, and this does not impact their team, we can easily fix it with a script to update their CI. Is it the same for you @meilisearch/docs-team and @meilisearch/cloud-team?

## Steps

- [x] Check with all the teams the impact is not too huge compared to the benefit of being fully semver compliant.
<s>- [ ] Update the CI in this repo </s> -> nothing to update
- [X] Update [our guide](https://github.com/meilisearch/engine-team/blob/main/resources/meilisearch-release.md) -> https://github.com/meilisearch/engine-team/pull/37

## Impacted teams

@meilisearch/integration-team

**Comment by nicolasvienot** [comment]
No impact that I can think of for the @meilisearch/cloud-team, @eskombro can you confirm? Thanks!

**Comment by eskombro** [comment]
We can definitely support both without any change in the codebase. What I don't understand is if this will impact older docker tags (rc that have been released before). We may need to recreate those docker images in that case, but we only expose RCs internally (in our .dev) so it shouldn't imapct any client

**Comment by guimachiavelli** [comment]
As far as I can see there are no mentions of RCs anywhere in the docs—and I struggle to think of any reasons why we would want to refer to a binary outside the usual major.minor.patch releases.

Should be good to go and have no impacts on the docs.

**Comment by bidoubiwa** [comment]
I tried with the [this script](https://raw.githubusercontent.com/meilisearch/integration-guides/main/scripts/get-latest-meilisearch-rc.sh) that we are using in all the integrations to fetch the latest rc.


```sh
# temp_file='temp_file' # temp_file needed because `grep` would start before the download is over
# curl -s 'https://api.github.com/repos/meilisearch/meilisearch/releases' >"$temp_file"
#
# # currently returns this "tag_name":"v0.30.0rc5",
# latest_rc_release=$(cat "$temp_file" | grep -E 'tag_name' | grep 'rc' | head -1) 
# rm -rf "$temp_file"

latest_rc_release="\"tag_name\": \"v0.30.0-rc.5\"",
latest_rc_release=$(echo $latest_rc_release | tr -d ',"' | cut -d ':' -f2 | tr -d ' ')
echo "$latest_rc_release"
```

it echoes the correct version `v0.30.0-rc.5`. Unless the commented grep does not work (which from what I see should not be impacted), it seems to work.

It seems to be the only place I'm aware of where we scrap the rc version.

**Comment by curquiza** [comment]
Thanks both of you for your feedback

**Comment by curquiza** [comment]
Everything has been updated on the engine side
I get in mind changes have to be done on integration side, thanks @brunoocasali for having added the label. Closing this issue since it's done and part of v1 changes
