### ISSUE TITLE
The `instance-uid` file is badly formatted

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3214]
**Describe the bug**
Since the `v0.30.0`, the file containing the `instance-uid` is badly formatted.
It's supposed to be written as a simple string so our users can share it with us easily if they need to, but after the huge refactor of the index-scheduler, it was written as bytes directly, which are a bit cumbersome to copy-paste/share.

**To Reproduce**
1. Run meilisearch
2. Read the `data.ms/instance-uid`

**Expected behavior**
It's a human-readable string

**Screenshots**

**Meilisearch version:**
Meilisearch `v0.30.0` and `v0.30.1`

**Additional context**
Introduced in https://github.com/meilisearch/meilisearch/pull/2763

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3213
will be released in v0.30.2 today or next week
