### ISSUE TITLE
Update Cargo.toml CI: make the PR point to the right branch

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3219]
When using [this CI](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/update-cargo-toml-version.yml), like this

<img width="1774" alt="Capture d’écran 2022-12-08 à 13 46 32" src="https://user-images.githubusercontent.com/20380692/206450322-f9eb910c-f587-4088-a8a8-3d2e7e2bf6a6.png">

What I expect
- having a new branch created: this branch starts from `release-v0.30.2`. New commits with changes are added to this branch
- having a new PR created: this PR should point to `release-v0.30.2`

What I got currently
- same for the first point -> ✅ 
- a new PR is created but points to `main` instead of `release-v0.30.2` -> ❌

**Comment by mohitsaxenaknoldus** [comment]
@curquiza How about https://github.com/meilisearch/meilisearch/pull/3224?

**Comment by curquiza** [comment]
Hello @mohitsaxenaknoldus thanks for your PR. I made a review on it 😊

**Comment by curquiza** [comment]
Reopening because #3224 does not work, jus a little detail missing
