### ISSUE TITLE
Improve the way we handle the settings and reindexation (incremental indexing for settings)

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3242]
When we change any setting related to indexing document fields in an internal database, e.g., searchable, filterable, faceted, we reindex everything, even internal data structures unrelated to the modified setting.

If we change the filterable attributes, we reindex everything, not only the filterable data structures but also the searchable attributes too. This could be an incredible improvement to the indexing speed but is hard to implement in the current engine version.

**Comment by ManyTheFish** [comment]
closing in favor of https://github.com/meilisearch/meilisearch/issues/4493
