### ISSUE TITLE
Improve the way soft deleted documents are represented internally

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3259]
We had a few issues with soft deleted bugs in v0.30.x, and I would like that to reduce the chance they return. For that, I would like to evaluate the possibility of making us aware of them in the types we use maybe.

It looks like #2909 is related to that and maybe also the fields count.

**Comment by curquiza** [comment]
@ManyTheFish @Kerollmops is this issue still relevant since we release v1.6.0?

**Comment by dureuill** [comment]
I'm pretty sure we can close this; I removed the soft-deleted documents in v1.6.

I'm taking the liberty to close @ManyTheFish and @Kerollmops reopen if you deem necessary.
