### ISSUE TITLE
Disable  logging

### ISSUE THREAD

**Issue by Zabrane** [meilisearch/meilisearch#3286]
Hi Everyone and Happy New year.
I'd like to disable Meilisearch logging altogether. Is that possible?
I'm facing a strange behaviour when running search queries: when setting tje logging level to TRACE, i get better latencies than when I set it to ERROR. TRACE logs more things and i was expecting the opposite result.
Many thanks

**Comment by loiclec** [comment]
Hi @Zabrane !
It is indeed a very strange behaviour! Have you been able to replicate this change in latencies multiple times? Could you also give us a few data points of the latencies you see with TRACE and ERROR logging? (e.g. "with TRACE logging: search requests take 10–80ms, with ERROR logging, they take 20–150ms").
Thank you 😄

**Comment by loiclec** [comment]
There is also the question of whether we should make it possible to disable logging entirely. What do you think @gmourier ?

**Comment by gmourier** [comment]
I would expect the same as @Zabrane regarding the `ERROR` vs `TRACE` timing.

It might be interesting to introduce a flag to disable logging if there is a notable difference between the INFO log level (default) and no logging.

@Zabrane Did you try it with the `INFO` level? I guess you were missing information with that log level, please correct me if I'm wrong! 

Even if it is not directly related to @Zabrane's request, It reminds me of this [discussion](https://github.com/meilisearch/product/discussions/570), where a user says that the WARN level logs too much information.

**Comment by Zabrane** [comment]
@loiclec @gmourier this is what i noticed so far `08-CORE / Intel(R) Xeon(R) CPU  E5504  @ 2.00GHz` where Meilisearch is pinned on `CORE 4-7`:
```
TRACE:  02-65ms
ERROR: 30-120m with max ~700ms
```

Would be great if we can have a new flag to disable tracing:
```
log_level = NONE
```

Question: my data set contains `248545` indexed documents. Meilisearch is using `~80MiB` of `RSS` (`203GB` of `VIRT`).

What should i use to make the search latency stable and predictable? How can i tune the underlying `LMDB` storage engine?

**Comment by loiclec** [comment]
@Zabrane 

1. There is not a lot you can do to improve latency beside:
    - limiting the number of [`searchableAttributes`](https://docs.meilisearch.com/learn/configuration/displayed_searchable_attributes.html#searchable-fields) to the minimum necessary 
    - reducing the number of [displayed fields](https://docs.meilisearch.com/learn/configuration/displayed_searchable_attributes.html#displayed-fields) if possible, to minify the payload of a search response
    - Using a powerful machine, if possible: fast SSD, enough (fast) RAM, good single-core performance
    - Ensure that meilisearch does not run at the same time as other resource-hungry programs 

2. There is no way to tune the underlying LMDB storage, as it is not a very configurable key-value store.

3. There shouldn't be much of a difference between `development` and `production` environments. However, I'd like someone else from @meilisearch/engine-team to confirm this.

---

Regarding the option to disable logging, it seems like it is not a controversial proposal (yet?). I will see if I can make a PR for it this week, but I can't promise that it will land in the next release.

--- 

Note that we will work a lot on reducing latencies in the coming year. When it comes to search performance, we still have a few low-hanging fruits to pick, and we have also planned deeper changes. That being said, single word search requests should not take ~90ms to be processed today. Could you share a little more information about your system, settings, dataset, and search requests so that we can debug this issue? In particular, I am curious about:
1. The model of the SSD (or just capacity / advertised speed)
2. The amount/type of RAM available
3. Your [meilisearch settings](https://docs.meilisearch.com/reference/api/settings.html#settings-object)
4. A sample document from your dataset 
5. A sample 1-word search query that takes >50ms to be processed, as well as its response (with redacted documents if you prefer)
6. The log level

Thank you for bringing this issue to our attention 😌

**Comment by Zabrane** [comment]
> * The model of the SSD (or just capacity / advertised speed)

```
$ sudo hdparm -I /dev/sda2
/dev/sda2:

ATA device, with non-removable media
	Model Number:       HGST HUS724020ALA640                    
	Serial Number:      PN2134P6K09HNX
	Firmware Revision:  MF6OAA70
	Transport:          Serial, ATA8-AST, SATA 1.0a, SATA II Extensions, SATA Rev 2.5, SATA Rev 2.6, SATA Rev 3.0; Revision: ATA8-AST T13 Project D1697 Revision 0b
Standards:
	Used: unknown (minor revision code 0x0029) 
	Supported: 8 7 6 5 
	Likely used: 8
Configuration:
	Logical		max	current
	cylinders	16383	16383
	heads		16	16
	sectors/track	63	63
	--
	CHS current addressable sectors:    16514064
	LBA    user addressable sectors:   268435455
	LBA48  user addressable sectors:  3907029168
	Logical  Sector size:                   512 bytes
	Physical Sector size:                   512 bytes
	device size with M = 1024*1024:     1907729 MBytes
	device size with M = 1000*1000:     2000398 MBytes (2000 GB)
	cache/buffer size  = unknown
	Form Factor: 3.5 inch
	Nominal Media Rotation Rate: 7200
Capabilities:
	LBA, IORDY(can be disabled)
	Queue depth: 32
	Standby timer values: spec'd by Standard, no device specific minimum
	R/W multiple sector transfer: Max = 16	Current = 16
	Advanced power management level: disabled
	DMA: mdma0 mdma1 mdma2 udma0 udma1 udma2 udma3 udma4 udma5 *udma6 
	     Cycle time: min=120ns recommended=120ns
	PIO: pio0 pio1 pio2 pio3 pio4 
	     Cycle time: no flow control=120ns  IORDY flow control=120ns
Commands/features:
	Enabled	Supported:
	   *	SMART feature set
	    	Security Mode feature set
	   *	Power Management feature set
	   *	Write cache
	   *	Look-ahead
	   *	Host Protected Area feature set
	   *	WRITE_BUFFER command
	   *	READ_BUFFER command
	   *	NOP cmd
	   *	DOWNLOAD_MICROCODE
	    	Advanced Power Management feature set
	    	Power-Up In Standby feature set
	   *	SET_FEATURES required to spinup after power up
	    	SET_MAX security extension
	   *	48-bit Address feature set
	   *	Device Configuration Overlay feature set
	   *	Mandatory FLUSH_CACHE
	   *	FLUSH_CACHE_EXT
	   *	SMART error logging
	   *	SMART self-test
	    	Media Card Pass-Through
	   *	General Purpose Logging feature set
	   *	WRITE_{DMA|MULTIPLE}_FUA_EXT
	   *	64-bit World wide name
	   *	URG for READ_STREAM[_DMA]_EXT
	   *	URG for WRITE_STREAM[_DMA]_EXT
	   *	WRITE_UNCORRECTABLE_EXT command
	   *	{READ,WRITE}_DMA_EXT_GPL commands
	   *	Segmented DOWNLOAD_MICROCODE
	    	unknown 119[7]
	   *	Gen1 signaling speed (1.5Gb/s)
	   *	Gen2 signaling speed (3.0Gb/s)
	   *	Gen3 signaling speed (6.0Gb/s)
	   *	Native Command Queueing (NCQ)
	   *	Host-initiated interface power management
	   *	Phy event counters
	   *	NCQ priority information
	    	Non-Zero buffer offsets in DMA Setup FIS
	    	DMA Setup Auto-Activate optimization
	    	Device-initiated interface power management
	    	In-order data delivery
	   *	Software settings preservation
	   *	SMART Command Transport (SCT) feature set
	   *	SCT Write Same (AC2)
	   *	SCT Error Recovery Control (AC3)
	   *	SCT Features Control (AC4)
	   *	SCT Data Tables (AC5)
Security: 
	Master password revision code = 65534
		supported
	not	enabled
	not	locked
		frozen
	not	expired: security count
	not	supported: enhanced erase
	420min for SECURITY ERASE UNIT.
Logical Unit WWN Device Identifier: 5000cca22dea6a31
	NAA		: 5
	IEEE OUI	: 000cca
	Unique ID	: 22dea6a31
Checksum: correct
```

> * The amount/type of RAM available
```
$ sudo lshw -short -C memory
H/W path       Device     Class          Description
====================================================
/0/0                      memory         64KiB BIOS
/0/4/5                    memory         256KiB L1 cache
/0/4/6                    memory         1MiB L2 cache
/0/4/7                    memory         4MiB L3 cache
/0/8/9                    memory         256KiB L1 cache
/0/8/a                    memory         1MiB L2 cache
/0/8/b                    memory         4MiB L3 cache
/0/14                     memory         16GiB System Memory
/0/14/0                   memory         8GiB DIMM DDR3 800 MHz (1.2 ns)
/0/14/1                   memory         DIMM DDR3 [empty]
/0/14/2                   memory         DIMM DDR3 [empty]
/0/14/3                   memory         DIMM DDR3 [empty]
/0/14/4                   memory         DIMM DDR3 [empty]
/0/14/5                   memory         DIMM DDR3 [empty]
/0/14/6                   memory         8GiB DIMM DDR3 800 MHz (1.2 ns)
/0/14/7                   memory         DIMM DDR3 [empty]
/0/14/8                   memory         DIMM DDR3 [empty]
/0/14/9                   memory         DIMM DDR3 [empty]
/0/14/a                   memory         DIMM DDR3 [empty]
/0/14/b                   memory         DIMM DDR3 [empty]
```

> * Your [meilisearch settings](https://docs.meilisearch.com/reference/api/settings.html#settings-object)

Default settings. See below for `log_level`.

> * A sample document from your dataset

```json
{
  "hits": [
    {
      "price": 1329,
      "agence": "1",
      "region_client": "4",
      "cip": "8085214",
      "article": "ESLOTIN 60MG/120ML SIR /120ML",
      "eip": "0",
      "dci": "",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "418085214"
    },
    {
      "price": 1462,
      "agence": "1",
      "region_client": "4",
      "cip": "2264401",
      "article": "MEDVITE SP FL/200ML          .",
      "eip": "0",
      "dci": "",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412264401"
    },
    {
      "price": 1640,
      "agence": "1",
      "region_client": "4",
      "cip": "8094762",
      "article": "FLEMING 250/31,25MG/5ML F/60ML",
      "eip": "0",
      "dci": "Amoxicilline#Acide clavulanique",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "418094762"
    },
    {
      "price": 754,
      "agence": "1",
      "region_client": "4",
      "cip": "2255678",
      "article": "IBEX 200/235/30MG GELU B/24",
      "eip": "0",
      "dci": "Paracétamol#Ibuprofène#Caféine",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412255678"
    },
    {
      "price": 532,
      "agence": "1",
      "region_client": "4",
      "cip": "2257051",
      "article": "PARAFLAM 400/325MG CP B/10",
      "eip": "0",
      "dci": "Paracétamol#Ibuprofène",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412257051"
    },
    {
      "price": 443,
      "agence": "1",
      "region_client": "4",
      "cip": "2283829",
      "article": "ZEBEN 400MG CP B/1",
      "eip": "0",
      "dci": "Albendazole",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412283829"
    },
    {
      "price": 399,
      "agence": "1",
      "region_client": "4",
      "cip": "2283835",
      "article": "ZEBEN 400MG/20ML SUSP 20ML",
      "eip": "0",
      "dci": "Albendazole",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412283835"
    },
    {
      "price": 1773,
      "agence": "1",
      "region_client": "4",
      "cip": "2283841",
      "article": "NORZOL 400/600MG CP B/10",
      "eip": "0",
      "dci": "Norfloxacine#Tinidazole",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412283841"
    },
    {
      "price": 931,
      "agence": "1",
      "region_client": "4",
      "cip": "2283143",
      "article": "BIOFERON 305MG GELU B/30",
      "eip": "0",
      "dci": "Multivitamines et mineraux",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412283143"
    },
    {
      "price": 1329,
      "agence": "1",
      "region_client": "4",
      "cip": "2283858",
      "article": "BIOFERON 8G/200ML SUSP 200ML",
      "eip": "5",
      "dci": "Multivitamines et mineraux",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412283858"
    },
    {
      "price": 4033,
      "agence": "1",
      "region_client": "4",
      "cip": "2252740",
      "article": "FLEMING 1000/125MG CP B/16",
      "eip": "0",
      "dci": "Amoxicilline#Acide clavulanique",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412252740"
    },
    {
      "price": 3102,
      "agence": "1",
      "region_client": "4",
      "cip": "2292308",
      "article": "OMIZEC 20MG GEL B/28",
      "eip": "0",
      "dci": "Oméprazole",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412292308"
    },
    {
      "price": 2659,
      "agence": "1",
      "region_client": "4",
      "cip": "2283864",
      "article": "FLEMING 500/62,5MG CP B/16",
      "eip": "0",
      "dci": "Amoxicilline#Acide clavulanique",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412283864"
    },
    {
      "price": 886,
      "agence": "1",
      "region_client": "4",
      "cip": "2263413",
      "article": "AMITRON 500MG GELU B/12",
      "eip": "0",
      "dci": "Amoxicilline",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412263413"
    },
    {
      "price": 709,
      "agence": "1",
      "region_client": "4",
      "cip": "2263407",
      "article": "AMITRON 250MG 3G/60ML SU 60ML",
      "eip": "0",
      "dci": "Amoxicilline",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "412263407"
    },
    {
      "price": 886,
      "agence": "1",
      "region_client": "3",
      "cip": "2263413",
      "article": "AMITRON 500MG GELU B/12",
      "eip": "0",
      "dci": "Amoxicilline",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "312263413"
    },
    {
      "price": 709,
      "agence": "1",
      "region_client": "3",
      "cip": "2263407",
      "article": "AMITRON 250MG 3G/60ML SU 60ML",
      "eip": "0",
      "dci": "Amoxicilline",
      "lib_cp": "MEDREICH",
      "lib_sp": "E.P.DIS. FRANCE.",
      "pr_nmla": "MEDREICH",
      "id": "312263407"
    },
    {
      "price": 888,
      "agence": "1",
      "region_client": "5",
      "cip": "2263413",
      "article": "AMITRON 500MG GELU B/12",
      "eip": "0",
      "dci": "Amoxicilline",
      "lib_cp": "MEDREICH",
      "lib_sp": "",
      "pr_nmla": "MEDREICH",
      "id": "512263413"
    },
    {
      "price": 710,
      "agence": "1",
      "region_client": "5",
      "cip": "2263407",
      "article": "AMITRON 250MG 3G/60ML SU 60ML",
      "eip": "0",
      "dci": "Amoxicilline",
      "lib_cp": "MEDREICH",
      "lib_sp": "",
      "pr_nmla": "MEDREICH",
      "id": "512263407"
    },
    {
      "price": 1332,
      "agence": "1",
      "region_client": "5",
      "cip": "8085214",
      "article": "ESLOTIN 60MG/120ML SIR /120ML",
      "eip": "0",
      "dci": "",
      "lib_cp": "MEDREICH",
      "lib_sp": "",
      "pr_nmla": "MEDREICH",
      "id": "518085214"
    }
  ],
  "query": "MEDREICH",
  "processingTimeMs": 97,
  "limit": 20,
  "offset": 0,
  "estimatedTotalHits": 401
}
```

> * A sample 1-word search query that takes >50ms to be processed, as well as its response (with redacted documents if you prefer)

```bash
$ curl -s 'http://xxxxx/indexes/items/search' -H 'Content-Type: application/json' --data-binary '{ "q": "MEDREICH" }'
```

> * The log level

`log_level = ERROR` (or `log_level = DEBUG`)

**Comment by Zabrane** [comment]
@loiclec little experiment: moving the indices to a `tmpfs` directory dramatically reduces the search latency:
```bash
$ mkdir /mnt/meili
$ mount -t tmpfs none /mnt/meili
$ cp -rf  /var/lib/data/meili/{data.ms,dumps} /mnt/meili/
$ chown -R meili:meili /mnt/meili
$ systemctl restart meilisearch.service
```

No query exceeded `10ms` now.

**Comment by loiclec** [comment]
@Zabrane Thanks **a lot** for all this information!

--- 

First, we saw there is [an existing issue about the performance of the logger used by meilisearch](https://github.com/rust-cli/env_logger/issues/123) and will be looking into it.

---

Also:

1. I _think_ that the main reason for meilisearch's bad performance on your machine is due to the hard drive. [We strongly recommend using a SDD instead of a HDD](https://docs.meilisearch.com/learn/advanced/indexing.html#improving-indexing-performance) (the link is about indexing performance, but this particular point also applies to search performance).

2. I'd like to amend my previous post about optimising latency with a couple more tips. I would recommend tweaking the default settings by:
   - manually setting the `searchableAttributes` to the smallest possible list of attributes that should be searchable (e.g. do the `id`, `agence`, `region_client`, etc. need to be searchable?). Though I acknowledge that you may really need all of them to be searchable. You may also want some attributes to be `filterableAttributes` ([1](https://docs.meilisearch.com/learn/core_concepts/indexes.html#filterable-attributes), [2](https://docs.meilisearch.com/reference/api/settings.html#filterable-attributes)) but not `searchableAttributes` (maybe for `price` or `id`, for example).
   - manually setting the [`rankingRules`](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#ranking-rules). For example, I noticed that the text of each field in the documents is quite short. So you may be able to remove the [`proximity`](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#_3-proximity) ranking rule without negatively affecting the relevancy of the search results. Similarly, you may try removing the [`attribute`](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#_4-attribute) ranking rule and evaluate the new relevancy and latency of the search requests.

**Comment by loiclec** [comment]
I've realised that the `OFF` log level is already available in meilisearch, but we chose not to document it in the past. We will officially document it in the next release. In the meantime, you can already use this unofficial feature by using the environment variable `MEILI_LOG_LEVEL` set to `OFF` or with the CLI option: `./meilisearch --log-level 'OFF'`.

**Comment by Zabrane** [comment]
@loiclec amazing. Thanks for the `OFF` tip.
I've tested the above optimization and indeed, the search latency is much more stable now.
