### ISSUE TITLE
Introduce a new cli-flag to autogenerate the master key

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3287]
Product discussion: https://github.com/meilisearch/product/discussions/538

Provide a new cli-flag `--generate-master-key` to autogenerate the master-key.

## TODO
- [x] Implement `--generate-master-key` CLI option in Meilisearch + the associated env variable
- [ ] Update the specification

## Impacted teams

@meilisearch/docs-team 
(sorry integration-team, I pinged you but you have nothing to do here)

**Comment by curquiza** [comment]
@meilisearch/docs-team 
⚠️ ⚠️ Important news!
Following [this thread](https://meilisearch.slack.com/archives/C01K0CZKASZ/p1672769479169809) (internal only) we decided NOT to implement this in v1.0
This [PR](https://github.com/meilisearch/meilisearch/pull/3308) removes the feature

We want to limit the newly introduced flags to avoid too much maintenance. Also, we want to wait for a concrete user-need before integrating this. So maybe the feature will come in the future, but not in v1.0. I will re-open an issue if one day we want to integrate it again.

Have a nice day 👋
