### ISSUE TITLE
Use the enum to display the error code and error type directly

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3289]
Currently, we represent all the possible error codes and types as enums in meilisearch; https://github.com/meilisearch/meilisearch/blob/ab655a85e8f678f50a7a2fda4a0957be71514c19/meilisearch-types/src/error.rs#L111-L184

But when we need to display them, instead of using their name, we write the implementation by hand instead of letting a tool like `serde_json` do it for us; https://github.com/meilisearch/meilisearch/blob/ab655a85e8f678f50a7a2fda4a0957be71514c19/meilisearch-types/src/error.rs#L186-L334
That's very error-prone, not tested and could cause issues in the dump since we need to deserialize the string by hand once again to try to get the original enum.

We then have to store `String` in the final type we give to `actix-web` when we could keep our original types and ease everything.

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3329
