### ISSUE TITLE
Remove `--disable-auto-batching` CLI option

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3294]
We should not keep the `--disable-auto-batching` CLI option, because:
1. I don't think there are clear advantages to disabling autobatching other than for debug purposes.
2. We can't introduce breaking changes after v1.0 is released. Keeping the flag will commit us to keeping this feature until v2.0 is released.
3. We can reintroduce it as an unstable feature later on.

## Impacted teams
@meilisearch/docs-team

**Comment by curquiza** [comment]
Did @gmourier give the final approval? Just to be sure he's aware of it

**Comment by gmourier** [comment]
Approving it by writing my comment! Thanks for the ping!

**Comment by curquiza** [comment]
Thanks @gmourier, I ping the @meilisearch/docs-team here.

Also @loiclec the spec needs to be updated and linked into this issue 😊
