### ISSUE TITLE
Meilisearch use way more memory than it should

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3299]
**Describe the bug**
As you can see in the following image, meilisearch constantly goes over 100% of RAM usage, then it gets killed, tries to index data again and gets killed again etc...
![image](https://user-images.githubusercontent.com/7032172/210405831-ac572b11-8127-46b6-ac43-c0e44e820322.png)

**Context**

- The searches running at the same time are probably not the issue (the machine isn't used a lot)
- Meilisearch was able to guess the 70% of the RAM available correctly; it limits itself to 2.5GiB and then tries to use 4GiB and die
- There is **a lot** of tasks processing at the same time. 45522, to be exact; maybe this is linked to the issue, maybe not.
- The geosearch is **not** used

The issue appeared to two persons who were sending pretty small batches;
- 1000 documents per batch with ~1M documents in total
- 256 documents per batch with ~2M documents in total

The specs of the first person are;
```
4 GB Memory / 2 Intel vCPUs / 25 GB Disk + 90 GB / NYC3 - MeiliSearch 0.30.0 on Debian 10 (buster) 
```

---------

MAYBE, a first fast fix could be to provide a way to limit the number of tasks the autobatching can batch together. imo that's not the best option, and maybe it won't even solve the issue, but we never know. 
If we do that, I'm 100% toward an unstable cli flag because I don't want to stabilize this option.

The real fix should be to find where it comes from in milli and stops using too much memory, but that could take a long time.

**Comment by JaySunSyn** [comment]
In addition to "limit the number of tasks the autobatching can batch together", a max batching time window would be super useful as well.

**Comment by irevoire** [comment]
That would be nice, but I don't think we can do it, sadly.
First, we select all the tasks, and then we try to process everything, which means if we realize it's taking too much time, it's already too late, everything has already been batched together :pensive:

**Comment by JaySunSyn** [comment]
v0.30.5

meilisearch uses 100% of the total CPU. No searches are executed.

![image](https://user-images.githubusercontent.com/5872432/211171509-ac3d80bc-d718-4d87-9ebe-d346245f72d5.png)

![image](https://user-images.githubusercontent.com/5872432/211171511-84371ec8-fcff-441a-bf6a-827e403fb548.png)

![image](https://user-images.githubusercontent.com/5872432/211171516-8d71463f-4d11-42fd-88b0-88df03fcde38.png)


After restarting, the CPU usage is fine again. If I then execute some searches it rises to 100% (expected). After stopping the searches, the CPU stays at 100% (unexpected).

Even after deleting all tasks (indexing stopped), the total CPU remains at 100%.

![image](https://user-images.githubusercontent.com/5872432/211171494-475b319c-2641-48e7-aafa-b2a6bb58a29e.png)

**Comment by curquiza** [comment]
Hello @JaySunSyn thanks for your report. I opened a new dedicated issue for your problem since it's not related at all with the current issues

Please, answer in the newly created issue to follow the progress of the @JaySunSyn's issue: https://github.com/meilisearch/meilisearch/issues/3314

**Comment by curquiza** [comment]
Some updates, discussed with @Kerollmops, here are some related PRs
- https://github.com/meilisearch/milli/pull/656
- https://github.com/meilisearch/meilisearch/pull/3651

**Comment by dureuill** [comment]
See comment in https://github.com/meilisearch/meilisearch/issues/3397#issuecomment-1630962794

**Comment by curquiza** [comment]
Hello!
For people following the issue, we release v1.6.0 on 15/01/2024, containing a way to limit the number of tasks 🎉

During Q1, we will also work on reducing the crash due to RAM consumption => we will open dedicated issues for specific things we want to improve in the code base.

I close the issue
