### ISSUE TITLE
Primary Key inference simplification: Address error message change

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3301]
The changes requested here need to be addressed:

- https://github.com/meilisearch/meilisearch/pull/3269#discussion_r1061527697
- https://github.com/meilisearch/meilisearch/pull/3269#discussion_r1061540382

This requires:

- [ ] A new milli PR to change the error message => https://github.com/meilisearch/milli/pull/759
- [ ] A new meilisearch PR to integrate the changes and update the tests => https://github.com/meilisearch/meilisearch/pull/3323
- [x] An update to the related spec PR: https://github.com/meilisearch/specifications/pull/208

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3329
