### ISSUE TITLE
Meilisearch Version 30.4 Undefined array key "facets"

### ISSUE THREAD

**Issue by leeweaver2222** [meilisearch/meilisearch#3312]
I am new to Meilisearch been on this for days,

I have followed the documentation 

These are the steps

POSTMAN
"filterableAttributes":["colour", "size", "fragrance", "theme", "crystal"]
TO ADD THEM 

PRODUCT MODEL
 public function toSearchableArray()
  {

    return array_merge([
      'id' => $this->id,
      'title' => $this->title,
      'slug' => $this->slug,
      'price' =>  $this->price,
      'category_ids' => $this->categories->pluck('id')->toArray()
    ], 
    $this->variations->groupBy('type')
         ->mapWithKeys(fn ($variation, $key) => [
         $key => $variation->pluck('title')
         ])
         ->toArray()

  );

Next PRODUCT BROWESER
   $searchquery = Product::search('', function ($meilisearch, string $query, array $options) {

            $options['facets'] = ['colour', 'theme', 'size', 'fragrance'];
        
            return $meilisearch->search($query, $options);
            
        })->raw();

$search = $this->category->products->find(collect($searchquery['hits'])->pluck('id'));

    return view('livewire.product-browser', [
            'currencies' => $currencies,
            'filters' => $search['facets'],
            'products' => $products
        ]);

C:\wamp64\www\www.leeweaver.uk\vendor\laravel\framework\src\Illuminate\Collections\Collection
.php
 
: 1701
  public function offsetGet($key): mixed

    {

        return $this->items[$key];

    }

What am I doing wrong please?.

Lee

**Comment by oluademola** [comment]
Hello @leeweaver2222 

Very sorry for the delayed response. I'll look into it and get back to you soon.

**Comment by oluademola** [comment]
Hello @leeweaver2222,

Can you please check if you have the key you are trying to access in your view? I'm not a Laravel expert, but I reckon you could try using the `exists` or `array_key_exists` method.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
