### ISSUE TITLE
DigitalOcean with volumes: Meilisearch uses 100% of the CPU when no search are executed

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3314]
----

Originally posted by @JaySunSyn [here](https://github.com/meilisearch/meilisearch/issues/3299#issuecomment-1374625371)

----

v0.30.5

meilisearch uses 100% of the total CPU. No searches are executed.

![image](https://user-images.githubusercontent.com/5872432/211171509-ac3d80bc-d718-4d87-9ebe-d346245f72d5.png)

![image](https://user-images.githubusercontent.com/5872432/211171511-84371ec8-fcff-441a-bf6a-827e403fb548.png)

![image](https://user-images.githubusercontent.com/5872432/211171516-8d71463f-4d11-42fd-88b0-88df03fcde38.png)

After restarting, the CPU usage is fine again. If I then execute some searches it rises to 100% (expected). After stopping the searches, the CPU stays at 100% (unexpected).

Even after deleting all tasks (indexing stopped), the total CPU remains at 100%.

![image](https://user-images.githubusercontent.com/5872432/211171494-475b319c-2641-48e7-aafa-b2a6bb58a29e.png)

**Comment by JaySunSyn** [comment]
At first it was indexing, then I cancelled all tasks, then I deleted the main index. CPU stayed at 100%
 

```txt
# This file shows the default configuration of Meilisearch.
# All variables are defined here: https://docs.meilisearch.com/learn/configuration/instance_options.html#environment-variables

db_path = "/meilisearch-data/data"
# Designates the location where database files will be created and retrieved.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#database-path

env = "production"
# Configures the instance's environment. Value must be either `production` or `development`.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#environment

http_addr = "localhost:7700"
# The address on which the HTTP server will listen.

master_key = "XXX"
# Sets the instance's master key, automatically protecting all routes except GET /health.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#master-key

no_analytics = false
# Deactivates Meilisearch's built-in telemetry when provided.
# Meilisearch automatically collects data from all instances that do not opt out using this flag.
# All gathered data is used solely for the purpose of improving Meilisearch, and can be deleted at any time.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#disable-analytics

http_payload_size_limit = "100 MB"
# Sets the maximum size of accepted payloads.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#payload-limit-size

log_level = "INFO"
# Defines how much detail should be present in Meilisearch's logs.
# Meilisearch currently supports five log levels, listed in order of increasing verbosity: `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`
# https://docs.meilisearch.com/learn/configuration/instance_options.html#log-level

max_index_size = "100 GiB"
# Sets the maximum size of the index.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#max-index-size

max_task_db_size = "100 GiB"
# Sets the maximum size of the task database.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#max-task-db-size

#max_indexing_memory = "3 GiB"
# Sets the maximum amount of RAM Meilisearch can use when indexing.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#max-indexing-memory

#max_indexing_threads = 4
# Sets the maximum number of threads Meilisearch can use during indexing.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#max-indexing-threads

disable_auto_batching = false
# Deactivates auto-batching when provided.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#disable-auto-batching


#############
### DUMPS ###
#############

dumps_dir = "/meilisearch-dumps/dumps/"
# Sets the directory where Meilisearch will create dump files.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#dumps-destination

# import_dump = "./path/to/my/file.dump"
# Imports the dump file located at the specified path. Path must point to a .dump file.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#import-dump

ignore_missing_dump = false
# Prevents Meilisearch from throwing an error when `import_dump` does not point to a valid dump file.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ignore-missing-dump

ignore_dump_if_db_exists = false
# Prevents a Meilisearch instance with an existing database from throwing an error when using `import_dump`.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ignore-dump-if-db-exists


#################
### SNAPSHOTS ###
#################

schedule_snapshot = false
# Activates scheduled snapshots when provided.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#schedule-snapshot-creation

snapshot_dir = "/meilisearch-dumps/snapshots/"
# Sets the directory where Meilisearch will store snapshots.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#snapshot-destination

snapshot_interval_sec = 86400
# Defines the interval between each snapshot. Value must be given in seconds.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#snapshot-interval

# import_snapshot = "./path/to/my/snapshot"
# Launches Meilisearch after importing a previously-generated snapshot at the given filepath.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#import-snapshot

ignore_missing_snapshot = false
# Prevents a Meilisearch instance from throwing an error when `import_snapshot` does not point to a valid snapshot file.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ignore-missing-snapshot

ignore_snapshot_if_db_exists = false
# Prevents a Meilisearch instance with an existing database from throwing an error when using `import_snapshot`.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ignore-snapshot-if-db-exists


###########
### SSL ###
###########

# ssl_auth_path = "./path/to/root"
# Enables client authentication in the specified path.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ssl-authentication-path

# ssl_cert_path = "./path/to/certfile"
# Sets the server's SSL certificates.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ssl-certificates-path

# ssl_key_path = "./path/to/private-key"
# Sets the server's SSL key files.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ssl-key-path

# ssl_ocsp_path = "./path/to/ocsp-file"
# Sets the server's OCSP file.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ssl-ocsp-path

ssl_require_auth = false
# Makes SSL authentication mandatory.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ssl-require-auth

ssl_resumption = false
# Activates SSL session resumption.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ssl-resumption

ssl_tickets = false
# Activates SSL tickets.
# https://docs.meilisearch.com/learn/configuration/instance_options.html#ssl-tickets
```

**Comment by curquiza** [comment]
Thanks for your reactive answer @JaySunSyn 

I know you have discussed this with @irevoire, who tried to reproduce the issue but without any success 😢 

Would it be possible for you to give more information about your machine?

To any other people reading this issue and having the same problem, please let us know about any other information you might have 🙏

**Comment by JaySunSyn** [comment]
@curquiza 
```
4 GB Memory / 2 Intel vCPUs
```

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5872432/212767920-ef42fe7a-c810-4321-a01d-896769852248.png">


What other infos do you need?

**Comment by JaySunSyn** [comment]
It happens again.

1. no searches, only indexing => CPU at low level
2. multiple heavier searches => CPU at 100%
3. no searches => CPU stays at 100%


<img width="1006" alt="image" src="https://user-images.githubusercontent.com/5872432/212768620-f26e10cd-0f81-4c64-a77b-e4710f3e9188.png">

<img width="605" alt="image" src="https://user-images.githubusercontent.com/5872432/212769023-2a0a546c-8fe0-4e91-b0ec-cd8aaa221ef6.png">

**Comment by curquiza** [comment]
Sorry for the late answer @JaySunSyn 
Thanks for your report, we don't really know what to do since we don't succeed to reproduce. However, it looks like your issue is related to this one: https://github.com/meilisearch/meilisearch/issues/3349

**Comment by curquiza** [comment]
Also, for anyone having this bug, and who has the time to do more investigation: can you test to reproduce the bugs with [v0.29.3](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.3) or [v1.0.0-rc.1](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0-rc.1)?

**Comment by curquiza** [comment]
Hello @JaySunSyn 

> multiple heavier searches => CPU at 100%

I was discussing with @loiclec, and we were wondering what you mean exactly with "heavy search"?

How long does the search take? Do you get the response from Meilisearch (with search results)?

How many searches do you do? If you do a lot, do you ensure you have gotten all the responses?

Thanks in advance for your help 🙏

**Comment by JaySunSyn** [comment]
@curquiza  Upgraded to v1.1.0. After executing around 40 searches and then stopping, this happens:

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/5872432/231026220-766e3f1f-27cd-4887-a6a9-a086fcfe6ffc.png">


<img width="1791" alt="image" src="https://user-images.githubusercontent.com/5872432/231026166-b59d0a69-1e07-4a48-8457-0c78488d9477.png">

**Comment by JaySunSyn** [comment]
It's stuck at 100% without searches. Moved now to GCP and all good. Def something to do with DO and maybe attached Volumes.

**Comment by Kerollmops** [comment]
Hey @JaySunSyn 👋

We highly improved the search speed and latency in [the latest meilisearch v1.2.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.2.0).
Could you take a look at it?

Have a nice day 🌻

**Comment by savikko** [comment]
Probably related to this: https://github.com/meilisearch/meilisearch/issues/4653
