### ISSUE TITLE
Ensure we test every error codes

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3325]
Error codes to test;
- [x] Search API - https://github.com/meilisearch/meilisearch/pull/3324
- [x] All Settings API - https://github.com/meilisearch/meilisearch/pull/3326
- [x] Sub Settings API - There is a bug, the error code were NEVER returned correctly - https://github.com/meilisearch/meilisearch/pull/3329
- [x]  Task API - There was a bug on the `limit` and `from` - https://github.com/meilisearch/meilisearch/pull/3330
- [x] Document Resource - https://github.com/meilisearch/meilisearch/pull/3373
- [x] Swap API - https://github.com/meilisearch/meilisearch/pull/3341
- [x] Index API - #3416
- [x] Keys API - #3419

**Comment by curquiza** [comment]
Closed since all the tasks are finished
