### ISSUE TITLE
Testing the swap-indexes

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3340]
Currently, there are zero (0) integration tests on the swap-indexes features.
(there is a lot of test in the index-scheduler but no integration tests)

- [x] Ensure the feature works as expected
  - [x] When swapping two indexes their task history should be updated as well
- [x] Ensure all the good errors messages are returned when they're supposed to and with the good error codes

**Comment by curquiza** [comment]
Fixed by #3341
