### ISSUE TITLE
Improve error messages given by `deserr`

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3350]
I am listing here a few ideas to improve meilisearch's error messages when a request cannot be deserialised. 

## Suggesting corrections to invalid field names
When a given field/parameter is invalid, look at the list of accepted fields to find the closest match (using its Levenshtein distance). Suggest it to the user. 
Current error:
```json
"Unknown field `displayedAttribute`: expected one of `displayedAttributes`, `searchableAttributes`, `filterableAttributes`, `sortableAttributes`, `rankingRules`, `stopWords`, `synonyms`, `distinctAttribute`, `typoTolerance`, `faceting`, `pagination`"
```
Improved error:
```json
 "Unknown field `displayedAttribute`: did you mean `displayedAttributes`? Expected one of `displayedAttributes`, `searchableAttributes`, `filterableAttributes`, `sortableAttributes`, `rankingRules`, `stopWords`, `synonyms`, `distinctAttribute`, `typoTolerance`, `faceting`, `pagination`"
```
The same can be done when deserialising a simple enum like `MatchingStrategy`. The following error:
```json
"Unknown value `lasts` at `.matchingStrategy`: did you mean `last`? Expected one of `last`, `all`"
```
We can also manually specify "invalid aliases" for certain fields. For search requests, we could automatically suggest the user to use `q` instead of `query`:
 ```json
 "Unknown field `query`: did you mean `q`? Expected one of `q`, `offset`, `limit`, `page`, `hitsPerPage`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `showMatchesPosition`, `filter`, `sort`, `facets`, `highlightPreTag`, `highlightPostTag`, `cropMarker`, `matchingStrategy`"
 ```
 
## Customisable "expected..." messages
When the type of a field is invalid, we should give a better explanation of what the engine expects. This could be done via a new `deserr` field/container attribute, e.g. `#[deserr(expected = "an array of task ids")]` 
Current error:
```json
"Invalid value type: expected an array, but found a string: `\"doggo\"`"
```
Improved error:
```json
"Invalid value type: expected an array of attribute names, but found a string: `\"doggo\"`"
```
For another example, the error for an invalid index swap could become:
```json
"Invalid value type at `[0].indexes`: expected an array containing two index names, but found a string: `\"doggo\"`"
```

## Easily review the error messages
It would be good to have a file in `meilisearch/tests` with a _reasonably thorough_ (or at least representative) list of all our error messages. This would make it easy for the documentation team to review them and suggest improvements. 

## Other
I'll add more to this list as I find more ideas. Also feel free to add your own suggestions :)

**Comment by irevoire** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3339
