### ISSUE TITLE
Detect Language during indexing to enhance language detection at search time

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#3357]
The goal of this issue is to use the work made in meilisearch/milli#660 at search time to reduce the list of languages that can be detected by Charabia. This would avoid the search to detect languages that have not been detected during indexing and so, for example, avoid segmenting and normalizing Japanese Kanji like Chinese characters when we know that the index is 100% Japanese.

Fixes meilisearch/milli#646 
related to https://github.com/meilisearch/meilisearch/issues/2403

branch: https://github.com/meilisearch/milli/tree/enhance-language-detection

### TODO

- [x] Include the last version of Charabia
- [ ] Collect detected Languages in an allowlist and pass the allowlist to Charabia

**Comment by ManyTheFish** [comment]
closed by https://github.com/meilisearch/meilisearch/pull/3347

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.1.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation here in this current issue.
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 3rd April 2023

⚠️ RC (release candidates) are not recommended for production
