### ISSUE TITLE
Don't limit the number or size of indexes

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3382]
## Context

- There is currently an inherent tradeoff between the number of opened indexes and their max size. In v1.0.0, this tradeoff is "fixed" due to the removal of the `--max-index-size` option. We would like to not expose this tradeoff to end users anymore.
- For more context: https://github.com/meilisearch/meilisearch/discussions/3280
- Also related to issue https://github.com/meilisearch/meilisearch/issues/1841 that's already planned for the v1.1 milestone

## Implementation

- Automatically resize indexes: this allows to start with a lower "`--max-index-size`" and plan accordingly to the actual space needs of the index.
- Limit the concurrent number of opened indexes: this ensures that we can reach bigger `--max-index-size` by closing least recently used indexes.

I have some draft PRs implementing both of these: https://github.com/meilisearch/meilisearch/pull/3319 and https://github.com/meilisearch/meilisearch/pull/3331 

## Specification

A specification PR was opened: see https://github.com/meilisearch/specifications/pull/226

**Comment by curquiza** [comment]
I add the `missing spec` label in case we would need to update the spec. @gmourier and @dureuill

**Comment by curquiza** [comment]
Also this issue could interest @meilisearch/docs-team  regarding the limitations of the search engine

**Comment by curquiza** [comment]
Just discussed with @dureuill, he confirmed the newly introduced limits will be present in the spec, or at least in this issue.
In Linux, only the size of the disk will be the limit (can be different on Windows), so no defined limit of number of indexes 😊

**Comment by dureuill** [comment]
After discussing with @Kerollmops, here are some points that are still to be done after #3331 : 

- [ ] Check that the lock cannot become poisoned due to an *impromptu* panic
- [ ] There is a `indexes` method on the `IndexMapper` and the `Indexer` that return a vector of handles to all the indexes, resulting in all indexes being opened. This is used in several places, such as the API keys, the stats route, and so on.  This results in a failure is the sum of all indexes cannot fit in the virtual memory address space. Several solutions can possibly address this issue:
  1. Have the `indexes` methods return an iterator instead => doesn't prevent caller from `collect`'ng it
  2. Have the `indexes` methods accept a closure with an IndexHandle that cannot be cloned or escape the closure as argument.
  3. Replace the `indexes` methods by `index_stats` methods that return a Vec of stats => not necessarily sufficient for dumps
  4. Wrap the `Index` object in a `LazyIndex` object that doesn't keep the `Index` handle, but reopen it as necessary => Would make sure that the issue cannot popup whatever what the `IndexMapper` clients do, but is very invasive.

For the first iteration, it would be good to at least document the issue in the concerned function, and at least explore option (2) or (3)

**Comment by dureuill** [comment]
Indexing performance concern:

As we have to wait for the indexing task to fail when indexing, if the indexed data is big, we might resize the index multiple times, and so attempt the task multiple times.

This can make indexing bigger datasets much slower, as we would have to attempt indexing them many more times. Two consecutive resizes would result in about tripling the indexing time.

---

Possible solutions discussed with @Kerollmops and @ManyTheFish : 


### 1. Allocate a significant portion of the memory space for the index that is being written to.

- Advantage: No resize for that index
- Cons: the index must be closed to write to another index, losing data locality. This can be particularly bad in patterns where multiple indexes are updated together with small, incremental updates

### 2. Evaluate our process "virtual address space" budget, then allocate it up to some size in the LRU

- Advantage: No special "index being written to" status, limits the need for closing index, improve data locality
- Cons: Will need fine tuning to avoid situations where the maximum index size is too small, and situations where the budget is taken entirely (due to an index resizing unexpectedly, etc)
- Cons: Having each index be e.g. 2TB (so about 30 indexes if taking half of the available space in linux) will penalize people that have many small indexes.
- Cons: determining the budget takes up to 2 seconds which might slow down startup/first search by that duration

### 3. Choose some "reasonable default" for index size, leave resize a costly operation that should happen infrequently in normal use

- eg 200 GB. Possibly downsize the index for users that have a very small virtual memory index space if opening the index fails.

- Pros: Simple, no need to compute a budget
- Cons: Penalizes people with a few big indexes, as they will suffer resizes.


---

There are 2 use cases to consider:

1. Dump import / first indexation. In this use case, the final size of the index is completely unknown (although we could have the size of the index on size as of the dump creation stored in the dump for a hint)
2. Index update: While the final size of the index is fundamentally unknown, there's a good likelihood that it will remain close to the original size of the index


---

From all this, a first strategy could be:

1. At startup, compute "virtual address space" budget by attempting to open an environment with various sizes dichotomically.
2. Keep a fraction (e.g. 1/2) of this budget as the "index budget".
3. Initialize the LRU to accommodate for N indexes of 1TB of map_size such that the "index budget" is entirely taken. N=6 on Windows, N=50 on Linux/macOS.
4. If the "index budget" is < 1TB, then have a LRU of 1 index with the map_size the entire index budget.

The strategy favors users with a few bigger indexes, as users with many indexes (1000) will have them closed/opened often. OTOH, with many indexes they are probably small, so reading them from disk isn't that much a penalty with a SSD. Moreover, other system limits like simultaneous file handle available to a process (256 on stock Unix) might come into play anyway for keeping many indexes open.

Having an index need more than 1TB of map_size might result in allocation errors if the cache is full. Disregarding Windows this would be a use case with many big indexes or 1 big indexes and many small indexes. This use case could be better handled by making the cache "understand" how much budget it has and how much budget an index takes.

**Comment by dureuill** [comment]
A prototype that removes the restriction on the number or size of indexes is available!

### How to get the prototype?

- Using docker, use the following command: `docker run -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:prototype-unlimited-indexes-0`
- From source, compile Meilisearch on the `prototype-unlimited-indexes-0` tag

### How to use the prototype?

Use the prototype as you would use a `v1.0.0` Meilisearch instance, in particular it is not needed to reindex your data. The prototype should allow you to create as many indexes as wanted, of any arbitrary size (that fits on disk!)

⚠️ Do not use the prototype in production ⚠️

### Use cases we might want to test with the prototype

1. Having one, or a few, big indexes, like >500GiB in size. For this use case it would be interesting to index the data with the prototype to see if there are any significant performance hit compared with e.g. `v0.30` (see performance concern in the [comment above](https://github.com/meilisearch/meilisearch/issues/3382#issuecomment-1429965088))
2. Having many smaller indexes, like >200 indexes. For this use case it would be interesting to perform searches on the various indexes depending on actual workloads, to see if there are any significant performance hit compared with e.g. `v0.30`.

Thanks to anyone taking the time to test this prototype ♥️

**Comment by dureuill** [comment]
A second prototype that removes the restriction on the number or size of indexes is available!

Compared with the previous prototype, this one removes the performance concern wrt index resize 👍 . However, it uses a sufficiently distinct approach that testing it again is welcome 😃 

### How to get the prototype?

- Using docker, use the following command: `docker run -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:prototype-unlimited-indexes-1`
- From source, compile Meilisearch on the `prototype-unlimited-indexes-1` tag

### How to use the prototype?

Use the prototype as you would use a `v1.0.0` Meilisearch instance, in particular it is not needed to reindex your data. The prototype should allow you to create as many indexes as wanted, of any arbitrary size (that fits on disk!)

⚠️ Do not use the prototype in production ⚠️

### Use cases we might want to test with the prototype

1. Having one, or a few, big indexes, like >500GiB in size. For this use case it would be interesting to index the data with the prototype to see if there are any significant performance hit compared with e.g. `v0.30` (see performance concern in the [comment above](https://github.com/meilisearch/meilisearch/issues/3382#issuecomment-1429965088))
2. Having many smaller indexes, like >200 indexes. For this use case it would be interesting to perform searches on the various indexes depending on actual workloads, to see if there are any significant performance hit compared with e.g. `v0.30`.

Thanks to anyone taking the time to test this prototype ♥️

**Comment by dureuill** [comment]
Good news, we reached a good first level in preparation for v1.1 RC0 :tada:.

However, I'm reopening this issue because we have some follow-ups that should be addressed before closing:

- Increased Windows/macOS startup time. This could be mitigated by first trying a budget value that should be "good enough" and skipping the dichotomy if it passes.
- Degraded stats performance. This could be mitigated by caching the stats of indexes (eg in the tasks db).
- Finer-grained error handling in the dichotomy: make a difference between allocation errors (continue the dichotomy after marking this value as "bad") and other kinds of errors (stop the dichotomy and report the error to the caller)

**Comment by dureuill** [comment]
So I'm not sure how to best express this and **where in the specification this should appear**, but following the changes made for v1.1, the current status, relevant to the docs team in particular, is the following: 

- Meilisearch can accommodate an **arbitrary number** of indexes under 2TiB of disk size.
- If having indexes bigger in size than 2TiB, then Meilisearch can still accommodate them as long as the sum of the disk sizes taken by any group of 20 of the existing indexes is below 80 TiB.
- While Meilisearch supports an arbitrary number of indexes, having many indexes accessed at random will trigger more reads from disk and might be slower, so limit the number of concurrently accessed indexes if possible. For instance, if requiring multi-tenancy, consider using tenant tokens in a single index rather than creating one index per tenant.

Cc @gmourier where in the specs should this appear?

**Comment by dureuill** [comment]
Discussed with gmourier and opened the following specification PR: https://github.com/meilisearch/specifications/pull/226

**Comment by curquiza** [comment]
Done and release in v1.1.0 🎉
