### ISSUE TITLE
When updating the `primaryKey`, if the previous `primaryKey` value has already been used for a document, the API returns an index_primary_key_already_exists error -> ASYNC

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3385]

**Comment by irevoire** [comment]
Not sure we actually want to « fix » this.
It would stop us from autobatching every time there is a pk change :thinking:

**Comment by curquiza** [comment]
I'm not sure to get the relation with auto-batching

**Comment by curquiza** [comment]
Maybe you need to inform @gmourier about this because I'm pretty sure that returning a `index_primary_key_already_exists` when the pk already exist is an expectation from the specifications.

**Comment by irevoire** [comment]
Yeah, I already told him about it, but he doesn't have the time rn; I guess we'll see next week what we want to do with it.
I don't think it'll be hard to implement whichever solution we choose so it should be _ok_ to do it next week

**Comment by curquiza** [comment]
We can wait for next week, no problem

**Comment by irevoire** [comment]
It has been decided to merge it because, most of the time it shouldn't be an issue

**Comment by curquiza** [comment]
Closed by #3412
