### ISSUE TITLE
Meilisearch allocates too much memory when processing a settings update 

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3397]
**Describe the bug**
When processing a `settingsUpdate` task, meilisearch allocates twice the amount of memory given by `--max-indexing-memory`.

**To Reproduce**
0. Launch meilisearch with the flag `--max-indexing-memory 2GB`
1. Index some documents
2. Update the settings in a way that triggers a reindexing (e.g. change the filterable attributes)

Notice that the allocated memory sometimes largely exceeds 2GB.

**Details**
I wrote a custom allocator to print the resident memory after each large allocation, which gave this trace:
```txt
allocating 1000000000 with new resident size: 1015258128
   8: milli::update::index_documents::helpers::grenad_helpers::create_sorter
   9: milli::update::index_documents::transform::Transform::new
  10: milli::update::index_documents::IndexDocuments<FP,FA>::new
  11: milli::update::settings::Settings::reindex

allocating 1000000000 with new resident size: 2015258128
   8: milli::update::index_documents::helpers::grenad_helpers::create_sorter
   9: milli::update::index_documents::transform::Transform::new
  10: milli::update::index_documents::IndexDocuments<FP,FA>::new
  11: milli::update::settings::Settings::reindex

allocating 500000000 with new resident size: 2515338368
   8: milli::update::index_documents::helpers::grenad_helpers::create_sorter
   9: milli::update::index_documents::extract::extract_docid_word_positions::extract_docid_word_positions
  10: milli::update::index_documents::extract::send_and_extract_flattened_documents_data::{{closure}}

allocating 500000000 with new resident size: 3015395707
   8: milli::update::index_documents::helpers::grenad_helpers::create_sorter
   9: milli::update::index_documents::extract::extract_docid_word_positions::extract_docid_word_positions
  10: milli::update::index_documents::extract::send_and_extract_flattened_documents_data::{{closure}}
```

**Cause**
The `Settings::reindex` method does the following:
1. create its own `Transform`, allocating the maximum amount of memory
2. consume this `Transform` to get a `TransformOutput`. Memory usage down to ~0 again.
3. call `IndexDocuments::new`, which also creates a (useless) transform using the maximum amount of memory
4. call `IndexDocuments::execute_raw(..)` with the output of (2), which launches the whole regular indexing process

The core of the issue is that the transform created in (3) is never dropped before indexing starts.

**Caveat:**
Since the memory allocated by the transform in `IndexDocuments::new` is never touched, I don't know whether it can cause any real issue.

**Meilisearch version:** 
v0.30.0 (at least)

**Related issues**: 
Maybe https://github.com/meilisearch/meilisearch/issues/3299 , but I am not convinced it is the same one.

**Comment by curquiza** [comment]
For your information, @Kerollmops has started working on it, on this branch https://github.com/meilisearch/grenad/compare/main...sorter-lazy-allocation

**Comment by curquiza** [comment]
Some updates, discussed with @Kerollmops, here are some related PRs
- https://github.com/meilisearch/milli/pull/656
- https://github.com/meilisearch/meilisearch/pull/3651

**Comment by dureuill** [comment]
Ping from triage

- Size: small to test if open [PR fixes](https://github.com/meilisearch/grenad/pull/43) the issue

**Comment by ManyTheFish** [comment]
I've tried several indexing with version 1.9.0 using the flag `--max-indexing-memory 2GB`:
- 8GB wiki:
  - full indexing: spike at 5.37GB
  - change filter setting: spike at 3.02GB
  - change the searchable setting: pike at 2.47GB but 7.85GB when writing `words_prefix_integer_docids` 
- 1GB songs:
  - full indexing: spike at 5.00GB
  - change filter setting: spike at 1.91GB
  - change the searchable setting: pike at 3.44GB but 4.32GB when writing `words_prefix_integer_docids` 

Meilisearch still overuses the memory when it can, mainly when writing in the database. This may be due to LMDB.
