### ISSUE TITLE
Add tests with rust `nightly` to our CI

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3402]
In the [`test-linux`](https://github.com/meilisearch/meilisearch/blob/b3166df7ea597beef798278e56d2a4b4c545c0da/.github/workflows/rust.yml#L18) job, we would like to add two tests
- one run with rust `stable`
- one with rust `nightly`

As we did in this CI:

https://github.com/meilisearch/milli/blob/3521a3a0b287ff788de875b53f3f35d04c7fa155/.github/workflows/rust.yml#L15-L49

Like in the previous CI, the test on `nightly` should only run once a day, like we did before:

https://github.com/meilisearch/milli/blob/3521a3a0b287ff788de875b53f3f35d04c7fa155/.github/workflows/rust.yml#L4-L5

The test with `stable` should keep running for every commit on pull request

**Comment by PrathyushaModala** [comment]
Hi @curquiza I would like to work on this issue. Can you please assign it to me:)
