### ISSUE TITLE
Implement more term matching strategies: frequency, first, etc.

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3424]
Linked to the following product discussion: https://github.com/meilisearch/product/discussions/255.

It's possible to implement two additional matching strategies ([v0.30.0 documentation link](https://github.com/meilisearch/documentation/blob/v0.30/reference/api/search.md#matching-strategy)):

- `frequency` will drop the query words that are the most frequent in the dataset (and therefore keep the least frequent ones) -> discussed with @ManyTheFish and the team, it's not trivial, and we need to discuss if the typo will be allowed or not (benchmark needed before making any decision)
- `first` will drop the first words in the query -> ⚠️  discussed with @gmourier and the team, looks like there is no point to do this now

The following modifications could be also implemented:
- if a word in the query matches 0 documents, we immediately remove it, before applying the matching strategy or the query length limit
- the matching strategy should be applied *before* the query length limit. So with the `frequency` strategy and a query of 30 words, we should only keep the 10 least frequent words
- however, if these changes are implemented, we should be careful to handle malicious search properly (e.g. those containing hundreds of words)

**Comment by vaishnavi-ramanujapuram** [comment]
Hello @loiclec, I would like to contribute to this issue.

**Comment by loiclec** [comment]
Hi @vaishnavi-ramanujapuram, that's great to hear :-) At the moment, it isn't possible to add these new strategies, because we are refactoring a large part of the code related to search algorithms. However, it will become possible to start working on it in a month or two. I will add a comment to this issue when this happens.

**Comment by curquiza** [comment]
For your information @vaishnavi-ramanujapuram only issues with the `contribution accepted` and `good first issue` label are open to the community.
You can find the list here: https://github.com/meilisearch/meilisearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+label%3A%22contribution+accepted%22
Also [bugs investigation](https://github.com/meilisearch/meilisearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug%22+) are more than welcome 😊

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

I close this issue in favor of the product discussion https://github.com/meilisearch/product/discussions/255

Some possible addition of `matchingStrategy` will be prioritized in the future, so we will re-open clearer issues with our sprint issue format when we officially work on them.

If you have one of new `matchingStrategy` you would like to see, please let us know which one and why in the product discussion
