### ISSUE TITLE
Allow setting the ranking rules at search time

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3425]
This issue is linked to the following product discussion: https://github.com/meilisearch/product/discussions/593 .
More will be added to it depending on the course of the discussion.

**Comment by curquiza** [comment]
Closing this issue in favor of the product discussion https://github.com/meilisearch/product/discussions/593

This feature will be prioritized in the next sprints, so we will re-open a clearer one with our sprint issue format when we will officially work on it
