### ISSUE TITLE
ERROR: Impossible to get the latest stable version of Meilisearch.

### ISSUE THREAD

**Issue by speciale** [meilisearch/meilisearch#3429]
**Describe the bug**
curl -L https://install.meilisearch.com | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4353  100  4353    0     0  17840      0 --:--:-- --:--:-- --:--:-- 17840
Downloading Meilisearch binary v0.30.5 for linux, architecture amd64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Failed to create the file meilisearch-linux-amd64: Permission denied
  0  111M    0  1369    0     0   2822      0 11:28:28 --:--:-- 11:28:28  2822
curl: (23) Failure writing output to destination

ERROR: Impossible to get the latest stable version of Meilisearch.
Please let us know about this issue: https://github.com/meilisearch/meilisearch/issues/new/choose

In the meantime, you can manually download the appropriate binary from the GitHub release assets here: https://github.com/meilisearch/meilisearch/releases/latest

**To Reproduce**
Run
 curl -L https://install.meilisearch.com | sh
**Expected behavior**
Download and install

**Screenshots**
Nope

**Meilisearch version:** [e.g. v0.20.0]
latest stable 
**Additional context**

Debian 11

**Comment by curquiza** [comment]
Hello @speciale 
Thanks for this report

Could you please give more information about your machine? The OS (with its version) and the architecture?

**Comment by speciale** [comment]
My pleasure. Yep…
```

uname -a
	Linux DEBIAN-LS 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

lscpu

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           77
Model name:                      Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
Stepping:                        8
Frequency boost:                 enabled
CPU MHz:                         1500.060
CPU max MHz:                     2401.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4800.19
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled,
                                 RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat p
                                 se36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdt
                                 scp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology n
                                 onstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx
                                  est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadli
                                 ne_timer aes rdrand lahf_lm 3dnowprefetch cpuid_fault epb pti ibrs
                                 ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep er
                                 ms dtherm ida arat

```

**Comment by curquiza** [comment]
@speciale 
I did not succees to reproduce the issue on my debian machine

However, looks like you have permission issue, see your logs

>  Warning: Failed to create the file meilisearch-linux-amd64: Permission denied

You need to authorize the script to create file in your machine.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
