### ISSUE TITLE
Phrase search not return full-text when using japanese with number or with special character japanese

### ISSUE THREAD

**Issue by avganti1102** [meilisearch/meilisearch#3430]
**Describe the bug**
I have 2 cases where the results are incorrect when using phrase search

Case 1: Japanese with number
-> No response when search like that
-> When i add "." before a number
But for this case it will return to the case of searching 2-term search, not full-text

Case 2: Search with English, Japanese and special character Japanese

**Meilisearch version:** 
v0.29.1

Can someone help me to solve this problem or find solution to search by phrase :"<

**Comment by ManyTheFish** [comment]
Hello @avganti1102, 
For the first case, There is probably an issue with the tokenization.
For the second case, I don't really understand your issue, it seems that the phrase search works and found exactly the document. 🤔 

In any case, I see that you use an old version of Meilisearch, could you retry with version 1.0.1, please?

Thanks!
