### ISSUE TITLE
v1.0.0. client.get_keys() --> Error code: invalid_api_key 

### ISSUE THREAD

**Issue by marinaaaniram** [meilisearch/meilisearch#3473]
Hi!

I up the latest version (v1.0.0) in docker. Then I have to find out what my api_key is.
(use python meilisearch = "0.24.0")

I am calling:

```
import meilisearch    

client = meilisearch.Client(MEILI_ENDPOINT, MEILI_MASTER_KEY)
tasks = client.get_keys()
```

but I get an error:

`meilisearch.errors.MeiliSearchApiError: MeiliSearchApiError. Error code: invalid_api_key. Error message: The provided API key is invalid. Error documentation: https://docs.meilisearch.com/errors#invalid_api_key Error type: auth`

Vicious circle. To know my keys I need my keys 😑
When an error is in the master key, it is necessary to write that the error is in the master key. Otherwise everyone will waste a lot of time understanding

**Comment by curquiza** [comment]
Hello @marinaaaniram 
Sorry for the frustration you have

If you are looking for the master key, you don't have any endpoint in the API to know it, for security reasons. This is something you set up when running Meilisearch, so you are supposed to already know what your master key is. 

With the master key, you can call any endpoint of your Meilisearch instance, so probably the `MEILI_MASTER_KEY` you fill is not the correct one. 

⚠️ do not use master key everywhere when using Meilisearch in production; please use specific API keys you have to create. [This guide will explain better how to manage this](https://docs.meilisearch.com/learn/security/master_api_keys.html#protecting-a-meilisearch-instance)

Also, I see you call `get_tasks()` in your code -> you will not know what are your current API keys this way. You need to use the [`GET /keys`](https://docs.meilisearch.com/reference/api/keys.html#get-all-keys) (probably `get_keys()` with your SDK) and you will get all the setup API keys. Master key must be used to call this endpoint, for security reasons.

Hope it helps, let me know!

**Comment by marinaaaniram** [comment]
Sorry, I mean get_keys, of course (corrected my massage). 
But I tell about wrong message. You should say that the invalid_master_key, not invalid_api_key.

**Comment by curquiza** [comment]
The fact is you don't necessarily have to send a master key in this situation: you really send an API key and the master key is just a kind of API key. Here, in your case, you chose to use the master key, but it could have been another API key created with the [`keys.get` action](https://docs.meilisearch.com/reference/api/keys.html#actions) -> it's not the master key, but can access this route, so being invalid as well.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
