### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by liugang219890719** [meilisearch/meilisearch#3491]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Hello @liugang219890719 

Could you please give information about the panic you got?

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
