### ISSUE TITLE
Add a `Did you mean?` section to our error messages when possible

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3493]
Add a « Did you mean? » part in our error messages when a field or a value is miss-typed.

That was proposed in [this discussion](https://github.com/meilisearch/meilisearch/discussions/3154) initially.

**Comment by curquiza** [comment]
@irevoire can you list which routes and in which situation the "did you mean" can happen?

**Comment by irevoire** [comment]
Errm, to be honest, it's a bit hard.

It's automated, so it can happen on _all_ the route that takes a body or query parameters.

If we really want the list, I could probably generate it somehow, but I don't think it's relevant to anyone since it impacts 90% of the engine

**Comment by curquiza** [comment]
> It's automated, so it can happen on all the route that takes a body or query parameters.

Ok, this is the information I was missing. It's obvious for you, not for me, when I read the issue 😉
