### ISSUE TITLE
Not finding documents that has word occurring on both documents

### ISSUE THREAD

**Issue by mech** [meilisearch/MeiliSearch#3503]
**Describe the bug**
I have 2 documents and when I try to query one word from each document, only the first word will trigger document retrieval.

I am not sure if this is a fundamental understanding on my part on the relevant document, but I have asked around my colleague and all says the correct results should be both documents will display.

**Expected behavior**
When I query for `jet` and `Satellite` I am expecting 2 documents to be returned. 

**Screenshots**

<img width="949" alt="16vmp_16_35_16" src="https://user-images.githubusercontent.com/5850/219313872-f5187ed2-1bfd-42ab-82fb-20216b832901.png">

**Meilisearch version:** v1.0.1

**Comment by mech** [comment]
This might be my own misunderstanding of how searching is supposed to work in enterprise/elasticsearch/Algolia/Meilisearch vs the Google Public Internet way of searching.

Because when google, the result might be vast and it is showing all documents with "jet" word in it as well as with "satellite" word in it.

**Comment by curquiza** [comment]
Hello @mech 
The results you got are expected, it's not a bug 😊 

Indeed, Meilisearch does [prefix search](https://docs.meilisearch.com/learn/advanced/prefix.html#prefix-search), like Algolia.

It means, when you type "jets satellite" Meilisearch first tries to retrieve documents containing `jets` AND `satellite`, and then, documents with only `jets`. This is the behavior of one of the ranking rules: the [`word` ranking rules](https://docs.meilisearch.com/learn/core_concepts/relevancy.html#_1-words). Unfortunately, you cannot disable this behavior at the moment.

You can customize the relevancy in Meilisearch by using [`matchingStrategy` parameter](https://docs.meilisearch.com/reference/api/search.html#matching-strategy) during the search, but so far, you cannot ask for Meilisearch to retrieve all documents containing at least one word of each query word.
Pinging our product team @gmourier for your information 😇

**Comment by mech** [comment]
Want to ask further. The ordering is like so:

1. jets AND satellite (will find)
2. jets (will still find)
3. satellite and sequence wording (will no longer try to find)

The point 3, am I right?

**Comment by curquiza** [comment]
If you type `jets satellite`, yes. I'm not sure we are meaning the same thing for the third point, so let me give you a second example with 3 words.

If you type `Hello everyone here", Meilisearch will try to find
1. First, documents containing `hello` AND `everyone` AND `here`
2. Then, documents containing `hello` AND `everyone`
3. Finally documents containing `hello`

If you change `matchingStrategy` to `all` (default is `last` and leads to the behavior I described above) Meilisearch will only retrieve documents containing `hello` AND `everyone` AND `here`, nothing else.

**Comment by mech** [comment]
Tks @curquiza, now I can see why it is called prefix search 😀. Tks for the explanation.
