### ISSUE TITLE
Test the all features in the CI

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3506]
We have to test the `route_metrics.rs` with the correct feature flag. It doesn't compile, which has happened for a long time.

**Comment by curquiza** [comment]
Discussed with @Kerollmops -> the CI

**Comment by irevoire** [comment]
Also, we need to wait until https://github.com/meilisearch/meilisearch/pull/3496 is merged before implementing this issue

**Comment by jlucktay** [comment]
Hi there! 👋
I just started on a fork to add this new CI job, and will create a PR after making sure it runs correctly.

**Comment by curquiza** [comment]
Got it @irevoire!

And thank your @jlucktay for being volunteer!
