### ISSUE TITLE
Integrate Charabia 0.7.1

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#3513]
## Changes related to Chrabia impacting Meilisearch

* Reduce crate size (from ~200MB to ~50MB) by compressing dictionaries
* Enhance Greek support by normalizing diacritics and final sigma
* Enhance Arabic support by ignoring Tatweel

**Comment by curquiza** [comment]
Thanks @ManyTheFish for opening the issue

I ping @meilisearch/docs-team in case it interests you (let me know if not, I will remove the label in this case)
