### ISSUE TITLE
Experimental feature: Metrics

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3523]
All details are in: https://github.com/meilisearch/meilisearch/discussions/3518
Spec: https://github.com/meilisearch/specifications/pull/174

Get rid of the feature flags we had and provide the metrics route as a cli flag shipped by default in every executable.

## For the @meilisearch/docs-team 
I named the cli flag `--experimental-enable-metrics`.
That can change, obviously. Let me know if you would like to update it. The only constraint is that it **must** starts with `experimental`.

I also wrote a little description for the `--help`:
```
      --experimental-enable-metrics
          Experimental metrics feature. For more information, see: https://github.com/meilisearch/meilisearch/discussions/3518

          Enables the Prometheus metrics on the `GET /metrics` endpoint.

          [env: MEILI_EXPERIMENTAL_ENABLE_METRICS=]
```

Also, take care of documenting this sentence well:
> Provides access to `GET` `/metrics` route. **A restriction on `indexes` does not affect returned metrics.**

It means that someone who should only have access to one index will be able to see the metrics of **all** indexes, including the one he shouldn't know the existence of.

## Impacted teams

@meilisearch/integration-team @meilisearch/docs-team

**Comment by curquiza** [comment]
@irevoire can we link the discussion https://github.com/meilisearch/meilisearch/discussions/3518 when doing `meilisearch --help`? 😊

**Comment by irevoire** [comment]
Yep, that's what I showed in the initial message:
```
      --experimental-enable-metrics
          Experimental metrics feature. For more information, see: https://github.com/meilisearch/meilisearch/discussions/3518

          Enables the Prometheus metrics on the `GET /metrics` endpoint.

          [env: MEILI_EXPERIMENTAL_ENABLE_METRICS=]
```

**Comment by curquiza** [comment]
Oops, I missed this! thanks tamo 😇
