### ISSUE TITLE
Update the error code of the csv delimiter 

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3533]
According to the spec: https://github.com/meilisearch/specifications/pull/221

The initial error code that was decided has been changed from `invalid_index_csv_delimiter` to `invalid_document_csv_delimiter`.

Originally implemented in https://github.com/meilisearch/meilisearch/issues/3442

@meilisearch/docs-team @meilisearch/integration-team

**Comment by gmourier** [comment]
Thank you @irevoire! Sorry for the late feedback
