### ISSUE TITLE
Cache the result of the indexes stats 

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3540]
Since https://github.com/meilisearch/meilisearch/pull/3331 has been merged, we now have the possibility to store thousands of indexes in meilisearch.
But at the same time, opening indexes became slower.

That can be a real issue when calling the global `stats`.
And it will also degrade the usage of the new experimental `/metrics` route.

After chatting with @dureuill we decided it would be better to cache the result of the stats on disk to avoid opening the indexing just to extract a few information out of the index.

**Comment by gmourier** [comment]
Does the cache is invalidated as soon as an index operation impacts its stats number? Just wondering if the information is always up-to-date 🤓

**Comment by irevoire** [comment]
The cache is updated after any update is applied to an index. 
Thus it should always be up to date.

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3541
Will be released in rc1 today
