### ISSUE TITLE
Make the `proximity` ranking rule less precise

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3545]
An idea to (potentially significantly) reduce the size of the index and speed up indexing tasks: store a less precise proximity between words.

Currently, we index all pairs of words that are separated by either `0,1,2,3,4,5,6` words from each other. This is 7 proximities to keep track of. I’d like to investigate whether we could instead group some proximities together: `0, 1, (2+3), (4+5+6)`. This is now only 4 proximities to keep track of. The advantage is that the implementation of phrase search won’t be impacted, and we still distinguish between words that are very close to each other and those that are far from each other. But the real impact on relevancy and index size/indexing time need to be evaluated.

Furthermore, we also have other databases for backward proximities. That is, given the words hello world  in a document, we store:
- forward proximity: `hello world 0`
- backward proximity: `world hello 0`

We could consider being less precise in the backward proximity, for example by grouping the following proximities together: `(0+1), (2+3+4+5+6)`.
We also have the prefix proximities database, which currently store the proximities `0,1,2,3`. We could also consider grouping some proximities here: `(0+1), (2+3)`. And for the backward prefix proximity DB: `(0+1)`.

**Comment by curquiza** [comment]
The team think about better solutions than this one (like reducing the maximum proximity and changing the format of the database)
@Kerollmops will write a new issue related to these new solutions
