### ISSUE TITLE
Fix sentences errors

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#357]
@bidoubiwa Would it be possible to make sure to not introduce sentences mistakes next time you modify the README, please? 😃 It's also my bad, I did not spot it, though.

https://github.com/meilisearch/MeiliSearch/commit/387eb3fde30d5c61f22d89fc2135ed5265f8ba4f#diff-04c6e90faac2675aa89e2176d2eec7d8L26

https://github.com/meilisearch/MeiliSearch/commit/387eb3fde30d5c61f22d89fc2135ed5265f8ba4f#diff-04c6e90faac2675aa89e2176d2eec7d8R142

At the end of the sentences you wrote:
> and provides excellent great performances

Could you fix this please? 😄

**Comment by bidoubiwa** [comment]
Those are not my changes. But I could fix them yes.

**Comment by bidoubiwa** [comment]
#359

**Comment by Kerollmops** [comment]
Ho my bad! That was @tpayet, thank you anyway!
