### ISSUE TITLE
Troubles installing meilisearch via terminal

### ISSUE THREAD

**Issue by adelaineho** [meilisearch/meilisearch#3573]
**Describe the bug**
Not being able to install meilisearch
(Will try with github option)

**To Reproduce**
1. Go to Terminal
2. Entered `curl -L https://install.meilisearch.com | sh`
3. See error `ERROR: Impossible to get the latest stable version of Meilisearch.`

**Screenshots**
<img width="1470" alt="Screen Shot 2023-03-09 at 1 11 54 pm" src="https://user-images.githubusercontent.com/7259977/223897860-f41b73ca-2574-43c9-beb8-a6e0f6788c32.png">

**Additional context**
Additional information that may be relevant to the issue.
MBP macOS Monterey 12.3.1 - Apple M1 Max chip

**Comment by curquiza** [comment]
Hello @adelaineho,

Thanks for the report 🙏 

Can you do the following commands and let us know about the return?
- `mktemp -q /tmp/meilisearch.XXXXXXXXX`
- `uname -s`
- `uname -m`
- `curl --fail -OL "https://github.com/meilisearch/meilisearch/releases/download/v1.0.2/meilisearch-macos-apple-silicon  > test-meilisearch` -> should create a `test-meilisearch` file you can run
```bash
chmod +x meilisearch-macos-apple-silicon 
./meilisearch-macos-apple-silicon 
```
