### ISSUE TITLE
Compute the database size from all indexes in stats

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3578]
Currently, the database size returned by the `stats` route only considers the indexes authorized to the current tenant, effectively underestimating the space taken on disk if some indexes are unauthorized.

It might be preferable always to compute a database size taking into account the contribution of all indexes, regardless of authentication. This does not leak the names or contents of unauthorized indexes, but it can leak the fact they exist (if they are, e.g. taking a lot of disk space).

See https://github.com/meilisearch/meilisearch/pull/3541#discussion_r1126747643 for more context.

**Comment by dureuill** [comment]
Not sure if this affects docs or specs?

**Comment by curquiza** [comment]
In my opinion
- it does not impact the docs
- could be worth adding the precision to the spec

**Comment by curquiza** [comment]
Question: is this behavior already present in v1.0, or is it something we introduced in v1.1?

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/3541
Will be released in rc1 today
