### ISSUE TITLE
File takes up too much storage

### ISSUE THREAD

**Issue by Avey777** [meilisearch/meilisearch#3591]
On average, such a small json file requires about 15K storage space, and there is still a lot of room for improvement in Meilisearch's data compression. Normally such a small file is stored at around 2K.

Algolia does json twice this size, using an average of less than 1 KB of storage
![image](https://user-images.githubusercontent.com/35259040/225283493-c1516bff-dea7-45f4-a978-9af18c28c8c2.png)

**Comment by curquiza** [comment]
Hello @Avey777 

I'm not sure to understand. Which size of database would you expect by insert which dataset?

> Algolia does json twice this size, using an average of less than 1 KB of storage

I'm not sure to understand. Algolia is close-source, so the DB size is not a problem on user side. What do you mean by this?

**Comment by Avey777** [comment]
![Snipaste_2023-03-15_22-26-32](https://user-images.githubusercontent.com/35259040/225342258-0ae45ee4-7507-4d3c-8cda-a088b9c5b02c.png)

**Comment by Avey777** [comment]
![image](https://user-images.githubusercontent.com/35259040/225342997-5dd642c0-7612-4541-9834-c18bdf787a1f.png)

**Comment by curquiza** [comment]
On the Algolia dashboard, it's not the size of the DB, but the size of your record, so your data. Algolia is close source and does not display this information. I saw people answer the same as me on Discord (following your screenshot).

Anyway, I would love to know better about your need, I asked some questions in my previous message:

> I'm not sure to understand. Which size of database would you expect by importing which dataset?
> I need more information about what would be acceptable for you.

> What are the current issues you encounter with the Meilisearch database size?
