### ISSUE TITLE
Meilisearch Cloud Reset Password is 404-ing

### ISSUE THREAD

**Issue by benparsell** [meilisearch/meilisearch#3594]
**Describe the bug**
The Meilisearch Cloud platform seems to have a bug with resetting a password for an existing acount – it will throw a 404 error on form submission.

**To Reproduce**
1. Go to https://cloud.meilisearch.com/login 
2. Click on 'Forgotten Password'
3. Walk through process with existing account / email.
4. Click URL from Email with token appended
5. Error is thrown when entering new password

**Expected behavior**
I expect to be able to reset a password for an existing account

**Screenshots**
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/9341434/226061817-60935d77-5213-426f-8a1d-68a9b2609a70.png">
<img width="852" alt="image" src="https://user-images.githubusercontent.com/9341434/226061889-90126928-87c1-4438-8845-ae3163c38c39.png">

**Meilisearch version:** 
Meilisearch Cloud

**Additional context**
Additional information that may be relevant to the issue.
Attempting to do this from Chrome on Mac OS

**Comment by Kerollmops** [comment]
Hey @benparsell,

Sorry for the inconvenience. This bug was fixed an hour ago. You should be able to reset your password now.
I am closing this issue now but feel free to reopen it if you have any problems.

Have a nice day 🥛
