### ISSUE TITLE
Tasks filter does not works with the dump

### ISSUE THREAD

**Issue by irevoire** [meilisearch/MeiliSearch#3596]
**Describe the bug**
After importing a dump, trying to query the task via a date filter doesn't works.

**To Reproduce**
1. Import a dump
2. Query the tasks via a date filter
3. Find nothing

**Expected behavior**
It works

**Screenshots**

**Meilisearch version:** v1.0.2 & v1.1.0 & main branch
It has been present since v0.30

**Comment by curquiza** [comment]
Fixed by #3597 

Will be integrated into RC2 asap
