### ISSUE TITLE
Meilisearch throws error: [index_scheduler] Invalid argument (os error 22)

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#3598]
**Describe the bug**
I cannot say what triggered the error. I was running some tests that were previously working and suddenly this error popped.

**To Reproduce**
No idea

**Expected behavior**
No error

**Screenshots**
<img width="556" alt="Screenshot 2023-03-21 at 19 33 33" src="https://user-images.githubusercontent.com/33010418/226708485-7fa95c55-74cb-4230-8d90-e5b242a3574e.png">

**Meilisearch version:**
[v1.1.0-rc.1](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.0-rc.1)

**Additional context**
MacOS M1 ventura

**Comment by curquiza** [comment]
Hello @bidoubiwa 

Thanks for the report.
However, we really need more information to reproduce the bug otherwise it's just completely impossible to fix it.

Pinging @irevoire for your information

**Comment by bidoubiwa** [comment]
My Meilisearch instance kept running all day long. I run the test suite of meilisearch-js, instant-meilisearch, meilisearch-rust, multiple times. At one point, while running the test suite of meilisearch-js, absolutely all requests returned that error.

I'm sorry I cannot provide more information.

**Comment by irevoire** [comment]
If you still have your instance running, could you try to;
- Index a document
- Run a search
- Adds an API-key

And let us know which requests throw an error?

**Comment by bidoubiwa** [comment]
No bugs are thrown anymore. The error used to be thrown on all calls before I restarted the instance.
From as far as I can recall, it never happened before.

**Comment by bidoubiwa** [comment]
> Do you still have the logs above the first ERROR log? If so we could try to infer some context of what the instance was doing.



Unfortunately, my tests send a huge amount of requests. By the time I realized they were failing, the history of my terminal could not let me go back this far.

> Were you calling the stats route regularly ?

The stats route is used in my tests but is not called extensively. It's called maybe 10 times per test batch which takes 3 minutes to run completely.

> How many indexes are in your DB? 

On each test, the indexes are all deleted and re-created for the next tests. There are ~2000 tests in total. So the amount would be 0 at the end and 1 or 2 per test.

> Were you making requests on many indexes at once

The tests are sequential, and my requests are all waiting for MS to respond before making a new one. 

> Were you using the experimental metrics feature?

No!

**Comment by dureuill** [comment]
Sorry for double posting, but just linking https://github.com/meilisearch/heed/issues/135, which is the known source of `error 22` on macOS for now.

Should not be specific to v1.1 though.

Could maybe be fixed by taking on https://github.com/meilisearch/meilisearch/issues/3462

**Comment by dureuill** [comment]
Hello @bidoubiwa, this is triage, is this still current? If not, maybe we could close this issue?

**Comment by bidoubiwa** [comment]
I didn't experience this again, i'm closing it :)
