### ISSUE TITLE
Missing matched index information using `showMatchesPosition` on string arrays

### ISSUE THREAD

**Issue by Sofiman** [meilisearch/meilisearch#3609]
**Describe the bug**
It seems that there is no way of retrieving which array member matched within a string array field using `showMatchesPosition` as a search parameter. If a document has matched in an inner array member, only the matched range is returned without specifying which one matched.

**To Reproduce**
Small python script to reproduce the current behaviour:
```python
import meilisearch

client = meilisearch.Client('http://127.0.0.1:7700', 'dev')

index = client.index('test')

documents = [
      { 'id': 1, 'titles': ['First Title', 'Second Title Second'] }
]

index.wait_for_task(index.add_documents(documents).task_uid)

print(index.search('Second', { 'showMatchesPosition': True }))
```
Current behaviour using _"Second"_ as the query:
```json
{
    "hits": [{
        "id": 1, 
        "titles": ["First Title", "Second Title Second"], 
        "_matchesPosition": {
            "titles": [{
                "start": 0,
                "length": 6
            },
            {
                "start": 13,
                "length": 6
            }]
        }
    }],
   "query": "Second", 
   "processingTimeMs": 0, 
   "limit": 20, 
   "offset": 0, 
   "estimatedTotalHits": 1
}
```

**Expected behavior**
Not sure what is the better solution:
1. Add the matched index information in the matched key
```json
{
    "hits": [{
        "id": 1, 
        "titles": ["First Title", "Second Title"], 
        "_matchesPosition": {
            "titles[0]": {
                "start": 0,
                "length": 6
            }
        }
    }]
}
```
2. Add a child object containing matched indexes to the matched key
```json
{
    "hits": [{
        "id": 1, 
        "titles": ["First Title", "Second Title"], 
        "_matchesPosition": {
            "titles": {
                "0": {
                    "start": 0,
                    "length": 6
                }
            }
        }
    }]
}
```
3. Add a subarray containing matches for each child
```json
{
    "hits": [{
        "id": 1, 
        "titles": ["First Title", "Second Title"], 
        "_matchesPosition": {
            "titles": [
                null,
                [{
                    "start": 0,
                    "length": 6
                }]
            ]
        }
    }]
}
```
4. Other

**Meilisearch version:** 1.0.2

**Comment by amgadserry** [comment]
Having the same issue

**Comment by Sofiman** [comment]
Hi, it seems that the consideration has got not update since October 12 2023. Any update of that consideration or a new one would be great.

**Comment by curquiza** [comment]
Hello @Sofiman 
You indeed have a lot of feature requests to treat and implement, so we focus on the most requested ones.
This feature has not been requested by many users so far, so we spent our times on most demanded ones.
That's why having information about your usage (why you need it in your company? what do you expect from the feature?) definitely helps.

Thanks in advance for your help, I close this issue since everything is handled on the product side now 😊
