### ISSUE TITLE
Search in facet values

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3611]
Related product team resources: [roadmap card](https://www.notion.so/meilisearch/ef7d86c80ef44c549e2361c70a367723?v=d11906bcef8b4b77815f84b801931c00&p=cf423172ec454fd286bcaae62f4da9be&pm=s)  (_internal only_)
Related product discussion: 
- https://github.com/meilisearch/product/discussions/515

Related spec: WIP

## Motivation

When you have hundreds/thousands of different values for a given facet attribute, it’s impossible to display them all on a user interface. Searching for facet values allows users to search within a specific faceted field (for example, brands, authors, or categories) without creating a separate index.

## Usage

Refer to the final spec to know the details and the final decisions about the usage.

## TODO

- [ ] Release a prototype
- [ ] If prototype validated, merge changes into `main`
- [ ] Update the spec

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team

**Comment by curquiza** [comment]
Prototype available: https://github.com/meilisearch/product/discussions/515#discussioncomment-5730618

**Comment by curquiza** [comment]
Discussed with the team today, impossible to make it for v1.2, moving to v1.3
The search refactoring + un-anticipated issue with task DB made us slower, sorry for the inconvenience

**Comment by gillian-meilisearch** [comment]
Hello everyone 👋 

We have just released the first RC (release candidate) of Meilisearch containing this change!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.0
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
