### ISSUE TITLE
Exp - `CONTAINS` filter operator

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3613]
Related product team resources: [roadmap card](https://www.notion.so/meilisearch/ef7d86c80ef44c549e2361c70a367723?v=d11906bcef8b4b77815f84b801931c00&p=e7356b40249f4e41856faafc3ec57043&pm=s) (_internal only_)
Related product discussion: https://github.com/meilisearch/product/discussions/544

## Motivation

Not possible with Algolia or Typesense currently.

## Usage

Refer to the final spec to know the details and the final decisions about the usage.

Might be released as an experimental feature.

## TODO

- [x] create a product discussion to explain the usage

## Impacted teams

Might be released as an experimental feature.

@meilisearch/integration-team @meilisearch/docs-team

**Comment by curquiza** [comment]
Discussed with the team today, impossible to make it for v1.2
The search refactoring + un-anticipated issue with task DB made us slower, sorry for the inconvenience

**Comment by gillian-meilisearch** [comment]
Moving this out of the v1.3.0 plan as there are still some concerns to address. We aim to get this into a future release instead.

**Comment by irevoire** [comment]
The feature is finally ready to be merged as experimental 🎉 

Related PRD: (private link) https://www.notion.so/meilisearch/Contains-Like-Filter-Operator-0d8ad53c6761466f913432eb1d843f1e
Public usage page: https://meilisearch.notion.site/v1-10-AI-search-changes-737c9d7d010d4dd685582bf5dab579e2#ece824a1814e47a0a986d786baff1be9

**Comment by guimachiavelli** [comment]
I think the second link is wrong: I assume it should point to the public version of  https://www.notion.so/meilisearch/Contains-Like-Filter-Operator-0d8ad53c6761466f913432eb1d843f1e, but clicking it leads me to the public usage page for AI-powered search
