### ISSUE TITLE
Race condition can lead to multiple schema updates

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#364]
If multiple document additions are seen in a short time and no schema is present that could lead to multiple schema updates.

It is due to the fact that we check if we need to introduce a schema update when there is no schema.

https://github.com/meilisearch/MeiliSearch/blob/fc8182d7d355b6e9569aff8c05cc8d34ceb17356/meilisearch-http/src/routes/document.rs#L157-L166

To fix that we need to introduce a schema update in the update system, instead of the HTTP route itself.

**Comment by MarinPostma** [comment]
is that still a thing?

**Comment by Kerollmops** [comment]
I would say that is not relevant anymore as we have a schema update type in the update queue now!
