### ISSUE TITLE
Bad result in chinese from v1.1.1

### ISSUE THREAD

**Issue by garrydzeng** [meilisearch/meilisearch#3683]
**Describe the bug**
I have an index with `{"searchableAttributes":["name"]}`, when I search by `{"q":"张云"}` (`张云` is person name in Chinese), returns a lot of irrelevant results, such as:

```
[
  {"name":"张广伍"},
  {"name":"张建"},
  {"name":"钟俊生"},
  {"name":"高政"}
]
``` 
especially `钟俊生` and `高政`, they are last name isn't `张`. why they appear in the results? 

**To Reproduce**
1. Create an index and configure by `{"searchableAttributes":["name"]}`
2. Import data like `[{"name":"张云"},{"name":"张广伍"},{"name":"张建"},{"name":"钟俊生"},{"name":"高政"}]`
4. Search by `{"q":"张云"}`

**Expected behavior**
I think correct result is `{"name":"张云"}` only.

**Meilisearch version:**
v1.1.1

**Comment by spencerswagger** [comment]
@ManyTheFish 
Having better typo tolerance for Chinese is important, but we may need to disable it for certain indexes or attributes. For example, some users may want to search for someone by their exact name, so we need to be careful not to return too many records.

Another issue with Chinese searching without typo tolerance is that different Chinese characters can have the same pinyin. For instance, searching for `张芸` may also return hits for `张云`, even if typo tolerance is disabled.
(Both `云` and `芸` are pronounced as `yún`)
