### ISSUE TITLE
Handle single quotation mark (’) and apostrophe (') the same way.

### ISSUE THREAD

**Issue by oluademola** [meilisearch/meilisearch#3689]
**Describe the bug**
As reported by Mason, it seems that meilisearch doesn't handle the single quotation mark (’) as apostrophe (') in v1.x.x. It appears the same with v0.29 in my test, so I think this could have been introduced in v0.29 because they are both handled the same (as `'`) in v0.28. Cross posting initial issue by Mason on [Discord](https://discord.com/channels/1006923006964154428/1006923007559729154/1095376419372155034) below:

> So we have an issue in both 1.1.0 and 1.0.2 (both instances in Meilisearch Cloud) where apostrophes (’) in queries are not treated as single quotes ('). This means that uses on iOS whose keyboards will default to an apostrophe get much worse results than users on desktop who use single quote, especially for common English-language contractions like I'm. This seems like the incorrect behavior. We can work around this with the synonyms settings for contractions like you're, but for possessive words there isn't a clear way to solve this via config, like with the book Ender's Game. We can replace apostrophes on the fly in the query before sending it the Meilisearch endpoint, but I wanted to bring this up here since this is such a common problem

**To Reproduce**
1. Index documents containing single quotation mark (’) and apostrophe ('). 
2. Search on the index. Words with single quotation marks (’) are not normalized to apostrophes ('). 

**Expected behavior**
Meilisearch should normalize single quotation mark (’) to apostrophe (') and handle both the same so they can be used interchangeably. 

**Meilisearch version:**
v1.x.x

**Comment by curquiza** [comment]
Invoking @ManyTheFish to have more input 🧞 Could be a `good first issue`
Also pinging @Kerollmops for you information

**Comment by mason-stewart** [comment]
Hi @ManyTheFish thanks for patching this, I was the original reporter in Discord. Sorry I didn't comment before the PR was merged, but I did want to point out that double quotes have the exact same issue for users using iOS us-en keyboards. We've patched this with JS in the mean time, and ended up handling single and double quotes like this (in JS):

```js
export function standardizePunctuation(query) {
  // replace apostrophe and quote variations(‘’ and “”) with ' and " 
  return query.replace(/\u2018|\u2019/g, '\u0027').replace(/\u201C|\u201D/g, '\u0022');
}```

This ends up impacting exact search negatively, specifically. Thank you!

**Comment by mason-stewart** [comment]
I should also point out that 0.28 did not treat `“gideon the ninth”` as `"gideon the ninth"`, so I doubt the is the same regression as we had with single quotes, but it is a subtle point that should probably be addressed. If a user uses quote search on iOS (or any keyboard that defaults to `“”` for double quotes), exact match quote search will not work. Currently it's up the client to convert these characters, but that seems like a bug?

**Comment by ManyTheFish** [comment]
Hello @mason-stewart, indeed it's interesting to know it.

Could you please create another bug report with the double quote please? This will allow us to close this issue and resolve the new issue with another PR.

Thank you for your report!
