### ISSUE TITLE
Need a `format checker` for rust code.

### ISSUE THREAD

**Issue by ArshErgon** [meilisearch/meilisearch#3700]
As I was going through some active PR I saw in some files there are unformatted code, its not making a difference but it can improve the readability of the codebase.

**Comment by curquiza** [comment]
Hello @ArshErgon 

We already use Rust fmt in our CI -> https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/test-suite.yml#L153

And we also have a configuration file for it -> https://github.com/meilisearch/meilisearch/blob/main/.rustfmt.toml

Maybe is there some pattern you saw that shouldn't be accepted by Rustfmt? Can you precise a little bite what you thought about? 😊 

In any case, feel free to do a suggestion to improve our format checker, the tech team will review and consider your suggestions.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
