### ISSUE TITLE
Error running meilisearch on Termux (aarch64)

### ISSUE THREAD

**Issue by scrazzz** [meilisearch/meilisearch#3707]
**Describe the bug**
I'm getting the following error when running meilisearch on Termux (aarch64).

Error:
```console
bash: ./meilisearch-linux-aarch64.bin: cannot execute: required file not found
```

**To Reproduce**
1. Install the latest `aarch64` version from [GitHub release](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.1).
2. Run: `chmod +x meilisearch-linux-aarch64.bin`
3. Execute: `./meilisearch-linux-aarch64.bin`
4. See above error

**Expected behavior**
The program to run normally as intended.

**Screenshots**
N/A

**Meilisearch version:**
I installed `v1.1.1` from [GitHub releases](https://github.com/meilisearch/meilisearch/releases/tag/v1.1.1).

**Additional context**
I'm running this on an aarch64 device, Android 11.

**Comment by scrazzz** [comment]
Okay so I had to edit [this line](https://github.com/meilisearch/meilisearch/blob/414b3fae89428e453e738ba0e7b93cea846e8839/download-latest.sh#L27) and change the path of the temp directory which fixed the issue downloading issue.


But now after the installation is complete, and I run `./meilisearch`, I get this error:
```console
bash: ./meilisearch: cannot execute: required file not found
```

Googling this error tells me to use `dos2unix` to fix the file but since this is a compiled binary file it won't fix itself.
```console
$ dos2unix meilisearch
dos2unix: Binary symbol 0x02 found at line 1
dos2unix: Skipping binary file meilisearch
```

**Comment by scrazzz** [comment]
> I may be wrong but It's possible that certain Linux binaries may not run on Termux due to differences in compilation.

Yes, you are right. https://wiki.termux.com/wiki/Differences_from_Linux

I guess I'll close this issue.

**Comment by Happiness777** [comment]
> I was unable to replicate the issue on Ubuntu aarch64

I have a guess about why it doesn't work. Android uses different (bionic) libc, while usual Linux uses glibc, and because of that, the linking is messed up on Android and it can't run the executable.

I'm going to test (try to compile) it a bit later and tell you the results.

**Comment by Happiness777** [comment]
As I've thought, it's the glibc linking issue. I've successfully ran it with grun (glibc for termux)
![Screenshot_2023-08-07-02-33-38-254_com termux](https://github.com/meilisearch/meilisearch/assets/35190676/21875b00-ca15-4a02-b4a7-06ce02d341f7)

**Comment by Happiness777** [comment]
Works fine after compiling it in termux
![Screenshot_2023-08-07-03-20-08-947_com termux](https://github.com/meilisearch/meilisearch/assets/35190676/dd911ae1-1bc6-4e56-be08-e5d111b4660b)

**Comment by scrazzz** [comment]
Nice!
