### ISSUE TITLE
404 Error from README

### ISSUE THREAD

**Issue by brandondrew** [meilisearch/meilisearch#3708]
**Describe the bug**
The link to your SDKs in the README returns a 404 Not Found error.

**To Reproduce**

1. Open the Meilisearch project on GitHub 
2. Scroll down in the README to the SDKs
3. Click the link, opening https://meilisearch.com/docs/learn/what_is_meilisearch/sdks.html
4. Note that you get a 404 instead

**Expected behavior**
A list of SDKs

**Screenshots**

<img width="687" alt="image" src="https://user-images.githubusercontent.com/9854/235030053-1fd9aeea-d891-4469-b460-eea13b1b8985.png">

**Comment by Kerollmops** [comment]
Thank you for the report @brandondrew, I made a fix, and it will be merged soon 😊
