### ISSUE TITLE
Meilisearch Instance ran without master key or authentication is asking for Authentication header.

### ISSUE THREAD

**Issue by coolb0y** [meilisearch/meilisearch#3713]
**Describe the bug**
I ran meilisearch instance with windows binary file no key provided just double click on binary. Operating system windows 10 a RDP machine.
When I run command like
` curl -XGET http://localhost:7700/indexes/index22`  It should provide me the result but instead it shows error 
`{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}`

If I start instance instance with --master-key option and then do curl with authentication it still shows error of wrong api key event if I put the currect api keys.(I have put api key in image please don't mind them I won't use them in production )

**To Reproduce**
1. Download the binary file for windows which is 1.1.1 . 
2. Run it. You can see information like it is development mode and warning as well that no materkey is provided.

**Expected behavior**
When I run command like
` curl -XGET http://localhost:7700/indexes/index22`  It should provide me the result but instead it shows error 
`{"message":"The Authorization header is missing. It must use the bearer authorization method.","code":"missing_authorization_header","type":"auth","link":"https://docs.meilisearch.com/errors#missing_authorization_header"}`

**Screenshots**
I have attached the screenshot for both of the issue.
![meilisearchrdperror](https://user-images.githubusercontent.com/57170752/235379064-221dbc1a-d12e-4525-9f52-5085aecb229d.png)
![meilisearchautherror](https://user-images.githubusercontent.com/57170752/235379076-6b0a7bc8-f2fd-491e-9423-c247f2fd4368.png)

**Meilisearch version:**
v1.1.1

**Additional context**
Windows 10 , azure RDP machine . 
Thank You in Advance

**Comment by coolb0y** [comment]
I am able to make it work . Start meilisearch instance with command after moving to directory which contain meilisearch.
`meilisearch --env  development`  . This start instance without any authentication in development mode.

**Comment by oluademola** [comment]
Hello @coolb0y. I encountered the same problem on my Windows 11 machine, which was described in this [bug report](https://github.com/meilisearch/meilisearch/issues/3733). I'm curious to know how the "--env development" flag fixed the issue for you. It's strange because it didn't work for me, and I'm not sure if this problem is specific to a particular Windows version. Could you please clarify? Appreciate the help 🙏
