### ISSUE TITLE
the meiliseach from dart dose not allow inserting elements with spaces?

### ISSUE THREAD

**Issue by Vildnex** [meilisearch/meilisearch#3719]
**Describe the bug**
The meiliseach version 11.1 from [Dart](https://pub.dev/packages/meilisearch) dose not allow entries with "space" between words.

**To Reproduce**
**DART CODE:**
```
import 'package:meilisearch/meilisearch.dart';

void main() async {
  var meiliseach = new MeiliSearchClient("http://172.18.0.3:7700");
  var o = await meiliseach.index("movies3").addDocuments([
    {"test_uuid": "Miss Piper", "some": "AAAA", "name": "vasile"}
  ]);
  print("UID: " + o.uid);
}
```
This code is going to spring UID been 1 (the first insert), but when I am going to http://172.18.0.3:7700 I am not able to see any new document been inserted. But if, instead of **test_uuid** which is "Miss Piper" I will use just "Miss" everything is going to work as expected, and I will see my document to my local dashboard. But this will show the UID been 2 (which based on my understanding means that the other document was inserted somehow but is not displayed...

**Expected behavior**
I would expect in both of these cases to insert my document, without any matter whether or not the name is "Miss Piper" or "Miss".

**Meilisearch version:**
Meilisearch: 1.1.1

**Additional context**
Additional information that may be relevant to the issue.
OS: Linux

**Comment by Vildnex** [comment]
UPDATE:

Als this code:
```
import 'package:meilisearch/meilisearch.dart';

void main() async {
  var meiliseach = new MeiliSearchClient("http://172.18.0.3:7700");
  var o = await meiliseach.index("movies3").addDocuments([
    {"test_uuid": "Miss Piper", "some": "AAAA", "name": "vasile"}
  ]);
  //do a search
  var search = await meiliseach.index("movies3").search("Miss");
  int a=1;
}

```

The insertion of that document does not give any error but the search is not going to give me that result either.

**Comment by oluademola** [comment]
Hello @Vildnex. If you don't see results for the newly inserted document, I think there is a great chance the documentAdditionOrUpdate task was still in the queue when you made the search request. Did you check the [task object ](https://www.meilisearch.com/docs/reference/api/tasks#task-object)to double-check if this task was completed before searching for the document?

**Comment by Vildnex** [comment]
I see, you were right, that was the problem, I was expecting to either meiliseach create an internal id automaticly if I want provide one, or to give me an exception when running the program. That's why I was consfuse, thanks for clarifing this ;)
