### ISSUE TITLE
Include current payload size limit in the payload_too_large error

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/meilisearch#3736]
# Description
Following a discussion we had [in the cloud repository](https://github.com/meilisearch/meilisearch-cloud/issues/2466), we would like to start using the `MEILI_HTTP_PAYLOAD_SIZE_LIMIT` [environment variable](https://www.meilisearch.com/docs/learn/configuration/instance_options#payload-limit-size) and would need a way to provide to the user the current payload size limit [in the error returned by Meilisearch](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#payload_too_large) `payload_too_large`.

# Expected result

It should be a `413 Payload Too Large` from [what is specified in the specs.](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#payload_too_large)

Update the message to specify the current payload size limit. Example:
```json
{
    "message": "The provided payload reached the size limit. The maximum accepted payload size is :payloadSizeInHumanReadableFormat",
    "code": "payload_too_large",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#payload_too_large"
}
```

**Comment by curquiza** [comment]
Fixed by #3739 
Will be present in v1.2.0-rc.1, and in the official v1.2.0 on the 5th of June
