### ISSUE TITLE
Add a cron test when `all-tokenization` is disabled

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3743]
To avoid having this issue again (https://github.com/meilisearch/meilisearch/pull/3687), we would like to add a test in our CI running every week.

A new job should be created into this file: https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/test-suite.yml
The name of the job should be `test-disabled-tokenization`.
This job should only run for the event `schedule`.
The following command should be done, in two separated steps:
```bash
cargo tree -f '{p} {f}' -e normal --no-default-features | grep lindera -vqz
```
and then
```bash
cargo tree -f '{p} {f}' -e normal | grep lindera -qz
```

You can take inspiration from this already existing cron test job: https://github.com/meilisearch/meilisearch/blob/918ce1dd674f99a41545c50272507a275ca53baf/.github/workflows/test-suite.yml#L80-L106

**Comment by gentcys** [comment]
Hi @curquiza may I put my hand on this ticket?

**Comment by curquiza** [comment]
Hello @gentcys 
Sorry for the mistake on my side, this issue is done by https://github.com/meilisearch/meilisearch/pull/3779
I forgot to link the PR to this issue. Closing this then, and thanks @gentcys anyway for your involvement.
