### ISSUE TITLE
MEILI-RC Wrong error code returned

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3753]
**Describe the bug**
When trying to delete documents by a filter, if everything is well-formed except the attribute is not filterable. The « original » error code coming from milli stays `invalid_search_filter`; we should patch it.

I think there is already a test for this specific case; I just wrote so many tests at once that I didn't realize it was wrong.

**Meilisearch version:**
latest rc

This was introduced by this release

**Comment by curquiza** [comment]
Fixed by #3759
will be released in rc1 during this week
