### ISSUE TITLE
v1.2.0rc.1: Error code inconsistency

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#3770]
There are two new errors introduced in the new release (v1.2).
* invalid_document_filter
* invalid_document_delete_filter

`invalid_document_delete_filter` is triggered whenever `filter` is null for example on the delete document route.
`invalid_document_filter` is triggered when the filter does not work. For example if my filter is `id = 1`, but `id` is not filterable, than this error occurs.

The issue is that `invalid_document_filter` is triggered on the delete documents route in the second case. Should it not be `invalid_document_delete_filter`

example where `id` is not filterable. The error code is `invalid_document_filter`.

``` let mut query = DocumentDeletionQuery::new(&index);
        query.with_filter("id = 1");
        let error = index
            .delete_documents_with(&query)
            .await?
            .wait_for_completion(&client, None, None)
            .await?;

        let error = error.unwrap_failure();

        assert!(matches!(
            error,
            MeilisearchError {
                error_code: ErrorCode::InvalidDocumentFilter,
                error_type: ErrorType::InvalidRequest,
                ..
            }
        ));```

**Comment by curquiza** [comment]
Thank you @bidoubiwa for your report 🙏  We fix this this week and will release it as soon as possible.

**Comment by irevoire** [comment]
Superseded by https://github.com/meilisearch/meilisearch/issues/3774
