### ISSUE TITLE
`frequency` matchingStrategy

### ISSUE THREAD

**Issue by gillian-meilisearch** [meilisearch/meilisearch#3773]
Related product team resources: https://www.notion.so/meilisearch/Frequency-Matching-Strategy-0f3ba08833a442a39590a53a1505ab00?pvs=25

## Motivation

Improve relevancy for documents where terms are often repeated. 

Example: In e-commerce sites, item descriptions for similar items are often templated, which means the same description terms might be identical for a large number of items. This makes it harder to find relevant documents due to the frequency of the repeated terms. By removing the most common term within the dataset, relevancy is optimized.

## Usage

Reduce friction when it comes to fine-tuning search relevancy by adding a new matching strategy that removes the search terms most frequently found from the index’s documents.

https://meilisearch.notion.site/frequency-matchingStrategy-usage-f669fcc5d71e4f438d2a07cf94e9885a

### Reminders when modifying the Setting API

- [ ] Ensure the new setting route is at least tested by the [`test_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/tests/settings/get_settings.rs#L276)
- [ ] Ensure Analytics are fully implemented
  - [ ] `/settings/my-new-setting` configurated in the [`make_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L141-L165)
  - [ ] global `/settings` route configurated in the [`update_all` function](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L655-L751)
- [ ] Ensure the dump serializing is consistent with the `/settings` route serializing, e.g., enums case can be different (`camelCase` in route and `PascalCase` in the dump)

#### Special cases when adding a setting for an experimental feature

- [ ] ⚠️ API stability: The setting does not appear on the main settings route when the feature has never been enabled (e.g. mark it `Unset` when returned from the index in this situation. See [an example](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch-types/src/settings.rs#L608))
- [ ] The setting cannot be set when the feature is disabled, either by the main settings route or the subroute (see [`validate_settings` function](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch/src/routes/indexes/settings.rs#L811))
- [ ] If possible, the setting is reset when the feature is disabled (hard if it requires reindexing)

## Impacted teams
 @meilisearch/docs-team @meilisearch/integration-team

**Comment by curquiza** [comment]
Back to v1.9 🎉
