### ISSUE TITLE
[API] Health routes question

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#379]
In the [route file](https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/src/routes/mod.rs):
```rust
// Private
    app.at("").nest(|router| {
        router
            .at("/health")
            .get(health::get_health)
            .post(health::set_healthy)
            .put(health::change_healthyness)
            .delete(health::set_unhealthy);
```
Do all these routes are necessary?
I say that only because we need to document them, so I want to know if we are going to keep all of them before doing it. 
Currently only `get` and `post` routes are documented.

Or maybe did we plan to delete all these routes because I can see the little `// Private` comment above them? :)

**Comment by qdequele** [comment]
We can only keep the routes `get` and `put`, what do you think about that?

**Comment by curquiza** [comment]
I agree with you, only these both (`get` and `put`) are useful in my point of view.

**Comment by bidoubiwa** [comment]
Documentation already up to date
