### ISSUE TITLE
Meili filtering in wrong order for attribute search

### ISSUE THREAD

**Issue by waffshappen** [meilisearch/meilisearch#3793]
Meilisearch returns results that do not make sense to me when considering the ordering i gave it.

**To Reproduce**

With meilisearch-php (latest 1.x, latest meilisearch 1.1.1) i am creating the following index:
```php
$test = $client->index('test');
$test->updateSettings([
    'rankingRules' => [
	    'attribute',
	    'search_order:desc',
	    /*'words',
	    'proximity',
	    'sort',
	    'exactness',
	    'typo',*/
    ],
    'searchableAttributes' => [
	    'title',
	    'description',
    ],
    'displayedAttributes' => [
	    'id',
	    'title',
	    'description',
	    'search_order'
    ],
    'filterableAttributes' => [
	    'search_order'
    ],
]);

$client->updateIndex('test', ['primaryKey' => 'id']);

$test->addDocuments([
    [
	    'id' => 1,
	    'title' => 'Example Lower Rank',
	    'description' => 'Meili Description',
	    'search_order' => 10
    ],
    [
	    'id' => 2,
	    'title' => 'Example Meili normal Rank',
	    'description' => 'Example Description',
	    'search_order' => 20
    ],
    [
	    'id' => 3,
	    'title' => 'Meili Example normal Rank',
	    'description' => 'Example Description',
	    'search_order' => 20
    ],
    [
	    'id' => 4,
	    'title' => 'Example normal Rank',
	    'description' => 'Example Description',
	    'search_order' => 20
    ],
    [
	    'id' => 5,
	    'title' => 'Meili Example highest Rank',
	    'description' => 'Example Description',
	    'search_order' => 30
    ],
    [
	    'id' => 6,
	    'title' => 'Meili highest Rank Example',
	    'description' => 'Meili Description',
	    'search_order' => 30
    ],
    [
	    'id' => 7,
	    'title' => 'Example Meili highest Rank',
	    'description' => 'Meili Description',
	    'search_order' => 30
    ]
]);
```

And then search in the dashboard for "Meili" (same behaviour with the instantsearch clients)

**Expected behavior**
Given the ordering is 
```
attribute
search_order:desc
```

I expect the search for "Meili" to return
[2,3,5,6,7] in some order later determined by other factors later in the order
Then [1]
And [4] should not be found
Given this specific case of search_order:desc it should be

[5, 6, 7] in whatever order (to be determined later) - match title, highest search order
[2,3] (title matches, search_order lower)
[1] (description only, lowest search_order)

Instead Meilisearch returns
5
6
3 (?) - has title match but search_order is way lower
7 (?) - it matches the title and description and has a higher search order. 
2
1

I could understand it returning title+description match first, then title, then description.
(So [6, 7] 5,3,2,1 ) 

I would want it to return "has title match", then "has description match" and then sort the output of those based on the next tiebreakers.

But the above order indicates that attributes by itself already orders by word proximity or if it appears first internally which is the exact opposite of what i expect. This makes attribute ordering useless for me and i have to move it basically to the end or remove it entirely. But doing so also significantly lowers the quality of the results.

**Meilisearch version:**
1.1.1

**Additional context**
Fedora Linux 38, podman container, Firefox latest.

**Comment by oluademola** [comment]
Hello @waffshappen. Thank you for the report. But I would like to clarify this isn't a bug. I do understand your pain point, and you can start a product discussion in this [repo](https://github.com/meilisearch/product/discussions) to discuss further the limitation of the current relevancy settings and your use case. There isn't an easy way to do the exact relevancy settings you want because the current behavior considers documents with attributes starting with the query "Meili" more relevant than other positions with the attribute criterion. However, I found better results with the latest version [v1.2](https://github.com/meilisearch/meilisearch/releases/tag/v1.2.0), and the order of the result is as follows with the same settings: [5, 6, 7, 3, 2, 1]

**Comment by gillian-meilisearch** [comment]
Closing this issue out due to inactivity. Further discussion may take place on the product discussion side as mentioned above. Feel free to re-open if there is more to report here.
