### ISSUE TITLE
Latest RC release uses a different tag format

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch#3797]
**Describe the bug**
The v1.2.0 RC4 release has a different tag format than the other releases (`v1.2.0-rc4` vs `v1.2.0-rc.4`). Will this new format be used going forward? I noticed this because when updating my CI for testing the RC it failed to download Meilisearch from docker. Not a big deal either way, I just want to check if I should start expecting the new `rc4` format instead of the `rc.4` format.

**To Reproduce**
1. `docker pull getmeili/meilisearch:v1.2.0-rc.4`

**Expected behavior**
Download from docker hub failed

**Screenshots**

**Meilisearch version:**
v1.2.0 RC 4

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by gillian-meilisearch** [comment]
@sanders41 thanks for highlighting this. No, there is no intention to change the format, it was a just typo on my part. I'll fix this up now

**Comment by gillian-meilisearch** [comment]
That tag has been updated on the release and the new job has kicked off. Once that finishes we'll do final clean up and should be good to go. Thanks again @sanders41 for pointing this out and sorry for any inconvenience caused 🙏

**Comment by gillian-meilisearch** [comment]
This job has finished and the tag has been fixed up to the previous format. All clean up should be complete. Please let us know if there are any further issues. Thanks!
