### ISSUE TITLE
An unexpected crash occurred when processing the task.

### ISSUE THREAD

**Issue by copylian123** [meilisearch/meilisearch#3800]
{
    "uid": 144,
    "indexUid": "movies",
    "status": "failed",
    "type": "settingsUpdate",
    "canceledBy": null,
    "details": {
        "filterableAttributes": [
            "genres",
            "id"
        ]
    },
    "error": {
        "message": "An unexpected crash occurred when processing the task.",
        "code": "internal",
        "type": "internal",
        "link": "https://docs.meilisearch.com/errors#internal"
    },
    "duration": "PT1.028991200S",
    "enqueuedAt": "2023-06-01T05:52:29.3929104Z",
    "startedAt": "2023-06-01T05:52:29.3936727Z",
    "finishedAt": "2023-06-01T05:52:30.4226639Z"
}

**Comment by gillian-meilisearch** [comment]
Hi @copylian123 thanks so much for reporting this 🙏  Can I ask for some additional information please to help us get to the bottom of it? 
- In which version of Meilisearch did this occur for you?
- Could you provide some more detailed steps on how we could reproduce this, please? Any additional information you can share would be super useful.

**Comment by oulover** [comment]
This problem occurs again:

**Comment by oulover** [comment]
This problem occurs again:
env : win10    64
version: 1.33 
https://www.meilisearch.com/docs/learn/getting_started/quick_start
step reference:  https://www.meilisearch.com/docs/learn/getting_started/quick_start
1.download :  https://github.com/meilisearch/meilisearch/releases/download/v1.3.3/meilisearch-windows-amd64.exe
2.download :  https://www.meilisearch.com/movies.json
3.cmd  run: meilisearch-windows-amd64.exe
4.http request : post : http://localhost:7700/indexes/movies/documents?primaryKey=id 
   response :{
    "taskUid": 0,
    "indexUid": "movies",
    "status": "enqueued",
    "type": "documentAdditionOrUpdate",
    "enqueuedAt": "2023-09-11T08:14:08.813747Z"
}
5.http request : get: http://localhost:7700/tasks/0
   response :{
    "uid": 0,
    "indexUid": "movies",
    "status": "failed",
    "type": "documentAdditionOrUpdate",
    "canceledBy": null,
    "details": {
        "receivedDocuments": 31944,
        "indexedDocuments": 0
    },
    "error": {
        "message": "An unexpected crash occurred when processing the task.",
        "code": "internal",
        "type": "internal",
        "link": "https://docs.meilisearch.com/errors#internal"
    },
    "duration": "PT0.011174800S",
    "enqueuedAt": "2023-09-11T07:48:30.6646353Z",
    "startedAt": "2023-09-11T07:48:30.6654939Z",
    "finishedAt": "2023-09-11T07:48:30.6766687Z"
}
![image](https://github.com/meilisearch/meilisearch/assets/61042846/572f3e89-685f-46c0-b937-9a5fe80e8230)

**Comment by ahmednfwela** [comment]
@oulover try running meilisearch with `./meilisearch-windows-amd64.exe --max-indexing-memory 0`
