### ISSUE TITLE
no_space_left_on_device

### ISSUE THREAD

**Issue by yongheng0911** [meilisearch/meilisearch#3801]
**Describe the bug**
unaccepted status code found: 422 expected: [202], MeilisearchApiError Message: Meilisearch cannot receive write operations because the limit of the task database has been reached. Please delete tasks to continue performing write operations., Code: no_space_left_on_device, Type: system, Link: https://docs.meilisearch.com/errors#no_space_left_on_device (path "POST /indexes/jishuwz/documents" with method "AddDocuments")

**Screenshots**
![2BZ@3_746EA1WNAJ_Q G9CH](https://github.com/meilisearch/meilisearch/assets/127751358/51b9865f-2095-41a6-a44e-4abe6e1cacf6)

**Meilisearch version:**
[e.g. v1.1.1]

**Comment by yongheng0911** [comment]
First the disk ran out, then it was cleaned up, and it still couldn't be stored

**Comment by yongheng0911** [comment]
Always be 20  GetTasks

**Comment by yongheng0911** [comment]
![image](https://github.com/meilisearch/meilisearch/assets/127751358/890f7e1b-0d58-49d2-8699-ccb10ad4cc3b)
I finally figured out that's what's causing it

**Comment by gillian-meilisearch** [comment]
Hi @yongheng0911 that's great 🎉 I'm delighted to see you figured it out. I'm not sure I fully understand how you got there 🤔 would you mind expanding/explaining further? Just for information purposes, if you have time.

Thanks!

Gillian
