### ISSUE TITLE
Wrong analytics properties

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3814]
**Describe the bug**
A few properties don't have the expected name.
When sending the total number of times we've seen a specific event, we don't send the right name for the:
- documentFetchAggregator (introduced in v1.2)
- documentDeleteAggregator (introduced in v1.2)
- healthSeenAggregator (introduced in v1.1)

This bug isn't exposed to the end users

**Comment by dureuill** [comment]
Resolved by #3877
