### ISSUE TITLE
Phrase search doesn't return all document that matches the query

### ISSUE THREAD

**Issue by oluademola** [meilisearch/meilisearch#3815]
**Describe the bug**
Phrase search doesn't return all document that matches the query.

**To Reproduce**
1. Index the doc sample in this [discussion](https://github.com/meilisearch/meilisearch/discussions/3704)
2. Normal search returns both documents that match the search term
3. Phrase search doesn't return all documents that match the search term. 

**Expected behavior**
All documents with the matching search term or query should be returned. Also, highlighting is inconsistent for example the arrow-pointed term is even seen as a complete match. In v1.2 it's more inconsistent. 

**Screenshots**
<img width="1302" alt="Screenshot 2023-05-24 at 23 10 38" src="https://github.com/meilisearch/meilisearch/assets/101267639/4ab189e4-8bfb-4162-b443-66acaa7a12b2">

<img width="1360" alt="Screenshot 2023-05-24 at 23 16 16" src="https://github.com/meilisearch/meilisearch/assets/101267639/4476e624-4591-466b-9a29-af0c455e1a99">

![Screenshot 2023-06-06 at 12 51 27](https://github.com/meilisearch/meilisearch/assets/101267639/a6df8463-26df-4529-99aa-09d70c793179)

**Meilisearch version:** v1.1.1 and v1.2

**Comment by gillian-meilisearch** [comment]
thanks for reporting this @oluademola 🙏🏻  I've just discussed with @macraig and we'd like to fix it up for the next version

**Comment by dureuill** [comment]
Hello @oluademola and @gillian-meilisearch  :wave:

reproduced this on my end, and reduced it to a behavior in `charabia` where it is tokenizing the first number it encounters as its own token if the text starts with a number, but includes any trailing text otherwise.

```
"aaa bbb ccc" is tokenized as ["aaa", " ", "bbb", " ", "ccc"]
"10a 10b 10c" is tokenized as ["10", "a", " ", "10b", " ", "10c"]
"aaa 10b 10c" is tokenized as ["aaa", " ", "10b", " ", "10c"]
```


<details>
<summary>
cargo script
</summary>

```rust
//! cargo script, save as `charabia-numtoken.rs`,
//! then run with `cargo +nightly -Zscript charabia-numtoken.rs`
//!
//! ```cargo
//! package.edition = "2021"
//! [dependencies]
//! charabia = "0.7.2"
//! ```

fn print_tokenized(text: &str) {
    let words: Vec<_> = charabia::TokenizerBuilder::default()
        .build()
        .tokenize(text)
        .map(|token| token.lemma().to_string())
        .collect();
    println!("\"{text}\" is tokenized as {words:?}");
}

fn main() {
    print_tokenized("aaa bbb ccc");
    print_tokenized("10a 10b 10c");
    print_tokenized("aaa 10b 10c");
}
```
</details>

**Comment by gillian-meilisearch** [comment]
Hello everyone 👋 

We have just released the first RC (release candidate) of Meilisearch containing this fix!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.0
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
