### ISSUE TITLE
Incorrect deletion of documents when using the `disableOnAttributes` typo setting

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3816]
To reproduce, on Meilisearch v1.2.0 (and earlier versions):

Set the searchable attributes to `[text, exact]`
Set the `disableOnAttributes` to: `[exact]`

Add the following documents:
```
    { id: 0, text: "hello" }
    { id: 1, exact: "hello" }
```

Delete the document with the external id `1` (make sure to disable soft deletion).

The remaining documents are correct:
```
    { id: 0, text: "hello" }
```

But the `words_fst` structure in the index was incorrectly updated. It does not contain `hello` anymore.
As a result, if we now search for `hello`, we get zero results.

**Comment by curquiza** [comment]
Also reduce size of the index https://github.com/meilisearch/meilisearch/pull/3819#issuecomment-1580321320
