### ISSUE TITLE
Meilisearch is no more able to return split words

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3818]
In the previous version of Meilisearch, camelCasing wasn't supported and therefore words like _DeLonghi_ were not split. In this new v1.2 version we introduced the support of camelCase. Unfortunately, we also consider that concatenating two query words is considered one typo.

**To Reproduce**
 1. Start Meilisearch v.1.2.0
 2. Send the document `[{ "id": 0, "title": "DeLonghi" }]`
 3. Search for _dellonghi_

**Expected behavior**
Meilisearch should be able to find this one document without issue.

**Related issue to verify**
* https://github.com/meilisearch/meilisearch/issues/3869

**Comment by curquiza** [comment]
Feedback from the user here: https://github.com/meilisearch/meilisearch/discussions/3831

**Comment by gillian-meilisearch** [comment]
Hello everyone 👋 

We have released the first RC (release candidate) of Meilisearch containing this change!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.2)
- the [Meilisearch Docker image](https://hub.docker.com/r/getmeili/meilisearch/tags)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.2
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
