### ISSUE TITLE
Meilisearch on Docker not adding Documents 

### ISSUE THREAD

**Issue by Dmitriyx** [meilisearch/meilisearch#3828]
**Describe the bug**
Out of no where, the meilisearch instance on docker-compose v1.2.0 - stopped adding documents.
What I did:
- use postman to manually add one document
- watch meilisearch logs through docker 
- - meilisearch shows successful:
![image](https://github.com/meilisearch/meilisearch/assets/16686549/b6404826-ccfc-436a-b288-1a54089ee06b)
- when I search - I get no results because meilisearch not storing it.

What I tried to do to resolve:
- restarting meilisearch instance
- delete entire container and reinstall
- restart my entire computer
- delete entire stored volume 

**To Reproduce**
Unable to reproduce because I can not get it back to working state.
What else can I provide to help debug issue?

**Expected behavior**
save documents

**Meilisearch version:**
version: 1.2.0

**Additional context**
OS: Windows 10 Pro v.19045
CPU: AMD Ryzen 9
GPU: 4070 super
RAM: 64GB
Using WSL2
Computer shows that I have lots of available resources
MEILI_LOG_LEVEL=INFO
tested on MacOs with M2 chip - same issue.

I know this may not be the most descriptive / informative bug report - where can I find the logs to help debug this issue?

**Comment by Dmitriyx** [comment]
After looking into the EnqueuedTask - I saw the error message there and resolved my issue.

**Comment by curquiza** [comment]
Hello @Dmitriyx 
Glad you found out the issue. For people reading this issue, we always recommend looking at the task queue to know how the tasks have been processed.
https://www.meilisearch.com/docs/reference/api/tasks#get-tasks
Have a nice day
