### ISSUE TITLE
No options could be set when using Docker.

### ISSUE THREAD

**Issue by SaarChaffee** [meilisearch/meilisearch#3832]
**Describe the bug**
I'm not good at English, sorry

I deploy my Meilisearch by using Docker-compose, and here is the yaml.

```yaml
version: '3'
services:
  search:
    container_name: search
    image: getmeili/meilisearch:v1.2.0
    ports:
      - 27700:7700
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY='foo-bar'
    volumes:
      - ./meilisearch:/meili_data
```

When I start it, it works fine and I can access the web page, but without the master key.
It print the logs.

```log
search       | Config file path:        "none"
search       | Database path:           "./data.ms"
search       | Server listening on:     "http://0.0.0.0:7700"
search       | Environment:             "development"
search       | Commit SHA:              "foo-bar"
search       | Commit date:             "2023-05-30T18:20:28+00:00"
search       | Package version: "1.2.0"
search       | 
search       | Thank you for using Meilisearch!
search       | 
search       | 
search       | We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://www.meilisearch.com/docs/learn/what_is_meilisearch/telemetry
search       | 
search       | Anonymous telemetry:     "Enabled"
search       | Instance UID:            "foo-bar"
search       | 
search       | 
search       | 
search       |  No master key was found. The server will accept unidentified requests.
search       | 
search       |  A master key of at least 16 bytes will be required when switching to a production environment.
search       | 
search       | 
search       | We generated a new secure master key for you (you can safely use this token):
search       | 
search       | >> --master-key foo-bar <<
search       | 
search       | Restart Meilisearch with the argument above to use this new and secure master key.
search       | 
search       | Documentation:           https://www.meilisearch.com/docs
search       | Source code:             https://github.com/meilisearch/meilisearch
search       | Discord:         https://discord.meilisearch.com
search       | 
search       | [2023-06-13T02:47:23Z INFO  actix_server::builder] Starting 1 workers
search       | [2023-06-13T02:47:23Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
```

I have try the master key that generated from it, and also try using CLI `--master-key="foo-bar"` instead of ENV, but it dose not work. I also tried changing the environment to production to see if it would report an error, but unfortunately, it didn't. It's like not getting the options variables.
**To Reproduce**
1. Write down a docker-compose.yml like above.
2. Run docker-compose up search.
3. Run docker-compose logs search.

**Expected behavior**
It should be getting the master key in ENV or CLI, and throw an error when I change MEILI_ENV to production without master key just like the [document](https://www.meilisearch.com/docs/learn/security/master_api_keys#protecting-a-meilisearch-instance).

**Meilisearch version:**
getmeili/meilisearch:v1.2.0

**System info:**
Linux NAME 5.4.0-136-generic #153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SaarChaffee** [comment]
> Hello @SaarChaffee. That is strange. Sorry for the inconvenience. Unfortunately, I didn't succeed in reproducing the issue using the same compose file you posted above on an Ubuntu machine. It works fine from my end. Perhaps there is some information about your config or some other steps you took that might help me reproduce it. Please let me know. Thanks

Thanks for your reply. When I re-downloaded the image and started it, the problem was gone. I thought it was strange too, this is the first time I've had this problem.

**Comment by oluademola** [comment]
Hello @SaarChaffee. Thanks for letting me know that re-downloading the image resolved the issue for you. Since we can't reproduce the issue, I think it might not be a real issue. However, if you encounter any similar issues in the future or have any further questions, please don't hesitate to let us know.
