### ISSUE TITLE
Enhance search database cache

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#3847]
The feature **Define searchable fields at runtime** introduced changes in the search database cache that could be rewritten in a better way, related comment:

https://github.com/meilisearch/meilisearch/pull/3834#pullrequestreview-1488380472

**Comment by Kerollmops** [comment]
After more investigation, I discovered it is way more complex to implement than expected. The performance gain is not very important either.

The reason it is complex to change is that the `DatabaseCache::get_value/get_value_from_keys` functions are parametrized on a `DC::Item` type, which makes it impossible to return a RoaringBitmap as it is not necessarily constant (and we could ask for anything else).
