### ISSUE TITLE
Implemented api wrapper for Go

### ISSUE THREAD

**Issue by alexisvisco** [meilisearch/MeiliSearch#385]
Hey ! Since I'm not good enough to contribute directly to the database I allowed myself to start making a wrapper for the API in Go (my primary language).

I did not rely on your node wrapper made in typescript because I think it is in my opinion not really well built and especially it does not cover the whole API.

The link of the repository: http://github.com/meilisearch/meilisearch-go

It is with joy that I do it on my free time! 👍

**Comment by qdequele** [comment]
Thank you so much Alexis! We will add it to our documentation soon!

**Comment by qdequele** [comment]
> I did not rely on your node wrapper made in typescript because I think it is in my opinion not really well built and especially it does not cover the whole API.

Can we have your feedback on the js wrapper?

**Comment by Kerollmops** [comment]
Thank you Alexis, you made an awesome job!

**Comment by alexisvisco** [comment]
Feedback on the nodejs api wrapper:

#### The design of the wrapper

So in your library you have two bigs part which is index.ts (the globals endpoints) and indexes which stand for endpoint that rely on an index uid.

But in your documentation, you separate the APIs into different domains (indexes, documents, synonyms ...). I think it would be great if you had the same approach in the wrapper.

I don't known if you have ever used for instance the stripe api but it is one of most beautiful  🌟 api I have erver used !  

For instance to create an user:
`await stripe.customers.create(...)`

To create a paymentIntent:
`await stripe.paymentIntents.create(...)`
To cancel a paymentIntent:
`this.stripe.paymentIntents.cancel(...)`

Their library is segmented into modules which each are responsible for their API. 
Your way of designating the database-side API should be perfectly suited to the way stripe has organized their client.

#### The lack of types

I do not know if it is related to the fact that the sdk is not finished but it is really lacking a lot of type (you often return objects) that sometimes can be avoided, I imagine it was for prototyped quickly :)

Here I hope not to bother you too much but it's a pretty good opinion I think.
(btw @qdequele check your pm messages on the 42 slack !)

**Comment by alexisvisco** [comment]
Repository move from my account to the meilisearch organization! 🎉

**Comment by Kerollmops** [comment]
Yay 🎉 
Thank you, we will add some CI test workflows to the repo, I that will be good!
