### ISSUE TITLE
Improve the indexing performances of the Search Facet by Value feature

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3862]
This issue describes my concerns with adding [the Search Facet by Value feature](https://github.com/meilisearch/product/discussions/515). It will impact every user as we decided not to make people opt-in to this feature but otherwise enable it by default.

The current implementation forces Meilisearch to create an FST of all the facet string values of the available filterable attributes. This operation takes time and will always take more and more time as the user add documents (with filterable attributes). The reason is that constructing FST is slow and is down from scratch **at every indexation**, either deletion or addition of documents.

Note that shipping the support of searching in facet value words (consider facet value not as single big words) will be even more impactful. It will take even more indexing time to compute the necessary data structures.

## What can we do about it?

 - Ask the users about the searchable facets, i.e. [Algolia does that](https://www.algolia.com/doc/api-reference/api-parameters/attributesForFaceting/#parameter-option-searchable). Unfortunately, it will become a breaking change if we don't do that before the official v1.3.0 release.
 - Introduce a new setting to disable the search feature on some facets you don't want to make searchable.
 - Improve the speed of the implementation. It is not straightforward and will always cost more than nothing, which can be impactful for users who don't care about searching in facets.

**Comment by qdequele** [comment]
Indeed, it is an issue and I would go for the first proposal you have! Then later, the third one.
Thank you for proactively proposing three good solutions that may fix the issues; it makes the choice incredibly straightforward.

**Comment by Kerollmops** [comment]
Good news :tada:

The performance doesn't seem impacted at all. Either the database size and indexing time are in the variance threshold, which means that users shouldn't notice anything and will be able to search in facets. However, remember that I tested [with a specific dataset](https://www.notion.so/meilisearch/Songs-from-MusicBrainz-686e31b2bd3845898c7746f502a6e117) by sending it in one go. This is one use case but doesn't represent every one of them.

I would also like to add that in the future. We want to support search by words in the facets, which means more work to do at indexing time. However, adding a new `searchableFacets` setting that will see its default value as`"*"` in the future would not be breaking.
