### ISSUE TITLE
No result for partial character search within a word

### ISSUE THREAD

**Issue by cjtrbx** [meilisearch/MeiliSearch#3863]
**Describe the bug**
Search does not work if we are looking for a set of characters with a word. For instance, the search 'maid' from the movie 'mermaid' will not return any result.

**To Reproduce**
1. Go to '[...](https://www.meilisearch.com/)'
2. Click on 'seach input.'
3. Type 'maid' 
4. No result with mermaid, you can reproduce with 'tion', no result for 'extraction'

**Expected behavior**
See results with extraction or mermaid.

**Meilisearch version:**
Current version on the website, and 1.0 for our internal search

**Comment by oluademola** [comment]
Hello @cjtrbx. I understand your concerns, but I want to clarify that this is not a bug. Meilisearch is a prefix-based search engine and doesn't natively support partial word matches like querying in the middle of a word or at the end etc. You can find more information about prefix search [here](https://www.meilisearch.com/docs/learn/advanced/prefix). However, there is a workaround you can try. You can split the word and add an extra field to your document that contains an array of all possible infixes or suffixes for the word. This will enable you to search for a substring of the word and still find a match.
