### ISSUE TITLE
Do not leak field information on error

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3865]
This error message is inconsistent with the new `InvalidSearchableAttribute` error message wrt fields that don't appear in `displayedAttributes` in the settings.

As-is, the message could leak field names that are facet-searchable (filterable), but not in the `displayedAttributes` list, whereas they are redacted (hidden) in `InvalidSearchableAttribute`.

Since `InvalidSortableAttribute` suffers from the same issue we can probably address this in another PR, though.

_Originally posted by @dureuill in https://github.com/meilisearch/meilisearch/pull/3699#discussion_r1245356111_

**Comment by dureuill** [comment]
Ping from triage

- Severity: security-related, but more for inconsistency, we do not expect security vulnerabilities from this
- User impact: simplifies the security model

**Comment by ashu565** [comment]
Hi @Kerollmops can I work on this issue?

**Comment by Kerollmops** [comment]
Hey @ashu565 👋

You can work on that if you want. Just create a PR and I'll review it.

Have fun 🤩

**Comment by vivek-26** [comment]
Hey @Kerollmops, I have opened a [PR](https://github.com/meilisearch/meilisearch/pull/3945) for this issue. Could you please review it?

**Comment by vivek-26** [comment]
Hi @Kerollmops, requesting your review.
