### ISSUE TITLE
Unexpected case-sensitive search result

### ISSUE THREAD

**Issue by Nextra** [meilisearch/meilisearch#3869]
**Describe the bug**
When the search query matches a term with capital letters exactly (character for character), the search result appears to become case-sensitive unexpectedly, seemingly falling back to typo tolerance rules.

**To Reproduce**
Reproduction using a fresh, unconfigured index, using PHP:
```php
> $client->deleteIndex('test')
= [
    "taskUid" => 204897,
    "indexUid" => "test",
    "status" => "enqueued",
    "type" => "indexDeletion",
    "enqueuedAt" => "2023-06-30T14:20:15.49074795Z",
  ]
> $client->index('test')->addDocuments([['id' => 1, 'test' => 'TestAB']])
= [
    "taskUid" => 204899,
    "indexUid" => "test",
    "status" => "enqueued",
    "type" => "documentAdditionOrUpdate",
    "enqueuedAt" => "2023-06-30T14:20:35.571879172Z",
  ]
> $client->index('test')->search('testa')->count()
= 1
> $client->index('test')->search('testab')->count()
= 0
> $client->index('test')->search('Testab')->count()
= 0
> $client->index('test')->search('TestAb')->count()
= 1
> $client->index('test')->search('testaB')->count()
= 1
> $client->index('test')->search('TestaB')->count()
= 1
> $client->index('test')->search('TestAB')->count()
= 1
```

This also occurs if the "offending" term appears in a much longer document.

**Expected behavior**
The search should be case insensitive even if a word is matched exactly.

**Meilisearch version:**
v1.2.0

**Comment by Nextra** [comment]
Bonus: Capitalized words also lead to weirdness with typo tolerance.

Document contains lowercase "word":
```php
> $client->deleteIndex('test')
= [
    "taskUid" => 221303,
    "indexUid" => "test",
    "status" => "enqueued",
    "type" => "indexDeletion",
    "enqueuedAt" => "2023-07-03T11:07:17.486684029Z",
  ]
> $client->index('test')->addDocuments([['id' => 1, 'test' => 'testab']])
= [
    "taskUid" => 221307,
    "indexUid" => "test",
    "status" => "enqueued",
    "type" => "documentAdditionOrUpdate",
    "enqueuedAt" => "2023-07-03T11:07:31.826627782Z",
  ]
> $client->index('test')->search('tetsab')->count()
= 1
```

Index contains "word" with capital letters:
```php
> $client->deleteIndex('test')
= [
    "taskUid" => 221314,
    "indexUid" => "test",
    "status" => "enqueued",
    "type" => "indexDeletion",
    "enqueuedAt" => "2023-07-03T11:08:01.78582517Z",
  ]
> $client->index('test')->addDocuments([['id' => 1, 'test' => 'TestAB']])
= [
    "taskUid" => 221315,
    "indexUid" => "test",
    "status" => "enqueued",
    "type" => "documentAdditionOrUpdate",
    "enqueuedAt" => "2023-07-03T11:08:06.938675556Z",
  ]
> $client->index('test')->search('tetsab')->count()
= 0
> $client->index('test')->search('TetsAB')->count()
= 0
```

**Comment by gillian-meilisearch** [comment]
@Nextra thanks so much for raising this and your detailed steps 🙏🏻 We have an issue alreadythat we are targeting to add to v1.3.0 that should address this problem. That issue is here for reference: https://github.com/meilisearch/meilisearch/issues/3818

**Comment by dureuill** [comment]
Ping from triage:

- Severity 2 to 3: Affects a specific case of relevancy, very surprising results, workaround: index documents lowercased
- Size medium

**Comment by gillian-meilisearch** [comment]
Hello 👋 

Just wanted to highlight we have released the first RC (release candidate) of Meilisearch containing this change!

You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.2)
- the [Meilisearch Docker image](https://hub.docker.com/r/getmeili/meilisearch/tags)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.2
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
