### ISSUE TITLE
Japanese Katakana characters split when registering synonyms

### ISSUE THREAD

**Issue by hieunv5501** [meilisearch/meilisearch#3883]
**Describe the bug**

I tried add a synonym below.
`{"デジダル": ["Digital"]}`
then synonyms were added below
`{ "テ ゙ シ ゙ タ ゙ ル": ["digital"]}`

**Japanese Katakana characters split**: `デ => テ ゙`, `ジ => シ ゙`, ...

**Expected behavior**
I expected: `デジダル => デジダル`

**Screenshots**
<img width="633" alt="image" src="https://github.com/meilisearch/meilisearch/assets/130542420/4cefcbec-bd86-454d-86d4-0ad6f06eed12">
<img width="626" alt="image" src="https://github.com/meilisearch/meilisearch/assets/130542420/6ffb911e-d847-4455-88ca-a75062723814">

**Meilisearch version:**
getmeili/meilisearch:prototype-japanese-2

**Comment by ManyTheFish** [comment]
Hello @hieunv5501,
It's a known display bug related to https://github.com/meilisearch/meilisearch/issues/2760, it should not impact the relevancy of your queries.

I'm closing this issue in favor of #2760,
Thank you for your report,
See you!
