### ISSUE TITLE
Integrate mini-dashboard with Cloud information

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3892]
Discussed with @gmourier 

v1.3 should integrate the new version of the mini-dashboard. This new version will display information about the Cloud: a button or a banner redirecting to the new Cloud landing page (in progress)

We are waiting for the new Cloud landing page to be ready before releasing. If the new landing page is not ready before the v1.3 release day, let's merge the new mini-dashboard anyway with a redirection to the [pricing page](https://www.meilisearch.com/pricing) instead. **Indeed, this issue is a must-have for v1.3**.

Pinging @bidoubiwa since you are the owner of the mini-dashboard.

**Comment by gmourier** [comment]
@curquiza Can we add it even if the landing is not ready yet? In the case the landing arrives before the release, we could make a quick change to the link. WDYT?

**Comment by curquiza** [comment]
Yes, it's more up to Charlotte who will have to do 2 changes instead of 1. It's up to you.

**Comment by gillian-meilisearch** [comment]
PR added to 1.3 🎉 Thanks @bidoubiwa
