### ISSUE TITLE
[API] Document Get One

### ISSUE THREAD

**Issue by alexisvisco** [meilisearch/MeiliSearch#390]
Hi, there is an issue with this route: https://docs.meilisearch.com/references/documents.html#get-one-document (and maybe all routes that are using a document identifier)

The bug is that the url parser does not recognize the end parameter when it's a string and produce this error message: 
`{"message":"Url parameter identifier error: expected value at line 1 column 1"}`

Here a bash script to reproduce the bug:

```bash
#!/usr/bin/env bash

docker run -d -p 7700:7700 --name testmeili --rm getmeili/meilisearch ; \


# creating an index
curl \
  --request POST 'http://localhost:7700/indexes' \
  --data '{
  "name": "Movies",
  "uid": "Movies",
  "schema": {
    "id": ["identifier", "indexed", "displayed"],
    "title": ["displayed", "indexed"],
    "overview": ["displayed", "indexed"],
    "release_date": ["displayed"],
    "poster": ["displayed"]
  }
}' ; sleep 2 ; echo ; \

# adding a document into the previous index with an id in string
curl \
  --request POST 'http://localhost:7700/indexes/Movies/documents' \
  --data '[{
    "id": "itisanid",
    "title": "Shazam",
    "poster": "https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg",
    "overview": "A boy is given the ability to become an adult superhero in times of need with a single magic word.",
    "release_date": "2019-03-23"
  }]' ; sleep 2 ;  echo \

# getting the document with a string id
curl --request GET 'http://localhost:7700/indexes/Movies/documents/itisanid' ; echo ; \


docker kill testmeili
```

It should work because in the documentation an identifier is basically a string or an integer:
> Documents identifiers are always converted into strings. Only strings and integers are valid identifiers. It means that it is, for example, forbidden to use arrays or objects as an identifier.

Version of the docker image: `343d1b03539b`

**Comment by Kerollmops** [comment]
Thank you for this great dive into this bug. I looked at it and it was a mistake, I tried to interpret the identifier as a JSON value, it think I tested it only with number therefore did not noticed that string needed quotes to work.
