### ISSUE TITLE
Meilisearch v1.3: accept `["*"]` as a value for attributesToSearchOn

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#3911]
**Describe the bug**
Currently only the known document fields are accepted in attributesToSearchOn.
On other similar fields like `attributesToRetrieve`, the value `["*"]` is also accepted.

**To Reproduce**
1. Make a search on an index with `attributesToSearchOn: ["*"]`

**Expected behavior**
Be consistent with the other similar fields

**Meilisearch version:**
v1.3.0rc-1

----

Curqui's update
`["*"]` means "all the possible attributes", so in this case, contrary to `attributesToRetreive`, it's "all the `searchableAttributes`"

**Comment by gillian-meilisearch** [comment]
Hello everyone 👋 

We have released the first RC (release candidate) of Meilisearch containing this change!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.2)
- the [Meilisearch Docker image](https://hub.docker.com/r/getmeili/meilisearch/tags)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.2
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
