### ISSUE TITLE
Meilisearch v1.3: when using attributesToSearchOn, accept all fields if searchableAttributes is ["*"]

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch#3912]
**Describe the bug**
Currently, `attributesToSearchOn` only accepts the fields that have already been discovered in some documents. Meaning that if there is a field not present in a document, if it is added to attributesToSearchOn it will throw an error.

Nonetheless, `attributesToSearchOn` should accept all fields that are declared in `searchableAttributes`. 
If `searchableAttribute` is `["title"]` only `title` is accepted in `attributesToSearchOn`. Similarly, if `searchableAttributes` is `["*"]`, `attributesToSearchOn` should accept all fields.

**To Reproduce**
- Create an index
- Add documents
- Do not edit any setting
- search with `attributesToSearchOn` set to `["whatever field that does not exist"]`
- Error is thrown

**Expected behavior**
In case searchableAttributes is `["*"]` all fields should be accepted in `attributesToSearchOn`. In the other case, keep current behavior.

**Meilisearch version:**
v1.3.0rc-0

**Comment by gillian-meilisearch** [comment]
Hello everyone 👋 

We have released the first RC (release candidate) of Meilisearch containing this change!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.2)
- the [Meilisearch Docker image](https://hub.docker.com/r/getmeili/meilisearch/tags)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.2
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
