### ISSUE TITLE
Load a user-defined dictionary 

### ISSUE THREAD

**Issue by gillian-meilisearch** [meilisearch/meilisearch#3917]
Related product team resources: [roadmap card](https://www.notion.so/meilisearch/Send-my-own-word-dictionary-099bd4a69ef94614897728cdbc007110) (_internal only_)
Related product discussion:
- [Load a user-defined dictionary #663](https://github.com/meilisearch/product/discussions/663)
- https://github.com/meilisearch/meilisearch/issues/2879

Related spec: https://github.com/meilisearch/specifications/pull/255

## Motivation

Some Languages are not always space separated (Chinese, Japanese, Korean...) forcing Meilisearch to rely on common word dictionaries to segment a text into words, however, this strategy works only to segment common words and struggles when a text contains domain-specific words, technical words, or People Nouns.

Because it is impossible to have an exhaustive list of words of all the possible domains or a complete list of Nouns, Meilisearch should allow the user to add their own list of words specialized for their use case.

## Usage

TBC: Refer to the final spec to know the details and the final decisions about the usage.

## TODO

- [x] Release a prototype
- [ ] If prototype validated, merge changes into `main`
- [x] Update the spec

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team

**Comment by curquiza** [comment]
Hello everyone 👋

We have just released the first RC (release candidate) of Meilisearch containing this new feature!

You can test it by using:

- The [release assets](https://github.com/meilisearch/meilisearch/releases)
- The [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)

```
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.4.0-rc.0

```

You are welcome to leave your feedback in this discussion.

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️

🎉 Official and stable release containing this change will be available on September 25th, 2023

⚠️ RC (release candidates) are not recommended for production
