### ISSUE TITLE
Strange behavior on the get one synonym route

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#392]
With this synonyms:
```json
{
    "smartphone": [
        "iphone",
        "samsung"
    ],
    "harry potter": [
        "hp"
    ],
    "hp": [
        "harry potter"
    ]
}
```

When I request:
- `GET /indexes/:uid/synonyms/hp`: OK
- `GET /indexes/:uid/synonyms/lol`: returns an empty array and `200`. Can we do the same behavior than the documents routes, that returns a `404` and a clear error message in the body?
- `GET /indexes/:uid/synonyms/harry%20potter`: returns an empty array and a `200`, but should return `[ "hp" ]`. Related to this [issue](https://github.com/meilisearch/MeiliSearch/issues/389).

**Comment by alexisvisco** [comment]
Maybe related it seems like when you add a new synonym with an input with an Uppercase letter when you want to retrieve it, the list of synonyms for this input is empty.

Script to reproduce:

```bash
#!/usr/bin/env bash

docker run -d -p 7700:7700 --name testmeili --rm getmeili/meilisearch \
; curl \
  --request POST 'http://localhost:7700/indexes' \
  --data '{
  "name": "Movies",
  "uid": "Movies",
  "schema": {
    "id": ["identifier", "indexed", "displayed"],
    "title": ["displayed", "indexed"],
    "overview": ["displayed", "indexed"],
    "release_date": ["displayed"],
    "poster": ["displayed"]
  }
}' ; echo ; sleep 2 \
;  curl \
  --request POST 'http://localhost:7700/indexes/Movies/synonyms' \
  --data '{ "input": "Hello", "synonyms": ["hello-ish"]}' ; echo ; sleep 5 \
;  curl --request GET 'http://localhost:7700/indexes/Movies/synonyms/Hello' ; echo  \
; docker kill testmeili
```

(Not due to async update I have set sleep to 5 seconds)

**Comment by qdequele** [comment]
The synonyms endpoint will be completely refactored due to several issues and misunderstandings.

The issue #398  has been created to explain what will change. The fix is coming soon! I Will work on it today.

Thank you both for these comments !
