### ISSUE TITLE
Search huge time variance between queries

### ISSUE THREAD

**Issue by Magorx15** [meilisearch/meilisearch#3925]
**Describe the bug**
There is a huge variance in the time it takes for the first and second queries. This seems to happen for every individual query.

Example:
We search for `acropolis` in our **english** index for the **first** time -> 114 ms
We search for `acropolis` in our **english** index for the **second** time -> 30 ms

We search for `From the Stone Age to the Iron Age` in our **english** index for the **first** time -> 910 ms
We search for `From the Stone Age to the Iron Age` in our **english** index for the **second** time -> 120 ms

(just to demonstrate index does not matter)
We search for `From the Stone Age to the Iron Age` in our **hungarian** index for the **first** time -> 215 ms
We search for `From the Stone Age to the Iron Age` in our **hungarian** index for the **second** time -> 84 ms

**To Reproduce**
Sadly we are not sure how to reproduce this exactly

**Meilisearch version:**
v0.27.2 - v1.1.0

**Additional context**
Our ram usage is very low considering our data.ms is 25 GB. Meilisearch uses less than 1 GB of ram and we think this might be the cause. Just to clarify: we are not talking about indexing but when meilisearch is running from a snapshot and users search in it.

![image](https://github.com/meilisearch/meilisearch/assets/118532529/0a1764e6-0046-4ecb-828d-95539c21e4d7)

We are using ssd and have plenty of available disk space and ram as well. CPU is not overloaded either.
We are restarting meilisearch from snapshot every day so this problem sadly reoccurs every day

Maybe this wouldn't solve our issue at all, but it would be nice to see a config for managing RAM usage not only limited to indexing

**Comment by Kerollmops** [comment]
Hey @Magorx15 👋

Thank you for the detailed report. With a data.ms of about 25GiB you should see a higher Virtual Memory usage than just 1GiB. The 1GiB are related to the internal data structures we allocate dynamically, that must be low and it seems ok.

 - How much RAM do you have?
 - Have you tried [the latest v1.2 release](https://github.com/meilisearch/meilisearch/releases/tag/v1.2.0)? We improved the search speed by a lot.

Have a nice day 🎉

**Comment by Magorx15** [comment]
- We have 14 GB free RAM
- Depends on the index, its 5.000 to 70.000. english index has 30.000 and hungarian index has 60.000
- Sadly we can't use 1.2 or any other version after 1.0 yet because of an issue that will only be fixed in 1.3 and we can't really put that into production just yet

**Comment by Kerollmops** [comment]
> Sadly we can't use 1.2 or any other version after 1.0 yet because of an issue that will only be fixed in 1.3 and we can't really put that into production just yet

Can you tell me about the specific issue you have with those versions?

Do you think you could redirect the production search requests on [the v1.3.0-rc.2 release](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.2) without really putting it in production and tell us if it works great? It would be better if you can spot bugs before July 31, the release day ☺️

**Comment by Magorx15** [comment]
It has to do with separators.
_word,anotherWord -> this works for `_word` query
anotherWord,_word -> this does not work for '_word` query

1.3 fixes this, i already checked locally.

We can try to do something like start another instance of meilisearch with that version

**Comment by Magorx15** [comment]
I tried the 1.3.0-rc.2 version on local and on a different server which is on the same network as my computer.
The local was fast everytime while the server had the same effect. It is very weird.

Given, the server is much more powerful in every possible way, ram, disk space, cpu

As soon as meilisearch starts i just searched 2 times on both machines.
The server:
"POST /indexes/lexikon_en/search HTTP/1.1" 200 184220 "-" "PostmanRuntime/7.29.3" 1.296197
"POST /indexes/lexikon_en/search HTTP/1.1" 200 184218 "-" "PostmanRuntime/7.29.3" 0.062469

Local:
"POST /indexes/lexikon_en/search HTTP/1.1" 200 184218 "-" "PostmanRuntime/7.29.3" 0.031128
"POST /indexes/lexikon_en/search HTTP/1.1" 200 184218 "-" "PostmanRuntime/7.29.3" 0.035178

One thing i find weird but might be nothing is that the response size is different for the first time

**Comment by Kerollmops** [comment]
Thank you for these detailed reports. However, can you also give me the `estimatedTimeMs` Meilisearch answers? We could probably spot a diff between this and the time the HTTP server returns (as I guess those are the Meilisearch Logs).

Is there more than Meilisearch running on your machine? Is it an NVMe SSD? Note that I am pretty sure the issue comes from the hotness of the LMDB pages in RAM. [We use the LMDB key-value store internally](https://www.meilisearch.com/docs/learn/advanced/storage), which is highly dependent on your OS's memory mapping quality and performance.

> One thing i find weird but might be nothing is that the response size is different for the first time

I would guess that the size differs due to the time the engine takes which is longer and will therefore use more characters when returned under the `estimatedTimeMs` fields.

**Comment by Magorx15** [comment]
Sure!

Server:
"processingTimeMs": 291 | Postman time: 321 ms | Meilisearch log: 0.312241
"processingTimeMs": 108 | Postman time: 129 ms | Meilisearch log: 0.121617

Local:
"processingTimeMs": 39 | Postman time: 51 ms | Meilisearch log: 0.052932
"processingTimeMs": 26 | Postman time: 31 ms | Meilisearch log: 0.028467

There is always just a single meilisearch running on every machine. All of them are SATA ssd.

> Note that I am pretty sure the issue comes from the hotness of the LMDB pages in RAM. [We use the LMDB key-value store internally](https://www.meilisearch.com/docs/learn/advanced/storage), which is highly dependent on your OS's memory mapping quality and performance.

I am not sure i understand, how can we improve this?

**Comment by Magorx15** [comment]
Any updates? @Kerollmops

**Comment by Kerollmops** [comment]
Hey @Magorx15,

Sorry for the late reply.

> All of them are SATA ssd except my machine which is NVMe. Does it really have this much impact?

It seems that indeed the performance of the Disk is very important. However, it seems strange as once the database on disk is hot in RAM no more slowness should be noticed. At least only if the database is updated.

Can you try with NVMe servers?

**Comment by Magorx15** [comment]
I moved one of our servers to nvme and weirdly enough it did not solve the issue!

**Comment by Magorx15** [comment]
- Debian 11
- Docker
- If i understand correctly the question, we are using pre-compiled one. We create our own image using getmeili/meilisearch:v0.27.2
(and ofc i tested with higher version the same way)

**Comment by curquiza** [comment]
Hello @Magorx15 
@Kerollmops is on Holiday, so I try to help you in the meantime
You have to know Meilisearch v0.27.2 is a really old version of Meilisearch (more than a year), and is not even a stable version of Meilisearch. We released v1.0.0 in February 2023.

The latest one we have just released is v1.3.0 of Meilisearch. Between v0.27.0 and v1.3 we worked a lot on performance improvements. You might see some improvements by only migrating to it.
https://www.meilisearch.com/docs/learn/update_and_migration/updating.

You can also use our [cloud offer](https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=github&utm_medium=meilisearch) to manage Meilisearch in an easier way. The migration to another version of Meilisearch can only be done with one click

**Comment by Magorx15** [comment]
Sure! @curquiza i tried using v1.3.0 as i stated before and the results were the same sadly
