### ISSUE TITLE
task 577 panicked when using "sort":["_geoPoint(46.4982953,11.3547582):asc"]

### ISSUE THREAD

**Issue by jmarcher** [meilisearch/meilisearch#3927]
Have around 11k documents in my index but in this case i'm event filtering the results by id like so:

`"filter" : ["type=1", "_facet_something=1", "platform_ground=1", "id IN [11137]"]`

but when trying to sort the results by distance I get the following error:

```
{
    "message": "task 577 panicked",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
}
```

Note: Not all the documents have a `_geo`attribute (we do not have this information in all the cases)

**Comment by gillian-meilisearch** [comment]
Hi @jmarcher thanks for reporting this, can I ask what version you're seeing this on please?

**Comment by jmarcher** [comment]
```
Commit SHA:		"d963b5f85ae9aea42615924de4e41e96a1e5358e"
Commit date:		"2023-05-30T18:20:28Z"
Package version:	"1.2.0"
```

**Comment by jmarcher** [comment]
I just did a test and flushed the index and re-imported all the documents now with lat lng as floats and it works. 

The documentation says it should work with strings: https://www.meilisearch.com/docs/learn/fine_tuning_results/geosearch#preparing-documents-for-location-based-search

**Comment by jmarcher** [comment]
@gillian-meilisearch Yes, that's the same as my case

**Comment by gillian-meilisearch** [comment]
@jmarcher thanks again for the report, much appreciated! We've got a fix together that will go into the next RC version 🎉 and it will go out with 1.3 all going well.

**Comment by gillian-meilisearch** [comment]
Hello everyone 👋 

We have released the first RC (release candidate) of Meilisearch containing this change!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.3)
- the [Meilisearch Docker image](https://hub.docker.com/r/getmeili/meilisearch/tags)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.3
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
