### ISSUE TITLE
Rewrite the `segment_analytics` module with the destructuring syntax

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3928]
The segment_analytics module has been written so that we can omit using fields from the query or the Aggregator struct itself. We must rewrite it with [the Rust Destructuring syntax](https://doc.rust-lang.org/rust-by-example/flow_control/match/destructuring/destructure_structures.html) to be sure to have an error when we forget to use a field and do something with it explicitly.

I no more want to have to do [this kind of PR](https://github.com/meilisearch/meilisearch/pull/3909) in the middle of the pre-release cycle.

https://github.com/meilisearch/meilisearch/blob/2b4160ebb95b7ec3c46f3b7ce5735013d47a9500/meilisearch/src/analytics/segment_analytics.rs#L613-L681

**Comment by XshubhamX** [comment]
Can i work on this @Kerollmops ?

**Comment by Kerollmops** [comment]
Hey @XshubhamX 👋,

You can work on this, indeed. It seems there already is a PR but it doesn't look finished yet and far from that 😊
Create your draft PR and I'll review it once you're done and make it _ready for review_.
