### ISSUE TITLE
Setting a string field to ranked (as in the docs) fails

### ISSUE THREAD

**Issue by deanishe** [meilisearch/MeiliSearch#393]
I get the following error when trying to index a document with a string in a field marked `ranked`:

```
serializer error; error while trying to parse a number: can not parse number: invalid digit found in string, invalid float literal
```

[The ranking example in the docs](https://docs.meilisearch.com/advanced_guides/ranking.html#custom-ranking-rules) uses a string, however.

I don't know if this is a problem in the code or the docs, but I hope it's the former.

**Comment by Kerollmops** [comment]
I think this error doesn't comes from the fact that `"asc"` is a string or not but the fact the marked as ranked field of one of your document isn't a number.

I understand that it is wrong, having an invalid document must not be fatal and must not abort this update. It should return warnings about invalid documents instead.

**Comment by deanishe** [comment]
> the fact the marked as ranked field of one of your document isn't a number.

Yes. That's what I was trying to say. As in the example in the docs, I'm trying to rank results on a YYYY-MM-DD-formatted date string.

> having an invalid document must not be fatal and must not abort this update.

I had no reason to consider the document invalid: The examples in the docs also show a `ranked` field as being a string.

Does that mean the docs are wrong, and `ranked` fields must be numeric? Because that would not be ideal.

**Comment by Kerollmops** [comment]
Ho! I see that was our mistake, if you used the dataset that is provided on the README (https://bit.ly/33MKvk4) we forget to modify it and to transform the `release_dates` in timestamp.

As a solution you can use [the movies file available in this repository](https://github.com/meilisearch/MeiliSearch/blob/master/datasets/movies/movies.json), we will update the other one.

It would not be easy to accept any kind of date format as there is no real format out there that works for all (YYYY-MMM-DD could also be understood as YYYY-DD-MM), so we chose to only accept negative and positive integers and floats. It is easier for us and covers more cases.

**Comment by Kerollmops** [comment]
I created the issue #395, tell me if the new references file works better than the old one and I will merge it.

**Comment by deanishe** [comment]
> As a solution you can use the movies file available in this repository, we will update the other one.

Thanks, but I don't want to search your data, I want to search mine…

> It would not be easy to accept any kind of date format

I'm not suggesting Meili try to parse date strings, I'm suggesting that strings be permitted in `ranked` fields. They are also sortable.

**Comment by Kerollmops** [comment]
Currently the ranking attributes that you specify are parsed as numbers (64bit integers or floats) and stored inside a big HashMap for fast lookups.

It would not be a great solution to store strings as those are not of known sizes and accessing them require a memory lookup (which is slow).

I can only recommend you to compute the timestamps associated to you dates and use them as custom ranked attributes like before. [Here is the command line that we used to to that on our data](https://stackoverflow.com/a/58882569/1941280).

**Comment by deanishe** [comment]
> I can only recommend you to compute the timestamps associated to you dates 

That is, of course, what I'm doing.
