### ISSUE TITLE
Update the experimental product discussion linked to the metrics feature with the following text

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3947]
Main changes:
- I got rid of the mention « do not use in production », because actually, you can if you’re ready to patch your dashboards according to what we say in the « What is an experimental feature » part.
- I updated the list of exposed features
- I added a step-by-step tutorial to run the metrics

If possible, this should be done on the day of the release
Here’s the link of the discussion: https://github.com/meilisearch/product/discussions/625

-----------

Hey everyone 👋

For the v1.1 of Meilisearch (which was released on 3rd April), we will finally introduce the [metrics](https://github.com/meilisearch/meilisearch/pull/2657) feature as an **experimental feature**. 

## Feature Abstract

The `/metrics` endpoint exposes metrics to be scraped by a Prometheus collector at regular intervals and stored for analysis. By monitoring these metrics over time, teams can gain valuable insights into the behavior and performance of Meilisearch and use that information to optimize their performance, troubleshoot issues, and improve the overall reliability of their systems.

### How to use the feature?

- The metrics are sent using the [prometheus](https://prometheus.io/) format
- When launching meilisearch, use the cli-flag `--experimental-enable-metrics` or the `MEILI_EXPERIMENTAL_ENABLE_METRICS` env var
- This exposes a new route in the API endpoint `GET /metrics`
     - To poll this route, your API key needs the right to pull metrics through the `metrics.get` action and access to all indexes.
     - The [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) must contain an `Authorization` header using the bearer method with the Meilisearch API Key authorized to poll the `/metrics` endpoint. You can find a basic config in the repository under [`assets/prometheus-basic-scraper.yml`](assets/prometheus-basic-scraper.yml).

#### Step-by-step basic tutorial

To read before starting the tutorial:
- You need to install Prometheus and Grafana. Refer to the documentation of your distribution / OS.
- I won't explain how to secure your instance. Refer to [this](https://www.meilisearch.com/docs/learn/security/master_api_keys#protecting-a-meilisearch-instance) documentation if you need to learn how it works, and adapt the following command to include your master-key / api-key.

1. Run meilisearch with the experimental feature enabled: `./meilisearch --experimental-enable-metrics`.
2. Download the Prometheus assets file stored on the meilisearch repository [`assets/prometheus-basic-scraper.yml`](assets/prometheus-basic-scraper.yml).
3. If you need to use an API key, add the following lines to the end of the config file (and replace <api-key> with your API key):
```
authorization:
	credentials: <api-key>
```
4. On another terminal or server, run Prometheus with your config file: `./prometheus --config.file=path-to-your-config-file.yml`
5. Download the default Grafana dashboard on the following URL: [`https://github.com/meilisearch/meilisearch/blob/main/assets/grafana-dashboard.json`](https://github.com/meilisearch/meilisearch/blob/main/assets/grafana-dashboard.json).
6. Connect to your Grafana instance (by default, it runs on `http://localhost:3000`). Create an account if needed.
7. Add a data source that points to your Prometheus server (by default, it runs on `http://localhost:9090`).
8. Go into the dashboard menu and import a dashboard file.
9. Import the json previously downloaded. You should be good to go :tada:

### What's currently exposed?

| Name                                     | Description | Type      |
|------------------------------------------|-------------|-----------|
| `meilisearch_http_requests_total`        | Returns the number of times an API resource is accessed. | counter   |
| `meilisearch_http_response_time_seconds` | Returns a time histogram showing the number of times an API resource call goes into a time bucket (expressed in second). | histogram |
| `meilisearch_db_size_bytes`              | Returns the “real” size of the database on disk in bytes. It includes all the lmdb memory mapped files plus all the files contained in the `data.ms` directory (mainly the updates files that were not processed yet). | gauge     |
| `meilisearch_used_db_size_bytes`         | Returns the size of the database actually used by meilisearch in bytes. Include all the same files as `meilisearch_db_size_bytes` except that when it comes to an LMDB database, we only count the pages used by meilisearch. This means if you see a large gap between both metrics, adding documents will probably re-use freed pages instead of growing `meilisearch_db_size_bytes`. | gauge     |
| `meilisearch_index_docs_count`           | Returns the number of documents for an index. | gauge     |
| `meilisearch_index_count`                | Returns the total number of index for the Meilisearch instance. | gauge     |
| `meilisearch_nb_tasks`                   | Returns the total number of tasks for the Meilisearch instance parametrized by the kind of task and its value (see the table below). | counter   |
| `meilisearch_last_update`                | Returns the timestamp of the last update. | gauge     |
| `meilisearch_is_indexing`                | Returns `1` if Meilisearch is indexing or `0` if not. | gauge     |

---

## What is an experimental feature

- The API and the behavior of an experimental feature can break between two minor versions of Meilisearch.
- The whole experimental feature process can break between 2 minor versions of Meilisearch.
- The newly introduced experimental features or improvements can be removed in the future. Providing a feature as “experimental” does not guarantee it will be stable one day.
- The experimental features are supposed to be unstable regarding the API usage but **not bugged**.

## Why is this feature not stable yet?

We have yet to determine which metrics we want to expose and how. Thus this may change a lot depending on our needs and your needs.

## When will the feature potentially be stable?

We don't know yet when this feature could be stable since we need to iterate on it. As explained previously, we do not guarantee it will be stable one day yet.

Depending on the feedback we get, we plan to iterate on the feature every 1 or 2 releases (Currently, our release cycle is two months long).

## X metrics are missing

We know the feature is not finished yet.

Please let us comment on which information you would like to see integrated into the metrics.
And do not hesitate to create a PR as well. Most of the code is available in `meilisearch/src/metrics.rs`.

🗣️  **You are welcome to give feedback about the feature or ask any questions; we can guide you through this new feature usage!**

---

cc @meilisearch/cloud-team

**Comment by curquiza** [comment]
@irevoire I updated it!

Let me know if it's not what you expected

Closing this!
