### ISSUE TITLE
Documents uploading

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#397]
This issue is in two parts:
- [x] MVP: allows JSON with `null` and boolean fields, but these fields will not be indexable.
<del> - [ ] Set up logs that will be accessible with the `updateId` via [update status route](https://docs.meilisearch.com/references/updates.html). So that the user can check which document failed and if all the fields were taken into account. </del> (In favor of #432)

**Comment by qdequele** [comment]
Closes due to #400

**Comment by bidoubiwa** [comment]
No documentation needed
