### ISSUE TITLE
Prometheus `meilisearch_nb_tasks` seems to report nothing

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#3972]
Mentioned by @gabrieltz [here](https://github.com/meilisearch/product/discussions/625#discussioncomment-6612886) 

"I upgraded to version 1.3.0 yesterday and used some of the new metrics, however i noticed that the metric meilisearch_nb_tasks{instance="XXXXXX:7700", job="meilisearch", kind="statuses", value="processing"} is zero all the time, even while importing a few million documents in over 700 batches. The /tasks endpoint values were correct though"

**Comment by irevoire** [comment]
I reproduced it; it’s a bug

**Comment by curquiza** [comment]
Will be fixed in v1.3.1 and release this week or next week

**Comment by curquiza** [comment]
Fixed by #3976
