### ISSUE TITLE
Panic: MDB_BAD_VALSIZE when importing a dump in v1.3.0

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#3978]
**Describe the bug**
Panic: MDB_BAD_VALSIZE when importing a dump in v1.3.0

**To Reproduce**
1) Import a dump containing a long filter value
2) it panics during indexing

**Expected behavior**
No panic  when importing any dump

**Meilisearch version:**
v1.3.0

**Additional context**
initial reporter: https://discord.com/channels/1006923006964154428/1136303730652889190/1136303730652889190

**Comment by Magorx15** [comment]
Hi! Just an additional information that the same error happens with documentAdditionalOrUpdate. If a field has too long value

**Comment by curquiza** [comment]
Closed by #3981
Will be released and integrated into v1.3.1, by the end of this week, or next week
