### ISSUE TITLE
Stops sending the `http_response_time_seconds_count` in the metrics because it overwhelms prometheus

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3983]
The `http_response_time_seconds_count` field sends way too much information, and that slows down Prometheus a lot and makes it use a lot of memory (the same is probably true for meilisearch as well, even if it’s less impactful).
We should get rid of it and group the route behind a common denominator.
Maybe instead of exposing these metrics that updates with every possible route, we should instead send a fixed number of route.
Something like:
- `http_response_time_tasks` for all the tasks
- `http_response_time_search` parametrized by the index name for all the searches.
- Is that enough? Should we share more, like the time to add a document?

Reported by @miiton here: https://github.com/meilisearch/product/discussions/625#discussioncomment-6600928

------

I see that the Prometheus process is consuming a lot of CPU/Memory due to the large number of values related to TASKs.
I think this is a point for improvement.

```
http_response_time_seconds_count{method="GET",path="/tasks/1"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/1",le="0.0005"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/1",le="0.0008"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/1",le="0.00085"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/1",le="0.0009"} 1
...
...
...
http_response_time_seconds_count{method="GET",path="/tasks/9977"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/9978",le="0.0005"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/9978",le="0.0008"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/9978",le="0.00085"} 1
http_response_time_seconds_bucket{method="GET",path="/tasks/9978",le="0.0009"} 1
...
```

**with scrape meilisearch metrics**
![image](https://github.com/meilisearch/product/assets/468745/56723350-382a-41f9-8518-c1f68fe1fbce)

**without scrape meilisearch metrics**
![image](https://github.com/meilisearch/product/assets/468745/1a21055e-27ae-428b-bfb2-9bc74d0cd41e)

- Meilisearch v1.2.0
- Prometheus v2.45.0

**Comment by itsajay1029** [comment]
I'd love to work on this @irevoire. Can you assign it to me and explain how to resolve this ?

**Comment by Kerollmops** [comment]
Hey @itsajay1029 👋

I'm glad you want to work on that. We prefer when someone submits a PR instead. You can propose a change and we will close this issue once you fix it.

**Comment by itsajay1029** [comment]
Can you highlight the issue and suggest the probable solution for it ? It's bit confusing for me @Kerollmops

**Comment by itsajay1029** [comment]
Hey @Kerollmops ? Please ellaborate the issue

**Comment by Malgefor** [comment]
Hey! I have a question related to this issue. I was also experiencing an overload of metrics on my Prometheus server which caused it to go down. After #4619 it is partly fixed. However, I am still getting **82.000** metrics just to see that a certain task returned a 200 OK status code (sample below). That amount of metrics still occasionally kills my Prometheus server. 

Can this metric, maybe specific to **/tasks/***, receive the same kind of treatment as in #4619?

```
meilisearch_http_requests_total{method="GET",path="/tasks/9989",status="200"} 31
meilisearch_http_requests_total{method="GET",path="/tasks/999",status="200"} 36
meilisearch_http_requests_total{method="GET",path="/tasks/9990",status="200"} 28
meilisearch_http_requests_total{method="GET",path="/tasks/9991",status="200"} 1
meilisearch_http_requests_total{method="GET",path="/tasks/9992",status="200"} 1
meilisearch_http_requests_total{method="GET",path="/tasks/9993",status="200"} 2
meilisearch_http_requests_total{method="GET",path="/tasks/9994",status="200"} 2
meilisearch_http_requests_total{method="GET",path="/tasks/9995",status="200"} 14
meilisearch_http_requests_total{method="GET",path="/tasks/9996",status="200"} 30
meilisearch_http_requests_total{method="GET",path="/tasks/9997",status="200"} 31
meilisearch_http_requests_total{method="GET",path="/tasks/9998",status="200"} 31
meilisearch_http_requests_total{method="GET",path="/tasks/9999",status="200"} 36
```
