### ISSUE TITLE
Numeric typos are always considered with typo tolerance

### ISSUE THREAD

**Issue by JamesToothill** [meilisearch/meilisearch#3999]
**Describe the bug**
When you have typo tolerance enabled with a `oneTypo` setting (in our case of `4`), numeric typos are always considered.  

This means a search for example for:

"2001"

Gets results such as:

"2001: A Space Odyssey"
"2001: A Space Travesty" 
"Dracula 2000"
"Fantasia 2000"

**To Reproduce**
Steps to reproduce the behaviour:
1. Use an index with data that has years in the (searchable) title.
3. Set the `oneTypo` setting to `4` (or less)
4. Search for a year

**Expected behavior**
Algolia has a setting to disable this behaviour `allowTyposOnNumericTokens` which is default `true` but which we would set to `false`.

This allows us to search for:

"2001"

And get results such as:

"2001: A Space Odyssey"
"2001: A Space Travesty" 

But not irrelevant results such as:

"Dracula 2000"
"Fantasia 2000"

**Meilisearch version:**
v1.2.0

**Comment by macraig** [comment]
Hi @JamesToothill , thanks for opening up an issue! This is actually more of a feature request than a bug, so I'm transferring it to our Product repo for better tracking.

**Comment by macraig** [comment]
Closing in favor of https://github.com/meilisearch/product/discussions/688
