### ISSUE TITLE
[1.3.0] Panic: "the ranking rule exactness did not sort its bucket exhaustively"

### ISSUE THREAD

**Issue by Tarpsvo** [meilisearch/meilisearch#4006]
**Describe the bug**
Meilisearch panics when searching "usb-c k".

But when I search "usb-c kb" it works.

Same when searching "RTX 3060". Crashes. But "RTX 30601" works.

Is it something to do with my dataset?

I found these in the logs:
`thread 'tokio-runtime-worker' panicked at 'The ranking rule exactness did not sort its bucket exhaustively', milli/src/search/new/bucket_sort.rs:162:13`

**UPDATE:**
If I removed the "exactness" ranking rule, it now crashes with:
`thread 'tokio-runtime-worker' panicked at 'The ranking rule typo did not sort its bucket exhaustively', milli/src/search/new/bucket_sort.rs:162:13`

**To Reproduce**
Unsure what to do to provide a reproable dataset. Mine is quite large (ca 100k entries).

**Expected behavior**
No crash.

**Meilisearch version:**
1.3.0

**Comment by Kerollmops** [comment]
Hey @Tarpsvo 👋

Thank you very much for your bug report. Can you show me the JSON search request you are sending in more detail? Are you using the `attributesToSearchOn` field? If so, I will close this one in favor of #3995 and highly advise you to subscribe.

In the meantime. I would be thankful if you find a smaller dataset and a way to reproduce this bug. However, if you don't and can share your 100k documents with us (email or zip link), I would gladly debug Meilisearch with it.

**Comment by Tarpsvo** [comment]
Reproable dataset dump:
https://file.io/VaPur3ZZhOTZ

NB! One-time download link. Try to catch it and let me know if you didn't. :)

The query that causes the panic is "rtx 305". Reproduced using 1.3.1.

This is an example payload which causes the panic:
![image](https://github.com/meilisearch/meilisearch/assets/2018660/7f9bcd1b-afd3-4d18-8f89-67f0cd9d3e49)

With the response:
![image](https://github.com/meilisearch/meilisearch/assets/2018660/c393cf21-f9ff-4c2c-b168-5feddd273f69)

**Comment by Kerollmops** [comment]
Fixed by #4013.
