### ISSUE TITLE
and operation and exact match mode support

### ISSUE THREAD

**Issue by unihon** [meilisearch/meilisearch#4014]
eg: input "apple green",
I want just get docs with include "apple" and "green", and just match "apple" not  "apples", 
how can do this.

**Comment by curquiza** [comment]
Hello @unihon 

Can you try to disable typo tolerance?
https://www.meilisearch.com/docs/learn/configuration/typo_tolerance

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
