### ISSUE TITLE
Homebrew publish CI broken because of the new meilisearch formula path

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4015]
The homebrew-core repository has modified its Formula folder and split the files into folders with the first letter of the formula name. The issue is that we use the _mislav/bump-homebrew-formula-action_ Action in our release CI, and it is not up-to-date to follow this new path rule. I propose [using the `formula-path` setting](https://github.com/mislav/bump-homebrew-formula-action#action-inputs) to define where the Meilisearch Formula lies.

For the latest v1.3.2 release, I had to [do the Formula update by hand](https://github.com/Homebrew/homebrew-core/pull/140345). That wasn't that hard, but the CI must have done it automatically.

**Comment by curquiza** [comment]
Closed and fixed by #4016
