### ISSUE TITLE
version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by MaxKingPor** [meilisearch/meilisearch#4022]
**Describe the bug**
```
./meilisearch: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./meilisearch)
./meilisearch: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ./meilisearch)
./meilisearch: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./meilisearch)
./meilisearch: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./meilisearch)
```

**To Reproduce**
```
[root@VM-0-16-centos meilisearch]# uname -a
Linux VM-0-16-centos 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@VM-0-16-centos meilisearch]# ./meilisearch 
./meilisearch: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./meilisearch)
./meilisearch: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ./meilisearch)
./meilisearch: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./meilisearch)
./meilisearch: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./meilisearch)
[root@VM-0-16-centos meilisearch]# 

```

**Expected behavior**

**Screenshots**
![image](https://github.com/meilisearch/meilisearch/assets/43533178/e0299222-3b5f-4eec-8f93-501d44282444)

**Meilisearch version:**
meilisearch 1.3.2

**Additional context**
Linux VM-0-16-centos 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 28 15:37:28 UTC 2022

**Comment by MaxKingPor** [comment]
Can run under the "x86_64-unknown-linux-musl" target. 
Whether this target will be used in the release page？

**Comment by curquiza** [comment]
Hello @MaxKingPor 
Looks like your centos version is too old and do not contain the right version of Glibc that is the only C library dependency of Meilisearch

**Comment by truebit** [comment]
> Can run under the "x86_64-unknown-linux-musl" target. Whether this target will be used in the release page？

@MaxKingPor Could you please tell how to compile the x86_64-unknown-linux-musl target? I got the same problem here.
Tried the instructions in https://github.com/meilisearch/meilisearch/issues/559#issuecomment-605501263, but still not working.

**Comment by MaxKingPor** [comment]
> > Can run under the "x86_64-unknown-linux-musl" target. Whether this target will be used in the release page？
> 
> @MaxKingPor Could you please tell how to compile the x86_64-unknown-linux-musl target? I got the same problem here. Tried the instructions in [#559 (comment)](https://github.com/meilisearch/meilisearch/issues/559#issuecomment-605501263), but still not working.

Please tell me your Compile error messages.
