### ISSUE TITLE
search

### ISSUE THREAD

**Issue by artartart123412** [meilisearch/meilisearch#4036]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Meilisearch version:**
[e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by ManyTheFish** [comment]
Hello @curquiza and @artartart123412,
I'm closing this issue because it seems to be a misclick and we didn't get any response,

Don't hesitate to open a new issue with a detailed description if you see any bugs or irrelevant when using Meilisearch,

See you! 😊
