### ISSUE TITLE
HTTP Delete multiple item spec & standardization

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#404]
There are multiples ways to do deletions on multiples items on an API.

## Restful
**HTTP route:** `DELETE /items&ids=id1,id2,id3`
**Pro:** This is the rest way
**Cons:** There is a limit on the maximum number of items that can be deleted. (https://tools.ietf.org/html/rfc7230#section-3.1.1)
This is not possible !

## 1. Restful alternative
**HTTP route:** `POST /items/delete-xxx` body: `[id1,id2,id3]`
**Pro**: Infinite limit of items to delete. Not restricted to delete by id, it's possible to write a more complex structure. This used by some projects.
**Cons:** Could be considerate as ugly
**e.g.**
```
DELETE /documents/:id //delete ONE stop-word
DELETE /documents //delete ALL stop-words
POST /documents/delete-selection : //delete a selection of stop-word passed in the body
or POST /documents/delete
or POST /documents/delete-batch
```

## 2. Body inside DELETE
**HTTP route:** `DELETE /items` body: `[id1,id2,id3]`
**Pro:** Infinite limit of items to delete. Not restricted to delete by id, it's possible to write a more complex structure.
**Cons:** controversy about putting a body in a delete. RFCs don't specify anything (https://tools.ietf.org/html/rfc7231#section-4.3.5).
**e.g.**
```
DELETE /documents/:id //delete ONE stop-word
POST /documents/clear //delete ALL stop-words or
DELETE /documents/all //delete ALL stop-words
DELETE /documents : //delete a selection of stop-word passed in the body
```

---

For the routes with no ressources_ids (Settings/Synonyms/StopWords). The possibilities are different.

- `GET /ressource` Get the global ressource
- `PUT /ressource` Update/override all the ressource with the new one. It is necessary to `GET` before `PUT`
- `DELETE /ressource` Remove all the ressource content

**Comment by Kerollmops** [comment]
There is something invalid with the second solution: there is a conflict between the `DELETE /stop-words/:id` and the `DELETE /stop-words/all` routes. The `POST /stop-words/clear` route is neither valid because it is not self-explanatory, what tells de user that it will _delete all_ the stop-words as it is a `POST` ?

**Comment by curquiza** [comment]
After reading others blogs/posts, I have a name alternative for the *numero 1*:
`delete-batch` instead of `delete-selection`. Maybe more "English". I don't know what you prefer (if you like the num 1 option).

**Comment by Kerollmops** [comment]
I prefer the 1. with the `POST /stop-words/delete-batch` route.

**Comment by curquiza** [comment]
Same as kero, the 1 with `POST /stop-words/delete-batch`

**Comment by tpayet** [comment]
I would go with the first alternative with `POST /stop-words/delete-batch`

**Comment by bidoubiwa** [comment]
Other alternative : 
```
`GET /stop-words` => ['one',two']
`POST /stop-words` body :["the","and"] => overrides ['one',two']
`DELETE /stop-words` => 204 No Content (deleted all stop words)
```

**Comment by curquiza** [comment]
@bidoubiwa, pretty sure that's the current behavior on master. Am I wrong?

**Comment by qdequele** [comment]
> There is something invalid with the second solution: there is a conflict between the `DELETE /stop-words/:id` and the `DELETE /stop-words/all` routes, what if there is a stop-word `"all"`?
> The `POST /stop-words/clear` route is neither valid because it is not self-explanatory, what tells de user that it will _delete all_ the stop-words as it is a `POST`?

This is not true if we only use resources_ids. And if there is no id resource, it is probably because the complete entity is the resource?!

**Comment by Kerollmops** [comment]
I don't understand, in the `DELETE /documents/:id` route couldn't `:id` corresponds to `"all"` if a user wants to set this word as a stop-word for example? This will collide with this second route `DELETE /documents/all`?

**Comment by qdequele** [comment]
> wa, pretty sure that's the current behavior on master (not on 8.4). Am I wrong?

Currently we have:

`GET /stop-words` => ['one',two']
`PATCH /stop-words body` :["the","and"] => overrides ['one',two']
`POST /stop-words` => 204 No Content (deleted all stop words)

**Comment by bidoubiwa** [comment]
@curquiza No, for the moment it is like this

`PATCH /stop-words` and the delete route is `POST /stop-words` 

I want the delete route to be delete and to delete everything, 
and the post route to be ONE ressource so it overrides the previous stop-words.

**Comment by curquiza** [comment]
@qdequele  For me the `resource_id` of a stop-word is the stop-word itself. The stop-word is unique.

**Comment by bidoubiwa** [comment]
If the complete entity is the ressource than this would be the rest way : 

`GET /stop-words` => ['one',two']
`POST /stop-words` body :["the","and"] => overrides ['one',two']
`DELETE /stop-words` => 204 No Content (deleted all stop words)

**Comment by qdequele** [comment]
I assume that a stop-word is not an id but just a word in a array. This array is the global resource. Maybe it's a misunderstanding.
