### ISSUE TITLE
task register of SwapIndexes is called in an asyncronous context

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4040]
**Describe the bug**
When registering a swap indexes task, we do it in the asynchronous context without spawning a blocking task.
That could theorically starve the main thread if we end up being blocked by something that takes time in lmdb.

**Meilisearch version:**
Since the introduction of the swap index feature in v0.30

**Comment by curquiza** [comment]
Fixed by #4041 
will be released in v1.4.0-rc.1
