### ISSUE TITLE
After upgrading Meilisearch from 1.2.0 to 1.3.3 breaks search result

### ISSUE THREAD

**Issue by Jasperav** [meilisearch/meilisearch#4045]
**Describe the bug**
After upgrading from 1.2.0 to 1.3.3, a test failed and I am curious why the search results has been changed.

**To Reproduce**
Add index and update:

```
{
	"uid": "user",
	"primaryKey": "user_id"
}
```

Update index:

```
{
	"displayedAttributes":["user_id"],
	"rankingRules": [
		"typo",
		"proximity",
		"attribute",
		"sort",
		"exactness",
		"words"
	],
	"searchableAttributes": [
		"username"
	],
	"filterableAttributes": [
		"username"
	],
	"typoTolerance": {
		"minWordSizeForTypos": {
			"oneTypo": 3,
			"twoTypos": 6
		}
	}
}
```

Add this user:
```
		{
			"username": "Pietjuh_Bell",
			"user_id": "e7998ff3-fe7a-4291-8220-982ae604444d"
		}
```

Previously, searching for `Pietj_Bell` gave 1 result at Meilisearch 1.2.0, as expected by the configured type tolerance (2 typos allowed for 6 characters or more). Now it gives 0 results.

**Comment by ManyTheFish** [comment]
Hello @Jasperav,

It's an expected change, Meilisearch now splits the words around `_` (underscore), allowing the users to search for `bell`.
However, this change implies that `Pietj` is now too small to allow 2 typos, so `Pietjuh` can't be found.

The next version, V1.4, will introduce separator customization allowing the user to remove `_` (underscore) from the separators.

Don't hesitate to ask more questions if you need them, or close the issue if my comment answered it,
Thanks for your report,

See you!

**Comment by Jasperav** [comment]
@ManyTheFish Ok seems like 1.4 will fix my issues than, these are usernames and shouldn't be separated at all, thanks!

**Comment by Jasperav** [comment]
@ManyTheFish I still have a question about the PR and your comment: https://github.com/meilisearch/meilisearch/pull/3946#issuecomment-1668153942. Here you are mentioning that users should provide the list of nonSeparatorTokens themself (`you could eventually set the exhaustive list of separators`). 

For my usecase (username search where usernames can contain any character, which should never mean separation), should I first query the separator tokens myself and than update Meili? What if Meili updates with a new set of characters? Why isn't there an option to disallow token separating at all?

**Comment by curquiza** [comment]
Hello @Jasperav 

> should I first query the separator tokens myself and than update Meili?
You just have to send the separators you want to add, not to query the original separators of Meilisearch

> What if Meili updates with a new set of characters? 
If a new Meilisearch version adds new separators, it will be automatically added to the "original" list. But it does not happen often, and you will be informed in the changelogs

>Why isn't there an option to disallow token separating at all?
You will be also able to remove separators 😊 

Check out the [changelogs](https://github.com/meilisearch/meilisearch/releases/tag/v1.4.0-rc.0) we create for the first RC of v1.4.0 to be fully aware of what will happen in v1.4.0 next Monday

**Comment by ManyTheFish** [comment]
Hello @Jasperav,

when you speak about username, do you speak about a specific field that contains characters that could be considered separators but shouldn't be in this specific field?
Or, do you have usernames anywhere in your documents and you want some default separators like underscore (`_`) or dash (`-`) to no more be considered separators?

Thanks!

**Comment by Jasperav** [comment]
@ManyTheFish I have an index which contains a username field. Usernames can contain any characters, this means that I don't want any separators to be used.
