### ISSUE TITLE
movies.json crash when imported on Windows

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4059]
Looks like a user reported a crash here: https://github.com/meilisearch/meilisearch/issues/3800#issuecomment-1713394918

When importing the [movie.json dataset](https://www.meilisearch.com/movies.json) available in the [getting started](https://www.meilisearch.com/docs/learn/getting_started/quick_start) of the docs, Meilisearch return an `internal` error

The movie.json import perfectly works on Linux and macos.

👉 Windows bugs are not the priority for the Meili team, so we need someone from the community to check if they can reproduce the bug on their machine, and then, someone to fix the bug. Please try to reproduce the bug with the latest version of Meilisearch

Reported on v1.3.3

**Comment by ahmednfwela** [comment]
I started a local windows instance downloaded from https://github.com/meilisearch/meilisearch/releases/download/v1.3.3/meilisearch-windows-amd64.exe
with
`./meilisearch-windows-amd64.exe --master-key=masterKey`
 and ran all the integration tests in the dart repository https://github.com/meilisearch/meilisearch-dart 

here are the results:

1. any call to `updateFilterableAttributes` AFTER documents are added, crashes with an internal error:
    ```
    thread 'indexing-thread:7' panicked at 'the allocator is unable to allocate that much memory (1428747712 bytes requested)', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\grenad-0.4.4\src\sorter.rs:350:9
    stack backtrace:
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    Rayon: detected unexpected panic; aborting
    ```
    and the instance is bricked, meaning if I restart it again, it crashes with the same error.
    
    btw I have no idea why is it trying to access `C:\Users\runneradmin`, since it's not my user name.
    
    I suppose there is an issue with re-indexing documents in general on windows.

    also it takes VERY long to add documents in general on windows vs docker
2. all other tests are working, including document addition in bulk/patches and updating index settings BEFORE documents are added.

**Comment by curquiza** [comment]
Thank you very much @ahmednfwela, it will help the users coming week to fix the issue.
In more general I recommend using Linux in production with Meilisearch, this is where we do most of our tests.

Also to ease your production with Meilisearch, you can use our [cloud offer](https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=github&utm_medium=meilisearch) to manage Meilisearch in an easier way. The migration to another version of Meilisearch can only be done with one click.

**Comment by curquiza** [comment]
Can someone check if the issue is still present with v1.6.0?

**Comment by Elkiwa** [comment]
Unlike the previous indicated error, I failed at [Adding movies.json](https://www.meilisearch.com/docs/learn/getting_started/quick_start#add-documents)

```pwsh
curl -X POST 'http://localhost:7700/indexes/movies/documents?primaryKey=id' -H 'Content-Type: application/json' -H 'Authorization: Bearer aSampleMasterKey' --data-binary movies.json
{"message":"The `json` payload provided is malformed. `Couldn't serialize document value: expected value at line 1 column 1`.","code":"malformed_payload","type":"invalid_request","link":"https://docs.meilisearch.com/errors#malformed_payload"}
```

version: v1.6.2

**Comment by ahmednfwela** [comment]
that's because you forgot the `@` before `movies.json`

```
curl \
  -X POST 'http://localhost:7700/indexes/movies/documents?primaryKey=id' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer aSampleMasterKey' \
  --data-binary @movies.json

```

**Comment by Elkiwa** [comment]
> that's because you forgot the `@` before `movies.json`
> 
> ```shell
> curl \
>   -X POST 'http://localhost:7700/indexes/movies/documents?primaryKey=id' \
>   -H 'Content-Type: application/json' \
>   -H 'Authorization: Bearer aSampleMasterKey' \
>   --data-binary @movies.json
> ```
Oh, sorry. I thought it would work on PowerShell also, but the '@' sign only works in Bash and stated on Quick start page already.

I finished executing all the steps on Quick start page and seems like no issue.

**Comment by curquiza** [comment]
Thank you @Elkiwa 

Can I close the issue or @ahmednfwela you still have the problem with v1.6.2?

**Comment by ahmednfwela** [comment]
nope, all good

**Comment by curquiza** [comment]
thank you for your reactivity @ahmednfwela 
a pleasure to have you in the community
