### ISSUE TITLE
About speeding up the indexing processes

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4071]
## The difference-based indexing

The main issue right now is that a lot of database is written to disk even if we are only modifying a single filterable attribute of a document. The current indexing process deletes the documents and reindexes them from scratch. If only the `price` field is modified, the whole `description` field will be reindexed. It could be much better regarding the number of I/O operations if only the subset of changes in the databases could be modified on disk.

Computing the internal databases of the documents that are added or updated, computing the internal databases of the current versions of the documents, and computing the difference between them: extracting the subset of entries that must be modified in the final LMDB database.

<details>
  <summary>Notes about the different databases</summary>

  - [ ] Modify the grenad library to be able to delete entries when merging.
  - [ ] Create a document with only the altered fields by the new version (only `title` if it is modified).
  - [ ] Modify the indexing system to be able to tell it only to index the subset fields.
  - [ ] Put the deletion and addition entries into the same grenad entry (using an `obkv` special `Key` enum).
  - [ ] What about the prefix databases? Can we still compute them?
</details>

## Deletion Optimisations

When we want to delete a document, the current deletion process iterates over the whole set of entries of all of the internal databases, and deserializes the bitmaps values to remove the document IDs corresponding to the documents to delete. This is slow and CPU-intensive. We reduced the impact of this deletion method by introducing the soft-deletion system, which is a system that puts a tombstone of the documents to delete. This tombstone is used at search/read-time to ignore the documents that are considered deleted. When a large enough number of documents are soft-deleted, we decide to delete them effectively and execute the first detailed process.

The _difference-based indexing_ solution would be the first step in making the deletion more efficient. This new method would be able to expose the **small** subset of internal database entries that must be modified, either for indexing new documents or deleting them.

## Multithreading the grenad sorter

TBD

## Check the correctness of the new indexing algorithms

TBD We must create tools to ensure the new internal database content remains the same after modifying the algorithms.

**Comment by dureuill** [comment]
This work is set to remove soft-deletion, which is [mentioned in the documentation](https://www.meilisearch.com/docs/learn/advanced/storage#soft-deletion) and so will impact docs (added relevant label)

**Comment by curquiza** [comment]
Discussed with @Kerollmops we can close this since 2 first sections have been done in v1.6.0
And the other ones have not been defined yet -> will be done in other issues.
