### ISSUE TITLE
Make internal documents ids monotonical

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#408]
Currently, the JSON documents IDs are transformed into strings and hashed [using a `SipHasher`](https://docs.rs/siphasher) to produce a "unique" 64bit hash, [this is definitely not enough to avoid collisions](https://lemire.me/blog/2019/12/12/are-64-bit-random-identifiers-free-from-collision/).

We must produce monotonic (incremental) unique IDs, keeping two LMDB databases, one for the relation internal monotonic ID -> JSON original string ID, and another for the reverse relation.

When a document is given to the indexer, its ID will be interpreted as a string, and compared to those in the database, if it already exists use it, or use a non-existing one instead (filling gaps).

When a document must be removed, interpret its original ID as a string, search for its internal ID and remove it from the database, and from the two ways IDs databases.

This solution would permit us to store the `DocumentId` in an u32, helping us reduce [the DocIndex struct size](https://github.com/meilisearch/MeiliSearch/blob/3d19f566b64b9636d57d383cd25bf87289bbf751/meilisearch-types/src/lib.rs#L25-L41), from 128bits to 96bits which is... useless as it will be rounded to 128bit anyway...

**Comment by Kerollmops** [comment]
I thought about the size of the structs and it seems to be possible to divide by 2 the size of the [`DocIndex`](https://github.com/meilisearch/MeiliSearch/blob/11b684114d1d8a656b0bad153c8b7bf746d215a7/meilisearch-types/src/lib.rs#L25-L41) (the postings lists). By using a u32 to represent the [`DocumentId`](https://github.com/meilisearch/MeiliSearch/blob/11b684114d1d8a656b0bad153c8b7bf746d215a7/meilisearch-types/src/lib.rs#L15) like I said above, and by limiting a little more the length of the documents and the number of words we would be able to represent the matching attribute, and the matching position with a u16 instead of two.  The same technique can be used for the `char_index/length`.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=00094c69ab4a55ab3e753d7f48dd2a9a

**Comment by Kerollmops** [comment]
Another advantage of that is that documents additions will be way faster. Updates times is mostly spent in the postings lists updates, doing an union of the `DocIndex`es, if we make the documents ids monotonical, those unions will only be appends on the previous postings lists, no more interlivings.

**Comment by qdequele** [comment]
Closed by #696
