### ISSUE TITLE
distinctAttribute interferes with pagination offset, always starts from 0

### ISSUE THREAD

**Issue by montassar-vaionex** [meilisearch/meilisearch#4083]
I'm encountering an unexpected behavior when combining distinctAttribute with pagination (offset and limit) in MeiliSearch.

"meilisearch": "^0.35.0",

**Comment by curquiza** [comment]
Hello @montassar-vaionex 

An issue already exists, I close this one in favor of https://github.com/meilisearch/meilisearch/issues/4078

Also, Meilisearch v0.35.0 does not exist. It's probably the version of the SDK you use.
The Meilisearch version can be gotten by using this route: https://www.meilisearch.com/docs/reference/api/version
