### ISSUE TITLE
Make dump import process faster

### ISSUE THREAD

**Issue by irevoire** [meilisearch/MeiliSearch#4087]
**Describe the bug**
We found out that some dumps are really slow to import for no clear reason.
A customer sent us a dump that was taking 2h to import on my machine and multiple days on the cloud (it never finished, actually).

On a first investigation, I found out that most of the time was spent on the `read` syscall inside of the grenad operation.
![image](https://github.com/meilisearch/meilisearch/assets/7032172/bbb27f6d-3359-4897-85e8-e1b44515098c)

**To Reproduce**
1. Create a dump with indexes that contain a lot of documents, each containing a lot of text
2. import the dump

**Expected behavior**
Is fast.

**Meilisearch version:**: all

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/4089
