### ISSUE TITLE
Document with an identifier with several words

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#409]
When there is a document with an identifier with more than one word, for example:
```json
[
    {
        "objectId": "toto et titi",
        "title": "Title 0",
        "description": "Description 0"
    },
    {
        "objectId": 3,
        "title": "Title 3"
    },
    {
        "objectId": 2,
        "title": "Title 2"
    },
    {
        "objectId": 1,
        "title": "Title 1"
    }
]
```

- the route `GET /indexes/:uid/documents/toto%20et%20titi` returns a 404
- the route `DELETE /indexes/:uid/documents/toto%20et%20titi` returns an `updateId`, the operation is marked as proccessed, but the document is not deleted.

**Comment by qdequele** [comment]
closed in favor of #416

**Comment by bidoubiwa** [comment]
documentation: meilisearch/documentation#111

**Comment by bidoubiwa** [comment]
documentation: meilisearch/documentation#104
