### ISSUE TITLE
Flag to disable front integration

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#411]
Add a flag to disable the front.
Flag: `--no-web-interface`

**Comment by MarinPostma** [comment]
@meilisearch/integration-team is this still something we want to do?

**Comment by curquiza** [comment]
It could be great when you are running MeiliSearch in production.

**Comment by MarinPostma** [comment]
I will write the spec :)

**Comment by eskombro** [comment]
I just came by to say: +1
