### ISSUE TITLE
ERROR: Impossible to get the latest stable version of Meilisearch.

### ISSUE THREAD

**Issue by iodrift** [meilisearch/meilisearch#4119]
**Describe the bug**
Following the standard installation instructions on Lubuntu VM yields ERROR: Impossible to get the latest stable version of Meilisearch.

**To Reproduce**
1. curl -L https://install.meilisearch.com | sh

yields:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4352  100  4352    0     0  10979      0 --:--:-- --:--:-- --:--:-- 10979
Downloading Meilisearch binary v1.4.1 for linux, architecture amd64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

ERROR: Impossible to get the latest stable version of Meilisearch.
Please let us know about this issue: https://github.com/meilisearch/meilisearch/issues/new/choose

In the meantime, you can manually download the appropriate binary from the GitHub release assets here: https://github.com/meilisearch/meilisearch/releases/latest

**Expected behavior**
Installation

**Comment by curquiza** [comment]
Hello @iodrift 

Can you try now?
We released a new latest version of Meilisearch like 10min ago -> https://github.com/meilisearch/meilisearch/releases/tag/v1.4.1

GitHub updated their latest "tag" on our release before the CIs end to push the assets of the release. They are available now

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
