### ISSUE TITLE
Get API Key on Web Interface

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#412]
The web interface needs the permission to access all indexes (to fetch the list of indexes).
If the web interface does not have the permission, we should display a pop-up (or a field) to get the right key and use the front.

**Comment by eskombro** [comment]
I don't understand, do you mean that the user should be able to `retrieve` a key, or that there should be a field where he can `input` a key in order to use the web interface when a Master Key is set.

The second option seems like very easy to implement, and quite useful!

**Comment by curquiza** [comment]
Indeed, it's the second option!

**Comment by LuisRodriguezLD** [comment]
My team is currently in the process of moving to meilisearch but this is feature is important for us. If anyone could point me to the right direction I can try to make a PR. Thanks!

**Comment by curquiza** [comment]
Hello @LuisRodriguezLD!

Glad to read your team wants to use MeiliSearch 😁 If you have any questions, feel free to post on [our forum](https://github.com/meilisearch/MeiliSearch/discussions). If you need direct chatting, join us at [our Slack](https://slack.meilisearch.com/).

If I'm not wrong, the feature [is already available on master](https://github.com/meilisearch/MeiliSearch/pull/732). If you need it right now, you can use it by [compiling MeiliSearch from source](https://docs.meilisearch.com/guides/advanced_guides/installation.html#installation) (tab "Source").
If you can wait for 1 week, it will be available in the next release of MeiliSearch (v0.11.0) 😉

**Comment by qdequele** [comment]
Closed by #732
