### ISSUE TITLE
Simplify the export of Puffin reports

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4121]
Related product discussion: https://github.com/meilisearch/product/discussions/693

## Motivation

We want to simplify the export of Puffin reports by exposing a new experimental feature called `exportPuffinReports`. This experimental feature can be enabled from the `/experimental-features` route.

## Usage

https://github.com/meilisearch/product/discussions/693

## TODO

The PR is available here: https://github.com/meilisearch/meilisearch/pull/4073

## Impacted teams

@meilisearch/docs-team
cloud-team not involved -> the created file is on the machine, so not accessible for the cloud users. And activate it by default would impact negatively the indexing performance of the user instance

**Comment by curquiza** [comment]
Merged by #4073

**Comment by curquiza** [comment]
Pinging @meilisearch/cloud-team here.

- Front end people: this feature should NOT be activated by cloud users on the dashboard. This will only slow down their machine and generate a file they will not be able to access
- Infra/back-end & support people: you might need to activate this feature sometimes in debugging session to understand with engine team what is happening on specific use-case. Not something to stop a fire, but can help for later investigation.
