### ISSUE TITLE
Make the dump creation cancellable

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4157]
Currently, there is no point in a dump creation where we can cancel a dump creation.

That means if a dump creation is taking a really long time to process, the whole engine is stuck, registering tasks it can't process forever.
That's a real issue because we've encountered some dump creations taking days to process, during which a lot of enqueued tasks stacked up, and then the whole instance was dying under its huge number of enqueued tasks.

**Comment by curquiza** [comment]
@meilisearch/docs-team here, I don't know if it's something you mentioned in the docs
