### ISSUE TITLE
Change documents routes

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#416]
### Routes
The current routes are kept. We only proceed to a naming change: 
`POST /indexes/:uid/documents/delete` > `POST /indexes/:uid/documents/delete-batch`

### Uploading documents

- The document id must contain only `A-Z a-z 0-0` and `-_`. This is to avoid encoding in the url path in the case of a multi-word id.
- The route `POST /indexes/:uid/documents` can take a query parameter `&identifer=field_name` to specify at the first indexation the main identifier. If an identifier is already defined, this query parameter is ignored.

**Comment by bidoubiwa** [comment]
documentation: 
meilisearch/documentation#104
meilisearch/documentation#105
meilisearch/documentation#102
