### ISSUE TITLE
Incorrect Results for phrase in Japanese

### ISSUE THREAD

**Issue by uintaam** [meilisearch/meilisearch#4162]
**Describe the bug**
When searching for the Japanese phrase "有料配信" we do not see the results with "有料配信" in the document but instead get seemingly unrelated results.

**To Reproduce**
1. Create a new index "test_index"
2. Upload the attached documents "test-documents.json" (a small subset of our index showing the behavior). 
[test-documents.json](https://github.com/meilisearch/meilisearch/files/13098729/test-documents.json)

3. All attributes are the default for a new index. Searchable attributes are ["*"] etc.
4. Search 有料配信 and see that of the three documents, the two without the text show up.

**Expected behavior**
The document with the name "無観客有料配信イベント定期公演 SEIZE THE DAY vol.9" is expected to show as it contains "有料配信"; but it does not show.

**Screenshots**
![Screenshot 2023-10-24 at 10 29 46](https://github.com/meilisearch/meilisearch/assets/295346/337f30b5-d89a-49d8-830f-6cad918f303d)
![Screenshot 2023-10-24 at 10 45 18](https://github.com/meilisearch/meilisearch/assets/295346/65f07136-6e87-426f-96f3-8fdd0ddd6165)

**Meilisearch version:**
Meilisearch Cloud v1.4.0

**Additional context**
If we search the full name, or just the full Japanese text then the correct document will show i.e. "無観客有料配信イベント定期公演"

**Comment by curquiza** [comment]
Hello @uintaam 

Thanks for the report. This behavior is currently expected. Currently, when Meilisearch cannot make the distinction between Chinese or Japanese languages, Chinese tokenization is applied by default. This is what happened in your case and led to this issue.

**Short term solutions**
I see you are a Cloud user: you can contact Meilisearch Cloud and see with them if it's possible to use [Docker image provided on this branch](https://github.com/meilisearch/meilisearch/pull/3882) instead of the classic v1.4.0. This is the same as v1.4.0 (so as safe as v1.4.0) but with a prioritization for Japanese

**Long term solutions**
Pinging PMs @macraig @gmourier 
As Algolia does, we might need to provide a setting to let the users define the language(s) of their datasets. This way, Meilisearch will be able to adapt and behave as expected based on the defined language.
I opened a [product discussion](https://github.com/orgs/meilisearch/discussions/702) here to ensure our product team is aware of it

**Comment by uintaam** [comment]
Allowing it to be defined in the data sets is essential as our site also has traditional Chinese and Chinese Simplified documents with Japanese, all in different arrays in the JSON.

**Comment by curquiza** [comment]
@uintaam 
So if I understand correctly your usage, you have different language in the same documents? or in different document or index?
Can you show us a basic example of one of your documents (without the data, but at least which language is associated to each document or each field)?

**Comment by uintaam** [comment]
I'm sorry for not getting back to you sooner. If you take a look at this page, for example, we have events on our system that are in English and Japanese (sometimes other languages) https://zaiko.io/event/355725

The structure is a bit of a mess at the moment, in Algolia we would take the fields as a language, but we can maybe be smarter than that

```
{
  "name": "Riot Blue PRESENTS 舞弦ウラ SOLO ONEMAN LIVE【ハルハレウララ】",
  "poster": "https://media.zkocdn.net/pf_1/1_42l7thkthqiayq43fbfbl",
  "name_reading": [
    "riotbluepresentsまいつるうらsoloonemanlive【はるはれうらら】",
    "riotbluepresentsマイツルウラsoloonemanlive【ハルハレウララ】",
    "riot blue presentsmai tsuru ura solo oneman live haruhareurara",
    [
      "Riot",
      "Blue",
      "PRESENTS舞",
      "弦",
      "ウラ",
      "SOLO",
      "ONEMAN",
      "LIVE",
      "【",
      "ハルハレウララ",
      "】"
    ]
  ],
  "genres": [
    "ライブ",
    "ポップ",
    "ロック"
  ],
  "genres_en": [
    "Live",
    "Pop",
    "Rock"
  ],
  "name_en": "Riot Blue PRESENTS Ura Mao SOLO ONEMAN LIVE【haruhareurara】",
  "name_ko": "Riot Blue PRESENTS 마오우라 SOLO ONEMAN LIVE【하루하레우라라】",
  "objectID": "355725"
}
```
The structure could be improved, though, to something like this. Or, really, any format.

```
{
  "poster": "https://media.zkocdn.net/pf_1/1_42l7thkthqiayq43fbfbl",
  "ja": {
    "name": "Riot Blue PRESENTS 舞弦ウラ SOLO ONEMAN LIVE【ハルハレウララ】",
    "name_reading": [
      "riotbluepresentsまいつるうらsoloonemanlive【はるはれうらら】",
      "riotbluepresentsマイツルウラsoloonemanlive【ハルハレウララ】",
      "riot blue presentsmai tsuru ura solo oneman live haruhareurara",
      [
        "Riot",
        "Blue",
        "PRESENTS舞",
        "弦",
        "ウラ",
        "SOLO",
        "ONEMAN",
        "LIVE",
        "【",
        "ハルハレウララ",
        "】"
      ]
    ],
    "genres": [
      "ライブ",
      "ポップ",
      "ロック"
    ],
  },
  "en": {
    "name": "Riot Blue PRESENTS Ura Mao SOLO ONEMAN LIVE【haruhareurara】",
    "genres": [
      "Live",
      "Pop",
      "Rock"
    ],
  },
  "ko": {
    "name": "Riot Blue PRESENTS 마오우라 SOLO ONEMAN LIVE【하루하레우라라】",
  },
  "objectID": "355725"
}
```

**Comment by uintaam** [comment]
Note, I updated the structure above with what we are currently using.

**Comment by curquiza** [comment]
Thanks @uintaam for the information!

**Comment by uintaam** [comment]
Any news on if a resolution will make it in to a future version?

**Comment by curquiza** [comment]
Hello @uintaam, having a better language support (with a setting?) is a solution we explore at the moment.
We don't know yet if we can prioritize in the coming week, but it's on our roadmap for the next months.

**Comment by eve0415** [comment]
> having a better language support (with a setting?) is a solution we explore at the moment. We don't know yet if we can prioritize in the coming week, but it's on our roadmap for the next months.

Hello, any information we can get about the language support with a settings?
We are planning to have few translations for *one* document each, and are considering of separating by index or having everyting in the same document by using (nested) objects.
(or, actually finding some other alternatives)

Example of nested objects:

```json
{
  "description": { "en": "Hello", "ja": "こんにちは" } 
}
```

Another example:

```json
{
  "en": { "title": "Hello", "description": "Hello World" }.
  "ja": { "title": "こんにちは", "description": "こんにちは 世界" } 
}
```

I understand if this isn't planned (yet), but I also sould like to know which way would have better performances for future reference. Depending on context, some Japanese translations would have some words in English/Romaji, and it would be bother if the search result would hit on Japanese translation when searching for English users and vice versa.

**Comment by ManyTheFish** [comment]
Hello @eve0415,
It's okay to mix languages in Meilisearch if they don't share the same script; for instance, mixing English and Japanese shouldn't be an issue. However, mixing Chinese and Japanese is not a good idea because it's hard for Meilisearch to assign a Kanji character as Chinese or Japanese. In this last case, I suggest separating the documents into different indexes.
If you have some issues with the Japanese support, more precisely with the Kanji detection, I suggest using the dedicated docker image to resolve this issue. I put below the threads with all the versions:
https://github.com/meilisearch/meilisearch/pull/3882

We are not sure about the future settings' final shape, but they will allow the user to list the detectable languages in the index, avoiding any miss-detection from Meilisearch.

**Comment by curquiza** [comment]
Hello @eve0415 and @uintaam 

Just to let you know we have released in [v1.10.0](https://github.com/meilisearch/meilisearch/releases/v1.10.0) the ability to set up your language in the settings: https://www.meilisearch.com/docs/reference/api/settings#localized-attributes

I close this issue, let us know if it does not fix, I will re-open.

**Comment by YukiKubota0605** [comment]
Hello @curquiza

I'm surprised to see amazing setting was released like this because I want to use meilisearch with Japanese Lang.
By the way, when example codes are publied on https://www.meilisearch.com/docs/reference/api/settings#example-19 ?
I need  example codes of Java.

**Comment by curquiza** [comment]
Hello @YukiKubota0605 
So far, the localizedAttributes settings in not available in Java SDK: https://github.com/meilisearch/meilisearch-java/issues/770
If someone from the community opens a PR for it, I will review it as soon as possible and will do a release right after

In the meantime, you can still update this setting with cURL command, of course, to update your settings of Meilisearch. You just have to do it once and the settings will be saved into Meilisearch

**Comment by YukiKubota0605** [comment]
Hello @curquiza 
Thank you for your reply.
I will use cURL command until Java SDK will come to be availabel.
I hope this setting is avaliable via Java SDK in the future!

**Comment by Barabasbalazs** [comment]
@YukiKubota0605 @curquiza  I implemented support for this in the Java sdk. See -> https://github.com/meilisearch/meilisearch-java/pull/788
