### ISSUE TITLE
Delete tasks api doesnt reduce the `tasks/data.mdb` filesize

### ISSUE THREAD

**Issue by jackbit** [meilisearch/meilisearch#4165]
**Describe the bug**
I have hundred thousands documents that needs to be updated every 5 minutes and it can lead out of storage because:

- The file `data.ms/tasks/data.mdb` keeps getting bigger even than the folder `data.ms/indexes` its self.
- The `tasks/data.mdb` is not reduced after running delete tasks api

```
curl \   
  -X DELETE 'http://localhost:7700/tasks?statuses=*' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer SecretAuthKey'
```

**Expected behavior**
Delete tasks should reduce the `tasks/data.mdb` or add any option to not store tasks which succeeded, failed and canceled `meilisearch --no-task-storage`

**Meilisearch version:**
1.3.3

**Comment by curquiza** [comment]
Hello @jackbit 

this is indeed expected. Meilisearch use LMDB and by default, regarding the tasks, the deletion of tasks will not free space, but would make more room for new tasks

Even if it's not intuitive, changing this is not a trivial change for the engine team, so not something we plan to change

In the meantime, what we recommend is to 
- flush your tasks
- once it's fully done, create a dump
- shut down meilisearch
- remove your data.ms
- relaunch Meilisearch by importing the just created dump
-

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
