### ISSUE TITLE
Rewrite the stop-words endpoint

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#417]
We're going to start with a classic get/set/delete.
*All stop-words = 1 resource.*
All routes take on a level of depth. The new routes will therefore be:
- `GET /indexes/:uid/settings/stop-words` : get all stop words (so the resource)
- `POST /indexes/:uid/settings/stop-words`: replaces all current stop-words with those in the body
- `DELETE /indexes/:uid/settings/stop-words`: delete all stop-words (so the resource)

**Comment by bidoubiwa** [comment]
documentation: meilisearch/documentation#107
