### ISSUE TITLE
Introduce meilitool: a CLI tool to do operations on Meilisearch

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4175]
## Motivation

Sometimes Meilisearch gets stuck doing tasks processing or dump export or anything else. The cloud team can suffer from that and, as a result, our customers. I want to introduce a new command line interface tool to clear the tasks queue and export a dump without enqueuing it in the tasks queue.

## Usage

You'll find the usage on https://github.com/meilisearch/meilisearch/pull/4167 and specifically in [this part of the code](https://github.com/meilisearch/meilisearch/blob/d6da79324b056245b7563972be166e35138e12f1/meilitool/src/main.rs#L25-L65). That's what is outputted from a `--help` call. The `meilitool` binary is located in the `/bin` folder according to the Dockerfile, alongside the `meilisearch` one.
```bash
cd /bin
./meilitool --help
```

## TODO

- [ ] Release a prototype
- [ ] If prototype validated, merge changes into `main`
- [ ] Update the spec

## Impacted teams

@meilisearch/cloud-team: Could you tell me, on the PR, if the changes in the Dockerfile fit your needs? You must keep the `meilitool` binary file with the `meilisearch` one.

**Comment by curquiza** [comment]
Closed by #4167

will be released into `rc2` and then into the official release `v1.5.0` on November 20th
