### ISSUE TITLE
Rewrite the synonyms endpoint

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#418]
We're staying on a get/set.

But all routes take a level of depth: 
- GET `/indexes/:uid/settings/synonyms`: displays ALL synonyms.
- POST `/indexes/:uid/settings/synonyms`: replaces ALL synonyms.
- DELETE `/indexes/:uid/settings/synonyms`: reset ALL synonyms.

**Comment by bidoubiwa** [comment]
@qdequele I need precisions on the body of the POST route.

**Comment by bidoubiwa** [comment]
I just read your code and apparently proposition A is the one that has been chosen. 

documentation: 
meilisearch/documentation#111
