### ISSUE TITLE
Meilisearch do not thrown a error when queried with a wrong-sized vector

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4201]
I stored 384 dimensions vectors into the Meilisearch vector store and queried the engine with a 1536 one. Meilisearch didn't return any error and answered with very bad results. It took me some time to understand the issue.

**To Reproduce**
1. Send X-dimension vectors.
2. Query with Y-dimension vectors where X is not Y.
3. Recieve useless results.

**Expected behavior**
Meilisearch should have thrown an error when querying it.

**Meilisearch version:**
I was on main (48865470d) but the problem has been here since the release of the vector store feature.

**Comment by dureuill** [comment]
Should the fix target v1.6 or the upcoming v1.5?

**Comment by dureuill** [comment]
Fix on v1.5 by #4204
