### ISSUE TITLE
Review keys and permission; Fine tune authorization layer

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#421]
- The current title "Keys" in the doc will be "Permissions" or "Authorization".
- The roads remain the same
- Concerning the attributes of a key object
    - `acl` becomes `role` and corresponds to a role + its permissions in camelCase (for example: `ownerWrite`). See below for roles and permissions.
    - `key` becomes `token`
- The new roles:
    - **Owner**: Indexes - Keys - SysInfo - General statistics
    - **Admin**: Settings of an index - Stats of an index
    - **Maintainer**: Documents
    - **User**: Search
- The roles operate in a cascade from top to bottom.
E.g.: a Maintainer also has the rights of the User.
- The permissions on each:
    - Read (GET)
    - Write (`POST` `PUT` `PATCH` `DELETE`)
- The User role is the only role accessible in Read-only. A user who enters `userWrite` will automatically end up with a `userRead` key.
- The `/version` and `/health` routes do not require permission.

**Comment by bidoubiwa** [comment]
@qdequele will it be Permissions or Authorization ?

**Comment by curquiza** [comment]
The `/health` route does not require permission ONLY for the `GET` one. The `PUT` one still needs permission.

**Comment by Immortalin** [comment]
@qdequele would you be willing to accept a pull request for simple JWT claim based access control? I am considering writing a proxy in front of mellisearch for an application I am building but it might be easier to just send a pull request and add the feature directly to Mellisearch.

**Comment by elgalu** [comment]
@Immortalin did you write the JWT integration?

**Comment by Immortalin** [comment]
@elgalu nope I switched to Algolia.

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/82-authorization-keys?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
