### ISSUE TITLE
The delete documents by batch route ignores the payload limit setting

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4224]
The `POST /indexes/{index_uid}/documents/delete-batch` route ignores the `--http-payload-size-limit` parameter and restricts the payload to be 2 Mib. The reason is highly due to [the default `Json` actix deserializer limit](https://docs.rs/actix-web/4.3.1/actix_web/web/struct.JsonConfig.html#method.limit).

**To Reproduce**
Send more than 2 MiB of JSON document IDs in a single call on the batch document deletion route.

**Expected behavior**
The engine must accept the limit defined by the `--http-payload-size-limit` parameter.

**Screenshots**

**Meilisearch version:**
Every version of Meilisearch since we use Actix Web.

**Comment by Karribalu** [comment]
Hey @Kerollmops ,
I reproduced the issue with a really large dataset.
I confirm that this fix works when the payload is more than 2MiB as I have tested with the IDs payload having 2.7MiB.

<img width="1291" alt="Screenshot" src="https://github.com/meilisearch/meilisearch/assets/42462452/807a6f00-06c1-4904-bd1a-259611bff46a">
