### ISSUE TITLE
Task Queue Webhook

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4236]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Task-Queue-Webhook-2c9ff1c6b820489399194539d37c4d11#b9b5f11827394793994dc514a0f44996)
Related product discussion: N/A
Related spec: WIP

## Motivation

Introduce a configuration for a webhook url that will be called whenever a task finishes so a third party can be notified. It will be used to compute some of the required metrics for the [Monitoring Metrics v1](https://github.com/4782d56795c043799dde33309e73a20f?pvs=25) project.

## Usage

https://www.notion.so/meilisearch/Task-Queue-Webhook-64b4b5eaf80e45948357d9b16c584c4c

## TODO

- [ ] Release a prototype
- [ ] If prototype validated, merge changes into `main`
- [ ] Update the spec

## Impacted teams

@meilisearch/docs-team

**Comment by curquiza** [comment]
Closed by #4238 and already integrated into rc3
