### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#424]
> Faceted search is a technique which involves augmenting traditional search techniques with a faceted navigation system, allowing users to narrow down search results by applying multiple filters based on faceted classification of the items. ([Wikipedia](https://en.wikipedia.org/wiki/Faceted_search))

Facets are used to create categories on a select group of attributes. For example, on an index of books, useful facets might be author and genre. 

### Possibilities: 
- List all the possible values for the selected attributes, and return contextual values and counts with each search result
- Compute a facet count for each value (number of records matching each value of the attribute)

### How it's work
Attributes for faceting must be indexed in a separate index. Values can only be `String`/`Vec<String>`. 
It must be easy to retrieve during a search all the facets and their number of occurrences

**Comment by MarinPostma** [comment]
closing in favor of #625
