### ISSUE TITLE
Compatible for minio storage system

### ISSUE THREAD

**Issue by Jiaget** [meilisearch/meilisearch#4241]
**Describe the bug**
I deployed Meilisearch in Kubernetes with [csi-s3](https://github.com/yandex-cloud/k8s-csi-s3) storage class as storage support.

It was I sent an AddDocuement request to Meilisearch during my usage and received an error message `MeilisearchApiError Message: No such file or directory (os error 2) at path \"/meili_data/./data.ms/update_files/.tmpsvj5ql\`

I digged into the bug, and found out the exact reason:
Meilisearch will create a file in  dir `/data.ms/update_files` when it receive a write request(add docuemnt/update document). After the write task finish, the temple file in update_files will be deleted by the Meilisearch. 
It runs well in some file system, but it will lead to a bug in minio storage system or something based on mini(like csi-s3).
As the [MinIO Trims Empty Prefixes on Object Removal](https://min.io/docs/minio/linux/reference/minio-mc/mc-rm.html#id11) describes, when Meilisearch delete the last file in `/data.ms/update_files`, the dir `/update_files` will be deleted by the storage system, and the next write request will be refused by the Meilisearch.

**To Reproduce**
1. Use minio as the storage system, or deploy the Meilisearch in k8s with csi-s3 storage class.
2. Send an AddDocument request, and everything is ok.
3. Wait a minute, send second AddDocument request, and the error message appears.

**Expected behavior**
I expect the second AddDocument request run well

**Screenshots**
<img width="307" alt="image" src="https://github.com/meilisearch/meilisearch/assets/26248992/d79b040b-125f-42ef-9f08-0e3464e3a890">

**Meilisearch version:**
v1.5

**Additional context**
- K8s environment
- csi-s3 storage class
- [Helm chart repo](https://github.com/meilisearch/meilisearch-kubernetes)

**Comment by curquiza** [comment]
An answer has been given regarding the issue
Feel free to re-open if needed of course, nothing is definitive 😊
