### ISSUE TITLE
Improved filters

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#425]
Currently, we have filtering but only with one rule.  It's impossible to combines rules. It could be great to improve these filters by adding mutch more features.

## Proposal

- Allow more types

We should allow filtering a string but also arrays, floats or integers.

- Add more operator types

Currently, we can only perform an "is" filter noted now `:`. We must allow mutch more operators types. 
> Equal: `=`
> Contain: `:`
> Not equal: `!=`
> Not contain: `!:`
> More than: `>`
> Less than: `<`

- Combine operators

It should be good to allow the user to leverage Boolean operators (AND, OR, NOT) and parentheses to combine individual filters, similar to SQL expression syntax. This will allow range query

### More improvements

Like faceting, it should be great to allow them to be indexed on a specific index. It will speed up the query time.

## Sub Issues

- [ ] #511 Range queries

**Comment by erlend-sh** [comment]
Marked as done in Public Roadmap. So this is done? [Filtering doc](https://docs.meilisearch.com/guides/advanced_guides/filtering.html) also done?

**Comment by qdequele** [comment]
Yes, I close the isssue

**Comment by eelco-4free** [comment]
This proposal also included operator for `contain` and `not contain`. However this does not seem to be implemented. Why was this not implemented and are there plans to implement it in the future?

**Comment by gmourier** [comment]
Hi @eelco-weblog!

This is a discussion we have on the repository produced [here](https://github.com/meilisearch/product/discussions/407). We haven't implemented it yet due to lack of time but it is planned for the future. 

I can't give you an ETA for now.
