### ISSUE TITLE
Allow Geo Search

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#426]
Geo Search is a way to filter and sort results by distance or around certain geographical locations. User can limit your results to a street, to a city or cities, to one or more parts of the world. You can sort your results according to how near or far they are to a certain defined geolocation.

Geo offers you various possibilities:
- Filter and sort around a set of latitude and longitude coordinates
- Filter by one or more box-shaped geographical areas (bounded boxes)
- Filter by one or more freely-drawn geographical areas (polygons)
- Sort around a set of latitude and longitude coordinates

It could be done by implementing [s2 and Hilbert Curves algorithms](https://blog.zen.ly/geospatial-indexing-on-hilbert-curves-2379b929addc).

We can force the user to reformat there data by adding a geo field in there documents:
```json
"_geoloc": {
  "lat": 48.733333,
  "lng": -3.466667
}
```
Or we can add on settings the possibility to select the `latitude` and the `longitude` fields.

**Comment by westurner** [comment]
- https://en.wikipedia.org/wiki/GeoJSON
  - `coordinates: [0.1, 0.2]`
- https://schema.org/Place
  - https://schema.org/latitude
  - https://schema.org/longitude
- https://schema.org/GeospatialGeometry

**Comment by westurner** [comment]
- https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html
  - https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html
    > - Geo-point expressed as an object, with lat and lon keys.
    > - Geo-point expressed as a string with the format: "lat,lon".
    > - Geo-point expressed as a geohash.
    > - Geo-point expressed as an array with the format: [ lon, lat]
    > - Geo-point expressed as a Well-Known Text POINT with the format: "POINT(lon lat)"
    > - A geo-bounding box query which finds all geo-points that fall inside the box.
  - https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html

**Comment by martin-juul** [comment]
Postgres also offers geometric types. Also for different use cases like sizes, which could come in handy - should MeiliSearch opt for feature comparability (simpler indexing, when ingesting from a postgres store)

 https://www.postgresql.org/docs/12/datatype-geometric.html

**Comment by flother** [comment]
There's also [PostGIS](https://postgis.net/). PostgreSQL's built-in geometry fields are two-dimensional geometries that use unprojected Cartesian coordinates: while they would work as expected at the equator, they would become more and more distorted closer to the poles.

What MeiliSearch needs is geospatial geometries. PostGIS implements the Open Geospatial Consortium's [Simple Features](https://en.wikipedia.org/wiki/Simple_Features). That's where the widely-used well-known text (WKT) and well-known binary (WKB) markup formats come from.

**Comment by ofebles** [comment]
When will meili include geo search? Date planned? We need it a lot for new projects.  :) Thanks

**Comment by wael-mohamed** [comment]
I hope this feature will be planned for the next release

**Comment by JexPY** [comment]
I hope we will have this feature soon. I would like to use meilisearch and nothing more for indexed data.

**Comment by tchartron** [comment]
Just wanted to ask if there is any chance to see this released any time soon as i see the 2020_Q4 label has been removed ? 
Thanks for the great work on Meilisearch 💪🏼👍🏼

**Comment by LegendreM** [comment]
Hi @tchartron, thanks for your support!
About geo-search, we will not release it at the end of Q4_2020 because we are working on enhancing our tokenizer to have better support of other languages like Chinese Languages. I hope it will enhance your search experience too!

For Q1_2021, we don't know if we will work on geo-search or distributed systems, but I think it is a feature that we want to release in 2021.

I hope my answer was satisfactory,

Thanks again for your support, and stay tuned!

**Comment by tchartron** [comment]
Great thanks for these informations, I'll keep an eye on this until it's release 🚀

**Comment by qdequele** [comment]
Hello, 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/33-geo-search?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.

**Comment by TomasWeg** [comment]
By the moment, the only way is to store the latitude and the longitude as another JSON field, and when the results are retrieved, skip those who aren't in a certain area. It will be slow, but the only way

**Comment by flother** [comment]
@TomasWeg It's not the only way. One option would be to compute the [geohash](https://en.wikipedia.org/wiki/Geohash) for each record, store the geohashes in the MeiliSearch index, and then do a prefix search.

As an example, the old observatory at Greenwich in London has a longitude of 0.0 and latitude of 51.47773. This location has the geohash `u10hb50p80`, and every object within ~2.5km will have a geohash with the same five-letter prefix, `u10hb`. Every object within ~20km will have the same four-letter prefix, `u10h`. [And so on](https://en.wikipedia.org/wiki/Geohash#Digits_and_precision_in_km).

Geohashes (and space-filling curves in general) aren't perfect — it's possible they won't match some nearby objects — but this will be a much faster way of finding things nearby.

**Comment by shivaylamba** [comment]
@qdequele Geo Search is live in the latest release : https://github.com/meilisearch/MeiliSearch/releases/tag/v0.23.1

**Comment by devcshort** [comment]
Are there plans to expand on Meillisearch's Geo capabilities? We are currently using Elasticsearch and were interested in switching to Meilli, however I'm finding that Meilli geo capabilities are limited to latitude/longitude. In our use case we store entire GeoJSON shapes within our records and during our queries we do an intersect query.

Essentially, given a user's current latitude/longitude we want to find all records that have GeoJSON shapes that intersect with their position.

**Comment by macraig** [comment]
Hi @devcshort , while we don't currently have support for GeoJSON shapes or intersect queries planned in the near term, we are definitely interested in expanding our geo capabilities in the future. However, we don't have an ETA for this at the moment.

**Comment by devcshort** [comment]
Thanks @macraig! I'm glad to hear that it's on your guys radar, even if not currently planned. I imagine our use case isn't really the "norm" when it comes to search and how people use it. Even Algolia only supports the typical latitude/longitude radius type of queries.
