### ISSUE TITLE
Rename AttributesToSearchIn into SearchableAttributes

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#428]
The latter is more clear than the first one.

It would be even better if we used `restrictSearchableAttributes` in the search parameters and `SearchableAttributes` in the settings.

**Comment by qdequele** [comment]
Finally, we will remove `SearchableAttributes` because they are time-consuming features that are not currently requested by users.

**Comment by bidoubiwa** [comment]
documentation : meilisearch/documentation#109
