### ISSUE TITLE
v1.6 update embedder settings different when using settings vs settings/embedders

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch#4286]
**Describe the bug**
When updating the embedder settings with the `/settings` route and `/settings/embedders` route the embedder required values are different. With `settings`, the embedders are updated with `curl -X PATCH 'http://127.0.0.1:7700/indexes/movies/settings' -H 'Authorization: Bearer masterKey' -H 'Content-Type: application/json' --data '{"embedders": {"default": {"source": "userProvided", "dimensions": 512}}}'`.

With the embedders route `curl -X PATCH 'http://127.0.0.1:7700/indexes/movies/settings/embedders' -H 'Authorization: Bearer masterKey' -H 'Content-Type: application/json' --data '{"embedders": {"default": {"source": "userProvided", "dimensions": 512}}}'` results in an error.

```console
{"message":"Unknown field `default` inside `.embedders`: expected one of `source`, `model`, `revision`, `apiKey`, `dimensions`, `documentTemplate`","code":"invalid_settings_embedders","type":"invalid_request","link":"https://docs.meilisearch.com/errors#invalid_settings_embedders"}
```

When using the embedders route you instead have to send `curl -X PATCH 'http://127.0.0.1:7700/indexes/movies/settings/embedders' -H 'Authorization: Bearer masterKey' -H 'Content-Type: application/json' --data '{"embedders": {"source": "userProvided", "dimensions": 512}}'`. But this means only one embedder can be used because when updating it always replaces the current embedder.

**To Reproduce**
1. Run `curl -X PATCH 'http://127.0.0.1:7700/indexes/movies/settings/embedders' -H 'Authorization: Bearer masterKey' -H 'Content-Type: application/json' --data '{"embedders": {"default": {"source": "userProvided", "dimensions": 512}}}'`
2. Get an error

**Expected behavior**
Both settings routes should take the same values.

**Screenshots**

**Meilisearch version:**
v1.6.0-rc.3

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Hello @sanders41 

When you send a settings to `/settings/embedders` you should remove `embedders` and directly put the JSON object you would have put inside `embedders` if you were using the `/settings` route.

with `/settings` you have to send

```bash
curl -X PATCH 'http://127.0.0.1:7700/indexes/movies/settings' -H 'Authorization: Bearer masterKey' -H 'Content-Type: application/json' --data '{"embedders": {"default": {"source": "userProvided", "dimensions": 512}}}'
```

and with `/settings/embedders` you have to send

```bash
curl -X PATCH 'http://127.0.0.1:7700/indexes/movies/settings' -H 'Authorization: Bearer masterKey' -H 'Content-Type: application/json' --data '{"default": {"source": "userProvided", "dimensions": 512}}'
```

It's the same behavior than with [`typoTolerance` settings](https://www.meilisearch.com/docs/learn/configuration/typo_tolerance#configuring-typo-tolerance)

Let me know it I miss-understood your bug report

**Comment by sanders41** [comment]
Got it, this makes sense and fixed my issue.
