### ISSUE TITLE
502 status code after some time

### ISSUE THREAD

**Issue by Jasperav** [meilisearch/meilisearch#4299]
**Describe the bug**
I am running Meilisearch 1.5.0 on AWS on t3.medium and 100 gb storage for testing purposes. I have a setup script which I run to add 250.000 documents. After 1 hour, around 80.000 documents are successfully added. However, for some reason, I suddenly get a 502 error response back from Meilisearch. How is this possible?

This is the raw response: 

`MeilisearchCommunication(\n    MeilisearchCommunicationError {\n        status_code: 502,\n        message: None,\n        url: \"http://34.xxx.xxx.16/tasks/78165\",\n    },\n)
`
I get this while waiting for a task to be completed with this method call (Rust client):

`wait_for_completion_successful`

After calling `add_or_replace`.

**Comment by curquiza** [comment]
Hello @Jasperav 

Do you have a similar issue with using curl and not the Rust client?
Also, this error means it's impossible to reach the server, it's not from Meilisearch, but from the server and returned by the Rust client -> are you sure the server was up all the time?

**Comment by Jasperav** [comment]
Thanks for the quick response, the batch import is successfully now without any issues, guess I had some sort of network issue after all.
