### ISSUE TITLE
Meilisearch Cloud: Status code 405 when capturing analytics click event

### ISSUE THREAD

**Issue by fabio-nettis** [meilisearch/meilisearch#4302]
**Describe the bug**

Following the [instructions](https://www.meilisearch.com/docs/learn/cloud/analytics#configuring-click-through-rate-and-average-click-position) inside the official Meilisearch documentation to capture click events for analytical purposes, I receive a `405 Method Not Allowed` error when trying to sending following request:

```bash
curl \
  -X POST 'https://edge.meilisearch.com' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer [REDACTED]'
  --data-binary '{ 
    "eventType": "click",
    "eventName": "Search Result Clicked",
    "indexUid": "[REDACTED]",
    "objectID": "39221",
    "position": 2
  }'
```

Executing a `OPTIONS` request to the same endpoint indeed shows that the only two allowed verbs are `GET` and `OPTIONS`, am I doing something wrong here? Seems to me the API is not configured properly.

**To Reproduce**
1. Enable analytics inside your cloud dashboard
2. Follow the instructions [here](https://www.meilisearch.com/docs/learn/cloud/analytics#configuring-click-through-rate-and-average-click-position)
3. Send a request to capture a click event

**Expected behavior**

The API should return a positive response code

**Meilisearch version:**
v1.5.1 (Cloud)

**Comment by curquiza** [comment]
Hello @fabio-nettis 

Sorry for the trouble, our engineers are working on this. I'll let you know

**Comment by fabio-nettis** [comment]
@curquiza Thanks for quick the response! Looking forward to a fix.

**Comment by curquiza** [comment]
Thank you @fabio-nettis 

Indeed, thank you for the feedback

**Comment by brunoocasali** [comment]
Hi @fabio-nettis there was a mistake in our docs that were giving you the wrong coordinates.

I provided a PR to fix the docs https://github.com/meilisearch/documentation/pull/2677 you can check what changed in depth there.

But to help you just change your code to:

```
curl \
  -X POST 'https://edge.meilisearch.com/events' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer [REDACTED]'
  --data-binary '{ 
    "eventType": "click",
    "eventName": "Search Result Clicked",
    "indexUid": "[REDACTED]",
    "objectID": "39221",
    "position": 2
  }'
```

Thanks for using Meilisearch ❤️

**Comment by fabio-nettis** [comment]
@brunoocasali Reflected the changes as seen in your PR and receiving following error now.

```json
{
  "error": "Cannot destructure property 'searchId' of '(intermediate value)' as it is null.",
  "status": 500
}
```

There is no mention inside the documentation of any `searchId` property. Maybe something inside the backend code is faulty?

**Comment by brunoocasali** [comment]
I see, we should better handle these errors, sorry about that.

In a simplified way, this error happened due to the fact that you need to make the search request and then right after it send the events request.

Due to the information coming from the request like the IP address Cloudflare could let us know that the user that made the previous request also sends the `/events` call so we can relate them.

So, give it a try by sending one search request and then sending the /events call from the same machine ip-config it should work :)

**Comment by fabio-nettis** [comment]
@brunoocasali Well that is not possible for us since the client sends the analytics event but the API makes the search request. Wouldn't it be more sensible to return a `searchId` from the `.search()` function that in return can be optionally added to the event to reference the search it is attached to?

**Comment by qdequele** [comment]
Hello @fabio-nettis, I know you're probably using an SDK to perform the searches, but we have a fix that might interest you. Normally, you should be able to push for the search and the call on `/events` with the header `X-MS-USER-ID` to set your own userId for your users. By doing this, while pushing an event, you'll no longer have an issue of not being able to find the searchId for your event. What do you think about this?

**Comment by fabio-nettis** [comment]
@qdequele I think this would indeed suffice, I will test this tomorrow and let you know if this is a feasable approach. If it is, it is probably worth adding it to the documentation.
