### ISSUE TITLE
Incremental indexing for vector search (with Arroy)

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4305]
## Motivation

Develop incremental indexing in [arroy](https://github.com/meilisearch/arroy) to drastically improve vector search performances

## Usage

Nothing to do for the user, immediately available when using the experimental `vectorStore` feature

## TODO

- [x] Merge https://github.com/meilisearch/arroy/pull/41
- [x] Bump arroy version in Meilisearch

**Comment by curquiza** [comment]
Will be fixed by https://github.com/meilisearch/meilisearch/pull/4332, upgrading the Arroy dependency

**Comment by irevoire** [comment]
#4332 has been merged.
