### ISSUE TITLE
CUDA: support of GPU for vector search

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4306]
Related product team resources: [PRD](https://www.notion.so/meilisearch/AI-Search-cd5b8d6ce94944618914ab8d958aceb0) (internal)
Related product discussion: https://github.com/orgs/meilisearch/discussions/677

## Motivation

⚠️ This feature is about an experimental feature. Activate the [`vectorStore` experimental feature to use it](https://www.meilisearch.com/docs/reference/api/experimental_features#configure-experimental-features)

Make the GPU support available when computing vector with HuggingFace model.

## Usage

Cf comment [here](https://github.com/meilisearch/meilisearch/issues/4306#issuecomment-1893849620)

## TODO

- [x] Define usage
- [ ] Merge changes into `main`
- [ ] Update [product discussion](https://github.com/orgs/meilisearch/discussions/677) with usage

## Impacted teams

@meilisearch/docs-team

**Comment by dureuill** [comment]
Please find below a short guide to enable GPU support through CUDA for HuggingFace embedding generation.

## Prerequisites

- Linux distribution with a compatible CUDA version
- NVidia GPU with CUDA support
- A recent Rust compiler to compile Meilisearch from source

## Steps

1. Follow [the guide](https://huggingface.github.io/candle/guide/installation.html) to install the CUDA dependencies
2. Clone Meilisearch: `git clone https://github.com/meilisearch/meilisearch.git`
3. Compile Meilisearch with the `cuda` feature: `cargo build --release --features cuda`
4. In the freshly compiled Meilisearch, enable the vector store experimental feature:
```bash
❯ curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H 'Content-Type: application/json'  \
--data-binary '{ "vectorStore": true }'
```
5. Add an HuggingFace embedder to the settings:
```bash
curl \
-X PATCH 'http://localhost:7700/indexes/your_index/settings/embedders' \
-H 'Content-Type: application/json' --data-binary \
'{ "default": { "source": "huggingFace" } }'
```

# Impact

Enabling the CUDA feature allows using an available GPU to compute embeddings with a `huggingFace` embedder. 
On an AWS Graviton 2, this yields a x3 - x5 improvement on indexing time.

**Comment by doreilly257** [comment]
What about metal/mps or better mlx?

**Comment by dureuill** [comment]
Hello @doreilly257 👋 

We're using [candle](https://github.com/huggingface/candle), and at the time of implementation, the metal backend was not usable.

I think adding a metal feature to Meilisearch is probably a good first issue for contributors, if the support is now there on the candle side
