### ISSUE TITLE
Meilisearch Cloud: Optimize analytics event association handling

### ISSUE THREAD

**Issue by fabio-nettis** [meilisearch/meilisearch#4309]
**Describe the bug**

As currently implemented, the analytics endpoint found at `https://edge.meilisearch.com/events` must be called within a specific time window by the same machine that has executed the search request. This enables Meilisearch to automatically match the previous search request to the event.

### Problem

While this approach may work for specific use-cases it renders the analytics features useless for anyone who has a dedicated API with their own `/search` endpoint that may transform, optimize or modifies the response received my Meilisearch and forwards it to the client.

### Possible solution

In a future release, each search or multi-search request should return a singular or multiple `id` properties that can in return be included in the request to the `/events` endpoint, to manually associate the event to a search request.

```typescript
type SearchResponse<
  T = Record<string, any>,
  S extends SearchParams | undefined = undefined
> {
  id: string; // <--- Can be send to the analytics endpoint to reference this query
  hits: Hits<T>;
  processingTimeMs: number;
  query: string;
  facetDistribution?: FacetDistribution;
  facetStats?: FacetStats;
  vector?: number[];
}
```

if omitted, the current behavior tries to match the request automatically, this will broadly increase the overall usability of the analytics feature and is required to be viable for production use.

```jsonc
{
  // optional id that references search event
  "searchId": "92829",
  "eventType": "click",
  "eventName": "Search Result Clicked",
  "indexUid": "[REDACTED]",
  "objectID": "39221",
  "position": 2
}
```

As you can see above, an additional and optional property called `searchId` would be added to the events endpoint so that the request can be matched manually.

**To Reproduce**

1. Make a request from a remote API, Relay etc.
2. Click on one of the results on your client
3. Send a valid request to the `/events` endpoint
4. See error `Cannot destructure property 'searchId' of '(intermediate value)' as it is null.`

**Meilisearch version:**

v1.5.1 (Cloud)

**Additional context**

Referenced in #4302

**Comment by curquiza** [comment]
Hello @fabio-nettis 
Thank you for your suggestion.
It has been logged by our engineering teams and our product team is now aware of your feedback 😊

In the future, if you want to give feedback about the Cloud product or the engine itself, you can use
- our [public product roadmap](https://roadmap.meilisearch.com/tabs/1-under-consideration) 
- or directly write your feedback and your expectations in our [GitHub product discussion](https://github.com/orgs/meilisearch/discussions) if you want more direct interaction with Product team

I close this issue then! 😊
