### ISSUE TITLE
The `/facet-search` route doesn't take the `faceting.maxValuesPerFacet` setting

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4312]
**Describe the bug**
The number of values per facet returned by the `indexes/{index}/facet-search` route is not tacking the `faceting.maxValuePerFacet` setting into account.

**To Reproduce**
1. Send documents with filterable attributes to Meilisearch
2. Call the `facet-search` route and see that it returns 100 values per facet
3. Change the `faceting.maxValuesPerFacet` in the settings to, say, 3
4. Call the `facet-search` route and see that it always returns 100 values per facet

**Expected behavior**
The `faceting.maxValuesPerFacet` must impact the `/facet-search` route.

**Meilisearch version:**
All the version from v1.3 to 1.5.

**Comment by curquiza** [comment]
@meilisearch/docs-team, it might impact the documentation

**Comment by curquiza** [comment]
Merged by #4311 -> will be in rc7 tomorrow and in the official stable release on Monday

**Comment by curquiza** [comment]
Discussed with docs -> does not impact their side.
