### ISSUE TITLE
Autobatch task deletions

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4315]
Related spec: WIP

## Motivation

Autobatching the task deletions makes the engine faster to process them and ensures that if a user is sending task deletion while the engine is trying to delete tasks it still ends up working correctly.

## Usage

Nothing to do on your side.

## TODO

- [ ] Update the spec

## Impacted teams

@meilisearch/docs-team I don't know if we want to document that since it's very low level, but at least you know.

**Comment by guimachiavelli** [comment]
I agree with @irevoire—I don't see the need to document this. It's very low level and I'm not sure it is information people can clearly use to improve how they use Meilisearch.
