### ISSUE TITLE
[v1.6.0.rc-8] embedders key is present even when the vectorSearch is not enabled.

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch#4323]
**Describe the bug**

**To Reproduce**
1. Use the last prototype v1.6.0.rc-8
2. Do not enable the `vectorSearch` experimental feature
3. Run a simple `GET /indexes/my_index/settings`
4. See the `"embedders": {}` key

**Expected behavior**
To not see the embedders key because this is part of a experimental feature.

**Screenshots**

**Meilisearch version:**
v1.6.0.rc-8

**Additional context**
@curquiza is aware of the issue I let her know last Thursday.

**Comment by dureuill** [comment]
Fixed by #4318
