### ISSUE TITLE
> i have gotten this before too on mainnet, but only sporadically. it is very hard to reproduce.

### ISSUE THREAD

**Issue by Tura187** [meilisearch/meilisearch#4335]
> i have gotten this before too on mainnet, but only sporadically. it is very hard to reproduce.
> 
> btw, this seems to be the same:
> 
> * [TransactionNotFoundError: Transaction with hash "0x00...." could not be found. #2799](https://github.com
/issues/2799)
> * [frequent "transactionNotFoundError" #3152](https://github.com/wevm/wagmi/issues/3152)

Indeed, it is hard to reproduce. I updated to wagmi/viem 2.0.x now, so will keep an eye, but it happens more often on Base for some reason, maybe something to do with the opstack and how it reports confirmations 🤷  but hard to tell. If it happens again, i'll report here, but I doubt that reproducable example will be possible, as I haven't been able to notice any pattern behind it, besides it happening on Base more often
Disable wagmi/wagmi/
_Originally posted by @Yuripetusko in https://github.com/wevm/wagmi/issues/3241#issuecomment-1888943075_

**Comment by ManyTheFish** [comment]
Hello @Tura187,
It seems that this issue is not related to Melisearch at all, and it's not the only one.
Could you please avoid doing this? It may be due to a wrong configuration of your tools.

Thank you
