### ISSUE TITLE
if anyone stumbles upon this, my temporary fix was to ensure that one of the calls is conditionally mounted, which seems to solve the issue — in my case the second prepare was in a bridge modal (as part of a minting flow) and i was able to conditionally mount the hook iff the modal was open (though not ideal). note that the `enabled:` config doesn't affect anything because `usePrepareContractWrite`'s `useWalletClient` will always `watchWalletClient`disable 


### ISSUE THREAD

**Issue by Tura187** [meilisearch/meilisearch#4336]
if anyone stumbles upon this, my temporary fix was to ensure that one of the calls is conditionally mounted, which seems to solve the issue — in my case the second prepare was in a bridge modal (as part of a minting flow) and i was able to conditionally mount the hook iff the modal was open (though not ideal). note that the `enabled:` config doesn't affect anything because `usePrepareContractWrite`'s `useWalletClient` will always `watchWalletClient`

_Originally posted by @shrugs in https://github.com/wevm/wagmi/issues/2942#issuecomment-1693445870_

**Comment by ManyTheFish** [comment]
Hello @Tura187,
It seems that this issue is not related to Melisearch at all, and it's not the only one.
Could you please avoid doing this? It may be due to a bad configuration of your tools.

Thank you
