### ISSUE TITLE
Deep Dive still mentions using the sled kv store.

### ISSUE THREAD

**Issue by whmountains** [meilisearch/MeiliSearch#434]
This really had me confused when I was first getting started with Meili.

**Comment by Kerollmops** [comment]
Yes, the deep-dive must be updated, I will try to work on that this week.
MeiliSearch uses the LMDB key-value store. We tried many other stores like RocksDB and Sled but RAM and CPU usage were not satisfying.

**Comment by Kerollmops** [comment]
You can take a look at the PR #436 until it is improved and merged.
