### ISSUE TITLE
Make the Facet Search Indexing process incremental

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4354]
The facet search indexing is recomputing the whole database for each batch, which means that if we update 1 document on a database containing 1M documents, the Facet search indexing part will compute 1M + 1 documents instead of calculating the newly added document only.

Meilisearch should index the document incrementally.

## Related code

https://github.com/meilisearch/meilisearch/blob/b6fc18199380e902fcf4a0d634fb03c6c783614d/milli/src/update/facet/mod.rs#L173-L258

## Contextual puffin graph

Puffin graph of a complete indexing process of 7 documents taking 12 seconds to process.

![Capture d’écran 2024-01-23 à 18 20 23](https://github.com/meilisearch/meilisearch/assets/6482087/92430d8d-8330-49ff-9369-b4239e666474)

Over the 12 seconds, we see that more than 11 seconds are spent in the **facet search indexing process**. 

## Related

- [meilisearch-support issue 87](https://github.com/meilisearch/meilisearch-support/issues/87)
- [meilisearch-support issue 95](https://github.com/meilisearch/meilisearch-support/issues/95)

**Comment by curquiza** [comment]
Related to https://github.com/meilisearch/meilisearch-support/issues/87 (internal only)

**Comment by curquiza** [comment]
Fixed by #4350 
Will be released in v1.7.0-rc1
