### ISSUE TITLE
Update Charabia

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4357]
- [ ] release new charabia version
- [ ] update Meilisearch

**Comment by curquiza** [comment]
@ManyTheFish which changes in charabia should we hilight in the Meilisearch changelogs?

**Comment by curquiza** [comment]
@ManyTheFish a new version of Charabia might be needed since new PRs have been merged: https://github.com/meilisearch/charabia/releases

**Comment by ManyTheFish** [comment]
The only thing to highlight is that we can now retrieve the character 'Ð', 'Đ', 'đ' and 'ð'  using 'd', it is a minor normalization change

**Comment by curquiza** [comment]
Thanks @ManyTheFish 
closed by #4365
