### ISSUE TITLE
Canceling a settings update is too long

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4358]
Canceling an update of the settings can take a lot of time. [A user has noticed (private link)](https://meilisearch.slack.com/archives/C0557UPQHQA/p1705487905846229) that when sending an update cancel on a processing settings update, the time before it is canceled is long.

**To Reproduce**
1. Send an update of the settings
2. The settings update is processing
3. Cancel the settings update
4. Take a long coffee

**Expected behavior**
Cancelation tasks are prioritized over any other task, and when inserted in the tasks queue, the canceled tasks are compared to the processing ones. If a processing task must be canceled, we cancel the batch and start dequeuing tasks. The current processing settings update must have been canceled when the canceling task was inserted.

**Meilisearch version:**
??? TBD

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/meilisearch/issues/3715
