### ISSUE TITLE
Speed up the `FacetsUpdateIncremental` for big databases

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4367]
When [debugging a very big client](https://github.com/meilisearch/meilisearch-support/issues/95), we noticed that executing the differential indexing on 148M documents with nine filterable and three sortable attributes. When disabling the incremental indexing and only enabling the facet bulk indexing, we take 12 minutes to proceed with 488k document updates, while more than 2 hours and 30 minutes when using the incremental part of the code.

https://github.com/meilisearch/meilisearch/blob/b968616a99c99c7b3eed9bb4f0c4d05e16b5cf0d/milli/src/update/facet/mod.rs#L141-L171

**Comment by curquiza** [comment]
Fixed by #4433, will be release in v1.7.0-rc.2
