### ISSUE TITLE
Embedding with Hugging Face fails when input text is tokenized to >512 tokens

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#4370]
**Describe the bug**
If a rendered document is tokenized to more than 512 tokens, then embedding with Hugging Face fails.

**To Reproduce**
1. Try to embed a long document with a document template that is ineffective to shorten the input
2. Embedding fails with: `internal: Error while generating embeddings: runtime error: could not run model: index-select invalid index 512 with dim size 512.`

**Expected behavior**
Embedding succeeds

**Meilisearch version:**
1.6.0

**Additional context**
Thanks to @CaroFG for reporting this issue

**Comment by curquiza** [comment]
fixed by #4371, will be released in v1.6.1
