### ISSUE TITLE
Error: Directory not empty (os error 39) during dump import

### ISSUE THREAD

**Issue by MullaCode** [meilisearch/meilisearch#4395]
**Describe the bug**
I am updating meilisearch from v1.2 to v1.6 
meilisearch is hosted using docker on ECS in AWS with EFS used for data storage. When launching the new image, it error's out with 
Error: Directory not empty (os error 39) 
            
  |   | 2024-02-07T11:18:41.449+00:00 | [2024-02-07T11:18:41Z INFO meilisearch] Importing index `case-search`. 
  |   | 2024-02-07T11:18:41.538+00:00 | [2024-02-07T11:18:41Z INFO meilisearch] Importing the settings. 
  |   | 2024-02-07T11:18:41.538+00:00 | [2024-02-07T11:18:41Z INFO meilisearch] Importing the documents. 
  |   | 2024-02-07T11:20:07.846+00:00 | [2024-02-07T11:20:07Z INFO meilisearch] 11143093 documents found. 
  |   | 2024-02-07T11:22:07.479+00:00 | Error: Directory not empty (os error 39)

I have done this on 4 other environments with no issue however the import of data was much smaller. 

**To Reproduce**
1. Create dump via API
2. Stop ECS task for meilisearch
3. Connect to EFS and rename data.ms to backup_data.ms
4. Start ECS task with v1.6 and trigger import 
5. Import begins with error occur as mentioned above

**Expected behavior**
All documents to be imported successfully

**Meilisearch version:**
Docker --> getmeili/meilisearch:v1.6

**Additional context**
One index with 11143093 documents
Index size: approx 16GB
Dump size: approx 1.2GB
I've used ECS tasks with Memory of up to 64GB
EFS is elastic so no shortage of storage

**Comment by ManyTheFish** [comment]
Hello @MullaCode,

This error appears when Meilisearch doesn't manage to remove a file from a directory in deletion, could you check the access rights of the directory where the database is?

Thanks!

**Comment by MullaCode** [comment]
Hi @ManyTheFish 

The directory permissions are 755 
```
drwxr-xr-x  6 root root 6144 Feb  8 14:08 data.ms
drwxr-xr-x  2 root root 6144 Feb  8 14:03 dumps
drwxr-xr-x  6 root root 6144 Jul 26  2023 old_data.ms
```
I had attempted the upgrade a few times yesterday all will the same result. 

However I retried the whole process again today and it worked fine. The only difference was there was some more data added to the index! 
```
2024-02-08T14:08:10Z INFO meilisearch] Importing a dump of meilisearch `V6` from the 2024-02-08 13:45:00.095978167 
2024-02-08T14:08:10.301+00:00 | [2024-02-08T14:08:10Z INFO meilisearch] Importing index `case-search`. 
2024-02-08T14:08:10.409+00:00 | [2024-02-08T14:08:10Z INFO meilisearch] Importing the settings. 
2024-02-08T14:08:10.409+00:00 | [2024-02-08T14:08:10Z INFO meilisearch] Importing the documents. 
2024-02-08T14:09:36.382+00:00 | [2024-02-08T14:09:36Z INFO meilisearch] 11227412 documents found. 
2024-02-08T14:18:13.405+00:00 | [2024-02-08T14:18:13Z INFO meilisearch] All documents successfully imported.
```

Don't know what the root cause was yesterday but happy to have it upgraded now.
