### ISSUE TITLE
"Error while generating embeddings: runtime error: loading model failed: specified file not found in archive" Huggingface /settings endpoint

### ISSUE THREAD

**Issue by emraza1ai** [meilisearch/meilisearch#4399]
**Describe the bug** 
When trying to create embedding via:
```
curl -X PATCH "http://localhost:7700/indexes/meeting_actions/settings" -H "Content-Type: application/json" --data-binary "{\"embedders\": {\"default\": {\"source\": \"huggingFace\", \"model\": \"BAAI/bge-m3\"}}}"
```
The server logs:

```
[2024-02-09T23:46:56Z INFO  hf_hub] Token file not found "C:\\Users\\HP\\.cache\\huggingface\\token"
config.json [00:00:00] [███████████████████████████████████████████████████████████████████] 687 B/687 B 2.73 KiB/s (0s)
tokenizer.json [00:00:03] [████████████████████████████████████████████████████████] 16.31 MiB/16.31 MiB 4.23 MiB/s (0s)
pytorch_model.bin [00:08:15] [███████████████████████████████████████████████████████] 2.12 GiB/2.12 GiB 4.37 MiB/s (0s)
```
And then the task fails with the following error message: via get_task()

```
uid=68 index_uid='meeting_actions' status='failed' type='settingsUpdate' details={'embedders': {'default': {'source': 'huggingFace', 'model': 'BAAI/bge-m3'}}} error={'message': 'internal: Error while generating embeddings: runtime error: loading model failed: specified file not found in archive.', 'code': 'internal', 'type': 'internal', 'link': 'https://docs.meilisearch.com/errors#internal'} canceled_by=None duration='PT0.700991200S' enqueued_at=datetime.datetime(2024, 2, 10, 0, 10, 27, 92751) started_at=datetime.datetime(2024, 2, 10, 0, 10, 27, 145644) finished_at=datetime.datetime(2024, 2, 10, 0, 10, 27, 846635)
```

 
**To Reproduce**
 1. Install [meilisearch-windows-amd64.exe](https://github.com/meilisearch/meilisearch/releases/download/v1.6.1/meilisearch-windows-amd64.exe)
2. Enable vectorStore
3. Create index and add document 
3. Use the embedders index setting of the update /settings endpoint to configure embedders for an index: 
curl -X PATCH "http://localhost:7700/indexes/meeting_actions/settings" -H "Content-Type: application/json" --data-binary "{\"embedders\": {\"default\": {\"source\": \"huggingFace\", \"model\": \"BAAI/bge-m3\"}}}"

**Meilisearch version:** v1.6.1
**Additional context**
OS: Windows 11
I tried several models on huggingface, all failed with the exact Error 'while generating embeddings: runtime error: loading model failed: specified file not found in archive'. 
Tried downloading seperately from huggingface_hub import hf_hub_download, still after the model download's it faces the same error.

**Comment by sanders41** [comment]
The issue may be that a BERT model is required, I don't think is `BAAI/bge-m3` BERT? Have you tried BERT models and still get the same error?

https://www.meilisearch.com/docs/learn/experimental/vector_search#generate-auto-embeddings-with-huggingface

**Comment by emraza1ai** [comment]
You are right.  ```BAAI/bge-m3``` is based on XLM-Roberta not BERT.
But I have tried avsolatorio/GIST-all-MiniLM-L6-v2 to no avail:
```
uid=73 index_uid='meeting_actions' status='failed' type='settingsUpdate' details={'embedders': {'default': {'source': 'huggingFace', 'model': 'avsolatorio/GIST-all-MiniLM-L6-v2'}}} error={'message': 'internal: Error while generating embeddings: runtime error: loading model failed: specified file not found in archive.', 'code': 'internal', 'type': 'internal', 'link': 'https://docs.meilisearch.com/errors#internal'} canceled_by=None duration='PT23.760405S' enqueued_at=datetime.datetime(2024, 2, 10, 14, 34, 31, 113366) started_at=datetime.datetime(2024, 2, 10, 14, 34, 31, 115745) finished_at=datetime.datetime(2024, 2, 10, 14, 34, 54, 876150)
```

**Comment by emraza1ai** [comment]
I even tried the model mentioned at https://www.meilisearch.com/docs/learn/experimental/vector_search#generate-auto-embeddings-with-huggingface,
it downloads ```BAAI/bge-base-en-v1.5``` :
```
config.json [00:00:00] [███████████████████████████████████████████████████████████████████] 777 B/777 B 1.09 KiB/s (0s)
tokenizer.json [00:00:01] [████████████████████████████████████████████████████] 694.72 KiB/694.72 KiB 459.47 KiB/s (0s)
pytorch_model.bin [00:01:36] [███████████████████████████████████████████████████] 417.71 MiB/417.71 MiB 4.32 MiB/s (0s)
```

But then it still gives the same error:

```
uid=75 index_uid='meeting_actions' status='failed' type='settingsUpdate' details={'embedders': {'default': {'source': 'huggingFace', 'model': 'BAAI/bge-base-en-v1.5'}}} error={'message': 'internal: Error while generating embeddings: runtime error: loading model failed: specified file not found in archive.', 'code': 'internal', 'type': 'internal', 'link': 'https://docs.meilisearch.com/errors#internal'} canceled_by=None duration='PT102.462092400S' enqueued_at=datetime.datetime(2024, 2, 10, 14, 53, 38, 266617) started_at=datetime.datetime(2024, 2, 10, 14, 53, 38, 304698) finished_at=datetime.datetime(2024, 2, 10, 14, 55, 20, 766790)
```

**Comment by sanders41** [comment]
I was able to recreate this on Linux so it isn't a Windows specific issue. Hugging Face is giving a 401 access denied error. So it looks like a token is needed. `hf-hub` looks to have a way to pass a token (https://docs.rs/hf-hub/0.3.2/hf_hub/api/sync/struct.ApiBuilder.html#method.with_token), but I don't see a way to pass the token to Meilisearch.

```console
uid=9 index_uid='movies' status='failed' task_type='settingsUpdate' details={'embedders': {'default': {'source': 'huggingFace', 'model': 'bge-base-en', 'revision': 'v1.5', 'documentTemplate': "A movie titled '{{doc.title}}' whose description starts with {{doc.overview|truncatewords: 20}}"}}} error={'message': 'internal: Error while generating embeddings: error: fetching file from HG_HUB failed: request error: https://huggingface.co/bge-base-en/resolve/v1.5/config.json: status code 401.', 'code': 'internal', 'type': 'internal', 'link': 'https://docs.meilisearch.com/errors#internal'} canceled_by=None duration='PT0.098242910S' enqueued_at=datetime.datetime(2024, 2, 10, 16, 53, 50, 198972) started_at=datetime.datetime(2024, 2, 10, 16, 53, 50, 203195) finished_at=datetime.datetime(2024, 2, 10, 16, 53, 50, 301438)
```

**Comment by emraza1ai** [comment]
You are facing a different error:
```
error={'message': 'internal: Error while generating embeddings: error: fetching file from HG_HUB failed: request error: https://huggingface.co/bge-base-en/resolve/v1.5/config.json: status code 401.'
```

This is because I think you didn't specify ```BAAI/``` before ```bge-base-en-v1.5```, therefore it is resolving to ```https://huggingface.co/bge-base-en/resolve/v1.5/config.json```

Correct way:
```
curl -X PATCH "http://localhost:7700/indexes/meeting_actions/settings" -H "Content-Type: application/json" --data-binary "{"embedders": {"default": {"source": "huggingFace", "model": "BAAI/bge-base-en-v1.5"}}}"
```
Wrong way:
```
curl -X PATCH "http://localhost:7700/indexes/meeting_actions/settings" -H "Content-Type: application/json" --data-binary "{"embedders": {"default": {"source": "huggingFace", "model": "bge-base-en" , "revision": "v1.5"}}}"
OR
curl -X PATCH "http://localhost:7700/indexes/meeting_actions/settings" -H "Content-Type: application/json" --data-binary "{"embedders": {"default": {"source": "huggingFace", "model": "bge-base-en-v1.5"}}}"
```

**Comment by sanders41** [comment]
I tried both ways and got the same error, but I'll try again to make sure I didn't have a typo.

**Comment by sanders41** [comment]
Apparently I did have a typo, I tried again and didn't have any errors this time.

**Comment by emraza1ai** [comment]
Glad for you!
But coming back to my original error:
```uid=69 index_uid='meeting_actions' status='failed' type='settingsUpdate' details={'embedders': {'default': {'source': 'huggingFace', 'model': 'BAAI/bge-base-en-v1.5'}}} error={'message': 'internal: Error while generating embeddings: runtime error: loading model failed: specified file not found in archive.', 'code': 'internal', 'type': 'internal', 'link': 'https://docs.meilisearch.com/errors#internal'} canceled_by=None 
```
What should I do? I looked around that maybe it might be symlink issue in windows. But no I don't think so, seems to be some other problem.

**Comment by emraza1ai** [comment]
Any update on this?

**Comment by dureuill** [comment]
Hello :wave:, and thank you for your report :heart:

Given that the issue doesn't reproduce on Linux or macOS, it might be Windows-specific.

👉 Windows bugs are not the priority for the Meili team, so we need someone from the community to check if they can reproduce the bug on their machine, and then, someone to fix the bug.

That said, I'll try to reproduce it on a Windows machine if I can find the time.

**Comment by dureuill** [comment]
Hello again 👋 

I found some time and I indeed reproduced the issue on Windows.
By investigating with a debugger, it seems related to the dependency we're using to perform embedding.

I'll try to minimize the problem and open an issue on their repository.
