### ISSUE TITLE
max-indexing-threads CLI parameter consume an additional thread to write in database

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4406]
**Describe the bug**
When there are more available threads than the number of threads set by `--max-indexing-threads`, Meilisearch will use an extra thread to write the data in LMDB.

**To Reproduce**
1. Have an instance with at least 2 threads
2. set `--max-indexing-threads=1`
3. Meilisearch will use 2 threads

**Expected behavior**
Meilisearch should use only 1 thread for processing and writing the data

**Meilisearch version:**
v1.6.1

**Comment by curquiza** [comment]
fixed by #4350
