### ISSUE TITLE
Inconsistent string and number faceted documents order

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4409]
When modifying a small number of documents, they appear in the wrong order.

Related to #4374, #4339, and #4390.

**To Reproduce**
It happens when a few documents are modified in a bigger DB, so the incremental facet update kicks in.
The real fix is to rework the incremental facet update; many have started (or will start) work in this area.
A workaround is to do a 1.6.2 with incremental facet update disabled and only bulk facet update enabled.

**Expected behavior**
Faceted documents, when their facets are modified, must be ordered correctly, whether they are strings or numbers, which doesn't matter either.

**Meilisearch version:**
All versions with the incremental indexing: v1.6.0 and v1.6.1.

**Comment by curquiza** [comment]
Fixed by #4433, will be release in v1.7.0-rc.2
