### ISSUE TITLE
Curl Installation Error

### ISSUE THREAD

**Issue by nickashley** [meilisearch/meilisearch#4411]
**Describe the bug**
When trying to install with the Curl command, I get the following error:

curl: (22) The requested URL returned error: 404

ERROR: Impossible to get the latest stable version of Meilisearch.
Please let us know about this issue: https://github.com/meilisearch/meilisearch/issues/new/choose

**To Reproduce**
Run the command  curl -L https://install.meilisearch.com | sh

**Screenshots**
<img width="786" alt="image" src="https://github.com/meilisearch/meilisearch/assets/449016/43c95acc-aa68-4aad-8601-bacf75d522a0">

**Additional context**
On an Apple silicon Macbook, with Sonoma 14.2.1

**Comment by curquiza** [comment]
Hello @nickashley 
thank you for the report, I can indeed reproduce the issue

In the meantime, you can
- use or [cloud offer](https://www.meilisearch.com/cloud?utm_campaign=oss&utm_source=github&utm_medium=meilisearch)
- use our docker image `getmeili/meilisearch:v1.6.2`
- compile from source
- directly download the [assets from the release](https://github.com/meilisearch/meilisearch/releases/tag/v1.6.2)

**Comment by curquiza** [comment]
We had an issue with the Apple silicon CI, it was stuck for hours
I re-ran it, should be fine in 30min
https://github.com/meilisearch/meilisearch/actions/runs/7889313572

**Comment by nickashley** [comment]
Thanks! I can install directly for now. FYI, it looks like it failed to publish the binary again, so this is currently still broken :(

**Comment by dureuill** [comment]
Hello, this is now fixed ☀️ 

thank you for the report :heart:
