### ISSUE TITLE
Logs should be outputted to `stderr` instead of `stdout`

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4419]
**Describe the bug**
In the last rc: v1.7.0-rc.0 the logs are sent to `stdout`; this is a bug, and logs should always be sent to `stderr` as we’ve always done.

This bug never landed on a stable version of meilisearch. No need to mention it in the final changelog.

**To Reproduce**
1. Run meilisearch

**Comment by curquiza** [comment]
Closed by #4418
