### ISSUE TITLE
Meili search ignore offset in request. Always start with 0 in response

### ISSUE THREAD

**Issue by jonaskahn** [meilisearch/meilisearch#4425]
**Describe the bug**
I found a very wired bug when work with Meilisearch.  I tried so many times but offset still be ignored in request
Here is my request:
```json
{
    "filter": [
        "status IN [1]"
    ],
    "q": "name",
    "offset": 10,
    "hitsPerPage": 10,
    "attributesToSearchOn": [
        "name",
        "description",
        "url"
    ],
    "limit": 10,
    "sort": [
        "createdAt:desc",
        "updatedAt:desc"
    ]
}
```
**Screenshots**
![image](https://github.com/meilisearch/meilisearch/assets/4338500/99b3fc1b-dd7c-417c-aeea-380eebe8c0fe)

**Meilisearch version:**
 v1.6.2

I use docker with default settings. Do I make some wrong configuration ? @@

**Comment by curquiza** [comment]
Hello @jonaskahn 

Looks like here you used two different features of Meilisearch at the same time: `offset`/`limit` and `hitsPerPage`.

When using `hitsPerPage`, Meilisearch ignores `offset`/`limit`. You can use either `offset`/`limit` or `page`/`hitsPerPage`.

More information [here](https://www.meilisearch.com/docs/learn/front_end/pagination)
Summary:
- if you need to know the exact number of page when doing your UI pagination, so a "go to the last page" button, use `page`/`hitsPerPage` 
- if you just need a "next" & "previous" button, use `offset`/`limit`, you will have better performance during the search

**Comment by jonaskahn** [comment]
Oh, I see. Let me try it again.

**Comment by jonaskahn** [comment]
It worked. Thank you.
