### ISSUE TITLE
Need Help - Touches Relationships Laravel scout & meilisearch

### ISSUE THREAD

**Issue by seifrached** [meilisearch/meilisearch#4431]
_Framework: Laravel 8 with driver scout 9.5
Meilisearch v1.5.1_

I'm creating a bookmark system for users by 3 models who
**User** can make Many records
**Record** Bookmarked by her owner and others Many User**s**
**Bookmark** belongsTo **Record** and **User**

**Models relationship**

**Record.php**
```
class Record extends Model
{
    use HasFactory, Searchable, SoftDeletes;
    public $table = 'records';

    /**
     * All of the relationships to be touched.
     *
     * @var array
     */
    protected $touches = ['user'];

public function user(){
        return $this->belongsTo(User::class);
    }
    public function bookmarks(){    
        return $this->hasMany(Bookmark::class,'record_id')->withTrashed();
    }

}
```
**User.php**

```
public function bookmarks()
    {
        return $this->hasMany(Bookmark::class);
    }

    public function records()
    {
        return $this->hasMany(Record::class);
    }
```

**Bookmark.php**

```
class Bookmark extends Model
{
    use HasFactory, Searchable, SoftDeletes;
    public $table = 'bookmarks';
    protected $touches = ['user','record'];
    protected $fillable = ['record_id','user_id'];
    protected $dates = ['updated_at','created_at','deleted_at'];
    
   
public function user()
    {
        return $this->belongsTo(User::class);    
    }

    public function record()
    {
        return $this->belongsTo(Record::class);
    }

}
```

Everything is okey when the owner softDelete his record, The record un-indexed from Meilisearch **Bookmarks** Model  and From **User->bookmarks**, the problem isnothing change for all others user**s** who bookmarks this **record**, Meaning it is touching only her owner.

I tried to iterate all user->bookmarks to update the relationship but this solution it takes a lot of time and effort, and frankly, I do not consider it reasonable if the number of Bookmarkers is large.

**Record.php**
```
protected static function boot()
    {
        parent::boot();
        static::softDeleted(function ($model) {  
            $model->images()->delete();
            $model->bookmarks()->delete();
            $model->user->update();
            $model->images->unsearchable();
            $model->bookmarks->unsearchable();

            $bookmarkIds = $model->bookmarks()->pluck('id')->toArray();
            Bookmark::whereIn('id', $bookmarkIds)->unsearchable();
)};
       static::restored(function ($model) {
                $model->images()->restore();
                $model->bookmarks()->restore();
                $model->user->update();
                $model->images->searchable();
                $model->bookmarks->searchable();
                $model->searchable();

                $bookmarkIds = $model->bookmarks()->pluck('id')->toArray();
                Bookmark::whereIn('id', $bookmarkIds)->searchable();
        });
}
```

I'm skeptical whether that's the problem is from my Relationship design or Laravel scout or Meilisearch !
When I check Laravel Eloquent works fine
![Capture d'écran 2024-02-21 172410](https://github.com/meilisearch/documentation/assets/45343853/ade18755-dfee-4c3e-9685-475bc29f24d0)

**Inside Meilisearch**

![Capture d'écran 2024-02-21 172317](https://github.com/meilisearch/documentation/assets/45343853/a04a845d-c908-4f17-90f8-8fd7e56eddaa)

please any suggest or solution.

Thanks

**Comment by curquiza** [comment]
Hello @seifrached

I'm not sure to understant what you do, and what you expect from Meilisearch, but I can say Meilisearch does not handle relation between documents and indexes. You have to update them on your side.

---

Also, for next time, you might have seen it when you opened the issue: opening an issue is not for support request.

<img width="1306" alt="Capture d’écran 2024-02-22 à 13 58 13" src="https://github.com/meilisearch/meilisearch/assets/20380692/42147280-ff5a-40bf-87ac-c2b810327d97">
