### ISSUE TITLE
Make the processing of batches atomic 

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4432]
**Describe the bug**
Currently, when meilisearch processes the tasks, there is three phases:
1. Find the tasks you need to process in your batch
2. Actually, process the batch, for example, index documents
3. Write the results in the task queue and delete the associated update files.

We just realized that there was a bug in step 3️⃣:
4. We take a write transaction on the task store
5. Loop over all the processed tasks
6. For each task: Write its new status and delete its associated update file
7. Commit the content of the task store

Here, if a crash/restart happens during the loop of 6️⃣, Meilisearch will restart, recreate a batch that contains at least the same tasks, and in step 2️⃣ realize that some of the update files have been deleted.
=> We just lost some data.

**To Reproduce**
1. Index a ton of thing
2. Restart meilisearch in the middle of step 6️⃣ 

**Expected behavior**
We don't lose any tasks

**Meilisearch version:**
Everything above and including v0.30.0

**Comment by curquiza** [comment]
Fixed by #4435, will be release in v1.7.0-rc.2
