### ISSUE TITLE
Webhooks parsed with no content-type

### ISSUE THREAD

**Issue by Calemy** [meilisearch/meilisearch#4436]
**Describe the bug**
I've been trying to use the webhook from meilisearch into my nodejs program with fastify. I've been running into the issue of "not supported media type" which in itself is not a huge problem, but i noticed that meilisearch does not send any content-type which makes it a lot more difficult to deal with.
**To Reproduce**
1. specify webhook url
2. make basic nodejs server with fastify
3. add any document to database to trigger the webhook
4. see error

**Expected behavior**
being able to process the webhook

**Meilisearch version:**
v1.6.2

**Additional context**
i've been "avoiding" this issue by adding the content-type into my headers by checking the user-agent. this of course is not sustainable and i'd suggest adding this natively into meilisearch.

**Comment by curquiza** [comment]
Hello @Calemy 

thanks for opening this issue
we set this issue as `good first issue` and we welcome any contribution for it

**Comment by irevoire** [comment]
Hey, while trying to understand this issue https://github.com/meilisearch/meilisearch/issues/4449 I ended up thinking both were maybe linked and just fixed this one to start with
