### ISSUE TITLE
webhook body returns undefined

### ISSUE THREAD

**Issue by Calemy** [meilisearch/meilisearch#4449]
**Describe the bug**
Using the task webhook sends over an undefined body

**To Reproduce**
1. Create simple api with nodejs + fastify
2. Set webhook url
3. Send test data

**Expected behavior**
Being able to receive/process the body

**Meilisearch version:**
v1.6.2

**Additional context**
```js
import "dotenv/config"
import { fastify as f } from "fastify"
import compress from "@fastify/compress"
const fastify = f({ logger: true, trustProxy: true })

fastify.register(compress) //adds support for gzip

fastify.addContentTypeParser('application/x-ndjson', function (request, payload, done) {
    done()
})
fastify.addHook("onRequest", (req, reply, done) => {
    //* MeiliSearch please add a content-type :(
    if(req.headers["user-agent"].includes("ureq/")){
        req.headers["content-type"] = "application/x-ndjson"
    }
    done()
})

fastify.post("/api/update", (req, reply) => {
    console.log(req.body) // returns undefined
    return "ok"
})

fastify.listen({ host: "0.0.0.0", port: process.env.port }
```

**Comment by irevoire** [comment]
Hey, I don’t know what is « an undefined body », I guess it’s related to the SDK you’re using, but I’ll really need more info on that.
Is it happening because of the missing content type?

**Comment by Calemy** [comment]
an undefined body in javascript basically just means that the content being sent to the router has nothing in it.
I've been trying for days to find out why that is, but can't seem to find any reasonal logic for it.
I also have an open issue on the fastify/help repo (https://github.com/fastify/help/issues/998#issue-2150650699)
To the conclusion there is that the format is not gzip/ndjson as expected. Any ideas would be highly appreciated because i'm losing it at this point.

**Comment by irevoire** [comment]
@Calemy, can we close the issue since you have a solution in https://github.com/fastify/help/issues/998

**Comment by Calemy** [comment]
seems to work out. thanks you a lot! :)
