### ISSUE TITLE
 Inconsistencies in Chinese Keyword Search Results with Default Settings

### ISSUE THREAD

**Issue by dwzkit** [meilisearch/meilisearch#4465]
**Describe the bug**
I am experiencing inconsistent search results with Chinese keywords using MeiliSearch with default settings. When searching for "告诉我如何写周报" (Tell me how to write a weekly report), no results are returned. However, altering the query slightly to "写周报告诉我如何" (How to write a weekly report tell me) yields the expected results.

**To Reproduce**

- Use the MeiliSearch instance with the index ai_command_template.
- Send a search query with "q": "告诉我如何写周报" (Tell me how to write a weekly report).
- Observe that no results are returned.
<img width="1008" alt="图片" src="https://github.com/meilisearch/meilisearch/assets/41875799/53003fa7-6ab2-4d3f-ada8-7e199f89d7af">

- Change the search query to "q": "写周报告诉我如何" (How to write a weekly report tell me).
- Observe that results are correctly returned.
<img width="1054" alt="图片" src="https://github.com/meilisearch/meilisearch/assets/41875799/0e79b7d5-7b28-4208-987b-7733d7d1598a">

Expected behavior
I expected the search query "告诉我如何写周报" to return relevant results, especially since the data contains keywords closely matching the query.

Screenshots
<img width="1008" alt="图片" src="https://github.com/meilisearch/meilisearch/assets/41875799/53003fa7-6ab2-4d3f-ada8-7e199f89d7af">

Meilisearch version:
V1.6

Additional context
I'm working with the default settings in MeiliSearch, without any specific configuration for handling Chinese language searches. The database includes entries that should match the query based on their content. Is there a configuration or setting recommended for improving search accuracy with Chinese text?

**Comment by dwzkit** [comment]
In my experience with Elasticsearch (ES), it appears to offer similar functionalities to MeiliSearch but with potentially greater precision in search result matching.

**Comment by ManyTheFish** [comment]
Hello @dwzkit,
Could you provide the documents in a copy-paste-able way?
I want to reproduce your issue on my side.

Thank you! 😄

**Comment by dwzkit** [comment]
> Hello @dwzkit, Could you provide the documents in a copy-paste-able way? I want to reproduce your issue on my side.
> 
> Thank you! 😄

OK~~

```
[
  {
    "id": 1,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "year_end_summary",
    "command_name": "年终总结",
    "priority": 1,
    "command_description": "一键搞定年终总结报告",
    "command_content": "写一篇[2023年新媒体运营工作]的年终总结报告，主要包括：1、工作概述：[短视频运营、小红书和微博运营、直播运营]；2、成果评估：[达到了涨粉30w的目标]；3、亮点分析：[短视频运营方向的总结和思考]；4、问题与反思；5、明年展望。",
    "is_deleted": 0,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  },
  {
    "id": 2,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "ppt_outline",
    "command_name": "PPT大纲",
    "priority": 1,
    "command_description": "根据给定的主题，生成PPT大纲",
    "command_content": "请为我生成主题为：[奶茶店连锁加盟介绍]的PPT大纲，PPT观众是[加盟商]，你需要考虑的内容包括[行业背景、市场前景、城市选择、选址推荐、加盟优势]。请按照主题和内容，准备PPT大纲，包括标题、目录、内容概述等。",
    "is_deleted": 0,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  },
  {
    "id": 3,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "weekly_work_report",
    "command_name": "工作周报",
    "priority": 1,
    "command_description": "一键生成周报，清晰展现工作进展",
    "command_content": "请为我准备一份关于本周的工作周报，我的工作岗位是：[产品经理]，本周的完成的工作事项有：[完成项目A的需求分析与设计，输出了需求文档和设计文档。]，请根据以下要素生成周报：1、本周工作进展，描述本周完成的工作和结果；2、下周工作安排，规划下周要推进的事项；3、思考总结，本周的收获和反思。",
    "is_deleted": 0,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  },
  {
    "id": 4,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "brainstorming",
    "command_name": "头脑风暴",
    "priority": 1,
    "command_description": "头脑风暴，发挥联想",
    "command_content": "现在你是一位创意策划大师，需要为一场头脑风暴会议提供一些建议和创意。在这场头脑风暴中，我们的主题是[如何更好地使用AI]，请给出尽可能多的可执行方向。",
    "is_deleted": 0,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  },
  {
    "id": 5,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "work_plan",
    "command_name": "工作计划",
    "priority": 1,
    "command_description": "根据岗位及工作目标，生成工作计划",
    "command_content": "现在你扮演一位职场办公人员，请帮我写一个[第三季度]的工作计划，目标是[完成公司内部用管理后台]。你的计划需要包括以下要点：{多选(请选择)[工作目标,工作任务,所需资源,风险预测,跟进与评估]}。希望的计划风格是{多选(请选择)[详细,简洁,有条理,具有创新点]}。",
    "is_deleted": 0,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  },
  {
    "id": 6,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "performance_report",
    "command_name": "述职报告",
    "priority": 1,
    "command_description": "一键生成述职报告",
    "command_content": "你是一名[部门领导]，现在需要为我撰写一篇关于[2023年度]的述职报告。报告中需包括以下内容：工作成绩{多选(请选择)[任务完成情况,业绩指标达成,客户满意度,团队建设]}，工作亮点：{多选(请选择)[突破性进展,创新性探索,困难克服,优秀案例等]}，自我评价{多选(请选择)[工作态度,职业素养,能力水平,团队协作]}，改进计划[举例：针对不足进行制定的计划和行动]，岗位期望{多选(请选择)[希望在职位能xxx,工作内容,团队和发展方向等方面的期望]}。报告风格{单选(请选择)[正式,简洁,积极]}，字数要求{单选(请选择)[不少于500字,不少于800字,不少于1000字]}。",
    "is_deleted": 0,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  },
  {
    "id": 7,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "english_email",
    "command_name": "英文邮件",
    "priority": 1,
    "command_description": "一键生成英文邮件",
    "command_content": "你现在是一个外企职工[小李]，需给[王总]写一封关于[主题]的邮件，邮件内容包括[线上会议时间已确定，于2023年12月1日18:00在xx进行]，请按照我给定的要求[表达热情,吸引客户,内容简洁]生成一封英文邮件。",
    "is_deleted": 0,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  },
  {
    "id": 8,
    "author": "official",
    "catigoray_code": "workplace_office",
    "command_code": "japanese_email",
    "command_name": "日文邮件",
    "priority": 1,
    "command_description": "一键生成日文邮件",
    "command_content": "现在你是一位演讲训练师，你要为一个即将参加岗位竞聘的职场人士准备一份演讲稿。演讲稿需针对[人力资源]岗位，进行自我介绍，涵盖{单选(请选择)[学历背景,工作经历,实践技能,团队协作,领导力,沟通能力,业绩成果]}等方面，竞聘原因是[希望在新岗位挑战自己]，最后谈及如何为公司创造价值。演讲稿中注意用尊称开头，如尊敬的评委老师。请直接输出结果，不要返回其他内容。",
    "is_deleted": 1,
    "created_at": "2023-12-15 21:12:00",
    "updated_at": "2023-12-15 21:12:00",
    "is_hot": 0
  }
]
```

**Comment by honhimW** [comment]
From my experience, for Chinese search, you might need to set the twoTypos in typoTolerance a bit lower (for example: 7 or even 6). This is just a suggestion.

**Comment by dwzkit** [comment]
> From my experience, for Chinese search, you might need to set the twoTypos in typoTolerance a bit lower (for example: 7 or even 6). This is just a suggestion.

I tried adjusting the typo tolerance settings in MeiliSearch with commands to modify minWordSizeForTypos for both oneTypo and twoTypos, even setting oneTypo to 0 and twoTypos to 2, targeting the command_name field for searches. Unfortunately, these adjustments didn't solve the issue. 
```
curl \
  -X PATCH 'http://localhost:7700/indexes/ai_command_template/settings/typo-tolerance' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "minWordSizeForTypos": {
      "oneTypo": 4,
      "twoTypos": 6
    }
  }'，

curl \
  -X PATCH 'http://localhost:7700/indexes/ai_command_template/settings/typo-tolerance' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "minWordSizeForTypos": {
      "oneTypo": 0,
      "twoTypos": 2
    }
  }'
```

With similar configuration and a more complex search query("“告诉我如何写一篇符合领导要求的相关的周报”") in Elasticsearch, the search worked fine and returned the expected results. I'm encountering challenges with searches that should work similarly in MeiliSearch.
<img width="1157" alt="图片" src="https://github.com/meilisearch/meilisearch/assets/41875799/ab59bf39-8291-42a8-b665-88c9b31705fd">

**Comment by ManyTheFish** [comment]
Hello @dwzkit,
The documents you provided don't match the queries you shared in your original message at all, could you send me a similar request that should match one of the documents but doesn't, please? Thank you!

**Comment by dwzkit** [comment]
> Hello @dwzkit, The documents you provided don't match the queries you shared in your original message at all. Could you send me a similar request that should match one of the documents but doesn't?
> 
> Something like:
> 
> > With the query `xxxxxx`, I want to retrieve the document `yyyyyyyyy` but Meilisearch doesn't.
> 
> Thank you!

The documents I provided does match the queries I shared.
<img width="975" alt="图片" src="https://github.com/meilisearch/meilisearch/assets/41875799/223d4c3c-56ba-41bb-b973-0429c56941a6">
<img width="1092" alt="图片" src="https://github.com/meilisearch/meilisearch/assets/41875799/0487a1c8-0a39-4270-baa1-09d5806670ff">

> With the query '告诉我如何写周报', I want to retrieve the document
>```
>{
>    "id": 3,
>    "author": "official",
>    "catigoray_code": "workplace_office",
>    "command_code": "weekly_work_report",
>    "command_name": "工作周报",
>    "priority": 1,
>    "command_description": "一键生成周报，清晰展现工作进展",
>    "command_content": "请为我准备一份关于本周的工作周报，我的工作岗位是：[产品经理]，本周的完成的工作事项有：[完成项目A的需求分析与设计，输出了需求文档和设计文档。]，请根据以下要素生成周报：1、本周工作进展，描述本周完成的工作和结果；2、下周工作安排，规划下周要推进的事项；3、思考总结，本周的收获和反思。",
>    "is_deleted": 0,
>    "created_at": "2023-12-15 21:12:00",
>    "updated_at": "2023-12-15 21:12:00",
>    "is_hot": 0
>  },
> ```
>  but Meilisearch doesn't.`

**Comment by ManyTheFish** [comment]
Hello @dwzkit,

To fully understand the issue, the last question is, which part of the document should match the query, and why?

Sorry for my naive questions. I don't speak Chinese 😬

Thank you for all the details

**Comment by dwzkit** [comment]
> Hello @dwzkit,
> 
> To fully understand the issue, the last question is, which part of the document should match the query, and why?
> 
> Sorry for my naive questions. I can't speak Chinese 😬
> 
> Thank you for all the details
Apologies if my previous message was unclear due to the specific context involving Chinese language search. Let me try to explain the issue in a more universal way.

We've encountered an issue where the search results are inconsistent, depending on the order of words in the search query, which is quite critical when dealing with languages like Chinese that do not separate words with spaces as English does.

For example, when we search using a phrase (let's analogize it to "Tell me how to write a weekly report" in English for understanding), we get no results. However, if we reorder the words in the query to something like "Write weekly report tell me how" (again, this is just an analogy for the word order change in Chinese), we then receive the expected results.

This issue suggests that the search engine might not be handling the nuances of Chinese text search optimally, as reordering the words in a query shouldn't dramatically change the search results in a language where word order can vary but still convey the same meaning.

After further exploration, I've successfully implemented a solution that meets my needs using Elasticsearch. This has led me to the decision to close this issue, as my immediate requirements for text search functionality have been satisfied.

I wanted to extend my sincere thanks for your time and support regarding the issue I encountered with Chinese text search in MeiliSearch.

**Comment by ManyTheFish** [comment]
Hello @dwzkit,
Thank you for your message, and I am sorry if Meilisearch doesn't fit your needs at this step.
If you remain interested in the product and want to stay tuned on the Chinese Language support changes, I encourage you to follow the bellow discussion:
https://github.com/orgs/meilisearch/discussions/503

If we make any enhancement, I will post it in it.
Thank you for your explanations and your support,
I hope you will retry our product if we enhance the Language support.

See you
