### ISSUE TITLE
Croplength application

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#448]
When doing a search request with `cropLength: 1` i receive a field with 2 chars. 

I would like to know how croplength is applied to the field. I thought it was the number of chars before and after the matched query word. So it would have been either `3` or `0` since the croplength is smaller than the query word length.

```
    id: '485811',
    overview: 'After a zombie apocalypse spreads from a London prison, the UK is brought to its knees. The spread of the virus is temporarily contained but, without a cure, it’s only a matter of time before it breaks its boundaries and the biggest problem of all… any zombies with combat skills are now enhanced. With the South East of England quarantined from the rest of the world using fortified borders, intelligence finds that the scientist responsible for the outbreak is alive and well in London. With his recovery being the only hope of a cure, a squad of eight Special Forces soldiers is sent on a suicide mission to the city, now ruled by the undead, with a single task: get him out alive within 72 hours by any means necessary. What emerges is an unlikely pairing on a course to save humanity against ever-rising odds.',
    _formatted: { id: '485811', overview: ' s' }
```

**Comment by qdequele** [comment]
What is your search query ?

**Comment by bidoubiwa** [comment]
```
q: 'scientist',
offset: 0,
limit: 5,
attributesToRetrieve: ['overview', 'id'],
attributesToSearchIn: ['overview'],
attributesToCrop: ['overview'],
cropLength: 1,
```

**Comment by qdequele** [comment]
The crop function will be applied from the first match char (from the beginning in case there is no match). Then it will take x char of each side of the starting point. (x being the cropLength).

**Comment by bidoubiwa** [comment]
It's a starting point and not a starting char?

**Comment by bidoubiwa** [comment]
So, after talking with @qdequele it is in fact a starting point. 

At the first letter of the matched query word it will go X chars to the left and X char to the right (X = cropLength. 

For example is our cropLength is 4 and the matched query word is `cat` the resulting cropped value will be : `4321cat4`
