### ISSUE TITLE
Name and Uid are redondant and only one should be kept

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#451]
Since in all our example we chose the name of the UID ourself we already create a human readable field.

because of that, and because there will probably not be a case where the user needs an infinite number of indexes with random generated uid's, I think the name should simply be specified as unique.
Like in SQL, and most databases.

We thrive for simplicity of use and this double parameter each time we create an index is weird.

@qdequele @Kerollmops

**Comment by qdequele** [comment]
No relevant anymore.
