### ISSUE TITLE
Meilisearch installation on ubuntu: ERROR: Impossible to get the latest stable version of Meilisearch.

### ISSUE THREAD

**Issue by bhuvaneshprasad** [meilisearch/meilisearch#4517]
**Describe the bug**
Following the standard installation instructions on Ubuntu yields ERROR: Impossible to get the latest stable version of Meilisearch.

**To Reproduce**
1. Go to 'terminal'
2. Type 'curl -L https://install.meilisearch.com | sh'
3. Press 'Enter'

**Expected behavior**
Meilisearch installation on Ubuntu Machine

**Error Message**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4352  100  4352    0     0   5378      0 --:--:-- --:--:-- --:--:--  5378
Downloading Meilisearch binary v1.7.2 for linux, architecture amd64...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

ERROR: Impossible to get the latest stable version of Meilisearch.
Please let us know about this issue: https://github.com/meilisearch/meilisearch/issues/new/choose

In the meantime, you can manually download the appropriate binary from the GitHub release assets here: https://github.com/meilisearch/meilisearch/releases/latest

**Meilisearch version:**
Trying to install the latest Version

**Comment by snapeuh** [comment]
https://github.com/meilisearch/meilisearch/actions/runs/8359620679

The publish binaries for Linux Mac and Windows have failed.

**Comment by curquiza** [comment]
Hello here

Sorry for the issue. We will deploy v1.7.3 today that will fix the issue

**Comment by curquiza** [comment]
v1.7.3 is released and the new binaries are available. It's fixed 🎉
