### ISSUE TITLE
Unable to update separator tokens

### ISSUE THREAD

**Issue by jbinder** [meilisearch/meilisearch#4523]
**Describe the bug**
According to the documentation, it should be possible to update separator-tokens using the API [1] (/settings/separator-tokens). I get a 404 error for that endpoint though.

**To Reproduce**
1. Ensure settings works by performing: GET {{host}}/indexes/{{index_uid}}/settings
2. Try accessing separator-tokens: GET {{host}}/indexes/{{index_uid}}/settings/separator-tokens
3. The response is a 404 instead the actual list of separator tokens.

**Expected behavior**
The separator tokens endpoint should be functional.

**Meilisearch version:**
v1.7.2

**Additional context**
Deployed using Ploi [2].

[1] https://www.meilisearch.com/docs/reference/api/settings#separator-tokens
[2] https://ploi.io

**Comment by curquiza** [comment]
Hello @jbinder 

Sorry, I don't manage to reproduce your issue
- I added documents
- I get separated tokens and got `200` with `[]` in response body as expected

If you receive a 404, it's maybe because you haven't created your index -> you must have received information in the response body like:

```
{
    "message": "Index `test` not found.",
    "code": "index_not_found",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#index_not_found"
}
```

If it's not because of this, can you detail more the steps you did so that we can reproduce your issue?

**Comment by jbinder** [comment]
@curquiza Thanks a lot for getting back! As stated I am able to access the settings, so the index should not be the issue. Also I do not get back any content in the body. What kind of details could I share in addition to help investigate?

**Comment by curquiza** [comment]
> Also I do not get back any content in the body

When calling `GET {{host}}/indexes/{{index_uid}}/settings/separator-tokens`?
You should get `[]` in the response body if you never have set any separator tokens

> What kind of details could I share in addition to help investigate?

An example with real documents, the exact calls you made and the answer you got.
Here you give an example with `{{index_uid}}` and your index is created, but I don't know how. With only the information you gave, I was not able to reproduce the issue :(

**Comment by jbinder** [comment]
> When calling GET {{host}}/indexes/{{index_uid}}/settings/separator-tokens?

Exactly.

Here is the Postman raw request/response:
```
GET /indexes/some_index/settings/separator-tokens HTTP/1.1
Authorization: Bearer [...]
User-Agent: PostmanRuntime/7.30.0
Accept: */*
Postman-Token: [...]
Host: [...]
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
 
HTTP/1.1 404 Not Found
transfer-encoding: chunked
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
vary: accept-encoding
content-encoding: gzip
date: Mon, 25 Mar 2024 10:07:20 GMT
 
```

I guess I will have to try with another version / instance.
Thanks a lot anyways!

**Comment by curquiza** [comment]
It's really weird.
Are you sure you use Meilisearch v1.7.2?

**Comment by jbinder** [comment]
That's what `meilisearch --version` states at least.

**Comment by jbinder** [comment]
Absolutely correct, the issue was an older version running, as the automated update did not restart the service.
So sorry about bothering you with that, thanks a lot for your time and help!
