### ISSUE TITLE
failed to download `candle-kernels v0.3.1

### ISSUE THREAD

**Issue by HCY2315** [meilisearch/meilisearch#4529]
stdout :  Downloading crates ...
error: failed to download `candle-kernels v0.3.1 (https://github.com/huggingface/candle.git#f4fcf609)`

Caused by:
  unable to get packages from source

Caused by:
  failed to find candle-kernels v0.3.1 (https://github.com/huggingface/candle.git#f4fcf609) in path source
note: this is an unexpected cargo internal error
note: we would appreciate a bug report: https://github.com/rust-lang/cargo/issues/
note: cargo 1.78.0-nightly (a4c63fe53 2024-03-06)

stderr :

**Comment by dureuill** [comment]
Hello @HCY2315, I cannot reproduce the issue.

Here are the commands I ran from inside the Meilisearch repository (on an up-to-date `main` branch):

1. `rustup install nightly-2024-03-06`
2. `cargo clean && rm -rf ~/.cargo/git/checkouts`
3. `cargo +nightly-2024-03-06 build`

Can you specify the commands you ran, on which commit of the Meilisearch repository?

(we can also see that the commit https://github.com/huggingface/candle.git#f4fcf609 exists)

**Comment by DRN88** [comment]
I got this, quick fix is to change the version:

```
# meili/Cargo.toml-t
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.4.2" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.4.2" }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.4.2" }
```
