### ISSUE TITLE
Would this work as a webassembly module?

### ISSUE THREAD

**Issue by bionicles** [meilisearch/MeiliSearch#455]
To integrate this with browser/client/serverless javascript, as a developer, I want to find out if this could compile to web assembly. That would be interesting because you could import a search function in the browser or alongside node processes in serverless microservices and use MeiliSearch without needing to wait for network requests. That might be hella fast

How do you feel about web assembly? 

https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

**Comment by Kerollmops** [comment]
Hey,
Thank you, your involvement in MeiliSearch is a pleasure. We thought about that before and it is something we will do research in the future.

Currently the engine hardly depends on LMDB the disk backed key-value store used internally to store and get all the data to make the search efficient, it is not possible to make the engine compile and work correctly as a WebAssembly module. I tried with an old version of MeiliSearch to keep all the data in the program itself, it was hard to work with but it worked a little bit.

The other important issue is the size of the index. When you index documents many data is saved in a data-structure, this structure can be really big, that a big problem when you index even a little amount of records.

In the future we would like to make it possible to compile the engine and to think about reducing the index data structure size.

**Comment by janus-reith** [comment]
I really hope this discussion is revived at some point. I feel like there is such a huge potential in running a lightweight search engine on the edge, utilizing some distributed KV storage.

**Comment by curquiza** [comment]
Hello @janus-reith
You're right, the potential is huge, we are aware of this, but the work is huge as well :)
Making MeiliSearch work on lambda edge in an easy and open-sourced is really complex regarding the current codebase.
Most of the core team is currently focusing on adding the most important features we are missing, for instance, the High Availability. But be sure we are still working on it 🙂

FYI, the search on the edge needs several R&D phases on our side. The first phase is to integrate segments into [milli](https://github.com/meilisearch/milli/) -> you can follow the work on [this issue](https://github.com/meilisearch/milli/issues/391).
But integrating segments is only the beginning, so it's not possible to give any ETA.

**Comment by janus-reith** [comment]
> You're right, the potential is huge, we are aware of this, but the work is huge as well :)

Awesome to hear it's still on your radar! :)

> Making MeiliSearch work on lambda edge in an easy and open-sourced is really complex regarding the current codebase.

Yeah I can imagine that there's quite some hurdles involved.
I have my eye on Cloudflare Workers and Deno Deploy, as well as any potentially emerging platforms built on a similar architecture. ^^
Maybe sometime in the future one wasm build could cover them all with some simple wrappers 🤞

**Comment by curquiza** [comment]
Hello @nolotz 

No, sorry we have not worked on this yet. It's not trivial to make meilisearch work on the edge, but it's still something we have as long term plan.
