### ISSUE TITLE
Some hybrid search results get ranking score over 1.0

### ISSUE THREAD

**Issue by Igloczek** [meilisearch/meilisearch#4550]
**Describe the bug**
When using the experimental feature of hybrid search, some part of results get `_rankingScore` over `1.0`, which makes no sense because [it's against what is said there](https://www.meilisearch.com/docs/learn/core_concepts/relevancy#ranking-score) and this simply doesn't match, as this content should get a score around zero as it has no common parts with the search query.

**To Reproduce**
1. Enable `vectorStore` experiment
```js
  await axios({
    method: "patch",
    url: "http://127.0.0.1:7700/experimental-features/",
    data: { vectorStore: true },
  })
```
2. Create index, set searchable attributes and embedders
```js
  await client.createIndex(contentId, { primaryKey: "id" })
  await client.index(contentId).updateSearchableAttributes(["simpleText"])
  await client.index(contentId).updateEmbedders({
    default: {
      source: "openAi",
      apiKey: "sk-XXXX",
      model: "text-embedding-3-small",
      documentTemplate: "{{doc.simpleText}}",
      dimensions: 1536,
    },
  })
```
3. Add documents and wait for indexing
4. Do a hybrid search with `semanticRatio` higher than `0`
```js
  const results = await client.index(contentId).search(this.query, {
    showRankingScore: true,
    hybrid: {
      semanticRatio: 0.1,
      embedder: "default",
    },
  })
```

**Current behavior**
Search results contain items with `_rankingScore` higher than `1`.

I've handpicked just a few, but they wall have exactly the same scores, doesn't matter if the text is longer or shorter.

These particular results are for query `game`, but you can reproduce it easily with many others too, just write something unrelated.

```js
results: {
  hits: [
    {
      simpleText: "Haha well some yes and some no.",
      _rankingScore: 1.1920928955078125e-7,
      _semanticScore: 1.1920929e-7,
    },
    {
      simpleText: "BioWare is cooked",
      _rankingScore: 1.1920928955078125e-7,
      _semanticScore: 1.1920929e-7,
    },
    {
      simpleText: "It's part of the joke, Leisure Suit Larry didn't flop because it had an ugly protagonist.",
      _rankingScore: 1.1920928955078125e-7,
      _semanticScore: 1.1920929e-7,
    },
    {
      simpleText: "What about Avowed?",
      _rankingScore: 1.1920928955078125e-7,
      _semanticScore: 1.1920929e-7,
    }
  ]
}
```

**Expected behavior**
I expect them to have a ranking score close to zero, as they are not relevant for the search query.

**Meilisearch version:**
1.7.4

**Comment by dureuill** [comment]
Hello,

from your sample here, it looks like the scores are all around `1.1920928955078125e-7`, if I'm not missing anything.

The `e-7` here is important, this is [scientific notation](https://en.wikipedia.org/wiki/Scientific_notation). The number being expressed here is equal to `0.00000011920928955078125`, so far below 1.
