### ISSUE TITLE
Japanese Kanji cannot search

### ISSUE THREAD

**Issue by exkoi** [meilisearch/meilisearch#4561]
**Describe the bug**
Japanese Kanji cannot search

**To Reproduce**
Create Index:
```bash
curl -X POST 'http://localhost:7700/indexes' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "uid": "hospitals",
    "primaryKey": "id"
  }'
```
Setting index:
```bash
curl -X PATCH 'http://localhost:7700/indexes/hospitals/settings' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "searchableAttributes": [
      "name",
      "kana"
    ],
    "displayedAttributes": [
      "name",
      "kana"
    ]
  }'
```

Insert documents:
```bash
curl -X POST 'http://localhost:7700/indexes/hospitals/documents' \
  -H 'Content-Type: application/json' \
  --data-binary '[
      { "id": 1, "name": "日健クリニック", "kana": "ニッケンクリニック" },
      { "id": 2, "name": "日見中央病院", "kana": "ヒミチュウオウビョウイン" }
  ]'
```

**Expected behavior**
When search for the word "健", I want "日健クリニック" to be hit, but documents containing "見" are hit.
In Japanese, "健" and "見" both have the same pronunciation as "ken", but they have different meanings.

**Screenshots**
![meilisearch](https://github.com/meilisearch/meilisearch/assets/110365897/cefc77e4-57c0-453f-ae66-81f11067e122)

**Meilisearch version:**
v1.7.2

**Additional context**
Docker Image: getmeili/meilisearch:v1.7

**Comment by uintaam** [comment]
This is because Meilisearch defaults to Chinese support. I have the same issue https://github.com/meilisearch/meilisearch/issues/4162

**Comment by exkoi** [comment]
> This is because Meilisearch defaults to Chinese support. I have the same issue #4162
> 
> You can use the Japanese builds to solve your problem #3882

@uintaam Thank you for your reply!
Can I use Japanese build without Docker? (I use Ubuntu22.04 without Docker in production)

**Comment by curquiza** [comment]
Hello @exkoi two solutions
- compile from source. See the related [docs](https://www.meilisearch.com/docs/learn/getting_started/installation#local-installation) ("Source tab"). But instead of `cargo build --release`, use this command: `cargo build --release -p meilisearch -p meilitool --no-default-features --features "analytics mini-dashboard japanese"`
- or, if you don't want to bother with this, you can also use our cloud offer and ask support team (in the chat box) to use Japanese version

**Comment by exkoi** [comment]
Thank you @curquiza !
I'll try your solution

**Comment by curquiza** [comment]
I'm closing this issue since we have another opened 😊
