### ISSUE TITLE
Increase the default search cutoff

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4575]
Right now, the search cutoff is set at 150ms, which is perfect for a good search-as-you-type experience except... when we do anything related to AI.
Everything related to AI is just so slow that keeping a normal cutoff would stop the search requests before doing anything meaningful.

As a first fix for v1.8, we’re simply going to increase the search cutoff from 150ms to 1.5s; this should still be enough to protect the instance against malicious requests without blocking the AI stuff.
It won’t improve the search-as-you-type experience.

**Comment by curquiza** [comment]
Closed by #4576
