### ISSUE TITLE
Meilisearch 1.8.0-rc.1 stuck process when adding hugging face and ollama embedders

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch#4585]
**Describe the bug**
When I test adding either hugging face or ollama embedders Meilisearch seems to be stuck processing indefinently on v1.8.0-rc1. Running the exact same code on v1.8.0-rc0 doesn't have this issue.

**To Reproduce**
Here is a minimum reproducable Python program

```py
import asyncio

from httpx import AsyncClient as HttpxAsyncClient

from meilisearch_python_sdk import AsyncClient
from meilisearch_python_sdk.models.settings import (
    HuggingFaceEmbedder,
    MeilisearchSettings,
)


async def enable_vector_search() -> None:
    async with HttpxAsyncClient(
        base_url="http://127.0.0.1:7700", headers={"Authorization": "Bearer masterKey"}
    ) as client:
        await client.patch("/experimental-features", json={"vectorStore": True})


async def main() -> int:
    await enable_vector_search()
    async with AsyncClient("http://127.0.0.1:7700", "masterKey") as client:
        settings = MeilisearchSettings(
            embedders={
                "default": HuggingFaceEmbedder(),  # bad
            },
        )
        await client.create_index("movies", settings=settings)

    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
```

**Expected behavior**
The process should either compete or I should at least get an error.

**Screenshots**

**Meilisearch version:**
v1.8.0-rc.1

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
hello @sanders41 thanks for the report.

the team will work on it as soon as possible! 😊 We will fix this before v1.8.0

**Comment by ManyTheFish** [comment]
Hello @sanders41,

I don't manage to reproduce your bug exactly, 
Did you put any documents in your index? If so, could you let me know if you inserted your documents before changing the settings?

I've tried the following process:
1) Put documents
```
curl -XPOST localhost:7700/indexes/movies/documents -H "Content-type: Application/json" -d @movies.json
```
2) change settings
```
curl \
  -X PATCH 'http://localhost:7700/indexes/movies/settings' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "embedders": {
      "default": {
        "source": "huggingFace"
      }
    }
  }'
```

Is it right? or do I miss something?

Thank you for your report!

**Comment by sanders41** [comment]
Alright I have done some more investigating and here is what I have found so far. On rc.1 it does complete it is just way slower. I did not add any documents to the index. On rc.1 it takes ~30 seconds (sometimes much longer though), the same thing takes ~0.148 seconds on rc.0.

My current theory is this delay is causing my test suite to time out and error, which would explain why it looked like it never finished processing.

For reference this is the exact JSON that is being sent:

```json
{
  "embedders": {
    "default": {
      "source": "huggingFace",
      "model": null,
      "revision": null,
      "documentTemplate": null,
      "distribution": null
    }
  }
}
```

The same thing happens when I try ollama. As far as I can tell these are the only two that do it.

**Comment by ManyTheFish** [comment]
Oh! Ok!
So it's a slowness. Thank you for the precisions I am currently investigating the issue.
I plan to fix it for v1.8 and maybe for the next rc.

**Comment by ManyTheFish** [comment]
Ok, it's weird,
so, it means that it's not completely related to the changes between rc0 and rc1 :/ 

Let's keep this issue open. I will ask for a second eye in the engine team.

Thank you for the report!

**Comment by sanders41** [comment]
Updating with a new log message I just saw while running tests on rc1 again. I assume this is related because it stalled at this point.

```console
WARN milli::vector::rest: Failed: runtime error: could not reach embedding server: http://localhost:11434/api/embeddings: Connection Failed: Connect error: Connection refused (os error 111)
```

**Comment by dureuill** [comment]
Hello @sanders41 :wave:

Up to RC0, we would download the model from the Hugging Face Hub and make a call to ollama only on adding the first document needing to be embedded.

Starting with RC1, we perform these operations right when updating the settings. If the model from the Hugging Face Hub is not in the local cache of the machine, performing this download operation is going to take time. 

Performing these operations when updating the settings allow for more intuitive errors. It also does not pessimize performance in the general case, because that cost already existed before RC1, it was just delayed up to the first document addition.

Thank you for your report :heart:

**Comment by sanders41** [comment]
Thanks @dureuill this definitely explains the issue I was seeing. Knowing this I can either patch the route in tests, or really skipping HuggingFace and Ollama should be fine in my tests now that I know the reason and that settings updates are working.

**Comment by sanders41** [comment]
I just realized it also explains why I couldn't find it with a bisect. This first time it would be slow, then the model would be cached so it wouldn't happen again until I removed the volume and tried again.
