### ISSUE TITLE
API key for local test

### ISSUE THREAD

**Issue by djKooks** [meilisearch/MeiliSearch#459]
Hello.
Currently I'm trying to test this on Java app. While looking on, it seems they are all require 'API key' to setup in header with `X-Meili-API-Key` key. 

If I want to test by accessing MeiliSearch running via compiling source, how can I find this API key?

**Comment by Kerollmops** [comment]
Hey, IIRC if you do not define an api key at the start of the program no such api key is require to make any call on the server. However, if you define one vie the `MEILI_API_KEY` env var or via the `—api-key` argument it will be requested for all the write calls.

**Comment by djKooks** [comment]
@Kerollmops got it~
Also, I've make some separate java API wrapper for private project using this.
- https://github.com/djKooks/meilisearch-java (currently only includes 'indexes' API).

If you're interested please take a look(comment is very welcome). Or if you are preparing for JVM wrapper, please let me know when it is opened(hope to contribute).

Thanks~

**Comment by Kerollmops** [comment]
Wow, so cool!

What do you think about moving your Java client into the meilisearch organization? This way it would be considered official, and you will always be able to maintain it :)

We already moved [the Go client](https://github.com/meilisearch/meilisearch-go) that was made by [an external contributor](https://github.com/alexisvisco), it is always maintain by the original maintainer, and this is the official Go client for MeiliSearch.

**Comment by djKooks** [comment]
@Kerollmops great~What should I do for that? 
Please invite me to your group if needed.

**Comment by Kerollmops** [comment]
I think you can transfert it by [following these steps](https://help.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account), did you try that? If you can't transfert it to the organization directly, please transfert it to me and I will move it to the organization myself (with the reop creation rigths) :)

I would like this client to follow the naming of the other ones and be named, `meilisearch-java`? What do you think about that?

**Comment by djKooks** [comment]
@Kerollmops okay~
I've follow that step but it said I couldn't create public repository to meilisearch organization, so just send transfer request to your ID.

Please check and approve.

**Comment by djKooks** [comment]
@Kerollmops please let me know if you have a problem on working it~

**Comment by Kerollmops** [comment]
Ho, sorry, yes I saw the github email a little bit too late last time you tried to tranfert it to me (I was in vacation). Could you transfert it to me again, I will more careful now :)

**Comment by djKooks** [comment]
@Kerollmops okay~did it again. Please check~

**Comment by Kerollmops** [comment]
Hum... I just clicked on the link in the mail, the mail says that the link will expires "in about a day", I received it 1h ago and it is already expired.

![Screenshot_2020-02-11 Build software better, together](https://user-images.githubusercontent.com/3610253/74234788-f1629d80-4ccd-11ea-9ec2-b98b535d82fe.png)

**Comment by djKooks** [comment]
@Kerollmops I just checked that repository has been transferred to you. Is it okay?

**Comment by Kerollmops** [comment]
Ho, that's right, the repository as been transfered to me, I thought it was not. I made you an outside collaborator with admin rights. We will add a README to specify that it is a work in progress.

Thank you for your help :)

**Comment by djKooks** [comment]
@Kerollmops thanks for follow-up!
I'll keep update java-api. Please update issue or commit if you have any suggestions~
