### ISSUE TITLE
> 只匹配关键词，不分词。

### ISSUE THREAD

**Issue by ValarDohaerisX** [meilisearch/meilisearch#4590]
> 只匹配关键词，不分词。
> 
> 如何配置这个？
> 
> for example search "酒吧"
> 
> ```
> http://127.0.0.1:7700/indexes/books/search?q=%E9%85%92%E5%90%A7&attributesToHighlight=chapter
> ```
> 
> 结果
> 
> ```
> <em>酒吧</em>Review Dazzle Bar, <em>酒吧内</em>/At Bar
> ```
> 
> `\<em\>酒吧内\</em\>/At Bar`这不是我需要的

@jet10000 你好啊，我现在也遇到这个问题了，我想根据搜索内容模糊搜索，但是会分词，把不相关的结果也会带出来，请问你是怎么解决的？

_Originally posted by @ValarDohaerisX in https://github.com/meilisearch/meilisearch/issues/790#issuecomment-2067536283_

**Comment by curquiza** [comment]
Hello @ValarDohaerisX 

We don't speak Chinese, can you describe your issue in English please?
You linked an issue, but since you created a new one, can you detail exactly
- the steps you did
- what you got
- what you expected to get

Thank you

**Comment by ValarDohaerisX** [comment]
> 你好@ValarDohaerisX
> 
> 我们不会说中文，您能用英语描述您的问题吗？ 您链接了一个问题，但由于您创建了一个新问题，您能否准确地详细说明
> 
> * 你所做的步骤
> * 你有什么
> * 你期望得到什么
> 
> 谢谢
Sorry, this is my first time asking a question. Please forgive my lack of professionalism.

Last answer：
Hello, I am also encountering this problem now. I want to blur the search based on the search content, but I can segment words and bring out irrelevant results. How did you solve this problem?

Hello, I hope Meilisearch can only be used for fuzzy search without the need for word segmentation. May I know how to configure it to be implemented? I am using Java as my language and I have tried many methods, but none of them have worked.

**Comment by curquiza** [comment]
Hello @ValarDohaerisX 

> I want to blur the search based on the search content, but I can segment words and bring out irrelevant results. How did you solve this problem?

What do you mean exactly?
What do you send to Meilisearch? What do you get? What do you expect to get?

Also, which version of Meilisearch do you use?

**Comment by curquiza** [comment]
Closing this due to a lack of answer and precision
Feel free to re-open if having answers
