### ISSUE TITLE
`distribution` field not retrieved correctly on the `settings/embedders` route

### ISSUE THREAD

**Issue by mdubus** [meilisearch/meilisearch#4594]
**Describe the bug**
I added the following embedder to my settings: 
```
    "default": {
        "source": "openAi",
        "model": "text-embedding-ada-002",
        "apiKey": "sk-wv<...>",
        "documentTemplate": "A movie titled '{{doc.title}}' whose description starts with '{{doc.overview|truncatewords: 20}}'",
        "distribution": {
            "mean": 0.7,
            "sigma": 0.3
        }
    },
```

When I GET the `settings` route, I retrieve the following (which is correct): 
```
   "default": {
            "source": "openAi",
            "model": "text-embedding-ada-002",
            "apiKey": "sk-wvXXXXXX...",
            "documentTemplate": "A movie titled '{{doc.title}}' whose description starts with '{{doc.overview|truncatewords: 20}}'",
            "distribution": {
                "mean": 0.7,
                "sigma": 0.3
            }
        }
```

But when I GET the `settings/embedders` route, I retrieve the following:
```
    "default": {
        "source": "openAi",
        "model": "text-embedding-ada-002",
        "apiKey": "sk-wvXXXXXX...",
        "documentTemplate": "A movie titled '{{doc.title}}' whose description starts with '{{doc.overview|truncatewords: 20}}'",
        "distribution": {
            "mean": 0.699999988079071,
            "sigma": 0.30000001192092896
        }
    },
```

As you can see, the `distribution` field doesn't match the one I sent

**To Reproduce**

1. Enable the `vectorStore` exp. feature
2. Add a new embedder as the one described above
3. Check the `distribution` field by getting both the `settings` and the `settings/embedders` route. See inconsistency.

**Expected behavior**
The `distribution` field retrieved on the `settings/embedders` route should match the one I sent, and the one that I'm getting on the `settings` route

**Screenshots**
<img width="1004" alt="Capture d’écran 2024-04-23 à 11 18 24" src="https://github.com/meilisearch/meilisearch/assets/30866152/de74a320-ab01-4fa9-8ff5-96df174fa817">
<img width="1001" alt="Capture d’écran 2024-04-23 à 11 18 39" src="https://github.com/meilisearch/meilisearch/assets/30866152/02432410-1d3d-4ede-a512-58f603eaf0ac">

**Meilisearch version:**
v1.8.0-rc.0

**Comment by ManyTheFish** [comment]
fixed by https://github.com/meilisearch/meilisearch/pull/4600
