### ISSUE TITLE
`Ollama` embedder has missing fields on GET

### ISSUE THREAD

**Issue by mdubus** [meilisearch/meilisearch#4595]
**Describe the bug**
When adding an Ollama embedder and retrieving it, some fields are missing

**To Reproduce**

1. Enable the `vectorStore` exp. feature
2. Add a new Ollama embedder (see below)
3. Get the `settings/embedders` or the `settings` route. The `url` and `apiKey` fields are missing from this embedder

Example of an Ollama embedder:
```
    "ollama": {
        "source": "ollama",
        "url": "http://localhost:11434/api/embeddings",
        "apiKey": "<your-ollama-api-key>",
        "model": "nomic-embed-text",
        "documentTemplate": "blabla"
    }
```

**Expected behavior**
The Ollama embedder should return all its fields for consistency reasons. 
It should work both on the `settings` and the `settings/embedders` routes

**Screenshots**

**Embedder sent:**
<img width="993" alt="Capture d’écran 2024-04-23 à 12 06 40" src="https://github.com/meilisearch/meilisearch/assets/30866152/3c195192-6411-45c6-8636-1edcaf9e3fda">

**Embedder retrieved:**
<img width="1008" alt="Capture d’écran 2024-04-23 à 12 06 48" src="https://github.com/meilisearch/meilisearch/assets/30866152/266c272f-d257-4ab6-b4ca-928bc04b95f6">

**Meilisearch version:**
v1.8.0-rc.0

**Comment by ManyTheFish** [comment]
fixed by https://github.com/meilisearch/meilisearch/pull/4600
