### ISSUE TITLE
Index gets into bugged state when `documentDeletion` task fails due to transaction size (`MDB_TXN_FULL`)

### ISSUE THREAD

**Issue by queer** [meilisearch/meilisearch#4598]
**Describe the bug**
My production Meilisearch instance contains around 2.2 million documents, that are updated once daily as part of a data ingestion job. Once daily, documents are ingested, and then an hour later, a job runs to purge old documents with a timestamp filter. The deletion job is this cURL command:

```sh
curl -v -H "Authorization: Bearer ${MEILISEARCH_API_KEY}" \
    -H "Content-Type: application/json" \
    "${MEILISEARCH_HOST}/indexes/${INDEX_NAME}/documents/delete" \
    -d "{\"filter\": \"timestamp < $(date --date="00:00 today" -u "+%s000")\"}"
```

Generally, this works. However, today my index got stuck in an odd state where the number of documents reported by the `/stats` endpoint differs from the field counts reported:

```js
{
  "databaseSize": 24604622848,
  "lastUpdate": "2024-04-23T13:30:57.927004309Z",
  "indexes": {
    "prod_index": {
      "numberOfDocuments": 2156729,
      "isIndexing": false,
      "fieldDistribution": {
        "_geo": 4361739,
        // repeat for 16 more fields, field distribution numbers are exactly the same
        "timestamp": 4361739
      }
    }
  }
}
```

Looking through meilisearch logs, indexing consistently succeeds; no errors are reported. However, the most-recent document deletion job failed with this error:

```sh
{
  "results": [
    {
      "uid": 20182,
      "indexUid": "...",
      "status": "failed",
      "type": "documentDeletion",
      "canceledBy": null,
      "details": {
        "providedIds": 0,
        "deletedDocuments": 0,
        "originalFilter": "\"timestamp < 1713830400000\""
      },
      "error": {
        "message": "internal: MDB_TXN_FULL: Transaction has too many dirty pages - transaction too big.",
        "code": "internal",
        "type": "internal",
        "link": "https://docs.meilisearch.com/errors#internal"
      },
      "duration": "PT343.739626897S",
      "enqueuedAt": "2024-04-23T13:00:44.308611462Z",
      "startedAt": "2024-04-23T13:01:15.239361209Z",
      "finishedAt": "2024-04-23T13:06:58.978988106Z"
    }
  ],
  "total": 11,
  "limit": 1,
  "from": 20182,
  "next": 12580
}
```

Interestingly, the `/indexes/${INDEX}/search` route still seems to work, but the `/multi-search` endpoint returns 500 errors, meaning my frontend application no longer works as expected. Sample logs of that error:

```sh
Apr 23 15:51:08 myhost meilisearch[51926]: 2024-04-23T15:51:08.275969Z ERROR meilisearch: info=panicked at milli/src/search/facet/facet_distribution.rs:215:22: called `Option::unwrap()` on a `None` value
Apr 23 15:51:08 myhost meilisearch[51926]: 2024-04-23T15:51:08.276406Z ERROR meilisearch: info=panicked at milli/src/search/facet/facet_distribution.rs:215:22: called `Option::unwrap()` on a `None` value
Apr 23 15:51:08 myhost meilisearch[51926]: 2024-04-23T15:51:08.276897Z ERROR HTTP request{method=POST host="search.prod.###.###" route=/multi-search query_parameters= user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15 status_code=500 error=Inside `.queries[0]`: task 1118714 panicked}: tracing_actix_web::middleware: Error encountered while processing the incoming HTTP request: ResponseError { code: 500, message: "Inside `.queries[0]`: task 1118714 panicked", error_code: "internal", error_type: "internal", error_link: "https://docs.meilisearch.com/errors#internal" }
```

A similar bug that triggered with this setup was #4300, but that is a different issue.

**To Reproduce**
Unclear, this issue suddenly triggered today. It might just be as simple as bulk-deleting many documents at once.

**Expected behavior**
Bulk-deletion should not leave my index in a bugged state.

**Meilisearch version:**
```js
{
  "commitSha": "unknown",
  "commitDate": "unknown",
  "pkgVersion": "1.7.6"
}
```

**Comment by queer** [comment]
To follow up on this, it doesn’t happen *every* day; today’s run went fine. It’s just concerning that it can happen at all and leave my index in a state where I have to fully delete and recreate it.

**Comment by Kerollmops** [comment]
Hey @queer 👋

Thank you very much for the report. It seems related to the deletion by filter, and it is not the first report we got about it. I'll create an issue to link them together and investigate this bug simultaneously.

However, I have a few questions:
 - Have you indexed your 2.2 million documents on a v1.7.6 from the beginning, or did you upgrade from a previous version?
 - How did you upgrade from the previous version if that was the case?
 - What is the OS and architecture of your machine, are you running on Docker? `uname -a`
 
 Have a good day 🌻

**Comment by queer** [comment]
Hello 🌈 This has not occurred again since the first time it happened, so I'm unsure if it was "just" a transient issue. I'll be sure to update if it comes up again!

**Comment by queer** [comment]
I have not been able to reproduce this thus far and will close this unless it comes up again (:
