### ISSUE TITLE
Recommended storage class?

### ISSUE THREAD

**Issue by Bajix** [meilisearch/MeiliSearch#460]
I'm working on deploying MeiliSearch via helm and was wondering if you had recommendations for resource allocations. Is there a compelling benefit to use a Provisioned IOPS SSD (io1) over a General Purpose SDD (gp2) or is it the case that so much is in memory that sustained IOPS performance isn't essential?

**Comment by Kerollmops** [comment]
Hey,
The data that we store on disk is managed by LMDB, therefore the best I can do to help is by guiding you to [the LMDB benchmarks](https://symas.com/lmdb/technical).

LMDB is a disk based key-value store which cache is fully based on memory mapping, therefore the data is in memory only when the OS thinks its useful.

**Comment by stevemk14ebr** [comment]
you should run on an i3 ec2 machine. EBS based drives of any time do not perform great with lmdb as DB size grows beyond ram.
