### ISSUE TITLE
The `settings` route should return the `embedder` field

### ISSUE THREAD

**Issue by mdubus** [meilisearch/meilisearch#4601]
**Describe the bug**
When activating the `vectorStore` experimental feature and calling the `settings` route of my index (without having added any ambedders), I don't receive the `embedder` field.

**To Reproduce**
1. Activate the `vectorStore` experimental feature
2. GET the `settings` route
3. See error

**Expected behavior**
Since: 
- the `settings` route returns all available fields, even when they're null or empty
- the `settings` route returns the `embedder` field when embedders were added

I think we should retrieve the `embedders` field when it's empty too. 
Since its default value is `null`, I suggest retrieving that. But we could also retrieve an empty object too (I'll leave that decision to you 😄)

**Meilisearch version:**
v1.8.0-rc.0

**Comment by mdubus** [comment]
Closing since this behaviour is intended. 
See the related PR: https://github.com/meilisearch/meilisearch/pull/4318

**Comment by ManyTheFish** [comment]
Hello @mdubus,
It is a voluntary choice from the @meilisearch/engine-team. There is a PR specifically hiding this setting:
https://github.com/meilisearch/meilisearch/pull/4318

However, this may be discussed with @dureuill when he comes back.

Thank you for the report @mdubus!

**Comment by dureuill** [comment]
Hello, thanks @mdubus and @ManyTheFish for the report and discussion,

indeed, the current behavior is suboptimal. It was a tough balancing act between hiding the setting when the feature was never enabled and keeping the implementation simple as this is a detail of an experimental feature.
