### ISSUE TITLE
Only ever store vectors in the vector store + hide embeddings

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4607]
Related product team resources: [PRD](https://www.notion.so/meilisearch/AI-Search-cd5b8d6ce94944618914ab8d958aceb0) (_internal only_)
Related product discussion: https://github.com/orgs/meilisearch/discussions/677

## Motivation

Improve AI search performance

## Usage

[Only ever store vectors in the vector store and hide embeddings
](https://meilisearch.notion.site/v1-9-AI-search-changes-e90d6803eca8417aa70a1ac5d0225697?pvs=25#38e6d3adf40e4ef1be14a3c4be39df94)

### Reminders when modifying the Setting API

- [ ] Ensure the new setting route is at least tested by the [`test_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/tests/settings/get_settings.rs#L276)
- [ ] Ensure Analytics are fully implemented
  - [ ] `/settings/my-new-setting` configurated in the [`make_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L141-L165)
  - [ ] global `/settings` route configurated in the [`update_all` function](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L655-L751)
- [ ] Ensure the dump serializing is consistent with the `/settings` route serializing, e.g., enums case can be different (`camelCase` in route and `PascalCase` in the dump)

#### Special cases when adding a setting for an experimental feature

- [ ] ⚠️ API stability: The setting does not appear on the main settings route when the feature has never been enabled (e.g. mark it `Unset` when returned from the index in this situation. See [an example](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch-types/src/settings.rs#L608))
- [ ] The setting cannot be set when the feature is disabled, either by the main settings route or the subroute (see [`validate_settings` function](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch/src/routes/indexes/settings.rs#L811))
- [ ] If possible, the setting is reset when the feature is disabled (hard if it requires reindexing)

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team

**Comment by dureuill** [comment]
- Updated [usage](https://meilisearch.notion.site/v1-9-AI-search-changes-e90d6803eca8417aa70a1ac5d0225697?pvs=25#38e6d3adf40e4ef1be14a3c4be39df94), there are 3 possibilities for the API, to be discussed with product.

- About the implementation:
    - After #4633, at indexing time embeddings are either "userProvided" or not.
    - for "userProvided" embeddings, modifications to the document never trigger regeneration
    - else, modifications to the document trigger re-render of the document template and regeneration of the embedder as needed
    - per embedder, add a roaring bitmap of documents that provide "userProvided" embeddings
    - in the indexing process in extract_vector_points, set the bit corresponding to the document depending on the "userProvided" subfield in the `_vectors` field.
    - when writing the dump in batch.rs: write the `userProvided` field depending on the bitmap for each embedder
    - in the document DB in typed chunks, when writing the `_vectors` field, remove all keys corresponding to an embedder
    - make `_vectors` non-searchable/non-filterable,etc. should we remove `_vectors` from the flattened obkv, or individually from each extractor?

**Comment by curquiza** [comment]
Closed by #4649
