### ISSUE TITLE
Strange result when applying filters to an array

### ISSUE THREAD

**Issue by erycson-cubo** [meilisearch/meilisearch#4614]
**Describe the bug**
I have an index with car parts, and within each record, there is a list of suppliers of that part, but for some reason, when I want to filter all the parts by the ID of the supplier that has that part, a part that does not have that part is being returned. has no supplier

**To Reproduce**
I still haven't been able to isolate the problem to repeat the error, but I have screenshots of this happening

**Screenshots**
Screenshot of the request made
![meilisearch - 1 1](https://github.com/meilisearch/meilisearch/assets/127861451/cac266fd-a310-4e8d-a98a-c6d176f41f4d)

Screenshot of the search result where the error occurs
![meilisearch - 1](https://github.com/meilisearch/meilisearch/assets/127861451/2974e62d-aa49-42e0-b6fa-9d0aa3fc801c)

Screenshot showing that other results work correctly
![meilisearch - 2](https://github.com/meilisearch/meilisearch/assets/127861451/d5287683-41b0-4db6-b85a-de4541986b11)

**Meilisearch version:**
v1.6.0

**Comment by Kerollmops** [comment]
Hey @erycson-cubo 👋

We fixed this bug [in v1.7.6](https://github.com/meilisearch/meilisearch/releases/tag/v1.7.6). I advise you to upgrade as soon as possible.

Have a nice day 🤿
