### ISSUE TITLE
Improve compatibility with kubernetes by updating actix-web

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4625]
[We noticed that actix-web is potentially not using the right number of CPUs (internal link)](https://github.com/meilisearch/meilisearch-support/issues/157#issuecomment-2098321587) on small machines. Bumping to the latest version of actix-web leverage the use of the `available_parallelism` standard function and could fix the bug.

**Comment by curquiza** [comment]
Closed by #4675, will be released in rc1
