### ISSUE TITLE
Test CI failing when enabling/disabling some features

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4629]
Scheduled CI is failing on `main`

https://github.com/meilisearch/meilisearch/actions/runs/9057514821

- [ ] Fix CI `Tests almost all features`, [cf manifest](https://github.com/meilisearch/meilisearch/blob/95fcd17373f97076383346159d14432309c86a45/.github/workflows/test-suite.yml#L78)

<img width="1135" alt="Capture d’écran 2024-05-13 à 10 05 35" src="https://github.com/meilisearch/meilisearch/assets/20380692/28e99cb7-86e4-44c0-b963-a45be9955aa1">

- [ ] Fix CI `Test disabled tokenization`, [cf manifest](https://github.com/meilisearch/meilisearch/blob/95fcd17373f97076383346159d14432309c86a45/.github/workflows/test-suite.yml#L101)

<img width="1063" alt="Capture d’écran 2024-05-13 à 10 06 43" src="https://github.com/meilisearch/meilisearch/assets/20380692/6287480d-9842-484d-a2f6-e2950568fa6e">

**Comment by ManyTheFish** [comment]
I've created an issue on Charabia to fix this:
https://github.com/meilisearch/charabia/issues/290

**Comment by curquiza** [comment]
@ManyTheFish it's stil failing 😢

**Comment by curquiza** [comment]
Fiiiiiiixed 🎉 
https://github.com/meilisearch/meilisearch/actions/runs/9495849303
