### ISSUE TITLE
Create a default case for un-rankable field types

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#463]
If I have documents that contain `release_date' and I want to sort them by that date, I need to add this field to the ranking_rules. But if in a document this field doesn't exist or is not a number, all reindexing will fail and the ranking_rules will never be applied.

To solve this problem I propose the following update. 

Create a new case in the enum Number which could be `Null`. This new option will be the default if the value cannot be converted to a number. It will necessarily be less than any other option and equal to each other.

**Comment by jet10000** [comment]
how to query sort documents by date?

**Comment by Kerollmops** [comment]
Hey @jet10000,
You must first make you dates be simple integers (timestamps will do the job) then add the field name to [the list of criteria the engine will use](https://docs.meilisearch.com/references/settings.html#add-or-replace-index-settings).
