### ISSUE TITLE
matching strategy "all" is not matching expected hits

### ISSUE THREAD

**Issue by mdostmann** [meilisearch/meilisearch#4636]
**Describe the bug**
When using matching strategy 'all', I expect that documents where all search terms of the query match at least one searchable attribute are considered as hits.
However, it seems that for some reason documents that should get considered as valid hits are ignored and not returned in the result.

**To Reproduce**
1. set up fresh meili V1.8 instance
2. add the [movies.json](https://www.meilisearch.com/movies.json) to the index
3. do a search with matchingStrategy set to 'all' with one search term
**Request POST /indexes/movies/search:**
`{
    "q": "Taisto",
    "matchingStrategy": "all"
}`
**Result**
1 hit, movie "Ariel", as expected
4. do a search with matchingStrategy set to 'all' with two search terms
**Request POST /indexes/movies/search**
`{
    "q": "Kasu Taisto",
    "matchingStrategy": "all"
}`
**Result**
no hits

**Expected behavior**
In the given example, the overview attribute of the movie contains both search terms and this should get returned as a hit.

**Meilisearch version:**
V1.8

**additional context**
The behaviour can also be reproduced via [the matching strategy example](https://matching-strategy.meilisearch.com/)

**Comment by dureuill** [comment]
Hello 👋 

In your provided query `"Kasu Taisto"`, looks like the first word is a **prefix** of `Kasurinen` from the documents.

Prefix search is only applied on the last query term, **even** with the `all` matching strategy.

Looking for `Kasurinen Taisto` does return the expected hit.

**Comment by mdostmann** [comment]
Hi @dureuill and thank you for your response.
I think I do not get how this is supposed to work. E.g., searching for "Ted John" will return documents where both terms match, same for "Irving John".
"Irvi John", on the other hand, does not match any document.
"Taisto miner Finnish Kasu" does match, as does "Taisto miner Finnis Kasu" but not "Taisto miner Finn Kasu".

This is probably the intended behaviour, although I'm having a rough time figuring out what I can expect to match, especially due to this [blog](https://blog.meilisearch.com/matching-strategy/): "This matching strategy is called: all because all query terms must be present in the document for it to be returned."

The examples above all query terms that seem to be present and proper prefixes.

Is this really the intended behaviour?

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
