### ISSUE TITLE
User input stop words

### ISSUE THREAD

**Issue by Heveya** [meilisearch/meilisearch#4637]
I have search form with 2 text fields: "search text" and "no search text";
The first is common search text field, the second list of words that should be used to remove found result from first input.

Example
Have object: "a b c", "b c d", "c d a",
Search: "a c" (found: "a b c", "b c d", "c d a")
No search: "b" (excluded: "a b c", "b c d")
Result: "c d a"

How i could make it in POST http://localhost:7700/search?

**Comment by curquiza** [comment]
Hello @Heveya 
I'm not sure I get it, but can the negative search operator help you?
https://www.meilisearch.com/docs/reference/api/search#negative-search

**Comment by Heveya** [comment]
> Hello @Heveya I'm not sure I get it, but can the negative search operator help you? https://www.meilisearch.com/docs/reference/api/search#negative-search

Thanks for answer. This is what i need.

**Comment by ManyTheFish** [comment]
Hello @Heveya,
If the negative search operator suits your needs, can we close this issue as solved?

Thank you!

**Comment by Heveya** [comment]
Yes, you can.
