### ISSUE TITLE
v1.8.0 _geoRadius filter returns no results

### ISSUE THREAD

**Issue by bcicen** [meilisearch/meilisearch#4640]
Following the exact [example steps in the geosearch guide](https://www.meilisearch.com/docs/learn/fine_tuning_results/geosearch), a search using only `_geoRadius` filter will consistently return no results: 

```bash
curl \
  -X POST 'http://localhost:7700/indexes/restaurants/search' \
  -H 'Content-type:application/json' \
  --data-binary '{ "filter": "_geoRadius(45.472735, 9.184019, 2000)" }'
```

The same request returns results as expected on v1.7.6.

In both versions, `_geoBoundingBox` works as expected.

**Comment by ManyTheFish** [comment]
fixed by https://github.com/meilisearch/meilisearch/pull/4642
