### ISSUE TITLE
After setting `distinct_attribute` values inside `facetStats` and `facetDistribution` become incorrect.

### ISSUE THREAD

**Issue by zxcq544** [meilisearch/meilisearch#4677]
**Describe the bug**
I am building e-commerce form. To build form I use values from `facetStats` and `facetDistribution`. 
Before setting `distinct_attribute` eveything works correctly and I get all values for `price`(min and max):
```python
{'estimatedTotalHits': 2,
 'facetDistribution': {'price': {'100': 1, '200': 1}},
 'facetStats': {'price': {'max': 200.0, 'min': 100.0}}, #important
 'hits': [{'distinct_id': 1, 'id': 0, 'price': 100},
          {'distinct_id': 1, 'id': 1, 'price': 200}],
 'limit': 20,
 'offset': 0,
 'processingTimeMs': 0,
 'query': ''}
```
After setting `distinct_attribute` my facets lose data:
```python
{'estimatedTotalHits': 1,
 'facetDistribution': {'price': {'100': 1}},
 'facetStats': {'price': {'max': 100.0, 'min': 100.0}},  #important
 'hits': [{'distinct_id': 1, 'id': 0, 'price': 100}],
 'limit': 20,
 'offset': 0,
 'processingTimeMs': 0,
 'query': ''}
```
Here we can see that both `min` and `max` are same and `facetDistribution` shrinked to 1 value.
**To Reproduce**
1. Data that I used:
```python
[
    {
        "id": 0,
        "price": 100,
        "distinct_id": 1
    },
    {
        "id": 1,
        "price": 200,
        "distinct_id": 1
    }
]
```
2. Settings that I used(in python):
```python
client.index(index_name).update_filterable_attributes(["price"])
client.index(index_name).update_sortable_attributes(["price", ])
client.index(index_name).update_distinct_attribute("distinct_id")
```

**Expected behavior**
I expect facets to show data for all items in index even if they are using `distinct_attribute`. It allows to build complete user interface forms for faceted search.

**Screenshots**
Because of this problem my form looks like that :
![image](https://github.com/meilisearch/meilisearch/assets/5781268/c4d2bc83-f3c5-4023-8b0a-f59a561f11fb)

But it should look like that:
![image](https://github.com/meilisearch/meilisearch/assets/5781268/5247ef68-8127-49d6-9959-487a02c9950a)

Here we can see that audio speakers are grouped by `nominal impedance` which is `distinct_attribute` for them.
But because of current facet behaviour it makes impossible to build UI forms when using facets with `distinct_attribute` because it shrinks data to 1 item which is shown and doesn't take in consideration all of available items.

**Meilisearch version:**
Package version:        "1.8.0"

**Comment by zxcq544** [comment]
Currently solved it by adding copy of index without `distinct attribute`. And that index is for facets only.

**Comment by ManyTheFish** [comment]
Hello @zxcq544,
If I understand well, your issue seems related to the following discussion:
https://github.com/orgs/meilisearch/discussions/741

We plan to solve the issue reported in the discussion by allowing the user to set the distinctAttribute at search time instead of at setting time. This would allow you to have a consistent `facetDistribution` using a multi-index search.

We plan to release it in 1.9.0 but it could be delayed to 1.10.0 if we encounter any issue during the implementation. 😄

**Comment by curquiza** [comment]
Yes, I will close it, thank you @zxcq544
