### ISSUE TITLE
Misleading error message when configuring the embedders

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4690]
**Describe the bug**
Found a confusing error message while trying to configure my embedded.
I sent `echo '{ "embedders": { "default": { "source": "userProvided", "dimensions": 2}}}' | mieli settings`
And got the following error:
```
`.embedders.default`: Field `model` unavailable for source `userProvided` (only available for sources: `huggingFace`, `openAi`, `ollama`). Available fields: `source`, `dimensions`, `distribution`
```

Even though I never specified the `model` field.

**To Reproduce**
1. `echo '{ "embedders": { "default": {}}}' | mieli settings` -- Here meilisearch specifies a bunch of settings I didn't asks for
2. [NOT REQUIRED] `echo '{ "embedders": { "default": { "source": "userProvided"}}}' | mieli settings` -- Then I sent this request which gave me a perfect error message, nothing to change 👌 
3. `echo '{ "embedders": { "default": { "source": "userProvided", "dimensions": 2}}}' | mieli settings` -- Then I finally wrote the configuration I wanted

**Expected behavior**
I can think of two behavior:
- Meilisearch keeps track of which fields I’ve set. In this case, it would know that I never set the `model` field (i.e., keep a `None` in place of a default value). That would mean Meilisearch only returns this error message when I’ve effectively tried to set a `model` in the first call.
- Meilisearch reset all the forbidden fields when I change the `source`. Not a fan, personally

**Screenshots**
<details>
  <summary>Click me</summary>

![kefir](https://github.com/meilisearch/meilisearch/assets/7032172/545682f3-cbed-457e-a263-e6f3dc96c5bc)

</details>

**Meilisearch version:**
v1.9.0-rc2

**Comment by dureuill** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/4649
