### ISSUE TITLE
Valid primary key is refused

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4696]
**Describe the bug**
When sending a document with a valid primary key I get a message saying my primary key is invalid.

**To Reproduce**
1. `echo '{ "id": 14630868576586246730, "name": "tamo" }' | mieli d a`
2. Document identifier `14630868576586246730` is invalid. A document identifier can be of type integer or string, only composed of alphanumeric characters (a-z A-Z 0-9), hyphens (-) and underscores (_).

**Expected behavior**
It works or returns a better error message

**Comment by dureuill** [comment]
Hello thanks for reporting,

We should probably amend the error message to include the range of supported integers, which is the `i64` range according to the code.

Not sure about the priority of this bug.

**Comment by irevoire** [comment]
Since there is a workaround and it's old, I would say it's the least priority possible.

> We should probably amend the error message to include the range of supported integers, which is the i64 range according to the code.

Can't we also convert the PK to a string if it doesn't fit in an `i64` to hide our internal optimization from the end user?
