### ISSUE TITLE
Bad http status and error message on wrong payload

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4698]
**Describe the bug**
When sending badly formatted payload to meilisearch it returns a « 500 internal error » instead of a user error.
The error message is also quite ugly.

**To Reproduce**
1.`echo "kefir" | http PUT :7700/indexes/12/documents "Content-Type: application/json" "Content-Encoding: gzip"`
2. 
```
HTTP/1.1 500 Internal Server Error
content-encoding: gzip
content-type: application/json
date: Thu, 13 Jun 2024 14:31:37 GMT
transfer-encoding: chunked
vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
vary: accept-encoding

{
    "code": "internal",
    "link": "https://docs.meilisearch.com/errors#internal",
    "message": "payload reached EOF before completing: Some(Custom { kind: Other, error: DecompressError(General { msg: None }) })",
    "type": "internal"
}
```

**Comment by Karribalu** [comment]
Hey @irevoire,

I opened PR #4716 for this fix, but I don't see my changes affecting any tests. However, I am seeing some random test failures. Can you please guide me on whether my changes are related to any other tests?

Thank you!
