### ISSUE TITLE
Item results contains Id and Filter

### ISSUE THREAD

**Issue by h-morales** [meilisearch/meilisearch#4699]
![image](https://github.com/meilisearch/meilisearch/assets/153176/62f1cff1-ba74-4643-92f2-01769bddb6db)

Why is there an id and filter to results array? how can I remove that?

**Comment by ManyTheFish** [comment]
Hello @h-morales,
Which request are you doing? Are you using an SDK to make the query?

Sorry for the delay.

**Comment by h-morales** [comment]
im using Postman and reqbin curl

**Comment by ManyTheFish** [comment]
Ok, but, what is exactly the request? for example, what is the CURL request?
This will help me to reproduce your bug.
