### ISSUE TITLE
Request my personally deployed embedding service via post

### ISSUE THREAD

**Issue by ZimaBlueee** [meilisearch/meilisearch#4720]
**Describe the bug**
![46fb6312dc7cffe0ed7a96794caf8f5](https://github.com/meilisearch/meilisearch/assets/53747502/15010f2a-8de0-4e68-8ea0-584b08fd37c2)

Is the embedding service requested by get? My service is post, error 405 is requested according to the document, may I ask how to change to post to request my embedding service?

**To Reproduce**
1. use Xinference to deploy embedding serveice
2. request meili
3. xinference error 405 is reported

**Expected behavior**
Compatible post request

**Screenshots**
![图片](https://github.com/meilisearch/meilisearch/assets/53747502/199b4fa6-d2e0-4e89-ba77-16e0991a9d9f)

**Meilisearch version:**
v1.8.2

**Comment by irevoire** [comment]
Hey @ZimaBlueee, thanks for your feedback!
Since this is more a feature request than a bug, could you please send us a message on the experimental feature discussion? https://github.com/orgs/meilisearch/discussions/677

**Comment by ZimaBlueee** [comment]
I made a mistake. Thank you very much for your answer
