### ISSUE TITLE
Reset value of searchable and displayed attributes

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#473]
In the 0.9.0 the default values of `searchableAttributes` and `displayedAttributes` are all the different fields found in all the documents.

On delete, both settings are set to null, which means there isn't any searchable or displayed attribute left.
Since on settings update, you add a list of fields on which to search or on which to display, you should be able to reset the value of those settings without having to find every field present in your dataset.

My suggestion is to use the same system as the ranking rules.

By default it has all the distinct fields found in the documents. On **update** the value is changed to whatever list of fields you send, and on **delete** it resets to the default value (all fields).
If a user would want to have no displayed field or no searchable field (which is not recommended in any use case) he would only need to send an empty array on update.

**Comment by qdequele** [comment]
I think the issue can be solved by replacing `searchableAttributes` and `displayedAttributes` by `restrictSearchableAttributes` and `restrictDisplayedAttributes`. If we mention that these settings only restrict fields it will mean that if the fields are null, all fields will be searchable and displayed.

**Comment by bidoubiwa** [comment]
Yes, this is also a solution that suits me!

**Comment by qdequele** [comment]
Finally, the names of the fields are kept, but if the `searchableAttributes ` or `displayedAttributes ` are set to null or reset the value will become the default value, so, all the fields already view in documents.
