### ISSUE TITLE
Make the `embeddings` parameter optional when specifying your embedder

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4741]
When sending user-provided vectors, you can either send your embeddings inlined like that;
```json
{"id": 0, "name": "kefir", "_vectors": { "manual": [0, 1, 2] }
```

Or, you can use an object which lets you specify if meilisearch should `regenerate` your embedding the next time your document is modified:
```json
{"id": 0, "name": "kefir", "_vectors": { "manual": { "embeddings": [1, 2, 3], "regenerate": true }
```

The `embeddings` field used not to be mandatory, and the error messages weren't clear when forgetting `regenerate`

**Comment by curquiza** [comment]
Closed by #4740
