### ISSUE TITLE
Improve usage of the rest embedder

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4756]
Here's a list of stuff I found hard to understand and use while trying to make the rest embedder work:
- [ ] [REST API parameter names and behavior are unclear](https://github.com/meilisearch/documentation/pull/2824#issuecomment-2124073720)
- [ ] [Bad error message or bad default value when we don't specify the `query` parameter](https://github.com/meilisearch/meilisearch/blob/85d8455c11bfa0a5c2ba70d15554c974b003d666/meilisearch/tests/vector/rest.rs#L105-L140)
- [ ] [Bad error message when both `pathToEmbeddings` and `embeddingObject` are missing](https://github.com/meilisearch/meilisearch/blob/2141cb3b69f52ca6fcf18d0b89df1d8601a22f85/meilisearch/tests/vector/rest.rs#L142-L178)
- [ ] [Unexpected error when we don't specify both `pathToEmbeddings` and `embeddingObject` (only once should be required)](https://github.com/meilisearch/meilisearch/blob/2141cb3b69f52ca6fcf18d0b89df1d8601a22f85/meilisearch/tests/vector/rest.rs#L180-L260)
- [ ] [Should not panic when the dimensions specified do not work with the model](https://github.com/meilisearch/meilisearch/blob/2141cb3b69f52ca6fcf18d0b89df1d8601a22f85/meilisearch/tests/vector/rest.rs#L262-L299)
- [ ] [Be more flexible on the type of data that is accepted](https://github.com/meilisearch/meilisearch/issues/4757#issuecomment-2201948531)
  - [ ] Always accept arrays of embeddings even if `inputType` is set to `text`
  - [ ] Accept arrays of result at the root level and texts/array of text at the root level.

**Comment by Karribalu** [comment]
Good Day @irevoire,
I found the culprit for internal server error when dimensions is missed and also bad error message when either query field is missed or bad json payload is passed.
I want to understand if the query field is mandatory?
It would be helpful if you can point me to some API Documentation for this.

**Comment by dureuill** [comment]
Hello @Karribalu, thanks for looking into this :heart:

I plan on discussing the REST embedder API at a more global scale, which could significantly change the API. As a result, I would not suggest working on the items of this task at the moment.

We'll keep this task updated.

**Comment by Karribalu** [comment]
Thanks, for letting me know @dureuill !
