### ISSUE TITLE
Option to disable ANSI sequences in log

### ISSUE THREAD

**Issue by szepeviktor** [meilisearch/meilisearch#4810]
**Describe the bug**
Currently a log line (stderr output) contains ANSI sequences.
```
?[2m2024-07-18T09:36:56.319222Z?[0m ?[32m INFO?[0m ?[2mactix_server::builder?[0m?[2m:?[0m starting 2 workers
```

**Expected behavior**
I'd like to disable syntax highlighting because I redirect the log into a file.

**Comment by curquiza** [comment]
Hello @szepeviktor 

Thanks for using Meilisearch and the suggestion.

We don't handle feature request in this repository

<img width="1305" alt="Capture d’écran 2024-08-02 à 16 56 40" src="https://github.com/user-attachments/assets/c275a17e-3cb6-40d3-a324-40b5bf5f2fe5">

A discussion has already been started in the dedicated place: https://github.com/orgs/meilisearch/discussions/764

Have a nice day
