### ISSUE TITLE
"Sorting" link in README.md leads to 404

### ISSUE THREAD

**Issue by gassiss** [meilisearch/meilisearch#4813]
**Describe the bug**

[This link](https://github.com/meilisearch/meilisearch/blob/main/README.md?plain=1#L50) in the README is not working. I'd update it with the right one myself, but I don't know what that would be. Sorry!

**Comment by curquiza** [comment]
Hello @gassiss 
I contacted the doc team because it looks more like an issue on the docs side. This link is supposed to exist

**Comment by curquiza** [comment]
I checked with documentation team, and now it's solved, the redirection is correctly done

closing the issue
