### ISSUE TITLE
Meilisearch v1.10.0 language settings

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch#4841]
**Describe the bug**
In v1.10.0 I am able to update the language settings using the main settings route, but I get 404s when I try to update the language settings alone. I'm not sure if I just can't find the correct address or if it is not possible to set language individually like with the other settings?

For example with proximity precision I can `get`, `put`, and `delete` to http://127.0.0.1:7700/indexes/movies/settings/proximity-precision. I tried this with multiple options for language and get a 404 with all of them: `localized-attributes`, `localization`, `language`, `language-settings`.

**To Reproduce**

**Expected behavior**
To be able to set the language settings individually like other settings.

**Screenshots**

**Meilisearch version:**
v1.10.0-rc.0

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Hello @sanders41 
Thank you for the report, we indeed already saw it, and we merged a PR as explained here: https://github.com/meilisearch/meilisearch/pull/4842#issuecomment-2258897455

I should have opened an issue for you to avoid to open this one 🙈 

Closed by https://github.com/meilisearch/meilisearch/pull/4836. Will be released in rc1 this week 👍
