### ISSUE TITLE
How to do high availability

### ISSUE THREAD

**Issue by wangsj1018** [meilisearch/meilisearch#4847]
May I ask how to achieve high availability of the Meilisearch service? Do I need to implement routing myself?

**Comment by curquiza** [comment]
Hello @wangsj1018 
So far we don't provide HA for Meilisearch out of the box. You have to implement it yourself

Here is some material about it:
- https://github.com/meilisearch/meilisearch/issues/3494
- https://github.com/orgs/meilisearch/discussions/617

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
