### ISSUE TITLE
Edit document by function do not delete all the selected documents

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4849]
**Describe the bug**
While deleting documents with the experimental `POST /indexes/:index_uid/documents/edit` route some documents are not deleted.

**To Reproduce**
1. `for i in {0..100}; do echo "{ \"id\": $i }" | mieli d a --async; done`
2. `echo '{ "function": "if doc.id % 3 != 0 { doc = (); } else { doc.title = \"kefir\"; }"}' | http :7700/indexes/mieli/documents/edit`
3. `mieli search`

You should see something looking like that:
```json
{
  "hits": [
    {
      "id": 0,
      "title": "kefir"
    },
    {
      "id": 1
    },
    {
      "id": 3,
      "title": "kefir"
    },
    {
      "id": 4
    },
    {
      "id": 5
    },
    {
      "id": 6,
      "title": "kefir"
    },
    ...
}
```

All the documents without a `title` were supposed to be deleted, but that's not the case.

**Comment by curquiza** [comment]
Closed by #4853. Will be in rc3
