### ISSUE TITLE
The websocket write function was added

### ISSUE THREAD

**Issue by a496046961** [meilisearch/meilisearch#4855]
We have redesigned our client's connection pool. Since our business involves more data writes and fewer queries, we want to introduce WebSocket functionality to avoid frequent connections. Additionally, MeiliSearch only supports HTTP connections, which are not ideal for handling performance. Offering multiple types of connectors would be more convenient, such as pubsub connectors, Redis message queue connectors, RocketMQ connectors, MySQL connectors, and custom connectors. This approach would greatly facilitate data processing.

**Comment by curquiza** [comment]
Hello @a496046961 

Thanks for using Meilisearch

We don't handle feature request in this repository

<img width="1305" alt="Capture d’écran 2024-08-02 à 16 56 40" src="https://github.com/user-attachments/assets/c275a17e-3cb6-40d3-a324-40b5bf5f2fe5">


I'd recommend you start a discussion about it on the [product repo](https://github.com/meilisearch/product/discussions/), detailing your use case and any other information that may be useful. This information would be very beneficial to our product team, and I assure you that your suggestion will be evaluated.

Have a nice day
