### ISSUE TITLE
Are there any limitations to nested json?

### ISSUE THREAD

**Issue by bjarneo** [meilisearch/MeiliSearch#486]
Couldn't find anything at the documentation regarding this. Might be something I haven't seen.

It seems that it does not support deep nesting, or arrays? I might be wrong, and this might be something MeiliSearch never will implement. I am just curious :)

**Comment by Kerollmops** [comment]
Hey @bjarneo,

Nested objects or arrays are supported by MeiliSearch but not in a clearly specified way, for example, highlights are not handled correctly for the moment, I need to work more on that.

Nested objects and arrays are currently flattened and indexed like basic sentences, it means that each objects keys will be indexed like being part of the content. Each keys and values appears like separate sentences.

I will keep your issue open this way other users can find information about that.

Thank you for this issue.

**Comment by Shriram-Balaji** [comment]
@Kerollmops is the Highlight issue for nested JSON fixed? I'm currently having to `JSON.stringify` the objects in order to show them up.

**Comment by Kerollmops** [comment]
Hey @Shriram-Balaji,

Unfortunately this hasn't been improved yet, maybe in the near future.

**Comment by Shriram-Balaji** [comment]
@Kerollmops okay, is there any potential downside to saving the object after stringification other than the 1000 word limit?

**Comment by Kerollmops** [comment]
Apart from the fact that you will have to `JSON.parse` it on your side.
