### ISSUE TITLE
Filter doesn't return valid documents

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#4860]
**Describe the bug**
"Complementary" issue to #4848 😢 

Some documents are not returned, despite having a value that the filter should react to.

**To Reproduce**
1. Create an index with primary key `id`
2. Add sortable attribute `foo`
3. Add a document `{ "id": 0, "foo": ["bar", "Bar"]}'
4. Check that `{"filter": "foo = bar"}` correctly returns the document.
5. Update the document `{"id": 0, "foo": "bar"}'
6. `{"filter": "foo = bar"}` no longer returns the document

**Expected behavior**
`{"filter": "foo = bar"}` still returns the document

**Screenshots**

**Meilisearch version:**
Tested in Meilisearch v1.9 and Meilisearch v1.10, but probably affects a larger range: since the differential indexing has been added to the time of writing this issue

**Additional context**
Discovered while investigating #4848.

The technical cause, which could also be an element of #4848, is that in `insert_strings_diff,` pairs of `(normalized_value, value)` are compared between the previous value of the field in the document and the latest value of the field in the document.

As the entire pair is compared lexicographically, but ultimately only one deladd obkv can be written per normalized value, what happens here is that we erroneously record that normalized("Bar")=normalized("bar") needs removal (despite there still being "bar" in the field).

Btw this also affects the facet search since only only exact value is kept among all normalized values, and if one value is added while a different value that normalize to the same thing is removed, it can be that we erroneously remove the facet value from the candidate search result.

**Comment by curquiza** [comment]
Fixed by #4864
