### ISSUE TITLE
A serious problem has been discovered

### ISSUE THREAD

**Issue by xzlinux** [meilisearch/meilisearch#4874]
A serious problem, I found that when using Chinese search, some words can not be searched, for example, I search "待处理" can be found, but if I search "处理" there is no
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/ed7b57de-c735-4e82-a21b-65672d26d2d5">
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/bb35af6b-83d3-40ba-93d3-0257974ccd05">

**Comment by a496046961** [comment]
我都存储英文和数字的情况，没有出现这个问题

**Comment by xzlinux** [comment]
> 我都存储英文和数字的情况，没有出现这个问题

问题出在jieba的分词上面

**Comment by skydig** [comment]
same issue， is there solution?
I search "工程” for “在建工程”， search failed

**Comment by ManyTheFish** [comment]
Hello, it's maybe because Meilisearch doesn't support suffix search.
It seems related to the following issue where I suggest several improvements:
https://github.com/meilisearch/meilisearch/issues/4814


What do you think?

**Comment by xzlinux** [comment]
> Hello, it's maybe because Meilisearch doesn't support suffix search. It seems related to the following issue where I suggest several improvements: #4814
> 
> What do you think?
I verified this question with jieba, it is a jieba problem, may not be very friendly to Chinese support.

**Comment by ManyTheFish** [comment]
Yes, I understand,
however, this specific comment may be helpful:
https://github.com/meilisearch/meilisearch/issues/4814#issuecomment-2247070959

**Comment by skydig** [comment]
#4814 dic solution still has problems,
I have phrase "笔记本电脑“
I create ”笔记本“ and ”电脑“ words
then, I perform phrase search
search ”笔记本“ return "笔记本电脑“
search ”电脑“  return "笔记本电脑“
search "笔记本电脑“ return **NOTHING**
I put "笔记本电脑“ in dic, result is same as above.

**Comment by ManyTheFish** [comment]
@skydig,
please don't put long words in the dictionary; I suggest adding common unique characters instead.

**Comment by ManyTheFish** [comment]
Closing the issue in favor of the official Language discussion,
Chinese segmentation is not good enough for Meilisearch for now.
