### ISSUE TITLE
Add a websocket function

### ISSUE THREAD

**Issue by a496046961** [meilisearch/meilisearch#4875]
You also know that http on the network overhead is relatively large, you can add a websocket function, this function knows to add document data, does not support the query function. For example: mysql pipeline, redis pipeline, kafka pipeline. Each operation must create an http link, because many scenarios are inserting data, querying data, wensocket can do these functions, and there is a smaller overhead of system resources.

**Comment by curquiza** [comment]
Hello @a496046961 

Thanks for using Meilisearch

We don't handle feature request in this repository

<img width="1305" alt="Capture d’écran 2024-08-02 à 16 56 40" src="https://github.com/user-attachments/assets/c275a17e-3cb6-40d3-a324-40b5bf5f2fe5">


I'd recommend you start a discussion about it on the [product repo](https://github.com/meilisearch/product/discussions/), detailing your use case and any other information that may be useful. This information would be very beneficial to our product team, and I assure you that your suggestion will be evaluated.

Have a nice day
