### ISSUE TITLE
Random crashes (exit code 143)

### ISSUE THREAD

**Issue by thecodeassassin** [meilisearch/meilisearch#4878]
**Describe the bug**

We are running Meilisearch 1.9.0 on Kubernetes. For some reason we experience very random crashes. 

We unfortunately cannot seem to reproduce the error with load testing.

The uptick wasn't that big, but the instance did crash with Exit code 143 at that time. What happens is that the container becomes unresponsive and the health checks start failing.

![image](https://github.com/user-attachments/assets/7b3577fb-691d-4d70-8ffc-08b30930de72)

Logs at the time of the incident:

https://gist.github.com/thecodeassassin/55192955fd537ffe73a0adf09b1e018a

The crashes happen 2-3 times per day max.

I cannot make it fully crash with k6 so I am not sure if it's purely load related.

This problem only started to appear after we upgraded from v1.0.0 to v1.9.0. We cannot downgrade anymore to V1.0.0 since the dump files are no longer compatible.

**To Reproduce**
At this point I cannot reproduce the issue without further guidance. 

**Expected behavior**
It should not crash.

**Meilisearch version:**
v1.9.0

**Additional context**
Ubuntu 22.04 nodes, vanilla kubernetes using dedicated servers (same environment as before the upgrade to v1.9.0)

**Comment by ManyTheFish** [comment]
When using Meilisearch on Kubernetes, the instance will sometimes take the host machine RAM as the reference and not the limits set by the container. I suggest using the [`MEILI_MAX_INDEXING_MEMORY` environment variable](https://www.meilisearch.com/docs/learn/self_hosted/configure_meilisearch_at_launch#max-indexing-memory) and set it between half and 2/3 of the limit you set for your container.

**Comment by thecodeassassin** [comment]
> When using Meilisearch on Kubernetes, the instance will sometimes take the host machine RAM as the reference and not the limits set by the container. I suggest using the [`MEILI_MAX_INDEXING_MEMORY` environment variable](https://www.meilisearch.com/docs/learn/self_hosted/configure_meilisearch_at_launch#max-indexing-memory) and set it between half and 2/3 of the limit you set for your container.
> 
> See you!

I have set this environment variable now and will monitor if it stops crashing:

apiVersion: v1
data:
  MEILI_ENV: production
  MEILI_MAX_INDEXING_MEMORY: 5Gb
  MEILI_NO_ANALYTICS: "true"
  
Although I would expect an OOMKILLED (137) to be the exit code instead of 143. How come this wasn't happening on 1.0?

**Comment by thecodeassassin** [comment]
@ManyTheFish that didn't solve the problem, it still crashed today.

Now it did die with code 137:

```
    Last State:     Terminated                                                                                                                                                                                                                                                                                           │
│       Reason:       Error                                                                                                                                                                                                                                                                                                │
│       Exit Code:    137                                                                                                                                                                                                                                                                                                  │
│       Started:      Mon, 19 Aug 2024 11:50:20 +0200                                                                                                                                                                                                                                                                      │
│       Finished:     Mon, 19 Aug 2024 18:06:01 +0200                                                                                                                                                                                                                                                                      │
│     Ready:          True                                                                                                                                                                                                                                                                                                 │
│     Restart Count:  1
   Limits:                                                                                                                                              │
│       memory:  8Gi                                                                                                                                       │
│     Requests:                                                                                                                                            │
│       cpu:      100m                                                                                                                                     │
│       memory:   1Gi
```

the configmap:

```
apiVersion: v1
data:
  MEILI_ENV: production
  MEILI_MAX_INDEXING_MEMORY: 5Gb
  MEILI_NO_ANALYTICS: "true"
  ```

But it never reached the pod's memory limit. So it's probably hitting the indexer memory limit or some other memory ceiling and exits with 137. 

As you can see in the screenshot below, the pod's memory limit was never reached:
![image](https://github.com/user-attachments/assets/377751d1-32db-4656-b316-1f941baba4d6)

**Comment by ManyTheFish** [comment]
Hello @thecodeassassin,
I am stunned by this error. The only way Meilisearch crashes without returning an error is by being killed. Most of the time, it is because of the Memory, but as you are showing it, there is plenty of RAM, and the limits are never reached.
However, I am pretty sure that exit 137 is a "virtualization" exit and is not triggered by the OS; it seems to be the virtualization system that kills the container for an unknown reason.
By [searching on the web](https://stackoverflow.com/questions/59729917/kubernetes-pods-terminated-exit-code-137), I found that Meilisearch may not have passed the liveness probe.
Can you check your health check setup?

**Comment by thecodeassassin** [comment]
> Hello @thecodeassassin, I am stunned by this error. The only way Meilisearch crashes without returning an error is by being killed. Most of the time, it is because of the Memory, but as you are showing it, there is plenty of RAM, and the limits are never reached. However, I am pretty sure that exit 137 is a "virtualization" exit and is not triggered by the OS; it seems to be the virtualization system that kills the container for an unknown reason. By [searching on the web](https://stackoverflow.com/questions/59729917/kubernetes-pods-terminated-exit-code-137), I found that Meilisearch may not have passed the liveness probe. Can you check your health check setup?

@ManyTheFish 

We are using the meilisearch helm chart:
https://github.com/meilisearch/meilisearch-kubernetes

So it seems to not be passing the "/health" endpoint. This is maintained by meilisearch not by us so i'm just going by what I can find in the repo.

```
  livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.livenessProbe.InitialDelaySeconds }}
```

**Comment by ManyTheFish** [comment]
Hello @thecodeassassin,
What are the `periodSeconds` and the `failureThreashold` values? I suggest putting both of them to 5.

Then, the issue could come from other pods on the same node, which could cause memory pressure on that node. You set a memory request of 1G for a limit of 8G: if there are other pods running with a similar configuration, there could be an overcommitting. Which could end up with a memory competition. Could it be the case on your side?

**Comment by thecodeassassin** [comment]
> Hello @thecodeassassin, What are the `periodSeconds` and the `failureThreashold` values? I suggest putting both of them to 5.
> 
> Then, the issue could come from other pods on the same node, which could cause memory pressure on that node. You set a memory request of 1G for a limit of 8G: if there are other pods running with a similar configuration, there could be an overcommitting. Which could end up with a memory competition. Could it be the case on your side?

Hello,

These are set to the default values:

     Liveness:   http-get http://:http/health delay=0s timeout=1s period=10s #success=1 #failure=3                                                                                       │
│     Readiness:  http-get http://:http/health delay=0s timeout=1s period=10s #success=1 #failure=3


This will not solve the issue because the Meilisearch instance becomes unresponsive so it doesn't matter. It will still ultimately fail, it will just be offline for longer since it will take more time for them to be restarted. What would be interesting to find out is why does it become unresponsive?

The nodes have 128GB of memory and 26GB is in use (max). So that's definitely not an issue.

**Comment by dureuill** [comment]
Hello,

would setting the env var `MEILI_EXPERIMENTAL_SEARCH_QUEUE_SIZE=0` mitigate the issue and reduce the number of crashes?

**Comment by thecodeassassin** [comment]
> Hello,
> 
> would setting the env var `MEILI_EXPERIMENTAL_SEARCH_QUEUE_SIZE=0` mitigate the issue and reduce the number of crashes?

We are already running it with this setting:

```
spec:
  containers:
  - command:
    - meilisearch
    - --experimental-search-queue-size
    - "0"
    envFrom:
    - configMapRef:
        name: meilisearch-environment
    - secretRef:
        name: meilisearch-master-key
    image: getmeili/meilisearch:v1.9.0
    ```

**Comment by dureuill** [comment]
alright, thank you. 

are you using the vector search?

**Comment by thecodeassassin** [comment]
> alright, thank you. 
> 
> 
> 
> are you using the vector search?

Hi,

No we are not using vector search.

**Comment by thecodeassassin** [comment]
One thing worth adding to this is that the amount of restarts do decrease if the number of searches decrease. We have implemented a caching proxy in front of Meilisearch and the restarts are much rarer now.

**Comment by dureuill** [comment]
Hello, we'll be releasing a v1.10.1 with changes in this area, it might improve the situation.

**Comment by skydig** [comment]
actually, 1.10.1 is random crash too（memory corrupt). I have tested, so I rollback to version 1.9

**Comment by ManyTheFish** [comment]
Hello @skydig,
what do you mean by "Memory corrupt", do you have the same exit code than thecodeassassin?

**Comment by skydig** [comment]
@ManyTheFish 
Sir, operation system I use is windows, I mean, the OS pops one window to indicate the meilisearch process has memory access violation randomly,  it's the meilisearch process, not application process.  I  just perform doc add/delete/modify.

**Comment by dureuill** [comment]
This doesn't seem related to this issue then.

This issue is about crashes in a docker environment due to the `/health` route that stopped responding, not a direct Meilisearch crash.

If you have a direct Meilisearch crash, can you please open a new issue detailing the steps you take to reproduce the crash and your environment (OS, Meilisearch version, etc)

**Comment by curquiza** [comment]
@thecodeassassin did v1.10.1 solve your problem?

**Comment by dureuill** [comment]
Closing the issue following the lack of activity; feel free to reopen with new elements!
