### ISSUE TITLE
Meilisearch silently crashes (presumably hitting memory limit) on Windows 11

### ISSUE THREAD

**Issue by Yuubari** [meilisearch/meilisearch#4910]
**Describe the bug**
The Meilisearch Windows amd64 binary seems to constantly request more memory from the OS and crashes after 4 GB is allocated. No issues with the Linux binary with the exact same usage scenario; it runs without issues in a VM with 2 GB RAM and 1 GB swap, seemingly without paging.

When limiting to insertion of just 100 documents per run with delays of 5-10 minutes in-between, memory usage steadily grows with each new batch in the same way as when running insertions immediately one after another.

A typical document consists of a text string (usually below 100 characters), a language identifier, and a resource ID, altogether well below 500 bytes (so ≈50 kilobytes per chunk).

**To Reproduce**
1. Start the Meilisearch service
2. Attempt to insert several batches of 100 documents, waiting for each task's completion (I am using meilisearch-rust)
3. The API gives an error during `wait_for_completion()`
4. About 5-10 seconds later the Meilisearch server silently terminates. There are no messages related to the crash even with `TRACE` logging level — everything looks normal.

The code in question:
```rust
    for docs in store.chunks(100) {
        eprintln!("Inserting {} entries…", docs.len());
        let Ok(task) = dictionary.add_or_update(docs, Some("tid")).await else {
            eprintln!("Cannot queue documents.");
            return ExitCode::FAILURE;
        };

        let Ok(task) = task.wait_for_completion(&client, None, None).await else {
            eprintln!("Wait for completion failed.");
            return ExitCode::FAILURE;
        };

        if task.is_failure() {
            eprintln!("Insertion failed: {:?}.", task.unwrap_failure());
            return ExitCode::FAILURE;
        }
    }
```
runs without issues when using Meilisearch Linux binary.

**Expected behavior**
Insertion should finish and Meilisearch server process should not terminate silently.

**Screenshots**
N/A

**Meilisearch version:**
1.10.0 (this behaviour was present in 1.8.x as well)

**Additional context**
OS: Windows 11 Enterprise 23H2; the system has 32 GB RAM.

**Comment by ManyTheFish** [comment]
Hello @Yuubari,

By default, Meilisearch is allowed to allocate up to 2/3 of the available memory.
Before investigating deeper, could you try [to reduce the max indexing memory](https://www.meilisearch.com/docs/learn/self_hosted/configure_meilisearch_at_launch#max-indexing-memory) using `--max-indexing-memory` or the `MEILI_MAX_INDEXING_MEMORY` environment variable, setting it to something like `2GB`.
This should help in reducing the crashes, if you continue encountering this issue, let me know.

**Comment by Yuubari** [comment]
Thank you, that seems to have done the trick. I wonder why was it having issues with the default settings…
