### ISSUE TITLE
Serious errors sometimes logged at "INFO" level

### ISSUE THREAD

**Issue by dpkirchner** [meilisearch/meilisearch#4916]
When a batch task is requested and the disk is full, a log message is written, but it's at "INFO" level so is easily missed if someone's trying to use logs to trigger alerts.

The code in this specific case is: https://github.com/meilisearch/meilisearch/blob/db0cf3b2ed0ca6cf6549510bf373681e83b775dd/index-scheduler/src/lib.rs#L1266 . There may be other places in the code where this can happen.

The error that was logged for me: `{"timestamp":"2024-09-07T18:06:37.387047Z","level":"INFO","fields":{"message":"Batch failed No space left on device (os error 28)"},"target":"index_scheduler"}`

**Comment by dureuill** [comment]
Hello :wave:

it indeed sounds reasonable to upgrade this to warning or even error level.

Sorry for the belated answer.

**Comment by irevoire** [comment]
Fixed in #4955
