### ISSUE TITLE
Ai embedders not processing the "documentTemplate" properly 

### ISSUE THREAD

**Issue by zeyaddiaa** [meilisearch/meilisearch#4918]
**Screenshots**
Screenshot 1
![image](https://github.com/user-attachments/assets/8012cd03-c8ef-40e1-b663-0711b88d4437)

Screenshot 2
![image](https://github.com/user-attachments/assets/2b57d11d-7cb5-4d53-b27a-5ff5e88e5670)

**Describe the bug**
The documentTemplate is not processing "doc.fieldName" properly, when I try to access a field in my document it gives me this error "user error: missing field in document: liquid: Unknown index", I tried to capitalize the first letter of each field but the error persists

**Comment by irevoire** [comment]
Hey @zeyaddiaa,

The error message is saying that some on your documents do not have the `name` or `Name` field.

Could you share one of the document of this index with us?

**Comment by zeyaddiaa** [comment]
Hey @irevoire,

I checked my documents, all of them had the same fields but some with "name" and the others with "Name". So I added an if condition to solve this problem and now it is working. 

Here is the if condition I used: 
_{% if doc.name %}{{doc.name}}{% elsif doc.Name %}{{doc.Name}}{% endif %}_

This solved the issue.

Thanks for your reply.
