### ISSUE TITLE
No id returned

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#492]
I create an index and I add documents.

When:
- searching
- getting documents (multiple or not)
the API does not display the ids of the documents.

### Steps
- [x] Fix in the code
- [x] Add tests to check this issue

### Version
On the `master` branch, [on this commit](https://github.com/meilisearch/MeiliSearch/commit/72450c765d77222b18cef2bf5d149d1037603121). Should be fixed for the `v0.9.0`.

**Comment by qdequele** [comment]
https://github.com/meilisearch/MeiliSearch/blob/2b780ab2c5f2da2eb5e9475ff789da5cba11c359/meilisearch-core/src/update/settings_update.rs#L37-L42

At this time we should also add the identifier as displayed and indexed.
