### ISSUE TITLE
error: Assertion 'pglast <= env->me_pglast' failed in mdb_freelist_save()

### ISSUE THREAD

**Issue by perryzhangateosi** [meilisearch/meilisearch#4931]
**Description**
we met a problem, after using meilisearch strapi plugin two weeks with everything working fine;

suddenly whenever we add a new data row in meilisearch' watching datatable,  meilisearch logs show error below:
/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/lmdb-master-sys-0.1.0/lmdb/libraries/:3549: Assertion 'pglast <= env->me_pglast' failed in mdb_freelist_save()

then meilisearch instance reboot itself, so we can't add new data row anymore.

what might be the problem cause this error, and how to fix it. Any suggestions would be appreciated.

**Expected behavior**
meilisearch instance index the new added data row and provide search resutls.

**Current behavior**
meilisearch instance reboot itself,  any added new data row won't be indexed.

**Screenshots or Logs**
 /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/lmdb-master-sys-0.1.0/lmdb/libraries/:3549: Assertion 'pglast <= env->me_pglast' failed in mdb_freelist_save()

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: [1.7.6]
- strapi-plugin-meilisearch version: 0.10.0 ]
- Browser: [e.g. Chrome version 90.0]
- Strapi version: [v4.19.1]

**Comment by dureuill** [comment]
Closing, answered https://github.com/meilisearch/meilisearch/discussions/4925#discussioncomment-10622586

Feel free to reopen as necessary

**Comment by perryzhangateosi** [comment]
> Hi @perryzhangateosi I'm going to move this issue to the right repo as I think this is not related to strapi.
> 
> But I need to ask you to provide a better description about how you encountered this error, what is your index configuration your use case and anything you may think it could help us understand your issue.
> 
> @meilisearch/engine-team feel free to close this if you don't think is an issue 😗

it's  possibily azure‘s problem,thanks @brunoocasali
