### ISSUE TITLE
1.9.1 -> 1.10.1 regression: "index_scheduler: internal: decoding failed."

### ISSUE THREAD

**Issue by bpolaszek** [meilisearch/meilisearch#4934]
Hello there,

I recently upgraded my 1.9.1 instance on Ubuntu 24.04 to 1.10.1, and all of a sudden the instance started to complain that something wrong occurred.

What I exactly did:
- Ensured nothing was about to be written to the instance
- Copied `data` dir to a safe place
- Created a dump through the REST API
- Stopped the instance
- Upgraded
- Started the instance manually by importing the dump
- Once done, stopped the temporary instance, then asked `systemd` to launch 1.10.1.
So far so good. REST API was OK, search was OK and so on.

Then I ran my usual background task to import fresh data, but after a few minutes, the server started to return 500 errors, I couldn't even list indexes.

Here's what a `service meilisearch status` said:

```
● meilisearch.service - Meilisearch
     Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; preset: enabled)
     Active: active (running) since Wed 2024-09-11 05:52:25 UTC; 4s ago
   Main PID: 608372 (meilisearch)
      Tasks: 9 (limit: 2320)
     Memory: 6.4M (peak: 6.7M)
        CPU: 21ms
     CGroup: /system.slice/meilisearch.service
             └─608372 /usr/bin/meilisearch --config-file-path /etc/meilisearch.toml

Sep 11 05:52:26 meilisearch[608372]: 2024-09-11T05:52:26.164716Z ERROR index_scheduler: internal: decoding failed.
Sep 11 05:52:26 meilisearch[608372]: 2024-09-11T05:52:26.456139Z ERROR HTTP request{method=POST host="xxx.xxx.xxx.xxx>
Sep 11 05:52:26 meilisearch[608372]: 2024-09-11T05:52:26.456339Z  INFO HTTP request{method=POST host="xxx.xxx.xxx.xxx>
Sep 11 05:52:27 meilisearch[608372]: 2024-09-11T05:52:27.165206Z ERROR index_scheduler: internal: decoding failed.
Sep 11 05:52:28 meilisearch[608372]: 2024-09-11T05:52:28.165595Z ERROR index_scheduler: internal: decoding failed.
Sep 11 05:52:28 meilisearch[608372]: 2024-09-11T05:52:28.665288Z ERROR HTTP request{method=POST host="xxxxxxxx.xyz>
Sep 11 05:52:28 meilisearch[608372]: 2024-09-11T05:52:28.665864Z  INFO HTTP request{method=POST host="xxxxxxxx.xyz>
Sep 11 05:52:28 meilisearch[608372]: 2024-09-11T05:52:28.671386Z ERROR HTTP request{method=POST host="xxxxxxxx.xyz>
Sep 11 05:52:28 meilisearch[608372]: 2024-09-11T05:52:28.671538Z  INFO HTTP request{method=POST host="xxxxxxxx.xyz>
Sep 11 05:52:29 meilisearch[608372]: 2024-09-11T05:52:29.165880Z ERROR index_scheduler: internal: decoding failed.
```

I did the whole process a second time without having more luck, so I reverted to 1.9.1. I ran my ETL to import fresh data and everything worked as expected.

Unfortunately, this is sensitive data that I cannot share, so I could not help find a bug by providing a dataset. But is there some places I should look on my machine that could help find clues or more details about why the new instance crashed that way?

Thank you,
Ben

**Comment by Kerollmops** [comment]
Hello @bpolaszek 👋

> I did the whole process a second time without having more luck, so I reverted to 1.9.1. I ran my ETL to import fresh data and everything worked as expected.

I am sorry to hear that. So, at least you have a working version of Meilisearch and didn't lose any data.

> Unfortunately, this is sensitive data that I cannot share, so I could not help find a bug by providing a dataset. But is there some places I should look on my machine that could help find clues or more details about why the new instance crashed that way?

That's very unfortunate because it seems to be a runtime issue. It doesn't seem to come from the environment or the key-value store but straight from Meilisearch. I would like to know where you got Meilisearch. Have you compiled it by yourself? Used the official Docker image?

Have a nice day 🌞

**Comment by bpolaszek** [comment]
Hi @Kerollmops,

Thank you for taking some time to answer me. 

Looks like "past me" did dirty things such as snapshot importing routines, and "new me" just forgot about that 🙄 
Except a snapshot cannot be imported from a previous Meilisearch version. This led to Meilisearch crash and I didn't get context to figure out why.
I retried earlier yesterday and everything worked perfectly. 

Sorry for wasting your time 😓
