### ISSUE TITLE
Phrase search doesn't work with `attributesToSearchOn`

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4974]
**Describe the bug**
When doing a phrase search a a specific attribute using `attributesToSearchOn`, the search results contain documents that doesn't match the phrase. 

**To Reproduce**
[I've created a commit containing a test reproducing the bug](https://github.com/meilisearch/meilisearch/pull/4973/commits/e134d03a14bf5d8c5a85adaf46e3f992267ac88b):

https://github.com/meilisearch/meilisearch/blob/e134d03a14bf5d8c5a85adaf46e3f992267ac88b/meilisearch/tests/search/restrict_searchable.rs#L371-L416

**Comment by curquiza** [comment]
⚠️ Good first issue for someone who already know rust and a little bit the code base

A PR is already opened to guide you: https://github.com/meilisearch/meilisearch/pull/4973. You can take the commit or copy/paste the test in the PR
