### ISSUE TITLE
The stop words are ignored by Meili

### ISSUE THREAD

**Issue by tysonite** [meilisearch/meilisearch#4984]
It seems that Meili is ignoring the stop words I set. According to the [specification](https://specs.meilisearch.dev/specifications/text/0123-stop-words-setting-api.html#_3-functional-specification), stop words should be ignored in the search query during matching. However, it appears that Meili is either not handling this as expected, or I may have misunderstood the concept of stop words.

I use the following command to update the settings of the index (which contains about 2000 items):
```
curl -X PATCH "${SEARCH_SERVER_URL}/indexes/${INDEX_NAME}/settings/" -H  'Content-Type: application/json' -H "Authorization: Bearer ${SEARCH_SERVER_KEY}" --data-binary @${SETTINGS_FILE}
```

The content of ${SETTINGS_FILE} file is following:
```
{
  "rankingRules": [
    "words",
    "typo",
    "proximity",
    "attribute",
    "sort",
    "exactness",
    "released:desc",
    "rank:desc"
  ],
  "searchableAttributes": [
    "asset_name",
    "asset_id",
    "title",
    "description",
    "actors",
    "director",
    "program_type",
    "creation_date",
    "released",
    "year",
    "suggested_price",
    "genre",
    "series_name"
  ],
  "stopWords": [
    "the",
    "a",
    "an"
  ],
  "filterableAttributes": [
    "program_type",
    "season",
    "episode",
    "actors",
    "suggested_price",
    "rated",
    "language",
    "display_as_new",
    "display_as_last_chance",
    "year",
    "director"
  ],
  "sortableAttributes": [
    "title",
    "released"
  ],
  "typoTolerance": {
    "disableOnAttributes": [
      "asset_id",
      "genre"
    ]
  }
}
```

Example of JSON items for index:
```
    {
        "asset_name": "The Launch",
        "creation_date": "29 May 2020",
        "description": "Four-star general Mark Naird - leader of the newly created Space Force - is pressured to launch a satellite despite dire warnings from scientists.",
        "asset_class": "episode",
        "title": "The Launch",
        "genre": [
            "comedy"
        ],
        "director": "Paul King",
        "actors": [
            "Steve Carell",
            "John Malkovich",
            "Ben Schwartz"
        ],
        "season": 1,
        "episode": 1,
        "year": 2020,
        "rated": "TV-MA",
        "released": "29 May 2020",
        "language": "en",
        "runtime": "35 min",
        "imdbrating": 6.8,
        "imdbvote": "N/A",
        "licensing_window_start": "2023-08-06",
        "licensing_window_end": "2027-01-20",
        "preview_period": 30,
        "display_as_new": "N",
        "display_as_last_chance": "N",
        "audio_type": "AC3",
        "hdcontent": "Y",
        "maximum_viewing_length": "48:00",
        "series_name": "Space Force",
        "subtitle_languages": "en",
        "closed_captioning": "Y",
        "suggested_price": 0.0,
        "program_type": "episode"
    },
```

The settings, aside from stopWords, seem to be working correctly, as I can see their effect in the Meili Web UI. For example, if some field is not included in searchableAttributes, the search results do not return matching items for that field when a query is executed. Meili logs also do not contain any errors during the settings are applied.

As you can see, I have set "the," "a," and "an" as stop words. However, in the screenshot below, when the search query contains these words, results are still returned. I expect that when a stop word is set, Meili would exclude the corresponding items from the results during the search query execution (and avoid highlighting them too).

**Screenshots**
![image](https://github.com/user-attachments/assets/e457186f-dc56-4aa7-a2f2-bf5f8773f7b4)

**Meilisearch version:**
v1.10.2

**Comment by Its-kushal** [comment]
Hi Team,

I've reviewed the issue regarding stop words not being ignored during the search query execution, despite being configured in the settings file.

I plan to investigate the following areas:

Reviewing how stop words are processed during both indexing and search query stages.
Analyzing logs for any overlooked errors or edge cases related to stop words.
Verifying if the stop words list is properly applied when the settings are updated.
Additionally, I will inspect the code path from settings application to query execution to identify if there are any specific conditions under which stop words are bypassed during searches.

Please help me in setting up the environment and assign me this issue so that I can focus on it and solve it as soon as possible.

Looking forward to helping resolve this!

Thanks,
Kushal K

**Comment by anaibol** [comment]
> Hi Team,
> 
> I've reviewed the issue regarding stop words not being ignored during the search query execution, despite being configured in the settings file.
> 
> I plan to investigate the following areas:
> 
> Reviewing how stop words are processed during both indexing and search query stages. Analyzing logs for any overlooked errors or edge cases related to stop words. Verifying if the stop words list is properly applied when the settings are updated. Additionally, I will inspect the code path from settings application to query execution to identify if there are any specific conditions under which stop words are bypassed during searches.
> 
> Please help me in setting up the environment and assign me this issue so that I can focus on it and solve it as soon as possible.
> 
> Looking forward to helping resolve this!
> 
> Thanks, Kushal K

Wtf?

**Comment by Its-kushal** [comment]
> > Hi Team,
> > I've reviewed the issue regarding stop words not being ignored during the search query execution, despite being configured in the settings file.
> > I plan to investigate the following areas:
> > Reviewing how stop words are processed during both indexing and search query stages. Analyzing logs for any overlooked errors or edge cases related to stop words. Verifying if the stop words list is properly applied when the settings are updated. Additionally, I will inspect the code path from settings application to query execution to identify if there are any specific conditions under which stop words are bypassed during searches.
> > Please help me in setting up the environment and assign me this issue so that I can focus on it and solve it as soon as possible.
> > Looking forward to helping resolve this!
> > Thanks, Kushal K
> 
> Wtf? Are you an agent? What was your favorite part of the last movie you watched?

More like a machine

**Comment by ManyTheFish** [comment]
Hello @tysonite,
I managed to reproduce the bug locally, this occurs when doing a prefix search on a stop word, I may find a fix next week for the next release,

Thank you for the report!

**Comment by tysonite** [comment]
@ManyTheFish , thank you!

**Comment by LukasKalbertodt** [comment]
I came across this issue as well and noticed that this has something to do with Meilis prefix search. Searching for `"the"` and `"the "` has very different results. In the latter case, it's apparent that its treated as a stop word. I suppose Meili still needs to search for stop words at the end of the query (since they might be a valid prefix), but should ignore matches where the supposed prefix matches the whole world (e.g. if the word in the document is `the`).
