### ISSUE TITLE
Higher ranking threshold is returning more results

### ISSUE THREAD

**Issue by zperzendetta** [meilisearch/meilisearch#4989]
**Describe the bug**

The title.
Search_1 with ranking threshold set on 0.90 will return 4 results, with 0.9083333333333333 as max relevancy score.

Search_2, identical to Search_1 minus the ranking threshold that is changed from 0.90 to 0.91 returns 200+ results with 0.9611111111111111 and similars, that weren't even in Search_1.

**To Reproduce**

It's a closed instance, but I can provide a dump or a key + host privately.

**Expected behavior**

By increasing the ranking threshold I would expect less or none results, not 200+ out of nowhere.

**Meilisearch version:**
v0.10.0

This is an example of query:

```{"q": "search term", "limit": 1000, "showRankingScore": true, "rankingScoreThreshold": 0.92, "attributesToRetrieve" : ["A", "B"]}```

The endpoint is /search, but obviously it also affects multi-search.

**Comment by curquiza** [comment]
Hello @zperzendetta 

is your issue the same as #4988?

**Comment by zperzendetta** [comment]
Hi @curquiza, yes that's indeed the same issue.

**Comment by ManyTheFish** [comment]
@zperzendetta, thank you for your answer, I am closing this issue in favor of #4988,
don't hesitate to subscribe to it if you want to follow the advancement,

see you!
