### ISSUE TITLE
The search queue size default value of the config files is wrong

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4991]
**Describe the bug**
The default value of the config file is set to 0 instead of 1000.

Initial discovery was made in https://github.com/meilisearch/meilisearch/issues/4991

Even though the bug is on an experimental feature flag, it actually affects all instances 😬 

**To Reproduce**
1. Starts meilisearch with an empty config file

**Expected behavior**

**Meilisearch version:**
v1.9 to v1.11

**Comment by curquiza** [comment]
Closed by #4992
