### ISSUE TITLE
Meilisearch with Google Cloud Storage Bucket 

### ISSUE THREAD

**Issue by vitoalmeida** [meilisearch/meilisearch#4994]
I'm using a Meilisearch container at Google Cloud Run, and I created a bucket in Google Cloud Storage using [gcsfuse](https://cloud.google.com/storage/docs/gcsfuse-cli?hl=pt-br). The idea is to mount the Meilisearch container volume on this bucket. I can create an index, but when I post a document to an index, I receive the following error:
```
{
  "message": "failed to persist temporary file: Operation not supported (os error 95)",
  "code": "internal",
  "type": "internal",
  "link": "https://docs.meilisearch.com/errors#internal"
}
```

The gscfuse, give this additional logs:
```
{"timestamp":{"seconds":1728508262,"nanos":937616548},"severity":"ERROR","message":"Rename: operation not supported, cannot rename open file \".tmpim1lQI\": operation not supported"}
{"timestamp":{"seconds":1728508262,"nanos":937701027},"severity":"ERROR","message":"fuse: *fuseops.RenameOp error: operation not supported"}
```
I understand that Meilisearch might not support this case, because it's a specific error of an integration of Meilisearch and gcsfuse, but I hope someone can help me understand what is happening.

**Comment by irevoire** [comment]
Hello @vitoalmeida,

It looks like it’s `gcsfuse` that doesn’t support anything this time.
As you can see in the error message, it returns an error when Meilisearch tries to rename a file 🥶 

But as a general rule, Meilisearch doesn’t work well with network disks because they tend not to support locking correctly. (that’s the case with Azure for example)

In your case, you can’t do anything else than move to another solution. Sorry

**Comment by vitoalmeida** [comment]
> Hello @vitoalmeida,
> 
> 
> 
> It looks like it’s `gcsfuse` that doesn’t support anything this time.
> 
> As you can see in the error message, it returns an error when Meilisearch tries to rename a file 🥶 
> 
> 
> 
> But as a general rule, Meilisearch doesn’t work well with network disks because they tend not to support locking correctly. (that’s the case with Azure for example)
> 
> 
> 
> In your case, you can’t do anything else than move to another solution. Sorry

I understand, thanks for your reply!

It's a problem have a large database storage at the container memory? Because container memory is more expensive that a bucket or another types of storage.
