### ISSUE TITLE
Let users configure the time after which meilisearch drops the search requests

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4995]
**Context**
Meilisearch often runs behind a reverse proxy like nginx, and a common good practice is to set a timeout for all requests.
Not long ago we’ve stated that a search running for one minute or more could be dropped instantaneously because it was not relevant anymore.
But if there is a reverse proxy running in front of Meilisearch with a timeout of 10s then Meilisearch can be stuck processing searches that are not relevant anymore.

By letting the users configure this timeout we can greatly reduce the time spent processing useless searches.

**I want to release this as an experimental feature**

Ideally, Meilisearch should be able to detect when an HTTP connection was dropped, but there is currently a bug in actix-web; thus, that’s the best we can do.
But in the future, we may be able to drop this flag entirely if this gets fixed.

It’ll be a CLI flag named `--experimental-drop-search-after` that takes a number of seconds as a parameter.

**Meilisearch version:**
All versions

**Comment by curquiza** [comment]
Merged by #5000 and released in v1.10.3
