### ISSUE TITLE
Let the user configures how many searches can be processed by cores

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4997]
Currently, each core available can only process one search at a time.
But it looks like it could process way more depending on the kind of disk you’re using (HDD are sequential iirc, SSD can do read in parallel, EBS is completely another beast and should be able to be highly parallel as well).

We should provide a new `experimental-nb-searches-per-core` experimental cli flag that will configure this behavior.

**Comment by curquiza** [comment]
Closed by #5000 and released in v1.10.3
