### ISSUE TITLE
Add prometheus metrics about the usage of the search queue

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4998]
To help us debug search performance issues, we should add to the prometheus metrics the:
- Size of the search queue (a single number that shouldn’t change over time)
- The current number of searches being processed
- The number of searches waiting to be processed in the search queue

**Comment by bp7968h** [comment]
First, as soon as I forked and ran cargo test, some tests are failing, should I ignore and continue to work or what should I do in this case, below is the result for you reference or am I missing something:
```rust
failures:
    tests::delete_embedder_with_user_provided_vectors
    tests::import_vectors
    tests::import_vectors_first_and_embedder_later

test result: FAILED. 65 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 302.78s
```

And some tips, please on starting with this issue. Thank you very much for your assistance.

**Comment by irevoire** [comment]
Hey, you have a lot of information on the CONTRIBUTING.md
Here, it's hard to help you without more context, but I can see two possible causes of your issue:
- You are running on macOS and cannot run the tests like that. The easiest solution is to use cargo nextest, or you can run the test with something like “cargo test —-nb-threads 4” or something (I'm on the phone and cannot check what is the exact command Sorry)
- Orher thing that could be happening is that you must increase your ulimit; I believe the command to do it temporarily in your current bash session is "ulimit -Sn 30000,"a

**Comment by PedroTurik** [comment]
i am trying to understand where is this data found, Correct me if I am wrong please.

* Size of the search queue (a single number that shouldn’t change over time)

this seems to be equivalent to https://github.com/meilisearch/meilisearch/blob/be2a7c70f202358bbc9b87af81b3c48a6419165a/crates/meilisearch/src/search_queue.rs#L32

* The current number of searches being processed

I think this is found here, although I have no idea how to inspect this value during processing. https://github.com/meilisearch/meilisearch/blob/be2a7c70f202358bbc9b87af81b3c48a6419165a/crates/meilisearch/src/search_queue.rs#L90

* The number of searches waiting to be processed in the search queue

coudnt find something promissing

Perhabs i am missing something, I dont know if this information is already easily available for the API but this is what I could find.

**Comment by irevoire** [comment]
Hey @PedroTurik, it’s awesome you’re working on that I was thinking of doing it myself literally this today ahah

So FYI you can retrieve the `SearchQueue` data structure from the parameter of the [`get_metrics`](https://github.com/meilisearch/meilisearch/blob/0507f5d99b790fc098214aa67503a7ec515d1f61/crates/meilisearch/src/routes/metrics.rs#L18) function
```rust
pub async fn get_metrics(
    index_scheduler: GuardedData<ActionPolicy<{ actions::METRICS_GET }>, Data<IndexScheduler>>,
    auth_controller: Data<AuthController>,
    search_queue: web::Data<SearchQueue>, // here
) -> Result<HttpResponse, ResponseError> {
```

> Size of the search queue (a single number that shouldn’t change over time)

You’re right, it’s this number. You should just add a small getter to retrieve the number, and we should be good.

> The number of searches waiting to be processed in the search queue

It’s not this number, but it’s a good catch because we should definitely return metrics on this one as well. It represents the number of searches currently running, something that depends on a few parameters and is not that easy to compute on your side, but it can get quite large.

But it’s not that easy because we want to be 100% sure that no one will ever update this number except us.
I think the most efficient way to provide access to this number from multiple thread quickly without impacting the performances and ensuring we're still the only one able to modify the number would be to use an atomic number that replicates the count and that can be accessed from the `SearchQueue` datastructure directly.

```rust
#[derive(Debug)]
pub struct SearchQueue {
    sender: mpsc::Sender<oneshot::Sender<Permit>>,
    capacity: usize,
    /// If we have waited longer than this to get a permit, we should abort the search request entirely.
    /// The client probably already closed the connection, but we have no way to find out.
    time_to_abort: Duration,
    searches_waiting_to_be_processed: Arc<AtomicUsize>,
}
```

This way it’s easy to query, to make it as fast as possible, use the [`Ordering::Relaxed`](https://doc.rust-lang.org/stable/std/sync/atomic/enum.Ordering.html) please.
And in the `run` function **we should keep our old number as is** but, at the end of the loop, we should update the new one with the [`store`](https://doc.rust-lang.org/stable/std/sync/atomic/struct.AtomicUsize.html#method.store) function:
```rust
searches_running_metric.store(searches_running, Ordering::Relaxed);
```

> The number of searches waiting to be processed in the search queue

And finally, the number of searches waiting to be processed are simply the length of the queue defined at the beginning of the `run` function:
```rust
        let mut queue: Vec<oneshot::Sender<Permit>> = Default::default();
```

We have the exact same issue as before, but we can implement the same solution, an `Arc<AtomicUsize>` that gets updated at the end of the loop and that can be read from everywhere at the same time.

-----

Not sure this is super clear, do not hesitate to ask more question if anything wasn’t clear!

**Comment by PedroTurik** [comment]
Awesome :rocket:. Yes, the explanation is very clear, thanks. I am a bit confused on the naming of the second one though. Are both `let mut searches_running: usize` and the `len` of `let mut queue: Vec<oneshot::Sender<Permit>>` representative of the number of searches waiting to be processed in the search queue?

**Comment by irevoire** [comment]
Hey,

Not exactly.
The way the search queue works is that by default we have a capacity of 1000 searches sitting in the queue waiting to be processed.
But then, the `len` of the vector gives us the number of searches actually **waiting** to be processed.

When the queue has the space to process a new search request, it removes it from the queue and starts processing it. This number is the number of threads (`available_parallelism`) multiplied by a factor defined while starting Meilisearch (4 by default iirc).

So,
- `len` of the vec is equal to the number of searches waiting to be processed
- `searches_running` represents the searches actually being processed currently
