### ISSUE TITLE
We need to accept soft updates

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#50]
Soft updates are updates that can be ingested by the database without any cpu overhead.
Unlike the heavy updates they doesn't carry any fst-docids entry therefore no blob merge is needed and entry modification can be seen in realtime.

Obviously soft updates can only be done on non-indexed attributes.

Allowing this can be useful for custom ranking rules using non-indexed attributes frequently changing like a `number_of_clicks` attribute for example.

**Comment by qdequele** [comment]
Closed in favor of https://github.com/meilisearch/MeiliSearch/issues/527
