### ISSUE TITLE
Error 500 when sending bad rankingRules

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#500]
Currently, when I send a rankingRule which does not exist, MeiliSearch returns a `500`.
Ex: if I send `typos` instead of `typo`.

2 behavior possibilities:
- MeiliSearch returns a 400 with message `invalid data` if one of the rules is wrong.
- MeiliSearch returns an `updateId` anyway and the user can check if there were an error in his/her settings on update status routes.

~In both cases, it could be great if MeiliSearch can also check if the custom rules are right or not. I mean if the attribute in `desc(...)` or `asc(...)` is a known attribute. I don't know if it's complex to do or not~ => Bad idea, because the user could anticipate that he/she will push documents containing the field put as a custom rule.

### Steps

- [x] Fix in the code
- [x] Add tests to check this issue

### Version

`master` branch, this [commit](https://github.com/meilisearch/MeiliSearch/commit/2b780ab2c5f2da2eb5e9475ff789da5cba11c359).

### Fun fact

The 500th issue for a 500 error 🎉

**Comment by curquiza** [comment]
See also #487

**Comment by Kerollmops** [comment]
Would it be possible to send us the logs associated to the 500 you get please?

**Comment by curquiza** [comment]
```
[2020-03-04T15:32:21Z ERROR meilisearch_http::error] internal server error: impossible to convert into RankingRule
[2020-03-04T15:32:21Z INFO  tide::middleware::logger] POST /indexes/indexUID/settings/ranking-rules 500 0ms
```

**Comment by Kerollmops** [comment]
The error is related to the `Settings::into_update` method, and more specifically the way we return in case of an error:

https://github.com/meilisearch/MeiliSearch/blob/1cb9f750264702bbad3f5068fab2fb5d742b5860/meilisearch-http/src/routes/setting.rs#L132

https://github.com/meilisearch/MeiliSearch/blob/1cb9f750264702bbad3f5068fab2fb5d742b5860/meilisearch-http/src/routes/setting.rs#L194

We should do something more like:
```rust
let settings = settings.into_update().map_err(ResponseError::bad_request)?;
```
