### ISSUE TITLE
"unknown field `embeddingObject` after import dump on version 1.10

### ISSUE THREAD

**Issue by spectable** [meilisearch/meilisearch#5003]
**Describe the bug**

upgrading from 1.9.0 to 1.10

After having : INFO All documents successfully imported.

The next log line is : ERROR  - panicked at dump/src/reader/v6/mod.rs:127:59: called `Result::unwrap()` on an `Err` value: Error("unknown field `embeddingObject`, expected one of `source`, `model`, `revision`, `apiKey`, `dimensions`, `documentTemplate`, `url`, `request`, `response`, `headers`, `distribution`", line: 1, column: 204)

Ubuntu 22.04.2 LTS

Thanks !

Xavier

**Comment by CaroFG** [comment]
Closing this because we solve it via chatbox. Problem was braking change in 1.10
