### ISSUE TITLE
Docker latest image not updated to v1.11.0

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch#5020]
**Describe the bug**
With the release of v1.11.0 the docker `latest` image was not updated and is still set to v1.10.3. Checking docker hub it shows the last `latest` was published 18 days ago: https://hub.docker.com/layers/getmeili/meilisearch/latest/images/sha256-3b2c708c236792fb8d7de94a2df665617e3a0dcd87c77e735b3160f9a5c74551?context=explore.

**To Reproduce**
1. `docker pull getmeili/meilisearch:latest`
2. Start a docker container with `meilisearch:latest`

```console
meilisearch-1  | Config file path:      "none"
meilisearch-1  | Database path:         "./data.ms"
meilisearch-1  | Server listening on:   "http://0.0.0.0:7700"
meilisearch-1  | Environment:           "development"
meilisearch-1  | Commit SHA:            "cf5aa630d2fd262ccbac86ad007da451fa4d72c6"
meilisearch-1  | Commit date:           "2024-10-10T13:25:55Z"
meilisearch-1  | Package version:       "1.10.3"
```

**Expected behavior**
`meilisearch:latest` should be v1.11.0

**Screenshots**

**Meilisearch version:**
[e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by Kerollmops** [comment]
Hey @sanders41 👋

Thank you again for the bug report. Indeed, I probably made a mistake when publishing. I rerun the Docker CI to see if it fixes the issue, and if it doesn't, I'll have to fix it by hand.

You're the best,
Have a nice week 🏅

**Comment by Kerollmops** [comment]
With the help of @brunoocasali we finally fixed the latest tag of the Meilisearch Docker Image 👏
Thank you again for the report Sanders 👍
