### ISSUE TITLE
Only some records are indexed when importing hight volume to vectorize

### ISSUE THREAD

**Issue by anaibol** [meilisearch/meilisearch#5024]
### **Describe the bug**
When importing data into Meilisearch, only 300,000 to 700,000 records are indexed, despite having 8 million products in total.

### **To Reproduce**
1. Use the provided code to import products from a Prisma database into Meilisearch.
2. Start the import script.
3. Observe that the import stops after 300k to 700k records, even after a prolonged period.

### **Expected behavior**
All 8 million products should be imported and indexed into Meilisearch without prematurely stopping.

### **Screenshots**
If applicable, add screenshots or logs showing the number of records fetched and imported.

### **Meilisearch version**
[v1.11.0], but happening also on previous versions

### **Additional context**
- **Architecture**: Fly io machine 4 CPUs, 8GB RAM
- **Device**: Remote server
- **OS**: Ubuntu 20.04
- **Browser**: Not applicable

### **Meilisearch Settings**
Tried also with `MEILI_EXPERIMENTAL_REDUCE_INDEXING_MEMORY_USAGE= 'true"`

```javascript
export const meilisearchProductsIndexSettings: Settings = {
  stopWords: spa,
  sortableAttributes: ['id', 'offers.price', 'ratingsAverage', 'ratingsCount', 'createdAt'],
  embedders: {
    default: {
      source: 'huggingFace',
      model: 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
      documentTemplate: '{{doc.name}}',
      binaryQuantized: true,
    },
  },
  searchableAttributes: [
    'name',
    'brand.name',
    'model.name',
    'line.name',
    'categories.name',
    'hierarchicalCategories',
    'keywords',
    'offers.shop.name',
  ],
  filterableAttributes: [
    'hierarchicalCategories',
    'categories',
    'brand',
    'offers.price',
    'offers.shop',
    'ratingsAverage',
    'ratingsCount',
    'offersCount',
  ],
}
```

### **Code Snippet**
```javascript
import { prisma } from '@/db.server'
import { fullProductSelect } from '@/modules/product/product.service.server'
import {
  meilisearchProductsIndex,
  fullProductToMeiliSearchProduct,
  createMeilisearchProductsIndex,
} from '@/utils/meilisearch'
import pMap from 'p-map'
import pRetry from 'p-retry'

const importProductsToMeilisearch = async () => {
  const lastImportedProduct = await meilisearchProductsIndex
    .search('', {
      limit: 1,
      sort: ['id:desc'],
    })
    .catch((err) => null)
    .then((res) => res?.hits?.[0])

  let currentCursor = 0
  const numPerPage = 1000

  while (true) {
    const products = await pRetry(() =>
      prisma.product.findMany({
        take: numPerPage,
        ...(currentCursor && { cursor: { id: currentCursor } }),
        skip: currentCursor ? 1 : 0,
        select: fullProductSelect,
      }),
    )

    if (!products.length) break

    currentCursor = products[products.length - 1].id

    const newMeiliSearchProducts = await pMap(products, fullProductToMeiliSearchProduct)

    await pRetry(() => meilisearchProductsIndex.updateDocumentsInBatches(newMeiliSearchProducts))
  }
}

importProductsToMeilisearch()
```

**Comment by Kerollmops** [comment]
Hello @anaibol 👋

Thank you for the report. I will list all the reasons why it could fail that way.

1. Do you have any information about the tasks in the queue?
```
curl 'http://localhost:7700/tasks?statuses=failed'
```

2. Did you compile Meilisearch [with GPU support](https://www.meilisearch.com/docs/guides/ai/computing_hugging_face_embeddings_gpu)? It doesn't seem you did. I hope you have a GPU on your machine 😬

I recommend using a third-party [API like Ollama](https://ollama.ai) (which you can install on your machine) or OpenAI for that many documents. The `huggingFace` option will compute the embeddings locally, and it's not efficient at all on a non-GPU machine.

Have a nice day 🏞️

**Comment by anaibol** [comment]
> Hello @anaibol 👋
> 
> Thank you for the report. I will list all the reasons why it could fail that way.
> 
> 1. Do you have any information about the tasks in the queue?
> 
> ```
> curl 'http://localhost:7700/tasks?statuses=failed'
> ```
> 
> 2. Did you compile Meilisearch [with GPU support](https://www.meilisearch.com/docs/guides/ai/computing_hugging_face_embeddings_gpu)? It doesn't seem you did. I hope you have a GPU on your machine 😬
> 
> I recommend using a third-party [API like Ollama](https://ollama.ai) (which you can install on another GPU machine) or OpenAI for that many documents. The `huggingFace` option will compute the embeddings locally, and it's not efficient at all on a non-GPU machine.
> 
> Have a nice day 🏞️

Hello! Since I have a lot of records to vectorize and I have the time to do it on background, no worries if it takes hours or days, I am running it on the CPU. Moving to GPU or an external service would be much expensive. Before moving to meilisearch I was using typesense, which handled great the vectors computation on the CPU, so I think it's an issue with the queueu and jobs management.

I see there is an issue with storage
![Screenshot 2024-10-30 at 10 56 36 AM](https://github.com/user-attachments/assets/bf590210-30fb-40c1-ae03-c9f545d9adf7), but the fly.io vm has plenty of free storage.
![Screenshot 2024-10-30 at 7 16 17 PM](https://gith
![Screenshot 2024-10-30 at 7 16 38 PM](https://github.com/user-attachments/assets/49770b48-f4f5-41ec-b07c-dfa8c459d2aa)
ub.com/user-attachments/assets/ccadd3ef-ded4-45f3-b673-744b47902885)

**Comment by Kerollmops** [comment]
Hey @anaibol 👋

Thank you for the report. It seems that you are indeed out of disk space, but it's nearly expected. When Meilisearch is indexing, it writes a lot of temporary files. Those files are stored in the `$TMP_DIR` folder, which, most of the time, is not on the main disk. That's why you see plenty of unused space.

What I can recommend is to:
 1. Create a _tmp_ folder at the root of your main disk and change the `$TMP_DIR` folder to point to this one. Meilisearch MUST be aware of this environment variable (specify it correctly and reboot it). You should see an increase in disk usage when Meilisearch is indexing. We [are working](https://github.com/meilisearch/meilisearch/pull/4900) on **drastically reducing** the disk usage when indexing.
 2. Reduce [the number of batched tasks](https://www.meilisearch.com/docs/learn/experimental/max_number_of_batched_tasks). Meilisearch tries to batch all the enqueued tasks by default. On the cloud, we use different techniques to manage that correctly. But when managing it yourself, you need to specify this limit yourself. Too many processing tasks can result in too much content written to disk.

Have a nice day 🎃

**Comment by anaibol** [comment]
> Hey @anaibol 👋
> 
> Thank you for the report. It seems that you are indeed out of disk space, but it's nearly expected. When Meilisearch is indexing, it writes a lot of temporary files. Those files are stored in the `$TMP_DIR` folder, which, most of the time, is not on the main disk. That's why you see plenty of unused space.
> 
> What I can recommend is to:
> 
> 1. Create a _tmp_ folder at the root of your main disk and change the `$TMP_DIR` folder to point to this one. Meilisearch MUST be aware of this environment variable (specify it correctly and reboot it). You should see an increase in disk usage when Meilisearch is indexing. We [are working](https://github.com/meilisearch/meilisearch/pull/4900) on **drastically reducing** the disk usage when indexing.
> 2. Reduce [the number of batched tasks](https://www.meilisearch.com/docs/learn/experimental/max_number_of_batched_tasks). Meilisearch tries to batch all the enqueued tasks by default. On the cloud, we use different techniques to manage that correctly. But when managing it yourself, you need to specify this limit yourself. Too many processing tasks can result in too much content written to disk.
> 
> Have a nice day 🎃

cool! that worked. I really appreciate your help and I love the product you are building!!!
