### ISSUE TITLE
Importing dump error from 1.10.3 -> 1.11.0

### ISSUE THREAD

**Issue by Flo4604** [meilisearch/meilisearch#5028]
**Describe the bug**
When import a dump from 1.10.3 to 1.11.0 I am getting the following error: 

```
Error: unknown field `localizedAttributes`, expected one of `displayedAttributes`, `searchableAttributes`, `filterableAttributes`, `sortableAttributes`, `rankingRules`, `stopWords`, `nonSeparatorTokens`, `separatorTokens`, `dictionary`, `synonyms`, `distinctAttribute`, `proximityPrecision`, `typoTolerance`, `faceting`, `pagination`, `embedders`, `searchCutoffMs` at line 1 column 765
```

**To Reproduce**
Have a database with some data, create dump in 1.10.3 and try to then upgrade the dump in 1.11.0

**Expected behavior**
To not have this error message.

**Screenshots**
![CleanShot 2024-10-30 at 14 30 51@2x](https://github.com/user-attachments/assets/e622349f-aeb7-4fb5-ae8c-f643a9b51c02)

**Meilisearch version:**
v1.10.3 & v1.11.0

**Comment by Kerollmops** [comment]
Hey @Flo4604 👋

Unfortunately, I cannot reproduce your issue. Here are the steps I followed:

1. Start a Meilisearch v1.10.3 and send the `locallizedAttributes` settings into an index called _movies_ (whatever).
2. Enqueue a dump creation and wait for it to be done.
3. Stop this Meilisearch v1.10.3 version.
4. Delete the data.ms database.
5. Start a Meilisearch v1.11.0 with the `--import-dump {mydump}` where `mydump` is the previously generated dump
6. Profit as no error was thrown, and the settings contain the `locallizedAttributes` parameters.

Would you mind providing a reproducer with a dump included, please?
Have a nice day 🎃

**Comment by Flo4604** [comment]
Hi @Kerollmops I just pulled the latest tag again and it seems to work. 

Sorry about that looks like I was on the wronger docker image

**Comment by Kerollmops** [comment]
Ho! It [may have been a problem on our side then](https://github.com/meilisearch/meilisearch/issues/5020#issuecomment-2444802342). We are sorry for the inconvenience 🤦‍♂️
