### ISSUE TITLE
Cancel embedding operations for hybrid search after a deadline is met

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#5032]
Currently, any embedding request Meilisearch makes to an embedding server will be retried up to 10 times, with exponential backoff.

The exponential backoff has a time limit of 2 minutes, so the longest theoretical wait time is about 20 minutes.
For indexing, this may be fine: when embedding millions of documents, it might be preferable to sometimes wait multiple minutes rather than cancel the whole operation.

For search, however, this is too long.
- For hybrid search, we want to fallback to full-text search after one second.
- For pure semantic search, we want to error after a couple seconds.

This task is about implementing that change. No API change is expected at this point.

**Comment by curquiza** [comment]
in v1.12 in #4900
