### ISSUE TITLE
Add prometheus metrics about the latency on the task queue

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#5046]
It should be done after https://github.com/meilisearch/meilisearch/pull/5044; otherwise, there will be a ton of conflicts.
It should also probably be done using the work of this PR: https://github.com/meilisearch/meilisearch/pull/5048

We should add the duration between `now` (at the time of the polling) and the `enqueuedAt` time of the **oldest** `enqueued` or `processing` task.
That gives us a measure of the global indexing latency of the engine.
To retrieve the oldest `enqueued` task, we can do a filtered query to the task queue with a limit of 1 and the `reverse` parameter introduced in the PR above.

**Comment by takaebato** [comment]
I'll work on this!
