### ISSUE TITLE
Provide a `reverse` query parameter while querying tasks

### ISSUE THREAD

**Issue by irevoire** [meilisearch/MeiliSearch#5047]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Reverse-the-order-of-the-task-queue-1364b06b651f801ca127d982289892e5) (_internal only_)

## Motivation

Often, while debugging, being able to retrieve the oldest task that matches your filter could be useful, currently the only way to do it is to paginate the task queue which is not easy to do by hand, or to retrieve a few thousands tasks which is hard to read and doesn’t guarantee you have the oldest task.

## Usage

https://www.notion.so/meilisearch/Feature-Reverse-the-order-of-the-task-queue-1364b06b651f81dcb618e8409d30429b

## Impacted teams

@meilisearch/docs-team
@meilisearch/integration-team

**Comment by yeonicy** [comment]
Hello, we are computer science students. We came across this issue and would like to work on resolving it. Could we take this on?

Thank you!

**Comment by irevoire** [comment]
Hello folks!
It's awesome to see students using meilisearch.
Thanks for your interest but sadly this issue is already done, you can see my pr here: https://github.com/meilisearch/meilisearch/pull/5048

**Comment by curquiza** [comment]
Hello @yeonicy any "good first issue" tagged issue are welcome. We also have other repositories you can contribute (our integrations) listed here: https://github.com/meilisearch/integration-guides
