### ISSUE TITLE
Deleting documents is extremelly slow

### ISSUE THREAD

**Issue by anaibol** [meilisearch/meilisearch#5065]
Meilisearch v1.11.0

I am syncing my postgres database with meilisearch index and trying to delete by batches of 1000, all the documents that are not present on postgres. It takes multiple minutes to run each batch.

```javascript
for (let i = 0; i < idsToDelete.length; i += batchSize) {
  const batch = idsToDelete.slice(i, i + batchSize)

  try {
    const { taskUid } = await meilisearchProductsIndex.deleteDocuments(batch)

    await meilisearchClient.waitForTask(taskUid, {
      timeOutMs: Number.MAX_SAFE_INTEGER,
    })

    deletedCount += batch.length

    console.log(`Meilisearch: Deleted ${deletedCount}/${idsToDelete.length} documents so far`)
  } catch (error) {
    console.error(`Meilisearch: Error deleting batch starting at index ${i}:`, error)
  }
}
```

and these are my index settings
```javascript
export const meilisearchProductsIndexSettings: Settings = {
  stopWords: spa,
  sortableAttributes: ['id', 'offers.price', 'ratingsAverage', 'ratingsCount', 'createdAt'],
  embedders: {
    default: {
      source: 'huggingFace',
      model: 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2',
      documentTemplate: '{{doc.name}}',
      binaryQuantized: true,
    },
  },
  searchableAttributes: [
    'name',
    'brand.name',
    'model.name',
    'line.name',
    'categories.name',
    'hierarchicalCategories',
    'keywords',
    'offers.shop.name',
  ],
  filterableAttributes: [
    'hierarchicalCategories',
    'categories',
    'brand',
    'offers.price',
    'offers.shop',
    'ratingsAverage',
    'ratingsCount',
    'offersCount',
  ],
}
```

I see there are some issues mentionining soft deletes, but can't find info about on the docs.

**Comment by ManyTheFish** [comment]
Hello @anaibol,
There is no more soft deletion in Meilisearch, so all the deleted documents are completely deleted,
when batching your documents, I suggest creating bigger ones to help with the performance.
However, I don't understand why it's slow:
1) can you check if the finishedAt tasks dates are the same? If they are, it means that all your tasks have been processed altogether which explains the time taken to be processed.
2) How many documents do you have in your database and how many documents you delete ijn total?

**Comment by anaibol** [comment]
> Hello @anaibol, There is no more soft deletion in Meilisearch, so all the deleted documents are completely deleted, when batching your documents, I suggest creating bigger ones to help with the performance. However, I don't understand why it's slow:
> 
> 1. can you check if the finishedAt tasks dates are the same? If they are, it means that all your tasks have been processed altogether which explains the time taken to be processed.
> 2. How many documents do you have in your database and how many documents you delete ijn total?

You are right, the issue was that and add documents tasks (with slow cpu vector embeddings) were turning in paralel, so deletion tasks where queued in between.
