### ISSUE TITLE
Filter error ignored on search request

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/meilisearch#5069]
**Describe the bug**
When searching using `POST /indexes/{indexUid}/search` there is a strange behavior when there is an error coming from the `filter` param. Depending on the `filter` object, sometimes, even if an error is present, Meilisearch just returns no documents without any error. It happens when adding more filter items in an array (creating AND), but does not seem linked to the number of filter items in the array, rather maybe the length of each independent filter item maybe.

**To Reproduce**
1. Index the movies dataset
2. Add `genres` as filterable

Try with these requests
```
req: POST /indexes/movies/search
params: {
  "facets": [
    "genres"
  ],
  "filter": [
    "test=test"
  ],
  "limit": 20
}
error: {
  "message": "Attribute `test` is not filterable. Available filterable attributes are: `genres`.\n1:5 test=test",
  "code": "invalid_search_filter",
  "type": "invalid_request",
  "link": "https://docs.meilisearch.com/errors#invalid_search_filter"
}
```
🔝 This is expected ✅ 
```
req: POST /indexes/movies/search
params: {
  "facets": [
    "genres"
  ],
  "filter": [
    "genres=\"Action\"",
    "test=test"
  ],
  "limit": 20
}
response: {
  "message": "Attribute `test` is not filterable. Available filterable attributes are: `genres`.\n1:5 test=test",
  "code": "invalid_search_filter",
  "type": "invalid_request",
  "link": "https://docs.meilisearch.com/errors#invalid_search_filter"
}
```
🔝 This is expected ✅ 

```
req: POST /indexes/movies/search
params: {
  "facets": [
    "genres"
  ],
  "filter": [
    "genres=\"Action\"",
    "genres=\"Adventure\"",
    "genres=\"Animation\"",
    "genres=\"Comedy\"",
    "test=test"
  ],
  "limit": 20
}
response: {
    "hits": [],
    "query": "",
    "processingTimeMs": 0,
    "limit": 20,
    "offset": 0,
    "estimatedTotalHits": 0,
    "facetDistribution": {
        "genres": {}
    },
    "facetStats": {}
}
```
🔝 This is not expected and the response should be the same as previous examples 🔴
 
**Expected behavior**
Meilisearch should respond an `error` if a `filter` is wrong, in all cases.

**Meilisearch version:**
v1.11.3

**Additional context**
Tested with the Meilisearch Cloud search preview

**Comment by jameshiew** [comment]
It looks like it returns the 0 hits response if one of the earlier filter conditions matches nothing (e.g. `"genres=\"nomatch\"`), so it never reaches the `"test=test"` condition
