### ISSUE TITLE
`tests::test_task_queue_is_full` fails on Mac Mx

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#5077]
**Describe the bug**
Unit test `tests::test_task_queue_is_full`

**To Reproduce**
1. On a Mac M1
2. `cargo test -- test_task_queue_is_full`
3. The test fails

**Expected behavior**
The test passes

**Screenshots**

**Meilisearch version:**
`9a08757a70e8a929b3328bba0032e54b052094c7`

**Additional context**

Tested on Mac M1

**Comment by irevoire** [comment]
Fiexd by #5110
