### ISSUE TITLE
Duplicated tasks and wrong status in batch details

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#5079]
**Describe the bug**
The batch details reports two tasks being enqueued in the batch details, whereas we have only one task and it is in the processing state

**To Reproduce**
1. Send a `DocumentAdditionOrUpdate` task that will trigger a long indexing operation
2. Check that your task has spawned in the task queue:
```jsonc
// GET http://localhost:7700/tasks/0
{
  "uid": 0,
  "batchUid": 0,
  "indexUid": "mieli",
  "status": "processing",
  "type": "documentAdditionOrUpdate",
  "canceledBy": null,
  "details": {
    "receivedDocuments": 1500000,
    "indexedDocuments": null
  },
  "error": null,
  "duration": null,
  "enqueuedAt": "2024-11-21T16:38:06.145396Z",
  "startedAt": "2024-11-21T16:38:06.149318Z",
  "finishedAt": null
}
```
3. Get the list of batches
```jsonc
// GET http://localhost:7700/batches
{
  "results": [
    {
      "uid": 0,
      "details": {
        "receivedDocuments": 3000000,
        "indexedDocuments": null
      },
      "stats": {
        "totalNbTasks": 2,
        "status": {
          "enqueued": 2
        },
        "types": {
          "documentAdditionOrUpdate": 2
        },
        "indexUids": {
          "mieli": 2
        }
      },
      "duration": null,
      "startedAt": "2024-11-21T16:56:07.325266Z",
      "finishedAt": null
    }
  ],
  "total": 1,
  "limit": 20,
  "from": 0,
  "next": null
}
```
5. The details above indicate a batch of 2 tasks, even though there exists only 1 task
6. The tasks have status enqueued instead of processing.

**Expected behavior**
A batch of a single task with status processing.

**Meilisearch version:**
`9a08757a70e8a929b3328bba0032e54b052094c7`

**Comment by irevoire** [comment]
Fixed by #5123
