### ISSUE TITLE
How to apply MeiliSearch to VuePress?

### ISSUE THREAD

**Issue by LeoHsiao1** [meilisearch/MeiliSearch#508]
Hello!
Is it possible to provide a tutorial on applying MeiliSearch to VuePress?

I used to use Algolia as Vuepress's search engine, but it required A lot of rent.
I was glad to find MeiliSearch. This search box is awesome.
![image](https://user-images.githubusercontent.com/45813403/75965041-2fd12e00-5f03-11ea-9f02-35b2f1284899.png)

But I don't know how to write JS code, to apply MeiliSearch to VuePress.
Hope to get your tutorial or guidance.

**Comment by curquiza** [comment]
Hello,

Thanks for your interest in MeiliSearch and in our new documentation search bar ♥️

I'm the one who works on the Vuepress search-bar on our MeiliSearch Documentation :) We've just integrated it one week ago.

Now, we plan to do:
- a Vuepress plugin for MeiliSearch
- a detailed tutorial to explain how to integrate MeiliSearch in your own documentation.

Both of these points are still a work in progress, and I will keep you in touch. It should be available in the next few weeks 🙂

**Comment by LeoHsiao1** [comment]
Thanks so much. Then thousands of VuePress users will be able to upgrade their search box.

**Comment by Kerollmops** [comment]
I would like to keep the issue open, this way other interested people could find this issue ;)

**Comment by qdequele** [comment]
I close this issue in favor of meilisearch/backlog#9
