### ISSUE TITLE
Update mini-dashboard for v1.12

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#5093]
This issue exists in mini-dashboard: https://github.com/meilisearch/mini-dashboard/issues/563

And should be fixed in Meilisearch v1.12

**Comment by guimachiavelli** [comment]
This is just adding the banner to the local search preview, not porting the Cloud search preview UI to local, right?

**Comment by curquiza** [comment]
> This is just adding the banner to the local search preview, not porting the Cloud search preview UI to local, right?

Nope, only fixing a bug (the banner promoting the Cloud did not display)

**Comment by curquiza** [comment]
I close by the way, fixed by #5102
