### ISSUE TITLE
Opt-out settings routes for facet search and prefix search 404 in v1.12.0-rc.1

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch#5099]
**Describe the bug**

Trying to use the `settings/facet-search` and `settings/prefix-search` routes in v1.12.0-rc.1 is returning a 404

**To Reproduce**
1. Run v1.12.0-rc.1
2. Create an index
3. Do a request on the `.../settings/facet-search` or `.../settings/prefix-search` routes

**Expected behavior**
The `get`, `put`, and `delete` routes should work for these settings.

**Screenshots**

**Meilisearch version:**
[e.g. v0.20.0]
v1.12.0-rc.1

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Closed by #5101
