### ISSUE TITLE
MeiliSearch for Opencart

### ISSUE THREAD

**Issue by adrianmihalko** [meilisearch/MeiliSearch#510]
I really hope somebody will be working on a plugin for MeiliSearch for Opencart. This would be a game changer for all stores using Opencart. Currently the only good alternative is Algolia, but for small stores it is a not option, because of the price.

**Comment by Kerollmops** [comment]
Hey @adrianmihalko,

Thank you for the interest you have for MeiliSearch. We know that the opencart community will be glad to have a good extensin to plug MeiliSearch on it and be able to bring intant, and relevant search results to this platform, unfortunately we currently don't have the resource to build it.

But don't, we already added it to our roadmap!

**Comment by qdequele** [comment]
I close this feature in favor of meilisearch/backlog#10
