### ISSUE TITLE
Rust tests are failing with rc2

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#5103]
https://github.com/meilisearch/meilisearch/actions/runs/12081290350

- [x] JS -> ok, new settings
- [x] instant-meilisearch -> ok, highlight change
- [x] Ruby -> vector tests to adapt
- [ ] Rust -> to investigate `test_query_facet_distribution` and `test_query_filter_with_array` tests

**Comment by dureuill** [comment]
> Rust -> to investigate test_query_facet_distribution and test_query_filter_with_array tests

the tests are not flaky, they fail reliably on my mac, which is good news.

here's a list of failing tests, locally:

- [ ] dumps::tests::test_dumps_success_creation
- [ ]    search::tests::test_distinct
- [ ]    search::tests::test_generate_tenant_token_from_client
- [ ]    search::tests::test_query_facet_distribution
- [ ]    search::tests::test_query_filter
- [ ]    search::tests::test_query_filter_with_array

**Comment by dureuill** [comment]
https://github.com/meilisearch/meilisearch/pull/5109 fixes:

- [x]    search::tests::test_distinct
- [x]    search::tests::test_generate_tenant_token_from_client
- [x]    search::tests::test_query_facet_distribution
- [x]    search::tests::test_query_filter
- [x]    search::tests::test_query_filter_with_array

Remains:

- [ ] dumps::tests::test_dumps_success_creation

**Comment by dureuill** [comment]
latest run on RC3 was successful, apparently: https://github.com/meilisearch/meilisearch/actions/runs/12138580653/job/33844341863

Closing for now
