### ISSUE TITLE
Range queries

### ISSUE THREAD

**Issue by repomaa** [meilisearch/MeiliSearch#511]
This is a feature proposal:
Allow limiting range queries for numerical attributes. This would be extremely useful for timestamps and such.

**Comment by Kerollmops** [comment]
Hey @repomaa,

If I understand your feature request correctly, you would like the engine to restrict the documents to search in a reduced set of documents identified by the date in this document, only the documents that have a date in the specified range will be used for the search.

This feature is kind of easy to build and it is on our roadmap, you will need to specify in your settings that a field must be use for range queries, the engine will create an index specific to this settings containing the timestamp associated to the corresponding document id this way we will pre-filter the documents based on the filter the user want (t BETWEEN 2019 AND 2020, t > 2019).

**Comment by repomaa** [comment]
That’s exactly what I meant and awesome that it’s already on your roadmap!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qdequele** [comment]
I close this issue in favor of #425
