### ISSUE TITLE
Feature request: static search urls

### ISSUE THREAD

**Issue by Bajix** [meilisearch/MeiliSearch#512]
It would greatly simplify the DevOps of this were there to be support for static search urls. My current CI deployment for this currently needs to deploy my Meilisearch chart with a sidekick container to seed it, after which point I use the rollout status to detect that data has been initialized before I can curl the index and deploy just the dedicated redirect ingress controller. If I could create this with a known endpoint, then my DevOps wouldn't need a redirection subdomain ingress controller and this could be accomplished as a single deployment. Something like `/search/:index-name` would suffice. 

```
if helm status << parameters.release_name >> --namespace << parameters.namespace >>; then
  helm dep build deployment/helm/charts/core-platform

  export SEARCH_INDEX_UID=$(curl -s "https://search.${BASE_DOMAIN}/indexes" | jq '.[0].uid' | tr -d '"')

  envsubst < << parameters.values_file >> | helm upgrade << parameters.release_name >> \
  --wait \
  --timeout 180s \
  --atomic \
  --install \
  -f - \
  --namespace << parameters.namespace >> \
  deployment/helm/charts/core-platform
else
  rm deployment/helm/charts/core-platform/Chart.lock || true
  helm dep build deployment/helm/charts/core-platform

  kubectl create namespace << parameters.namespace >> || true

  envsubst < << parameters.values_file >> | helm install << parameters.release_name >> \
  --wait \
  --timeout 180s \
  --atomic \
  -f - \
  --namespace << parameters.namespace >> \
  deployment/helm/charts/core-platform

  kubectl rollout status deployment/<< parameters.release_name >>-meilisearch --namespace << parameters.namespace >>

  export SEARCH_INDEX_UID=$(curl -s "https://search.${BASE_DOMAIN}/indexes" | jq '.[0].uid' | tr -d '"')

  envsubst < << parameters.values_file >> | helm upgrade << parameters.release_name >> \
  --wait \
  --timeout 180s \
  --atomic \
  -f - \
  --namespace << parameters.namespace >> \
  deployment/helm/charts/core-platform
fi
```

**Comment by Kerollmops** [comment]
Hey @Bajix,

We have an (for the moment) hidden feature to help make the index creation easier to use. You can specify the uid of your index.

When you send your index creation request, add an "uid" field containing whatever you want (a-zAZ0-9-_) your index to be named, this uid can’t be changed in the future.

```json

{
  "name": "Movies",
  "uid": "movies",
  "schema": ...
}
```

**Comment by Bajix** [comment]
Well that makes everything WAY easier 🍾 Now everything can deploy in in a single helm deploy and my mobile app won't break!
