### ISSUE TITLE
Change the new indexer memory usage to use 5% of the max indexing memory

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#5132]
As we keep the previous settings indexer and as it uses the max indexing memory in a different way than the new indexer, we cannot define this parameter the same way. We need to keep it like before but internally use only 5% of it for the new indexer.

Related to https://github.com/meilisearch/meilisearch/pull/5125#issue-2719850968 and https://github.com/meilisearch/engine-team/pull/73#discussion_r1871693843

**Comment by yuvashrikarunakaran** [comment]
# Retrieve the original memory limit for indexing from the configuration
indexing_memory_limit = config.get('indexing.memory_limit')

# Calculate 5% of the original memory limit for the new indexer
new_indexer_memory_limit = indexing_memory_limit * 0.05

# Apply the memory limits accordingly
if using_old_indexer:
    set_indexer_memory(indexing_memory_limit)  # Full memory for the old indexer
else:
    set_indexer_memory(new_indexer_memory_limit)  # 5% memory for the new indexer


# meilisearch configuration

# Memory setting for indexer (this should remain for compatibility)
indexing.memory_limit = 1024 # in MB (or whatever your unit is)

# Internal memory limit for new indexer (5% of the above value)
indexing.new_indexer_memory_limit = 51  # 5% of 1024 MB

**Comment by curquiza** [comment]
Checked with @Kerollmops, can be closed because fixed by #5141
