### ISSUE TITLE
Add a constant value for the "_geo" reserved field

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#5136]
Unlike the `"_vector"` reserved field (`RESERVED_VECTORS_FIELD_NAME`) the field `"_geo"` field has no associated constant value and is hardcoded everywhere it's used.

- [ ] Add a `RESERVED_GEO_FIELD_NAME` in milli
- [ ] Replace all the hardcoded occurrences of "_geo" by the newly created constant

**Comment by Gnosnay** [comment]
hi @ManyTheFish i would like to help refactor it.
if you don't mind, could you assign this issue to me? thx

**Comment by Kerollmops** [comment]
Hey @Gnosnay 👋

We prefer not to assign anyone until the job is done. Please create a PR and work on the task so we can close this issue if you are interested.

Have a nice day 🧶

**Comment by Gnosnay** [comment]
> Hey @Gnosnay 👋
> 
> We prefer not to assign anyone until the job is done. Please create a PR and work on the task so we can close this issue if you are interested.
> 
> Have a nice day 🧶

understood. i will create one PR today or tmr. thx for you reply and have a nice day too
