### ISSUE TITLE
Query normalization issue - character decompositions

### ISSUE THREAD

**Issue by smarkyun** [meilisearch/meilisearch#5151]
**Describe the bug**
The problem is that the Ukrainian word ґрунт (soil) does not appear as a result for the term "гру". I assume this is because, according to the page linked in the "Query term normalization" documentation, the character г is not a decomposition of the character ґ. In this case, it would be necessary to make it possible to configure custom character mapping.

**To Reproduce**
1. Add a document which contains the character ґ (ґрунт сухий)
2. Search with an expression that uses the character г (гру)

**Expected behavior**
I expect the search engine to return the document as a hit

**Screenshots**
Documents in my index:
![image](https://github.com/user-attachments/assets/15a43e3b-7492-432a-b691-e9fd8a4d1f1c)
Search with base character:
![image](https://github.com/user-attachments/assets/55bb39d3-a28e-4222-b1f9-fc0c25d31398)
Search with upturn character:
![image](https://github.com/user-attachments/assets/cf2d5162-e6f4-4220-b269-60ee58d0a148)

**Meilisearch version:**
v1.11.3

**Comment by Kerollmops** [comment]
Hey @smarkyun 👋

It's probably a bug, indeed. We don't have a normalizer for Ukrainian in Charabia, our tokenizer. After reading the contributing file, you can propose a pull request [for this repository](https://github.com/meilisearch/charabia). I am closing this issue as we will not make progress on it, but if you manage to merge something on our tokenizer, feel free to reopen this issue, and we will close it as part of a milestone.

Thank you for reporting the issue,
Have a nice day 🏂
