### ISSUE TITLE
Meilisearch opening too many file descriptors

### ISSUE THREAD

**Issue by hasnat-rhino** [meilisearch/meilisearch#5172]
Update Filterable task -> "status": "failed",

"error": {
        "message": "Too many open files (os error 24)",
        "code": "too_many_open_files",
        "type": "system",
        "link": " "
    },

MacBook Pro
13-inch, M1, 2020
Memory 8GB
MAC OS Sequoia 15.2 (24C101)

**To Reproduce**
1. Update Filterable task -> 
put -> http://127.0.0.1:7700/indexes/dev_xxx_index/settings/filterable-attributes
2.  Task uid -> "status": "failed", -> get -> http://127.0.0.1:7700/tasks/xxxxxx
3. "error": {
        "message": "Too many open files (os error 24)",
        "code": "too_many_open_files",
        "type": "system",
        "link": "https://www.meilisearch.com/docs/reference/errors/error_codes#too_many_open_files "
    },
4. Tried -> launchctl limit maxfiles 256 unlimited
launchctl limit maxfiles 128000 524288 with no luck

**Expected behavior**
Filterable values should update properly

**Screenshots**

**Meilisearch version:**
"1.3.1"

**Additional context**
Additional information that may be relevant to the issue.

MacBook Pro
13-inch, M1, 2020
Memory 8GB
MAC OS Sequoia 15.2 (24C101)

Postman request on local development->

put -> http://127.0.0.1:7700/indexes/dev_xxx_index/settings/filterable-attributes
get -> http://127.0.0.1:7700/tasks/xxxxxx

**Comment by irevoire** [comment]
Also, if the issue still reproduces, you may want to increase the number of files meilisearch can use with the following command:
```
ulimit -Sn 15000
```

It must be run in the same terminal you're using to run meilisearch.

----

Sometimes when you have a lot of documents, Meilisearch won't have the choice but to store them on disk, which means creating a lot of small temporary files everywhere. We're always working on reducing this number of files, but it can still be an issue sorry

**Comment by hasnat-rhino** [comment]
@irevoire ulimit understood..... **-Sn 15000 works,** many thanks. As you have said, the most important thing is that "have to run this command on the same terminal thats running meilisearch" since its a soft limit.
