### ISSUE TITLE
Create a dashboard to configure the search & analytics

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#523]
We already have a small web page that allows a user to search on the data they have indexed. The goal of this would be to go much further with a full dashboard. This dashboard could include the following features:
- Create/delete indexes
- Change settings
- Manage keys
- See the list of updates
- Have a monitoring view

**Comment by djKooks** [comment]
@qdequele is there a repo for this project?

**Comment by qdequele** [comment]
Not yet. We are looking to hire an frontend developer expert and this feature is planned for the end of the year.

**Comment by djKooks** [comment]
@qdequele seems good~I'm also interested on this so please share us when project is released as open source

**Comment by eskombro** [comment]
Would it be interesting to have a simple interface to configure production environment (domain name, SSL, proxy...)?

**Comment by erlend-sh** [comment]
> Would it be interesting to have a simple interface to configure production environment (domain name, SSL/TLS, proxy/nginx...)?

It would indeed! But aren't we talking about something quite separate from the dashboard then? Basically the same as the [WordPress config page](https://wordpress.org/support/article/how-to-install-wordpress/#setup-configuration-file), right?

![image](https://user-images.githubusercontent.com/583842/82290275-cf507980-99a6-11ea-984c-45bb1491ed58.png)

**Comment by eskombro** [comment]
@erlend-sh that's exactly what I had in mind!

**Comment by djKooks** [comment]
@eskombro seems it is different concept with 'dashboard', but it also should be useful 👍

**Comment by erlend-sh** [comment]
Started a dedicated issue for that here: https://github.com/meilisearch/MeiliSearch/issues/698

**Comment by shrikrishnaholla** [comment]
For monitoring, rather than building your own, I'd advise following the protocol of existing monitoring solutions (like prometheus) so that the development effort can be conserved to focus on the core :)

**Comment by dmyers** [comment]
If you haven't heard of it, I recommend checking out [Netdata](https://github.com/netdata/netdata), I finally played with it today and it is simply amazing. It's fast and light weight and supports tons of collectors and storage backends and even supports Prometheus if someone wanted to build that already that was mentioned then it could work for it too.

https://github.com/netdata/netdata

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/85-dashboard?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
