### ISSUE TITLE
Search for Chinese?

### ISSUE THREAD

**Issue by tarvos21** [meilisearch/MeiliSearch#535]
Hi, love the performance and simplicity of MeiliSearch, any plan to add support for Chinese or other Hanzi based language?

There are some tools to segment Chinese text into words:
- [jieba-rs](https://github.com/messense/jieba-rs)
- [jieba](https://github.com/fxsjy/jieba)

Thanks!

**Comment by Kerollmops** [comment]
Hey @travos21,

Yeah, this is on our short roadmap I already though about using these libraries in the past but didn’t took the time to work on that, currently we « kind of » support CJK languages: the engine splits each kanji separately which will make them appear like different words, that is currently the best we can do.

We will work on the tokenizer this week and the next one to make it please all the needs.

**Comment by johnnyshields** [comment]
For Japanese I recommend you take a look at Kuromoji which we use for Japanese in Elasticsearch https://github.com/atilika/kuromoji and the ES plugin https://github.com/elastic/elasticsearch-analysis-kuromoji

Looks like someone is doing a Rust port here: https://github.com/fulmicoton/kuromoji-rs

Unfortunately each of Chinese, Japanese, and Korean have their own requirements.

**Comment by johnnyshields** [comment]
@MarinPostma correct if wrong but we can now close this?

**Comment by dzcpy** [comment]
Are Chinese and Japanese supported?

**Comment by tarvos21** [comment]
> Are Chinese and Japanese supported?

yes.
