### ISSUE TITLE
Improve user facing error management

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#537]
The goal of this issue is to improve the error handling at multiples points in the MeiliSearch API & Core.

## Improvement points

- Return the correct error message if the URL parameters or message body is wrong
- Add an URL to documentation in the HTTP error response if possible
- Review errors messages on updates
- Add warning messages on updates

## Sub Issues

- [ ] #487 Error when add wrong rankingOrder
- [ ] #432 Keep update logs

**Comment by MarinPostma** [comment]
closed in favor of #683
