### ISSUE TITLE
HTML safe render

### ISSUE THREAD

**Issue by emresaglam** [meilisearch/MeiliSearch#538]
Currently the web interface of Meilisearch renders the findings the way they are stored in the database. If the findings contains Cross Site Scripting Payloads for example, they will execute on the browser, possibly endangering the user. 

Web interface should be sanitizing the findings before displaying it on the results page. It will cause a security issue.

Thanks!

**Comment by emresaglam** [comment]
One way to fix this in the web interface is to write a sanitizer and pass all the `lastRequest.responseText` from it to replace `<` and `>` with `&lt;` and `&gt;` respectively. Again doing it on the browser side is still not the right/best thing to do, but it will cut the bleeding. IMHO the response from the search API should still return sanitized output (in other words the return sanitization should be done at the server side. At least this should be a global option. I understand the use case of serving html pages straight from the search results too...) 

I'm not great at javascript but here is one way how I resolved this on the web UI: 

Added a function: 
```
function sanitizeHTMLEntities (str) {
    if(str && typeof str === 'string') {
        str = str.replace(/</g,"&lt;");
        str = str.replace(/>/g,"&gt;");
      }
return str;
}
```

And called the function right after pulling the results of the search as:
```
.....
sanitizedResponseText = sanitizeHTMLEntities(lastRequest.responseText)
let httpResults = JSON.parse(sanitizedResponseText);
results.innerHTML = '';
......
```

I can do a PR if you want me to. :) 
Cheers!
Emre

**Comment by Kerollmops** [comment]
Hey @emresaglam,

Thank you, that is a great idea, it could be really cool if you make us a PR to "kind of" patch the web interface. In a second step I would like to look into how other databases/search engines handle this security setting, I believe this is opt-out: if the user didn't ask for raw unsecure output therefore the engine answer with a secure answer, removing all the dangerous html tags.

I will look into adding this feature to our roadmap, that is not a really comlex one, but we need to handle it correctly.

Have a nice day, and see you soon on the PR page :)

**Comment by emresaglam** [comment]
Here is the PR: https://github.com/meilisearch/MeiliSearch/pull/539

Merci et bonne chance avec covid19. Laver les mains ✋ :)

**Comment by Kerollmops** [comment]
Ho! Thank you very much I will look at and test it!

Oui, vous aussi, bonne chance et n'oubliez pas de vous laver les mains 🤚:)

PS: I will keep this issue open to make sure we add the feature in the engine at some point and find a good moment to do that.
