### ISSUE TITLE
First update does not appear before being processed

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#542]
I tried to add 19000 documents in one go (our movies dataset). It worked and was processed in 10-15 seconds.

However, during this 10-15 seconds, if I try to get the updates list, I get an empty list. Then, after this time, the update appears with the status `processed` (without passing by `enqueued`).

Then, I re-tried the same push in the same index, and I get the updates list. This time, I get immediately the update with the status `enqueued`, and then, after 0-15 seconds, the status passes to `processed`.

Seems like there is an issue for the first update.

### Version

MeiliSearch `v0.9.0`

## Edit

Just found out that the update does not appear with the global route `GET indexes/:index_uid/updates` but it does with the routes `GET indexes/:index_uid/updates/:updateId` !

**Comment by sgummaluri** [comment]
Hi, there!
Can I go ahead pick this up?
PS: this would be my first every open source contribution :)

**Comment by Kerollmops** [comment]
Hey @sgummaluri,

Yes, go on, but be carreful I marked this issue as a good-first-issue but it doesn't mean it is an easy one :)

**Comment by sgummaluri** [comment]
Hey @Kerollmops,

Fair enough. How do you suggest I get started with this?

**Comment by Kerollmops** [comment]
It would be good if you launch the MeiliSearch server with the `RUST_LOG=debug` environnement variable, this way MeiliSearch will display more things when indexing documents. Once done, create an index and send the 19000 movies in it (you can find those in the dataset folder of the repository) and try to reproduce the bug.

**Comment by Kerollmops** [comment]
Hey @sgummaluri,

It would be easier to have a direct conversation than using Github, you are welcome to our https://slack.meilisearch.com.

**Comment by sgummaluri** [comment]
Hi @Kerollmops ,
Issued a PR #587 that fixes this! Do let me know if there's anything else that needs to be done on this :)

**Comment by Kerollmops** [comment]
Closed by #587
