### ISSUE TITLE
Russian support

### ISSUE THREAD

**Issue by s2qts** [meilisearch/MeiliSearch#552]
I want to give it try, but I need Russian support for that. Any plans on that?

**Comment by Kerollmops** [comment]
Hey @s2qts,

We want to please everyone with the engine, eventually supporting every possible language but that is hard to do when you do not know how to read all of them. Currently the engine parses text by splitting by space and when it comes to CJK it split at every CJK character and considers each like a word.

I don't know if it will fit your needs at all, I would be interrested by your feedbacks on that.
It would be really cool if you could index some little sentences in the engine and tell me what's the state of the engine, how does it handle the queries.

Thank you very much for your interrest in the project!

**Comment by hitslab** [comment]
Yes, it works. For example this is movies dataset from https://www.themoviedb.org/ on russian: [movies-ru.zip](https://github.com/meilisearch/MeiliSearch/files/4456559/movies-ru.zip)

It works fine
![ru-example](https://user-images.githubusercontent.com/1733190/78903253-eb015f80-7a8b-11ea-8632-2e53b3ae6029.JPG)

**Comment by Kerollmops** [comment]
Thank you @hitslab, that is nice, I think I will close this issue then.

**Comment by Virviil** [comment]
@hitslab This test does not show nothing.

We are interested in full text search, so:

* Will it find «Побег с планеты земля» if you type «планета»?
* Will it find it, if you’ll type «пабег»?


If not, please reopen the issue.

**Comment by Kerollmops** [comment]
So I just tested and the engine correctly finds the document!

![Capture d’écran 2020-04-11 à 11 22 11](https://user-images.githubusercontent.com/3610253/79040158-c968bb00-7be6-11ea-8ac6-124b7ad0e863.png)
![Capture d’écran 2020-04-11 à 11 22 19](https://user-images.githubusercontent.com/3610253/79040160-cbcb1500-7be6-11ea-969f-0c0e9278d08c.png)

The only problem seems to be the higlight system, we will look into that.

**Comment by max-frai** [comment]
It's broken, not only about highlighting.
For example search word: `Нокиа` (it's nokia in russian) results in `США показали свою супер-пупер ракету`. There is nothing for such word. It's completely wrong :(

<img width="399" alt="Screenshot 2020-07-19 at 8 24 47 PM" src="https://user-images.githubusercontent.com/24208746/87880880-e559d500-c9fd-11ea-8d6e-ce19601ecffd.png">

**Comment by ManyTheFish** [comment]
Hello @lpkobamn,

This issue is quite old, and Meilisearch has changed a lot since then. Could you retry with the last version and reopen a new issue if you have one, please?

Thanks!
