### ISSUE TITLE
JSON Import does not take the "id" field into account

### ISSUE THREAD

**Issue by asitemade4u** [meilisearch/MeiliSearch#557]
I am trying to import a plain JSON file into Meili.
Here is an extract of the JSON:
```json
  {
    "id": 1,
    "ful": "Benjamin Blackledge",
    "qua": "architect",
    "cnt": "An architect, died June 20, 1942."
  },
  {
    "id": 2,
    "ful": "Rudolph C. P. Boehler",
    "qua": "architect",
    "cnt": "An architect, died in Cincinnati, Ohio, April 18, 1935, aged eighty-two. He designed the Grand Opera House and many other buildings in Cincinnati."
  },
```
As per your [instructions](https://docs.meilisearch.com/guides/main_concepts/documents.html#primary-key) I extract a primary key from my PostgreSQL database table primary key and have named it `id`.
Here are the import instructions:
```bash
curl -i -X POST 'http://srv.lan.ourquietplaces.com:7700/indexes/kuq_ppl/documents' \
--header 'content-type: application/json' \
--data-binary @bio.json
```
Then, when I check with `GET... /updates` I receive this error message:
```
  {
    "status": "failed",
    "updateId": 4,
    "type": {
      "name": "DocumentsAddition",
      "number": 3272
    },
    "error": "document id is missing",
    "duration": 0.001464155,
    "enqueuedAt": "2020-03-27T19:54:22.275804148Z",
    "processedAt": "2020-03-27T19:54:22.300046415Z"
  }
```
What am I doing wrong?

**Environment:**
- last docker version on a Debian 10 server

**Comment by asitemade4u** [comment]
I understand the `id` field is not a string, but is that the reason it does not work?

**Comment by asitemade4u** [comment]
However it works when I state the `primaryKey` in the index creation.
Nevertheless, it should recognize the `id`attribute in ny JSON file.

**Comment by MarinPostma** [comment]
hello @asitemade4u!
I can't repro with the example you provided, is there a chance that one of your document is missing an id?

**Comment by asitemade4u** [comment]
I do not think so as data are coming straight from PostgreSQL, and `id` is the table's primary key, unique, non empty.

**Comment by asitemade4u** [comment]
I can provide the full JSON on a private channel if you wish.

**Comment by MarinPostma** [comment]
you can join our [slack](https://slack.meilisearch.com/) and send it to me there

**Comment by asitemade4u** [comment]
email instead?

**Comment by MarinPostma** [comment]
sure, marin@meilisearch.com.
