### ISSUE TITLE
v0.9.0 linux binary cannot run in CentOS7 / RHEL7

### ISSUE THREAD

**Issue by ramkumarkb** [meilisearch/MeiliSearch#559]
Hi,

I tried to download the v0.9.0 linux binary and run it. I see the following error -
```
./meilisearch-linux-amd64 
./meilisearch-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./meilisearch-linux-amd64)
```
I have verifed that the required library does exist in my linux machine - 
```
lrwxrwxrwx. 1 root root      12 Jun 24  2019 /lib64/libc.so.6 -> libc-2.17.so
-rwxr-xr-x. 1 root root 2151672 Apr  1  2019 /lib64/libc-2.17.so
```
I do not have root or privileged rights go alter in `/lib64` dir. 

Is there anything that I can do to run this binary? 

Thank you,

**Comment by Kerollmops** [comment]
Hey @ramkumarkb,

That's strange because I just tested to run it on my debian machine (I am root on it) and it work great!

Are you trying to run it on Centos? Because [it seems to be a common problem](https://www.google.com/search?&q=/lib64/libc.so.6:%20version%20`GLIBC_2.18%27%20not%20found%20(required%20by)) and I have not idea how to make it work, sorry.

**Comment by ramkumarkb** [comment]
@Kerollmops - Thank you for the reply.

Yes, indeed am running this on RHEL-7 (most of the enterprises still use this version) - so it would be a pity if Meilisearch cannot run on this platform. This seems to be an issue with `glibc 2.17` (default in CentOS 7) and looks like Meili needs `glibc 2.18`
```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
uname -mrs
Linux 3.10.0-1062.el7.x86_64 x86_64
```
I noticed that `deno` (another famous project based on rust) had a long discussion on this thread - 
https://github.com/denoland/deno/issues/1658 and recently seems to have resolved this with this - https://github.com/denoland/rusty_v8/issues/49 

I will do some more research and see what comes out of that. Some workaround is described here - https://serverfault.com/questions/894625/safely-upgrade-glibc-on-centos-7/894689#894689

**Comment by ramkumarkb** [comment]
@Kerollmops - After some intense googling with trial-n-error, I was finally able to make Meilisearch work in RHEL-7. May be you can add these steps in the documentation or I can give a PR to the docs?

**Step-1**
Installed `glibc 2.18` in a `/my/customdir/` as per the gist
https://gist.github.com/carlesloriente/ab3387e7d035ed400dc2816873e9089e
(Only thing is that i just used `make install` instead of `sudo make install` as anyway this is my own custom dir)

Step-2
Used the following command - 
`patchelf --set-interpreter /my/customdir/glibc-2.18/lib/ld-linux-x86-64.so.2 --set-rpath /my/customdir/glibc-2.18/lib:/usr/lib64 ./meilisearch-linux-amd64`

Step-3
`./meilisearch-linux-amd64` 
😄

**Comment by Kerollmops** [comment]
That is so good to read that! Thank you for this intense debugging session 🎉

I keep this issue open for now on, next week I will create a markdown with all the different ways you can install and run MeiliSearch on all platform and we will talk about to it from the documentation too!

I am glad you did the work, this is really nice ❤️

**Comment by ramkumarkb** [comment]
It took between 5 to 10 mins to compile `glibc 2.18` 
Btw, am new to `rust` and I was thinking that it is similar to `go` in terms of cross-compiled binaries. But may be not... ?
Quick question on Meili - can we join 2 different indexes (this was added very late in Elastic - i think it was in 6.x) - but a very useful feature when it comes to search (with data authorization)

**Comment by Kerollmops** [comment]
It is in fact a little bit harder to crosscompile in Rust compared to Go, but I have found [this github action](https://github.com/stevenleadbeater/rust-musl-builder) that could potential help use compile with musl.

Currently it isn't possible to do any action between two indexes, those are separate entities that cannot interract. But what do you mean by joining indexes? Do you see the engine answers with two lists of documents or with only one that mixes the two?

**Comment by ramkumarkb** [comment]
Joining 2 Indexes is useful for Data Authorization usecase - example - 
Index-1 has Users with attributes
Index-2 has Movies
So if a User (who is a child) searches for Movies, the result will only show Movies that has the attribute `kids`.

I know that Elastic added this feature very late (only in 6.x). Before this, to filter search with a certain context was bit difficult.

**Comment by Kerollmops** [comment]
Hum... I think I understand but it means that the engine would interpret the documents of the Users index like filters of some kind.

Probably next week the engine will support more feature-full filters, this will make the engine be able to support this kind of usage. We will also rework and design a way more interresting authentication system that will probably be able to contain filters, this way the user will not be able ignore the filters applied at query time, those will be force because stored inside of the authentication token.

**Comment by peterpan666** [comment]
Hi, I've got the exact same issue on CentOS 7 😓

I've read your reply @ramkumarkb, I'm a little afraid that it would break the server's librairies.. Did you had any issue running this? I don't know what patchelf really does but it is not installed on my server, what did you do to get it running?

**Comment by ramkumarkb** [comment]
@peterpan666 - I got `patchelf` from the Anaconda3 distribution that I installed in my CentOS-7 (to be able to work with Python3). One can easily install Anaconda3 in CentOS-7 using its `sh` based distribution - https://docs.anaconda.com/anaconda/install/linux/ 
From the little I know about `patchelf`, since am targeting only `meilisearch` with this, I have so far not faced any issues.

**Comment by peterpan666** [comment]
Hey and thanks for the quick reply!

I've found [this](https://redbeardlab.com/2019/05/07/rust-and-glibc-version/) article and it seems to describe the problem we have here.

From my understanding, it seems to be a problem from how the released files are build.

> The rust compiler dynamically link the executable against the glibc in the system.
>  Hence if you compile your software against a newer version of glibc (say 2.19) that the one available where you run the executable (say in the host is available 2.14) it may not work.

The article suggest that it is possible to either build the binary file including librairies (with `cargo build --target x86_64-unknown-linux-musl`) or build it on a system that as an older version of libc.

I'll try it and see how it goes but do you think further releases could be built this way? I'm not familiar with Rust so I don't even know if this is applicable in anyway 😅

**Comment by peterpan666** [comment]
Hi again!

I got it to work smoothly without touching my server!

I installed Docker on my local computer.

Ran `docker run -i -t centos:7`

Installed librairies (`yum install git`, `yum groupinstall 'Development Tools'`, ...)

And followed steps from this repo to recompile from source https://github.com/meilisearch/MeiliSearch/tree/master#compile-and-run-it-from-sources

Transfered the binary file to my server and ran it.

It seems to work really great!

**Comment by Kerollmops** [comment]
Closing before it does seems relevant anymore, feel free to reopen or even propose a PR that compile MeiliSearch using musl.

**Comment by chiefruds** [comment]
@peterpan666 thank you very much for your solution, hereby the dockerfile that worked for us to everyone that is interested:
`
# Use CentOS 7 as the base image
FROM centos:7

# Install system dependencies for building MeiliSearch, including development tools and C compiler
RUN yum -y update && \
    yum -y groupinstall "Development Tools" && \
    yum -y install git curl gcc openssl-devel centos-release-scl && \
    yum -y install devtoolset-7-gcc* && \
    yum clean all

# Enable devtoolset-7 for a newer GCC version that includes stdatomic.h
SHELL ["/usr/bin/scl", "enable", "devtoolset-7"]

# Install Rust (This might need to be updated depending on the best practices for installing Rust)
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Clone the MeiliSearch repository
WORKDIR /usr/src
RUN git clone https://github.com/meilisearch/MeiliSearch.git
WORKDIR /usr/src/MeiliSearch

# Build MeiliSearch
RUN cargo build --release

# Expose the port MeiliSearch listens on
EXPOSE 7700

# Configure the container to run MeiliSearch, replace this with the actual path if different
CMD ["/usr/src/MeiliSearch/target/release/meilisearch"]
`

**Comment by peterpan666** [comment]
Glad it helped !

Just to be sure, this is still needed. I know nothing about Rust or how Meilisearch works, but is there change that can be made to Meilisearch so that we don't have to compile it by hand ?

The error seems to be because Meilisearch is compiled with some library installed but not actually being used...

**Comment by irevoire** [comment]
Hey @peterpan666,

> The error seems to be because Meilisearch is compiled with some library installed but not actually being used...

Which libraries are you talking about?
Because if you’re talking about the glibc, we do actually use it a lot 😅

**Comment by peterpan666** [comment]
Well maybe not the entire library but at least a lower version as I said in this previous post https://github.com/meilisearch/meilisearch/issues/559#issuecomment-619488100

If Meilisearch is still working fine with a lower version, it may be possible to compile it to lower said library version constraint ?

**Comment by Kerollmops** [comment]
> If Meilisearch is still working fine with a lower version, it may be possible to compile it to lower said library version constraint?

Unfortunately, the GLIBC version is constrained by [the Rust libc crate](https://github.com/rust-lang/libc), and, most specifically, the Rust crates that use the newest versions of this library. [There is a plan to document the supported GLIBC versions](https://github.com/rust-lang/libc/issues/1412), but it is still not the case yet.

**Comment by peterpan666** [comment]
Thanks for your answer ! Just to be clear, even if the GLIBC version was documented, we'd still have to compile Meilisearch by hand right ?

Is there anything we can do on CentOS to avoid this ? Like updating something or anything else ? Or we will just be stuck to compile Meilisearch on CentOS ?

**Comment by irevoire** [comment]
Hey @peterpan666,

> Just to be clear, even if the GLIBC version were documented, we'd still have to compile Meilisearch by hand, right?

Yes, we’re probably not against shipping a Meilisearch version linked against an even older glibc version.
But we’re already using the oldest version available in the GitHub action.

----

I’m still very curious, though, on my side, when I try to get the list of glibc versions supported by Meilisearch, here’s what I get:
```
objdump -T ./meilisearch-linux-amd64 | grep GLIBC | sed 's/.*GLIBC_\([.0-9]*\).*/\1/g' | sort -Vu
2.2.5
2.3
2.3.2
2.3.4
2.4
2.6
2.7
2.9
2.10
2.12
2.14
2.15
2.18
2.25
2.27
```

From what I understand means that some versions that are more than 20 years old are still supported. But a lot of versions in between are missing??
https://sourceware.org/glibc/wiki/Glibc%20Timeline

Could you share your version of the glibc, I believe this command should give you the version installed on your system `ldd --version ldd`:

```
$ ldd --version ldd
ldd (Debian GLIBC 2.36-4) 2.36
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

---

> Is there anything we can do on CentOS to avoid this ?

**IF** the issue is that CentOS is really using a glibc version that is more than 20 years old on the system, then maybe we should start asking them to update it. But I don’t think you can do anything on your side.
On your side, maybe we will find a way to build against a very old version of the glibc, but I don’t know any other way than compiling Meilisearch on a a super old system.

**Comment by peterpan666** [comment]
Here is what I got

```bash
$ ldd --version ldd
ldd (GNU libc) 2.17
```

It seems that this version is not listed in what you provided 😅

**Comment by irevoire** [comment]
Hey @peterpan666, I just checked with the team, and it looks like there is no other solution than compiling Meilisearch on an old enough distribution (or directly on the instance you want to run it on); we can’t do much to help you. Sorry 😔

**Comment by peterpan666** [comment]
Hi @irevoire, sad to hear this but thanks for the feedback !

Any chance the team could include this version compiled for CentOS with every release like the 5 others ? (2 MacOS, Windows, 2 Linux)

**Comment by curquiza** [comment]
Hello @peterpan666 
Yes it's totally possible, if the community opens a PR, I'm available to review it 👍 

However, regarding the really small number of CentOS users, we cannot afford to spend time doing maintenance if there are any issues with it. I hope you understand. Community will be needed in this case

**Comment by rc-power** [comment]
same issue
centos 9 use glibc 2.34, cannot run binary
