### ISSUE TITLE
Change highlight tags on configuration 

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#564]
For the moment the highlight tags are by default to `<em>` and `</em>`. 
It would be a good thing to be able to change them in the configuration.

```json
{
    "highlight_tags": {
        "pre_tag": "<span>",
        "post_tag": "</span>"
    }
}
```

**Comment by lironhl** [comment]
1. Should this configuration be part of [index settings](https://docs.meilisearch.com/references/settings.html), [search query parameters](https://docs.meilisearch.com/references/search.html) or both?

2. I assume it should only contain alphabetical characters in order to prevent XSS, correct?

**Comment by qdequele** [comment]
> 1. Should this configuration be part of [index settings](https://docs.meilisearch.com/references/settings.html), [search query parameters](https://docs.meilisearch.com/references/search.html) or both?

I think the simplest way is to enable this configuration on index settings. It' also possible to add it to the query parameters but I'm afraid that will complexify the search parameters. 

> 2. I assume it should only contain alphabetical characters in order to prevent XSS, correct?

We should probably authorize all characters to allow the person to put HTML, markdown, etc... But we can add a length constraint.

**Comment by qdequele** [comment]
This is no more relevant, we close it, feel free to comment here or open a new issue.

This feature complexifies the settings and it's not wanted now.

**Comment by curquiza** [comment]
Too bad, this feature would be great for front-end developers 😢
