### ISSUE TITLE
Query crashes process

### ISSUE THREAD

**Issue by piccaso** [meilisearch/MeiliSearch#566]
If I do a search like `/indexes/{index}/search?q=lala` meilisearch crashes showing this error:
```
thread 'async-std/executor' panicked at 'called `Result::unwrap()` on an `Err` value: NotDedup', meilisearch-core/src/query_tree.rs:534:46
```
It is specific to the query 'lala' everything else I tried works as expected.  
I'm using the latest version from the master branch built with the included Dockerfile.

Sadly I know next to nothing about Rust...
What can I do to narrow this down and provide a better bug report?

The json dataset I'm using is about 350MB in size.
I can share it (its will become public information soon anyway...) if that helps.

**Comment by Kerollmops** [comment]
Hey @piccaso,

Wooow, this is bad, I know this kind of error but it must have never occured, would it be possible that you add the `RUST_BACKTRACE=1` environement variable when you run the server please?

For your information [this is an error](https://docs.rs/sdset/0.4.0/sdset/set/enum.Error.html#variant.NotDedup) that occurs when an array of elements that must be ordered and deduplicated is not deduplicated. That kind of error must never occur!

PS: I would be glad you you can point me to the dataset :)

Thank you very much ❤️

**Comment by Kerollmops** [comment]
Anyway, [I found the line in the report](https://github.com/meilisearch/MeiliSearch/blob/e3808b869431ed3962ca845e7ec15d3f236b5212/meilisearch-core/src/query_tree.rs#L534) you already provide, I will fix that soon.

Thank you again for your report.
