### ISSUE TITLE
Add automatic release drafter using Github action

### ISSUE THREAD

**Issue by gnomeria** [meilisearch/MeiliSearch#582]
Hello, for the changelog do you you think better to use something like https://github.com/marketplace/actions/release-drafter ?
It will automatically generate a draft for the github release based on the pull requests. I understand you've already setup a pull-requests check to always update the `CHANGELOG.md`.

**Comment by Kerollmops** [comment]
Hello,

This solution could be great as we cannot forget to update the `CHANGELOG.md` but I will probably not like the generated changelog as there is more than 1300 commits that are not formatted.

I would prefer having to update it by hand, and I am currently looking at the github action reference to see if I can add a `ignore-changelog` label to a PR and ignore my github-action conditionally (regarding this label). This way I'll avoid showing ❌ when unecessary.

Thank you for the proposition anyway 😁

**Comment by gnomeria** [comment]
Thanks for the reply. I think I just want to add that using the release drafter, it will be based on the names of the pull requests, and could be configured automatically to separate a fix, features, etc, so it's not based on commit. And you could manually edit the generated results when you're ready to release, remove some stuffs, or add label in pull-requests so it's not included.

**Comment by Kerollmops** [comment]
In fact the solution you prupose seems wayyy better than mine, I will look into that next week and reopen this issue! Thank you!

**Comment by gnomeria** [comment]
I could try to make a PR for this if you'd like

**Comment by Kerollmops** [comment]
I would love that you do this and remove my current ugly tricks to detect if the `CHANGELOG.md` have been updated :)

**Comment by gnomeria** [comment]
Hello, I've implemented initial configs in https://github.com/gnomeria/MeiliSearch/releases
Currently it will pickup all the merged requests without label in `CHANGES`. It will push a new tag based on the release. But the subsequent actions are not going to be triggered by the release tag, it needs to subscribe on `release` event for the upload release package. Do you think we should change the `publish-*.yml` actions to subscribe on release events?

**Comment by Kerollmops** [comment]
> Currently it will pickup all the merged requests without label in `CHANGES`.

Hum, do you mean that if the PR have a label named `changes` this tool will not take it into account? Or am I missunderstanding something?

> It will push a new tag based on the release. But the subsequent actions are not going to be triggered by the release tag, it needs to subscribe on release event for the upload release package.

Isn't there a way to trigger it on each PR, this way it can just fill in the `CHANGELOG.md`?
And also avoid making it create a tag? I would prefer making the tag myself, this way I can update the versions and update the `CHANGELOG.md` myself.

**Comment by gnomeria** [comment]
> Hum, do you mean that if the PR have a label named `changes` this tool will not take it into account? Or am I missunderstanding something?
No I mean, for PR that is not being labelled as a feature,bugfix, or chore, it will be defaulted to be put under `changes` section


> Isn't there a way to trigger it on each PR, this way it can just fill in the `CHANGELOG.md`?
> And also avoid making it create a tag? I would prefer making the tag myself, this way I can update the versions and update the `CHANGELOG.md` myself.
You mean just make it to update the `CHANGELOG.md` for each commit on PR? I haven't tried it actually. For the tagging, I think because it's being made in draft first without creating any tag, when you're ready to release, you can just choose version/tag on the release page version.
Or this changes too much on the flow?

**Comment by Kerollmops** [comment]
Thank you for all the work you've done but I don't think this tool can be used as easy as we would like it, and we will not integrate it into the workflow.

However, FYI we are always willing for a tool to compute the CHANGELOG for us but no tool fits our needs.
