### ISSUE TITLE
Adding Stop Words Breaks Searching

### ISSUE THREAD

**Issue by umahmood** [meilisearch/MeiliSearch#586]
Hello,

I am new to meilisearch so hopefully I have not made an obvious mistake. 

When adding stop words to an index and then performing a search at http://127.0.0.1:7700/ or via an api (i.e. meilisearch-go) no results are returned. 

Setup:
```
$ brew install meilisearch

$ meilisearch

$ curl -L 'https://bit.ly/2PAcw9l' -o movies.json

$ curl -X POST 'http://localhost:7700/indexes' \
  --data '{
  "uid": "movies",
  "primaryKey": "id"
}'

$ curl -i -X POST 'http://127.0.0.1:7700/indexes/movies/documents' \
  --header 'content-type: application/json' \
  --data-binary @movies.json
```
Verify search is working:
1. go to http://127.0.0.1:7700/
2. search for "the mask" 

~20 documents will be returned.

To Reproduce:

1. add the stop words:
```
curl \
  -X POST 'http://localhost:7700/indexes/movies/settings/stop-words' \
  --data '["the", "of", "to"]'
```
1. go to http://127.0.0.1:7700/
2. refresh the page
3. search for "the mask"

Observed behavior:

zero documents are returned. In fact, after entering more than two characters into the search field no entries are returned. This is true for any search string. And as stated above, calls made via an api library also return zero results.

Deleting the stop words with:
``` 
$ curl \
  -X DELETE 'http://localhost:7700/indexes/movies/settings/stop-words' \
``` 
Search begins to work again. 

I have added a few indexes and seen the same behavior when adding stop words. 

Environment:

Index information:
```
  {
    "name": "movies",
    "uid": "movies",
    "createdAt": "2020-03-31T13:10:43.594006Z",
    "updatedAt": "2020-04-04T13:25:04.839943Z",
    "primaryKey": "id"
  },

```

OS: macOS Catalina 10.15.3 

Browser: Firefox 74.0.1 (64-bit)

Meilisearch: meilisearch-http 0.9.0

**Comment by ppamorim** [comment]
@Kerollmops I am able to reproduce this issue.

**Comment by Kerollmops** [comment]
Thank you @umahmood and @ppamorim,

That is a really strange issue, I will look into that tomorrow, I'm sorry about that!
