### ISSUE TITLE
Server is slow to respond on update status api

### ISSUE THREAD

**Issue by yjh0502** [meilisearch/MeiliSearch#590]
I dumped index from elasticsearch and inserting it to millisearch. It seems that indexing is running on background, so my meilisearch instance have 30 pending updates with 10000 documents each, total 300K documents pending.

I tried to check how many updates are pending by using `/indexes/{name}/updates` API but it took quite long,  ground 15~20 seconds in my case.

```sh
$ curl '127.0.0.1:7700/indexes/d_article/updates' | jq '.[] | select(.status == "enqueued") | .updateId' | wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 68288    0 68288    0     0   4052      0 --:--:--  0:00:16 --:--:-- 18786
31
```

I'm not sure if it's a bug or intended behavior, but single API call taking 20 seconds looks suspicious.

**Comment by ppamorim** [comment]
Hi @yjh0502 

Could you please share a document example or describe how big is each document in your dataset? 

Thank you.

**Comment by Kerollmops** [comment]
Hey @yjh0502,

This is a known issue, this is related to some internal storage system and we must need to work on that. This is because when we return the updates we deserialize the JSON content sent by the user which can obviously be skipped.

Thank you for the report!

**Comment by qdequele** [comment]
Close in favor of #692
