### ISSUE TITLE
Guide on memory/disk usage?

### ISSUE THREAD

**Issue by yjh0502** [meilisearch/MeiliSearch#591]
Hi, I'm trying to test meilisearch by ingesting existing dataset served by ElasticSearch to MeiliSearch.

Is there any guide on memory / disk space / disk IO usage of the search engine? I inserted 10M documents, 5GB JSON dataset with 18 fields, 4 text fields, 14 numeric/boolean fields.

MelliSearch is using
 - memory: RSS 17GB, virtual memory 250GB
 - 79GB of disk space, 77GB main, 2GB update
 - reading 200~300MB/s from SSD while inserting documents (from LMDB memory-mapped file?)

Is there any guidelines for expected resources/machine size for the workload size?

**Comment by ppamorim** [comment]
Hi @yjh0502 

You can use these calls to get system information:

https://docs.meilisearch.com/references/sys-info.html#get-pretty-system-information
https://docs.meilisearch.com/references/sys-info.html#get-system-information

**Comment by Kerollmops** [comment]
Hey @yjh0502,

We are currently working on a document that we will put in the documentation website.
It will summarize how MeiliSearch and mostly LMDB, the key-value store we use internaly.

We will keep you up in this issue.

**Comment by tpayet** [comment]
Hello @yjh0502, I just wrote a guide about [MeiliSearch storage](https://docs.meilisearch.com/resources/about_storage.html)

Let me know if anything is still unclear or if you need any more precision
