### ISSUE TITLE
Documents with nested object array are not inserted

### ISSUE THREAD

**Issue by tadeugr** [meilisearch/MeiliSearch#593]
**Reproduce the error**

Run meilisearch:

```
docker run -it --rm \
    -p 7700:7700 \
    -v $(pwd)/data.ms:/data.ms \
    getmeili/meilisearch
```

Create an index.

```
curl \
  -X POST 'http://localhost:7700/indexes' \
  --data '{
  "uid": "testdata",
  "primaryKey": "uuid"
}'
```

Create a file called `test-array-1st-level.json` with the following content.

```
[
  {
    "uuid": "001",
    "first_level_array_works": [
      {
        "name": "value"
      }
    ]
  }
]
```

Create a file called `test-array-2nd-level.json` with the following content.

```
[
  {
    "uuid": "002",
    "my_array": {
      "second_level_array_does_not_work": [
        {
          "name": "value"
        }
      ]
    }
  }
]
```
Insert both files.

```
curl \
  -X POST 'http://localhost:7700/indexes/testdata/documents' \
  --data @test-array-1st-level.json

curl \
  -X POST 'http://localhost:7700/indexes/testdata/documents' \
  --data @test-array-2nd-level.json
```

Get documents.

```
curl \
  -X GET 'http://localhost:7700/indexes/testdata/documents?limit=5'
```

**Result**

Only `test-array-1st-level.json` was inserted.

```
[{"uuid":"001","first_level_array_works":[{"name":"value"}]}]
```

**Expected result**

Both data files inserted.

**Comment by Kerollmops** [comment]
Hey @tadeugr,

@ppamorim [already fixed that issue](https://github.com/meilisearch/MeiliSearch/pull/575), it will be available in the v0.9.1 release (end of the week) but if you need to continue working on your project and that issue is blocking you can compile and run the master branch.

Thank you for this detailled issue ❤️
