### ISSUE TITLE
batch add documents error

### ISSUE THREAD

**Issue by jet10000** [meilisearch/MeiliSearch#595]
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=7700): Max retries exceeded with url: /indexes/books/documents (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x101f29bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```
I have 100G mysql table, I want to add table items to meilisearch, with for loop per request 1000 rows. when loop run, after a while it's display :

```
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

docker meilisearch

**Comment by Kerollmops** [comment]
Hey @jet10000,

It seems like the server is likely overwhelmed, 100GB is a lot, I would like to have the logs of the server but it is likely that it has been killed by the OS running out of memory.

How many rows do you try to index in total?

I am currently working on finding a way to avoiding being out of memory while indexing, that is a hard problem to face.

Thank you for you interest in MeiliSearch anyway.

**Comment by jet10000** [comment]
Maybe docker version meilisearch's problem or limit, I just test meilisearch with local binary, current it's running, it already add more than 2 millions rows.

My mysql table total 3199244 rows.

MacOS 16G

**Comment by tpayet** [comment]
Hey actually, Docker has a default limit on MacOS that is quiet low. You can change the RAM and the cpu that you allocate to your virtual machine :) I think that Docker can use a maximum of 2Gb of RAM & 4 CPU by default, but these are settings you can change.

I suggest you change these settings if you want to use MeiliSearch on Docker which could be easier to deploy in production then ^^

**Comment by jet10000** [comment]
ok, I will test it.

current , I convert my mysql table to json per size is 2G, then use curl post to meilisearch local version, everything looks normal.

**Comment by JamieDixon** [comment]
For what it's worth I ran into an issue today where bulk adding records crashed Meilisearch. Here are our batches that all ran at around about the same time:

```
Indexing  with  3  records
Indexing  with  41  records
Indexing  with  194  records
Indexing  with  135  records
Indexing  with  8  records
Indexing  with  7  records
Indexing  with  91  records
Indexing  with  16  records
Indexing  with  130  records
Indexing  with 231  records
Indexing  with 280  records
Indexing  with  12  records
Indexing  with  11  records
Indexing  with  191  records
Indexing with  9  records
Indexing with  853  records
Indexing with  19  records
Indexing with 551  records
Indexing with  1  records
Indexing with  6  records
Indexing  with  1387  records
Indexing  with  6  records
```

Totalling `4182` records. 

When we put a 3 second delay between each batch so that the most that was being processed in one go was `1387` records, everything worked alright.
