### ISSUE TITLE
Significant changes in memory use in sys-info route

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#597]
When using `GET /sys-info` on MeiliSearch v0.9 in a server without any index or any documents this is what the overall info looks like. Please take a close look to `memoryUsage` and to the `global` key.

**V0.9:**
```json
{
  "memoryUsage": 91.07058048248291,
  "processorUsage": [
    1376.4003,
    1009.98267,
    766.17413,
    630.2423,
    530.9981,
    458.37265
  ],
  "global": {
    "totalMemory": 0,
    "usedMemory": 0,
    "totalSwap": 0,
    "usedSwap": 0,
    "inputData": 0,
    "outputData": 0
  },
  "process": {
    "memory": 0,
    "cpu": 0
  }
}
```

When trying the same route with the same preset but on master branch this is the result, take a close look at `memoryUsage`

**Master branch:** 
```json
{
  "memoryUsage": null,
  "processorUsage": [
    0,
    13.76223,
    10.098557,
    7.6607914,
    6.3013463,
    5.3090277,
    4.583062
  ],
  "global": {
    "totalMemory": 16777216,
    "usedMemory": 15279108,
    "totalSwap": 1048576,
    "usedSwap": 8192,
    "inputData": 4380023808,
    "outputData": 533682176
  },
  "process": {
    "memory": 7808,
    "cpu": 0
  }
}
```

Why are they so different? What changed? I couldn't find anything discussing that in the changelogs.

**Comment by jelly** [comment]
For me the memory endpoint does not work at all in master and 0.11.0 but when moving sys.refresh_all() at the start of the request it works.

**Comment by MarinPostma** [comment]
yeah @Jelly, you are right the position of the refresh in weird. Maybe sysinfo was bumped and behavior changed. @bidoubiwa can you confirm that calling this endpoint twice gives the expected result?
