### ISSUE TITLE
Nested document supported?

### ISSUE THREAD

**Issue by bortels** [meilisearch/MeiliSearch#600]
So - when trying to insert a json document with nested data... I get a 202 response and the updateId changes (ie. no error), but no document is actually inserted. If I remove all of the nested arrays and just leave in first level keys - it inserts fine. 

Is this a known/expected behavior? The original doc is not overly large (3k). The data is an aws ec2 "describe instances" result for a single instance - I can provide a sanitized copy if that helps.

**Comment by Kerollmops** [comment]
Hey @bortels,

It has been fixed and is now supported by MeiliSearch on the master branch, we will release a v0.9.1 version on the engine probably at the end of the week. However if you need this feature rigth now you [can compile MeiliSearch yourself](https://github.com/meilisearch/MeiliSearch#compile-and-run-it-from-sources) using the master branch.

Thank you for your interrest in the project :)
