### ISSUE TITLE
Automatically index content in a GraphQL server?

### ISSUE THREAD

**Issue by ryanberckmans** [meilisearch/MeiliSearch#606]
MeiliSearch looks great! I'd love to try it... my data is in a GraphQL server.

Is there a plugin or adapter to automatically index all content in a GraphQL server?

Bonus marks if the configuration allows whitelisting+blacklisting a subset of the GraphQL Schema. And re-indexes on an ongoing basis, or uses GraphQL subscriptions to update indexes in real time as the underlying data changes.

FYI the GraphQL server I'm using is https://hasura.io/.

**Comment by Kerollmops** [comment]
Hey @ryanberckmans,

MeiliSearch doesn't supports being sourced from a GraphQL instance but it can be done by an external tool that pulls the schema and the documents from it and sending those to the search engine.

Thank you for your interrest in MeiliSearch :)

**Comment by ryanberckmans** [comment]
@Kerollmops can you recommend or are you aware of such an external tool/adapter that can glue a GraphQL instance to MeiliSearch? Thanks!

**Comment by Kerollmops** [comment]
I am not aware of any tools that can do that, but it would be straighforward to build one, you can ask for batches of documents directly form the GraphQL server in JSON and send arrays of JSON documents to MeiliSearch, no need to export the GraphQL schema, only the primary key maybe.

https://docs.meilisearch.com/guides/introduction/quick_start_guide.html#create-your-index
