### ISSUE TITLE
Clean up the README to make it clear

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#613]
That was a mistake of me to keep the list of [MeiliSearch raw supported features under the "Technical features" header](https://github.com/meilisearch/MeiliSearch#technical-features). I would like that no more links points to the internal code.

This is more disturbing than helpful for anyway.

Anyway, would it be possible to clear and shorten the README, removing one of the two gifs, the performances section could be moved to the documentation for example.

I didn't thought that people comming to the repository would be people who don't want to know about the internal tech but just want to see the supported features for their needs.

What do you think about that?

**Comment by curquiza** [comment]
I agree I think your suggestions would make it clearer 👍

**Comment by Kerollmops** [comment]
#630 partially fixed this.

**Comment by tpayet** [comment]
Will work on this next week :)
