### ISSUE TITLE
Tracking issue: New tokenizer

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#624]
This is the tracking issue for Meilisearch's tokenizer rewrite.

It builds on the efforts of #560 and #275 (both closed in favor of the this issue)

## Why Meilisearch needs a Tokenizer? 

Tokenizer's principal role is to split documents into words (tokens) so each document can be indexed by it's contained words. It is also needed to split a search a query into token, and search on the work index.

It turns out that splitting texts into tokens is a complicated task, especially when you need to handle more than a single language. While the task for english may seem trivial at first glance (_mostly_ split white space), Chinese tokenization, for example is completely different (no spaces between words, groups of 1, 2 or 3 characters...).

Therefore, in order to provide the best possible language support for meilisearch, we decided to rewrite our tokenizer.

## A new approach 
Instead of designing a one-does-it-all tokenizer, that handles every language at the same time, we instead thought of a modular one. The goal is to efficiently scan through the text and split it according to the scripts (alphabet kinda) it contains. Once that is done, we define rule specifying which tokenizer to use for which script.

For now, we will use:

- Our Latin tokenizer, for Latin scripts
- [Jieba](https://github.com/messense/jieba-rs) for Chinese
- [Lindera](https://github.com/lindera-morphology/lindera) for Japanese and Korean
- The modular approach makes it easy to add other tokenizer for specific languages when they are needed

## Eventual optimization

For now, the goal it to scan through the text before we start emitting tokens. It decouples script detection and tokenization, but it has a cost. If tokenization appears to be a bottleneck in indexing in the future, we may consider using a default Latin tokenizer that emits tokens while scanning through the text, and only use fallback tokenizers is it detect non Latin scripts.

We may also want to provide event better language support with accurate language detection. We've done some experimentation with [whatlang](https://github.com/greyblake/whatlang-rs), but found the performance hit to critical to consider it now.

We've also considered huggingface's [tokenizers library](https://github.com/huggingface/tokenizers), but found it to allocate to much, and not fitting our needs.

## Related issues 

#563
#554
#553
#535
#864
#790
#894
#955 
#993 

## Cases to handle

- Casing e.g. PascalCase, dash-case, snake_case ...
- Paths e.g. `C:\..` (windows) `home/...` (unix)

## Release plan 

The release plan for this feature is in three parts:
- Integration of the script segmenter in place of the current tokenizer, with the current tokenizer as a fallback. 
- Integration for Chinese, Japanese and Korean to the script segmenter.
- Iterative addition of new Tokenizers.

**Comment by xcaptain** [comment]
How about making tokenizer an interface so people can choose a tokenizer from config file like elastic search does. https://www.elastic.co/guide/en/elasticsearch/reference/7.6/analysis-tokenizers.html

**Comment by MarinPostma** [comment]
@xcaptain we have that in mind for a later time. It would indeed be rather easy to implement on top of the new tokenizer. But for now, our goal is just to enhance what's existing without adding configuration on the user's end.

**Comment by xcaptain** [comment]
I also hate configurations, would be great to auto detect language and tokenize the input. So the hard part is to segment the input by language and then use different tokenizer to parse those segments into tokens right?

**Comment by MarinPostma** [comment]
yep, that's right, I already have a prototype that does just that. Although, it detects script rather than language per se. One good first configuration we could make  available would be to specify a default tokenizer for Latin script, other than english. Detecting language is very slow, whereas detecting script can be done efficiently, and it is already a decent improvement to a straightforward tokenizer. We could consider adding automatic language detection later too (through [whatlang](https://github.com/greyblake/whatlang-rs) for example), as a opt-in feature though, because the performance hit is too bad.

**Comment by jet10000** [comment]
It’s great to go further.

Can you consider provide a programming interface for word segmentation, such as obtaining word segmentation through http api? Algorithm-based word segmentation is far from enough for cjk.

**Comment by MarinPostma** [comment]
@jet10000, can you explain what you have in mind?

**Comment by jet10000** [comment]
Expose the structure model of the document. I use a third-party service (some cloud word segmentation services) to construct the result of word segmentation into the document structure and input it into meilisearch for query. Somewhat similar to tsvector and tsquery of postgresql.
