### ISSUE TITLE
Documentation for Facet filters

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#632]
While Facet filters are being developed (#625), we need to work on it's documentation. If anyone is seeking for a good first contribution, I could use some help on this.

**Comment by abankalarm** [comment]
will do this

**Comment by MarinPostma** [comment]
Amazing! Ping me on slack

**Comment by MarinPostma** [comment]
closed by https://github.com/meilisearch/documentation/pull/360

**Comment by willvincent** [comment]
#360 isn't merged yet, so this probably shouldn't be closed

**Comment by MarinPostma** [comment]
It's being worked on by a member of our team, I'm closing the call for participation.
