### ISSUE TITLE
Error "There is not enough space on the disk" on Windows x64

### ISSUE THREAD

**Issue by Wazner** [meilisearch/MeiliSearch#643]
## Error
I'm getting the following error when running MeiliSearch on a Windows Server 2019 x64:
```
Zlmdb(Io(Os { code: 112, kind: Other, message: "There is not enough space on the disk." }))
```

I traced the source of the error to the following call stack:
```
1. heed::EnvOpenOptions::open(path)
2. meilisearch_core::Database::open_or_create(path)
```

Is this expected behaviour, should the server have 200 gigs of storage space to be able to run MeiliSearch?

## Platform
OS: Windows Server 2019
Crate version: master branch
Note: I'm using meilisearch as an embedded database by referencing the meilisearch-core crate directly from github.

## Workaround
I managed to circumvent the error by commenting out the call to `map_size` on the `EnvOpenOptions` in `database.rs`.
https://github.com/meilisearch/MeiliSearch/blob/899559a060aff9051cfc34b187b7a74f8c71c18d/meilisearch-core/src/database.rs#L144-L153

**Comment by Kerollmops** [comment]
Hey @Wazner,

This is a known issue of MeiliSearch and especially of LMDB on Windows, Windows does hard reserve the memory mapper disk space when unix system does only auto-growth to the specified size and stop growing when the limit is reached.

I talked about a better solution for Windows users in #645.

**Comment by Wazner** [comment]
> Hey @Wazner,
> 
> This is a known issue of MeiliSearch and especially of LMDB on Windows, Windows does hard reserve the memory mapper disk space when unix system does only auto-growth to the specified size and stop growing when the limit is reached.
> 
> I talked about a better solution for Windows users in #645.
Thank you for your swift reply. I will create a new PR with your suggested changes once I find the time for it.

> This call to `map_size` is mandatory
After some testing i found out it defaults to 1Mb instead of auto growing. I get `MDB_MAP_FULL: Environment mapsize limit reached` after adding larger documents.
The very small database size confused me, thinking it would autogrow.
