### ISSUE TITLE
Error  with forked repo without changes.

### ISSUE THREAD

**Issue by carlosb1** [meilisearch/MeiliSearch#653]
Hi,
these last days I has been  working with meilisearch to index information and links from Internet... It works perfectly when I run the docker (compiled) image but I can not use a  forked version (no modified) from this repo... I only forked it a few days ago and I ran `cargo run --release`. But when I execute the index command: 

```
⇒  curl -i -X POST 'http://127.0.0.1:7700/indexes' --data '{ "name": "Movies", "uid": "movies" }'
HTTP/1.1 400 Bad Request
content-length: 0
date: Sun, 03 May 2020 14:31:31 GMT
```
It doesn t work... it is curious, it is the same command that it works with the docker image... I have tired different things: remove caches, rebuilding, remove data.ms, run from docker or cargo... but same result... I will appreciate any help, the only reply that I receive from meilisearch:

`[2020-05-03T14:31:31Z INFO  actix_web::middleware::logger] 127.0.0.1:50760 "POST /indexes HTTP/1.1" 400 0 "-" "curl/7.58.0" 0.000170
`

**Comment by Kerollmops** [comment]
Hey @carlosb1,

It seems like it is related to our switch to the actix web framework, we will look into this with @qdequele next week. I advise you to use the commit of a release (i.e. [`v0.10.1`](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.10.1)).

Thank you for the report!

**Comment by qdequele** [comment]
Hello @carlosb1. Don't forget to add the Header to say that you're sending json body. 
`curl -i -X POST 'http://127.0.0.1:7700/indexes' -H "Content-Type: application/json" --data '{ "name": "Movies", "uid": "movies" }'`

**Comment by carlosb1** [comment]
Thanks! it works with the v0.10.1 I will use it temporally. thanks for the fast feedback

**Comment by Kerollmops** [comment]
@carlosb1 Did you try [the quentin's response](https://github.com/meilisearch/MeiliSearch/issues/653#issuecomment-623140736)? Does it work?

**Comment by carlosb1** [comment]
@Kerollmops  I didn t need to include -H in the curl command... Directly, I changed branch... I can try to use master and the json flag if I have a gap.
 Another point.. take care because it is not specified in the README.md that it is necessary to these header parameter.... (If you need for some MR, not problem)
