### ISSUE TITLE
Improve test suite speed

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#655]
Right now, the integration test use the movie dataset. This is an issue because this dataset is unnessecarily big for testing purpose and thus drastically slows down running the test suite. I suggest we use a smaller dataset (< 100 entries) to improve our CI time.

**Comment by balajisivaraman** [comment]
@MarinPostma, If no one else has picked this up, I'll give it a shot. :+1:

**Comment by MarinPostma** [comment]
@balajisivaraman awesome!

I have added a [test dataset](https://github.com/meilisearch/MeiliSearch/tree/master/meilisearch-http/tests/assets) on master, that I have [used here](https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/tests/search.rs#L1298) for reference. With @Kerollmops we also discussed about making search queries more readable in tests, and I think [serde-url-params](https://github.com/boxdot/serde-url-params-rs) could be very handy, I fiddled a bit with it and it does the job. This is plenty of work, and I don't expect you to do it all, so it would be awsome if you did this in mergeable units, i.e one commit per test, so someone can continue where you leave it :) . Do not hesitate to ping me on slack if you need help

**Comment by balajisivaraman** [comment]
@MarinPostma, Great! Thanks for the getting started tips. I'll do the commits it like you suggested. :+1:
