### ISSUE TITLE
Synonyms not functioning as expected

### ISSUE THREAD

**Issue by captbrogers** [meilisearch/MeiliSearch#656]
kero asked me to open this issue. I have narrowed down the data set to the four users in question.

I'm trying to get synonyms working for locations. [Here is a link](https://gist.github.com/captbrogers/ad0b57f0f7a065da8982fcec165c756b) to the gist of sample data, and [here is the link](https://gist.github.com/captbrogers/46df58154ff5c30d72e71db909a8d822) to the gist of the commands I run on the server to set up the index.

The problem: I have a list of users that get loaded into the index. They have three attributes I'd like to search against; city, state, and country. I attempted to set up synonyms so that a shortened form of the state can be used, in this case "Hawaii" and "HI". When I search for 'Hawaii' I get three of the four users. When I search 'HI', I will get the fourth user only.

Here is the output of the version call:
```
{
  "commitSha": "UNKNOWN",
  "buildDate": "2020-04-28T14:24:39.310841928+00:00",
  "pkgVersion": "0.10.1"
}
```

Using the updates endpoint, all of the updates I used in the gist above reported as processed, no errors.

**Comment by qdequele** [comment]
@MarinPostma, What is the status of this issue, could we close it?

**Comment by captbrogers** [comment]
Yes, I believe an update has resolved this issue.
