### ISSUE TITLE
Get last updated/created document

### ISSUE THREAD

**Issue by baskin** [meilisearch/MeiliSearch#666]
Hi Team,
Just started experimenting with the project. Loving it so far!

Is there a way to determine the last created/updated document? I'm trying to build a quick job that keeps my db in sync with `meilisearch`. Previously, where I was using `algolia`, I depended on an `aloglia` api that deterministically returned the last updated/created document in an index. A field `created_at` in my document would then point towards how far back I needed to go in my DB in order to determine new documents to sync. 

I couldn't find a similar api in `meilisearch`. 
e.g. Documents returned by [get documents](https://docs.meilisearch.com/references/documents.html#get-documents) are ordered by their hashes.

**Comment by qdequele** [comment]
With feature #346 (in the roadmap for this quarter). You will able to make a search without query parameters and with custom ranking/filters you want. So, I think it could solve your issue.

**Comment by baskin** [comment]
Ok. Thanks. I'll sub to https://github.com/meilisearch/MeiliSearch/issues/346
