### ISSUE TITLE
Why don't have a rust api for meilisearch

### ISSUE THREAD

**Issue by NOVA-ME** [meilisearch/MeiliSearch#668]
I think that we maybe need a api for rust

**Comment by erlend-sh** [comment]
It has been started by @mubelotix here: https://github.com/Mubelotix/meilisearch-sdk

**Comment by Mubelotix** [comment]
Yes and it's almost finished but some things can still be improved.
I am currently working on wasm support.

**Comment by NOVA-ME** [comment]
@Mubelotix  I love the words you say: Rust is conquering the world, and so thank you for your [crate](https://github.com/Mubelotix/meilisearch-sdk).It's very useful.And I'm following you now.
