### ISSUE TITLE
timezone config

### ISSUE THREAD

**Issue by zTgx** [meilisearch/MeiliSearch#670]
Is there a way to config timezone? Utc or Local.
for example:
created_at/updated_at fields in IndexResponse.
```
struct IndexResponse {
    name: String,
    uid: String,
    created_at: DateTime<Utc>,
    updated_at: DateTime<Utc>,
    primary_key: Option<String>,
}
```

**Comment by Kerollmops** [comment]
Hey @zTgx,

MeiliSearch doesn't understand timezone at all, it only nows about numbers.
If you want to use a datetime in MeiliSearch for custom ranking (i.e `desc(created_at)`) you must transform it into a  number like [an unix timestamp](https://en.wikipedia.org/wiki/Unix_time) for example.
