### ISSUE TITLE
subscribing to query

### ISSUE THREAD

**Issue by anotherjesse** [meilisearch/MeiliSearch#671]
Any thoughts to having a subscription to a query - for instance getting live updates to your query when new documents are indexed that change the results?

This would allow a similar experience to google firestore "onSnapshot" where a frontend can subscribe to a query and have an up-to-date response results list without having to continually poll the server

**Comment by MarinPostma** [comment]
Hey,
We've decided not to implement this feature, this is not really what Meili is made for. We may reconsider if there is enough traction, so feel free to comment, cheers!

**Comment by anotherjesse** [comment]
Whoa. Thanks for the update!
