### ISSUE TITLE
MDB_CORRUPTED

### ISSUE THREAD

**Issue by zTgx** [meilisearch/MeiliSearch#672]
platform: WSL

create_index :
```
curl -i -X POST 'http://127.0.0.1:7700/indexes' -H "Content-Type: application/json" --data '{ "name": "Movies", "uid": "movies" }'
```
And response:
```
HTTP/1.1 400 Bad Request
content-length: 96
content-type: application/json
date: Mon, 11 May 2020 10:20:34 GMT

{"message":"Impossible to create index; heed error; MDB_CORRUPTED: Located page was wrong type"}
```

**Comment by Kerollmops** [comment]
Yeah, we must add somewhere on the README that we have an issue on Windows Subsystem for Linux. We can't debug that as we don't have access to this OS right now.

**Comment by MarinPostma** [comment]
So there simply is no support for WSL?

**Comment by MarinPostma** [comment]
We don't plan to support WSL in the future, as this is not a production environment. We support compiling  on windows if you want to work with MeiliSearch on Windows :)
