### ISSUE TITLE
Change ranking/sorting in the search request

### ISSUE THREAD

**Issue by unknownhasher** [meilisearch/MeiliSearch#673]
Hi Meili,

Currently, if i want to change the ranking of the index search i have to post to /settings/ranking-rules the rules of rankings. For example:
`"typo", "words", "proximity", "attribute", "wordsPosition", "exactness", "desc(id)"`

In the tool where i'm using MeiliSearch to build a result list (with filtering and textsearch). I want to add the option for users to change the sort for just one search query, and not for the entire index. (of the last element (desc(id)). So i can add a ranking-rule to the options that are send with the search request. 

It would be nice to have that extra functionality.

**Comment by Kerollmops** [comment]
Hey @unknownhasher,

Yeah this is something we have in mind: allow the user to change the criteria at query time.
I don't know if we will allow the user to set the whole list of criteria or only the custom ones (i.e. `desc(id)`), this can impact the performances too much.

If you want to let the user search for `desc(id)` or `asc(id)` at query time the solution I see **for now** is to have two indexes with the same documents but different custom ranking rules.

**Comment by jiminy-billy-bob** [comment]
I agree that this would be very useful.

We are building a marketplace. Allowing users to specify ascending and descending sorting on custom criteria is critical.
For example in our use-case, sorting by: price, popularity, name, date, file size, etc...

**Comment by Kerollmops** [comment]
Hey,

Closing in favor of #730, you can follow the racking issue now!
