### ISSUE TITLE
Add ability to set maximum payload size

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#682]
Currently the maximum payload size is set to 10mb. We want to allow the user to override this setting to an arbitrary value, thanks to  a command line argument

proposed argument name: `max-payload-size`

**Comment by Kerollmops** [comment]
Could we use a more explicit name like `http-body-limit` or `http-payload-limit`?

**Comment by MarinPostma** [comment]
Yes sir. I opt for `http-payload-size-limit`, as limit only suggests more of a quantity than an amount.

**Comment by bidoubiwa** [comment]
@MarinPostma 
This should be documented here: https://docs.meilisearch.com/guides/advanced_guides/installation.html#environment-variables-and-flags
