### ISSUE TITLE
Sort on Documents endpoint doesn't apply

### ISSUE THREAD

**Issue by imagineimpact** [meilisearch/MeiliSearch#686]
It would seem sort ranking only applies to search. Is there a way to order the documents index endpoint? Also, will it be possible in the future to sort by non-numeric values? Right now we're resorting to Buffer.from(name).readUInt32BE() in order to sort by name and are combining this with a wildcard search for a faux-index capability (q=[*] & all entries have an index over bracket wrapped tags with `[*]` globally seeded).

**Comment by Kerollmops** [comment]
Hey @imagineimpact,

> Is there a way to order the documents index endpoint?
Are ou talking about sorting the documents by the custom ranking rules you set in the settings? If so, then yes this is in the roadmap, you can follow [the tracking issue](https://github.com/meilisearch/MeiliSearch/issues/346) to keep beinging updated.

> Also, will it be possible in the future to sort by non-numeric values? Right now we're resorting to Buffer.from(name).readUInt32BE() in order to sort by name [...]
I am not sure I understand correctly but if your are using `readUInt32BE` it means that `name` is a number in fact, no? Also this really time consumming to sort documents by non numeric values like strings, lexicographic sort means that we need to compare each strings between others, byte by byte until one win. This is not planned and will probably be never be possible.

> and are combining this with a wildcard search for a faux-index capability (q=[*] & all entries have an index over bracket wrapped tags with [*] globally seeded).
I am not sure I understand this part correctly.

**Comment by MarinPostma** [comment]
close in favor of #730
