### ISSUE TITLE
Interface for installer and production configuration

### ISSUE THREAD

**Issue by erlend-sh** [meilisearch/MeiliSearch#698]
> @eskombro:
> 
> Would it be interesting to have a simple interface to configure production environment (domain name, SSL/TLS, proxy/nginx...)?

It would indeed! We need something basically the same as the [WordPress config page](https://wordpress.org/support/article/how-to-install-wordpress/#setup-configuration-file).

![image](https://user-images.githubusercontent.com/583842/82290275-cf507980-99a6-11ea-984c-45bb1491ed58.png)

**Comment by eskombro** [comment]
This is something that can add huge value for users, making MeiliSearch more and more accessible. The tools we have been working on in the back-end side to automate the production deployment and configuration will certainly serve us! I think that the most important need in that field would be the front-end work, which would be totally new and I guess starting from scratch, but I can absolutely work in any prototype/idea to make that possible!  As for now, we have automated tools, but running servers and accessing them through SSH is already a constraint that many people will never try / want to overcome. It is our job to make it as simple as we can :)

**Comment by erlend-sh** [comment]
- What installers will we model this after? Is there any prior art that maps on to our specs even better than WordPress?

- Where do we draw the line on UI for production configuration? At some point it’s just fair to require production runners to resort to the terminal.

- We want this to work both locally and in the cloud, right?

- Maybe this is out of scope for the MVP, but is it a reasonable end-goal that I should be able to install MeiliSearch locally with zero terminal interaction?
