### ISSUE TITLE
HttpClient

### ISSUE THREAD

**Issue by mjl4043** [meilisearch/MeiliSearch#701]
I was trying to make a http request in java 11 using HttpRequest to create index for meilisearch.
jdk-oracle java11

curl command: curl -i -X POST 'http://localhost:7700/indexes' --data '{ "name": "xyz", "uid": "abc", "type": "user"}'
 How can i pass the --data field arguments through the same?

**Comment by Kerollmops** [comment]
Hey @mjl4043,

I am sorry but I can't help you more for this, I don't know Java at all but maybe @ppamorim can?

I find out that you can send [a body with the `POST` method and a `BodyPublishers` type](https://openjdk.java.net/groups/net/httpclient/recipes.html#post) but not sure if it is the same in Java 11.
