### ISSUE TITLE
Private/public keys for a specific index

### ISSUE THREAD

**Issue by eskombro** [meilisearch/MeiliSearch#709]
Would it be possible to implement the creation of private/public API keys giving access to a single index?

Rights and permissions right now are handled only for the whole MeilISearch instance. It may be interesting to have different access keys to different indexes inside a single MeilISearch instance, to give users a more detailed, fine and controlled access to their data

**Comment by qdequele** [comment]
Duplicate and subset of https://github.com/meilisearch/MeiliSearch/issues/421
