### ISSUE TITLE
Json data in index

### ISSUE THREAD

**Issue by mjl4043** [meilisearch/MeiliSearch#710]
I was trying to upload a json file to an index.

I used the following command- 
curl -i -X POST 'localhost:7700/indexes/mredul/documents' --header 'Content-Type: application/json' --data-binary @sample.json

sample.json
{
    "firstName": "Rack",
    "lastName": "jackson",
    "gender": "man",
    "age": 24,
    "address": {
        "streetAddress": "126 Udhna",
        "city": "san jone",
        "state": "CA",
        "postalCode": "394221"
    },
    "phoneNumbers": [
        { "type": "home", "number": "7383627627" }
    ]
}

It is showing error 400 bad request. What can i do to eradicate this?

**Comment by eskombro** [comment]
Hi @mjl4043 

First of all, try sending your document inside an array:

```json
[
  {
    "firstName": "Rack",
    "lastName": "jackson",
    "gender": "man",
    "age": 24,
    "address": {
      "streetAddress": "126 Udhna",
      "city": "san jone",
      "state": "CA",
      "postalCode": "394221"
    },
    "phoneNumbers": [
      { "type": "home", "number": "7383627627" }
    ]
  }
]
```

Also, MeiliSearch probably won't be able to infer which is the primary key from your document.  If you need more info about it, check [this link](https://docs.meilisearch.com/guides/main_concepts/documents.html#primary-key)
