### ISSUE TITLE
GET /indexes/:index_uid/documents denied with Public Key

### ISSUE THREAD

**Issue by jiminy-billy-bob** [meilisearch/MeiliSearch#717]
According to the [documentation](https://docs.meilisearch.com/guides/advanced_guides/authentication.html), with the Public Key we can access these routes:
```
GET /indexes/:index_uid/search
GET /indexes/:index_uid/documents
GET /indexes/:index_uid/documents/:doc_id
```

With my Public Key, I can access `GET /indexes/:index_uid/search` and `GET /indexes/:index_uid/documents/:doc_id` just fine, but `GET /indexes/:index_uid/documents` returns `Invalid API key`.
It works fine when using my Private Key or Master Key.

Am I doing something wrong?
Is there some setting to enable to make this work?

I'm running v0.10.1.

**Comment by curquiza** [comment]
Hello @jiminy-billy-bob !
I succeeded to reproduce the issue.
According to [the docs](https://docs.meilisearch.com/guides/advanced_guides/authentication.html#authentication), you indeed should be able to retrieve documents via the route `GET /indexes/:index_uid/documents` with your public key.
This will be fixed 😉

**Comment by jiminy-billy-bob** [comment]
On second thoughts, I'm wondering if it would be a good idea, actually.

Because according to [the docs](https://docs.meilisearch.com/guides/advanced_guides/field_properties.html#displayed-fields), the `/documents` route returns all fields, even those excluded from `displayedAttributes`.
Is this a good thing? It means we can't store private fields in documents, because they will be publicly visible via the `/documents` route.

**Comment by curquiza** [comment]
> Because according to the docs, the /documents route returns all fields, even those excluded from displayedAttributes.

I guess you talk about this paragraph:
```
Therefore, if a field attribute is not in the displayed-attribute list, the field won't be added to the documents returned upon search. Nevertheless, the documents fetched using the GET /documents route will have those fields, this setting only affects the document hits upon search.
```

I've just tested and only the displayed attributes are displayed with the `GET /documents`, not all the fields as the docs say.

So I invoke @bidoubiwa for the docs and @Kerollmops for the core-engine 🐉

> Is this a good thing? It means we can't store private fields in documents, because they will be publicly visible via the /documents route.

Invoking @Kerollmops again 🙂

**Comment by bidoubiwa** [comment]
If `get /documents` does not return fields that are not in the `displayedAttribute` it should be corrected in the documentation.

If `get /documents` is not accessible with the public key, is there another way for public user to have a sample of documents without doing a specific search? This is useful when displaying random documents before a search

**Comment by curquiza** [comment]
I've just tested on `master`:
- The `GET /documents` routes is accessible with the public key 🙂
- The issue with the displayed attributes is still there (I mean, it's not according to the docs)

**Comment by Kerollmops** [comment]
Hey @curquiza and @jiminy-billy-bob,

The engine will never show fields that are not listed in the `displayedAttribute` setting, never ever, don't worry, you can store private data inside of the attributes that are not in the `displayedAttribute` setting :)

The issue you have spotted about not being able to reach the `documents/` route is fixed master and will be available in the v11 of the engine and will be released in probably less than a week now 💯 

Thank you for the report!

**Comment by curquiza** [comment]
> The engine will never show fields that are not listed in the displayedAttributes setting, never ever, don't worry, you can store private data inside of the attributes that are not in the displayedAttributes setting :)

So, the docs need to be updated @bidoubiwa

**Comment by jiminy-billy-bob** [comment]
> The engine will never show fields that are not listed in the displayedAttributes setting, never ever, don't worry, you can store private data inside of the attributes that are not in the displayedAttributes setting :)

That's good to hear!

Thanks for the quick fix! Although for now the `/documents` route is actually not very useful to our use-case, as we need to apply filters even when querying without any search term (our content is categorized).
It would be good to either:
- have `filters` and `attributesToRetrieve` available on the `/documents` route
- allow to get all documents by hitting the `/search` route with an empty query string (already requested in #346 )

**Comment by MarinPostma** [comment]
@jiminy-billy-bob #771 should fix your problem once it's merged :)
closing
