### ISSUE TITLE
Allow empty query string

### ISSUE THREAD

**Issue by jtmiclat** [meilisearch/MeiliSearch#724]
Hi! First off thanks for a wonderful search engine! 

I am wondering if it would be possible to search with an empty string and only use other fields like `limit` and `filters`. I tried running the following query but results returned no hits.

```sh
$ curl --get 'http://127.0.0.1:7700/indexes/movies/search' \ 
   --data-urlencode 'q='  \
   --data-urlencode 'filters=release_date > 795484800'
# {"hits":[],"offset":0,"limit":20,"nbHits":0,"exhaustiveNbHits":false,"processingTimeMs":1,"query":""}%    
```
My use case is having filters on search component and show some results before even typing anything.

**Comment by Kerollmops** [comment]
Hey @jtmiclat,

This is something we have in mind and will release in a next release for sure, this is in the roadmap and you can follow this [on the dedicated issue](https://github.com/meilisearch/MeiliSearch/issues/346).

Thank you for your interrest in the project :)

**Comment by jtmiclat** [comment]
Wonderful! Thanks!
