### ISSUE TITLE
Pass API KEY in query parameters instead of header?

### ISSUE THREAD

**Issue by jiminy-billy-bob** [meilisearch/MeiliSearch#727]
Currently the API KEY must be passed in the request header.
This seems the logical way to do it. But there might be some performance issue with this.

When sending requests to MeiliSearch from the browser, a preflight `OPTIONS` request is sent before the actual `GET` request, because of the presence of the `x-meili-api-key` header.
This means that two requests are sent to the server, the second one waiting for the first one to come back. This essentially double the time it takes between triggering the search request and getting the results.
I have a 150-200ms ping between my machine and my MeiliSearch server, the search results actually arrive 300-400ms later! The difference is significant, especially for a search-as-you-type experience.

The solution would be to make [simple requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests), which means no custom headers. The API key would be passed as a query parameter.

What do you guys think?

I'm no HTTP expert, I randomly stumbled upon this while struggling with some CORS issues, so I might be interpreting things the wrong way. Please correct me if I'm mistaken.

**Comment by MarinPostma** [comment]
I'm definitely not an HTTP expert either, but if I understand right what you say, using the basic authorization header would solved this problem?

```
 'authorization: Basic my_key'
```

I remember that we had discussions about this, but I don't remember what we said about this. It's an interesting topic to investigate in any case!

**Comment by jiminy-billy-bob** [comment]
> using the basic authorization header would solved this problem?

No, it looks like it would not solve this problem.
The "Authorization" header is not in [this list](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests). It is even explicitly said a bit lower on the same page:
> However, if the request is one that triggers a preflight due to the presence of the Authorization header in the request, ...

**Comment by MarinPostma** [comment]
Thanks for that information, we're discussing a solution.

**Comment by MarinPostma** [comment]
closing as #735 solves the problem
