### ISSUE TITLE
Customizable processing time limit when searching

### ISSUE THREAD

**Issue by mikerogerz** [meilisearch/MeiliSearch#728]
Testing instant search (docs-searchbar), and getting into extremely long queries which increase with each query (specifically multiple copy-pasted strings purposely with no results). There doesn't seem to be any max processing time, where I've seen some queries run up to 217s. Normally this could be circumvented at the proxy level with rate limiting, but it wouldn't help to save the server load for each request as they build up and overload the resources of the server.

Would it be possible to add some sort of timeout option for searches? During testing it was eventually necessary to kill the Meilisearch process.

`[2020-05-28T13:22:25Z INFO  tide::middleware::logger] GET /indexes/landing_articles/search 200 2362ms`
`[2020-05-28T13:22:33Z INFO  tide::middleware::logger] GET /indexes/landing_articles/search 200 9834ms`
`[2020-05-28T13:23:15Z INFO  tide::middleware::logger] GET /indexes/landing_articles/search 200 51579ms`
`[2020-05-28T13:25:55Z INFO  tide::middleware::logger] GET /indexes/landing_articles/search 200 211371ms`
`[2020-05-28T13:29:33Z INFO  tide::middleware::logger] GET /indexes/landing_articles/search 200 217961ms`

**Comment by Kerollmops** [comment]
Hey @mikerogerz,

Aborting requests can be a little bot hard to handle, but one thing that can be done kind of easily is restricting the number of query words that are processed and used for the index search.

IIRC Algolia limits the number of query words to 10, we cold do the same, what do you think?

**Comment by mikerogerz** [comment]
I think that sounds like a good solution. Not sure whether you would want it to be a configuration option or not. But I think something is necessary, if a long query is able to kill the server so easily.

This doesn't affect the server-side libraries as much since it can be controlled, but for client-facing it could be a big problem.

**Comment by gmourier** [comment]
Closed because `q` is now limited to 10 terms to limit long query processing.
