### ISSUE TITLE
Tracking issue: Placeholder search or a search without query parameters

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#729]
This feature will be helpful for ecommerce websites or any kind of website that needs to display documents without specifying any search query. The displayed documents are sorted by the custom criteria specified in the settings when the query parameter is empty or not present at all (i.e `/search?q=` or `/search`).

[The `sortBy` feature](https://github.com/meilisearch/MeiliSearch/issues/730) will not be supported by placeholders, but we will eventually support it.

### What do we do at indexing time?

  1. Retrieve the custom ranking criteria in the order specified in the settings.
      If the settings contains `typo, words, asc(price), desc(time), proximity` the custom criteria that we will use are `asc(price)` and `desc(time)` in this specific order.
  2. Sort all the documents ids by the custom criteria.
  3. Store those ids in the key-value store ~and keep the deepest buckets bounds~.

### At query time with default search settings

We must use the cached documents ids and return the documents lying between the bounds requested (the result page).

### At query time with facets filters

  1. We compute the intersections and unions of the facets filters documents ids.
  2. Compute the scores of this restricted list of ids using the customs criteria defined in the settings.

**Comment by MarinPostma** [comment]
Should we allow filtering?

**Comment by jiminy-billy-bob** [comment]
Yes I think filtering and faceting are essential.
It is for our use-case, anyway.

**Comment by MarinPostma** [comment]
This could be very slow, maybe something like #728 would help

**Comment by Kerollmops** [comment]
Hey,

Yeah we need to support filetring on placeholders even if we can have performances issues.
We will improve that in futur work.

**Comment by Bajix** [comment]
The current way I handle this on production is to give have an indexed field `terms: ["[*]", "[...]"...]` with a default query `q=[*]` to match all documents. Instead of using `filters`, we create a query in the format of `q=[foo] [bar] myquery`, but it would be nice to be able to write this to leverage filters and an optional query.

The one thing I wonder about this though, perhaps should we update the functionality of the Documents index in order to support `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, and `filters` but to omit `q`, `attributesToHighlight` and `matches`? That way we can have a filterable index that's maybe faster by virtue of lacking querying capabilities.

**Comment by MarinPostma** [comment]
> The one thing I wonder about this though, perhaps should we update the functionality of the Documents index

We actually want to return documents sorted in the order specified in the `rankingRules` setting. It is more efficient to cache a sorted list of document_ids at indexing and piggy-back on a standard search for filtering, faceting etc.

**Comment by bidoubiwa** [comment]
Is it possible to create some curl examples to showcase the usage and the limitation?

**Comment by MarinPostma** [comment]
sure, working on it.

**Comment by stephanoparaskeva** [comment]
> sure, working on it.

Is there any way to make this refreshable. I'm using Meili on ReactNative and want to let client pull to refresh for user search?

**Comment by MarinPostma** [comment]
I'm not sure to understand what you want to do, can you elaborate?

**Comment by stephanoparaskeva** [comment]
> I'm not sure to understand what you want to do, can you elaborate?

### *Perhaps something like so:*

#### Scenario 1
- User loads app, they are presented with empty search bar, they also see a list of all users. The list would be infinite scroll.

- User moves to other tabs and comes back to search tab. The same list exists as there has been no additional calls to MeiliSearch API. 

- They don't want to search anything yet so they drag the page down. This causes a loading wheel at the top (implemented).

- When this finishes loading, the user list is updated. Perhaps new users had registered or the values in the ranked orders have changed.

#### Scenario 2
- This is the same as scenario 1, the user first sees a list of other users.

- The User then searches in the search bar and see some results.

- After some time the user wants to keep the search in the search bar but reload the searches again, the user drags down the screen and sees the same scroll wheel.

- Now the queried search (not search for all users, but search with same terms) is reloaded and the new list (changed or unchanged) is presented.

**Comment by MarinPostma** [comment]
Yes yes, this works, just make  a new call to refresh, the placeholder queries are fast :)
