### ISSUE TITLE
Tracking issue: SortBy at query time

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#730]
The `SortBy` feature is something that will help e-commerce websites or any website that needs to display documents in an order that depends on the user front-end settings, therefore at query time. This can be useful when you want the user to be able to choose if he want to see documents by ascending or descending price for example.

For that we will add two settings:
  - The `sortableAttributes` field to the settings, this way the engine is aware of the fields that it needs to index like numbers, etc...
  - The `sortBy` field to the search query parameters, it contains the name of one of the sortable attribute you defined in the settings and will be used as the last sorting criterion.

## How Algolia handles that

[Algolia uses replicas to handle this kind of custom search](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/search-in-a-replica-index/), for each of the custom sortable attributes you want to have, [the tools of Algolia creates replicas of your main index](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/use-sorting-ui-widget/) and changes the settings.

When a search query with custom sorting rules is performed, the front-end tools will request the right index. This index is named based on the rules you changed e.g. "movies_asc(price)_desc(released_at)".

Notice that you pay for all the replicas you have and all documents that are in any index count, it means if your plan allows you to have 10k documents but you have one replica, therefore you can only have 5k documents.

**Comment by MarinPostma** [comment]
Do really need to create multiple indexes? Right now, criteria are built at search time. The only place where we actually need a sorted document cache is for placeholder search, for which we need to cache sorted document_ids. What I am not completely sure about is how do we compose sorts. Should we allow sort by asc(foo) and desc(bar) for example? Should these case be specified in the `sortableAttributes` setting?

**Comment by MarinPostma** [comment]
I am thinking of a `SortStrategies` settings, that maps strategy names to set of ranking rules. The `sortBy` search parameter accepts a sort strategy. WDYT @Kerollmops @curquiza @bidoubiwa @eskombro

**Comment by jiminy-billy-bob** [comment]
So we would have to know in advance every possible sort filter combinations?

**Comment by MarinPostma** [comment]
yeah this seems necessary to perform efficient sorting...

**Comment by MarinPostma** [comment]
also if i'm not mistaken, we need a `ranked_map` for each sorting strategy, is that right @Kerollmops

**Comment by jiminy-billy-bob** [comment]
Okay, it's not ideal from a usage POV, but it's still usable. So it sounds like a good compromise.

**Comment by curquiza** [comment]
Is `sortStrategies` a replace name for the `sortableAttributes` suggestion of @Kerollmops or another settings?

**Comment by MarinPostma** [comment]
replacement, Algolia call them sorting strategies, and I think it makes more sense when you sort according to multiple criteria at the same time

**Comment by curquiza** [comment]
I think:
- `sortStrategies` is better if you set this kind of infomation:
```bash
{
    price_asc": [ typo, asc(price) ],
    ...
},
```
- `sortableAttributes` is better if you can only set this kind of information:
```bash
[price,  ...]
```

**Comment by MarinPostma** [comment]
How do you specify the other rules in this case?

**Comment by MarinPostma** [comment]
Ah yes I get what you mean, but we can't support placeholder search if we do that

**Comment by curquiza** [comment]
When I read the @Kerollmops issue description:

> The sortableAttributes field to the settings, this way the engine is aware of the fields that it needs to index like numbers, etc..

I'm not sure to really understand what you expect, so, I thought about an array of string with attributes names, but I was not sure at all 😅

**Comment by Kerollmops** [comment]
> Do really need to create multiple indexes?

No we don't we we do is adding a new setting where we list all of the attributes we use for the `sortBy` feature. This way the engine will create a ranked map for all of the listed attributes.

```
"sortableAttributes" : ["price", "createdAt"]
```

> Right now, criteria are built at search time.

Yeah, but the ranking rules are already known by the engine, therefore the ranked map have already been created for all of the criteria i.e. `asc(price)`.

> Should we allow sort by `asc(foo)` and `desc(bar)` for example? Should these case be specified in the `sortableAttributes` setting?

I want to support combined sort startegies but @qdequele didn't thought it was useful.

------

> also if i'm not mistaken, we need a ranked_map for each sorting strategy, is that right

@marin we have a ranked map by attribute that is used in any criterion, not a ranked map by criterion.

-----

**Comment by MarinPostma** [comment]
@Kerollmops we also keep a sorted list of doctors for every attributes then for placeholder search

**Comment by MarinPostma** [comment]
How does that mix with existing ranking rules?

**Comment by qdequele** [comment]
@Kerollmops I think we can easily do both by declaring in settings the:
`sortableAttributes: ["time", "price"]`

**Comment by MarinPostma** [comment]
This is not possible with placeholder search

**Comment by jiminy-billy-bob** [comment]
Any ETA on this?
I'm considering building a temporary solution with duplicated indexes, but if this feature is due soon I will avoid the extra work and just wait.

**Comment by paligiannis** [comment]
do we have any news on issue?

**Comment by gmourier** [comment]
Hello @paligiannis! This is an actively requested feature by our users, we will start working on it for releases coming after 0.21. I can't give an exact date but I will push this feature for our next iterations. We still need to define how far we want to go with the sortBy.

**Comment by paligiannis** [comment]
@gmourier thanks for the reply. I would be interested if I could help in research or anything, please let me know.

**Comment by gmourier** [comment]
Thanks @paligiannis!

**Comment by ppamorim** [comment]
Any news on this matter? We have been looking in ways to order our data using multiple integer fields.

**Comment by curquiza** [comment]
Hello @ppamorim, @gmourier answered about this less than 2 weeks ago in this issue 😉 https://github.com/meilisearch/MeiliSearch/issues/730#issuecomment-846997793
It's complicated for us to give an exact release date, but be sure it's in our roadmap.

**Comment by bmpf** [comment]
Filters : show document by true or false, example : product in stock = true , product has promo = false ; 
Thank you @ppamorim ,

**Comment by curquiza** [comment]
Closed in favor of a future tracking issue coming soon! :)

**Comment by VivianSolide** [comment]
It would have been nice to get the new issue link before closing this one.
Hope you will keep us updated.

**Comment by curquiza** [comment]
We don't have any tracking issue ready yet, but here is most of the work done by our PM on it https://github.com/meilisearch/product/issues/43

**Comment by curquiza** [comment]
Here is the new one: https://github.com/meilisearch/MeiliSearch/issues/1581
