### ISSUE TITLE
Build fails on FreeBSD/ HardenedBSD

### ISSUE THREAD

**Issue by dmilith** [meilisearch/MeiliSearch#740]
```
    Updating crates.io index
    Updating git repository `https://github.com/MarinPostma/pest.git`
thread 'main' panicked at 'byte index 2 is not a char boundary; it is inside 'ϗ' (bytes 1..3) of ` tp`', src/libcore/str/mod.rs:2219:
```

**Comment by Kerollmops** [comment]
Hey,

Can you reproduce this but with the `RUST_BACKTRACE=1` environnement variable please?
This way we would be able to debug a little bit more.

BTW was it triggered by a `cargo build`, a `run` or a `test`?

**Comment by dmilith** [comment]
It's even weirder than that.

I tried
`cargo update`

but then I got "segmentation fault" after `cargo build`

So I tried to go deeper, so I did:

```cd meilisearch-core
cargo build # all fine```

```cd meilisearch-error
cargo build # all good```

```cd meilisearch-error
cargo build # ok!```

```cd meilisearch-http
cargo build # failed ```

due to lack of libc const, details: http://s.verknowsys.com/9e7f153dc2da3ebab6e23d83f4134b05.png

```cd meilisearch-schema
cargo build # ok!```

```cd meilisearch-tokenizer
cargo build # ok!```

```cd meilisearch-types
cargo build # fine!```

and here's the weird thing:

after I built manually each depdendency there's no longer segfault but that issue with CLOCK_BOOTTIME only. Weird stuff!

**Comment by dmilith** [comment]
It's after any task involving build. It's weird cause I've seen SEGFAULT and BUS ERROR from it too… Like after clean: http://s.verknowsys.com/d53cf15167ca3e9babe4882da85a5d26.png

**Comment by dmilith** [comment]
More details:

It's HardenedBSD (FreeBSD) 12.1 x86_64 with disabled pax hardening for the build.
Using Rust 1.43.1 from rustup.

**Comment by dmilith** [comment]
Ok. I think I have some weird magic on that host I don't understand yet. Thing is… I invoked "mc" (midnight commander) and tried `cargo build` in it's internal shell… and it works there (until same libc issue). But I have no clue why it happens only in Meilisearch repository

**Comment by dmilith** [comment]
So making long story short, the only issue here is:

```
error[E0425]: cannot find value `CLOCK_BOOTTIME` in crate `libc`
   --> /User/.cargo/registry/src/github.com-1ecc6299db9ec823/sysinfo-0.12.0/src/linux/system.rs:120:43
    |
120 |     if unsafe { libc::clock_gettime(libc::CLOCK_BOOTTIME, &mut up) } == 0 {
    |                                           ^^^^^^^^^^^^^^ help: a constant with a similar name exists: `CLOCK_REALTIME`
    |
   ::: /User/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.71/src/unix/bsd/freebsdlike/freebsd/mod.rs:430:1
    |
430 | pub const CLOCK_REALTIME: ::clockid_t = 0;
    | ------------------------------------------ similarly named constant `CLOCK_REALTIME` defined here
```

**Comment by dmilith** [comment]
Ok, so previous failure is reported here: https://github.com/rust-lang/cargo/issues/8326

**Comment by Kerollmops** [comment]
Wow, thank you for this great report, this is kind of weird but not that strange when it comes this deep and related with libc or missing c libraries.

[I found the other error related to a missing value for a constant in the sysinfo library](https://github.com/GuillaumeGomez/sysinfo/issues/319).
I didn't read much but it seems to have been fixed 24 minutes from now, ahah!
Can you try to compile MeiliSearch with this fix, using the master branch or something.

I will be glad to accept a PR updating this dep when it is published on crates.io ;)

**Comment by dmilith** [comment]
There you go: https://github.com/meilisearch/MeiliSearch/pull/752

Build works fine now! Thanks

**Comment by dmilith** [comment]
https://github.com/meilisearch/MeiliSearch/pull/755

**Comment by dmilith** [comment]
If all is good now we can close the issue now :) thanks!
