### ISSUE TITLE
Trying to add documents with no primary key

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#743]
I create an index with a primary key (`id`). Then I try to add this document without primary key:
```json
[
  {"title": "Pride and Prejudice" }
]
```

On `master`:

Here is the update status result:
```json
{
    "status": "failed",
    "updateId": 0,
    "type": {
        "name": "DocumentsAddition",
        "number": 2
    },
    "error": "serializer error; serialized document does not have an id according to the schema",
    "duration": 0.000583215,
    "enqueuedAt": "2020-06-02T17:00:26.832627Z",
    "processedAt": "2020-06-02T17:00:26.833796Z"
}
```

`v0.10`:

I get this error `document id is missing` (in the update status), which is better to understand (no schema mention).

### Conclusion

I would rather the `v0.10` behavior 🙂

### Steps:
- [ ] fix in the code
- [ ] add tests

**Comment by bidoubiwa** [comment]
What do you think of this error 
```
"error": "Primary key was not found nor could it be inferred."
```

**Comment by curquiza** [comment]
"could not inferred the primary key" is not the same error. Here, the primary has already been inferred.
