### ISSUE TITLE
Tests suite for failure

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#758]
There appear to be some issues testing failures with actix.  I encountered issues when trying to write tests for authentication error with #757, where actix test harness panic instead of returning a response containing the error. Once a fix is found, we need to write a test suite to ensure that we expose consistent failure.

**Comment by MarinPostma** [comment]
After some investigation, it seems that it only concern error thrown in middlewares

**Comment by Kerollmops** [comment]
Can you please link the related actix issue here?

**Comment by qdequele** [comment]
@MarinPostma, is this error still present? Can we close this issue?

**Comment by MarinPostma** [comment]
This is still relevant and should be prioritized

**Comment by curquiza** [comment]
Closed in favor of #1785
