### ISSUE TITLE
Total result count (nbHits) not updated for filters

### ISSUE THREAD

**Issue by unknownhasher** [meilisearch/MeiliSearch#764]
**Is your feature request related to a problem? Please describe.**
I want to show the number of total results (for pagination and for feedback to my users). The result field nbHits is updated by the search string but is not updated by the filters that are given. Because of that it is impossible to give a total count to the users and make a good pagination.

**Describe the solution you'd like**
It would be nice if nbHits is also updated by filters or if there is a secord variable where the filtered count is shown.

**Comment by MarinPostma** [comment]
This is a good suggestion. Currently, we only report the number of candidates, not accounting for the filtered elements. We could in fact count the filtered out element and take them out of the candidate count.

**Comment by jiminy-billy-bob** [comment]
+1

**Comment by balajisivaraman** [comment]
@MarinPostma, Now that I'm done with the tests cleanup, I would be interested in picking this up, if it is still available.

**Comment by MarinPostma** [comment]
Amazing! There are multiple places where this have to be done unfortunately... Ping me on slack, and I'll show you where to look 😊

**Comment by balajisivaraman** [comment]
Awesome! I'll have a look and ping you for sure.

**Comment by isaackearl** [comment]
I tried looking at this a bit myself as I'm trying to migrate to meilisearch from algolia, and I didn't find an easy solution.  I'm to big of a Rust newb to actually tackle this without a bit more time to learn some things.  I think this issues should also qualify as a bug, because paginators that rely on total counts simply don't work when filtered with the current implementation.  Anyway just wanted to make a comment to support this enhancement.  Thanks!

**Comment by theo-lubert** [comment]
Testing the new v0.17.0 release as we speak, it seems the patch does not work if there is a `limit`

For exemple, with 3 "events" in my index (2 with `date` in the past):

`limit: 25` and `date >= ${Date.now}` gives you `nbHits: 1` (correct)
but,
`limit: 1` and `date >= ${Date.now}` gives you `nbHits: 3` (**incorrect**)

**Comment by MarinPostma** [comment]
answerin here too: 

-----
hello @theo-lubert, this is perfectly normal since we lazily filter elements, since you only ask for one, and it is not filtered out, the other are still counted.

**Comment by ghodouss** [comment]
Hi @MarinPostma . I'd like to propose a lightweight solution to this. 

The current nbHits is effectively unusable when using a filter and batching (my use case is a price filter on items). One lightweight solution to improve the approximation without sacrificing speed could be defining nbHits as the following

`nbHits = LIMIT + ( LIMIT/ (LIMIT + n_products_filtered) )*current_nbHits `
    where LIMIT < # Valid DOcuments
In english: set the nbHits equal to the LIMIT + (Percentage of seen documents that meet the filter) * Remaining Number of Hits. 

This way, at least at scale, the approximate nbHits at least factors in the filter.

**Comment by ManyTheFish** [comment]
Hello @ghodouss!
We are working on improving pagination in Meilisearch and we just released a first prototype that makes creating numbered pagination way easier! :fire:
It would be super helpful if you could let us know if this helps with your issue.
To know more about the prototype and how to use it, take a look at [the dedicated discussion](https://github.com/meilisearch/meilisearch/discussions/2635).
