### ISSUE TITLE
An attribute found in the rankingRules must not be added to searchable and displayed attributes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#769]
Related to [this discussion](https://github.com/meilisearch/MeiliSearch/issues/761), especially [this comment](https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641317172).

Here are the steps to reproduce:

- create an index
- udpate ranking rules like this:
```json
[
	"asc(title)",
	"typo"
]
```
Here are the settings now:
```json
{
    "rankingRules": [
        "asc(title)",
        "typo"
    ],
    "distinctAttribute": null,
    "searchableAttributes": [
        "title"
    ],
    "displayedAttributes": [
        "title"
    ],
    "stopWords": [],
    "synonyms": {},
    "acceptNewFields": true,
    "attributesForFaceting": []
}
```

=> the "title" field should not be added to `searchableAttributes` and `displayedAttributes`.

Don't forget to add tests ❤️ 

Tested on `master` before the `v0.11.0` release.

**Comment by MarinPostma** [comment]
Just looked at the code, and the behavior is weird, or I don't understand the `acceptNewField` param:

```rust
for name in ranked_field {
   if schema.accept_new_fields() {
      schema.set_indexed(name.as_ref())?;
      schema.set_displayed(name.as_ref())?;
   }
}
```

This means that this is legit:
- create an index
- add ranking rule `asc(foo)`
- set `acceptNewFields` to `false`
- add ranking rule `asc(bar)` (notice that bar is a new field)

Is this how we want it to behave? Is accept new field a good name then?

**Comment by curquiza** [comment]
Not sure to understand what you mean.

> add ranking rule asc(bar) (notice that bar is a new field)

What do you mean by "notice"? That `bar` is added to searchable and displayed attributes? It should not, as I said in the issue. Not matter what the value of `acceptNewFields`.

**Comment by qdequele** [comment]
This feature has been requested by the team and also @curquiza, long time ago. I would like, if we change the behavior, again, to make a real open proposition and not just a submarine issue.

**Comment by curquiza** [comment]
It's not a submarine issue, we discussed **a lot** about the settings behavior here: #761 
Yes we asked for this behavior before, but I (and the integration team) realized that the other settings behavior was not clear at all, in the docs and most of all in our mind.

According to the settings behavior, Kero took the decision:

> When an attribute is found in the rankingRules an attribute must not be considered new #761 (comment).

See this comment https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641901020.

And we (the SDKs team) agreed. You can guess our opinion is obviously not the same now we figured out the real behavior of the MeiliSearch settings 😉

In this same comment (https://github.com/meilisearch/MeiliSearch/issues/761#issuecomment-641901020), we decided to create 3 separate issues about the settings to make it clearer.
And Marin created one that gathers the 3 ones #776, in the same mindset of making it clearer.

@qdequele Is there a missing step we forgot and that you would add to make all of these process clearer?  🙂

**Comment by bidoubiwa** [comment]
Hey @qdequele which "feature" are you talking about?
The fact that we do not consider fields present in the ranking rules as a known field and thus we keep automatically adding them to the displayed and searchable attribute list?
