### ISSUE TITLE
Make settings more consistent

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#776]
As pointed out in #761, #768 and #769, there are some irregularities in the way new attributes are added by the engine when updating settings.

When a new field is found when updating settings, it is added to the list of known field and the setting is updated. It should not be added to `displayed_attributes` or `indexed_attributes`, the user is expected to know what he is doing when he changes settings, and that he is doing what he meant to.

When indexing, if `accept_new_fields` is set to `true`, new fields are added to the searchable and indexed attributes. That means that if a field is found that is already known by the engine, for example from previously set settings, then then it is not added to the indexed and searchable attributes. *The user should be aware of this* when updating settings.

This is a tracking issue to make the current behavior consistent with what is described above. The following settings must be checked:

- [x] ranking rules (#769)
- [x] distinct attributes should be added to the list of known fields (#768)
- [x] cleanup unused attributes (#767) (still under discussion)

**Comment by MarinPostma** [comment]
regarding known attributes (#767)
It's been decided that there will be a list of known attributes in the the settings.
- once a field is forgotten, all references to it are forgotten to, to keep db consistent.
- three new setting routes are added:
    - `GET /indexes/:index_uid/settings/known-fields`: returns [Strings] containing all known fields
    - `POST /indexes/:index_uid/settings/known-fields`: takes a body of [Strings] containing each known field
    - `DELETE /indexes/:index_uid/settings/known-fields/` resets all known fields **disclosure: this is dangerous, and must be used with caution**
- you can find these settings in the "all settings" route as usual

As a last note, this really is a power-user setting, and users should be warned that this can be dangerous to use

**Comment by curquiza** [comment]
See this related new issue https://github.com/meilisearch/MeiliSearch/issues/824.
