### ISSUE TITLE
use wildcards in search filters

### ISSUE THREAD

**Issue by toxsick** [meilisearch/MeiliSearch#780]
I'm currently evaluating if I can replace my current Elasticsearch setup with Meilisearch. One thing that came up is **using wildcards in search filters**, which i think is not possible currently. I need something like this:

```bash
$ curl --get 'http://localhost:7700/indexes/movies/search' \
    --data-urlencode 'q=Batman' \
    --data-urlencode 'filters=director = Tim*'
```
I guess this is not possible for performance reasons, but this is a blocker for my usecase. Also facets will not help here I think.

Is there any way to implement something like this or is it on the roadmap?

Thanks for the awesome work!

Hannes

**Comment by MarinPostma** [comment]
Hello @toxsick !
#610 proposed to do that, we put it on hold for know, for performance reasons. We may reconsider in the future, if it registers enough interest :)

**Comment by toxsick** [comment]
Hey @MarinPostma, thanks for the info, didn't see that one.

@Kerollmops mentioned in #610 that the upcomming "facetted searching (aggregations)" could solve this use case, but I don't understand how facets would help here, because i want to match dynamic portions of an attribute (e.g. `filters=director = Tim*` should match Tim Burton and Tim Cook).

**Comment by MarinPostma** [comment]
@toxsick I think he had categorical filtering in mind, and faceting is a better fit for such use cases

**Comment by toxsick** [comment]
Ok so #610 would be very interesting for me. I gave it a +1

Thanks for the info and I hope you guys reconsider this.

regards

**Comment by quanterion** [comment]
Wild card is also usefule if you have tree-like structure (e.g. file system) and each document have path property so to search for items in folder /var/log  we could provide wildcard '/var/log*' for path property. Or may be there is some other way to handle such issue?

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/64-search-for-facet-values?utm_medium=social&utm_source=portal_share). 

At first glance, it would not seem to be the same thing, but in fact, to be able to search in the facet values, you have to allow the engine to index, like the searched text, the facet values, and search (with typo and search prefix) in it. This will result in the facets being matched by prefix rather than by exact match. 

I invite everyone interested in this feature to update it on the roadmap.

**Comment by quanterion** [comment]
Actually not facet is not user generated data and things like typo etc is not really needed for facets. Only full and exact match by wildcard

**Comment by toxsick** [comment]
Sorry guys, maybe I don't get faceted search fully, but as I understand facets, they will by design not support something like wildcard filtering, because they are created when an item is indexed right?

I have a use case where I have items with all kinds of different (technical) attributes and I want to query (simplified):

```
$ curl --get 'http://localhost:7700/indexes/servers/search' \
    --data-urlencode 'filters=ip = 192.168*'
```

Not all items in the index will even have the attribute `ip`. Facets will not help here right? I understand that what I try to do will have a big performance impact, because indexes can only be matched partially. But I guess in my case I need that flexibility :)

regards and thx

**Comment by qdequele** [comment]
Thanks, @quanterion, @toxsick,  

I have updated my previous message with an feature that better fits.
