### ISSUE TITLE
Meili dumps compatible across version

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#782]
Meilisearch is still unstable and some update break compatibility with a db created on a previous version. To make transition to a newer version as smooth as possible, it should be possible to export and import meili state and documents in a format that is agnostic of meili version.

**Comment by qdequele** [comment]
Probably a duplicate of #561?

**Comment by MarinPostma** [comment]
you are right, closing as duplicate of #561
