### ISSUE TITLE
Support file based secrets

### ISSUE THREAD

**Issue by tanqhnguyen** [meilisearch/meilisearch#783]
**Is your feature request related to a problem? Please describe.**
Not really, but it's nice to have support for something like [docker secrets](https://docs.docker.com/engine/swarm/secrets/) or any similar file based secret solution in the [docker image](https://hub.docker.com/r/getmeili/meilisearch)

**Describe the solution you'd like**
Other images use `_FILE` suffix to pass the injected secret file into the container and the container can extract the content from that file to populate the normal secret environment variable. For example: `MEILI_MASTER_KEY` will be populated by the file specified in `MEILI_MASTER_KEY_FILE`

**Describe alternatives you've considered**
I'm not 100% sure if there are any other alternatives

**Additional context**
This is only applicable if you deploy meili to a swarm cluster.
I'm happy to submit a PR to update the docker image if you point me to the right direction :)

**Comment by curquiza** [comment]
Hello, just noticed this really old request should have been in the product repository, not here.
If someone is interested by this, can you open a [discussion in the product repo](https://github.com/meilisearch/product/discussions/new). If we have enough person asking for it, this is something we can consider 😄 

Sorry for the late triage
