### ISSUE TITLE
How to match CJK vocabulary accurately, use keyword search directly, without word segmentation.

### ISSUE THREAD

**Issue by jet10000** [meilisearch/MeiliSearch#790]
just match keyword without word segmentation.

How to configure this?

for example search "酒吧"
```
http://127.0.0.1:7700/indexes/books/search?q=%E9%85%92%E5%90%A7&attributesToHighlight=chapter
```
results
```
<em>酒吧</em>Review Dazzle Bar, <em>酒吧内</em>/At Bar
```
`<em>酒吧内</em>/At Bar` this is not what i need

**Comment by MarinPostma** [comment]
Thanks for reporting! We'll investigate 😊

**Comment by Kerollmops** [comment]
Hey @jet10000,

This is totally normal, MeiliSearch is a search engine that support prefix search, therefore the second highlight is totally correct.

**Comment by jet10000** [comment]
How to disable the prefix search feature?

**Comment by Kerollmops** [comment]
We don't have any option to do that for now as the engine target typo-as-you-search, but you can add a space at the end of the queries, as prefix search is only done for the last word if it isn't finished.

**Comment by jet10000** [comment]
![image](https://user-images.githubusercontent.com/2258120/85234583-e4ef0e00-b440-11ea-9ecb-65f106b5f4c5.png)

**Comment by curquiza** [comment]
Hello @jet10000! Sorry for the delay, we are currently working hard on the new search engine that should fix this issue! Is it possible to have the dataset? Or at least a sample of the dataset to reproduce the error.

**Comment by curquiza** [comment]
My bad, this issue should be already fixed with the integration of the new tokenizer thanks to this PR -> https://github.com/meilisearch/MeiliSearch/pull/1091
If it's not, please feel free to re-open this issue

**Comment by ValarDohaerisX** [comment]
> 只匹配关键词，不分词。
> 
> 如何配置这个？
> 
> for example search "酒吧"
> 
> ```
> http://127.0.0.1:7700/indexes/books/search?q=%E9%85%92%E5%90%A7&attributesToHighlight=chapter
> ```
> 
> 结果
> 
> ```
> <em>酒吧</em>Review Dazzle Bar, <em>酒吧内</em>/At Bar
> ```
> 
> `\<em\>酒吧内\</em\>/At Bar`这不是我需要的

@jet10000 你好啊，我现在也遇到这个问题了，我想根据搜索内容模糊搜索，但是会分词，把不相关的结果也会带出来，请问你是怎么解决的？

**Comment by jet10000** [comment]
> > 只匹配关键词，不分词。
> > 如何配置这个？
> > for example search "酒吧"
> > ```
> > http://127.0.0.1:7700/indexes/books/search?q=%E9%85%92%E5%90%A7&attributesToHighlight=chapter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 结果
> > ```
> > <em>酒吧</em>Review Dazzle Bar, <em>酒吧内</em>/At Bar
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `\<em\>酒吧内\</em\>/At Bar`这不是我需要的
> 
> @jet10000 你好啊，我现在也遇到这个问题了，我想根据搜索内容模糊搜索，但是会分词，把不相关的结果也会带出来，请问你是怎么解决的？

你好👋，后来我用了elastic， 不清楚meilisearch现在是否支持精确词汇检索。
