### ISSUE TITLE
Disable transliteration search

### ISSUE THREAD

**Issue by max-frai** [meilisearch/MeiliSearch#795]
Hello, I have cyrillic text with some latin words in it. So when I search for brand name "LG", for example, it suggests russian transliterated text which starts with "ЛГ", but I don't want such logic, because I need exactly "LG".
I tried to set `ranking-rules` to `["attribute", "wordsPosition", "exactness"]` but this didnt help.

**Comment by regzon** [comment]
I don't have this issue in MeiliSearch 0.19.0.

**Comment by curquiza** [comment]
Closing because obsolete. Feel free to re-open if needed.
