### ISSUE TITLE
The distinct-attribute route (GET) returns 0 after updating distinct-attribute

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#798]
## Steps to reproduce

- Create an index
- Update the distinct-attribute
- Get the distinct-attribute at `GET /indexes/:uid/settings/distinct-attribute` -> this route returns `0`.

## To do

- [x] Fix in the code
- [x] Add tests that check the distinct attribute in the general route (`/indexes/:uid/settings`) and in the sub-route (`/indexes/:uid/settings/distinct-attribute`) before and after updating.

## Version

`v0.11.1`

**Comment by curquiza** [comment]
If it's possible, could we have a new patch version (`v0.11.2`) soon? 😇 Because all the SDKs CI are failing right now because of this bug.

**Comment by eskombro** [comment]
I would rename this issue, because the problem is not only returning 0 when a user updates `distinct-attribute`, but it Always returns an integer (an index I suppose) when it is not `null` instead of the attribute name :)
