### ISSUE TITLE
GET /sys-info randomly returns null

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#799]
I don't know if it's a bug, but this was not present in the `v0.11.0`: sometimes, for the route `GET /sys-info` the `cpu` value (in `process`) returns `null`.

Visible, for example, in [this job in the SDK JS](https://github.com/meilisearch/meilisearch-js/pull/477/checks?check_run_id=812510015).

If this is a bug, can you add tests on this route about the expected returned values please? 😇

## Version

`v0.11.1`

**Comment by MarinPostma** [comment]
Hey the is a pr for that that was merge last week #793, can you try it out and tell me if it works for you?

**Comment by curquiza** [comment]
> Can you give me more details on the OS you've testes this on?

The job runs on ubuntu and I succeeded to reproduce it on MacOS (10.15.5).
