### ISSUE TITLE
Uninstall/remove Meilisearch 

### ISSUE THREAD

**Issue by muditsrivastava073** [meilisearch/MeiliSearch#803]
Hello, everyone, I am a noobie here and installed MeiliSearch on my PC (Windows 10) for some work. After installing it I realized that it took a massive 200 GB of space from my PC without any prior warning/mention before/during installation and now I want to remove/uninstall Meilisearch completely from my windows pc. I can't seem to understand how to do it. Please help me with this by either providing me with a link to the solution to my problem or guiding me through it.

**Comment by MarinPostma** [comment]
Hello @muditsrivastava073, how did you install it?

**Comment by muditsrivastava073** [comment]
Hi @MarinPostma I installed it using Git repo by cloning the repo and then compiling it via rust.

**Comment by MarinPostma** [comment]
If you haven't run the command `cargo install --path .`, then simply removing the folder containing the repository should be enough.

**Comment by Kerollmops** [comment]
By the way @muditsrivastava073 there is an option to reduce the size MeiliSearch database takes on disk ([`--max-mdb-size`](https://docs.meilisearch.com/guides/advanced_guides/configuration.html#max-mdb-size)), this is a known problem on Windows due to the way it handle memory mapping.

**Comment by muditsrivastava073** [comment]
@MarinPostma thanks! That worked out but what if i had run the command `cargo install --path`, in that case, what approach was i supposed to take? Just asking for learning purpose.

**Comment by muditsrivastava073** [comment]
@Kerollmops thanks for the help!

**Comment by MarinPostma** [comment]
`cargo uninstall meilisearch`, but you'd probably have to do some cleaning of the data.ms folder that contains the database

**Comment by muditsrivastava073** [comment]
Ok thanks!
