### ISSUE TITLE
Remove hard coded sentry dsn

### ISSUE THREAD

**Issue by Rio** [meilisearch/MeiliSearch#812]
Currently the sentry dsn is hard coded and the sentry client cannot be disabled without recompiling the binary without the sentry feature flag. Leaving this in can result in unintentional data leakage and should generally be avoided.

Removing the value will let the sentry client fall back to using the `SENTRY_DSN` environment variable. This will enable the user to substitute it with their own dsn thus taking control of their own data. To retain the default behaviour that dsn can be moved to the Dockerfile.

**Comment by Kerollmops** [comment]
Hey @Rio,

In the general idea I agree with you but I would say that it would be better to have a flag `--no-sentry` equivalent to the `--no-analytic` one that can be set to disable Sentry. I also looked at your PR (#813) and I am not convinced this is the best solution to put our Sentry DSN in the Dockerfile.

One thing that should be known here is that Sentry is here to help us find issue in the engine without leaking too much personal informations. It is important that crash reports are sent to our Sentry, always would be better.

A solution that can fix this issue would be to introduce to options to binary and not rely on any container system, people in the overall don't always use Docker:
 - the `--no-sentry` flag that can be used to disable Sentry at runtime.
 - and the `--sentry-dsn` option that can be set by the user **but** with a default value to our own current DSN.

What do you think about this solution?

**Comment by Rio** [comment]
No you're completely right. It's definitely a sub-par solution.

I understand that Sentry is there to help developers improve their software but having it default to a project that the operator doesn't have under control and that that behaviour isn't documented or logged is not really good practice.

Having a `--sentry-dsn` and using `SENTRY_DSN` to set them is better however if you're going the "default turned on and send everything to us` route at least it should be logged. Let me go over my PR to see what I can do.

**Comment by Rio** [comment]
@Kerollmops, I've introduced the `--no-sentry` and `--sentry-dsn` along with `SENTRY_DSN` and `MEILI_NO_SENTRY` environment variables.
