### ISSUE TITLE
Tests suite for meilisearch-http: minimal requirements

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#814]
This issue is there to improve the relevancy of the tests and to try to be as exhaustive as possible (even if it's impossible 😇). 
I'm aware that some of the tests on this list are already present 🙂

⚠️ These tests list is really basic:
- they do not take into account all the specific behavior we noticed for the settings and other specific behaviors of MS
- they're only about indexes, documents, update status, search and settings as a first start 🙂
- they only test the HTTP part. I mean, they check that the settings have been well updated, not there are applied during the search. These would deserve another set of tests.

🤖 If you disagree with one of the current behavior of MeiliSearch you notice here, feel free to open another issue.

## Indexes

`GET /indexes`
- [x] Get an empty array when there is no index
- [x]  Get all the indexes: check we get an array with the correct length and the correct UIDs. Check that all the keys/values of one of the elements are present.

`GET /indexes/:uid`
- [x]  Get an error when the index does not exist
- [x]  Get an object when the index exists, and check the JSON response

`POST /indexes`
- [x] Get an error when the index already exists
- [x] Get an error when creating an index with a bad-formatted `uid`
- [x] Get an error when creating an index with an unknown field
- [x] Create an index with no primary key, and check the JSON response
- [x] Create an index with a primary key and check the JSON response

`PUT /indexes/:uid`
- [x]  Get an error when the index does not exist
- [ ] Get an error when updating an index with a bad-formatted `primaryKey`
- [x] Get an error when updating an index where the primary-key is already set
- [x] Update the `primaryKey` with no error and check the JSON response

`DELETE /indexes/:uid`
- [x] Get an error when the index does not exist
- [x] Delete the index, check there is no JSON response

## Documents

`GET /indexes/:uid/documents/`
- [x] Get an error when the index does not exist
- [x] Get an empty array when there is no document
- [x] vGet documents with no parameters: check we get an array with the correct length and the correct UIDs. Check that all the keys/values of one of the elements are present.
- [ ] Get documents with parameters (`limit`, `offset` and `attributesToRetrieve`): check we get an array with the correct length and the correct UIDs. Check that all the keys/values of one of the elements are present.

`GET /indexes/:uid/documents/:id`
- [ ] Get an error when the index does not exist
- [ ]  Get an error when the document does not exist
- [ ] Get an object when the document exists, and check the JSON response

`POST /indexes/:uid/documents`
- [ ] Get an error when the index does not exist
- [ ] Get an error if adding/replacing documents but it's impossible to infer the primary key.
- [ ] Add many documents, check the JSON response (update status response), get the documents, and check that all the documents have been added
- [ ] Check that adding a document with an existing id in the DB completely overwrites the previous document (no partial-update)
- [ ]  Add/Replace documents with a primary key: it should take the `primaryKey` into account. You need to test with a document without any "inferrable" attributes as a primary key (no `id`, `objectId`...)
- [ ] Add/Replace documents with the primary key in parameter but the primary has been already set before: it should ignore the primary key in parameter
- [ ] Add/Replace documents with a bad formatted primary key value (e.g.: `"id": "coco et titi"`): it should return an error in the update status.

`PUT /indexes/:uid/documents`
- [ ] Get an error if adding/updating documents and it's impossible to infer the primary key.
- [ ] Get an error when the index does not exist
- [ ] Add many documents, check the JSON response (update status response), get the documents, and check that all the documents have been added
- [ ] Check that adding a document with an existing id in the DB completely does not overwrite the previous document (= checking the partial-update)
- [ ] Add/Update documents with a primary key: it should take the primaryKey into account. You need to test that with a document without any "inferrable" attributes as a primary key (no `id`, `objectId`...)
- [ ] Add/Update documents with the primary key in parameter but the primary has been already set before: it should ignore the primary key in parameter
- [ ] Add/Update documents with a bad formatted primary key value (e.g.: `"id": "coco et titi"`): it should return an error in the update status.

`DELETE /indexes/:uid/documents`
- [ ] Get an error when the index does not exist
- [ ] If there are documents: call the route, check the JSON response (update status response), check that all the documents have been removed.
- [ ] If there is no document: same than above, no error has been thrown in the update status

`DELETE /indexes/:uid/documents/:id`
- [ ] Get an error when the index does not exist
- [ ] if the document exists: call the route, check the JSON response (update status response), check that the document has been removed.
- [ ] if the document does not exist: same than above, no error has been thrown in the update status

`DELETE /indexes/:uid/documents/delete-batch`
- [ ] Get an error when the index does not exist
- [ ] if the documents exist: call the route, check the JSON response (update status response), check that the document has been removed.
- [ ] if the documents do not exist: same than above, no error has been thrown in the update status

## Update Status

`GET /indexes/:uid/updates`:
- [x] Get an error when the index does not exist
- [x] Get an empty array when there is no document
- [x] Get all the update status: check we get an array with the correct length. Check that all the expected keys/values of one of the elements are present.

`GET /indexes/:uid/updates/:id`:
- [x] Get an error when the index does not exist
- [x] Get an error when the update does not exist
- [x] Get an object when the update exists, and check the JSON response

## Settings

`GET /indexes/:uid/settings`
- [ ] Get an error when the index does not exist
- [ ] Get all the settings with the default value: check the JSON response

`POST /indexes/:uid/settings`
- [ ]  Get an error when the index does not exist
- [ ]  Get an error when updating the settings with an unknown field
- [ ]  Get an error when updating the ranking rules with an unavailable field (e.g.: `"lol"` as a ranking rule)
- [ ] Update the settings without overwriting the ones that are not in the request body (= partial update): call the route, check the JSON response (update status response), check the settings have been partially changed.

`DELETE /indexes/:uid/settings`
- [ ]  Get an error when the index does not exist
- [ ]  Resets all the settings with the expected default values: update settings, reset the settings, check the JSON answer (update status response), check the settings have been reset to their default value.

`GET /indexes/:uid/settings/XXX` (all sub-routes for settings)
- [ ]  Get an error when the index does not exist
- [ ]  Get the settings with the default value: check the JSON response

`POST /indexes/:uid/settings/XXX` (all sub-routes for settings)
- [ ]  Get an error when the index does not exist
- [ ]  Update the settings: call the route, check the JSON response (update status response), check the settings have been completely changed.

`DELETE /indexes/:uid/settings/XXX` (all sub-routes for settings)
- [ ]  Get an error when the index does not exist
- [ ]  Resets all the settings with the expected default values: update settings, reset the settings, check the JSON answer (update status response), check the settings have been reset to their default value.

## Search

- [x]  Get an error if the index does not exist
- [x]  Get an error if a parameter is not expected (e.g.: "lol")
- [x]  Check a basic search with no parameter
- [x]  Check a basic search with only a `q` parameter
- [x] Check a custom search with multiple parameters. At the same time or not, but not to do it in the same test is better. Try to create a search context, e.g. "I want to crop" or "I want to search with my facets": all the parameters have to be checked.

NB: all of these tests should be done for the `GET` and `POST` routes.

## Non-categorized

Add these tests:

- [ ]  a bad formatted JSON (for example the coma in a request body)
- [ ]  trying to send a string instead of an object in the request body when creating an index

## HTTP Error code

The HTTP code error (202, 201, 400, 404...) should be tested for every test.

## How to check an error?

- There is exactly the keys `message`, `errorCode`, `errorType` and `errorLink`
- The expected values of at least `errorCode` and `errorType`

## How to check a response?

What I mean by "check the JSON response" is checking the object contains exactly the expected keys and with the expected values (or at least the expected type).

For example, for the route `/indexes/:uid` you expect to receive:

```json
{
    "name": "indexUID",
    "uid": "indexUID",
    "createdAt": "2020-06-29T01:01:50.473521Z",
    "updatedAt": "2020-06-30T09:37:34.891675900Z",
    "primaryKey": "id"
}
```
You have to check that:
- there is ONLY the keys `uid`, `name`, `primaryKey`, `updatedAt` and `createdAt`
- the exact value of `uid`, `name` and `primaryKey` according to your test
- the type of the value of `updatedAt` and `createdAt`

💡 A function to automatically check the JSON response when receiving an update id (e.g. when updating settings or adding documents) could be great because this response might improve in the future.

**Comment by MarinPostma** [comment]
Thanks for the list @curquiza, I will make sure we are at least compliant with those test cases :)

**Comment by curquiza** [comment]
Replaced by #1440
