### ISSUE TITLE
Unexpected "Words" Ranking Behavior

### ISSUE THREAD

**Issue by mccordnate** [meilisearch/MeiliSearch#818]
**Describe the bug**
I set "words" as the only ranking rule for my index and I only have one searchable attribute. However, some results are lower than I would have expected.

The 1st document has 1 occurrence of the query word out of 355 words (0.28% of words). The 6th document has 27 occurrences of the query word out of 810 words (3.33%).

**Expected behavior**
I would have expected 6th result to be 1st or at least higher than the 1st result. Because 27 occurrences > 1 occurrence and the documentation describes the "words" ranking rule like this:

> 2. Words
Results are sorted by decreasing number of matched query terms in each matching document: find documents that contain more occurrences of the query terms first.

**Question**
Is there a way to obtain the expected behavior? Not sure if I'm just misinterpreting this rule

***Edit**
I should add, I noticed this quote under the "words" description.

> WARNING
It is now mandatory that all query terms are present in the returned documents. This rule does not impact search results yet. soon

I assumed this meant the first sentence didn't impact search results yet, but does this mean the entire "words" rule isn't implemented yet?

**Comment by Kerollmops** [comment]
Hey @mccordnate,

It seems like you miss understood the behavior of the `Words` criterion, it is not based on the number of times a query word matched in the document but the number of words from the query that matches in a document. So a document that contains many times the same query word will not be considered better than a document that contain only one time the same word.

Anyway this criterion is currently useless as only documents containing **all** the words of the query are returned.

**Comment by mccordnate** [comment]
Ah, thanks for clarifying! That makes sense. Part of my mistake is my own lack of experience with search engine terminology, I was reading "query term" as the full query being searched.

Looking over it again, I think the second sentence could be read incorrectly

> find documents that contain more occurrences of the query terms first.

It's not that it contains more occurrences of the query terms, it's that it contains more of the query terms.

Additionally, it would be helpful to have a screenshot example of this rule like the others.
