### ISSUE TITLE
User Restricted Access to Documents

### ISSUE THREAD

**Issue by maximedegreve** [meilisearch/MeiliSearch#826]
**Is your feature request related to a problem?**
As I have multiple users on my platform I don't want those users to have access to each others documents.
Therefore I need a way to limit what they can search.

**Describe the solution you'd like**
Is this maybe what I'm searching for here? 
https://www.algolia.com/doc/guides/security/api-keys/how-to/user-restricted-access-to-data/
https://typesense.org/docs/0.13.0/api/#generate-scoped-search-key

**Describe alternatives you've considered**
Maybe there are alternatives but I couldn't see them in the documentation?

**Additional context**
N/A

**Comment by MarinPostma** [comment]
Hello @maximedegreve! We don't have a solution out of the box for your use case right now (#843 may be a step toward that though, thanks to  restricted indexes and parameters). 
I would however suggest that you try faceting for this. You could add a list of authorized user-ids to your documents, and set that list as an attribute for faceting. searching with a facet to "authorized_uuids:<uid>" will only return documents with uid authorized.

Let me know if that helps

**Comment by maximedegreve** [comment]
That makes sense @MarinPostma. However one concern here is that someone could fetch all docs by not defining a facet?

**Comment by MarinPostma** [comment]
Yes, you'd have to proxy meilisearch request for it to work safely. We have plans to address that in the short future

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/82-authorization-keys?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
