### ISSUE TITLE
Meilisearch crashes on Google Cloud Run

### ISSUE THREAD

**Issue by tejpochiraju** [meilisearch/MeiliSearch#833]
**Describe the bug**
Meilisearch crashes on Google Cloud Run with the error: 
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Heed(Io(Os { code: 38, kind: Other, message: "Function not implemented" }))', meilisearch-http/src/data.rs:69:27`

**To Reproduce**
1. Go to Google Cloud Run
2. Deploy getmeili/meilisearch (you will need to push to Google Cloud Registry first)
3. See error

***Dockerfile***

```docker
FROM getmeili/meilisearch
CMD ./meilisearch
```

**Expected behavior**
Container starts and runs on port 7700 without crashing.

**Additional context**
[gVisor](https://github.com/google/gvisor) which is the kernel used for Google Cloud Run does not currently [implement membarrier](https://github.com/google/gvisor/issues/267). There is a warning about this just before the crash. I am not familiar enough with Rust to know if these are related.

I have tried this at the various memory capacities up to the maximum limit of 2GB with 1vCPU with the same result.

**Logs**
[null__logs__2020-07-04T12-41.zip](https://github.com/meilisearch/MeiliSearch/files/4871212/null__logs__2020-07-04T12-41.zip)

**Comment by tejpochiraju** [comment]
Since the crash happens when trying to [open a db](https://github.com/meilisearch/MeiliSearch/blob/2f6c55ef789818263ba999fc950ac4a3bd16ef82/meilisearch-http/src/data.rs#L69), I am checking to see if this is caused by a read-only filesystem for the container. 

```rust        
let db = Arc::new(Database::open_or_create(opt.db_path, db_opt).unwrap());`

Will update this issue if I find a solution or workaround.

**Comment by curquiza** [comment]
Do you still have the same issue with MeiliSearch v0.20.0
We are currently working on creating a GCP image of MeiliSearch but we didn't face any issue like that.

**Comment by MarinPostma** [comment]
@curquiza this is a runtime error, where some syscall is not implemented by google. Nothing we can do about it for now.
