### ISSUE TITLE
Greater control of keys for automated deploys

### ISSUE THREAD

**Issue by rsalmond** [meilisearch/MeiliSearch#839]
**Is your feature request related to a problem? Please describe.**
I am deploying Meilisearch in an automated fashion. Because I can only specify the master key the automation must either:
 * give the master key to Meilisearch and all clients at deploy time when the key is generated
 * include some glue component to take the master key, exchange it for the private key, and give that to the clients

**Describe the solution you'd like**
If I could specify all 3 keys at Meilisearch deploy time, I could easily store the lower privileged client keys in our secret manager for clients to consume.

**Describe alternatives you've considered**
I thought about writing some glue code to fetch the private key after it is generated but that glue code would need access to Meilisearch which is not directly exposed to the secret management infrastructure. By design our apps can fetch secrets from the secret management infrastructure, it was never intended to operate the other way round.

In the end we just gave the clients the master key.

**Additional context**

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/82-authorization-keys?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
