### ISSUE TITLE
Delete by facet

### ISSUE THREAD

**Issue by aeriksson** [meilisearch/MeiliSearch#845]
**Is your feature request related to a problem? Please describe.**
So the faceted search is great for finding documents e.g. by project, group, user, et cetera.

However, _deleting_ documents by project/group/user/whatever (e.g. when deleting all documents associated with a user that's deleted their account) is a bit more complicated (and inefficient); it requires the client to:
1. Search for all documents with the given facet.
2. Extract all primary keys from the search response.
3. Send a delete request with the primary keys.

This works okay when there's a small number of documents, but it gets complicated and inefficient when there are enough documents that the searching and deleting needs to happen via multiple requests.

**Describe the solution you'd like**
It'd be fantastic if there was a way to specify a facet filter or similar instead of a list of primary keys when deleting documents. Something like `POST /indexes/:index_uid/documents/delete-by-facet?facetFilters=["foo:bar"]`.

This would save a lot of effort on the part of developers, as well as make these sorts of batch deletes more efficient (by eliminating one or more round trips, and potentially allowing MeiliSearch to combine the search/delete into a single operation).

**Comment by LegendreM** [comment]
Hello thank you for your feature proposal which is really interesting,

do you have any idea of a concrete use case of this feature? 😄

**Comment by aeriksson** [comment]
@LegendreM sure!

Imagine that GitHub was using MeiliSeach to power its commits/issues/comments/etc search. Whenever a user or repository was deleted, they'd want to remove all corresponding commits/issues/comments/etc from the MeiliSearch index(es).

They could in principle accomplish this by (possibly repeatedly) querying for all documents related to the user/project and then doing one or more batch deletes. However, it would be a lot simpler (and faster) if they could delete directly by user/project via some of faceted attribute.

**Comment by FridgeSeal** [comment]
> do you have any idea of a concrete use case of this feature? 😄

Oooh I have one 😃 
At the moment I'm indexing a lot of documents that are in the order of 10's to 100's of pages long. I'm pre-emptively splitting them up so that they're under the maximum size limit and adding an attribute with the original document id. When my application gets told a given document needs to be deleted I'm currently doing what @aeriksson described.

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/68-delete-by-filters?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to update it on the roadmap.

**Comment by ar-siddiqui** [comment]
> Hello, Thanks for this feature proposal!
> 
> I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/68-delete-by-filters?utm_medium=social&utm_source=portal_share).
> 
> I invite everyone interested in this feature to upvote it on the roadmap.

I don't see it on the roadmap

**Comment by gmourier** [comment]
Hello @ar-siddiqui! 

Indeed! It no longer has the same identifier, the link is broken. I added the right one to the roadmap [here](https://roadmap.meilisearch.com/c/103-delete-by-query). Sorry for the inconvenience 😇
