### ISSUE TITLE
Explicit "primaryKey" not honored, documents not saved, no error messages shown

### ISSUE THREAD

**Issue by anborg** [meilisearch/MeiliSearch#852]
State: 
- Running docker compose of mili in windows (docker-compose.yml attached)
- Posting document through soapui multiple times (.json payload attached)

**Expectation:** 
- Since no error was reported in response, or console, I expect to see the documents at http://localhost:7700/indexes/mkmsite/documents, but it is empty.
- If there is error with json parsing, must report error in soapui/postman response, also in logs.

![image](https://user-images.githubusercontent.com/56970398/87251251-3551fe00-c438-11ea-9971-a81dde437842.png)

**To Reproduce**
Please run docker-compose up[ windows machine? ]
Post the json (seems like valid json according to https://codebeautify.org/jsonvalidator)
check logs and index

For creating index
```json
{ 
	"name": "Mkmsite"
	,"uid": "mkmsite"
	,"primaryKey" : "url"
}
```

.env file content for docker compose
```
MEILIDATA_DIR=c:/mnt/disks/datadisk/apps/meilisearch/data/mkmsite
```

[docker-compose.yml.txt](https://github.com/meilisearch/MeiliSearch/files/4908815/docker-compose.yml.txt)

[markham.json.txt](https://github.com/meilisearch/MeiliSearch/files/4908817/markham.json.txt)

**Comment by MarinPostma** [comment]
Hey @anborg 
What error when indexing are reported in the /updates routes, can you share what it says?

**Comment by anborg** [comment]
Hi Martin, 

>/indexes/:index_uid/updates routes, can you share what it says?

Sorry I destroyed when I ran further experiments.  :(

However, when I added an **id:** field in json, I'm able to post the content to index.

```json
{"id": 1, "url": "https://www.markham.ca/wps/portal/home", "title": "Markham", "conte
{"id": 2, "url": "https://www.markham.ca/wps/portal/home/online", "title": "Online Se
{"id": 3, "url": "http://www.markhampanamcentre.ca", "title": "Home - Markham Pan Am 
{"id": 4, "url": "http://www.markhampanamcentre.ca/about-us/faqs/", "title": "FAQs - 
{"id": 5, "url": "http://www.markhampanamcentre.ca/about-us/mission-vision/", "title"
{"id": 6, "url": "http://www.markhampanamcentre.ca/about-us/", "title": "About Us - M
{"id": 7, "url": "http://www.markhampanamcentre.ca/community-engagement/corporate-spo
{"id": 8, "url": "http://www.markhampanamcentre.ca/community-engagement/athlete-spotl
{"id": 9, "url": "http://www.markhampanamcentre.ca/community-engagement/markham-sport
```
Looks like **primaryKey: "url"** is not respected by the system. Is that correct?

**Comment by PolywickStudio** [comment]
hi,
I have something similar - 
https://github.com/meilisearch/MeiliSearch/issues/852

I have a reproducible repository.

**Comment by Kerollmops** [comment]
Hi @anborg,

I just looked at your issue and it seems to be related to the "url" primary key which doesn't [follow the rules](https://docs.meilisearch.com/guides/main_concepts/documents.html#document-id): a document id must only contain `A-Z a-z 0-9` and `-_` characters.

This must have been reporter in the updates logs. Which you can access via `indexes/:index-uid/updates/:update-id`.
