### ISSUE TITLE
Avoid sending the entire request in error message when error is 'Payload too large' 

### ISSUE THREAD

**Issue by deshetti** [meilisearch/MeiliSearch#862]
**Is your feature request related to a problem? Please describe.**
The total size of documents I was indexing was over 10MB and the terminal filled up with the request. The request returned in the error message filled up my log/terminal and made it difficult to find the error in the beginning, which is:

```
unaccepted status code found: 413 expected: [202], message from api: 'Payload to large', request:  [{< entire request>}]
```

**Describe the solution you'd like**
If the user tries to index a large number of documents let's say over 1GB, this would be even worse. The only error message that is related and should be shown in that case is the message from api: 'Payload too large'. In this case request returned in the api is not relevant. 

**Describe alternatives you've considered**
NA

**Additional context**
Trivial, but there is a typo in the error. The error message should say *Payload to**o** large*

**Comment by MarinPostma** [comment]
@deshetti Thanks for reporting, we'll fix this :)

**Comment by LegendreM** [comment]
hello @deshetti do you use meilisearch directly via HTTP or are you using an SDK? If you are using an SDK could you give us which SDK you are using?

**Comment by deshetti** [comment]
@LegendreM sorry for the delayed response. I do not check my github notifications very often.

We use the Golang SDK.

**Comment by curquiza** [comment]
Hello, MeiliSearch now returns:

```json
{
    "message": "Payload too large",
    "errorCode": "payload_too_large",
    "errorType": "invalid_request_error",
    "errorLink": "https://docs.meilisearch.com/errors#payload_too_large"
}
```

If it still does not return what you expect, this is an issue to open in the meilisearch-go repository -> https://github.com/meilisearch/meilisearch-go/ 🙂
