### ISSUE TITLE
Search api : attributesToCrop , does not reduce data {feature? suggestion?]

### ISSUE THREAD

**Issue by anborg** [meilisearch/MeiliSearch#863]
I use cropping feature in elasticsearch or meili to reduce the content returned in a field. The intent of client-app is explicitly to crop field(s), and get only cropped data, without introducing new json structure **_formatted**. Client-app that is consuming the json can treat cropped-result same as non-cropped, also data transfer over network is reduced.

Search url: http://127.0.0.1:7700/indexes/movies/search?q=snowman&attributesToCrop=*&cropLength=100

**Expected** 
```
{
    "id": "13382",
     //cropped non id fiends
},
```

**Actual:** 
If the overview field is in MBs, incurs unnecessary network cost.
```
{
         "id": "13382",
         "title": "Rudolph the Red-Nosed Reindeer",
         "poster": "https://image.tmdb.org/t/p/w1280/r0vtyGOwTLZg4pgtbjlMGke7Qo1.jpg",
        //If the overview field is in MBs, incurs unnecessary network cost.
         "overview": "Sam the snowman tells us the story of a young red-nosed reindeer who, after being ousted from the reindeer games because of his glowing nose, teams up with Hermey, an elf who wants to be a dentist, and Yukon Cornelius, the prospector. They run into the Abominable Snowman and find a whole island of misfit toys. Rudoph vows to see if he can get Santa to help the toys, and he goes back to the North Pole on Christmas Eve. But Santa's sleigh is fogged in. But when Santa looks over Rudolph, he gets a very bright idea...",
         "release_date": -160012800,
         "_formatted":          { 
            "id": "13382",
            "title": "Rudolph the Red-Nosed Reindeer",
            "poster": "https://image.tmdb.org/t/p/w1280/r0vtyGOwTLZg4pgtbjlMGke7Qo1.jpg",
            "overview": "Sam the snowman tells us the story of a young red-nosed reindeer who, after being ousted from the reindeer games",
            "release_date": -160012800
         }
},
```
![image](https://user-images.githubusercontent.com/56970398/87878139-74400080-c9b0-11ea-9ed4-8d8845e487cd.png)

**Middle ground**

Perhaps adding a flag to provide _original content, if flag present, include original content, if flag is not present, just return cropped content. 
search?q=snowman&attributesToCrop=*&cropLength=100&**includeOriginal**
```
{
    "id": "13382",
    //cropped non id fiends
    ,
    "_original" : { //original **if explicitly requested**. This makes sure both user intents are satisfied.
            "id" :"13382",
            //un cropped fields 
     } 
},
```
Having json structure same for cropped and uncropped, ensures UI clients does not need code change,

![image](https://user-images.githubusercontent.com/56970398/87879094-7dcc6700-c9b6-11ea-8255-21d1c7aef7d1.png)

**Comment by qdequele** [comment]
Hello, you can already do it by mixing the attributes `attributesToRetrieve` and `attributesToCrop`. 

- `attributesToRetrieve`: Will filter the attributes you want to retrieve in _original_ and _formated_ attributes. By default the value is a wildcard for all attributes.
-  `attributesToCrop`: Will select which attributes you want to crop. If this attribute is not present on `attributesToRetrieve`, o the field will be added only on the _formated_ response.

So what you can do is: 

```
curl "http://localhost:7700/indexes/movies/search?q=c&limit=4&attributesToRetrieve=id&attributesToCrop=overview&cropLength=20"
```

and the response will be:

```
{
  "hits": [
    {
      "id": "100402",
      "_formatted": {
        "overview": "After the cataclysmic events in"
      }
    },
    {
      "id": "16281",
      "_formatted": {
        "overview": "Inspired by the E.C. comics of the 1950s"
      }
    },
    {
      "id": "9584",
      "_formatted": {
        "overview": "form a mile long 'convoy' in support of"
      }
    },
    {
      "id": "23730",
      "_formatted": {
        "overview": "murders in New York City seems to point"
      }
    }
  ],
  "offset": 0,
  "limit": 4,
  "nbHits": 16520,
  "exhaustiveNbHits": false,
  "processingTimeMs": 10,
  "query": "c"
}
```

<img width="2135" alt="Capture d’écran 2020-07-20 à 09 30 40" src="https://user-images.githubusercontent.com/6064892/87911310-aebaa380-ca6b-11ea-89fb-e5eac248235e.png">
