### ISSUE TITLE
Have a `facetFiltersIn` instead of `facetFilters` in search query parameters

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/MeiliSearch#871]
**Is your feature request related to a problem? Please describe.**
the usage of `facetFilters` is confusing between `AND` and `OR` related facetsfilter,
when `facetFilters=["women", ["blue", "red"], "shirt"]` it's not really obvious that end filter will be:
`"women" AND ("blue" OR "red") AND "shirt"`

if I want only an `OR` relation I need to pass `facetFilters=[["red", "green"]]`

what should be the result of `facetFilters=[["women", ["blue", ["red", "green"]], "shirt"]]` ?

there is an other issue when adding facetFilter to an existing query, query parameter needs to be overwritten and can't just be added to the query

**Describe the solution you'd like**
- replace `facetFilters` by `facetFilter` to only have one facet and letting user pass several `facetFilter` param
- add a `facetFiltersIn` query parameter to manage `OR` relation passing an array of string 

at the end the query would be `facetFilter=women&facetFiltersIn=blue,red&facetFilter=shirt`

**Comment by MarinPostma** [comment]
> what should be the result of facetFilters=[["women", ["blue", ["red", "green"]], "shirt"]] ?

This is an error, depts is limited to 2.

When we first thought of facets I suggested a keyword `in` in the filter syntax that would allow to mix filters and facets (or just facets). You could use it like:  `price < 20 in category = tshirt` where everything to the right of in are facets. We decided to go with the array semantic to allow to programmatically create filters. Note that the two are not incompatible

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/MeiliSearch/pull/1421
