### ISSUE TITLE
how to create index with crawl website? 

### ISSUE THREAD

**Issue by chintan9** [meilisearch/MeiliSearch#882]
**Is your feature request related to a problem? Please describe.**
how to create index with crawl website? 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Need understand automated index process to use  MeiliSearch

**Comment by LegendreM** [comment]
Hello @chintan9 I'm not sure to understand your need (could you explain it more if I didn't 😄),
but we made a [scrapper](https://github.com/meilisearch/docs-scraper) to index websites in meilisearch,

Is this fit your need ?
