### ISSUE TITLE
Backup and Restore Meilisearch index?

### ISSUE THREAD

**Issue by PolywickStudio** [meilisearch/MeiliSearch#884]
**Is your feature request related to a problem? Please describe.**
There needs to be a way to backup and restore the index.

**Describe the solution you'd like**
I would like to backup and restore the index in Windows... the Meilisearch stupidly allocates 200GB. Can you imagine how much it costs for 500GB Windows VM?

**Describe alternatives you've considered**
WSL2. Maybe move to TypeSense, or other search engine. Getting tired fighting bugs.

**Additional context**
None.

**Comment by andresribeiro** [comment]
This would be very interesting, and could have some features like automatic backups

**Comment by LegendreM** [comment]
Hello @PolywickStudio there is 2 future features that could be interesting for you:
- snapshoting (fast and schedulable) in PR
- backup (cross version) WIP

Don't hesitate to say how the user interface of theses features should be, to fit optimaly your needs.

**Comment by PolywickStudio** [comment]
a) I need either an ability to back and restore from same or similar version.
b) I can do a snapshot, so long as it works on Windows or Linux (cross-platfom).

**Comment by PolywickStudio** [comment]
My use-case is something like this.

- I would like to run Meilisearch on a faster computer, let it run the index and then do a back-up, and then restore to a slow public-facing VM computer.

- I rent a VM, I got a 400GB index on rented Windows. Not good... I subsequently got a 10GB index but had to re-do the index many, many times with mysterious out-of-memory error on 32GB RAM, and 10GB-HDD file (with 100GB to spare) on a rented Linux VM.

- I would like to backup Meilisearch every now and then, so if Meilisearch or the VM crashes, I have some restore point.

**Comment by Bajix** [comment]
I don't get why you'd want to have this. Meilisearch isn't designed with the kinds of data guarantees that you'd need for it to be considered a primary data store. You should really just go the route of having something like a Meilisearch Helm chart that deploys to EKS and a parent chart that launches hooked tasks to create indexes, then to seed data, then to launch a synchronization service. This way you only need to backup your primary data store and you can use a recreation based deploy plan for installation/upgrading.

**Comment by gnur** [comment]
Meilisearch indexing is a serious bottleneck in my usecase, it takes about a week to fully index about 800.000 documents.  

So a better solution for moving between versions then simply "re-index" everything would be nice.

**Comment by Bajix** [comment]
If it takes you a week to index 800k documents, then your bottleneck isn't Meilisearch, it's your synchronization mechanism. With so few documents, this shouldn't take more than 2 hours if done optimally. Generally, for most upgrades you'll be able to just reattach the previous persistent volume, so it's already fairly uncommon that a backing data migration would need to occur. I'm sure Meilisearch will have better support for this at a later release, but even when they do you should still be building such that you have an optimal means of recreating as needed.
