### ISSUE TITLE
Facet Sorting

### ISSUE THREAD

**Issue by shyim** [meilisearch/MeiliSearch#890]
**Is your feature request related to a problem? Please describe.**
I have an JS input trigger to send an request to display the result. But after each request the facets are sorted random. On each request they change the order

**Describe the solution you'd like**
Parameter to sort the facets

**Describe alternatives you've considered**
Sorting it on the Client

**Additional context**
https://packages.friendsofshopware.com/search Type: paypal. And remove the last letter and add it. The facets are random other sorted

**Comment by MarinPostma** [comment]
Hello @shyim, thanks for your proposition. I'm not sure we want to add another parameter to do just this. We could return them sorted by default, or leave the sorting to the client, as this is a pretty light workload.

**Comment by shyim** [comment]
Yea maybe they should be sorted by something. So the same request does return the same order :)

**Comment by curquiza** [comment]
Hello!
What is the final decision for the sorting? By alphabetic order? By total of result?

**Comment by MarinPostma** [comment]
I would go with alphabetical order, to have a consistent order across searches

**Comment by LegendreM** [comment]
will be fixed by #943.

don't hesitate to reopen it if #943 is not exhaustive.
