### ISSUE TITLE
Attributes for faceting vs. lazily-created indices

### ISSUE THREAD

**Issue by xmirya** [meilisearch/MeiliSearch#891]
**Describe the bug**
Version 0.13rc, binary published by the project
Arch: linux/amd64

I'm trying to implement a lazily-created index pattern, where an index is expected to have some faceted attributes. This works in the way that a running application gets a "job" to index some object; the object defines an index it has to belong to (some kind of sharding), so 3 operations are done one by one:
1. Create an index: UID=index
2. Update index settings: UID=index, `{"attributesForFaceting":["users","type","labels"]}`
3. Insert an object into that index, `[{"body":"object 1","id":"m52","labels":[],"type":"1","users":["userid1"]}]`

(2) and (3) return an async ID, however I _assume_ those are serialized (e.g. 3 follows 2 on Meili side), so i'm not waiting for update (2) to complete, and just sending the request (3).

It appears the `attributesForFaceting` are somehow messed up in the index:
1. Right after (3) i'm _getting_ that index settings, to find out it returns the following:
```
{"rankingRules":["typo","words","proximity","attribute","wordsPosition","exactness"],"distinctAttribute":null,"searchableAttributes":["*"],"displayedAttributes":["*"],"stopWords":[],"synonyms":{},"attributesForFaceting":["id"]}
```
Notice `id` listed in `attributesForFaceting`

2. If i'm again _getting_ the index settings several seconds later, i now see `"attributesForFaceting":["id","body","labels"]`. Naturally, if i'm doing a search specifying `"type:1"` as a facetFilter, it returns HTTP/400 with a message like:
```
error processing facet filter: `type` is not set as a faceted attribute. available facet attributes: id, body, labels
```

My assumption about operations (2) and (3) above being serialized in that order might be wrong, however even if it is, I assume one of two outcomes:
1. If it's not serialized in that way: the record from (3) is inserted w/o settings from (2) being applied yet, so it won't be returned in the search
2. If it's actually serialized like that: the record from (3) is inserted after the settings from (2) are applied, so it's properly indexed and returned in the search.

Regardless of the order, i expect `attributesForFaceting` to be set to `["users","type","labels"]` at some point, not some random `["id","body","labels"]`

**To Reproduce**
1. Create an index with UID `index`
2. With no delay: update the index setting with `{"attributesForFaceting":["users","type","labels"]}`
3. With no delay: insert a document into the index, `[{"body":"object 1","id":"m52","labels":[],"type":"1","users":["userid1"]}]`

**Expected behavior**
After a few seconds the request to get the setting for `index` should return `{"attributesForFaceting":["users","type","labels"]}`. A search request with `"type:1"` as `facetFilter` should not return an error code.

**Comment by LegendreM** [comment]
this issue is now split in 2 children issues:
- a bug report #942
- a feature tracking issue #918

I close this issue, don't hesitate to reopen it if children issues are not exhaustives.
