### ISSUE TITLE
Lengthy indexing times. 3 days?

### ISSUE THREAD

**Issue by PolywickStudio** [meilisearch/MeiliSearch#892]
**Describe the bug**
The indexing takes very long time.

**To Reproduce**
1. Upload/post 30,000 documents.
2. Convert to Ubuntu server.
3. Wait and wait days... 
Previously, it took ~1.666 (1 day, 15 hours) days. Now it's 3 days+ and it's still indexing.

**Expected behavior**
Indexing should take less than 1 day.

**Screenshots**
curl -H -X GET http://XXXXXXXXXXXX:7700/indexes/docs1/updates/16703
{"status":"processed","updateId":16703,"type":{"name":"DocumentsAddition","number":1},"duration":16.563707589,"enqueuedAt":"2020-07-30T21:34:11.715174145Z","processedAt":"2020-08-03T02:26:55.220584794Z"}
More than 3 days have passed.

**Desktop (please complete the following information):**
Windows 10
Browser: Firefox 80b1, Chrome (latest)

**Smartphone (please complete the following information):**
N/A

**Additional context**
Why is my indexing taking so long?

**Comment by PolywickStudio** [comment]
![snag](https://user-images.githubusercontent.com/8903532/89144624-ce2ff100-d580-11ea-8270-1be7b44d2d89.png)

**Comment by qdequele** [comment]
As I said in the previous chat, you're trying to index full-text documents. That's not normally our use-case. We normally index JSON documents under 10Kb. It would be better to turn it into JSON (as explained in our previous conversation). 

However, most of them are over 10Kb and some are over 500Kb. To help with this, we should split the files into smaller 10Kb files.

**Comment by PolywickStudio** [comment]
I did. I split up the text into multiple Json paragraphs. Should I split it further?
