### ISSUE TITLE
cjk search experience is too bad, the highlight position is wrong.

### ISSUE THREAD

**Issue by jet10000** [meilisearch/MeiliSearch#894]
![image](https://user-images.githubusercontent.com/2258120/89184291-22f85980-d5cb-11ea-861d-78a8dc6f1580.png)

**Comment by Kerollmops** [comment]
I think this is highly related to #790.

**Comment by curquiza** [comment]
Hello @jet10000! Sorry for the delay, we are currently working hard on the new search engine that should fix this issue! Is it possible to have the dataset and your query? Or at least a sample of the dataset to reproduce the error.

**Comment by curquiza** [comment]
My bad, this issue should be already fixed with the integration of the new tokenizer thanks to this PR -> https://github.com/meilisearch/MeiliSearch/pull/1091
If it's not, please feel free to re-open this issue
