### ISSUE TITLE
Uncaught ReferenceError: select is not defined

### ISSUE THREAD

**Issue by elfeffe** [meilisearch/MeiliSearch#896]
I'm trying to use the web interface, I have the latest version installed with APT
The error is on this line

    select.onchange = triggerSearch;

select doesn't exist

**Comment by Kerollmops** [comment]
Hey @elfeffe,

Thank you very much, indeed it seems like the `select` variable has not been declared, we will fix this in the 0.13.1.
I don't understand how this could have even work.
