### ISSUE TITLE
Provide persistent logs in a specified path

### ISSUE THREAD

**Issue by eskombro** [meilisearch/MeiliSearch#898]
**Is your feature request related to a problem? Please describe.**

MeiliSearch logs are by default presented to the user in stdout. Using system capabilities, it is possible to access those logs in several other ways, but it would be interesting to have the possibility to provide a path to a file where the user wants MeiliSearch to store logs permanently.

**Describe the solution you'd like**

An example would be a `--log-file=<path-to-log-file>`

```bash
./meilisearch --log-file="/tmp/meili_logs.log"
```

**Describe alternatives you've considered**

Having by default a log file in the `data.ms` folder (with a limited number of lines, for example, to avoid creating huge files for logs)

**Comment by Kerollmops** [comment]
PR WELCOMES

**Comment by eskombro** [comment]
I think that would be a normal way to handle it when your project is in production, but not necessarily friendly for development, automated deployment, using persistent volumes in docker containers etc, in which case it would be quite a nice option to tell MS "I want some logs here my friend" :)

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/81-specify-log-path?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.

**Comment by kuchaguangjie** [comment]
`--log-file` is not supported, so what's the solution ?

**Comment by curquiza** [comment]
Hello @kuchaguangjie 
Sorry, so far there is no other solution. However, I've opened a discussion here so that the product team can start working on it. Your opinion about what you would expect as a user really interests us: https://github.com/meilisearch/product/discussions/471
Please, feel free to share your needs, it would be really helpful 😄

**Comment by tgoeg** [comment]
I assume installation lives in `/opt/meilisearch`, using Debian.
This is the systemd unit file I created:
```
cat >/etc/systemd/system/meilisearch.service <<EOF
[Unit]
Description=Meilisearch
After=systemd-user-sessions.service

[Service]
Type=simple
ExecStart=/opt/meilisearch/meilisearch --env development --master-key THEKEY --db-path /opt/meilisearch/data.ms --dump-dir /opt/meilisearch/dumps --http-addr 0.0.0.0:7700
StandardOutput=append:/var/log/meilisearch/meilisearch_stdout.log
StandardError=append:/var/log/meilisearch/meilisearch_stderr.log
User=meilisearch
Group=meilisearch

[Install]
WantedBy=default.target
EOF
```

The following also makes sure we use dropped privileges and correctly owned/rotated logfiles. Without any method in place to make Meilisearch know we pulled away the logfile beneath its feet (sending `SIGHUP` is the usual way with other Linux services), I'll truncate the logfile in place, this should work out best:
```
useradd meilisearch -s /bin/false -U -d /opt/meilisearch
mkdir /var/log/meilisearch && chown meilisearch: $_ && chmod 700 $_
chown -R meilisearch: /opt/meilisearch && chmod 700 $_
cat >/etc/logrotate.d/meilisearch <<EOF
/var/log/meilisearch/*.log
{
	rotate 52
	weekly
	missingok
	notifempty
	compress
	copytruncate
	su meilisearch meilisearch
}
EOF
```
Finally,
```
systemctl daemon-reload && service meilisearch restart
```
And probably
```
systemctl enable meilisearch
```
to make it start on boot.

@curquiza: Might make sense to include this somewhere?

**Comment by curquiza** [comment]
Hello @tgoeg 
Thank you very much for this workaround! 🙏 I will share your comment in the appropriate spaces
