### ISSUE TITLE
Feature proposal: Support index alias

### ISSUE THREAD

**Issue by eskombro** [meilisearch/MeiliSearch#899]
**Is your feature request related to a problem? Please describe.**
 
As an index name modification can't be done or would introduce quite important changes in any MeiliSearch implementation, a good alternative would be to add/modify/delete an `Alias` to an index. In that way a user can access an index using a different Index name, which can be updated and modified anytime without having an impact in the index itself.

This is especially interesting (for a usecase example) when you want to reindex your content and want to have zero downtime. You can create a new index, index the content, and when all updates have been processed, you can add an alias to the new index and delete the last one, making the new index inmediately available without any changes in the way you request MeiliSearch

**Additional context**

An example of this implementation can be seen in [ElasticSearch Index Alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html)

**Comment by curquiza** [comment]
In the same context, the `Copy/move index` endpoint provided by Algolia!

https://www.algolia.com/doc/rest-api/search/#copymove-index

I'm really interested in this feature, especially for `docs-scraper`!

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/65-swap-index?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
