### ISSUE TITLE
How can I conduct a EXACT MATCH (regex) query?

### ISSUE THREAD

**Issue by John-Theo** [meilisearch/MeiliSearch#902]
### Use case description

I have a bunch of documents already indexed, and I want to find those CONTAINS a certain text, say "patient #1". 

### Question

Typo tolerance is cool, but how can I construct my EXACT MATCH search query?

*. Also, if exact match is already implemented, what about regex expression? (something like "patient #?\d")

**Comment by Kerollmops** [comment]
Hello,

We do not currently support regex queries however I think you could probably pre-compute some facet for your documents. Documents could have a field refering the patients ids related.

MeiliSearch is an end-user search engine it means that it is focussed on front-end queries, it means that only unexperienced users can query the database and most importantly results must not be trusted like any SQL database.

Do you think that could fit your needs? What is your real usecase?

**Comment by Chaphasilor** [comment]
I'd also be very interested in an exact match. I'm using MeiliSearch on data not containing natural language and the typo tolerance and space separators really mess with the quality of the search results.  
See my issue here: https://github.com/meilisearch/documentation/issues/531

I personally don't need regex for not, but a query flag indicating that the exact search term has to be contained within a field would be a very welcome addition!

**Comment by eskombro** [comment]
You can customize the [ranking rules](https://docs.meilisearch.com/guides/advanced_guides/settings.html#ranking-rules) of MeiliSearch, in which `typo` is just an optional rule that happens to have a huge priority in the default settings. This is because it is a must-have for a lot of usecases. Try removing `typo` from the rules, or even applying only `exactness` and see which configuration fit your needs the best. Feel free to ask any question if you need any help

**Comment by Chaphasilor** [comment]
That looks very promising, thanks! I'll play around with it and see what is possible!

**Comment by bhavyalatha26** [comment]
Hi @eskombro, I have a similar use case , where I need to search terms based on query param and **ignore the typo tolerance**. I tried both the steps mentioned below

- Remove **typo** from the ranking rules 
- Use only **['exactness']** for raking rules.

But none of them helped. I still run into the same issue

I am running the meilisearch server on docker and I also made sure that the server was restarted everytime the rules got updated.

![image](https://user-images.githubusercontent.com/13586777/99875173-91f9cc80-2c13-11eb-87f4-73923ac265e3.png)
![image](https://user-images.githubusercontent.com/13586777/99875179-98884400-2c13-11eb-9255-9831195f756a.png)
 
Am I missing something else here ?

TIA.

Regards,
Bhavya.

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/61-policy-for-prefix-search?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
