### ISSUE TITLE
Search operators

### ISSUE THREAD

**Issue by John-Theo** [meilisearch/MeiliSearch#903]
### Related problem

I want to type in a structured string to perform an advanced search.

### The solution I'd like

e.g. `("text"[field] OR "another phrase"[field]) NOT (bad keywords)`

### Alternatives I've considered

Currently, `faceted search` or `search filters` can meet this request to some extent,  but they are lack of flexibility (~and less cool :fire:~).

### Some resources related to this request

- [Search refinement](https://support.google.com/websearch/answer/2466433) by *Google*
- [ENTREZ](https://www.ncbi.nlm.nih.gov/books/NBK3837/#_EntrezHelp_Entrez_Searching_Options_) by *NCBI*
- [Advanced search examples](https://images.webofknowledge.com/images/help/WOS/hp_advanced_examples.html) by *Web of Science*

**Comment by Kerollmops** [comment]
Hello,

MeiliSearch targets end user search queries and therefore will support this kind of SQL like queries. The  search engine must not be used as a trusted source of data like any other big SQL database.

However thank you for your interrest in our engine,
I which you a good day!
