### ISSUE TITLE
"Pulling" documents for indexing as an alternative to "pushing" 

### ISSUE THREAD

**Issue by rmbagel** [meilisearch/MeiliSearch#904]
**Is your feature request related to a problem? Please describe.**

 I want to index a few thousand documents in Meilisearch. However, I do not want to write a recurring batch or have one-off requests to update / create / delete individual items as time progresses.   

**Describe the solution you'd like**
Meilisearch could perform a GET request to an endpoint every ten minutes, parse the documents from the JSON, and then rebuild a collection, handling all the deletes and updates for me. 

The flow as I imagine it could be be:

1.  Write a JSON endpoint with the correct schema
2. Set up Meilisearch.
3. Point Meilisearch to pull / collect the JSON for a specific collection
4. Let it run.

**Describe alternatives you've considered**
I have not seen how to set up a recurring "pull" for other search-in-a-box solutions. 

**Additional context**
I know that this "pull" model is inefficient past a certain number of documents.
However, I think having this as an alternative would help to reduce the friction (and maintenance) for developers with small datasets.

**Comment by Kerollmops** [comment]
Hello @rmbagel,

I think that could be in fact a good idea for small datasets for sure, but maybe this is not a mainstream feature that everyone would like in MeiliSearch, however there is two solutions for you:
 1. Create a cron job that generates and deletes indexes in the way you described,
 2. wait for us to potentially create a plugon system where you will be able to developpe a plugin that does that.

Thank you for your request 😃

**Comment by qdequele** [comment]
Hello @rmbagel,

We're sorry, but at the moment we're not interested in this kind of feature. If anyone else would also like to see this feature, please leave a comment and ping it. I will then follow up with a discussion. 

Thanks
