### ISSUE TITLE
Finite pagination

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#911]
⚠️ It's not a bug report or a requested feature, but more to explain my problem if we think about implementing pagination in MeiliSearch later 🙂 I discussed that with @MarinPostma, it's more to keep a trace.

I'm currently creating a **finite** pagination in JS, so in front-end, and I did not find any correct way to implement one.
MeiliSearch is indeed perfect to browse through all the documents thanks to `offset` and `limit`.
But I don't have any way to know the total number of results for a query so the total number of pages for my finite pagination.
**I know this is impossible for performance reasons, of course.** 😅

When it will be implemented, I could use `nbHits` and `exhaustiveNumberHits`, but even though, it's not really relevant in my use-case: I indeed need to be sure that the number of hits is _always_ exhaustive, even if MeiliSearch has to set a limit -> [Algolia set it to 1000](https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/) for example.

The Algolia pagination is a little bit different than ours, here are the [API references of the pagination](https://www.algolia.com/doc/api-reference/api-parameters/page/) (the other parameters for paginations are accessible on the left in the sidebar). They know when the user is asking for pagination during a search or not, which makes it easier to apply the limit of 1000 or not and return the exact number of results.

**Comment by gmourier** [comment]
Triage update: This has been specified here https://github.com/meilisearch/specifications/pull/42
