### ISSUE TITLE
Make download of past version easier

### ISSUE THREAD

**Issue by RokZabukovec** [meilisearch/MeiliSearch#913]
**Is your feature request related to a problem? Please describe.**
Now if the user wants to download a past version of meilisearch he needs to search and download it from the GitHub repository.

**Describe the solution you'd like**
It would be useful if the user could specify the version in the download command.

**Comment by curquiza** [comment]
For the moment we want to enforce our users to use the latest version for security and performance reasons. We indeed only maintain only one version, until we are stable (`v1.X.Y`), so this is not something we want in our download script at the moment

Thanks for this suggestion anyway :)
