### ISSUE TITLE
Facets with numbers

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#919]
Currently, the facets do not work with numbers. It would be useful to implement a range slider in front-end, like searching for products in a range of prices.

I need this feature for instant-meilisearch and implement the [rangeSlider component](https://www.algolia.com/doc/api-reference/widgets/range-slider/js/) provided by InstantSearch.js 🙂

**Comment by bidoubiwa** [comment]
Is this not possible with [filters](https://docs.meilisearch.com/guides/advanced_guides/filtering.html#conditions) ?

**Comment by qdequele** [comment]
@curquiza I saw the link you shared. Do you know if the field `precision` is only used on the instant-search plugin on is it sent to the server? How should we handle the `precision`?

**Comment by curquiza** [comment]
> Is this not possible with [filters](https://docs.meilisearch.com/guides/advanced_guides/filtering.html#conditions) ?

Yes, but it would lead to performance issueson big dataset, so I cannot use it for insant-meilisearch.

> @curquiza I saw the link you shared. Do you know if the field `precision` is only used on the instant-search plugin on is it sent to the server? How should we handle the `precision`?

As a first investigation, the `precison` means "only" the search-engine would be able to filter (the `filters` search parameter) with float
```json
price >= 6.99
```

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/79-facets-on-numbers?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.

**Comment by meck93** [comment]
Hi @qdequele do you have the faceting with numbers on the public roadmap? I was unable to find it. Thx for the feedback!

**Comment by curquiza** [comment]
Hello @meck93!
sorry for the lack of communication, we are currently working on a new search engine that would handle this feature! We will keep you informed!

**Comment by meck93** [comment]
Hi @curquiza no problem at all! Thanks a lot for the quick feedback. Looking forward to the v0.21 release! Thanks for your awesome work with Meilisearch!

**Comment by mikhi** [comment]
@curquiza thanks for feedback!
Do you have any time estimation for this release?
Thanks,
Mihai

**Comment by curquiza** [comment]
Hello @mikhi! We are currently working on a completely new search engine improving the performance and also fixing a lot of issues like this one, so giving an ETA is complicated. However, we hope we can release it by the end of June 🙂

**Comment by bradjonesca** [comment]
Are you planning on some kind of alpha/beta release during April?

**Comment by curquiza** [comment]
We already provide alpha in [this repo](https://github.com/meilisearch/transplant/) ⚠️ BUT ⚠️ 
- the search is not completely implemented yet -> the relevancy will not be what you expect
- the `attributesForFaceting` does not behave as in the current MeiliSearch for the moment
=> So I would recommend waiting until a better alpha release so that you can test the facet with numbers. I will inform you when it's ready, you feedback will be really apreciated 🙂

**Comment by bradjonesca** [comment]
Merci beaucoup! We are very excited by this ;)

**Comment by ntraykov** [comment]
You guys are amazing! You cannot imagine how excited I am. Once I replace Algolia with Meilisearch, instead of giving money to Algolia, I will give them for a new machine and a donation to you! This way the circle will close because I am also making a free software and it's users are donating to me. Also, this is a project, I'd love to contribute to. If I can help, please let me know how.

**Comment by nikeee** [comment]
What is the current recommended way for having number or boolean facets? The numbers must not be range-selectable. They are just a "flag" / plain enum value (ranges don't make any sense for them in my case).

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/MeiliSearch/pull/1421

**Comment by mikkpokk** [comment]
Hi @curquiza

Is there specific reason why other than stringable attributes don't work with facet search in 1.3.1 again?

**Comment by Kerollmops** [comment]
Hey @mikkpokk 👋

The main reason is the format of the numbers. JSON allows a lot of ways to store numbers, e.g., `100`, `3e+3`, `0.7e-4`, or `1e2`. It complexifies the search system. We need to understand the user query and convert it into our internal format to search in numbers. We would also like to support typos or even nearest numbers first.

We decided not to support them for the first step of the search in facets, the same for multi-word facet values, i.e. searching `world` will not return the `hello world` facet. Note that we plan to continue the work on this subject in future releases.

Would it be possible to tell us more about your use case [in this product discussion](https://github.com/meilisearch/product/discussions/515), please? Please, next time, answer in the product repository by either finding the appropriate discussion or creating a new one if needed.

Have a nice day 🍹
