### ISSUE TITLE
Add ... during the crop

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#923]
It would be nice that MeiliSearch returns the cropped value with `...` at the end/beginning of the string if the cropped string is not at the beginning/end of the **document field value**.

The `...` could be the default behavior.
The users could change this value by passing a parameter during the search:
```json
"cropEllipsisText": "[...]"
```
or if they want nothing:
```json
"cropEllipsisText": ""
```

Here is the [`SnippetEllipsisText`](https://www.algolia.com/doc/api-reference/api-parameters/snippetEllipsisText/) that Algolia provides. Here are the differences compared to what I suggest:
- the `SnippetEllipsisText` is also settable in the settings (back-end), not only during the search. Not sure this is necessary to complexify our settings until users ask for it.
- the `SnippetEllipsisText` is `""` (empty string = no chars around the cropped string) by default. I'm not sure this is the main usecase. From my POV, when you want a crop in front-end, you want the `...` to easily understand where is the crop. That's why I suggest `...` as default behavior for the crop.

I know the `...` trick is doable in front-end but it's not convenient at all to implement => I wanted to know if it's complex to do in the search-engine part 🙂

**Comment by G-Sheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by qdequele** [comment]
Please check this issue on our [public roadmap](https://roadmap.meilisearch.com/c/69-policy-for-cropped-values?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
