### ISSUE TITLE
Deprecate /health route

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#930]
We are considering deprecating this route. It's original intent was to mark an instance unhealthy for the loadbalancers, but we can't really find a use for it now.

**Comment by eskombro** [comment]
I think it is quite useful for any automated deployment, and it is simple, clear, and straight forward. For example, the sandbox uses it to asynchronously check if the instance has been deployed before activating it for the user. Also, it doesn't seem to add any maintenance workload.

What would we gain by deprecating it?

**Comment by MarinPostma** [comment]
well it seems that you are using it as a dummy route, therefore not for the usage it was meant for. You could use pretty much any route for that purpose. Actually, you are the one setting the health of the server, so it doesn't even notify you on the actual health of the instance.

**Comment by LegendreM** [comment]
an health route is useful in several production environments when you want 100% availability,
in kubernetes, for example, this route may be used:
- at deploy time when you need to know when the previous version can be dropped
- at running time this route is triggered every sec

A good health route:
- NEEDS to ensure that service is completely up if it returns `201`
_ DOES NOT block service process (write transaction)
- NEEDS to use the less network bandwidth as possible when it's triggered
- NEEDS to use the less service resources as possible when it's triggered
- DOES NOT NEED any authentication
- MAY be named `/health`

I don't understand why we should remove it? 😅

**Comment by MarinPostma** [comment]
Thanks for the details @LegendreM. A couple of questions:
- What should be triggering a change in health?
- should this state be persistant?

**Comment by LegendreM** [comment]
I don't see any use of changing healthiness via an http route, `set_healthy` and `set_unhealthy`are useless (for me). 
the `/health` route could just return `201` any time, but if we have a kind of checklist to know if we consider meilisearch up or not, the `/health` route should make the checks and respond depending them.

**Comment by bidoubiwa** [comment]
I discovered that even when you set health to false it still let you use the API normally. Is this something we want it that futur route?

**Comment by LegendreM** [comment]
@bidoubiwa `set_healthy` and `set_unhealthy` should be removed

**Comment by LegendreM** [comment]
related to tracking-issue #940
