### ISSUE TITLE
Sort fields without consistency in lexicographical order

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/MeiliSearch#943]
# Summary

Some fields like:
- `displayedAttributes` in `GET /index/:uid:/settings` and `GET /index/:uid:/settings/displayed-attributes` routes
- `facetsDistribution`  in a search query `/indexes/test/search?facetsDistribution=%5B%22color%22%5D`

are never consitently sorted between same requests.

# Motivations

Same request should respond same results in the same order.

# Implementation

`displayedAttributes` and `facetsDistribution` use the `HashSet` struct which is an unsorted structure, a fast fix should be to sort fields in meilisearch-http  before returning them.

# Related

related to #890 

- [ ] Validated by the team
- [ ] Test added

**Comment by bidoubiwa** [comment]
Are `attributesForFaceting` also impacted by this PR ?

**Comment by curquiza** [comment]
Sorry to think about this now, but I only realize it when using it: isn't it possible to give the same order as the user input? I mean the similar behavior of `searchableAttributes`?
When I push `["id", "title", "author"]` I don't find any convenient to see them in lexicographical order instead of the order I choose.
The motivation is: `Same request should respond same results in the same order.` This same result could be the user oder.

**Comment by eskombro** [comment]
I think the most important part was indeed to make it stable, I don't think the actual order has a real impact IMO

**Comment by curquiza** [comment]
Yes, both solutions are stable (user order or lexicographical), but what I wanted to discuss is the best stable solution.
What do you mean by the actual order @eskombro ?

**Comment by eskombro** [comment]
"the actual order" = "the order itself, which is the order"

What I mean is that it was important for them to be ordered and cosistent, but "how" they are ordered is a matter of preference, and seems very subjective for me to make a decision on it. If you want to modify it I'm ok with that, but I don't think it has an impact on the usage :)

**Comment by MarinPostma** [comment]
This would involve yet another change in the data structure we use, one that would decrease code usability. Unless there is a good, objective reason to do so, we should stick with what we have.

**Comment by curquiza** [comment]
Fixed by the introduction of the new search engine https://github.com/meilisearch/MeiliSearch/pull/1421
