### ISSUE TITLE
facetsDistribution does not take others filters & facets in consideration

### ISSUE THREAD

**Issue by hadjedjvincent** [meilisearch/MeiliSearch#945]
**Describe the bug**

As discussed into #929 , `facetsDistribution` doesn't take into consideration others applied facets.
Let's assume that we have a catalog of Dresses and we are using two facets (Color & Size).

If I select Red & Blue facets, i have all my dresses that have Red **OR** Blue color.
Now, I would want to filter theses dresses by Size, but only for Red **OR** blue colors.

If I provide the right facets while searching (red **OR** blue colors), the facets distribution is unchanged for any others facets than "Color". Meaning that I have all sizes related to the search query, and not the search query + current facets.

**Expected behavior**

`facetsDistribution` should take any previous applied filters or facets.

**Comment by LegendreM** [comment]
Sorry I don't understand your need.

Lets imagine that we sell t-shirts. I have different colors (red, blue, green) and several sizes (S, M, L). the global distribution would be:
- S
  - red: 7
  - blue: 12
  - green: 5
- M
  - red: 17
  - blue: 32
  - green: 15
- L
  - red: 3
  - blue: 1
  - green: 4

now I make several request:

1) `/search?facetFilters=[["color:red", "color:blue"]]` (OR)
2) `/search?facetFilters=["color:red", "color:blue"]` (AND)
3) `/search?facetFilters=["size:S", ["color:red", "color:blue"]]`
4) `/search?facetFilters=["color:red", ["size:M", "size:L"]]`


what would be for you the facet count for each request ? 

thanks for your response :)

**Comment by hadjedjvincent** [comment]
`facetsDistribution` for Size facet should be:
But, we have to take in consideration the primary key of a product, this is just an example, assuming each variant as a different ID here:

case 1:
Red = 7 + 17 + 3 = 27
Blue = 12 + 32 + 1 = 45

S = 7 + 12 = 19
M = 17 + 32 = 49
L = 3 + 1 = 4

case 2 (if we assume that a t-shirt can only have one color):
Red = 0
Blue = 0
S = 0
M = 0
L = 0

case 3:
Red = 7
Blue = 12
S = 7 + 12 = 19
M = 17 + 32 = 49
L = 3 + 1 = 4

case 4:
Red = 20
S = 7
M = 17
L = 3

The goal is to calculate how many documents would be available for each facet, if we apply facetFilters (and filters) on each of them.
Else, this would end to a possible case where you have no results when combining multiple facets (at least by user interaction)

Here is an example of combined facets behaviour: https://preview.algolia.com/instantsearch/index-simplified.html

If you have an available dataset i would be happy to have more consistent data & help you on this 👍

**Comment by LegendreM** [comment]
hello @hadjedjvincent why in your example you always consider all sizes but not all colors (I assume that not distributed fields = 0)? 

Between case 3 and case 4 the same request is made but in one case `right hand facets` ([_, ["color:red", "color:blue"]]) are partially distributed (no green) and in the second case it's `left hand facets`["color:red", _]` which are partially distributed (only red provided).

For me the only way to fit your example is to hardcode `if facet == "color" { partial_distribution() }` 🤔

**Comment by LegendreM** [comment]
hello @hadjedjvincent behind the algolia example there are 4 requests made by the client to retrieve each facets count:
```json
{
  "requests": [
    {
      "indexName": "instant_search",
      "params": "query=&highlightPreTag=__ais-highlight__&highlightPostTag=__%2Fais-highlight__&page=0&maxValuesPerFacet=10&facets=%5B%22type%22%2C%22categories%22%2C%22brand%22%2C%22price%22%5D&tagFilters=&facetFilters=%5B%5B%22categories%3ATV%20%26%20Home%20Theater%22%5D%2C%5B%22brand%3AElite%20Screens%22%2C%22brand%3ARocketfish%E2%84%A2%22%5D%5D"
    },
    {
      "indexName": "instant_search",
      "params": "query=&highlightPreTag=__ais-highlight__&highlightPostTag=__%2Fais-highlight__&page=0&maxValuesPerFacet=10&hitsPerPage=1&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&analytics=false&clickAnalytics=false&facets=categories&facetFilters=%5B%5B%22brand%3AElite%20Screens%22%2C%22brand%3ARocketfish%E2%84%A2%22%5D%5D"
    },
    {
      "indexName": "instant_search",
      "params": "query=&highlightPreTag=__ais-highlight__&highlightPostTag=__%2Fais-highlight__&page=0&maxValuesPerFacet=10&hitsPerPage=1&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&analytics=false&clickAnalytics=false&facets=brand&facetFilters=%5B%5B%22categories%3ATV%20%26%20Home%20Theater%22%5D%5D"
    },
    {
      "indexName": "instant_search",
      "params": "query=&highlightPreTag=__ais-highlight__&highlightPostTag=__%2Fais-highlight__&page=0&maxValuesPerFacet=10&hitsPerPage=1&attributesToRetrieve=%5B%5D&attributesToHighlight=%5B%5D&attributesToSnippet=%5B%5D&tagFilters=&analytics=false&clickAnalytics=false&facets=price&facetFilters=%5B%5B%22categories%3ATV%20%26%20Home%20Theater%22%5D%2C%5B%22brand%3AElite%20Screens%22%2C%22brand%3ARocketfish%E2%84%A2%22%5D%5D"
    }
  ]
}
```

**Comment by MarinPostma** [comment]
After careful consideration, we decided to revert #944 in order to allow the behavior defined above.
