### ISSUE TITLE
"Words" ranking rule

### ISSUE THREAD

**Issue by mzperix** [meilisearch/MeiliSearch#948]
Currently it is a problem that many searches end up with very short result list (or even empty) because of over-specified user queries. (Context: I am testing our search logs against meilisearch results, current search engine shows results with partial matches also but meilisearch doesn't which leads to meilisearch not showing correct results that the users previously have clicked).

[Documentation has a "soon" tag on this feature.](https://docs.meilisearch.com/guides/main_concepts/relevancy.html#ranking-rules)

It would be great to show results with not all query terms matched.

**Comment by LegendreM** [comment]
Hello @mzperix,

as you can see we plan to develop it, there is no due date for the moment.

It should be released before 2021
