### ISSUE TITLE
Typo tolerance on synonyms

### ISSUE THREAD

**Issue by mzperix** [meilisearch/MeiliSearch#949]
Synonyms are great but if there is a typo in the query for the synonym, it is not matched like it is when the original word has typo error.

While this may lead to unwanted symmetric relationship in some cases (like the one in the documentation with phone => iphone), if the synonym matching is lower ranked anyway, this should not be problem in my opinion.

**Comment by LegendreM** [comment]
Hello @mzperix,

Could you please give us an example, we are not sure about the current and expected behavior?

**Comment by mzperix** [comment]
Hello @LegendreM,

Sticking to the example in the docs, suppose I have these docs:

{name: Samsung, type: phone}
{name: iPhone, type: phone}
{name: iPhone case, type: accessory}

synonyms: phone => iphone

Then for these queries:

- phone: get all three
- phoen: get only first two (not all three!) -- typo tolerance recognizes phone in the type field, but the synonym is not triggered

Having all three results in the second case would be a better use for the synonyms in my opinion. (This way a fallback is if I add a lot of mistyped synonym associations)

Same goes for searching "phon", the first two results are shown because of matching the first part of the type field but not the synonyms.

I hope this clarifies, let me know if you need anything else.

**Comment by LegendreM** [comment]
Understood @mzperix thanks for the explanation!
your feature is interesting and could be useful,

BUT this feature could impact search performances, for example: 
if you have synonyms:
peck => [bite, nip, strike, hit, tap, rap, jab, poke, prick]
pack => [packet, container, package, box, crate, carton, parcel, group, herd, troop]
dock => [harbour, marina, waterfront, port, anchorage, wharf, quay, pier, jetty, landing stage, dockyard, boatyard, hithe, moorage, harbourage]

and your query is `pock` you'll have lot of alternatives to your query word on only 1 word, without counting prefix search results.

I think we need to discuss this feature with the @meilisearch/core-team .

**Comment by Kerollmops** [comment]
Hey @mzperix,

We deliberate and we concluded that it would be too much work for the engine in term of performance to consider every single word even with typos as any alternative to every matching word. The other argument is that if there is too much synonyms matching the end results will be incomprehensible as too much alternative words matches in the dataset.

Thank you for your request :)
