### ISSUE TITLE
Cyrillic support?

### ISSUE THREAD

**Issue by JohnatanNorman** [meilisearch/MeiliSearch#950]
**Is your feature request related to a problem? Please describe.**
First of all, I wanted to say thank you, for this incredible search-engine. I am looking forward to be using it, but I have one problem: while most of my projects are using Latin-based languages, I would've loved to have Cyrillic support for this awesome engine.

**Describe the solution you'd like**
I didn't see Cyrillic support mentioned in any of the milestones (and anywhere in issues too), but I think since you are aiming to be go-to solution for **all** the devs it would be really nice to have Cyrillic support.

**Additional context**
Both Algolia and Elastic allow you to use Cyrillic languages, but Algolia is expensive for many countries that would use Cyrillic languages (mostly slavic ones), and Elastic is overkill almost every time, which is why I think it would be perfect if engine like yours would step in.

**Comment by qdequele** [comment]
Hello Johnatan, did you tried the tokenizer we already have? Or did you ask because you didn't talk about the Cyrilic language support?

**Comment by JohnatanNorman** [comment]
Hi, @qdequele, thanks for the reply! I'll try your tokenizer and get back to you. If it will work, I think it'll make sense to update the docs, so they won't scare anyone, who would want to use your search-engine for their Cyrillic projects.

**Comment by Kerollmops** [comment]
I close this issue, feel free to open it if needed.
