### ISSUE TITLE
WebSocket Streams for (near) **Real-Time** data access.

### ISSUE THREAD

**Issue by Fefke** [meilisearch/MeiliSearch#951]
**Is your feature request related to a problem? Please describe.**
Not an practical problem, but an theoretical in order to reach the "real-time" requirement.

**Describe the solution you'd like**
To handle data-streams from user-/ or backend-side it would be nice to implement an WSS (WebSocket Stream)
feature, that allows an data-flow in and out of the DBMS and up to the user/ another machine.
It could cut some overhead off the normal HTTP-Requests and improve the Time until the user 
or (most importantly) an another machine (like a service - like Spotify) see's the content.

**Describe alternatives you've considered**
I think there are currently no other options to allow data-streams in the <WebDeveloper world>.

**Additional context**
It would give you an another feature that could help the developer-teams out there,
deciding to use MeiliSearch over Elasticsearch - because they don't have WSS implemented yet.

So it would be an 🚀 for marketing too.

**Comment by qdequele** [comment]
Hello, it's super interesting, unfortunately it's a lot of work for little performance gain. For the moment the optimization at this level is not yet in our priorities. However the idea is really interesting and we keep it in mind.
