### ISSUE TITLE
Movies.json not public available

### ISSUE THREAD

**Issue by Skillkiller** [meilisearch/MeiliSearch#953]
**Describe the bug**
Hello,
The readme file contains a Movies.json which is no longer publicly available. Notion blocks the access to the file. Therefore the curl command below in the readme file is no longer valid.  
**To Reproduce**
1. Open README.md
2. Scroll to "Create an Index and Upload Some Documents"
3. Click on "this movie database" **OR** Use the curl download command

**Expected behavior**
Preview of the file or direct download

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18444809/92274187-0c586180-eeed-11ea-97d5-bd30a618ae1c.png)

**Comment by MarinPostma** [comment]
Thank you for finding this one out :)

**Comment by qdequele** [comment]
Hello @Skillkiller, sorry for the disappointment, the link is back online. Thanks for the report.

**Comment by bidoubiwa** [comment]
It should be updated with the new movies.json that has the genre field.
