### ISSUE TITLE
Highlighting doesn't work if HTML tag precedes word already

### ISSUE THREAD

**Issue by huzaifahj** [meilisearch/MeiliSearch#955]
**Describe the bug**
If there is a HTML tag before (only before) the search query word, <em> tags are not placed around the word and I'm not sure if it even recognises the word when searching.

**To Reproduce**
1. Attribute value is `<p>test hello</p>`
2. Search query word is `test`
3. Under _formatted value is INCORRECTLY `<p>test hello</p>`
4. Search query word is `hello`
5. Under _formatted value is CORRECTLY `<p>test <em>hello</em></p>`

**Expected behavior**
Under _formatted value is `<p><em>test</em> hello</p>`

Thanks for your time.

UPDATE: the `test` search query word is not even found at all if there are tags before it (0 hits)

**Comment by MarinPostma** [comment]
Hello @huzaifahj,
this appears to be a tokenizer bug, my guess is that it is not able to correctly split `<p>` and `test`. Thank you for reporting the issue!

**Comment by huzaifahj** [comment]
![image](https://user-images.githubusercontent.com/52999758/92300527-7e639180-ef53-11ea-9e30-40d2dd7ac3d1.png)

Think you're right, it does!

**Comment by MarinPostma** [comment]
thanks! we'll work on this :)

**Comment by huzaifahj** [comment]
Thanks for your time on this.

**Comment by qdequele** [comment]
The tracking issue for that is https://github.com/meilisearch/MeiliSearch/issues/624

**Comment by vird** [comment]
There is also another issue with contents with html tags. Is there any way I can get

    &lt;p&gt;test <em>hello</em>&lt;/p&gt;
instead of

    <p>test <em>hello</em></p>

Reason:
I want put this into existing html and I want to be sure that I didn't inject any invalid HTML or don't have any XSS if attacker can control indexed contents

**Comment by gmourier** [comment]
Closed in favor of the https://github.com/meilisearch/product/discussions/119 discussion.
