### ISSUE TITLE
Incorrect highlighting 

### ISSUE THREAD

**Issue by appa1303** [meilisearch/MeiliSearch#956]
When using Unicode language (e.g. Cyrillic, Hebrew or Arabic) highlighting is not calculated correctly

1. create a new index, with a text field
2. fill the text with "גלידת ווניל"
2. using the web UI of meilisearch, search for "גלידת"
3. the highlight is not calculated correctly
See the JSON (I have marked the fields bold):
{
    "hits": [{
            "id": "2",
            "name": "גלידת ווניל",
            "desc": "vanilla icecream",
            "_formatted": {
                "id": "2",
                **"name": "\<em\>גלידת ווני\</em\>ל",**
                "desc": "vanilla icecream"
            }
         ...
    "processingTimeMs": 1,
    **"query": "גלידת"**
}
 
![image](https://user-images.githubusercontent.com/12508835/92325058-37a79180-f050-11ea-8cf5-4efaec1808ce.png)

and another image with Cyrillic 
I used this text "ӰӂӃӄӅӆ"  

![image](https://user-images.githubusercontent.com/12508835/92325199-5bb7a280-f051-11ea-8865-41de574695ae.png)

**Comment by LegendreM** [comment]
Hello @appa1303, thanks for your report,
it's a known issue, I link it to #894 and #790

**Comment by qdequele** [comment]
The tracking issue for that is https://github.com/meilisearch/MeiliSearch/issues/624
