### ISSUE TITLE
Aggregate capability

### ISSUE THREAD

**Issue by frank-io** [meilisearch/MeiliSearch#957]
Hi there,

I'm new to Meilisearch and looking at the documentation. 

Not sure if this is a proper place to ask ... But anyway, I haven't found much information about aggregations (similar to `agg` in Elasticsearch) for Meilisearch in either this repo or the documentation. Could anyone advise me how does Meilisearch query with aggregations or point me to the aggregation chapter of Meilisearch.

Cheers
Frank

**Comment by bidoubiwa** [comment]
Hello @frank-io 
What we have closest to this are [facets and facetsDistribution](https://docs.meilisearch.com/guides/advanced_guides/faceted_search.html). This is also the name that [elasticSearch used to give to the aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-facets.html).

Good luck!

**Comment by frank-io** [comment]
Awesome! Thanks @curquiza @bidoubiwa
