### ISSUE TITLE
Running in the background with Supervisor

### ISSUE THREAD

**Issue by Cannonb4ll** [meilisearch/MeiliSearch#961]
So I've created a simple script to run MeiliSearch with which is installed via APT, the script looks like this:

*meilisearch-service.sh*
```sh
#!/bin/bash

export MEILI_DB_PATH=~/data.ms
export MEILI_HTTP_ADDR=127.0.0.1:7700
export MEILI_MASTER_KEY=mymasterkey
export MEILI_ENV=production

meilisearch
```

If I run this script manually it is all fine, when I run it with supervisor, it is also fine, however, when I stop or remove the supervisor config and reload, there's still a process running for some reason in the background.

*Supervisor configuration*
```
[program:worker-32]
command=/home/user/meilisearch-service.sh
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
user=user
redirect_stderr=true
numprocs=1
```

`ps aux` output after creating the supervisor config and daemon:

```
user     26830  0.0  0.3  23712  3452 ?        S    18:10   0:00 /bin/bash /home/user/meilisearch-service.sh
user     26831  0.0  1.3 210194348 13304 ?     Sl   18:10   0:00 meilisearch
user     26840  0.0  0.1  14740  1096 pts/0    S+   18:10   0:00 grep --color=auto meili
```

As you can see, there's 2 services present, once I remove the script service and reload supervisor, this is the output:

```
user     26831  0.0  1.3 210194348 13304 ?     Sl   18:10   0:00 meilisearch
user     26928  0.0  0.1  14740  1012 pts/0    S+   18:11   0:00 grep --color=auto meili
```

For some reason, there's still a single process running of meilisearch which is causing problems. I am not logged in more than once, there's no other users logged into the server that's running the command. (I've also tested by using `kill` to kill that process and then spawn a new supervisor daemon, same issue replicates)

Is this not the way to configure meilisearch to be ran?

**Comment by eskombro** [comment]
Hi @Cannonb4ll 

isn't this related to your `autorestart` policy?

```
autorestart

    Specifies if supervisord should automatically restart a process if it exits when it is in the RUNNING state. May be one of false, unexpected, or true. If false, the process will not be autorestarted. If unexpected, the process will be restarted when the program exits with an exit code that is not one of the exit codes associated with this process’ configuration (see exitcodes). If true, the process will be unconditionally restarted when it exits, without regard to its exit code.
```

What command are you using to stop th supervisor service?
