### ISSUE TITLE
Question: smart datetime search

### ISSUE THREAD

**Issue by SirWindfield** [meilisearch/MeiliSearch#962]
Is it somehow possible to build an index that allows one to search by datetime efficiently? I'm thinking of ranges, specific dates and times like a year, a weekday or something similar.

Even more useful for my case would be search functionality like "last week" or "two days ago".

I took a closer look at the project and it seems that this is not supported right now nor does it actually seem to fit with the current vision of the project.

If you, however, have ideas on how I could realize this using this project, let me know!

**Comment by MarinPostma** [comment]
this could be sugar on top of range facets (#919), after all this could be desugared into timestamps

**Comment by Kerollmops** [comment]
Hey @SirWindfield,

It is a good idea but it should be handled by the front-end apps as it will lighten the core engine.
