### ISSUE TITLE
Use in-process?

### ISSUE THREAD

**Issue by kristiandupont** [meilisearch/MeiliSearch#965]
I am wondering if it's possible to use MeiliSearch as a statically linked library that runs in-process? I would like to release a single binary, built in Rust, that basically exposes an alternative (more specialized) version of the web server that comes with the current binary, plus a few other things.

The Rust SDK accesses an external process, and I can't find any hints that this is possible.

**Comment by LegendreM** [comment]
Hello @kristiandupont, we are currently working on an independent rust library but for now you can't use meilisearch as a rust library.

**Comment by Kerollmops** [comment]
Hey @kristiandupont,

Could you provide more information on waht you would like to expose with your HTTP front-end?
It will help us know what we will need to expose with the next Rust library we are working on.

Thank you very much :)

**Comment by kristiandupont** [comment]
Sounds good!
I am making a tiny app that uses Meilisearch for indexing source code on my hard drive. I have a little web frontend for it and will make a vscode extension as well. So in terms of indexing, it currently scans raw text but I imagine I will introduce a parsing stage to get better results. As for the frontend, it's similar to the one built into Meilisearch except it doesn't show a dropdown for which index to search, and the results feature syntax highlighting etc.

It works for me at the moment, but I would like to be able to distribute it easily and having a single process, single executable would help quite a lot in that regard.

**Comment by Kerollmops** [comment]
Closing because it will be done in the future.
