### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by olimart** [meilisearch/MeiliSearch#969]
**Describe the bug**

Cannot install Meilisearch on a Raspberry Pi (4)

**To Reproduce**

**From Source** 

this step fails `$ cargo build --release`

**From APT**

This step `apt update && apt install meilisearch-http`
returns package not found `meilisearch-http`

**Expected behavior**

It should let me install Meilisearch on Raspbian Lite

**Desktop (please complete the following information):**
 - OS: Raspbian Lite

**Comment by zaherg** [comment]
If I am not mistaken you will have to download the binary file and use it (if you are using docker you can use my image https://github.com/users/zaherg/packages/container/package/meilisearch ).

you can download the binary from the releases page https://github.com/meilisearch/MeiliSearch/releases and download the `armv8` file

**Comment by olimart** [comment]
yeah, I should have mentioned that I'd rather not use Docker if possible

the installer script returns something along "platform not supported"

Once the `armv8` binary is downloaded, what's the next step?
Launch? `./meilisearch-linux-armv8` ?

**Comment by zaherg** [comment]
@olimart do you use 32bit or 64bit? 

if the installer says the platform is not supported, so mostly even if you downloaded the binary it wont work, but you wont lost anything from trying

once you downloaded the file you need to change the permission

```bash
mv meilisearch-linux-armv8 meilisearch
chmod u+x meilisearch
```
then run it

```bash
./meilisearch
```

**Comment by Kerollmops** [comment]
Hey @olimart and @zaherg,

Were you able to make it work on your rapsberry pi? Thank you @zaherg for your precious time :)

Thank you for your interrest in the project

**Comment by olimart** [comment]
Nope.
I'm getting `-bash: ./meilisearch: cannot execute binary file: Exec format error`
Any idea?

**Comment by olimart** [comment]
@zaherg Any suggestion I could try over the weekend?

**Comment by zaherg** [comment]
@olimart you need to provide more information about your PI , is it 64 or 32b, the OS, the model .. etc.

**Comment by olimart** [comment]
Raspberry Pi 4 64bit with Raspbian Lite

**Comment by zaherg** [comment]
@olimart the beta version?

**Comment by zaherg** [comment]
I can confirm it is working on PI4 64bit (Beta version) Raspberry OS

![image](https://user-images.githubusercontent.com/27624/94984563-f1155c00-0555-11eb-8c01-5a5f15538401.png)


@olimart I guess you are using 32bit OS that's why it is not working at your end. You need to know that even if you are using PI4 which is 64bit your OS should be 64bit too to work, Raspbian lite is 32bit not 64bit.

to download the 64bit of RaspberryOS you can get it from https://www.raspberrypi.org/forums/viewtopic.php?f=117&t=275370

**Comment by olimart** [comment]
Raspberry Pi OS Lite 32 bit released 20020-08-20

**Comment by olimart** [comment]
> I guess you are using 32bit OS that's why it is not working at your end. You need to know that even if you are using PI4 which is 64bit your OS should be 64bit too to work, Raspbian lite is 32bit not 64bit.

Indeed. Just noticed when checking for the version number.
Looks like I need to reinstall. Thanks for pointing out.

**Comment by olimart** [comment]
Working fine on 32bit.
Is the `armv8 binary` 64bit only?

**Comment by zaherg** [comment]
From what I know yes, V8 is 64bit only

**Comment by olimart** [comment]
Thanks for your help @zaherg 🙏
