### ISSUE TITLE
Is it possible to connect a search engine to https://docusaurus.io/?

### ISSUE THREAD

**Issue by nikolasj** [meilisearch/MeiliSearch#970]
I would like a description of the possibility of adding a search to https://docusaurus.io/

**Comment by eskombro** [comment]
Indeed it would be possible, and great!

We provide a few tools for this. Especially the [Docs search bar](https://github.com/meilisearch/docs-searchbar.js), a customizable [docs scrapper](https://github.com/meilisearch/docs-scraper), and front-end tools like [instant-meilisearch](https://github.com/meilisearch/instant-meilisearch).

Those tools are also provided to complement, of course several SDK's as, for your example, [MeiliSearch JS](https://github.com/meilisearch/meilisearch-js) (for fornt and back end purposes)

If you have already integrated Algolia (as I see you have) the transition won't be painful at all, mostly straigth forward. Do not hesitate to check our [Documentation](https://docs.meilisearch.com/)
