### ISSUE TITLE
Allow filters search for null values

### ISSUE THREAD

**Issue by Skillkiller** [meilisearch/MeiliSearch#972]
**Is your feature request related to a problem? Please describe.**
For my project I need the possibility to filter for zero fields. This is currently not possible. If I pass "field = null" as filter, the search is done for a string with the value null. At the moment I get all documents from Meili and filter again with an extra backend over it which is completely disproportionate from a performance point of view.

**Describe the solution you'd like**
The solution is to allow searching for zero values in filters. If you want to search for a string with null you can still put it in ''.

Example what should be allowed: 
Request Body: 
```
{
    "filters": "company != zero"
}
```
or
```
{
    "filters": "company = zero"
}
```
**Describe alternatives you've considered**
An alternative would be to allow this in a Faceted Search.

**Additional context**

**Comment by Kerollmops** [comment]
Hey @Skillkiller,

As I understand what you want is something like "Give me all the documents that doesn't contain any company"?
If this is the case there is maybe an alternative way where you can just create a dummy company name (e.g. "company = null") and filter by that dummy value. By the way it is always better, because faster, to use facets than filter.

Would it be possible to know your specific use case?

Thank you!

**Comment by Skillkiller** [comment]
Sorry for my late answer. I tested your suggestion with the dummy value for a Faceted Search. The whole thing goes so far.
This dummy value now appears in the search because the company attribute must be searchable.

My special case is that I want to display all documents if the company is not set. But with the search it should also be possible to search for a document based on the company.

Your workaround works perfectly for me. Thanks for suggesting it and I'm surprised that I didn't come up with something as simple as this.

The question if it should be possible to do a faceted search with a null value in one of the next versions or meilisearch.

**Comment by LegendreM** [comment]
Hello @Skillkiller,
I'm happy that our suggestion fits your need 🛠

about your last question:
`The question if it should be possible to do a faceted search with a null value in one of the next versions of meilisearch.`

We don't plan to do it.

Thank you for your interrest in the project,
and don't hesitate to open new issues to suggest new features or to ask help!

**Comment by ahmednfwela** [comment]
UPDATE: there is a PR for it now https://github.com/meilisearch/meilisearch/pull/3571
