### ISSUE TITLE
Please return indication to the quality of each result

### ISSUE THREAD

**Issue by appa1303** [meilisearch/MeiliSearch#973]
Hi, 
Is it possible that to provide the score for each result ?
Something like 0 for "exact match" ...  to 1 for "sparse words with spelling typos".
It will be useful to give the end user some indication of each result quality.

Thanks

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/78-get-ranking-information?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
