### ISSUE TITLE
Distributed index processing

### ISSUE THREAD

**Issue by MCOfficer** [meilisearch/MeiliSearch#974]
**Is your feature request related to a problem? Please describe.**
Indexing as of now is pretty slow on cheap hardware, at least if you have millions of links.  Apparently [it's being worked on](https://github.com/meilisearch/MeiliSearch/discussions/872#discussioncomment-39994), but there's always room for improvement :wink: 

**Describe the solution you'd like**
Create an API that allows clients to log in and lend processing power to the indexing process. Specifically: The client requests a batch of unprocessed documents, the server sends the batch and then waits for the client to upload the finished batch.

Case example: My project runs on a cheap server that only just indexed 1M links (out of 50M, with more to come). Me and a contributor would like to use our desktops for indexing, but the only way to do so is by stopping the indexing, downloading the DB and starting Meilisearch locally, then uploading the DB again, which only one of us can do at a time.

**Describe alternatives you've considered**
#410 could work - We could run Meilisearch on other machines just for indexing purposes, they don't need to answer any requests. The comment mentioning https://github.com/tikv/tikv is also interesting.

**Comment by Kerollmops** [comment]
Hey @MCOfficer,

I think this is not the intended use case of MeiliSearch, but maybe you can use the snapshots to do that. Maybe you can use a bigger machine to do the indexing. Note that the indexing process is improving a lot and you will maybe be able to index this massive number of documents on your cheap server, in the next version of the engine.

Thank you anyway for the feedback.

**Comment by MCOfficer** [comment]
This was to be expected, but it can't hurt to ask. I will look into snapshots, and i'm eagerly awaiting  the indexing overhaul ;)
