### ISSUE TITLE
Typo on multiple words query does not work

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#981]
**Describe the bug**
We used to be able to make typos on one of the words in a multiple words query. Now when I make the same typo I get 0 results.

<img width="1292" alt="Screenshot 2020-09-29 at 11 16 17" src="https://user-images.githubusercontent.com/33010418/94539589-b6ee4680-0245-11eb-9d8c-51f8fa79a5ee.png">

**To Reproduce**

1. Index movie dataset
2. search on Leonard Chelby
3. 0 results

**Expected behavior**
I expected the same results as on the gif we display

**Screenshots**

<img width="912" alt="Screenshot 2020-09-29 at 11 18 02" src="https://user-images.githubusercontent.com/33010418/94539548-a5a53a00-0245-11eb-8c08-bfd9903dec12.png">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser chrome

**Comment by MarinPostma** [comment]
I always thought that we didn't support typos on the first letter of a word, or do they count as 2 typos? @Kerollmops

**Comment by Kerollmops** [comment]
We don't support typos on the first letter for performance reason, yeah. Maybe this isn't documented?

**Comment by bidoubiwa** [comment]
Apparently this feature was present in MeiliSearch for about two weeks around one year ago. Unfortunately it was a that time that I made the movie gif that we use a lot. 

Changing this gif becomes a high priority as it does not reflect reality.

**Comment by qdequele** [comment]
Could we close this one and recreate one about typos on the first letter of a word?
