### ISSUE TITLE
Renaming backup to dump

### ISSUE THREAD

**Issue by tpayet** [meilisearch/MeiliSearch#983]
**Is your feature request related to a problem? Please describe.**
When someone think about Backup, we often think about automated snapshots that will allow to restart the binary from a fresh state that was saved some time before.

What MeiliSearch provides under the name of backup is very similar to SQL dump, it is a data export that can be done anytime (but not automatically or regularly) to reimport it into a different version of MeiliSearch. This manoeuver should be done in exceptionnal cases when the user change MeiliSearch version. It should not be automated for backups because you will have to reindex data.

**Describe the solution you'd like**
Rename backup to dump. And talk about backuping MeiliSearch in the documentation relative to the snapshots

**Describe alternatives you've considered**
Maybe rename snapshot to backups but that is not necessary. When searching for backups on the documentation we should fallback on snapshots. 

**Additional context**
- [Description of SQL dump on PostgreSQL documentation](https://www.postgresql.org/docs/9.1/backup-dump.html)
- [Description of backup on PostgreSQL documentation similar to what we call snapshot](https://www.postgresql.org/docs/9.1/backup-file.html)
- [Elasticsearch documentation on snapshots](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-restore.html)

**Comment by LegendreM** [comment]
I rename it so, @bidoubiwa we'll need to change some things in documentation 😏

**Comment by LegendreM** [comment]
closed by #982
