### ISSUE TITLE
`&` Breaks Search on Dashboard

### ISSUE THREAD

**Issue by jcohlmeyer** [meilisearch/MeiliSearch#986]
**Describe the bug**
When entering a search in the provided MeiliSearch dashboard the search is broken, returning a 400 error as the `&` breaks the search request URL. This is because the search string is not URL encoded using `encodeURIComponent(search.value)`.

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the MeiliSearch dashboard: http://localhost:7700
2. Enter a search with an ampersand (`&`) in it.
3. See the search does not complete and a 400 error is returned in the network tab

**Expected behaviour**
A search with an ampersand should work and the & should be URL encoded.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2)
 - Browser Firefox
 - Version 82.0b4 (64-bit)

**Comment by qdequele** [comment]
Thanks @jcohlmeyer, as it is a simple issue, why not letting the hacktoberfest participants fix it? 😉
