### ISSUE TITLE
Dumps status are not consistent

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#991]
**Is your feature request related to a problem? Please describe.**
When using the dump status route `GET /dumps/dumps_uid/status` the returned status may be one of the following:
- `processing`
- `dump_process_failed`
- `done`

One of them gives context, the two others not. 

**Describe the solution you'd like**
I would like them to be consistent in their information

**Describe alternatives you've considered**

### Option A ❤️
- `processing`
- `failed`
- `done`

### Option B  👍 
- `dump_is_processing`
- `dump_process_failed`
- `dump_is_done`

### Option C 👀
No changes

----

Please vote with the emojis or make any suggestions or comments.

**Comment by LegendreM** [comment]
`dump_process_failed` is prefixed because it's linked to a global error in documentation: errors/#meilisearch-errors
so the option A is not really possible

**Comment by bidoubiwa** [comment]
I don't think it should not be the global error code. We should find another way of communicating the error code when a async process fails. For example in the update route : `/indexes/:index/updates` failing processes are displayed this way: 
```
{
  "status": "failed",
  "updateId": 3,
  "type": {
    "name": "DocumentsAddition",
    "number": 1
  },
  "error": "document id is missing",
  "duration": 0.000048524,
  "enqueuedAt": "2019-12-07T20:23:50.156433207Z",
  "processedAt": "2019-12-07T20:23:50.157436246Z"
}
```
The error_code is clearly missing but the `status` is still only `failed`.

In an automatic environment there will be a condition looking for a failed status, if the status can be one of a multitude of possible error codes, checking for an error will become tedious
```javascript
if ( ["dump_process_failed", "dump_already_in_progress", "other_error"].includes(update.status)){
    throw "An error occured during dump creation"
}
```

Instead of the following 
```javascript
if ( update.status == "failed"){
    throw `${update.errorCode}: ${update.message} ${update.errorLink} ` 
}
```

**Comment by eskombro** [comment]
It is true that the status and the error code are not the same, and it would be easy to use consistent status like 'failed', 'enqueued', and 'processed'
