### ISSUE TITLE
Add a crop-length index setting

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#992]
**Is your feature request related to a problem? Please describe.**

 It is currently not possible to set the global crop-length for an index.

**Describe the solution you'd like**

Add a setting to do that in the settings of the index.

**Comment by eskombro** [comment]
Would it apply to every field unless you overwrite that value in your search request? Or you qould be able to specify also the attributes to crop?

I like it :)

**Comment by qdequele** [comment]
Hello,

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/69-policy-for-cropped-values?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
