### ISSUE TITLE
search_benchmark is broken

### ISSUE THREAD

**Issue by neeldug** [meilisearch/MeiliSearch#994]
**Describe the bug**
The MeiliSearch Core `search_benchmark` is broken, this is easily fixed [here](https://github.com/meilisearch/MeiliSearch/blob/b406b6ee44353812314877ebabd30dc54492a70f/meilisearch-core/benches/search_benchmark.rs#L101), by dereferencing and forcing it into an Option, 

**To Reproduce**
```
cargo bench -p meilisearch-core
```

**Expected behavior**
The benchmark to run correctly

**Additional context**
Also, the benchmarking setup doesn't currently take advantage of criterion's black_box function, which allows for better benchmarking of software, I can create these changes in another PR rather than here!

**Comment by LegendreM** [comment]
Hey @neeldug thx for your report 👍
