### ISSUE TITLE
Should there be a route to find dumps uid?

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#996]
**Describe the bug**
As of today when launching a dump creation process using the following route `POST /dumps/` MeiliSearch returns a `dumps_uid`. This `uid` helps the user track the dump creation process using the dump status route `GET /dumps/:dumps_uid/status`.

If the user **did not save** the `dumps_uid` he will not be able to recover it as there is no `GET /dumps/` route which could inform about the previous dumps creation.

The only solution is to go directly into the dump folder and look at the dump name. But this only works when the process succeeded.

**To Reproduce**
1. use `POST /dumps` without saving the `dumps_uid`
2. Not able to recover the `dumps_uid`

**Expected behavior**
There should be a `GET /dumps/` route that gives you the history of dump creation and helps you recover any dump_uid.

**Comment by LegendreM** [comment]
Not for now, I think this route is relevant if you have a full http interface with upload, download... Which is not the case. Today's backup needs to have access to the file system to use them so the only way to have the backup list is to check the directory where backups are.

**Comment by qdequele** [comment]
Hello, 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/66-download-dumps?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to upvote it on the roadmap.
