### ISSUE TITLE
Add processing time and date to dumps status

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#999]
**Is your feature request related to a problem? Please describe.**
For the moment the dump status looks like this
```json
{
   "uid": 123,
   "status": "done"
}
```

There is missing information on how much time a dump is made. Information that could be relevant when adding the dump in a scheduled task.

**Describe the solution you'd like**

We should also add the following: `createdAt`, `processedAt`, `duration`.

With the same idea as the update body:
```json
{
  "status": "processed",
  "updateId": 1,
  //...
  "duration": 12.757581815,
  "enqueuedAt": "2019-12-07T21:10:07.607581330Z",
  "processedAt": "2019-12-07T21:10:20.511525620Z"
}
```

**Comment by CreaTorAleXander** [comment]
Hey, I would like to do this can I get some more informations?

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
